force-app/main/default/objects/OCR_Settings__c/OCR_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Opportunity Contact Role set up data</description>
    <label>CRM : OCR : Settings</label>
</CustomObject>

force-app/main/default/objects/OCR_Settings__c/fields/OCR_Msg__c.field-meta.xml
<CustomField>
    <fullName>OCR_Msg__c</fullName>
    <description>Message to be shown when there is no Primary Contact and Role set with the Opportunity</description>
    <inlineHelpText>Message to be shown when there is no Primary Contact and Role set with the Opportunity</inlineHelpText>
    <label>OCR_Msg</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DR_Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>DR_Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SDS-1740-Remove field filter from Primary Customer Contact field on the Opportunity such that someone can pick any contact from the db</description>
    <inlineHelpText>This field must contain the Primary Contact involved with this opportunity</inlineHelpText>
    <label>Primary Customer Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Customer Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Role__c</fullName>
    <inlineHelpText>Select the role that best describes the Primary Customer Contact above.  This field must be populated when a Primary Customer Contact is identified.</inlineHelpText>
    <label>Primary Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Contact</fullName>
                <default>true</default>
                <label>Sales Contact</label>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Influencer/Buyer</fullName>
            </value>
            <value>
                <fullName>Solution Architect/IT</fullName>
            </value>
            <value>
                <fullName>Renewal Contact</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CRM_OPP_ContactRole_Banner_cls.cls
/*
	2016.08.30 - pjena
	Controller class for CRM_OPP_ContactRole_Banner vf to show banner in the Opportunity record if there is no DR_Customer_Contact__c and Primary_Contact_Role__c

*/
public class CRM_OPP_ContactRole_Banner_cls {
    public boolean showMessage{get;set;}
    public string message{get;set;}
    
    public CRM_OPP_ContactRole_Banner_cls(ApexPages.StandardController sc){
    	Id recordId = sc.getId();
    	
    	if (recordId != null){
    		 
    		 list<Opportunity> lstOpps = [Select DR_Customer_Contact__c, Primary_Contact_Role__c 
    		 						From Opportunity 
    		 						Where Id = :recordId 
    		 							And (DR_Customer_Contact__c != null And Primary_Contact_Role__c != null)];
    		 
    		 if (lstOpps.isEmpty()){
    		 	showMessage = true;
    		 	message = OCR_Settings__c.getOrgDefaults().OCR_Msg__c;
    		 }
    	}
    }
}