force-app/main/default/objects/Service_Cloud_Settings__mdt/Service_Cloud_Settings__mdt.object-meta.xml
<CustomObject>
    <label>Service Cloud: Settings</label>
    <pluralLabel>Service Cloud: Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Service_Cloud_Settings__mdt/fields/Agent_Profile_Names__c.field-meta.xml
<CustomField>
    <fullName>Agent_Profile_Names__c</fullName>
    <defaultValue>&apos;Service Cloud Generic User&apos;</defaultValue>
    <description>This field value is used as constant to identify Service Cloud Agent profiles.</description>
    <label>Agent Profile Names</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Cloud_Settings__mdt/fields/Case_Team_Roles_Design_Win__c.field-meta.xml
<CustomField>
    <fullName>Case_Team_Roles_Design_Win__c</fullName>
    <description>This field has &quot;;&quot; separated Case Team roles which will be automatically created for design win Cases.</description>
    <label>Case Team Roles: Design Win</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Cloud_Settings__mdt/fields/Customer_Profile_Names__c.field-meta.xml
<CustomField>
    <fullName>Customer_Profile_Names__c</fullName>
    <defaultValue>&apos;ESP Community User,NVES Community User Non-Admin,NPN Partner Community(LOGIN),NPN Partner Community(NAMED),NPN Tegra Jetson Partner Community(LOGIN)&apos;</defaultValue>
    <description>This field value is used as constant to identify Internal Users vs Customer.</description>
    <label>Customer Profile Names</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Cloud_Settings__mdt/fields/Default_Asset_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>Default_Asset_Contact_ID__c</fullName>
    <label>Default Asset Contact ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Cloud_Settings__mdt/fields/Disable_Trigger_Actions__c.field-meta.xml
<CustomField>
    <fullName>Disable_Trigger_Actions__c</fullName>
    <defaultValue>false</defaultValue>
    <description>STOP: Please DO NOT check this checkbox if you do not understand the impact of it.
Purpose of this flag to use during data migration when user don&apos;t want backend processes like Triggers, Process Builder, Validation Rule etc to RUN. 
Only disables,
1. Triggers: which inherits &quot;NV_TriggerHandler&quot; class
2. Any other processes: If they have used this flag in criteria.</description>
    <inlineHelpText>STOP: Please DO NOT check this checkbox if you do not understand the impact of it.
 
It Disables,
1. Triggers: which inherits &quot;NV_TriggerHandler&quot; class
2. Any other processes: If they have used this flag in criteria.</inlineHelpText>
    <label>Disable Trigger Actions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Cloud_Settings__mdt/fields/Internal_User_Types__c.field-meta.xml
<CustomField>
    <fullName>Internal_User_Types__c</fullName>
    <defaultValue>&apos;Standard&apos;</defaultValue>
    <label>Internal User Types</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Cloud_Settings__mdt/fields/Link_All_Assets__c.field-meta.xml
<CustomField>
    <fullName>Link_All_Assets__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This checkbox is to indicate whether to process all assets or only matching with criteria. It is used in Asset trigger and ESP_LinkAssets_BAT batch job.</description>
    <inlineHelpText>This checkbox is to indicate whether to process all assets or only matching with criteria. It is used in Asset trigger and ESP_LinkAssets_BAT batch job.</inlineHelpText>
    <label>Link All Assets</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Service_Cloud_Settings__mdt/fields/NVIDIA_Return_Account_ID__c.field-meta.xml
<CustomField>
    <fullName>NVIDIA_Return_Account_ID__c</fullName>
    <description>This field is used in hold return Assets. Used in Full System RMA code (RMATriggerHelper).</description>
    <label>NVIDIA Return Account ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Cloud_Settings__mdt/fields/Placeholder_Entitlement_Name__c.field-meta.xml
<CustomField>
    <fullName>Placeholder_Entitlement_Name__c</fullName>
    <defaultValue>&apos;Placeholder Entitlement - Please Update&apos;</defaultValue>
    <description>This field value is used to set Placeholder Entitlement Name for Business Critical service.</description>
    <label>Placeholder Entitlement Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Cloud_Settings__mdt/fields/SLA_24x7Support_Label__c.field-meta.xml
<CustomField>
    <fullName>SLA_24x7Support_Label__c</fullName>
    <defaultValue>&apos;24x7 Escalated Remote&apos;</defaultValue>
    <description>This field is used to compare support label with Account and Product and find Correct support process.</description>
    <label>SLA: 24x7Support Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Cloud_Settings__mdt/fields/TAM_Queue__c.field-meta.xml
<CustomField>
    <fullName>TAM_Queue__c</fullName>
    <defaultValue>&apos;TAM_Queue&apos;</defaultValue>
    <description>This field contains API Name of &quot;TAM Queue&quot;. It is used in Case Trigger to set correct queue when Case is escalated.</description>
    <inlineHelpText>This field contains API Name of &quot;TAM Queue&quot;</inlineHelpText>
    <label>TAM Queue</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SLA_Settings__mdt/SLA_Settings__mdt.object-meta.xml
<CustomObject>
    <description>This metadata type will have information about SLA Process variables based on Support Level.</description>
    <label>SLA Settings</label>
    <pluralLabel>SLA Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SLA_Settings__mdt/fields/Entitlement_Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Process_Name__c</fullName>
    <label>Entitlement Process Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SLA_Settings__mdt/fields/SLA_By_Product_Line_Label__c.field-meta.xml
<CustomField>
    <fullName>SLA_By_Product_Line_Label__c</fullName>
    <defaultValue>&apos;All with same Product Line&apos;</defaultValue>
    <label>SLA By Product Line Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SLA_Settings__mdt/fields/SLA_By_SN_Label__c.field-meta.xml
<CustomField>
    <fullName>SLA_By_SN_Label__c</fullName>
    <defaultValue>&apos;All with same Serial Number&apos;</defaultValue>
    <label>SLA By SN Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ESP_Constants.cls
/**
 * This class is a common place to store all Service Cloud Specific Constants.
 * Created: 09/20/2019 - Akhilesh Gupta 
 * 2020.20.26 - Akhilesh Gupta 	- SDS-2064 - Updated Constructor to populate new properties, 
 								- make ServiceCloudSettings public which will avoid having one variable for each Constant
 * Steps to add New Constant:
    //- Create new fields in Metadata "Service_Cloud_Settings__mdt" (e.g. SLA_24x7Support_Label__c)
    //- Update Query: Add newly created field in the query 
    //- if needed add new public property in this class: (CUSTOMER_PROFILES) [SKIP this step for premetive datatypes e.g. SLA_24X7SUPPORT]
    //- 	Add logic to retrieve from metadata in constructor
    //- Example how to use in code: ESP_Utility.ESPConstants.SLA_24X7SUPPORT 
 */
 public class ESP_Constants { 
    public Set<string> CUSTOMER_PROFILES 	= NULL;//new Set<string>{'ESP Community User', 'NVES Community User Non-Admin','NPN Partner Community(LOGIN)','NPN Partner Community(NAMED)','NPN Tegra Jetson Partner Community(LOGIN)'};
    public Set<string> AGENT_PROFILES 		= NULL;//new Set<string>{'Service Cloud Generic User'};
    public Set<string> INTERNAL_USERTYPES 	= NULL;//new Set<string>{'Standard'};
    public string SLA_24X7SUPPORT 			= '24x7 Escalated Remote';
    //public static string SLA_BY_PROD_LINE 	= 'All with same Product Line';
    //public static string SLA_BY_SN 			= 'All with same Serial Number';
     
    public Service_Cloud_Settings__mdt ServiceCloudSettings = NULL;
    public SLA_Settings__mdt SLA_Settings = NULL;
	public Set<string> DESIGN_WIN_CASE_TEAM_ROLES = NULL; 
    //Future Enhancements: Convert below static variables to class variables same as above and update constructor.
    //- Update all the code which is using these static variables 
    //-- ESP_Utility.ESPConstants.SLA_24X7SUPPORT
    public static final boolean ACTIVE_ENTITLEMENTS_ONLY= FALSE;
    public static final string SUPPORT_PORTAL 			= 'Support Portal';
    public static final string LICENSING_PORTAL 		= 'Licensing Portal';
    public static final map<String, String> OBJECT_TO_ACTIVITY_TYPE_MAP 
    													= new map<String, String>{
															'Attachment'			=> 'Attachment', 
															'ContentDocumentLink'	=> 'Attachment', 
															'EmailMessage' 			=> 'Email Message', 
															'CaseComment' 			=> 'Case Comment'
														};
	
	private ESP_Constants(){
        if(ServiceCloudSettings == null)
            ServiceCloudSettings = [SELECT Id, MasterLabel, DeveloperName, TAM_Queue__c, Placeholder_Entitlement_Name__c
            							, Customer_Profile_Names__c, Agent_Profile_Names__c, Internal_User_Types__c
                                    	, SLA_24x7Support_Label__c, Case_Team_Roles_Design_Win__c, Disable_Trigger_Actions__c
                                    	, NVIDIA_Return_Account_ID__c, Default_Asset_Contact_ID__c, Link_All_Assets__c
                                    FROM Service_Cloud_Settings__mdt];
        
        if(SLA_Settings == NULL) 
            SLA_Settings = [SELECT Id, MasterLabel, DeveloperName 
                            	, Entitlement_Process_Name__c, SLA_By_Product_Line_Label__c, SLA_By_SN_Label__c
                            FROM SLA_Settings__mdt];
        
        SLA_24X7SUPPORT = ServiceCloudSettings.SLA_24x7Support_Label__c;
        //if(CUSTOMER_PROFILES == NULL) {
    		CUSTOMER_PROFILES = new Set<string>();
    		String cprofiles = ServiceCloudSettings.Customer_Profile_Names__c;
	    	if(!string.isEmpty(cprofiles))
	    		CUSTOMER_PROFILES.addAll(cprofiles.split(','));
    	//}
        //if(AGENT_PROFILES == NULL) {
    		AGENT_PROFILES = new Set<string>();
    		String aprofiles = ServiceCloudSettings.Agent_Profile_Names__c;
	    	if(!string.isEmpty(aprofiles))
	    		AGENT_PROFILES.addAll(aprofiles.split(','));
    	//}
        //if(INTERNAL_USERTYPES == NULL) {
    		INTERNAL_USERTYPES = new Set<string>();
    		String userTypes = ServiceCloudSettings.Internal_User_Types__c;
	    	if(!string.isEmpty(userTypes))
	    		INTERNAL_USERTYPES.addAll(userTypes.split(','));
    	//}
    	//Design_Win_Case_Team_Roles
    	Design_Win_Case_Team_Roles = new Set<string>();
        String caseRoles = ServiceCloudSettings.Case_Team_Roles_Design_Win__c;
        if(!string.isEmpty(caseRoles))
	    	DESIGN_WIN_CASE_TEAM_ROLES.addAll(caseRoles.split(','));
    }
	
	private static ESP_Constants ESP_Constants_instance = NULL;
    public static ESP_Constants getInstance() {
        
        if (ESP_Constants_instance == null)
            ESP_Constants_instance = new ESP_Constants();
        
        System.debug(ESP_Constants_instance.AGENT_PROFILES);
        System.debug(ESP_Constants_instance.CUSTOMER_PROFILES);
        System.debug(ESP_Constants_instance.INTERNAL_USERTYPES);
        System.debug(ESP_Constants_instance.DESIGN_WIN_CASE_TEAM_ROLES);
  		
        return ESP_Constants_instance;
    }
}