force-app/main/default/objects/PRM_Training_and_Events__c/PRM_Training_and_Events__c.object-meta.xml
<CustomObject>
    <description>Training and Event data displayed on the PRM Homepage.</description>
    <label>PRM Training and Events</label>
    <nameField>
        <label>PRM Training and Events Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PRM Training and Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PRM_Training_and_Events__c/fields/Date_Display__c.field-meta.xml
<CustomField>
    <fullName>Date_Display__c</fullName>
    <description>How the date or dates for the event should be displayed on the PRM homepage portal.</description>
    <inlineHelpText>How the date or dates for the event should be displayed on the PRM homepage portal.</inlineHelpText>
    <label>Date Display</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRM_Training_and_Events__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>The event or training description.  This will be displayed to users who visit this record directly by clicking on the name of the object in the PRM homepage.</description>
    <inlineHelpText>The event or training description.  This will be displayed to users who visit this record directly by clicking on the name of the object in the PRM homepage.</inlineHelpText>
    <label>Description</label>
    <length>32000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PRM_Training_and_Events__c/fields/External_URL__c.field-meta.xml
<CustomField>
    <fullName>External_URL__c</fullName>
    <description>A url external to Salesforce to direct users to if they click on the name of the event in the PRM homepage.  If no value is provided, the link will direct the users to this record.</description>
    <inlineHelpText>A url external to Salesforce to direct users to if they click on the name of the event in the PRM homepage.  If no value is provided, the link will direct the users to this record.</inlineHelpText>
    <label>Externald URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PRM_Training_and_Events__c/fields/Html__c.field-meta.xml
<CustomField>
    <fullName>Html__c</fullName>
    <description>Data entered in this field will be added verbatim to the PRM homepage training section.  No html escaping is done.  Use this option with caution, as style changes or invalid HTML may affect other page elements.</description>
    <inlineHelpText>Data entered in this field will be added verbatim to the PRM homepage training section.  No html escaping is done.  Use this option with caution, as style changes or invalid HTML may affect other page elements.</inlineHelpText>
    <label>Html</label>
    <length>32000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/PRM_Training_and_Events__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <description>The image pointed to will be displayed in the browser, and hyperlinked to External_Url__c.</description>
    <inlineHelpText>The image pointed to will be displayed in the browser, and hyperlinked to External_Url__c.</inlineHelpText>
    <label>Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PRM_Training_and_Events__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>The location to display on the PRM homepage, if any.</description>
    <inlineHelpText>The location to display on the PRM homepage, if any.</inlineHelpText>
    <label>Location</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PRM_Training_and_Events__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>The order in which PRM Training and Events objects will be displayed to users on the PRM homepage.  Remove this value to remove items from the homepage.  If there are multiple objects displayed, they will be sorted by this value.</description>
    <inlineHelpText>The order in which PRM Training and Events objects will be displayed to users on the PRM homepage.  Remove this value to remove items from the homepage.  If there are multiple objects displayed, they will be sorted by this value.</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/PRM_Training_and_Events__c/fields/Use_Description__c.field-meta.xml
<CustomField>
    <fullName>Use_Description__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box to display the contents of the Description field on the PRM homepage.</description>
    <inlineHelpText>Check this box to display the contents of the Description field on the PRM homepage.</inlineHelpText>
    <label>Use Description</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PRM_Training_and_Events__c/fields/Use_Html__c.field-meta.xml
<CustomField>
    <fullName>Use_Html__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box to display the contents of the Html field on the PRM homepage.</description>
    <inlineHelpText>Check this box to display the contents of the Html field on the PRM homepage.</inlineHelpText>
    <label>Use Html</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/PRM_Training_and_Events__c/fields/Use_Image__c.field-meta.xml
<CustomField>
    <fullName>Use_Image__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box to display the contents of the Image field on the PRM homepage.</description>
    <inlineHelpText>Check this box to display the contents of the Image field on the PRM homepage.</inlineHelpText>
    <label>Use Image</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/PrmEventsController.cls
/**
 * Returns PRM_Training_And_Events__c that should appear on a customized partner
 * portal homepage.
 *
 * @author tschulte@appirio.com
 * @date 06-08-2010
 */
public class PrmEventsController 
{
	public List<PRM_Training_and_Events__c> getEvents() 
	{
		return [SELECT Id, External_URL__c, Name, Date_Display__c, Location__c, Description__c, Html__c, Use_Html__c, Use_Description__c, Use_Image__c, Image__c
					  FROM PRM_Training_and_Events__c 
					  WHERE Sort_Order__c != null 
					  ORDER BY Sort_Order__c];
	}
 
 	@isTest
 	public static void testGetEvents() 
 	{
 		PrmEventsController controller = new PrmEventsController();
 		controller.getEvents();		
 	}
}