force-app/main/default/objects/SuRF_Partner_Performance_Scorecard__c/SuRF_Partner_Performance_Scorecard__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF-Partner Performance Scorecard</label>
    <nameField>
        <displayFormat>SuRF-PPS-{00000}</displayFormat>
        <label>SuRF-Partner Performance Scorecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuRF-Partner Performance Scorecards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_Partner_Performance_Scorecard__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <label>Flag</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SuRF_Partner_Performance_Scorecard__c/fields/PBM__c.field-meta.xml
<CustomField>
    <fullName>PBM__c</fullName>
    <label>PBM</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SuRF_Partner_Performance_Scorecard__c/fields/Program_Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>Program_Signed_Date__c</fullName>
    <label>Program Signed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SuRF_Partner_Performance_Scorecard_Trans__c/SuRF_Partner_Performance_Scorecard_Trans__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF-Partner Performance Scorecard Trans</label>
    <nameField>
        <displayFormat>SuRF-PPS-{00000}</displayFormat>
        <label>SuRF-Partner Performance Scorecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuRF-Partner Performance Scorecard Trans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_Partner_Performance_Scorecard_Trans__c/fields/Competency_Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>Competency_Signed_Date__c</fullName>
    <label>Competency Signed Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SuRF_Partner_Performance_Scorecard_Trans__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SuRF_Level</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SuRF_Partner_Performance_Scorecard_Trans__c/fields/Partner_Program__c.field-meta.xml
<CustomField>
    <fullName>Partner_Program__c</fullName>
    <label>Partner Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SuRF_Partner_Program</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SuRF_Partner_Performance_Scorecard_Trans__c/fields/Partner_SubProgram__c.field-meta.xml
<CustomField>
    <fullName>Partner_SubProgram__c</fullName>
    <label>Partner SubProgram</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/SuRF_Level.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Preferred</fullName>
    </customValue>
    <customValue>
        <fullName>Elite</fullName>
    </customValue>
    <customValue>
        <fullName>Registered</fullName>
    </customValue>
    <masterLabel>SuRF Level</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SuRF_Partner_Program.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Solution Provider</fullName>
    </customValue>
    <customValue>
        <fullName>OEM</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud Service Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Solution Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>Inception Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Tegra Embedded</fullName>
    </customValue>
    <customValue>
        <fullName>Services Subcontractor</fullName>
    </customValue>
    <customValue>
        <fullName>Service Delivery Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Solutions Integration Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Federal Systems Integrator</fullName>
    </customValue>
    <customValue>
        <fullName>Global Systems Integrator</fullName>
    </customValue>
    <masterLabel>SuRF Partner Program</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NPN_SuRF_Batch_PPS.cls
global class NPN_SuRF_Batch_PPS implements Database.batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([SELECT Account_ID__c
                                         ,Account_Name__c
                                         ,Category__c
                                         ,Competency__c
                                         ,Competency_Signed_Date__c
                                         ,Flag__c
                                         ,Level__c
                                         ,Order__c
                                         ,Partner_Program__c
                                         ,PBM__c
                                         ,Program_Signed_Date__c
                                         ,Region__c
                                         ,Partner_SubProgram__c
                                          FROM SuRF_Partner_Performance_Scorecard__c
                                         WHERE isDeleted = false]);
    }
    global void execute(Database.BatchableContext BC, List<SuRF_Partner_Performance_Scorecard__c> scope) {
        List<SuRF_Partner_Performance_Scorecard_Trans__c> lst = new List<SuRF_Partner_Performance_Scorecard_Trans__c>();
        for(SuRF_Partner_Performance_Scorecard__c obj : scope) {
            SuRF_Partner_Performance_Scorecard_Trans__c transObj = new SuRF_Partner_Performance_Scorecard_Trans__c();
            transObj.Account_ID__c = obj.Account_ID__c;
            transObj.Account_Name__c = obj.Account_Name__c;
            transObj.Category__c = obj.Category__c;
            transObj.Competency__c = obj.Competency__c;
            transObj.Competency_Signed_Date__c = obj.Competency_Signed_Date__c;
            transObj.Flag__c = obj.Flag__c;
            transObj.Level__c = obj.Level__c;
            transObj.Order__c = obj.Order__c;
            transObj.Partner_Program__c = obj.Partner_Program__c;
            transObj.PBM__c = obj.PBM__c;
            transObj.Program_Signed_Date__c = obj.Program_Signed_Date__c;
            transObj.Region__c = obj.Region__c;
            transObj.Partner_SubProgram__c = obj.Partner_SubProgram__c;
            lst.add(transObj);
        }
        insert lst;
    }
    global void finish(Database.BatchableContext BC) {
    }
}