force-app/main/default/objects/Community_Settings__c/Community_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to store all settings related to NPN</description>
    <label>Community Settings</label>
</CustomObject>

force-app/main/default/objects/Community_Settings__c/fields/ERROR_EMAILS__c.field-meta.xml
<CustomField>
    <fullName>ERROR_EMAILS__c</fullName>
    <description>Email addresses for notifying bulk sOEM user creation errors</description>
    <label>ERROR_EMAILS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NV_Error_Log__c/NV_Error_Log__c.object-meta.xml
<CustomObject>
    <description>NPN : SOEM Lead Convert error log</description>
    <label>NV Error Log</label>
    <nameField>
        <displayFormat>EL-{000000}</displayFormat>
        <label>SFDC Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NV Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NV_Error_Log__c/fields/Error_Description__c.field-meta.xml
<CustomField>
    <fullName>Error_Description__c</fullName>
    <label>Error Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/NV_Test_ErrorLogHelper.cls
@isTest
private class NV_Test_ErrorLogHelper {
    
    private static testMethod void ErrorLogSendEmailTest() {
        Community_Settings__c cs = new Community_Settings__c(ERROR_EMAILS__c = 'varunk22@gmail.com');
        insert cs;
        NV_Error_Log__c objNVErrLg = new NV_Error_Log__c();
        objNVErrLg.Error_Description__c = 'test';
        objNVErrLg.Error_Message__c = 'test';
        objNVErrLg.functionality__c = 'test';
        test.startTest();
            insert objNVErrLg;
        test.stopTest();    
    }

}