force-app/main/default/objects/Community_Settings__c/Community_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to store all settings related to NPN</description>
    <label>Community Settings</label>
</CustomObject>

force-app/main/default/objects/Community_Settings__c/fields/ERROR_EMAILS__c.field-meta.xml
<CustomField>
    <fullName>ERROR_EMAILS__c</fullName>
    <description>Email addresses for notifying bulk sOEM user creation errors</description>
    <label>ERROR_EMAILS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NV_Error_Log__c/NV_Error_Log__c.object-meta.xml
<CustomObject>
    <description>NPN : SOEM Lead Convert error log</description>
    <label>NV Error Log</label>
    <nameField>
        <displayFormat>EL-{000000}</displayFormat>
        <label>SFDC Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NV Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NV_Error_Log__c/fields/Error_Description__c.field-meta.xml
<CustomField>
    <fullName>Error_Description__c</fullName>
    <label>Error Description</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/NVErrorLogHelper.cls
public class NVErrorLogHelper {

    public static void sendEmail(List<NV_Error_Log__c> lstNVErrLog) {
        if(lstNVErrLog != null && lstNVErrLog.size() > 0) {
            Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
            Community_settings__c cs = Community_Settings__c.getInstance();
            String strErrorEmails  = cs.ERROR_EMAILS__c;
            string[] toAddresses = strErrorEmails.split(';');
            for (integer i=0; i < toAddresses.size(); i++){
               toAddresses[i] = toAddresses[i].trim();
            }
            mail.setToAddresses(toAddresses);
            mail.setSubject('SOEM Process failure');
            //build the email body
            string html = '<table width="100%">';
            html += '<tr><td><b>Error Description</b></td><td><b>Error Message</b></td></tr>';        
            for(NV_Error_Log__c objErrorInsert : lstNVErrLog) {
                html += '<tr><td>' + objErrorInsert.Error_Description__c + '</td><td>' + objErrorInsert.Error_Message__c+ '</td></tr>';
            }
            html += '</table>';
                
            //set html body
            mail.setHtmlbody(html);      
                
            //send email
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
        }
    }

}