force-app/main/default/objects/Community_Settings__c/Community_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to store all settings related to NPN</description>
    <label>Community Settings</label>
</CustomObject>

force-app/main/default/objects/Community_Settings__c/fields/ACC_COMPUTING_TESLA__c.field-meta.xml
<CustomField>
    <fullName>ACC_COMPUTING_TESLA__c</fullName>
    <label>ACC COMPUTING TESLA</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/BATCHJOB_PS_PG_ASSIGN_LKBK_TIME__c.field-meta.xml
<CustomField>
    <fullName>BATCHJOB_PS_PG_ASSIGN_LKBK_TIME__c</fullName>
    <defaultValue>60</defaultValue>
    <description>Batch Job: Lookback time used in LastModifiedDate &gt; Now - LookbackTime</description>
    <inlineHelpText>Batch Job: Lookback time used in LastModifiedDate &gt; Now - LookbackTime</inlineHelpText>
    <label>BATCHJOB_PS_PG_ASSIGN_LKBK_TIME</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/BATCHJOB_PS_PG_ASSIGN_RECUR__c.field-meta.xml
<CustomField>
    <fullName>BATCHJOB_PS_PG_ASSIGN_RECUR__c</fullName>
    <defaultValue>60</defaultValue>
    <description>Batch Job: Recurring time - the next time the job will run (Now + Recurring Time) in minutes</description>
    <inlineHelpText>Batch Job: Recurring time - the next time the job will run (Now + Recurring Time) in minutes</inlineHelpText>
    <label>BATCHJOB_PS_PG_ASSIGN_RECUR</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/BATCHJOB_PS_PG_BATCH_SIZE__c.field-meta.xml
<CustomField>
    <fullName>BATCHJOB_PS_PG_BATCH_SIZE__c</fullName>
    <defaultValue>25</defaultValue>
    <description>BATCH JOB: Number of records per batch to be processed in batch job</description>
    <inlineHelpText>BATCH JOB: Number of records per batch to be processed in batch job</inlineHelpText>
    <label>BATCHJOB_PS_PG_BATCH_SIZE</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/BATCHJOB_PS_PG_ENABLE_SCHDULED_JOB__c.field-meta.xml
<CustomField>
    <fullName>BATCHJOB_PS_PG_ENABLE_SCHDULED_JOB__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If set to false, the batch job will terminated, but you need to run it manually to start again.
COMM_AssignPSPG_To_CommunityUsers_Batch p = new COMM_AssignPSPG_To_CommunityUsers_Batch();
DateTime currDT = DateTime.now().addMinutes(2);
integer sec = currDT.second();
integer min = currDT.minute();
String sch = sec + &apos; &apos; + min + &apos; &apos; + &apos;* ? * *&apos;; //0 5 * * * ?
system.debug(&apos;sch: &apos; + sch);
system.schedule(&apos;Exec of COMM_AssignPSPG_To_CommunityUsers_Batch&apos;, sch, p);</description>
    <inlineHelpText>If set to false, the batch job will terminated, but you need to run it manually to start again. See the fields description field how to start the batch job that assigns the PS PG in batch mode.</inlineHelpText>
    <label>BATCHJOB_PS_PG_ENABLE_SCHDULED_JOB</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/BATCHJOB_PS_PG_ESCAPE_USER_SETTINGS_PROF__c.field-meta.xml
<CustomField>
    <fullName>BATCHJOB_PS_PG_ESCAPE_USER_SETTINGS_PROF__c</fullName>
    <description>COMM_AssignPSPG_To_CommunityUsers_Batch : Profiles that need to be skipped for user settings such as Salesforce1 User = False, 
Salesforce CRM Content User = True (Only for Partner Portal Users), 
Chatter Answers User = false, 
Receive Salesforce CRM Content Email Alerts = false, 
Receive Salesforce CRM Content Alerts as Daily Digest = false 
Note: Semi-colon separated e.g, Marketing Customer Community; this; that</description>
    <inlineHelpText>Semi-colon separated e.g, Marketing Customer Community; Prof2; Prof3</inlineHelpText>
    <label>BATCHJOB_PS_PG_ESCAPE_USER_SETTINGS_PROF</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/BATCHJOB_U2CSync_BATCH_SIZE__c.field-meta.xml
<CustomField>
    <fullName>BATCHJOB_U2CSync_BATCH_SIZE__c</fullName>
    <defaultValue>25</defaultValue>
    <description>COMM_Sync_CommUserDataToContactRec_Batch Job : Number of records per batch to be processed in batch job</description>
    <inlineHelpText>COMM_Sync_CommUserDataToContactRec_Batch Job : Number of records per batch to be processed in batch job</inlineHelpText>
    <label>BATCHJOB_U2CSync_BATCH_SIZE</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/BATCHJOB_U2CSync_ENABLE_SCHDULED_JOB__c.field-meta.xml
<CustomField>
    <fullName>BATCHJOB_U2CSync_ENABLE_SCHDULED_JOB__c</fullName>
    <defaultValue>false</defaultValue>
    <description>COMM_AssignPSPG_To_CommunityUsers_Batch:
If set to false, the batch job will terminated, but you need to run it manually to start again.
COMM_AssignPSPG_To_CommunityUsers_Batch p = new COMM_AssignPSPG_To_CommunityUsers_Batch();
DateTime currDT = DateTime.now().addMinutes(2);
integer sec = currDT.second();
integer min = currDT.minute();
String sch = sec + &apos; &apos; + min + &apos; &apos; + &apos;* ? * *&apos;; //0 5 * * * ?
system.debug(&apos;sch: &apos; + sch);
system.schedule(&apos;Exec of COMM_AssignPSPG_To_CommunityUsers_Batch&apos;, sch, p);</description>
    <inlineHelpText>COMM_AssignPSPG_To_CommunityUsers_Batch: If set to false, the batch job will terminated, but you need to run it manually to start again. See the fields description how to start the batch job that assigns the PS PG in batch mode.</inlineHelpText>
    <label>BATCHJOB_U2CSync_ENABLE_SCHDULED_JOB</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/BATCHJOB_U2CSync_LKBK_TIME__c.field-meta.xml
<CustomField>
    <fullName>BATCHJOB_U2CSync_LKBK_TIME__c</fullName>
    <defaultValue>60</defaultValue>
    <description>COMM_Sync_CommUserDataToContactRec_Batch Job. Lookback time to gather User Records to process</description>
    <inlineHelpText>COMM_Sync_CommUserDataToContactRec_Batch Job : Lookback time to gather User Records to processLookback time to gather User Records to process (e.g., If you want to process user records that got updated in last 5 mintues, set the value to 5</inlineHelpText>
    <label>BATCHJOB_U2CSync_LKBK_TIME</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/BATCHJOB_U2CSync_RECUR__c.field-meta.xml
<CustomField>
    <fullName>BATCHJOB_U2CSync_RECUR__c</fullName>
    <defaultValue>60</defaultValue>
    <description>COMM_Sync_CommUserDataToContactRec_Batch Job - Recurring time - the next time the job will run (Now + Recurring Time) in minutes</description>
    <inlineHelpText>COMM_Sync_CommUserDataToContactRec_Batch Job - Recurring time - the next time the job will run (Now + Recurring Time) in minutes</inlineHelpText>
    <label>BATCHJOB_U2CSync_RECUR</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/BRAINSHARK_URL__c.field-meta.xml
<CustomField>
    <fullName>BRAINSHARK_URL__c</fullName>
    <defaultValue>&quot;https://www.brainshark.com/portal/psapis/api/psSession.aspx&quot;</defaultValue>
    <label>BRAINSHARK_URL</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/CLOUD_VIRTUALIZATION_VGX__c.field-meta.xml
<CustomField>
    <fullName>CLOUD_VIRTUALIZATION_VGX__c</fullName>
    <label>CLOUD VIRTUALIZATION VGX</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/CONTENTVERSION_COMPETENCY_METAID__c.field-meta.xml
<CustomField>
    <fullName>CONTENTVERSION_COMPETENCY_METAID__c</fullName>
    <description>Portal Lite Content Filtering based on Competency and Region field (SPS-46, SIR-PJ25604)</description>
    <label>CONTENTVERSION COMPETENCY METAID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/CONTENTVERSION_LANGUAGE_REGION_METAID__c.field-meta.xml
<CustomField>
    <fullName>CONTENTVERSION_LANGUAGE_REGION_METAID__c</fullName>
    <defaultValue>&quot;00N40000002WvBR&quot;</defaultValue>
    <description>Field Id for CONTENTVERSION.LANGUAGE_REGION custom field</description>
    <label>CONTENTVERSION_LANGUAGE_REGION_METAID</label>
    <length>15</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/ERROR_EMAILS__c.field-meta.xml
<CustomField>
    <fullName>ERROR_EMAILS__c</fullName>
    <description>Email addresses for notifying bulk sOEM user creation errors</description>
    <label>ERROR_EMAILS</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/PROF_VISUALIZATION_VCA__c.field-meta.xml
<CustomField>
    <fullName>PROF_VISUALIZATION_VCA__c</fullName>
    <label>PROF VISUALIZATION VCA</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/PS_PG_ASSIGN_LKBK_TIME__c.field-meta.xml
<CustomField>
    <fullName>PS_PG_ASSIGN_LKBK_TIME__c</fullName>
    <defaultValue>5</defaultValue>
    <label>PS_PG_ASSIGN_LKBK_TIME</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/PS_PG_ASSIGN_RECUR__c.field-meta.xml
<CustomField>
    <fullName>PS_PG_ASSIGN_RECUR__c</fullName>
    <defaultValue>2</defaultValue>
    <label>PS_PG_ASSIGN_RECUR</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/PS_PG_ENABLE_SCHDULED_JOB__c.field-meta.xml
<CustomField>
    <fullName>PS_PG_ENABLE_SCHDULED_JOB__c</fullName>
    <defaultValue>true</defaultValue>
    <label>PS_PG_ENABLE_SCHDULED_JOB</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Community_Settings__c/fields/USERNAME_EXTENSION__c.field-meta.xml
<CustomField>
    <fullName>USERNAME_EXTENSION__c</fullName>
    <description>default username extension for bulk sOEM community users</description>
    <inlineHelpText>default username extension for bulk sOEM community users</inlineHelpText>
    <label>USERNAME_EXTENSION</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_Groups__c.field-meta.xml
<CustomField>
    <fullName>Portal_Groups__c</fullName>
    <label>Permissions &amp; Group Assignments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>All Partner Content</fullName>
            </value>
            <value>
                <fullName>Arrow Embedded Edge</fullName>
            </value>
            <value>
                <fullName>ATP</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Compute DGX Portal Full</fullName>
            </value>
            <value>
                <fullName>Compute Portal Full</fullName>
            </value>
            <value>
                <fullName>CSP Compute DGX Elite</fullName>
            </value>
            <value>
                <fullName>CSP Compute DGX Preferred</fullName>
            </value>
            <value>
                <fullName>CSP Compute Elite</fullName>
            </value>
            <value>
                <fullName>CSP Compute Preferred</fullName>
            </value>
            <value>
                <fullName>CSP Virtualization Elite</fullName>
            </value>
            <value>
                <fullName>CSP Virtualization Preferred</fullName>
            </value>
            <value>
                <fullName>CSP Visualization Elite</fullName>
            </value>
            <value>
                <fullName>CSP Visualization Preferred</fullName>
            </value>
            <value>
                <fullName>DGX Partner Content</fullName>
            </value>
            <value>
                <fullName>DISTI Compute DGX Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Compute Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Embedded Edge Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Virtualization Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Visualization Preferred</fullName>
            </value>
            <value>
                <fullName>EDU Lead Registration</fullName>
            </value>
            <value>
                <fullName>Embedded Edge Elite</fullName>
            </value>
            <value>
                <fullName>Embedded Edge Portal Full</fullName>
            </value>
            <value>
                <fullName>Embedded Edge Preferred</fullName>
            </value>
            <value>
                <fullName>Entitlements</fullName>
            </value>
            <value>
                <fullName>Fed SI Compute DGX Elite</fullName>
            </value>
            <value>
                <fullName>Fed SI Compute DGX Preferred</fullName>
            </value>
            <value>
                <fullName>Fed SI Compute Elite</fullName>
            </value>
            <value>
                <fullName>Fed SI Compute Preferred</fullName>
            </value>
            <value>
                <fullName>Fed SI Embedded Edge Elite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner Contact</label>
</RecordType>

force-app/main/default/objects/NPN_Tableau_UserMgmt__c/NPN_Tableau_UserMgmt__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NPN Tableau UserMgmt</label>
</CustomObject>

force-app/main/default/objects/NPN_Tableau_UserMgmt__c/fields/Contact_Permission__c.field-meta.xml
<CustomField>
    <fullName>Contact_Permission__c</fullName>
    <label>Contact Permission</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Tableau_UserMgmt__c/fields/SiteRole__c.field-meta.xml
<CustomField>
    <fullName>SiteRole__c</fullName>
    <label>SiteRole</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Tableau_UserMgmt__c/fields/Userlicense__c.field-meta.xml
<CustomField>
    <fullName>Userlicense__c</fullName>
    <label>Userlicense</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NPN_Tableau_UserMgmt_Bat_sch_Test.cls
@isTest(seeAllData=false)
public class NPN_Tableau_UserMgmt_Bat_sch_Test {

    static String sessionBody;
    static void makeData(){
        
        list<Community_Settings__c> listCommunity_Settings= new list<Community_Settings__c> ();

        Community_Settings__c Co1= new Community_Settings__c ();
        Co1.name= 'Test';
        Co1.setupownerid= UserInfo.getOrganizationId();
        Co1.acc_computing_tesla__c= 'Tesla';
        Co1.brainshark_url__c= 'https://staging.brainshark.com/portal/psapis/api/psSession.aspx';
        Co1.cloud_virtualization_vgx__c= 'Virutalization';
        Co1.prof_visualization_vca__c= 'Visualization';
        Co1.ps_pg_assign_lkbk_time__c= 8;
        Co1.ps_pg_assign_recur__c= 5;
        Co1.ps_pg_enable_schduled_job__c= false;
        //Co1.contentversion_language_region_metaid__c= '00N40000002WvBR';
        //Co1.contentversion_competency_metaid__c= '00N40000002zGdx';
        Co1.error_emails__c= 'apardeshi@nvidia.com.invalid;vakulkarni@nvidia.com.invalid';
        Co1.username_extension__c= 'npnbu';
        Co1.batchjob_ps_pg_assign_lkbk_time__c= 8;
        Co1.batchjob_ps_pg_assign_recur__c= 5;
        Co1.batchjob_ps_pg_batch_size__c= 25;
        Co1.batchjob_ps_pg_enable_schduled_job__c= true;
        Co1.batchjob_ps_pg_escape_user_settings_prof__c= 'Marketing Customer Community';
        Co1.batchjob_u2csync_batch_size__c= 100;
        Co1.batchjob_u2csync_enable_schduled_job__c= true;
        Co1.batchjob_u2csync_lkbk_time__c= 20;
        Co1.batchjob_u2csync_recur__c= 10;

        listCommunity_Settings.add(Co1);


        insert listCommunity_Settings;

        list<NPN_Tableau_UserMgmt__c> listNPN_Tableau_UserMgmt= new list<NPN_Tableau_UserMgmt__c> ();

        NPN_Tableau_UserMgmt__c NP1= new NPN_Tableau_UserMgmt__c ();
        NP1.setupownerid= UserInfo.getOrganizationId();
        NP1.siterole__c= 'Viewer';
        NP1.userlicense__c= 'Partner Community Login';
        NP1.contact_permission__c= 'NPN Compliance Tab';

        listNPN_Tableau_UserMgmt.add(NP1);


        insert listNPN_Tableau_UserMgmt;

        map<String, Id> mapProfNameId;
        Account partnerAcc;
        Contact partnerContact1,partnerContact2;
        User partnerUser1;
        String userName;

        Id accRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('NPN_Account_Registry').getRecordTypeId();
        Id contactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Partner').getRecordTypeId();

        //get All Profiles (PROF_PP_VGX_GENERIC = NPN Partner Community(LOGIN), PROF_INT_PARTNER_ADMIN = Sales Profile - Partner Admin)
        list<string> lstProfNames = new list<string> {COMM_Constants.PROF_PP_VGX_GENERIC, COMM_Constants.PROF_INT_PARTNER_ADMIN };
        mapProfNameId = Test_COMM_Factory.getProfsByName(lstProfNames);


        User thisUser = [SELECT Id FROM User WHERE Id = :UserInfo.getUserId()];
        System.runAs(thisUser){

            //Account partnerAcc = [SELECT Id, Name FROM Account WHERE Id = '0012200000MBJcb' LIMIT 1];

            //Create a NPN Account with Billing Country, Region
            partnerAcc = Test_COMM_Factory.createNPNAccountWithUSBillingAddressRegion('DRNPNAccountRegistry1', accRecTypeId);


            //Create a Partner Contact
            //partnerContact1 = Test_COMM_Factory.createContactWithMailingAddress('LDRJena11', 'FContact11', partnerAcc.Id, 'drcontactjena11@nv.com.invalid', contactRecTypeId, COMM_Constants.ADDRESS_STREET, COMM_Constants.ADDRESS_CITY, COMM_Constants.ADDRESS_STATE, COMM_Constants.ADDRESS_COUNTRY, COMM_Constants.ADDRESS_ZIP );

            partnerContact1 = new Contact(
                LastName='LNameTest',
                FirstName='FContact11',
                AccountId=partnerAcc.Id,
                Email='drcontact@nv.com.invalid',
                RecordTypeId=contactRecTypeId,
                MailingStreet='The NVIDIA Way64731572844891211',
                MailingCity='Santa Clara',
                MailingState='California',
                MailingCountry='United States',
                MailingPostalCode='95050',
                Portal_Groups__c = 'NPN Compliance Tab;Submit POS;'
                );

            insert partnerContact1;

            partnerContact2 = new Contact(
                LastName='LNameTest',
                FirstName='FContact11',
                AccountId=partnerAcc.Id,
                Email='drcontactTwo@nv.com.invalid',
                RecordTypeId=contactRecTypeId,
                MailingStreet='The NVIDIA Way64731572844891211',
                MailingCity='Santa Clara',
                MailingState='California',
                MailingCountry='United States',
                MailingPostalCode='95050',
                Portal_Groups__c = 'Submit POS;'
                );

            insert partnerContact2;


            //Create a Partner User with profile named 'NPN Partner Community(LOGIN)'
            User comUser = new User(
                LastName='one',
                Alias = 'tsale',
                Email = 'nvpartnerone@foo.com.invalid',
                Username = 'nvvippartnerone@foo.com.crqext',
                CommunityNickname = 'nvvippartnerone',
                ProfileId = mapProfNameId.get(COMM_Constants.PROF_PP_VGX_GENERIC),
                ContactId=partnerContact1.Id,
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                Tableau_IsUserCreated__c = false,
                Tableau_Do_Not_Sync__c = false
                );
            insert comUser;

            User comUser2 = new User(
                LastName='one',
                Alias = 'tsale',
                Email = 'nvpartnerTwo@foo.com.invalid',
                Username = 'nvpartnerTwo@foo.com.crqext',
                CommunityNickname = 'nvpartnerTwo',
                ProfileId = mapProfNameId.get(COMM_Constants.PROF_PP_VGX_GENERIC),
                ContactId=partnerContact2.Id,
                TimeZoneSidKey = 'America/Los_Angeles',
                LocaleSidKey = 'en_US',
                EmailEncodingKey = 'UTF-8',
                LanguageLocaleKey = 'en_US',
                Tableau_IsUserCreated__c = false,
                Tableau_Do_Not_Sync__c = false
                );
            insert comUser2;

        }
    }

    
    
    @isTest
    static void testBatchClassSchedule(){

        Test.startTest();
        NPN_Tableau_UserMgmt_Bat_sch sch = new NPN_Tableau_UserMgmt_Bat_sch();
        string cronexp='0 0 * ? * * *';
        Id jobId = System.schedule('TableauUserCreationFromTEST',cronexp,sch);

        System.abortJob(jobId);
        Test.stopTest();

    }

    @isTest
    static void testBatchClassExecuteUserActive(){

        Test.setMock(HttpCalloutMock.class, new Mock());
        
        makeData();

        List<User> commUser = [SELECT Id,Name, email, username, IsActive, Contact.Portal_Groups__c, ContactId, Tableau_IsUserCreated__c, Tableau_IsUserDeleted__c,
                               Tableau_UserCreationDateTime__c, Tableau_UserCreationLastAPICallResponse__c, Tableau_UserDeletionDateTime__c, Tableau_UserDeletionLastAPICallResponse__c,
                               Tableau_UserId__c, Tableau_Username__c, Tableau_Do_Not_Sync__c, Tableau_API_Response_Failure__c FROM USER WHERE UserName = 'nvvippartnerone@foo.com.crqext' AND (Contact.Portal_Groups__c != null OR Contact.Portal_Groups__c != '') ];

        Map<String,String> responseHeaders = new Map<String, String>();
        responseHeaders.put('Content-Type', 'text/xml; charset=utf-8');

        
        sessionBody = '<?xml version="1.0" encoding="utf-8"?>' +
                             '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"' +
                             'xmlns="urn:partner.soap.sforce.com"' +
                             'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">' +
                             '<soapenv:Body>' +
                             '<loginResponse>' +
                             '<result>' +
                             '<passwordExpired>false</passwordExpired>' +
                             '<serverUrl>https://na1.salesforce.com/services/Soap/u/10.0</serverUrl>' +
                             '<sessionId>QwWsHJyTPW.1pd0_jXlNKOSU</sessionId>' +
                             '<userId>'+commUser[0].Id+'</userId>' +
                             '<userInfo>' +
                             '<!-- ... -->' +
                             '</userInfo>' +
                             '</result>' +
                             '</loginResponse>' +
                             '</soapenv:Body>' +
                             '</soapenv:Envelope>';
        
        User admin = [SELECT Id FROM User WHERE Profile.Name ='System Administrator' AND IsActive = true LIMIT 1];
        System.runAs(admin){
            Test.startTest();
            NPN_Tableau_UserMgmt_Bat_sch oNPNTableauUserMgtBAtchSch = new NPN_Tableau_UserMgmt_Bat_sch();


            oNPNTableauUserMgtBAtchSch.token  ='1pd0jXlNKOSU';
            oNPNTableauUserMgtBAtchSch.siteRole = 'Viewer';
            oNPNTableauUserMgtBAtchSch.siteId = 'testSiteId';

            oNPNTableauUserMgtBAtchSch.mapIDMResponseElements.put('iserror','false');
            system.debug('*** Active '+commUser);

            NPN_Tableau_UserMgmt__c objNPNTableauUser = NPN_Tableau_UserMgmt__c.getInstance();

            oNPNTableauUserMgtBAtchSch.portalPermissions = objNPNTableauUser.contact_permission__c;


            oNPNTableauUserMgtBAtchSch.execute(null, commUser);

            Test.stopTest();
        }
    }

    @isTest
    static void testBatchClassExecuteUserInactive(){
        Test.setMock(HttpCalloutMock.class, new Mock());        
        makeData();

        List<User> commUser = [SELECT Id,Name, email, username, IsActive, Contact.Portal_Groups__c, ContactId, Tableau_IsUserCreated__c, Tableau_IsUserDeleted__c,
                               Tableau_UserCreationDateTime__c, Tableau_UserCreationLastAPICallResponse__c, Tableau_UserDeletionDateTime__c, Tableau_UserDeletionLastAPICallResponse__c,
                               Tableau_UserId__c, Tableau_Username__c, Tableau_Do_Not_Sync__c, Tableau_API_Response_Failure__c FROM USER WHERE UserName = 'nvpartnerTwo@foo.com.crqext'
                                                                                                                                                          AND (Contact.Portal_Groups__c != null OR Contact.Portal_Groups__c != '')];

        Map<String,String> responseHeaders = new Map<String, String>();
        responseHeaders.put('Content-Type', 'text/xml; charset=utf-8');

        sessionBody = '<?xml version="1.0" encoding="utf-8"?>' +
                             '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"' +
                             'xmlns="urn:partner.soap.sforce.com"' +
                             'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">' +
                             '<soapenv:Body>' +
                             '<loginResponse>' +
                             '<result>' +
                             '<passwordExpired>false</passwordExpired>' +
                             '<serverUrl>https://na1.salesforce.com/services/Soap/u/10.0</serverUrl>' +
                             '<sessionId>QwWsHJyTPW.1pd0_jXlNKOSU</sessionId>' +
                             '<userId>'+commUser[0].Id+'</userId>' +
                             '<userInfo>' +
                             '<!-- ... -->' +
                             '</userInfo>' +
                             '</result>' +
                             '</loginResponse>' +
                             '</soapenv:Body>' +
                             '</soapenv:Envelope>';
        User admin = [SELECT Id FROM User WHERE Profile.Name ='System Administrator' AND IsActive = true LIMIT 1];
        System.runAs(admin){
            Test.startTest();
            NPN_Tableau_UserMgmt_Bat_sch oNPNTableauUserMgtBAtchSch = new NPN_Tableau_UserMgmt_Bat_sch();

            oNPNTableauUserMgtBAtchSch.token  ='1pd0jXlNKOSU';
            oNPNTableauUserMgtBAtchSch.siteRole = 'Viewer';
            oNPNTableauUserMgtBAtchSch.siteId = 'testSiteId';

            oNPNTableauUserMgtBAtchSch.mapIDMResponseElements.put('iserror','false');

            NPN_Tableau_UserMgmt__c objNPNTableauUser = NPN_Tableau_UserMgmt__c.getInstance();

            oNPNTableauUserMgtBAtchSch.portalPermissions = objNPNTableauUser.contact_permission__c;

            system.debug('*** Inactive '+commUser);
            oNPNTableauUserMgtBAtchSch.execute(null, commUser);

            Test.stopTest();
        }
    }


    @isTest
    static void testBatchClassFinish(){

        Test.setMock(HttpCalloutMock.class, new Mock());
        
        makeData();

        List<User> commUser = [SELECT Id,Name, email, username, IsActive, Contact.Portal_Groups__c, ContactId, Tableau_IsUserCreated__c, Tableau_IsUserDeleted__c,
                               Tableau_UserCreationDateTime__c, Tableau_UserCreationLastAPICallResponse__c, Tableau_UserDeletionDateTime__c, Tableau_UserDeletionLastAPICallResponse__c,
                               Tableau_UserId__c, Tableau_Username__c, Tableau_Do_Not_Sync__c, Tableau_API_Response_Failure__c FROM USER WHERE UserName = 'nvvippartnerone@foo.com.crqext' ];

        Map<String,String> responseHeaders = new Map<String, String>();
        responseHeaders.put('Content-Type', 'text/xml; charset=utf-8');

        sessionBody = '<?xml version="1.0" encoding="utf-8"?>' +
                             '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"' +
                             'xmlns="urn:partner.soap.sforce.com"' +
                             'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">' +
                             '<soapenv:Body>' +
                             '<loginResponse>' +
                             '<result>' +
                             '<passwordExpired>false</passwordExpired>' +
                             '<serverUrl>https://na1.salesforce.com/services/Soap/u/10.0</serverUrl>' +
                             '<sessionId>QwWsHJyTPW.1pd0_jXlNKOSU</sessionId>' +
                             '<userId>'+commUser[0].Id+'</userId>' +
                             '<userInfo>' +
                             '<!-- ... -->' +
                             '</userInfo>' +
                             '</result>' +
                             '</loginResponse>' +
                             '</soapenv:Body>' +
                             '</soapenv:Envelope>';

        Test.startTest();        

        NPN_Tableau_UserMgmt_Bat_sch oNPNTableauUserMgtBAtchSch = new NPN_Tableau_UserMgmt_Bat_sch();

        oNPNTableauUserMgtBAtchSch.token  ='1pd0jXlNKOSU';
        oNPNTableauUserMgtBAtchSch.siteRole = 'Viewer';
        oNPNTableauUserMgtBAtchSch.siteId = 'testSiteId';

        oNPNTableauUserMgtBAtchSch.mapIDMResponseElements.put('iserror','false');


        oNPNTableauUserMgtBAtchSch.lstFailureUsers = new List<NPN_Tableau_UserMgmt_Bat_sch.UserFailure>();
        oNPNTableauUserMgtBAtchSch.lstFailureUsers.add(new NPN_Tableau_UserMgmt_Bat_sch.UserFailure(commUser[0],'test Error' ));

        oNPNTableauUserMgtBAtchSch.finish(null);

        Test.stopTest();
    }

    @isTest
    static void testBtachClassStart(){

        Test.setMock(HttpCalloutMock.class, new Mock());
        
        makeData();

        List<User> commUser = [SELECT Id,Name, email, username, IsActive, Contact.Portal_Groups__c, ContactId, Tableau_IsUserCreated__c, Tableau_IsUserDeleted__c,
                               Tableau_UserCreationDateTime__c, Tableau_UserCreationLastAPICallResponse__c, Tableau_UserDeletionDateTime__c, Tableau_UserDeletionLastAPICallResponse__c,
                               Tableau_UserId__c, Tableau_Username__c, Tableau_Do_Not_Sync__c, Tableau_API_Response_Failure__c FROM USER WHERE UserName = 'nvvippartnerone@foo.com.crqext' ];

        Map<String,String> responseHeaders = new Map<String, String>();
        responseHeaders.put('Content-Type', 'text/xml; charset=utf-8');

        sessionBody = '<?xml version="1.0" encoding="utf-8"?>' +
                             '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"' +
                             'xmlns="urn:partner.soap.sforce.com"' +
                             'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">' +
                             '<soapenv:Body>' +
                             '<loginResponse>' +
                             '<result>' +
                             '<passwordExpired>false</passwordExpired>' +
                             '<serverUrl>https://na1.salesforce.com/services/Soap/u/10.0</serverUrl>' +
                             '<sessionId>QwWsHJyTPW.1pd0_jXlNKOSU</sessionId>' +
                             '<userId>'+commUser[0].Id+'</userId>' +
                             '<userInfo>' +
                             '<!-- ... -->' +
                             '</userInfo>' +
                             '</result>' +
                             '</loginResponse>' +
                             '</soapenv:Body>' +
                             '</soapenv:Envelope>';
        Test.startTest();
       
        NPN_Tableau_UserMgmt_Bat_sch oNPNTableauUserMgtBAtchSch = new NPN_Tableau_UserMgmt_Bat_sch();

        Database.QueryLocator qlObj = oNPNTableauUserMgtBAtchSch.start(null);

        Test.stopTest();
    }


    @isTest
    static void syncWithTableauTest(){

        Test.setMock(HttpCalloutMock.class, new Mock());
        
        makeData();

        List<User> commUser = [SELECT Id,Name, email, username, IsActive, Contact.Portal_Groups__c, ContactId, Tableau_IsUserCreated__c, Tableau_IsUserDeleted__c,
                               Tableau_UserCreationDateTime__c, Tableau_UserCreationLastAPICallResponse__c, Tableau_UserDeletionDateTime__c, Tableau_UserDeletionLastAPICallResponse__c,
                               Tableau_UserId__c, Tableau_Username__c, Tableau_Do_Not_Sync__c, Tableau_API_Response_Failure__c FROM USER WHERE UserName = 'nvvippartnerone@foo.com.crqext' ];
        Map<String,String> responseHeaders = new Map<String, String>();
        responseHeaders.put('Content-Type', 'text/xml; charset=utf-8');

        sessionBody = '<?xml version="1.0" encoding="utf-8"?>' +
                             '<root>' +
                             '<element>' +
                             '<loginResponse>' +
                             '<result>' +
                             '<passwordExpired>false</passwordExpired>' +
                             '<serverUrl>https://na1.salesforce.com/services/</serverUrl>' +
                             '<sessionId>QwWsHJyTPW.1pd0_jXlNKOSU</sessionId>' +
                             '<userId>'+commUser[0].Id+'</userId>' +
                             '<userInfo>' +
                             '<!-- ... -->' +
                             '</userInfo>' +
                             '</result>' +
                             '</loginResponse>' +
                             '</element>' +
                             '</root>';

        String newUser = 'testUser';
        String siteRole = 'Viewer';
        String token  ='dptjyeVTXpcJH8B6A6EJtNf0';
        String siteId = 'dptjyeVTXpcJH8B6A6EJtNf0';

        Map<String, String> responseMap = new Map<String, String>();
        Map<String, String> newResponseMap = new Map<String, String>();

        Test.startTest();

        /*NPN_Tableau_UserMgmt_Bat_sch.token  ='dptjyeVTXpcJH8B6A6EJtNf0';
           NPN_Tableau_UserMgmt_Bat_sch.siteRole = 'Viewer';
           NPN_Tableau_UserMgmt_Bat_sch.siteId = 'testSiteId';*/

        //NPN_Tableau_Wrapper.syncWithTableau('testUser', 'Viewer');
        newResponseMap = NPN_Tableau_Wrapper.createTableauUser(newUser, siteRole, siteId, responseMap, token );

        Test.stopTest();
    }

    @isTest
    static void createTableauUserTest(){

        Test.setMock(HttpCalloutMock.class, new Mock());
        
        makeData();

        List<User> commUser = [SELECT Id,Name, email, username, IsActive, Contact.Portal_Groups__c, ContactId, Tableau_IsUserCreated__c, Tableau_IsUserDeleted__c,
                               Tableau_UserCreationDateTime__c, Tableau_UserCreationLastAPICallResponse__c, Tableau_UserDeletionDateTime__c, Tableau_UserDeletionLastAPICallResponse__c,
                               Tableau_UserId__c, Tableau_Username__c, Tableau_Do_Not_Sync__c, Tableau_API_Response_Failure__c FROM USER WHERE UserName = 'nvvippartnerone@foo.com.crqext' ];
        Map<String,String> responseHeaders = new Map<String, String>();
        responseHeaders.put('Content-Type', 'text/xml; charset=utf-8');

        sessionBody = '<?xml version="1.0" encoding="utf-8"?>' +
                             '<root>'+
                             '<element>'+
                             '<loginResponse>' +
                             '<result>' +
                             '<passwordExpired>false</passwordExpired>' +
                             '<serverUrl>https://na1.salesforce.com/services/</serverUrl>' +
                             '<sessionId>QwWsHJyTPW.1pd0_jXlNKOSU</sessionId>' +
                             '<userId>'+commUser[0].Id+'</userId>' +
                             '</result>'+
                             '</loginResponse>' +
                             '</element>' +
                             '<element>'+
                             '<tsRequest>'+
                             '<user name="testUser" siteRole="Viewer" authSetting="SAML"/>'+
                             '</tsRequest>'+
                             '</element>' +
                             '</root>';
      
        String newUser = 'testUser';
        String siteRole = 'Viewer';
        String token  ='dptjyeVTXpcJH8B6A6EJtNf0';
        String siteId = 'dptjyeVTXpcJH8B6A6EJtNf0';

        Map<String, String> responseMap = new Map<String, String>();
        Map<String, String> newResponseMap = new Map<String, String>();
        
        Test.startTest();

        newResponseMap = NPN_Tableau_Wrapper.createTableauUser(newUser, siteRole, siteId, responseMap, token );

        Test.stopTest();
    }


    @isTest
    static void getTableauUserIdrTest(){

        Test.setMock(HttpCalloutMock.class, new Mock());    
        
        makeData();

        List<User> commUser = [SELECT Id,Name, email, username, IsActive, Contact.Portal_Groups__c, ContactId, Tableau_IsUserCreated__c, Tableau_IsUserDeleted__c,
                               Tableau_UserCreationDateTime__c, Tableau_UserCreationLastAPICallResponse__c, Tableau_UserDeletionDateTime__c, Tableau_UserDeletionLastAPICallResponse__c,
                               Tableau_UserId__c, Tableau_Username__c, Tableau_Do_Not_Sync__c, Tableau_API_Response_Failure__c FROM USER WHERE UserName = 'nvvippartnerone@foo.com.crqext' ];
        Map<String,String> responseHeaders = new Map<String, String>();
        responseHeaders.put('Content-Type', 'text/xml; charset=utf-8');

        sessionBody = '<?xml version="1.0" encoding="utf-8"?>' +
                             '<root>'+
                             '<element>'+
                             '<loginResponse>' +
                             '<result>' +
                             '<passwordExpired>false</passwordExpired>' +
                             '<serverUrl>https://na1.salesforce.com/services/</serverUrl>' +
                             '<sessionId>QwWsHJyTPW.1pd0_jXlNKOSU</sessionId>' +
                             '<userId>'+commUser[0].Id+'</userId>' +
                             '</result>'+
                             '</loginResponse>' +
                             '</element>' +
                             '<element>'+
                             '<tsRequest>'+
                             '<user name="testUser" siteRole="Viewer" authSetting="SAML"/>'+
                             '</tsRequest>'+
                             '</element>' +
                             '</root>';
        
        String newUser = 'testUser';
        String siteRole = 'Viewer';
        String token  ='dptjyeVTXpcJH8B6A6EJtNf0';
        String siteId = 'dptjyeVTXpcJH8B6A6EJtNf0';

        Map<String, String> responseMap = new Map<String, String>();
        Map<String, String> newResponseMap = new Map<String, String>();


        responseMap.put('paginationtotalAvailable', '1');

        Test.startTest();

        newResponseMap = NPN_Tableau_Wrapper.getTableauUserId(newUser, siteId, responseMap, token );

        Test.stopTest();
    }



    @isTest
    static void removeTableauUserTest(){

        Test.setMock(HttpCalloutMock.class, new Mock());
        
        makeData();

        List<User> commUser = [SELECT Id,Name, email, username, IsActive, Contact.Portal_Groups__c, ContactId, Tableau_IsUserCreated__c, Tableau_IsUserDeleted__c,
                               Tableau_UserCreationDateTime__c, Tableau_UserCreationLastAPICallResponse__c, Tableau_UserDeletionDateTime__c, Tableau_UserDeletionLastAPICallResponse__c,
                               Tableau_UserId__c, Tableau_Username__c, Tableau_Do_Not_Sync__c, Tableau_API_Response_Failure__c FROM USER WHERE UserName = 'nvvippartnerone@foo.com.crqext' ];
        Map<String,String> responseHeaders = new Map<String, String>();
        responseHeaders.put('Content-Type', 'text/xml; charset=utf-8');

        sessionBody = '<?xml version="1.0" encoding="utf-8"?>' +
                             '<root>'+
                             '<element>'+
                             '<loginResponse>' +
                             '<result>' +
                             '<passwordExpired>false</passwordExpired>' +
                             '<serverUrl>https://na1.salesforce.com/services/</serverUrl>' +
                             '<sessionId>QwWsHJyTPW.1pd0_jXlNKOSU</sessionId>' +
                             '<userId>'+commUser[0].Id+'</userId>' +
                             '</result>'+
                             '</loginResponse>' +
                             '</element>' +
                             '<element>'+
                             '<tsRequest>'+
                             '<user name="testUser" siteRole="Viewer" authSetting="SAML"/>'+
                             '</tsRequest>'+
                             '</element>' +
                             '</root>';
                             
       
        String newUser = 'testUser';
        String siteRole = 'Viewer';
        String token  ='dptjyeVTXpcJH8B6A6EJtNf0';
        String siteId = 'dptjyeVTXpcJH8B6A6EJtNf0';

        Map<String, String> responseMap = new Map<String, String>();
        Map<String, String> newResponseMap = new Map<String, String>();


        responseMap.put('paginationtotalAvailable', '1');

        Test.startTest();
      
        newResponseMap = NPN_Tableau_Wrapper.removeTableauUser(newUser, siteId, responseMap, token );
        Test.stopTest();

    }

    @isTest
    static void signInTest(){
        
        Test.setMock(HttpCalloutMock.class, new Mock());
        makeData();

        List<User> commUser = [SELECT Id,Name, email, username, IsActive, Contact.Portal_Groups__c, ContactId, Tableau_IsUserCreated__c, Tableau_IsUserDeleted__c,
                               Tableau_UserCreationDateTime__c, Tableau_UserCreationLastAPICallResponse__c, Tableau_UserDeletionDateTime__c, Tableau_UserDeletionLastAPICallResponse__c,
                               Tableau_UserId__c, Tableau_Username__c, Tableau_Do_Not_Sync__c, Tableau_API_Response_Failure__c FROM USER WHERE UserName = 'nvvippartnerone@foo.com.crqext' ];
        Map<String,String> responseHeaders = new Map<String, String>();
        responseHeaders.put('Content-Type', 'text/xml; charset=utf-8');

        sessionBody = '<?xml version="1.0" encoding="utf-8"?>' +
                             '<root>'+
                             '<element>'+
                             '<loginResponse>' +
                             '<result>' +
                             '<passwordExpired>false</passwordExpired>' +
                             '<serverUrl>https://na1.salesforce.com/services/</serverUrl>' +
                             '<sessionId>QwWsHJyTPW.1pd0_jXlNKOSU</sessionId>' +
                             '<userId>'+commUser[0].Id+'</userId>' +
                             '</result>'+
                             '</loginResponse>' +
                             '</element>' +
                             '<element>'+
                             '<tsRequest>'+
                             '<user name="testUser" siteRole="Viewer" authSetting="SAML"/>'+
                             '</tsRequest>'+
                             '</element>' +
                             '</root>';
                             
        String newUser = 'testUser';
        String siteRole = 'Viewer';
        String token  ='dptjyeVTXpcJH8B6A6EJtNf0';
        String siteId = 'dptjyeVTXpcJH8B6A6EJtNf0';

        Map<String, String> responseMap = new Map<String, String>();
        Map<String, String> newResponseMap = new Map<String, String>();


        responseMap.put('paginationtotalAvailable', '1');

        Test.startTest();
        newResponseMap = NPN_Tableau_Wrapper.signIn( responseMap );
        Test.stopTest();
    }

    @isTest
    static void signoutTest(){

        Test.setMock(HttpCalloutMock.class, new Mock());
        makeData();

        List<User> commUser = [SELECT Id,Name, email, username, IsActive, Contact.Portal_Groups__c, ContactId, Tableau_IsUserCreated__c, Tableau_IsUserDeleted__c,
                               Tableau_UserCreationDateTime__c, Tableau_UserCreationLastAPICallResponse__c, Tableau_UserDeletionDateTime__c, Tableau_UserDeletionLastAPICallResponse__c,
                               Tableau_UserId__c, Tableau_Username__c, Tableau_Do_Not_Sync__c, Tableau_API_Response_Failure__c FROM USER WHERE UserName = 'nvvippartnerone@foo.com.crqext' ];
        Map<String,String> responseHeaders = new Map<String, String>();
        responseHeaders.put('Content-Type', 'text/xml; charset=utf-8');

        sessionBody = '<?xml version="1.0" encoding="utf-8"?>' +
                             '<root>'+
                             '<element>'+
                             '<loginResponse>' +
                             '<result>' +
                             '<passwordExpired>false</passwordExpired>' +
                             '<serverUrl>https://na1.salesforce.com/services/</serverUrl>' +
                             '<sessionId>QwWsHJyTPW.1pd0_jXlNKOSU</sessionId>' +
                             '<userId>'+commUser[0].Id+'</userId>' +
                             '</result>'+
                             '</loginResponse>' +
                             '</element>' +
                             '<element>'+
                             '<tsRequest>'+
                             '<user name="testUser" siteRole="Viewer" authSetting="SAML"/>'+
                             '</tsRequest>'+
                             '</element>' +
                             '</root>';
               
        String token  ='dptjyeVTXpcJH8B6A6EJtNf0';      
        
        Test.startTest();
        NPN_Tableau_Wrapper.signout(token );
        Test.stopTest();

    }
    
    private class Mock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {
            if (req.getEndpoint().startsWith('https://nvidiacorporation')) {
                HTTPResponse res = new HTTPResponse();
                res.setBody('<?xml version="1.0" encoding="UTF-8"?>'+
           '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/>'+
           '<soapenv:Body><ns:SyncServiceResponse xmlns:ns="http://nvidiasapemsconnector.nvidiaaxis2service.nvidia.smps.gmlto.com">'+
           '<ns:return xmlns:ax21="http://dto.nvidiaaxis2service.nvidia.smps.gmlto.com/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ax21:SyncResponse"><ax21:errorMessage>'+
           '</ax21:errorMessage><ax21:statusCode>success</ax21:statusCode>'+
           '<ax21:syncType>PartnerUser</ax21:syncType></ns:return>'+
           '</ns:SyncServiceResponse></soapenv:Body></soapenv:Envelope>');
                res.setStatusCode(200);
                
                return res;
            } else {
                HTTPResponse res = new HTTPResponse();
                res.setBody(NPN_Tableau_UserMgmt_Bat_sch_Test.sessionBody);
                res.setHeader('Content-Type', 'text/xml; charset=utf-8');
                res.setStatusCode(200);
                return res;
                
            }
        }
    }
}