force-app/main/default/objects/Community_Settings__c/Community_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used to store all settings related to NPN</description>
    <label>Community Settings</label>
</CustomObject>

force-app/main/default/objects/Community_Settings__c/fields/USERNAME_EXTENSION__c.field-meta.xml
<CustomField>
    <fullName>USERNAME_EXTENSION__c</fullName>
    <description>default username extension for bulk sOEM community users</description>
    <inlineHelpText>default username extension for bulk sOEM community users</inlineHelpText>
    <label>USERNAME_EXTENSION</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Create_Full_Portal_User__c.field-meta.xml
<CustomField>
    <fullName>Create_Full_Portal_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Full Portal User ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Create_User__c.field-meta.xml
<CustomField>
    <fullName>Create_User__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Create Lite Portal User ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Portal_Groups__c.field-meta.xml
<CustomField>
    <fullName>Portal_Groups__c</fullName>
    <label>Permissions &amp; Group Assignments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>All Partner Content</fullName>
            </value>
            <value>
                <fullName>Arrow Embedded Edge</fullName>
            </value>
            <value>
                <fullName>ATP</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Compute DGX Portal Full</fullName>
            </value>
            <value>
                <fullName>Compute Portal Full</fullName>
            </value>
            <value>
                <fullName>CSP Compute DGX Elite</fullName>
            </value>
            <value>
                <fullName>CSP Compute DGX Preferred</fullName>
            </value>
            <value>
                <fullName>CSP Compute Elite</fullName>
            </value>
            <value>
                <fullName>CSP Compute Preferred</fullName>
            </value>
            <value>
                <fullName>CSP Virtualization Elite</fullName>
            </value>
            <value>
                <fullName>CSP Virtualization Preferred</fullName>
            </value>
            <value>
                <fullName>CSP Visualization Elite</fullName>
            </value>
            <value>
                <fullName>CSP Visualization Preferred</fullName>
            </value>
            <value>
                <fullName>DGX Partner Content</fullName>
            </value>
            <value>
                <fullName>DISTI Compute DGX Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Compute Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Embedded Edge Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Virtualization Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Visualization Preferred</fullName>
            </value>
            <value>
                <fullName>EDU Lead Registration</fullName>
            </value>
            <value>
                <fullName>Embedded Edge Elite</fullName>
            </value>
            <value>
                <fullName>Embedded Edge Portal Full</fullName>
            </value>
            <value>
                <fullName>Embedded Edge Preferred</fullName>
            </value>
            <value>
                <fullName>Entitlements</fullName>
            </value>
            <value>
                <fullName>Fed SI Compute DGX Elite</fullName>
            </value>
            <value>
                <fullName>Fed SI Compute DGX Preferred</fullName>
            </value>
            <value>
                <fullName>Fed SI Compute Elite</fullName>
            </value>
            <value>
                <fullName>Fed SI Compute Preferred</fullName>
            </value>
            <value>
                <fullName>Fed SI Embedded Edge Elite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Orgin__c.field-meta.xml
<CustomField>
    <fullName>Lead_Orgin__c</fullName>
    <label>Lead Origin</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Auto_Contact Us Form_Web Form_NALA_2016_June</fullName>
            </value>
            <value>
                <fullName>Autodesk_Forum_ES_June_2014</fullName>
            </value>
            <value>
                <fullName>Auto Desk Leads - Dec 2013</fullName>
            </value>
            <value>
                <fullName>Bear Data Golf and Solution Showcase_10.31.2014</fullName>
            </value>
            <value>
                <fullName>BriForum_Denver_Event/Show_NALA_2015_July</fullName>
            </value>
            <value>
                <fullName>BriForum_London_Event/Show_EMEA_2015_May</fullName>
            </value>
            <value>
                <fullName>BriForum NALA 2014</fullName>
            </value>
            <value>
                <fullName>BriForum UK Leads</fullName>
            </value>
            <value>
                <fullName>BVE Event UK 2015</fullName>
            </value>
            <value>
                <fullName>CADD Edge Survey Leads - Nov 2013</fullName>
            </value>
            <value>
                <fullName>Citrix Mobility Germany 2013</fullName>
            </value>
            <value>
                <fullName>Citrix Mobility UK 2013</fullName>
            </value>
            <value>
                <fullName>Citrix Servtech</fullName>
            </value>
            <value>
                <fullName>Citrix Synergy Orlando NALA 2015-05-12</fullName>
            </value>
            <value>
                <fullName>Citrix Synergy Survey Leads - May 2014</fullName>
            </value>
            <value>
                <fullName>Citrix User Group Leads</fullName>
            </value>
            <value>
                <fullName>Citrix Webinar EMEA 2014-9-18</fullName>
            </value>
            <value>
                <fullName>Cornerstone/Dell Gaming &amp; Storage Lunch_8.20.2014</fullName>
            </value>
            <value>
                <fullName>Customer Online Web Configured Solution</fullName>
            </value>
            <value>
                <fullName>EMEA Dell TechFit - Grid Partner Conference</fullName>
            </value>
            <value>
                <fullName>EMEAI Training Web Form</fullName>
            </value>
            <value>
                <fullName>EMEA Supermicro Seeding Program - 2013</fullName>
            </value>
            <value>
                <fullName>Focus Technologies_Casino event_8.7.2014</fullName>
            </value>
            <value>
                <fullName>Focus Technologies_Golf event_9.18.2014</fullName>
            </value>
            <value>
                <fullName>Gotham Winter Technology Exchange</fullName>
            </value>
            <value>
                <fullName>GPU Test Drive.K80 Accelerator</fullName>
            </value>
            <value>
                <fullName>GRID_ASEAN Callout Campaign_Campaign_Program_APAC_2016_July</fullName>
            </value>
            <value>
                <fullName>GRID_Deliver Brilliance_Campaign/Program_EMEA_2015_July</fullName>
            </value>
            <value>
                <fullName>GRID_Deliver Brilliance_India_Campaign/Program_APAC_2015_Sept</fullName>
            </value>
            <value>
                <fullName>GRID_Deliver Brilliance_Penton_Campaign/Program_NALA_2015_July</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContactToUserCreationBatch.cls
global class ContactToUserCreationBatch implements Database.Batchable<sObject>, Database.Stateful{

   global final String Query;
   global list<Id> lstContactId;
   global list<ErrorInsert> lstErrorInsert;
   //global map<String, list<String>> mapPortalGroupListPermissionSet = new map<String, list<String>>();
   //global map<String, String> mapPermissionSetNameID = new map<String, String>();

   global ContactToUserCreationBatch(String q){
      Query=q;
      //this.mapPortalGroupListPermissionSet = mapPortalGroupListPermissionSet;
      //this.mapPermissionSetNameID = mapPermissionSetNameID;
      lstContactId = new list<Id>();
      lstErrorInsert = new list<ErrorInsert>();
   }

   global Database.QueryLocator start(Database.BatchableContext BC){
      return Database.getQueryLocator(query);
   }

   global void execute(Database.BatchableContext BC, List<sObject> scope){
       map<Id,Contact> mapIdContact = new map<Id,Contact>();
       Community_settings__c cs = Community_Settings__c.getInstance();
       map<string, Id> mapProfQPPCPGeneric = COMM_Utility.getProfsByName(COMM_Constants.PROF_CP_QPP_GENERIC);
       map<string, Id> mapProfPPGeneric = COMM_Utility.getProfsByName(COMM_Constants.PROF_PP_TPP_GENERIC);
       List<User> lstNewUsersToBeCreated = new list<User>();
       Database.DMLOptions dmo = new Database.DMLOptions();
       dmo.EmailHeader.triggerUserEmail = true;
       Map<string, COMM_Utility.Community_User_Local_Settings_Wrapper> mapCountryNameLocaleWrapper = COMM_Utility.getCommUserLocalSettings();
       for(sobject s : scope){
           mapIdContact.put(s.id,(Contact)s);                    
       }
       list<User> lstUsers = [select id,contactId from User where contactId in :mapIdContact.keySet()];
       list<Id> lstContactIdExistingUsers = new list<Id>();
       if(lstUsers.size() > 0) {
           for(User objUsr : lstUsers) {
               lstContactIdExistingUsers.add(objUsr.contactId);
               //System.ResetPasswordResult rpr = system.resetPassword(objUsr.Id, true);
           }          
       }
       mapIdContact.keyset().removeAll(lstContactIdExistingUsers);
       for(Id ContactId : mapIdContact.keyset()) {
           User newUser = new User();
           newUser.email = mapIdContact.get(ContactId).Email;
           newUser.firstName = mapIdContact.get(ContactId).FirstName;
           newUser.lastname = mapIdContact.get(ContactId).LastName;
           newUser.title = mapIdContact.get(ContactId).title;
           newUser.companyName = mapIdContact.get(ContactId).account.name;
           if(mapIdContact.get(ContactId).create_full_portal_user__c) {
               newUser.profileid = mapProfPPGeneric.get(COMM_Constants.PROF_PP_TPP_GENERIC);
           } else if(mapIdContact.get(ContactId).create_user__c) {
               newUser.profileid = mapProfQPPCPGeneric.get(COMM_Constants.PROF_CP_QPP_GENERIC);
           }
           newUser.contactId = contactId;
           string strCountry = mapIdContact.get(contactId).MailingCountry;
           if (strCountry != null && mapCountryNameLocaleWrapper.get(strCountry.toUpperCase()) != null){
               newUser.alias = mapCountryNameLocaleWrapper.get(strCountry.toUpperCase()).USER_ALIAS;
               newUser.emailencodingkey = mapCountryNameLocaleWrapper.get(strCountry.toUpperCase()).USER_EMAILENCODEKEY;
               if(mapCountryNameLocaleWrapper.get(strCountry.toUpperCase()).LOCALIZED_PORTAL)
                   newUser.languagelocalekey = mapCountryNameLocaleWrapper.get(strCountry.toUpperCase()).USER_LANGLOCALEKEY;
               else 
                   newUser.languagelocalekey = COMM_Constants.USER_LANGLOCALEKEY;        
               newUser.localesidkey = mapCountryNameLocaleWrapper.get(strCountry.toUpperCase()).USER_LOCALESIDKEY;
               newUser.timezonesidkey = mapCountryNameLocaleWrapper.get(strCountry.toUpperCase()).USER_TZSIDKEY;
           }else {
               newUser.alias = COMM_Constants.USER_ALIAS;
               newUser.emailencodingkey = COMM_Constants.USER_EMAILENCODEKEY;
               newUser.languagelocalekey = COMM_Constants.USER_LANGLOCALEKEY;
               newUser.localesidkey = COMM_Constants.USER_LOCALESIDKEY;
               newUser.timezonesidkey = COMM_Constants.USER_TZSIDKEY;
           }
              
           //if lead origin is EMEAI, then add different extn
           /*if (mapLeadsInTgrNew.get(leadId).lead_orgin__c == COMM_Constants.LEAD_ORIGIN_EMEAI_TRAINING_WEB_FORM){
               newUser.username = mapLeadsInTgrNew.get(leadId).Email + COMM_Constants.USRNAME_EXTN_EMEAI_TRAIN;
           } else{*/
           newUser.username = mapIdContact.get(contactId).Email + '.'+ cs.USERNAME_EXTENSION__c;
           //}
           newUser.setOptions(dmo); //send email notification when new user created
           lstNewUsersToBeCreated.add(newUser);
       }
       Database.SaveResult[] srList = Database.insert(lstNewUsersToBeCreated, false);
       integer count = 0;
       for(Database.SaveResult objSR : srList) {
           if(objSR.isSuccess()) {
               lstContactId.add(lstNewUsersToBeCreated[count].contactid);
           } else {
               lstErrorInsert.add(new ErrorInsert(lstNewUsersToBeCreated[count].contactid, objSR.getErrors()[0].getMessage()));
           }
           count++;
       }
       /*list<PermissionSetAssignment> lstPermissionSetAssignment = new list<PermissionSetAssignment>();
       for(User objUser : lstNewUsersToBeCreated) {
           set<Id> setUserSpecificPermissionSet = new set<Id>();
           if(mapIdContact.containsKey(objUser.contactId) && mapIdContact.get(objUser.contactId) != null && mapIdContact.get(objUser.contactId).portal_groups__c != null) {
               for(String strPortalGroup : mapIdContact.get(objUser.contactId).portal_groups__c.split(';')) {
                   if(mapPortalGroupListPermissionSet.containsKey(strPortalGroup)) {
                       for(String strPermissionSetName : mapPortalGroupListPermissionSet.get(strPortalGroup)) {                           
                           if(mapPermissionSetNameID.containsKey(strPermissionSetName)) {
                               if(!setUserSpecificPermissionSet.contains(mapPermissionSetNameID.get(strPermissionSetName))) {
                                   PermissionSetAssignment objPermissionSetAssignment = new PermissionSetAssignment();
                                   objPermissionSetAssignment.assigneeId = objUser.id;
                                   objPermissionSetAssignment.PermissionSetId = mapPermissionSetNameID.get(strPermissionSetName);
                                   setUserSpecificPermissionSet.add(mapPermissionSetNameID.get(strPermissionSetName));
                                   lstPermissionSetAssignment.add(objPermissionSetAssignment);
                               }
                           }
                       }
                   }
               }
           }
       }
       Database.SaveResult[] lstPSAinsert = Database.insert(lstPermissionSetAssignment, false);*/
       //update scope;
   }

   global void finish(Database.BatchableContext BC){
       
       ContactToUserCreationUpdateBatch objCUCB = new ContactToUserCreationUpdateBatch(lstContactId,lstErrorInsert);
       Database.executeBatch(objCUCB,200);       
   }
   
   global class ErrorInsert {
       public Id contactId;
       public String strErrorMessage;
       public ErrorInsert(Id contactId, String strErrorMessage) {
           this.contactId = contactId;
           this.strErrorMessage = strErrorMessage;
       }
   }
}