force-app/main/default/objects/CPQ_Pricing_Lookup__c/CPQ_Pricing_Lookup__c.object-meta.xml
<CustomObject>
    <description>Contains all pricing data from SAP. It is used to determine product pricing for a specific VAR, Disti, etc.</description>
    <label>CPQ Pricing Lookup</label>
    <nameField>
        <label>CPQ Pricing Lookup Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CPQ Pricing Lookup</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CPQ_Pricing_Lookup__c/fields/Condition_Record_Number__c.field-meta.xml
<CustomField>
    <fullName>Condition_Record_Number__c</fullName>
    <externalId>true</externalId>
    <label>Condition Record Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/CPQ_Pricing_Lookup__c/fields/Condition_Type__c.field-meta.xml
<CustomField>
    <fullName>Condition_Type__c</fullName>
    <label>Condition Type</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPQ_Pricing_Lookup__c/fields/CPQ_Price_Identifier__c.field-meta.xml
<CustomField>
    <fullName>CPQ_Price_Identifier__c</fullName>
    <formula>Name + Condition_Type__c + Inactive_To_String__c + Text(Valid_To__c)</formula>
    <label>CPQ Price Identifier</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CPQ_Pricing_Lookup__c/fields/Inactive_To_String__c.field-meta.xml
<CustomField>
    <fullName>Inactive_To_String__c</fullName>
    <formula>IF( Inactive__c, &quot;TRUE&quot;, &quot;FALSE&quot; )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Inactive To String</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TestCPQPricingLookupTrigger_cls.cls
/******************************************************************************************************************
       * Author: Samar Saha
       * Date: Apr 2021
       * Class Name : TestCPQPricingLookupTrigger_cls
       * Description: Test class for CPQPricingLookupTrigger_cls
******************************************************************************************************************/ 
@isTest
public class TestCPQPricingLookupTrigger_cls 
{   
    @TestSetup
    static void setup() {
        CPQ_Pricing_Lookup__c cpqLook = new CPQ_Pricing_Lookup__c();
        cpqLook.Name = '985-WKS000+P2INR36';
        cpqLook.Condition_Type__c = 'ZPR0';
        cpqLook.Inactive__c = False;
        cpqLook.Valid_To__c = Date.valueof('3999-12-31');
        cpqLook.Condition_Record_Number__c = '0000667853';
        insert cpqLook;
        
        CPQ_Pricing_Lookup__c cpqLook1 = new CPQ_Pricing_Lookup__c();
        cpqLook1.Name = '985-WKS000+P2INR36';
        cpqLook1.Condition_Type__c = 'ZPR0';
        cpqLook1.Inactive__c = False;
        cpqLook1.Valid_To__c = Date.valueof('3999-12-31');
        cpqLook1.Condition_Record_Number__c = '0000367853';
        insert cpqLook1;
        //reset inactive value since trigger made it True
        cpqLook1.Inactive__c = False;
        update cpqLook1;        
    }
    
    @isTest
    static void higherRecordNumber() {
        List<CPQ_Pricing_Lookup__c> cpqLookUpList = [Select Id, Name, Condition_Type__c, Inactive__c, Inactive_To_String__c, Valid_To__c, Condition_Record_Number__c, CPQ_Price_Identifier__c  
                                                         from CPQ_Pricing_Lookup__c where Condition_Record_Number__c = '0000667853'];                                                         
        CPQ_Pricing_Lookup__c cpqLook = new CPQ_Pricing_Lookup__c();
        cpqLook.Name = '985-WKS000+P2INR36';
        cpqLook.Condition_Type__c = 'ZPR0';
        cpqLook.Inactive__c = False;
        cpqLook.Valid_To__c = Date.valueof('3999-12-31');
        cpqLook.Condition_Record_Number__c = '0000867853';
        insert cpqLook;                                                   
    }
    
    @isTest
    static void lowerRecordNumber() {
        List<CPQ_Pricing_Lookup__c> cpqLookUpList = [Select Id, Name, Condition_Type__c, Inactive__c, Inactive_To_String__c, Valid_To__c, Condition_Record_Number__c, CPQ_Price_Identifier__c  
                                                         from CPQ_Pricing_Lookup__c where Condition_Record_Number__c = '0000667853'];                                                         
        CPQ_Pricing_Lookup__c cpqLook = new CPQ_Pricing_Lookup__c();
        cpqLook.Name = '985-WKS000+P2INR36';
        cpqLook.Condition_Type__c = 'ZPR0';
        cpqLook.Inactive__c = False;
        cpqLook.Valid_To__c = Date.valueof('3999-12-31');
        cpqLook.Condition_Record_Number__c = '0000467853';
        insert cpqLook;                                                    
    }
    
    @isTest
    static void updateHigherRecordNumber() {     
        List<CPQ_Pricing_Lookup__c> cpqLookUpList = [Select Id, Name, Condition_Type__c, Inactive__c, Inactive_To_String__c, Valid_To__c, Condition_Record_Number__c, CPQ_Price_Identifier__c  
                                                         from CPQ_Pricing_Lookup__c];                                                                       
        List<CPQ_Pricing_Lookup__c> updateList = new List<CPQ_Pricing_Lookup__c>();
        for(CPQ_Pricing_Lookup__c cpq : cpqLookUpList){
            if(cpq.Condition_Record_Number__c == '0000667853'){
                updateList.add(cpq);
            }
        }
        update updateList;                     
    }
    
    @isTest
    static void updateLowerRecordNumber() {     
        List<CPQ_Pricing_Lookup__c> cpqLookUpList = [Select Id, Name, Condition_Type__c, Inactive__c, Inactive_To_String__c, Valid_To__c, Condition_Record_Number__c, CPQ_Price_Identifier__c  
                                                         from CPQ_Pricing_Lookup__c];                                                                       
        List<CPQ_Pricing_Lookup__c> updateList = new List<CPQ_Pricing_Lookup__c>();
        for(CPQ_Pricing_Lookup__c cpq : cpqLookUpList){
            if(cpq.Condition_Record_Number__c == '0000367853'){
                updateList.add(cpq);
            }
        }
        update updateList;                     
    }
}