force-app/main/default/objects/QPB_Statement__c/QPB_Statement__c.object-meta.xml
<CustomObject>
    <description>NPN: Created for SDS-1406
Stores the QPB details for partners</description>
    <label>QPB Statement</label>
    <nameField>
        <displayFormat>QPBS-{000000}</displayFormat>
        <label>QPB Statement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QPB Statements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QPB_Statement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QPB Statements</relationshipLabel>
    <relationshipName>QPB_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Attachment_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attachment Uploaded?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FY20</fullName>
            </value>
            <value>
                <fullName>FY21</fullName>
            </value>
            <value>
                <fullName>FY22</fullName>
            </value>
            <value>
                <fullName>FY23</fullName>
            </value>
            <value>
                <fullName>FY24</fullName>
            </value>
            <value>
                <fullName>FY25</fullName>
            </value>
            <value>
                <fullName>FY26</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/FY_QTR__c.field-meta.xml
<CustomField>
    <fullName>FY_QTR__c</fullName>
    <formula>RIGHT(TEXT(Fiscal_Year__c), 2) + RIGHT(TEXT(Quarter__c), 1) + IF(ISPICKVAL(Type__c, &apos;Progress&apos;),&apos;1&apos;,&apos;2&apos;)</formula>
    <label>FY_QTR</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Q1</fullName>
            </value>
            <value>
                <fullName>Q2</fullName>
            </value>
            <value>
                <fullName>Q3</fullName>
            </value>
            <value>
                <fullName>Q4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>Progress</fullName>
            </value>
            <value>
                <fullName>MOU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NPN_QPB_Statements_ctlr.cls
/***
 *  @name NPN_QPB_Statements_ctlr
 *  @description    The controller class for NPN_QPB_Statements page. The access to this page is granted to partner users through PP_NPN_QPB_Statements permission set. Created for SDS-1406.
 *  @date 6-Jan-2020
 */
public without sharing class NPN_QPB_Statements_ctlr {

    public boolean showTable {get; set;}
    public list<QPB_Statement__c> QPBStatementsList {get; set;}
    public list<QPBWrapper> lstQPBStatements {get; set;}
    public list<QPBWrapper> lstQPBStatementsUnsorted {get; set;}

    public NPN_QPB_Statements_ctlr() {

        showTable = false;
        QPBStatementsList = new List<QPB_Statement__c>();

        for(QPB_Statement__c qpbObj : [SELECT Id, Account__c, Account__r.Name, Fiscal_Year__c, Quarter__c, Name, Type__c, FY_QTR__c, Status__c, Attachment_Uploaded__c FROM QPB_Statement__c WHERE Account__c IN (SELECT AccountId FROM User WHERE Id =: UserInfo.getUserId()) AND Status__c = 'Active' AND Attachment_Uploaded__c = true ORDER BY FY_QTR__c DESC]) {
            QPBStatementsList.add(qpbObj);
        }

        System.debug('QPBStatementsList '+ QPBStatementsList);
        if(!QPBStatementsList.isEmpty()) {
            showTable = true;
            loadQPBData(QPBStatementsList);
        }else{
            ApexPages.addMessage(new ApexPages.message(ApexPages.severity.INFO,'Your account does not have any QPB Statements available'));
        }
    }

    public void loadQPBData(list<QPB_Statement__c> QPBStatementsList){

        Map<Id, QPB_Statement__c> qpbMap = new Map<Id, QPB_Statement__c>();
        //Map<Id, Id> qpbAttachmentMap = new Map<Id, Id>();
        Map<Id,Id> contentDocLinkedEntityIdMap = new Map<Id, Id>();


        lstQPBStatements = new List<QPBWrapper>();
        lstQPBStatementsUnsorted = new List<QPBWrapper>();

        for(QPB_Statement__c qObj : QPBStatementsList) {
            qpbMap.put(qObj.Id, qObj);
        }

        if(!qpbMap.isEmpty()) {

            List<ContentDocumentLink> lstContentDocumentLink = [SELECT ContentDocumentId, LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId IN :qpbMap.keySet()];

            if(!lstContentDocumentLink.isEmpty()) {
                for(ContentDocumentLink cdlObj : lstContentDocumentLink ) {
                    contentDocLinkedEntityIdMap.put(cdlObj.ContentDocumentId, cdlObj.LinkedEntityId);
                }
            }

            if(!contentDocLinkedEntityIdMap.isEmpty()) {
                for(ContentVersion atcObj : [SELECT ContentDocumentId,Id,VersionData FROM ContentVersion WHERE ContentDocumentId IN :contentDocLinkedEntityIdMap.keySet()]) {
                    String qpbIdStr = contentDocLinkedEntityIdMap.get(atcObj.ContentDocumentId);
                    QPBWrapper qpbWrpObj = new QPBWrapper ();

                    qpbWrpObj.qpbId = qpbMap.get(qpbIdStr).Name;
                    qpbWrpObj.fiscalYear = qpbMap.get(qpbIdStr).Fiscal_Year__c;
                    qpbWrpObj.quarter = qpbMap.get(qpbIdStr).Quarter__c;
                    qpbWrpObj.accountName = qpbMap.get(qpbIdStr).Account__r.Name;
                    qpbWrpObj.fyQtr = Integer.valueOf(qpbMap.get(qpbIdStr).FY_QTR__c);
                    qpbWrpObj.type = qpbMap.get(qpbIdStr).Type__c;
                    qpbWrpObj.attachmentLink = '/apex/ViewPdf?id='+atcObj.ContentDocumentId;

                    lstQPBStatementsUnsorted.add(qpbWrpObj);
                }
            }

            if(!lstQPBStatementsUnsorted.isEmpty()) {
                lstQPBStatements = retSortedList(lstQPBStatementsUnsorted);
            }
        }
    }

    public List<QPBWrapper> retSortedList (List<QPBWrapper> unsortedList){
        List<QPBWrapper> sortedList = new List<QPBWrapper>();

        Integer n = unsortedList.size();
        for (Integer i = 0; i < n-1; i++) {
            for (Integer j = 0; j < n-i-1; j++) {
                if (unsortedList.get(j).fyQtr < unsortedList.get(j+1).fyQtr) {
                    QPBWrapper temp = unsortedList.get(j);
                    unsortedList.set(j, unsortedList.get(j+1));
                    unsortedList.set(j+1, temp);
                }
            }
        }
        sortedList.addAll(unsortedList);
        return sortedList;
    }

    public class QPBWrapper {
        public String attachmentLink {get; set;}
        public String fiscalYear {get; set;}
        public String quarter {get; set;}
        public String accountName {get; set;}
        public String qpbId {get; set;}
        public String type {get; set;}
        public Integer fyQtr {get; set;}
    }
}