force-app/main/default/objects/Announcement__c/Announcement__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : Custom Object for NVIDIA to create Announcements.</description>
    <label>Announcement</label>
    <nameField>
        <label>Announcement Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerAnnouncement__c/CustomerAnnouncement__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : Junction Object to create Announcement records to Accounts based on Announcement creation criteria like Generic, Product and Entitlement</description>
    <label>Announcement</label>
    <nameField>
        <label>Announcement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerAnnouncement__c/fields/Announcement__c.field-meta.xml
<CustomField>
    <fullName>Announcement__c</fullName>
    <label>Announcement</label>
    <referenceTo>Announcement__c</referenceTo>
    <relationshipLabel>Announcements</relationshipLabel>
    <relationshipName>Announcements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Service_Cloud_Error_Log__c/Service_Cloud_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : Error Logs - Stores all integration errors</description>
    <label>Service Cloud Error Log</label>
    <nameField>
        <displayFormat>Err-{000}</displayFormat>
        <label>Service Cloud Error Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Cloud Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Cloud_Error_Log__c/fields/Functionality_Name__c.field-meta.xml
<CustomField>
    <fullName>Functionality_Name__c</fullName>
    <label>Functionality Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch_DeleteAnncAccount.cls
/*
  * @Author: Moon (Perficient)
  * @Created Date: Jan 28, 2018
  * @Desc:	Purpose is to withdraw the announcements for all customer accounts.
  *			- This batch job is invoked by the Announcement Trigger
  *			- The Announcement Trigger invokes this job for 'Archived' announcements only
  *			- Customer Announcement junction object records that reference the archived announcements are deleted by this job 
*/
global class Batch_DeleteAnncAccount implements Database.Batchable<sObject> {
	Set<Id> anncIdSet = new Set<Id>();
	String query;
	
	global Batch_DeleteAnncAccount(Set<Id> tempAnncIdSet) {
		if(tempAnncIdSet != null && !tempAnncIdSet.isEmpty()){
			anncIdSet = tempAnncIdSet;
		}
		query = 'SELECT ID FROM CustomerAnnouncement__c WHERE Announcement__c IN (';
		for(Id anncId : anncIdSet){
			query += '\''+anncId + '\' ,';
		}
		query = query.removeEnd(' ,');
		query += ')';
	}
	
	global Database.QueryLocator start(Database.BatchableContext BC) {
		return Database.getQueryLocator(query);
	}

   	global void execute(Database.BatchableContext BC, List<sObject> scope) {
		List<CustomerAnnouncement__c> juncList = scope;
		Database.DMLOptions dml = new Database.DMLOptions();
		dml.allowFieldTruncation = true;
		try{
			delete juncList;
		}catch(Exception e){			
			Service_Cloud_Error_Log__c dError = new Service_Cloud_Error_Log__c(Functionality_Name__c = 'Customer Announcement Batch Delete', Error_Type__c = 'SALESFORCE BATCH', Error_Description__c = 'Soql query: ' + query + '\n Error: ' + e.getMessage());
			dError.setOptions(dml);
			insert dError;
		}		
	}
	
	global void finish(Database.BatchableContext BC) {
		
	}
	
}