force-app/main/default/objects/Announcement__c/Announcement__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : Custom Object for NVIDIA to create Announcements.</description>
    <label>Announcement</label>
    <nameField>
        <label>Announcement Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Announcement__c/fields/Access_Level__c.field-meta.xml
<CustomField>
    <fullName>Access_Level__c</fullName>
    <label>Access Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generic</fullName>
            </value>
            <value>
                <fullName>Product Specific</fullName>
            </value>
            <value>
                <fullName>Entitlement Specific</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Customer Specific</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Community_User__c.field-meta.xml
<CustomField>
    <fullName>Community_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Community User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/is_DGX_Contact__c.field-meta.xml
<CustomField>
    <fullName>is_DGX_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is DGX Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Synced_IDM_DGX__c.field-meta.xml
<CustomField>
    <fullName>Synced_IDM_DGX__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synced_IDM_DGX</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Hardware_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Hardware_Serial_Number__c</fullName>
    <label>Hardware Serial Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Service_Product__c.field-meta.xml
<CustomField>
    <fullName>Service_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is created to store Product lookup copied from Subscription or manually entered for MRS Products.</description>
    <label>Service Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Entitlements (Service Product)</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Entitlements</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/Test_ESP_DGXStationCoolentNotify_BAT_SCH.cls
@isTest(seeAllData=false)
public class Test_ESP_DGXStationCoolentNotify_BAT_SCH{

@isTest
public static void testDGXNotificationBatch(){
Test.startTest();
Account acc = Test_COMM_Factory.getAccount('dgxAcc');
insert acc;
Contact con = Test_COMM_Factory.getContact(acc.id);
con.is_DGX_Contact__c     = true;
con.Synced_IDM_DGX__c     = true;
insert con;
Profile prof= [select id from Profile where name = 'ESP Community User' limit 1];
User u = Test_COMM_Factory.createUser(con.id,prof.id);
con.community_user__c = u.id;
update con;
Product2 prd = Test_COMM_Factory.getProduct('DGX Station Product Family');
prd.family='DGX Station Product Family';
insert prd;
Contract contr = Test_COMM_Factory.getContract(acc.id);
insert contr;
SBQQ__Subscription__c subsription = Test_COMM_Factory.getSubscription(acc.Id, prd.Id, contr.Id);
insert subsription;
Entitlement ent = Test_COMM_Factory.getEntitlement('DGX Station Product Family',acc.id);
ent.startDate= system.Today().addYears(-1);
ent.EndDate= system.Today().addYears(1);
ent.Service_product__c = prd.id;
ent.Subscription__c = subsription.id;
ent.hardware_serial_number__c = '12345';
insert ent;
Announcement__c announce = Test_COMM_Factory.getAnnouncement('NVIDIA DGX Station Coolant Top Up Kit Now Available',null);
announce.Access_Level__c = 'Customer Specific';
insert announce;
SchedulableContext sc = null;
ESP_DGXStationCoolentNotify_BAT_SCH tsc = new ESP_DGXStationCoolentNotify_BAT_SCH();
tsc.execute(sc);
//ESP_DGXStationCoolentNotify_BAT_SCH dgx = new ESP_DGXStationCoolentNotify_BAT_SCH();
//Database.executeBatch(dgx,20);
Test.stopTest();
}

}