force-app/main/default/objects/SuRF_POS__c/SuRF_POS__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF-POS</label>
    <nameField>
        <displayFormat>SuRF-POS-{00000}</displayFormat>
        <label>SuRF-POS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuRF-POS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_POS__c/fields/Fiscal_Year_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year_Quarter__c</fullName>
    <label>Fiscal Year Quarter</label>
    <length>6</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SuRF_POS__c/fields/POS_Quantity__c.field-meta.xml
<CustomField>
    <fullName>POS_Quantity__c</fullName>
    <label>POS Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SuRF_POS__c/fields/POS_Revenue__c.field-meta.xml
<CustomField>
    <fullName>POS_Revenue__c</fullName>
    <label>POS Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SuRF_POS__c/fields/Target_Achieved__c.field-meta.xml
<CustomField>
    <fullName>Target_Achieved__c</fullName>
    <label>Target Achieved</label>
    <precision>1</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SuRF_POS_Trans__c/SuRF_POS_Trans__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF-POS Trans</label>
    <nameField>
        <displayFormat>SuRF-POS-{00000}</displayFormat>
        <label>SuRF-POS Trans Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuRF-POS Trans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_POS_Trans__c/fields/Partner_POS_Revenue__c.field-meta.xml
<CustomField>
    <fullName>Partner_POS_Revenue__c</fullName>
    <label>Partner POS Revenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SuRF_POS_Trans__c/fields/Partner_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Partner_Unit_Price__c</fullName>
    <label>Partner Unit Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SuRF_POS_Trans__c/fields/Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price__c</fullName>
    <label>Unit Price</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NPN_SuRF_Batch_POS.cls
global class NPN_SuRF_Batch_POS implements Database.batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([SELECT Account_ID__c
                                         ,Competency__c
                                         ,Fiscal_Year_Quarter__c
                                         ,Partner_POS_Revenue__c
                                         ,Partner_Program__c
                                         ,Partner_Unit_Price__c
                                         ,POS_Quantity__c
                                         ,POS_Revenue__c
                                         ,Product_Code__c
                                         ,Target__c
                                         ,Target_Achieved__c
                                         ,Unit_Price__c
                                         ,Partner_SubProgram__c
                                          FROM SuRF_POS__c
                                         WHERE isDeleted = false]);
    }
    global void execute(Database.BatchableContext BC, List<SuRF_POS__c> scope) {
        List<SuRF_POS_Trans__c> lst = new List<SuRF_POS_Trans__c>();
        for(SuRF_POS__c obj : scope) {
            SuRF_POS_Trans__c transObj = new SuRF_POS_Trans__c();
            transObj.Account_ID__c = obj.Account_ID__c;
            transObj.Competency__c = obj.Competency__c;
            transObj.Fiscal_Year_Quarter__c = obj.Fiscal_Year_Quarter__c;
            transObj.Partner_POS_Revenue__c = obj.Partner_POS_Revenue__c;
            transObj.Partner_Program__c = obj.Partner_Program__c;
            transObj.Partner_Unit_Price__c = obj.Partner_Unit_Price__c;
            transObj.POS_Quantity__c = obj.POS_Quantity__c;
            transObj.POS_Revenue__c = obj.POS_Revenue__c;
            transObj.Product_Code__c = obj.Product_Code__c;
            transObj.Target__c = obj.Target__c;
            transObj.Target_Achieved__c = obj.Target_Achieved__c;
            transObj.Unit_Price__c = obj.Unit_Price__c;
            transObj.Partner_SubProgram__c = obj.Partner_SubProgram__c;
            lst.add(transObj);
        }
        insert lst;
    }
    global void finish(Database.BatchableContext BC) {
    }
}