force-app/main/default/objects/PRM_Recent_News__c/PRM_Recent_News__c.object-meta.xml
<CustomObject>
    <description>These objects are displayed on the PRM homepage in the Recent News section.</description>
    <label>PRM Recent News</label>
    <nameField>
        <label>PRM Recent News Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PRM Recent News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PRM_Recent_News__c/fields/Image__c.field-meta.xml
<CustomField>
    <fullName>Image__c</fullName>
    <description>Enter a URL of an image to display in the Recent News section of the PRM homepage.  This image will float to the left.  If a banner image is required, choose one that is an appropriate size (TBD).</description>
    <inlineHelpText>Enter a URL of an image to display in the Recent News section of the PRM homepage.  This image will float to the left.  If a banner image is required, choose one that is an appropriate size (TBD).</inlineHelpText>
    <label>Image</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/PRM_Recent_News__c/fields/News_Text__c.field-meta.xml
<CustomField>
    <fullName>News_Text__c</fullName>
    <description>The text, exactly as it should appear on the PRM homepage.  All formatting, hyperlinks, and other HTML entered here will be transferred verbatim to the page.</description>
    <inlineHelpText>The text, exactly as it should appear on the PRM homepage.  All formatting, hyperlinks, and other HTML entered here will be transferred verbatim to the page.</inlineHelpText>
    <label>News Text</label>
    <length>32000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/PRM_Recent_News__c/fields/Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Sort_Order__c</fullName>
    <description>A sort order must be specified in order to include the news on the PRM homepage.  To remove a news item from the homepage, remove this value.   If multiple news items have a sort order, they will all be displayed in the order specified by this field.</description>
    <inlineHelpText>A sort order must be specified in order to include the news on the PRM homepage.  To remove a news item from the homepage, remove this value.   If multiple news items have a sort order, they will all be displayed in the order specified by this field.</inlineHelpText>
    <label>Sort Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PrmNewsController.cls
/**
 * Returns PRM_Recent_News__c  that should appear on a customized partner
 * portal homepage.
 *
 * @author tschulte@appirio.com
 * @date 06-08-2010
 */
public class PrmNewsController 
{
	public List<PRM_Recent_News__c> getNews() 
	{
		return [SELECT Id, Image__c, News_Text__c FROM PRM_Recent_News__c WHERE Sort_Order__c != null ORDER BY Sort_Order__c ASC];
	}

	@isTest
	public static void testGetNews()
	{
		PrmNewsController controller = new PrmNewsController();
		controller.getNews();
	}
}