force-app/main/default/objects/Asset/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <label>Material Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NV_Component__c/NV_Component__c.object-meta.xml
<CustomObject>
    <description>Service Cloud needs Asset info withMAC addresses from Asset File. 

For Drive Constellation
DGX1
DGX2</description>
    <label>Component</label>
    <nameField>
        <displayFormat>C-{0000000000}</displayFormat>
        <label>Component No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Components</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NV_Component__c/fields/Asset_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Asset_Serial_Number__c</fullName>
    <externalId>true</externalId>
    <label>Asset Serial Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NV_Component__c/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <label>Component Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NV_Component__c/fields/Component_Part__c.field-meta.xml
<CustomField>
    <fullName>Component_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Component_Part</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Components (Component_Part)</relationshipLabel>
    <relationshipName>Components1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NV_Component__c/fields/Component_PN__c.field-meta.xml
<CustomField>
    <fullName>Component_PN__c</fullName>
    <label>Component PN</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NV_Component__c/fields/Material_Number__c.field-meta.xml
<CustomField>
    <fullName>Material_Number__c</fullName>
    <label>Material Number</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NV_Component__c/fields/System_Part__c.field-meta.xml
<CustomField>
    <fullName>System_Part__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>System_Part</label>
    <referenceTo>Part__c</referenceTo>
    <relationshipLabel>Components</relationshipLabel>
    <relationshipName>Components</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Part__c/Part__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : It contains all the Parts (including Full System) that can be RMAed. It contains basically the Product Family, Part Number, Description and Replacement Type. During RMA, the product family is matched up from Customer&apos;s Entitlements and specific part that needs to be RMAed is pulled from this object.</description>
    <label>Part</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Part__c/fields/Component_Part_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Part_Name__c</fullName>
    <label>Component Part Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/Part_Number__c.field-meta.xml
<CustomField>
    <fullName>Part_Number__c</fullName>
    <label>Part Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Part__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>CPU Products</fullName>
            </value>
            <value>
                <fullName>CUDA Services</fullName>
            </value>
            <value>
                <fullName>DGX-1 Pascal Product Family</fullName>
            </value>
            <value>
                <fullName>DGX-1 Volta Product Family</fullName>
            </value>
            <value>
                <fullName>DGX-2 Volta Product Family</fullName>
            </value>
            <value>
                <fullName>DGX A100</fullName>
            </value>
            <value>
                <fullName>DGX Station A100</fullName>
            </value>
            <value>
                <fullName>DGX Station Product Family</fullName>
            </value>
            <value>
                <fullName>Drive Constellation</fullName>
            </value>
            <value>
                <fullName>Embedded Entertainment</fullName>
            </value>
            <value>
                <fullName>GRID Hardware</fullName>
            </value>
            <value>
                <fullName>GRID SW PERPETUAL</fullName>
            </value>
            <value>
                <fullName>GRID SW RENEWAL</fullName>
            </value>
            <value>
                <fullName>GRID SW SUBSCRIPTION</fullName>
            </value>
            <value>
                <fullName>GRID SW SUMS</fullName>
            </value>
            <value>
                <fullName>NGC Support Service - DSWS</fullName>
            </value>
            <value>
                <fullName>NGC Support Service - T4</fullName>
            </value>
            <value>
                <fullName>NGC Support Service - V100</fullName>
            </value>
            <value>
                <fullName>Notebook</fullName>
            </value>
            <value>
                <fullName>NVIDIA Professional Services</fullName>
            </value>
            <value>
                <fullName>Quadro Desktop - EP</fullName>
            </value>
            <value>
                <fullName>Quadro Desktop - HE</fullName>
            </value>
            <value>
                <fullName>Quadro Desktop - MR</fullName>
            </value>
            <value>
                <fullName>Quadro Desktop - NVS</fullName>
            </value>
            <value>
                <fullName>Quadro Desktop - UHE</fullName>
            </value>
            <value>
                <fullName>Quadro Industry Solution</fullName>
            </value>
            <value>
                <fullName>Quadro K20/K40</fullName>
            </value>
            <value>
                <fullName>Quadro Mobile - HE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TestComponentTriggerHelper.cls
@istest
public class TestComponentTriggerHelper {
    
    final static String NAME = 'TestComponentTriggerHelper';
    
    @testsetup
    public static void setup(){
        
        //Create Account
        Account acc = Test_COMM_Factory.getAccount('Test Account');
        insert acc;
        
        //Create Asset - 
        Asset ast 				= Test_COMM_Factory.getAsset(NAME, acc.Id);
        ast.SerialNumber		= 'Test123';
        insert ast;
        
        //System Part Creation
        Part__c systemPart          = Test_COMM_Factory.getPart();
        systemPart.Part_Number__c   = 'systemPart';
        systemPart.Description__c   = 'CRU, FAN DC 12V(92*92*56)';
        systemPart.Product_Family__c= 'DGX-1 Pascal Product Family';
        systemPart.Name             = 'CRU, FAN DC 12V(92*92*56)';
        systemPart.Component_Part_Name__c ='LINKCOMP2';
        insert systemPart;
        
        //Component Part Creation
        Part__c componentPart       = Test_COMM_Factory.getPart();
        componentPart.Part_Number__c= 'componentPart';
        componentPart.Description__c= 'CRU, FAN DC 12V(92*92*56)';
        componentPart.Name          = 'componentPart';
        componentPart.Product_Family__c      ='DGX-1 Pascal Product Family';
        componentPart.Component_Part_Name__c ='LINKCOMP2';
        insert componentPart;
    }
    
    @istest
    public static void TestAutopopulatePartDetails(){
        
        Test.startTest();
        
        //Test System Part Auto populate
        NV_Component__c comp1   	= Test_COMM_Factory.getComponent();
        comp1.Material_Number__c	= 'systemPart';
        comp1.Component_Name__c 	= 'sample-comp1';
        comp1.Asset_Serial_Number__c= 'Test123';
        insert comp1;
        
        comp1 = [select Id, Material_Number__c, System_Part__r.Part_Number__c from NV_Component__c where id =: comp1.Id];
        system.assertNotEquals(Null, comp1.System_Part__c);
        system.assertEquals(comp1.Material_Number__c, comp1.System_Part__r.Part_Number__c);
        
        comp1.System_Part__c    = null;
        update comp1;
        
        comp1 = [select Id, Material_Number__c, System_Part__r.Part_Number__c from NV_Component__c where id =: comp1.Id];
        system.assertNotEquals(Null, comp1.System_Part__c);
        system.assertEquals(comp1.Material_Number__c, comp1.System_Part__r.Part_Number__c);
        
        //Test Component Part Auto populate
        NV_Component__c comp2   = Test_COMM_Factory.getComponent();
        comp2.Component_PN__c   = 'componentPart';
        comp2.Component_Name__c = 'sample-comp2';
        insert comp2;
        comp2 = [select Id, Component_PN__c, Component_Part__r.Part_Number__c from NV_Component__c where id =: comp2.Id];
        system.assertNotEquals(Null, comp2.Component_Part__c);
        system.assertEquals(comp2.Component_PN__c, comp2.Component_Part__r.Part_Number__c);
        
        comp2.Component_Part__c = null;
        update comp2;
        comp2 = [select Id, Component_PN__c, Component_Part__r.Part_Number__c from NV_Component__c where id =: comp2.Id];
        system.assertNotEquals(Null, comp2.Component_Part__c);
        system.assertEquals(comp2.Component_PN__c, comp2.Component_Part__r.Part_Number__c);
        
        Test.stopTest();
    }
}