force-app/main/default/objects/Dev_Account__c/Dev_Account__c.object-meta.xml
<CustomObject>
    <description>Developer Marketing : Accounts</description>
    <label>Dev Account</label>
    <nameField>
        <displayFormat>Dev-A-{0000000}</displayFormat>
        <label>Dev Account Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dev Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dev_Account__c/fields/Dev_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Dev_Account_Name__c</fullName>
    <label>Dev Account Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dev_Contact__c/Dev_Contact__c.object-meta.xml
<CustomObject>
    <description>Developer Marketing : Contacts</description>
    <label>Dev Contact</label>
    <nameField>
        <displayFormat>DC-{0000000}</displayFormat>
        <label>Dev Contact Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Dev Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Dev_Contact__c/fields/Anonymization_Reason__c.field-meta.xml
<CustomField>
    <fullName>Anonymization_Reason__c</fullName>
    <description>Stores the reason a record was decided to be anonymized.</description>
    <label>Anonymization Reason</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Privacy Data Delete Request</fullName>
            </value>
            <value>
                <fullName>NVIDIA Data Retention Privacy Policy</fullName>
            </value>
            <value>
                <fullName>Deleted for Business Reasons</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dev_Contact__c/fields/Anonymized__c.field-meta.xml
<CustomField>
    <fullName>Anonymized__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates if a field is anonymized or not. This is part of the solution to stay compliant with General Data Protection Regulation (GDPR) and NVIDIA Privacy Policy of not retaining user information of those who we have not engaged with beyond the last 5 years.</description>
    <label>Anonymized</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Dev_Contact__c/fields/Dev_Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Dev_Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Dev Account Name</label>
    <referenceTo>Dev_Account__c</referenceTo>
    <relationshipLabel>Dev Contacts</relationshipLabel>
    <relationshipName>Dev_Contacts</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Dev_Contact__c/fields/Email2__c.field-meta.xml
<CustomField>
    <fullName>Email2__c</fullName>
    <caseSensitive>true</caseSensitive>
    <complianceGroup>PII</complianceGroup>
    <description>Stores the secondary e-mail as provided by a given developer.</description>
    <label>Email2</label>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Dev_Contact__c/fields/Email__c.field-meta.xml
<CustomField>
    <fullName>Email__c</fullName>
    <caseSensitive>true</caseSensitive>
    <complianceGroup>PII</complianceGroup>
    <label>Email</label>
    <required>true</required>
    <type>Email</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Dev_Contact__c/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dev_Contact__c/fields/Industry_Segment_Vertical__c.field-meta.xml
<CustomField>
    <fullName>Industry_Segment_Vertical__c</fullName>
    <label>Industry Segment/Vertical</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aerospace</fullName>
            </value>
            <value>
                <fullName>Architecture / Engineering / Construction</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Cloud Services</fullName>
            </value>
            <value>
                <fullName>Consulting Services</fullName>
            </value>
            <value>
                <fullName>Defense</fullName>
            </value>
            <value>
                <fullName>Energy / Oil &amp; Gas</fullName>
            </value>
            <value>
                <fullName>Financial Services</fullName>
            </value>
            <value>
                <fullName>Game Development</fullName>
            </value>
            <value>
                <fullName>Government / National Labs</fullName>
            </value>
            <value>
                <fullName>Hardware / Semiconductor</fullName>
            </value>
            <value>
                <fullName>Healthcare &amp; Life Sciences</fullName>
            </value>
            <value>
                <fullName>Higher Education / Research</fullName>
            </value>
            <value>
                <fullName>Internet / Telecommunications</fullName>
            </value>
            <value>
                <fullName>IT Services</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Media &amp; Entertainment</fullName>
            </value>
            <value>
                <fullName>Retail / Etail</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Other (please specify)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Dev_Contact__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <complianceGroup>PII</complianceGroup>
    <label>Last Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Dev_Contact__c/fields/Source_User_ID__c.field-meta.xml
<CustomField>
    <fullName>Source_User_ID__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>This field will store the developer user id provided by the API from the source (in this case, DevZone). This is required for MuleSoft comparisons and debugging.</description>
    <externalId>true</externalId>
    <label>Source User ID</label>
    <length>32</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Test_Dev_Contact_GDPR_tgr.cls
/*
 Author: Jasek Arent
 Comments:
    Test class for Dev_Contact_GDPR_tgr

*/
@isTest (SeeAllData=false)
public class Test_Dev_Contact_GDPR_tgr {
    
    @testSetup static void setUpDevContact() {
        
       Dev_Account__c devAccount = new Dev_Account__c();
       devAccount.Dev_Account_Name__c = 'TestDevAccount';
       insert devAccount;
        
       Dev_Contact__c devContact = new Dev_Contact__c();
       devContact.Dev_Account_Name__c = devAccount.Id;
       devContact.First_Name__c = 'TestFirstName';
       devContact.Last_Name__c = 'TestLastName';
       devContact.Email__c = 'testlastname20200414001@iamai.com';
       devContact.Email2__c = 'testlastname@iamai2.com';
       devContact.Source_User_ID__c = 'GDPR_TEST_1';
       devContact.Industry_Segment_Vertical__c = 'HPC';
       insert devContact;
        
       devContact = new Dev_Contact__c();
       devContact.Dev_Account_Name__c = devAccount.Id;
       devContact.First_Name__c = 'TestFirstName';
       devContact.Last_Name__c = 'TestLastName';
       devContact.Email__c = 'testIsAnonymized@iamai.com';
       devContact.Source_User_ID__c = 'GDPR_TEST_2';
       devContact.Industry_Segment_Vertical__c = 'HPC';
       insert devContact; 
        
       devContact = new Dev_Contact__c();
       devContact.Dev_Account_Name__c = devAccount.Id;
       devContact.First_Name__c = 'TestFirstName';
       devContact.Last_Name__c = 'TestLastName';
       devContact.Email__c = 'testlastname3@iamai.com';
       devContact.Source_User_ID__c = 'GDPR_TEST_3';
       devContact.Industry_Segment_Vertical__c = 'HPC';
       insert devContact;
    }
    
    @isTest
    static void Should_Anonymize_PII_Data() {
   
        Dev_Contact__c devContact = [SELECT ID, Anonymized__c FROM Dev_Contact__c WHERE Source_User_ID__c = 'GDPR_TEST_1'];
        System.assert(devContact != null);
        
        devContact.Anonymized__c = true;
        devContact.Anonymization_Reason__c = 'Privacy Data Delete Request';
        
        update devContact;        
        
        devContact = [SELECT ID, Email__c, Email2__c, Last_Name__c, First_Name__c, Anonymization_Reason__c FROM Dev_Contact__c WHERE Source_User_ID__c = 'GDPR_TEST_1'];
        
        System.assert(devContact.Email__c.contains('iamai.com'), 'Email domain must be preserved');
        System.assert(devContact.Email2__c.contains('iamai2.com'), 'Email domain must be preserved');
        
        System.debug(devContact.Last_Name__c);
        System.debug(devContact.First_Name__c);
        System.debug(devContact.Email__c);
        System.debug(devContact.Email2__c);
        System.debug(devContact.Anonymization_Reason__c);
    }
    
    @isTest
    static void Should_Not_Allow_For_Reverting_Anonymized() {
        Dev_Contact__c devContact = [SELECT ID, Anonymized__c FROM Dev_Contact__c WHERE Source_User_ID__c = 'GDPR_TEST_2'];
        System.assert(devContact != null);
        
        devContact.Anonymized__c = true;
        devContact.Anonymization_Reason__c = 'Privacy Data Delete Request';
        
        update devContact;
        
        devContact.Anonymized__c = false;
        
        try {
            update devContact;
            System.assert(false, 'Should fail update');
        } catch (Exception e) {
            System.debug('Expected error: ' + e);
        }
        
        devContact.Anonymized__c = true;
        
        try {
            update devContact;
            System.assert(false, 'Should fail update');
        } catch (Exception e) {
            System.debug('Expected error: ' + e);
        }
        
    }
    
    @isTest
    static void Should_Require_Anonymization_Reasone() {
   
        Dev_Contact__c devContact = [SELECT ID, Anonymized__c FROM Dev_Contact__c WHERE Source_User_ID__c = 'GDPR_TEST_3'];
        System.assert(devContact != null);
        
        devContact.Anonymized__c = true;
        
        try {
            update devContact;
            System.assert(false, 'Should fail update');
        } catch (Exception e) {
            System.debug('Expected error: ' + e);
        }    
    }
    
    @isTest
    static void Should_Fail_Insert_Anonymized() {
       Dev_Account__c devAccount = [SELECT ID FROM Dev_Account__c WHERE Dev_Account_Name__c = 'TestDevAccount'];
        
       Dev_Contact__c devContact = new Dev_Contact__c();
       devContact.Dev_Account_Name__c = devAccount.Id;
       devContact.First_Name__c = 'TestFirstName';
       devContact.Last_Name__c = 'TestLastName';
       devContact.Email__c = 'willfail@iamai.com';
       devContact.Source_User_ID__c = 'GDPR_TEST_FAIL';
       devContact.Industry_Segment_Vertical__c = 'HPC';
       devContact.Anonymized__c = true;
       
       try {
            insert devContact;
            System.assert(false, 'Should fail insert');
        } catch (Exception e) {
            System.debug('Expected error: ' + e);
        }    
    }

}