force-app/main/default/objects/NV_Contacts__c/NV_Contacts__c.object-meta.xml
<CustomObject>
    <description>NPN : Contains NV Contacts shown to NPN Partner Users/Community users based on their Program/Competency/Region/Account</description>
    <label>NV Contact</label>
    <nameField>
        <label>NV Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NV Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NV_Contacts__c/fields/Account_Owner_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Owner_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Owner Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NV_Contacts1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NV_Contacts__c/fields/Billing_Country__c.field-meta.xml
<CustomField>
    <fullName>Billing_Country__c</fullName>
    <label>Billing Country</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Aland Islands</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Andorra</fullName>
            </value>
            <value>
                <fullName>Angola</fullName>
            </value>
            <value>
                <fullName>Anguilla</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Aruba</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Belize</fullName>
            </value>
            <value>
                <fullName>Benin</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Bouvet Island</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>British Virgin Islands</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NV_Contacts__c/fields/Marketing_Manager_Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Manager_Contact_Number__c</fullName>
    <label>Marketing Manager Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/NV_Contacts__c/fields/Marketing_Manager_Email__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Manager_Email__c</fullName>
    <label>Marketing Manager Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/NV_Contacts__c/fields/Marketing_Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>Marketing_Manager_Name__c</fullName>
    <label>Marketing Manager Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NV_Contacts__c/fields/Other_States__c.field-meta.xml
<CustomField>
    <fullName>Other_States__c</fullName>
    <label>Other States/Territory</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NV_Contacts__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Competency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>NVEP</fullName>
            </value>
            <value>
                <fullName>Virtualization</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Embedded</fullName>
            </value>
            <value>
                <fullName>Compute DGX</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Compute</fullName>
            </value>
            <value>
                <fullName>Visualization</fullName>
            </value>
            <value>
                <fullName>Embedded Edge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NV_Contacts__c/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <label>Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Cloud Service Provider</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Federal Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Global Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Inception Partner</fullName>
            </value>
            <value>
                <fullName>Industry Focus</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Service Delivery Partner</fullName>
            </value>
            <value>
                <fullName>Solution Advisor</fullName>
            </value>
            <value>
                <fullName>Solution Provider</fullName>
            </value>
            <value>
                <fullName>Solutions Integration Partner</fullName>
            </value>
            <value>
                <fullName>Tegra Embedded</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NV_Contacts__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NALA</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEAI</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NV_Contacts__c/fields/Sales_Manager_Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager_Contact_Number__c</fullName>
    <label>Sales Manager Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/NV_Contacts__c/fields/Sales_Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>Sales_Manager_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sales Manager Name</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NV_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NV_Contacts__c/fields/Sales_Title__c.field-meta.xml
<CustomField>
    <fullName>Sales_Title__c</fullName>
    <inlineHelpText>This titile is for sales manager.</inlineHelpText>
    <label>Sales Title</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/NV_Contacts__c/fields/Sub_Program__c.field-meta.xml
<CustomField>
    <fullName>Sub_Program__c</fullName>
    <label>Sub Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Educational Services</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Data Center Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NV_Contacts__c/fields/Sub_Region__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region__c</fullName>
    <label>Sub-Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>SEA</fullName>
            </value>
            <value>
                <fullName>EE</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>SASIA</fullName>
            </value>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>MIAMI</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>KOREA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NV_Contacts__c/fields/Support_Manager_Contact_Number__c.field-meta.xml
<CustomField>
    <fullName>Support_Manager_Contact_Number__c</fullName>
    <label>Support Manager Contact Number</label>
    <type>Phone</type>
</CustomField>

force-app/main/default/objects/NV_Contacts__c/fields/Support_Manager_Email__c.field-meta.xml
<CustomField>
    <fullName>Support_Manager_Email__c</fullName>
    <label>Support Manager Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/NV_Contacts__c/fields/Support_Manager_Name__c.field-meta.xml
<CustomField>
    <fullName>Support_Manager_Name__c</fullName>
    <label>Support Manager Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NV_Contacts__c/fields/US_States__c.field-meta.xml
<CustomField>
    <fullName>US_States__c</fullName>
    <label>US States</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Billing_Country__c</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>Alabama</fullName>
            </value>
            <value>
                <fullName>Alaska</fullName>
            </value>
            <value>
                <fullName>Arizona</fullName>
            </value>
            <value>
                <fullName>Arkansas</fullName>
            </value>
            <value>
                <fullName>California</fullName>
            </value>
            <value>
                <fullName>Colorado</fullName>
            </value>
            <value>
                <fullName>Connecticut</fullName>
            </value>
            <value>
                <fullName>Delaware</fullName>
            </value>
            <value>
                <fullName>Florida</fullName>
            </value>
            <value>
                <fullName>Georgia</fullName>
            </value>
            <value>
                <fullName>Hawaii</fullName>
            </value>
            <value>
                <fullName>Idaho</fullName>
            </value>
            <value>
                <fullName>Illinois</fullName>
            </value>
            <value>
                <fullName>Indiana</fullName>
            </value>
            <value>
                <fullName>Iowa</fullName>
            </value>
            <value>
                <fullName>Kansas</fullName>
            </value>
            <value>
                <fullName>Kentucky</fullName>
            </value>
            <value>
                <fullName>Lousiana</fullName>
            </value>
            <value>
                <fullName>Maine</fullName>
            </value>
            <value>
                <fullName>Maryland</fullName>
            </value>
            <value>
                <fullName>Massachusetts</fullName>
            </value>
            <value>
                <fullName>Michigan</fullName>
            </value>
            <value>
                <fullName>Minnesota</fullName>
            </value>
            <value>
                <fullName>Mississippi</fullName>
            </value>
            <value>
                <fullName>Missouri</fullName>
            </value>
            <value>
                <fullName>Montana</fullName>
            </value>
            <value>
                <fullName>Nebraska</fullName>
            </value>
            <value>
                <fullName>Neveda</fullName>
            </value>
            <value>
                <fullName>New Hampshire</fullName>
            </value>
            <value>
                <fullName>New Jersey</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Used in Enterprise KPIs and Other dashboards</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>NALA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NV_UtilityClass.cls
public class NV_UtilityClass {
     //--------------------------------------------------------------------------------------------------------
    //set lstNVIDIAContactsWrapper object
    // Extracting NV Contacts data based on filtered logic. Preventing to add same content type records into list. If duplicate record exist using third filter with Account Owner.
     //--------------------------------------------------------------------------------------------------------
     //--------------------------------------------------------------------------------------------------------
    //set lstNVIDIAContactsWrapper object
    // Extracting NV Contacts data based on filtered logic. Preventing to add same content type records into list. If duplicate record exist using third filter with Account Owner.
     //--------------------------------------------------------------------------------------------------------
    public static list<NVIDIAContactsProductWiseWrapper> putAllNVIDIACONTACTDetail(Contact contactDetail, set<string> allProgramTypeContentType){       
        /*Map<string,integer> mapContentTypeAndUSStates = new Map<string,integer>();
        Map<string,integer> mapContentTypeAndOtherStates = new Map<string,integer>();           
        Map<string,integer> mapContentTypeAndBlankStates = new Map<string,integer>();   
        */
        list<NVIDIAContactsProductWiseWrapper> lstNVIDIAContactsProductWiseWrapper = new list<NVIDIAContactsProductWiseWrapper>();
        map<String, list<NVContactPriorityWrapper>> mapProgramTypeContentTypeLstNVContact = new map<String, list<NVContactPriorityWrapper>>(); 
        List<NV_Contacts__c> lstNVContact =   new List<NV_Contacts__c>();
        boolean IsContenttypeFound = false;
        List<NV_Contacts__c> lstNVContactstocompare = [ SELECT Billing_Country__c, Other_States__c, Account_Owner_Name__c, US_States__c, Marketing_Manager_Contact_Number__c, Sub_Region__c,
                                                            Marketing_Manager_Email__c, Marketing_Manager_Name__c, Product_Line__c, Sales_Manager_Contact_Number__c, Program_Type__c, Sub_Program__c,
                                                            Sales_Manager_Email__c, Sales_Manager_Name__c, Sales_Manager_Name__r.Name, Support_Manager_Contact_Number__c, Region__c,
                                                            Support_Manager_Email__c, Support_Manager_Name__c, Sales_Title__c, Marketing_Title__c, Support_Title__c, ProgramType_Competency_Concatenation__c   
                                                        FROM NV_Contacts__c 
                                                        WHERE (ProgramType_Competency_Concatenation__c in :allProgramTypeContentType
                                                        AND (
                                                               Billing_Country__c = :contactDetail.Account.BillingCountry 
                                                            OR Region__c = :contactDetail.Account.Billing_Region__c
                                                            OR Sub_Region__c = :contactDetail.Account.Billing_Sub_Region__c
                                                            OR Account_Owner_Name__c =:contactDetail.Account.OwnerId
                                                        ))
                                                        ];
                                                        
        for(NV_Contacts__c objNV : lstNVContactstocompare) {
            if(objNV.Billing_Country__c == contactDetail.Account.BillingCountry
                && (objNV.US_States__c == contactDetail.Account.BillingState 
                    || objNV.Other_States__c == contactDetail.Account.BillingState )) {
                if(!mapProgramTypeContentTypeLstNVContact.containsKey(objNV.ProgramType_Competency_Concatenation__c)){
                    mapProgramTypeContentTypeLstNVContact.put(objNV.ProgramType_Competency_Concatenation__c, new list<NVContactPriorityWrapper> { new NVContactPriorityWrapper(1,objNV)});
                }else {
                    mapProgramTypeContentTypeLstNVContact.get(objNV.ProgramType_Competency_Concatenation__c).add(new NVContactPriorityWrapper(1,objNV));                                                    
                }
            } else if(objNV.Billing_Country__c == contactDetail.Account.BillingCountry) {
                if(!mapProgramTypeContentTypeLstNVContact.containsKey(objNV.ProgramType_Competency_Concatenation__c)){
                    mapProgramTypeContentTypeLstNVContact.put(objNV.ProgramType_Competency_Concatenation__c, new list<NVContactPriorityWrapper> { new NVContactPriorityWrapper(2,objNV)});
                }else {
                    mapProgramTypeContentTypeLstNVContact.get(objNV.ProgramType_Competency_Concatenation__c).add(new NVContactPriorityWrapper(2,objNV));                                                    
                }
            } else if(objNV.Region__c == contactDetail.Account.Billing_Region__c) {
                if(!mapProgramTypeContentTypeLstNVContact.containsKey(objNV.ProgramType_Competency_Concatenation__c)){
                    mapProgramTypeContentTypeLstNVContact.put(objNV.ProgramType_Competency_Concatenation__c, new list<NVContactPriorityWrapper> { new NVContactPriorityWrapper(3,objNV)});
                }else {
                    mapProgramTypeContentTypeLstNVContact.get(objNV.ProgramType_Competency_Concatenation__c).add(new NVContactPriorityWrapper(3,objNV));                                                    
                }
            } else if(objNV.Sub_Region__c == contactDetail.Account.Billing_Sub_Region__c) {
                if(!mapProgramTypeContentTypeLstNVContact.containsKey(objNV.ProgramType_Competency_Concatenation__c)){
                    mapProgramTypeContentTypeLstNVContact.put(objNV.ProgramType_Competency_Concatenation__c, new list<NVContactPriorityWrapper> { new NVContactPriorityWrapper(4,objNV)});
                }else {
                    mapProgramTypeContentTypeLstNVContact.get(objNV.ProgramType_Competency_Concatenation__c).add(new NVContactPriorityWrapper(4,objNV));                                                    
                }
            } else if(objNV.Account_Owner_Name__c == contactDetail.Account.OwnerId) {
                if(!mapProgramTypeContentTypeLstNVContact.containsKey(objNV.ProgramType_Competency_Concatenation__c)){
                    mapProgramTypeContentTypeLstNVContact.put(objNV.ProgramType_Competency_Concatenation__c, new list<NVContactPriorityWrapper> { new NVContactPriorityWrapper(5,objNV)});
                }else {
                    mapProgramTypeContentTypeLstNVContact.get(objNV.ProgramType_Competency_Concatenation__c).add(new NVContactPriorityWrapper(5,objNV));                                                    
                }
            }
        }
        
        system.debug(mapProgramTypeContentTypeLstNVContact);
        List<NV_Contacts__c> lstNVContactsToBeEmailed = new List<NV_Contacts__c>();
        for(String strProgramTypeContentType : mapProgramTypeContentTypeLstNVContact.keyset()) {
            list<NVContactPriorityWrapper> lstNVContactPriorityWrapper = mapProgramTypeContentTypeLstNVContact.get(strProgramTypeContentType);
            if(lstNVContactPriorityWrapper.size() == 1) {
                lstNVContact.add(lstNVContactPriorityWrapper[0].objNVContact);
            } else {
                NVContactPriorityWrapper tempNVContactPriorityWrapper;
                Map<Decimal, List<NV_Contacts__c>> mapPriorityListNVContact = new Map<Decimal, List<NV_Contacts__c>>();
                for(NVContactPriorityWrapper objNVContactPriorityWrapper : lstNVContactPriorityWrapper) {
                    if(tempNVContactPriorityWrapper == null) {
                        tempNVContactPriorityWrapper = objNVContactPriorityWrapper;
                    } else if(tempNVContactPriorityWrapper.decPriority > objNVContactPriorityWrapper.decPriority) {
                        tempNVContactPriorityWrapper = objNVContactPriorityWrapper;
                        mapPriorityListNVContact.clear();
                    } else if(tempNVContactPriorityWrapper.decPriority == objNVContactPriorityWrapper.decPriority) {
                        if(objNVContactPriorityWrapper.objNVContact.Account_Owner_Name__c == contactDetail.Account.OwnerId) {
                            tempNVContactPriorityWrapper = objNVContactPriorityWrapper;
                            mapPriorityListNVContact.clear();
                        } else if(tempNVContactPriorityWrapper.objNVContact.Account_Owner_Name__c == contactDetail.Account.OwnerId) {
                            mapPriorityListNVContact.clear();
                        } else {    
                            if(!mapPriorityListNVContact.containsKey(tempNVContactPriorityWrapper.decPriority)) {
                                mapPriorityListNVContact.put(tempNVContactPriorityWrapper.decPriority, new list<NV_Contacts__c> {tempNVContactPriorityWrapper.objNVContact,objNVContactPriorityWrapper.objNVContact});
                            } else {
                                mapPriorityListNVContact.get(tempNVContactPriorityWrapper.decPriority).add(objNVContactPriorityWrapper.objNVContact);
                            }
                        }
                    }
                }
                if(!mapPriorityListNVContact.isEmpty()) {
                    lstNVContactsToBeEmailed.addAll(mapPriorityListNVContact.get(tempNVContactPriorityWrapper.decPriority));
                    system.debug(lstNVContactsToBeEmailed);
                    mapPriorityListNVContact.clear();
                }
                lstNVContact.add(tempNVContactPriorityWrapper.objNVContact);
            }
            
        }
        
        map<String, list<NVIDIAContactsWrapper>> mapProductTypeLstNVContactsWrapper = new map<String, list<NVIDIAContactsWrapper>>();  
        for(NV_Contacts__c obj :lstNVContact){
            
            NVIDIAContactsWrapper objWrapNV = new NVIDIAContactsWrapper();
            objWrapNV.contentType = obj.Product_Line__c;
            objWrapNV.subProgram = obj.Sub_Program__c;
                
            objWrapNV.Marketing_Manager_Name = obj.Marketing_Manager_Name__c;
            objWrapNV.Marketing_Manager_Email = obj.Marketing_Manager_Email__c;
            objWrapNV.Marketing_Manager_Contact_Number = string.valueOf(obj.Marketing_Manager_Contact_Number__c);
                
            objWrapNV.Sales_Manager_Name = obj.Sales_Manager_Name__r.Name;
            objWrapNV.Sales_Manager_Email = obj.Sales_Manager_Email__c;
            objWrapNV.Sales_Manager_Contact_Number = string.valueOf(obj.Sales_Manager_Contact_Number__c);
                
            objWrapNV.Support_Manager_Name = obj.Support_Manager_Name__c;
            objWrapNV.Support_Manager_Email = obj.Support_Manager_Email__c;
            objWrapNV.Support_Manager_Contact_Number = string.valueOf(obj.Support_Manager_Contact_Number__c);
                
            objWrapNV.SalesManager_Title1 = obj.Sales_Title__c;
            objWrapNV.MarketingManager_Title2 = obj.Marketing_Title__c;
            objWrapNV.SupportManager_Title3 = obj.Support_Title__c;

            if(!mapProductTypeLstNVContactsWrapper.containsKey(obj.Program_Type__c)) {
                mapProductTypeLstNVContactsWrapper.put(obj.Program_Type__c, new list<NVIDIAContactsWrapper>{objWrapNV});
            } else {
                mapProductTypeLstNVContactsWrapper.get(obj.Program_Type__c).add(objWrapNV);
            }

        }
        system.debug(mapProductTypeLstNVContactsWrapper);
        for(String strProgramType : mapProductTypeLstNVContactsWrapper.keyset()) {
            lstNVIDIAContactsProductWiseWrapper.add(new NVIDIAContactsProductWiseWrapper(strProgramType.toUpperCase(), mapProductTypeLstNVContactsWrapper.get(strProgramType)));
        }
        return lstNVIDIAContactsProductWiseWrapper;
    }
  //--------------------------------------------------------------------------------------------------------
    
    //--------------------------------------------------------------------------------------------------------
    // Wrapper class to consolidate NVIDIA CONTACT Grid details.     
    //--------------------------------------------------------------------------------------------------------
    public class NVIDIAContactsWrapper{
        @AuraEnabled public string contentType {get;set;}
        @AuraEnabled public string subProgram {get;set;}
        
        @AuraEnabled public string Marketing_Manager_Name {get;set;}
        @AuraEnabled public string Marketing_Manager_Email {get;set;}
        @AuraEnabled public string Marketing_Manager_Contact_Number {get;set;}
        
        @AuraEnabled public string Sales_Manager_Name {get;set;}
        @AuraEnabled public string Sales_Manager_Email {get;set;}
        @AuraEnabled public string Sales_Manager_Contact_Number {get;set;}
        
        @AuraEnabled public string Support_Manager_Name {get;set;}
        @AuraEnabled public string Support_Manager_Email {get;set;}
        @AuraEnabled public string Support_Manager_Contact_Number {get;set;}

        @AuraEnabled public string SalesManager_Title1 {get;set;}
        @AuraEnabled public string MarketingManager_Title2 {get;set;}
        @AuraEnabled public string SupportManager_Title3 {get;set;}
  
    }   
    
    public class NVIDIAContactsProductWiseWrapper {
        @AuraEnabled public string productType {get;set;}
        @AuraEnabled public List<NVIDIAContactsWrapper> lstNVIDIAContactsWrapper {get;set;}
        public NVIDIAContactsProductWiseWrapper(String strProductType, List<NVIDIAContactsWrapper> lstNVIDIACntsWrapper) {
            lstNVIDIAContactsWrapper = lstNVIDIACntsWrapper;
            productType = strProductType;
        }
    }
    
    public class NVContactPriorityWrapper {
        
        public NV_Contacts__c objNVContact;
        public Decimal decPriority;
        
        public NVContactPriorityWrapper(Decimal priority, NV_Contacts__c objNVCon) {
            objNVContact = objNVCon;
            decPriority = priority;
        }
    }
}