force-app/main/default/objects/NV_Contacts__c/NV_Contacts__c.object-meta.xml
<CustomObject>
    <description>NPN : Contains NV Contacts shown to NPN Partner Users/Community users based on their Program/Competency/Region/Account</description>
    <label>NV Contact</label>
    <nameField>
        <label>NV Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NV Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NV_Contacts__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Competency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>NVEP</fullName>
            </value>
            <value>
                <fullName>Virtualization</fullName>
            </value>
            <value>
                <fullName>Consumer</fullName>
            </value>
            <value>
                <fullName>Embedded</fullName>
            </value>
            <value>
                <fullName>Compute DGX</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Compute</fullName>
            </value>
            <value>
                <fullName>Visualization</fullName>
            </value>
            <value>
                <fullName>Embedded Edge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_SalesManagerNameForDeactivatedUser.cls
@isTest(seeAllData=true)
private class Test_SalesManagerNameForDeactivatedUser {

    static testMethod void myUnitTest() {
      Profile p = [SELECT Id FROM Profile WHERE Name='Standard User']; 
      User u = new User(Alias = 'standt', Email='standarduser123@testorg.com', 
      EmailEncodingKey='UTF-8', LastName='Testing123', LanguageLocaleKey='en_US', 
      LocaleSidKey='en_US', ProfileId = p.Id,isActive=false, 
      TimeZoneSidKey='America/Los_Angeles', UserName='standarduser321@testorg.com');
      insert u;
      
      NV_Contacts__c  nvContact = new NV_Contacts__c();
      nvContact.Name = 'Test';
      nvContact.Product_Line__c = 'TESLA';
      nvContact.Sales_Manager_Email__c = u.email;
      insert nvContact;
        
    }
}