force-app/main/default/objects/Account/recordTypes/New_Customer_Account.recordType-meta.xml
<RecordType>
    <fullName>New_Customer_Account</fullName>
    <active>true</active>
    <label>New Customer Account</label>
</RecordType>

force-app/main/default/objects/Announcement__c/Announcement__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : Custom Object for NVIDIA to create Announcements.</description>
    <label>Announcement</label>
    <nameField>
        <label>Announcement Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerAnnouncement__c/CustomerAnnouncement__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : Junction Object to create Announcement records to Accounts based on Announcement creation criteria like Generic, Product and Entitlement</description>
    <label>Announcement</label>
    <nameField>
        <label>Announcement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerAnnouncement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Announcements</relationshipLabel>
    <relationshipName>Announcements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CustomerAnnouncement__c/fields/Announcement__c.field-meta.xml
<CustomField>
    <fullName>Announcement__c</fullName>
    <label>Announcement</label>
    <referenceTo>Announcement__c</referenceTo>
    <relationshipLabel>Announcements</relationshipLabel>
    <relationshipName>Announcements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <formula>TEXT( Service_Product__r.Family )</formula>
    <label>Product Family</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Cloud_Error_Log__c/Service_Cloud_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : Error Logs - Stores all integration errors</description>
    <label>Service Cloud Error Log</label>
    <nameField>
        <displayFormat>Err-{000}</displayFormat>
        <label>Service Cloud Error Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Cloud Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Cloud_Error_Log__c/fields/Functionality_Name__c.field-meta.xml
<CustomField>
    <fullName>Functionality_Name__c</fullName>
    <label>Functionality Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Batch_InsertAnncAccount.cls
/*
  * @Author: Moon (Perficient)
  * @Created Date: Jan 28, 2018
  * @Desc:  Purpose is to associate the announcements to the new customer accounts on the Customer Announcement junction object.
  *         Please find below the criteria for eligible account(s) to be processed 
  *         - Record type 'New Customer Account'
  *         - Must have entitlements belonging to product family DGX or Grid
  *         This batch job is invoked by the Announcement Trigger 
  *         Currently, the Announcement Trigger invokes this job for 'Generic' announcements only
*/
global class Batch_InsertAnncAccount implements Database.Batchable<sObject> {
    Set<Id> anncIdSet;
    string strAccessLevel;
    String query;
    
    global Batch_InsertAnncAccount(Set<Id> tmpAnncIdSet, string strAccessLevel) {
        anncIdSet = tmpAnncIdSet;
        if(strAccessLevel=='Generic') 
            query = 'SELECT Id FROM Account WHERE RecordType.DeveloperName = \'New_Customer_Account\' and Id IN (SELECT AccountId FROM Entitlement WHERE Product_Family__c != null AND (Product_Family__c like \'%DGX%\' OR Product_Family__c like \'%Grid%\'))';
        else if(strAccessLevel=='Product Specific')
            query = 'SELECT Id FROM Account WHERE RecordType.DeveloperName = \'New_Customer_Account\' and Id IN (SELECT AccountId FROM Entitlement WHERE Product_Family__c != null AND status = \'Active\')';           
    }
    
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List<sObject> scope) {
        List<CustomerAnnouncement__c> juncList = new List<CustomerAnnouncement__c>();
        List<Account> acctList = scope;
        for(Account acct : acctList){
            for(Id anncId : anncIdSet){
                CustomerAnnouncement__c junc = new CustomerAnnouncement__c();
                junc.Announcement__c = anncId;
                junc.Account__c = acct.Id;
                juncList.add(junc);
            }
        }
        Database.DMLOptions dml = new Database.DMLOptions();
        dml.allowFieldTruncation = true;
        try{
            insert juncList;
        }catch(Exception e){            
            Service_Cloud_Error_Log__c iError = new Service_Cloud_Error_Log__c(Functionality_Name__c = 'Customer Announcement Batch Insert', Error_Type__c = 'SALESFORCE BATCH', Error_Description__c = 'Soql query: ' + query + '\n Error: ' + e.getMessage());
            iError.setOptions(dml);
            insert iError;
        }
    }
    
    global void finish(Database.BatchableContext BC) {
        
    }
    
}