force-app/main/default/objects/Account/recordTypes/NPN_Account_Registry.recordType-meta.xml
<RecordType>
    <fullName>NPN_Account_Registry</fullName>
    <active>true</active>
    <label>NPN Account Registry</label>
</RecordType>

force-app/main/default/objects/Comments__c/Comments__c.object-meta.xml
<CustomObject>
    <description>CRM : Opportunity Comments made by internal team</description>
    <label>Comments</label>
    <nameField>
        <label>Comment Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner Contact</label>
</RecordType>

force-app/main/default/objects/NFR_Software_Licence__c/NFR_Software_Licence__c.object-meta.xml
<CustomObject>
    <description>NPN : NFR : Software Licence for maintaining DocuSign Ids</description>
    <label>NFR DocuSign Id</label>
    <nameField>
        <label>NFR DocuSign Id Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NFR DocuSign Ids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NFR_Software_Licence__c/fields/DocuSIgn_Template_ID__c.field-meta.xml
<CustomField>
    <fullName>DocuSIgn_Template_ID__c</fullName>
    <label>DocuSIgn Template ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_NFR_Software__c/NPN_NFR_Software__c.object-meta.xml
<CustomObject>
    <description>NPN: Created for SDS-891
Child object of the NFR SW License Request object. It stores the NFR Software License details. One NFR SW License Request can have multiple NFR SW Licenses</description>
    <label>NFR SW License</label>
    <nameField>
        <displayFormat>NFRS-{0000}</displayFormat>
        <label>NFR SW License</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NFR SW Licenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NPN_NFR_Software__c/fields/NPN_NFR_Software_Request__c.field-meta.xml
<CustomField>
    <fullName>NPN_NFR_Software_Request__c</fullName>
    <label>NPN NFR Software Request</label>
    <referenceTo>NPN_NFR_Software_Request__c</referenceTo>
    <relationshipName>NPN_NFR_Software</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NPN_NFR_Software__c/fields/Software__c.field-meta.xml
<CustomField>
    <fullName>Software__c</fullName>
    <label>Software</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_NFR_Software_Request__c/NPN_NFR_Software_Request__c.object-meta.xml
<CustomObject>
    <description>NPN: Created for SDS-891
Stores the NFR SW License Requests raised on the NPN portal by partners.</description>
    <label>NFR SW License Request</label>
    <nameField>
        <displayFormat>NSR-{00000}</displayFormat>
        <label>NFR SW License Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NFR SW License Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NPN_NFR_Software_Request__c/fields/Comments_From_PBM__c.field-meta.xml
<CustomField>
    <fullName>Comments_From_PBM__c</fullName>
    <label>Comments From PBM</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/NPN_NFR_Software_Request__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>NPN_Demo_Unit_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPN_NFR_Software_Request__c/fields/DocuSign_Enevelop_ID__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Enevelop_ID__c</fullName>
    <label>DocuSign Enevelop ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_NFR_Software_Request__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>NFR_Licenses_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPN_NFR_Software_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NPN_NFR_SendDocusignCtrl_Test.cls
@isTest(seeAllData=false)
private class NPN_NFR_SendDocusignCtrl_Test {

  static void makeData(){
    
    map<String, Id> mapProfNameId;
    Account partnerAcc;
    Contact partnerContact1;
    User partnerUser1;
    Id accRecTypeId;
    Id contactRecTypeId;
    String userName;

    accRecTypeId     = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('NPN_Account_Registry').getRecordTypeId();
    contactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Partner').getRecordTypeId();

    //get All Profiles (PROF_PP_VGX_GENERIC = NPN Partner Community(LOGIN), PROF_INT_PARTNER_ADMIN = Sales Profile - Partner Admin)
    list<string> lstProfNames = new list<string> {COMM_Constants.PROF_PP_VGX_GENERIC, COMM_Constants.PROF_INT_PARTNER_ADMIN };
    mapProfNameId = Test_COMM_Factory.getProfsByName(lstProfNames);

    //Create a NPN Account with Billing Country, Region
    partnerAcc = Test_COMM_Factory.createNPNAccountWithUSBillingAddressRegion('DRNPNAccountRegistry1', accRecTypeId);
    system.debug('***partnerAcc: ' + partnerAcc);


    //we can not set IsParnter or IsCustomerPortal at the time of insert, so needs to do this on update
    partnerAcc.IsPartner = true;
    update partnerAcc;

    //Create a Partner Contact
    partnerContact1 = Test_COMM_Factory.createContactWithMailingAddress('LDRJena11', 'FContact11', partnerAcc.Id, 'drcontactjena11@nv.com', contactRecTypeId, COMM_Constants.ADDRESS_STREET, COMM_Constants.ADDRESS_CITY, COMM_Constants.ADDRESS_STATE, COMM_Constants.ADDRESS_COUNTRY, COMM_Constants.ADDRESS_ZIP );

    //Create a Partner User with profile named 'NPN Partner Community(LOGIN)'
    User comUser = new User(
      LastName='one',
      Alias = 'tsale',
      Email = 'nvpartnerone@foo.com',
      Username = 'nvvippartnerone@foo.com.crqext',
      CommunityNickname = 'nvvippartnerone',
      ProfileId = mapProfNameId.get(COMM_Constants.PROF_PP_VGX_GENERIC),
      ContactId=partnerContact1.Id,
      TimeZoneSidKey = 'America/Los_Angeles',
      LocaleSidKey = 'en_US',
      EmailEncodingKey = 'UTF-8',
      LanguageLocaleKey = 'en_US'
      );
    insert comUser;

    NFR_Software_Licence__c sobj = new NFR_Software_Licence__c(
      Name = 'NFR_Order Agreement for EULA February 2019',         // DocuSign Template Name
      DocuSIgn_Template_ID__c = '41754ecb-47aa-42dc-9b1d-142925ef2278'         // DocuSIgn Template ID
      );
    insert sobj;

    NPN_NFR_Software_Request__c requestOne = new NPN_NFR_Software_Request__c();
    requestOne.Email__c =   comUser.Email;
    requestOne.Status__c =  'Approved';
    requestOne.Company_Name__c = partnerAcc.Id;
    requestOne.Requested_By__c = comUser.ContactId;
    requestOne.Comments_From_PBM__c = 'Test Comment';
    requestOne.DocuSign_Enevelop_ID__c = '1D40F498-557E-41D8-969F-F091A64F41BD';
    insert requestOne;

    NPN_NFR_Software__c swRequestOne = new NPN_NFR_Software__c();
    swRequestOne.Software__c = 'VDWS';
    swRequestOne.Quantity__c =  2;
    swRequestOne.Comments__c = 'test comment';
    swRequestOne.NPN_NFR_Software_Request__c = requestOne.id;
    insert swRequestOne;

    NPN_NFR_Software__c swRequestTwo = new NPN_NFR_Software__c();
    swRequestTwo.Software__c = 'VPC';
    swRequestTwo.Quantity__c =  5;
    swRequestTwo.Comments__c = 'test comment';
    swRequestTwo.NPN_NFR_Software_Request__c = requestOne.id;
    insert swRequestTwo;

    NPN_NFR_Software__c swRequestThree = new NPN_NFR_Software__c();
    swRequestThree.Software__c = 'VCS';
    swRequestThree.Quantity__c =  5;
    swRequestThree.Comments__c = 'test comment';
    swRequestThree.NPN_NFR_Software_Request__c = requestOne.id;
    insert swRequestThree;
  }

  @isTest static void docuSignTest1(){
      
    genericMock fakeResp = new genericMock(200,'Complete', '<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/><soapenv:Body><ns:SyncServiceResponse xmlns:ns="http://nvidiasapemsconnector.nvidiaaxis2service.nvidia.smps.gmlto.com"><ns:return xmlns:ax21="http://dto.nvidiaaxis2service.nvidia.smps.gmlto.com/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ax21:SyncResponse"><ax21:errorMessage></ax21:errorMessage><ax21:statusCode>success</ax21:statusCode><ax21:syncType>PartnerUser</ax21:syncType></ns:return></ns:SyncServiceResponse></soapenv:Body></soapenv:Envelope>',null);
    
    

    test.startTest();
    System.Test.setMock(HttpCalloutMock.class, fakeResp);
    
    makeData();
    
    NPN_NFR_Software_Request__c requestOne = [SELECT Id, Name FROM NPN_NFR_Software_Request__c LIMIT 1];
    
    PageReference pageRef = Page.NPN_NFR_SendDocusignPage;
    Test.setCurrentPageReference(pageRef);
    ApexPages.currentPage().getParameters().put('id',requestOne.Id);
    NPN_NFR_SendDocusignCtrl controllerExt = new NPN_NFR_SendDocusignCtrl( new ApexPages.StandardController(requestOne));
    //controllerExt.approveRequest();

    test.stopTest();

  }
}