force-app/main/default/objects/Account/recordTypes/NPN_Community_Account.recordType-meta.xml
<RecordType>
    <fullName>NPN_Community_Account</fullName>
    <active>true</active>
    <label>NPN Community Account</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Channel/Partners</fullName>
            </value>
            <value>
                <fullName>Chief Executive Officer (CEO)</fullName>
            </value>
            <value>
                <fullName>Chief Information Officer (CIO)</fullName>
            </value>
            <value>
                <fullName>Chief Technology Officer (CTO)</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Data Scientist</fullName>
            </value>
            <value>
                <fullName>Developer/Programmer</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Executive/Management</fullName>
            </value>
            <value>
                <fullName>Film/Video Editor</fullName>
            </value>
            <value>
                <fullName>Graphic Designer/Animator</fullName>
            </value>
            <value>
                <fullName>Industrial Designer/Product Designer</fullName>
            </value>
            <value>
                <fullName>IT Administrator/Systems Administrator</fullName>
            </value>
            <value>
                <fullName>IT Manager/Director of IT/VP of IT</fullName>
            </value>
            <value>
                <fullName>Marketing/Communications</fullName>
            </value>
            <value>
                <fullName>Marketing Manager</fullName>
            </value>
            <value>
                <fullName>Product Design/Engineering</fullName>
            </value>
            <value>
                <fullName>Product Management/Technical Marketing</fullName>
            </value>
            <value>
                <fullName>Professor/Department Advisor</fullName>
            </value>
            <value>
                <fullName>Purchasing Manager</fullName>
            </value>
            <value>
                <fullName>Renewal Contact</fullName>
            </value>
            <value>
                <fullName>Research Scientist</fullName>
            </value>
            <value>
                <fullName>Sales/Business Development</fullName>
            </value>
            <value>
                <fullName>Sales Engineer</fullName>
            </value>
            <value>
                <fullName>Sales Rep/Sales Manager</fullName>
            </value>
            <value>
                <fullName>Senior Vice President (SVP)</fullName>
            </value>
            <value>
                <fullName>Student/Post Grad</fullName>
            </value>
            <value>
                <fullName>Support/Services</fullName>
            </value>
            <value>
                <fullName>Vice President (VP)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner Contact</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Approved_Competencies__c.field-meta.xml
<CustomField>
    <fullName>Approved_Competencies__c</fullName>
    <label>Approved Competencies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Compute</fullName>
            </value>
            <value>
                <fullName>Virtualization</fullName>
            </value>
            <value>
                <fullName>Visualization</fullName>
            </value>
            <value>
                <fullName>Compute DGX</fullName>
            </value>
            <value>
                <fullName>Embedded Edge</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Approved_Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Approved_Program_Type__c</fullName>
    <label>Approved Program Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Solution Provider</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Solution Advisor</fullName>
            </value>
            <value>
                <fullName>Cloud Service Provider</fullName>
            </value>
            <value>
                <fullName>Service Delivery Partner</fullName>
            </value>
            <value>
                <fullName>Solutions Integration Partner</fullName>
            </value>
            <value>
                <fullName>Federal Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Global Systems Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Approved_SubProgram_Type__c.field-meta.xml
<CustomField>
    <fullName>Approved_SubProgram_Type__c</fullName>
    <label>Approved_SubProgram_Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EDU Services</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Support Services</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Data Center Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Channel/Partners</fullName>
            </value>
            <value>
                <fullName>Chief Executive Officer (CEO)</fullName>
            </value>
            <value>
                <fullName>Chief Information Officer (CIO)</fullName>
            </value>
            <value>
                <fullName>Chief Technology Officer (CTO)</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Data Scientist</fullName>
                <label>Data scientist</label>
            </value>
            <value>
                <fullName>Developer/Programmer</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Executive/Management</fullName>
            </value>
            <value>
                <fullName>Film/Video Editor</fullName>
            </value>
            <value>
                <fullName>Graphic Designer/Animator</fullName>
            </value>
            <value>
                <fullName>Industrial Designer/Product Designer</fullName>
            </value>
            <value>
                <fullName>IT Administrator/Systems Administrator</fullName>
            </value>
            <value>
                <fullName>IT Manager/Director of IT/VP of IT</fullName>
            </value>
            <value>
                <fullName>Marketing/Communications</fullName>
            </value>
            <value>
                <fullName>Marketing Manager</fullName>
            </value>
            <value>
                <fullName>Product Design/Engineering</fullName>
            </value>
            <value>
                <fullName>Product Management/Technical Marketing</fullName>
            </value>
            <value>
                <fullName>Professor/Department Advisor</fullName>
            </value>
            <value>
                <fullName>Purchasing Manager</fullName>
            </value>
            <value>
                <fullName>Research Scientist</fullName>
            </value>
            <value>
                <fullName>Sales/Business Development</fullName>
            </value>
            <value>
                <fullName>Sales Engineer</fullName>
            </value>
            <value>
                <fullName>Sales Rep/Sales Manager</fullName>
            </value>
            <value>
                <fullName>Senior Vice President (SVP)</fullName>
            </value>
            <value>
                <fullName>Student/Post Grad</fullName>
            </value>
            <value>
                <fullName>Support/Services</fullName>
            </value>
            <value>
                <fullName>Vice President (VP)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Program_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Level__c</fullName>
    <label>Approved Program Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NPN_Key_Contact__c/NPN_Key_Contact__c.object-meta.xml
<CustomObject>
    <description>NPN : DocuSign : Automated onboarding - Key Contacts form</description>
    <label>NPN Key Contact</label>
    <nameField>
        <label>NPN Key Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPN Key Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NPN_Key_Contact__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>NPN Key Contacts</relationshipLabel>
    <relationshipName>NPN_Key_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPN_Key_Contact__c/fields/Sales_Training__c.field-meta.xml
<CustomField>
    <fullName>Sales_Training__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sales Training</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NPN_Key_Contact__c/fields/Technical_Training__c.field-meta.xml
<CustomField>
    <fullName>Technical_Training__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Technical Training</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/NV_Test_DocuSignLeadHelper.cls
@isTest
private class NV_Test_DocuSignLeadHelper {
    
    static Id leadId;
    static void createData() {
        
        NV_NPN_TestDataFactory.setupCustomSettings();
        RecordType leadRec = [select id from RecordType where sobjectType='Lead' and developerName='NPN_Web_Onboard_Form'];
        
        Lead objLead = new Lead();
        
        objLead.Approved_Competencies__c = 'Accelerated Computing; GPU Virtualization';
        objLead.Approved_Program_Type__c = 'Service Delivery Partner';
        objLead.Approved_SubProgram_Type__c= 'EDU Services';
        objLead.Program_Level__c = 'Elite';
        objLead.lastname = 'Varun Test';
        objLead.email = 'varun1234@test.com';
        objLead.Company = 'NVD';
        objLead.Country = 'India';
        objLead.recordTypeId = leadRec.id;
        insert objLead;
        leadId = objLead.id;
        Attachment att = new Attachment(parentId = objLead.id, name='test Att', body = Blob.valueOf('Str'));
        insert att;
        NPN_Key_Contact__c objNPN = new NPN_Key_Contact__c(lead__c = objLead.id, email__c = 'varun232@test.com', Job_Role__c = 'POS', sales_training__c = true, technical_Training__c = true);
        insert objNPN;
        
    }
    
    static void createData1() {
        
        NV_NPN_TestDataFactory.setupCustomSettings();
        RecordType leadRec = [select id from RecordType where sobjectType='Lead' and developerName='NPN_Web_Onboard_Form'];
        RecordType AccRec = [select id from RecordType where sobjectType='Account' and developerName='NPN_Community_Account'];
        RecordType ConRec = [select id from RecordType where sobjectType='Contact' and developerName='Partner'];
        Lead objLead = new Lead();
        Account ObjAcc = new Account();
        Contact ObjCon = new Contact();
        ObjAcc.Name = 'NVD';
        ObjCon.lastname = 'Varun Test';
        ObjCon.email='varun@test.com';
        objLead.Approved_Competencies__c = 'Accelerated Computing; GPU Virtualization';
        objLead.Approved_Program_Type__c = 'Solution Provider (VAR)';
        objLead.Program_Level__c = 'Elite';
        objLead.lastname = 'Varun Test';
        objLead.email = 'varun@test.com';
        objLead.Company = 'NVD';
        objLead.Country = 'India';
        objLead.recordTypeId = leadRec.id;
        objAcc.recordTypeId = AccRec.id;
        objCon.recordTypeId = ConRec.id;
        insert objLead;
        insert ObjAcc;
        leadId = objLead.id;
        ObjCon.Accountid=ObjAcc.id;
        Attachment att = new Attachment(parentId = objLead.id, name='test Att', body = Blob.valueOf('Str'));
        insert att;
        NPN_Key_Contact__c objNPN = new NPN_Key_Contact__c(lead__c = objLead.id, email__c = 'varun@test.com', Job_Role__c = 'POS', sales_training__c = true, technical_Training__c = true);
        NPN_Key_Contact__c objNPN1 = new NPN_Key_Contact__c(lead__c = objLead.id, email__c = 'varun@test.com', Job_Role__c = 'POS', sales_training__c = true, technical_Training__c = true);
        insert objNPN;
        insert objNPN1;
        
        insert ObjCon;
    }
    
    static testmethod void convertLeadTest() {
        genericMock fakeResp = new genericMock(200,'Complete', '<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/><soapenv:Body><ns:SyncServiceResponse xmlns:ns="http://nvidiasapemsconnector.nvidiaaxis2service.nvidia.smps.gmlto.com"><ns:return xmlns:ax21="http://dto.nvidiaaxis2service.nvidia.smps.gmlto.com/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ax21:SyncResponse"><ax21:errorMessage></ax21:errorMessage><ax21:statusCode>success</ax21:statusCode><ax21:syncType>PartnerUser</ax21:syncType></ns:return></ns:SyncServiceResponse></soapenv:Body></soapenv:Envelope>',null);
        Test.startTest();
            System.Test.setMock(HttpCalloutMock.class, fakeResp);
            createData();
            dsfs__DocuSign_Status__c objDCS = new dsfs__DocuSign_Status__c(dsfs__Lead__c = leadId, dsfs__Envelope_Status__c = 'Sent');
            insert objDCS;
            objDCS.dsfs__Envelope_Status__c = 'Completed';
            update objDCS; 
        Test.stopTest();
    }
    
    static testmethod void convertLeadTest1() {
        genericMock fakeResp = new genericMock(200,'Complete', '<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/><soapenv:Body><ns:SyncServiceResponse xmlns:ns="http://nvidiasapemsconnector.nvidiaaxis2service.nvidia.smps.gmlto.com"><ns:return xmlns:ax21="http://dto.nvidiaaxis2service.nvidia.smps.gmlto.com/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ax21:SyncResponse"><ax21:errorMessage></ax21:errorMessage><ax21:statusCode>success</ax21:statusCode><ax21:syncType>PartnerUser</ax21:syncType></ns:return></ns:SyncServiceResponse></soapenv:Body></soapenv:Envelope>',null);
        Test.startTest();
            System.Test.setMock(HttpCalloutMock.class, fakeResp);
            createData1();
            dsfs__DocuSign_Status__c objDCS = new dsfs__DocuSign_Status__c(dsfs__Lead__c = leadId, dsfs__Envelope_Status__c = 'Sent');
            insert objDCS;
            objDCS.dsfs__Envelope_Status__c = 'Completed';
            update objDCS; 
        Test.stopTest();
    }
    
}