force-app/main/default/objects/Account/recordTypes/PartnerAccount.recordType-meta.xml
<RecordType>
    <fullName>PartnerAccount</fullName>
    <active>true</active>
    <label>Partner Account</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/DR_Partner_Sales_Rep_Company__c.field-meta.xml
<CustomField>
    <fullName>DR_Partner_Sales_Rep_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DR2 : Deal Registration - copies value from lead convert</description>
    <label>Partner Sales Rep Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Partner Sales Rep Company)</relationshipLabel>
    <relationshipName>OpportunitiesDRPSRC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DR_SalesOps_Approver__c.field-meta.xml
<CustomField>
    <fullName>DR_SalesOps_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SalesOps Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LastModifiedDate_by_Partner__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedDate_by_Partner__c</fullName>
    <description>This field is being used by the Tegra Embedded Partner Opportunity.</description>
    <label>LastModifiedDate by Partner</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Detail_Link_for_Partner_User__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Detail_Link_for_Partner_User__c</fullName>
    <description>This field will have the Opportunity Detail Link for the Partner Users. This field is being used in the Email Templates for the &apos;Tegra Embedded Partner Opportunity&apos; Expirations project.</description>
    <label>Opportunity Detail Link for Partner User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Expired__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field acts as a flag to identify inactive Tegra Embedded Partner Opportunities by checking the Opportunities Owner has not updated in 60 days. If so, then re-assign ownership to the NVIDIA Account Manager (PBM).</description>
    <label>Opportunity Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <inlineHelpText>Auto-Populated Field.  No need to update.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>NALA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tegra_Embd_Regstr_Expiration_by_Partners__c/Tegra_Embd_Regstr_Expiration_by_Partners__c.object-meta.xml
<CustomObject>
    <description>This will have the list of all Partner Accounts those qualify for either of the criteria below, 
1) Partner Accounts which have to be exempted from the Registration expiration process 
2) Partner Accounts that will have their own threshold limit for expiration.</description>
    <label>Tegra Embd Regstr Expiration by Partners</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tegra Embd Regstr Expiration by Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tegra_Embd_Regstr_Expiration_by_Partners__c/fields/Default_Threshold_Limit_for_Partner__c.field-meta.xml
<CustomField>
    <fullName>Default_Threshold_Limit_for_Partner__c</fullName>
    <description>This field decides the maximum time the Opportunity should not be expired by its Partner (Account)</description>
    <label>Default Threshold Limit for Partner</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tegra_Embd_Regstr_Expiration_by_Partners__c/fields/Expire_Registration__c.field-meta.xml
<CustomField>
    <fullName>Expire_Registration__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field let the Opportunity Expired if it is child of this Partner (Account)</description>
    <label>Expire Registration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tegra_Embd_Regstr_Expiration_by_Partners__c/fields/Partner_Sales_Rep_Company__c.field-meta.xml
<CustomField>
    <fullName>Partner_Sales_Rep_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field contains the Partner Account of the Tegra Embedded Partner Opportunity being expired. This field represents the &apos;DR_Partner_Sales_Rep_Company__c&apos; field on the Opportunity.</description>
    <label>Partner Sales Rep Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>NPN_Account_Registry</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tegra Embd Regstr Expiration by Partners</relationshipLabel>
    <relationshipName>Tegra_Embd_Regstr_Expiration_by_Partners</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/Tegra_Embedded_Registration_Expirations__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This will have the Threshold limit in days for the Registration Expiration and the Threshold limit in days for the Email Notification Reminders for the first, second and third.</description>
    <label>Tegra Embedded Registration Expirations</label>
</CustomObject>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/fields/Default_Cc_Email_Ids__c.field-meta.xml
<CustomField>
    <fullName>Default_Cc_Email_Ids__c</fullName>
    <description>This Email Id&apos;s in this field will be added in the CC for the all the Email Notificaitons (1st, 2nd and 3rd)</description>
    <label>Default Cc Email Ids</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/fields/Default_Oppty_Owner_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Default_Oppty_Owner_Email_Id__c</fullName>
    <description>This field will have the Email address of the User who will be the Default replaced owner in case of any inActive PBM.</description>
    <label>Default Oppty Owner Email Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/fields/Default_Threshold_for_all_Partners__c.field-meta.xml
<CustomField>
    <fullName>Default_Threshold_for_all_Partners__c</fullName>
    <label>Default Threshold for all Partners</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/fields/First_Reminder__c.field-meta.xml
<CustomField>
    <fullName>First_Reminder__c</fullName>
    <label>First Reminder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/fields/Opportunity_Detail_Link_for_Partner_User__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Detail_Link_for_Partner_User__c</fullName>
    <description>This field will have the URL of Opportunity Detail Link for the Partner Users. This field is being used in the Email Templates for the &apos;Tegra Embedded Partner Opportunity&apos; Expirations project.</description>
    <label>Opportunity Detail Link for Partner User</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/fields/Opportunity_Stages_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stages_to_Exclude__c</fullName>
    <description>This field will have the StageNames of the Opportunities those should be excluded from Expiration process.</description>
    <label>Opportunity Stages to Exclude</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/fields/OWD_Sender_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>OWD_Sender_Email_Address__c</fullName>
    <description>This field have the OWD Email Address, which will be used as a Sender</description>
    <label>OWD - Sender Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/fields/Second_Reminder__c.field-meta.xml
<CustomField>
    <fullName>Second_Reminder__c</fullName>
    <label>Second Reminder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/fields/Third_Reminder__c.field-meta.xml
<CustomField>
    <fullName>Third_Reminder__c</fullName>
    <label>Third Reminder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Used in Enterprise KPIs and Other dashboards</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>NALA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TegraEmbdRegstrExpry_tgr_cls_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Author: Manideep
 * Created Date: 02/14/2020
 * JIRA # SDS-1493
 * Description: This Test Class contains unit tests for code coverage of classes adn triggers below
                - TegraEmbdRegstrExpry_tgr.trg
                - TegraEmbdRegstrExpry_tgr_cls.cls
 */
@isTest
private class TegraEmbdRegstrExpry_tgr_cls_Test {

  static testMethod void testInsertandinActivateTegraEmbdRegstrForPartner() {
   
    //Create Partner Users
    Id Pid = [Select Id from Profile where Name = 'Sales Profile - Tegra Embedded'].Id;
    Id RoleId = [Select Id From UserRole where Name = 'Sales Europe Manager - Tegra Auto/Emb'].Id;
        
    List<User> Users = new List<User>();
    User u;
  
    u = new User(FirstName = 'test', LastName = 'user 1', email = 'tusr1@example.com', Username = 'tusr1@example.com', Alias='bd', TimeZoneSidKey = 'America/Los_Angeles',
                 EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = Pid, UserRoleId = RoleId);  
    Users.add(u); 
    u = new User(FirstName = 'test', LastName = 'default Owner', email = 'testdefaultowner@nvidia.com', Username = 'testdefaultowner@nvidia.com', Alias='bd', TimeZoneSidKey = 'America/Los_Angeles',
                 EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = Pid, UserRoleId = RoleId);  
    Users.add(u);
            
    User usr = [Select Id from User where Id = :UserInfo.getUserId()];
    system.runAs(usr) {
     insert Users;
    }       
    
    List<User> UserList = [Select Id, Name from User where CreatedDate = Today AND ProfileId = :Pid AND UserRoleId = :RoleId ORDER BY email ASC];
    
    // Create Custom Setting to define various reminder timelines, Default Owner, Send email as, cc users in Notifications etc.,
    list<Tegra_Embedded_Registration_Expirations__c> tegEmbRegExpList = new list<Tegra_Embedded_Registration_Expirations__c>(); 
    Tegra_Embedded_Registration_Expirations__c terExp = new Tegra_Embedded_Registration_Expirations__c(Default_Threshold_for_all_Partners__c = 60, First_Reminder__c = 14, Second_Reminder__c = 5, Third_Reminder__c = 0, 
                                                                                                       Default_Oppty_Owner_Email_Id__c = 'testdefaultowner@nvidia.com',
                                                                                                       Default_Cc_Email_Ids__c = 'testdefaultowner@nvidia.com', OWD_Sender_Email_Address__c = 'no_reply@nvidia.com', 
                                                                                                       Opportunity_Detail_Link_for_Partner_User__c = 'https://stid.nvidia.com/sfdcContent/index.html?retURL=/',                                        
                                                                                                       Opportunity_Stages_to_Exclude__c = 'Closed Won;Closed Lost;Closed - Program Canceled;');                                                                                                                                                                                                                                                                
    tegEmbRegExpList.add(terExp);
    insert tegEmbRegExpList; // Create Custom Setting values 
                                                                                                         
    list<Opportunity> tEmdOpplst = new list<Opportunity>();  // list for Opportunities
            
    // Fetch the Opportunity Record Type 'Tegra Embedded Partner Opportunity' by Name 
    map<string, Id> map_tEmbd_Opportunity_RT = COMM_Utility.getRTsByName(COMM_Constants.SOBJECT_OPPORTUNITY, COMM_Constants.OPPTY_RT_TEGRA_EMBEDDED_PARTNER_OPPTY);
       
    // Create Partner Account, Contact and User
    map<String, Id> mapPP_PartnerProgramAccount_RT = COMM_Utility.getRTsByName(COMM_Constants.SOBJECT_ACCOUNT, COMM_Constants.ACCOUNT_RT_NV_PPA);
    map<String, Id> mapPP_PartnerContact_RT = COMM_Utility.getRTsByName(COMM_Constants.SOBJECT_CONTACT, COMM_Constants.CONTACT_RT_PARTNER_CONTACT);
    map<string, Id> mapPP_TPP_Generic_Prof = COMM_Utility.getProfsByName(COMM_Constants.PROF_PP_TPP_GENERIC); 
        
    // Create Partner Account (string Name, string RecordTypeId, Boolean isPartner, Boolean isCustomerPortal)
    Account partnerAccount = Test_COMM_Factory.createAccount('TegraEmb_Regstr_Expirations_trg_Test_Acc_1', mapPP_PartnerProgramAccount_RT.get(COMM_Constants.ACCOUNT_RT_NV_PPA), true, false);    
    
    //Create a Partner Contact     
    Contact partnerContact = Test_COMM_Factory.createContact('TegraEmb_Regstr_Expirations_trg_Test_PC_1', 'TestPC1@nv.com', partnerAccount.Id, mapPP_PartnerContact_RT.get(COMM_Constants.CONTACT_RT_PARTNER_CONTACT), COMM_Constants.CON_PPG_COMMUNITY);
      
    //Create a Partner User     
    User partnerUser = Test_COMM_Factory.createUserWithEmail(partnerContact.Id, partnerContact.email, mapPP_TPP_Generic_Prof.get(COMM_Constants.PROF_PP_TPP_GENERIC));
    list<user> lstPU = [Select email, IsPortalEnabled, UserType From User Where id =:partnerUser.Id AND IsPortalEnabled = TRUE]; 
            
    // Create records for the Custom object 'Tegra Embedded Regstr Expiration by Partner'
    list<Tegra_Embd_Regstr_Expiration_by_Partners__c> tembRegExpbyPartnerList = new list<Tegra_Embd_Regstr_Expiration_by_Partners__c>();
    
    Account pAct = [Select Id, Name, RecordTypeId, RecordType.Name, BillingStreet, BillingCity, BillingState, BillingCountry, BillingPostalCode from Account where Id =:partnerAccount.Id];
    pAct.BillingStreet = '1234 Test Street';
    pAct.BillingCity = 'Santa Clara';
    pAct.BillingState = 'California';
    pAct.BillingCountry = 'United States';
    pAct.BillingPostalCode = '12345';
    update pAct;
       
    // Create Tegra Embedded Registration Expiration by Partner
    Tegra_Embd_Regstr_Expiration_by_Partners__c tep = new Tegra_Embd_Regstr_Expiration_by_Partners__c();
    tep.Partner_Sales_Rep_Company__c = pAct.Id;
    tep.Default_Threshold_Limit_for_Partner__c = 60;
    tep.Expire_Registration__c = True;
    insert tep;  // Create records in Custom Object
    
    // login as Partner User and Create the Opportunity    
    system.runAs(partnerUser) {   
      // Create a single Opportunity
      Opportunity opp = new Opportunity();
      opp.Name = 'trg_Context_Test_Tegra_Embd_Opp_1';
      opp.AccountId = partnerAccount.Id;
      opp.StageName = 'Prospect';
      opp.RecordTypeId = map_tEmbd_Opportunity_RT.get(COMM_Constants.OPPTY_RT_TEGRA_EMBEDDED_PARTNER_OPPTY);
      opp.DR_Partner_Sales_Rep_Company__c = partnerAccount.Id;
      opp.DR_SalesOps_Approver__c = partnerUser.Id; 
      opp.LastModifiedDate_by_Partner__c = (Date.Today() - 46);
      opp.CloseDate = system.today() + 10;
      opp.Region__c = 'EMEA';
      insert opp;
    }
       
    list<Opportunity> oppLst = [SELECT Id, Name, OwnerId, StageName, LastModifiedDate_by_Partner__c, Opportunity_Expired__c  
                                FROM Opportunity 
                                WHERE Name = 'trg_Context_Test_Tegra_Embd_Opp_1'];
                                   
    // Validate the Before Insert logic in 'tegraEmbdPartnerOpptyRegExpInsert()' of the 'Opportuntiy_tgr_cls' class.
    system.assertEquals(oppLst[0].LastModifiedDate_by_Partner__c, Date.Today()); 
      
    Test.StartTest();
       
     // Populate the 'LastModifiedDate_by_Partner__c' field as System User
     for(Opportunity tegOpp: oppLst) {
         tegOpp.LastModifiedDate_by_Partner__c = (system.today() - 46);
     }
     update oppLst; 
       
     list<Opportunity> oppLst2 = [SELECT Id, LastModifiedDate_by_Partner__c, Opportunity_Expired__c 
                                  FROM Opportunity 
                                  WHERE Name = 'trg_Context_Test_Tegra_Embd_Opp_1'];
       
     // Validate the Before 'Update' logic in 'tegraEmbdPartnerOpptyRegExpUpdate()' of the 'Opportuntiy_tgr_cls' class.
     system.assertEquals(oppLst2[0].LastModifiedDate_by_Partner__c, (Date.Today() - 46)); 
     system.assertEquals(oppLst2[0].Opportunity_Expired__c, false); 
    
     // Update the Expire_Registration__c for the 'Tegra Embedded Registration Expiration by Partner' to false
     list<Tegra_Embd_Regstr_Expiration_by_Partners__c> tepList = [SELECT Id, Partner_Sales_Rep_Company__c, Default_Threshold_Limit_for_Partner__c, Expire_Registration__c
                                                                  FROM Tegra_Embd_Regstr_Expiration_by_Partners__c
                                                                  WHERE Partner_Sales_Rep_Company__c =:pAct.Id];
     tepList[0].Expire_Registration__c = false;
     update tepList;  // update records in Custom Object 
             
  }
  
  static testMethod void testInsertandDeleteTegraEmbdRegstrForPartner() {
   
    //Create Partner Users
    Id Pid = [Select Id from Profile where Name = 'Sales Profile - Tegra Embedded'].Id;
    Id RoleId = [Select Id From UserRole where Name = 'Sales Europe Manager - Tegra Auto/Emb'].Id;
        
    List<User> Users = new List<User>();
    User u;
  
    u = new User(FirstName = 'test', LastName = 'user 1', email = 'tusr1@example.com', Username = 'tusr1@example.com', Alias='bd', TimeZoneSidKey = 'America/Los_Angeles',
                 EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = Pid, UserRoleId = RoleId);  
    Users.add(u); 
    u = new User(FirstName = 'test', LastName = 'default Owner', email = 'testdefaultowner@nvidia.com', Username = 'testdefaultowner@nvidia.com', Alias='bd', TimeZoneSidKey = 'America/Los_Angeles',
                 EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = Pid, UserRoleId = RoleId);  
    Users.add(u);
            
    User usr = [Select Id from User where Id = :UserInfo.getUserId()];
    system.runAs(usr) {
     insert Users;
    }       
    
    List<User> UserList = [Select Id, Name from User where CreatedDate = Today AND ProfileId = :Pid AND UserRoleId = :RoleId ORDER BY email ASC];
    
    // Create Custom Setting to define various reminder timelines, Default Owner, Send email as, cc users in Notifications etc.,
    list<Tegra_Embedded_Registration_Expirations__c> tegEmbRegExpList = new list<Tegra_Embedded_Registration_Expirations__c>(); 
    Tegra_Embedded_Registration_Expirations__c terExp = new Tegra_Embedded_Registration_Expirations__c(Default_Threshold_for_all_Partners__c = 60, First_Reminder__c = 14, Second_Reminder__c = 5, Third_Reminder__c = 0, 
                                                                                                       Default_Oppty_Owner_Email_Id__c = 'testdefaultowner@nvidia.com',
                                                                                                       Default_Cc_Email_Ids__c = 'testdefaultowner@nvidia.com', OWD_Sender_Email_Address__c = 'no_reply@nvidia.com', 
                                                                                                       Opportunity_Detail_Link_for_Partner_User__c = 'https://stid.nvidia.com/sfdcContent/index.html?retURL=/',
                                                                                                       Opportunity_Stages_to_Exclude__c = 'Closed Won;Closed Lost;Closed - Program Canceled;');                                                                                                                                                                                                                                                                
    tegEmbRegExpList.add(terExp);
    insert tegEmbRegExpList; // Create Custom Setting values 
                                                                                                         
    list<Opportunity> tEmdOpplst = new list<Opportunity>();  // list for Opportunities
            
    // Fetch the Opportunity Record Type 'Tegra Embedded Partner Opportunity' by Name 
    map<string, Id> map_tEmbd_Opportunity_RT = COMM_Utility.getRTsByName(COMM_Constants.SOBJECT_OPPORTUNITY, COMM_Constants.OPPTY_RT_TEGRA_EMBEDDED_PARTNER_OPPTY);
       
    // Create Partner Account, Contact and User
    map<String, Id> mapPP_PartnerProgramAccount_RT = COMM_Utility.getRTsByName(COMM_Constants.SOBJECT_ACCOUNT, COMM_Constants.ACCOUNT_RT_NV_PPA);
    map<String, Id> mapPP_PartnerContact_RT = COMM_Utility.getRTsByName(COMM_Constants.SOBJECT_CONTACT, COMM_Constants.CONTACT_RT_PARTNER_CONTACT);
    map<string, Id> mapPP_TPP_Generic_Prof = COMM_Utility.getProfsByName(COMM_Constants.PROF_PP_TPP_GENERIC); 
        
    // Create Partner Account (string Name, string RecordTypeId, Boolean isPartner, Boolean isCustomerPortal)
    Account partnerAccount = Test_COMM_Factory.createAccount('TegraEmb_Regstr_Expirations_trg_Test_Acc_1', mapPP_PartnerProgramAccount_RT.get(COMM_Constants.ACCOUNT_RT_NV_PPA), true, false);    
    
    //Create a Partner Contact     
    Contact partnerContact = Test_COMM_Factory.createContact('TegraEmb_Regstr_Expirations_trg_Test_PC_1', 'TestPC1@nv.com', partnerAccount.Id, mapPP_PartnerContact_RT.get(COMM_Constants.CONTACT_RT_PARTNER_CONTACT), COMM_Constants.CON_PPG_COMMUNITY);
      
    //Create a Partner User     
    User partnerUser = Test_COMM_Factory.createUserWithEmail(partnerContact.Id, partnerContact.email, mapPP_TPP_Generic_Prof.get(COMM_Constants.PROF_PP_TPP_GENERIC));
    list<user> lstPU = [Select email, IsPortalEnabled, UserType From User Where id =:partnerUser.Id AND IsPortalEnabled = TRUE]; 
            
    // Create records for the Custom object 'Tegra Embedded Regstr Expiration by Partner'
    list<Tegra_Embd_Regstr_Expiration_by_Partners__c> tembRegExpbyPartnerList = new list<Tegra_Embd_Regstr_Expiration_by_Partners__c>();
    
    Account pAct = [Select Id, Name, RecordTypeId, RecordType.Name, BillingStreet, BillingCity, BillingState, BillingCountry, BillingPostalCode from Account where Id =:partnerAccount.Id];
    pAct.BillingStreet = '1234 Test Street';
    pAct.BillingCity = 'Santa Clara';
    pAct.BillingState = 'California';
    pAct.BillingCountry = 'United States';
    pAct.BillingPostalCode = '12345';
    update pAct;
       
    // Create Tegra Embedded Registration Expiration by Partner
    Tegra_Embd_Regstr_Expiration_by_Partners__c tep = new Tegra_Embd_Regstr_Expiration_by_Partners__c();
    tep.Partner_Sales_Rep_Company__c = pAct.Id;
    tep.Default_Threshold_Limit_for_Partner__c = 60;
    tep.Expire_Registration__c = True;
    insert tep;  // Create records in Custom Object
    
    // login as Partner User and Create the Opportunity    
    system.runAs(partnerUser) {   
      // Create a single Opportunity
      Opportunity opp = new Opportunity();
      opp.Name = 'trg_Context_Test_Tegra_Embd_Opp_1';
      opp.AccountId = partnerAccount.Id;
      opp.StageName = 'Prospect';
      opp.RecordTypeId = map_tEmbd_Opportunity_RT.get(COMM_Constants.OPPTY_RT_TEGRA_EMBEDDED_PARTNER_OPPTY);
      opp.DR_Partner_Sales_Rep_Company__c = partnerAccount.Id;
      opp.DR_SalesOps_Approver__c = partnerUser.Id; 
      opp.LastModifiedDate_by_Partner__c = (Date.Today() - 46);
      opp.CloseDate = system.today() + 10;
      opp.Region__c = 'EMEA';
      insert opp;
    }
       
    list<Opportunity> oppLst = [SELECT Id, Name, OwnerId, StageName, LastModifiedDate_by_Partner__c, Opportunity_Expired__c  
                                FROM Opportunity 
                                WHERE Name = 'trg_Context_Test_Tegra_Embd_Opp_1'];
    system.assertEquals(oppLst[0].LastModifiedDate_by_Partner__c, Date.Today()); 
      
    Test.StartTest();
       
     // Populate the 'LastModifiedDate_by_Partner__c' field as System User
     for(Opportunity tegOpp: oppLst) {
         tegOpp.LastModifiedDate_by_Partner__c = (system.today() - 46);
     }
     update oppLst; 
       
     list<Opportunity> oppLst2 = [SELECT Id, LastModifiedDate_by_Partner__c, Opportunity_Expired__c 
                                  FROM Opportunity 
                                  WHERE Name = 'trg_Context_Test_Tegra_Embd_Opp_1'];
     system.assertEquals(oppLst2[0].LastModifiedDate_by_Partner__c, (Date.Today() - 46)); 
     system.assertEquals(oppLst2[0].Opportunity_Expired__c, false); 
    
     // Update the Expire_Registration__c for the 'Tegra Embedded Registration Expiration by Partner' to false
     list<Tegra_Embd_Regstr_Expiration_by_Partners__c> tepList = [SELECT Id, Partner_Sales_Rep_Company__c, Default_Threshold_Limit_for_Partner__c, Expire_Registration__c
                                                                  FROM Tegra_Embd_Regstr_Expiration_by_Partners__c
                                                                  WHERE Partner_Sales_Rep_Company__c =:pAct.Id];
     delete tepList;  // Delete records in Custom Object 
    
  }
  
}