force-app/main/default/objects/Account/recordTypes/PartnerAccount.recordType-meta.xml
<RecordType>
    <fullName>PartnerAccount</fullName>
    <active>true</active>
    <label>Partner Account</label>
</RecordType>

force-app/main/default/objects/ChannelAdmin_Approval_Routing__c/ChannelAdmin_Approval_Routing__c.object-meta.xml
<CustomObject>
    <description>Country based Routing Rules for Jetson Deal Registration (SDS-2474)</description>
    <label>ChannelAdmin Approval Routing</label>
    <nameField>
        <label>Country Code</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChannelAdmin Approval Routings</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/ChannelAdmin_Approval_Routing__c/fields/Jetson_Approver__c.field-meta.xml
<CustomField>
    <fullName>Jetson_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Jetson Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>ChannelAdmin_Approval_Routings</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/DR_Partner_Sales_Rep_Company__c.field-meta.xml
<CustomField>
    <fullName>DR_Partner_Sales_Rep_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DR2 : Deal Registration - copies value from lead convert</description>
    <label>Partner Sales Rep Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Partner Sales Rep Company)</relationshipLabel>
    <relationshipName>OpportunitiesDRPSRC</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DR_SalesOps_Approver__c.field-meta.xml
<CustomField>
    <fullName>DR_SalesOps_Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SalesOps Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/LastModifiedDate_by_Partner__c.field-meta.xml
<CustomField>
    <fullName>LastModifiedDate_by_Partner__c</fullName>
    <description>This field is being used by the Tegra Embedded Partner Opportunity.</description>
    <label>LastModifiedDate by Partner</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Detail_Link_for_Partner_User__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Detail_Link_for_Partner_User__c</fullName>
    <description>This field will have the Opportunity Detail Link for the Partner Users. This field is being used in the Email Templates for the &apos;Tegra Embedded Partner Opportunity&apos; Expirations project.</description>
    <label>Opportunity Detail Link for Partner User</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Expired__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Expired__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field acts as a flag to identify inactive Tegra Embedded Partner Opportunities by checking the Opportunities Owner has not updated in 60 days. If so, then re-assign ownership to the NVIDIA Account Manager (PBM).</description>
    <label>Opportunity Expired</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <inlineHelpText>Auto-Populated Field.  No need to update.</inlineHelpText>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>NALA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Tegra_Embd_Regstr_Expiration_by_Partners__c/Tegra_Embd_Regstr_Expiration_by_Partners__c.object-meta.xml
<CustomObject>
    <description>This will have the list of all Partner Accounts those qualify for either of the criteria below, 
1) Partner Accounts which have to be exempted from the Registration expiration process 
2) Partner Accounts that will have their own threshold limit for expiration.</description>
    <label>Tegra Embd Regstr Expiration by Partners</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tegra Embd Regstr Expiration by Partners</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tegra_Embd_Regstr_Expiration_by_Partners__c/fields/Default_Threshold_Limit_for_Partner__c.field-meta.xml
<CustomField>
    <fullName>Default_Threshold_Limit_for_Partner__c</fullName>
    <description>This field decides the maximum time the Opportunity should not be expired by its Partner (Account)</description>
    <label>Default Threshold Limit for Partner</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tegra_Embd_Regstr_Expiration_by_Partners__c/fields/Expire_Registration__c.field-meta.xml
<CustomField>
    <fullName>Expire_Registration__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This field let the Opportunity Expired if it is child of this Partner (Account)</description>
    <label>Expire Registration</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tegra_Embd_Regstr_Expiration_by_Partners__c/fields/Partner_Sales_Rep_Company__c.field-meta.xml
<CustomField>
    <fullName>Partner_Sales_Rep_Company__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>This field contains the Partner Account of the Tegra Embedded Partner Opportunity being expired. This field represents the &apos;DR_Partner_Sales_Rep_Company__c&apos; field on the Opportunity.</description>
    <label>Partner Sales Rep Company</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Account.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>NPN_Account_Registry</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Tegra Embd Regstr Expiration by Partners</relationshipLabel>
    <relationshipName>Tegra_Embd_Regstr_Expiration_by_Partners</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tegra_Embd_Regstr_Expiry_Notifications__c/Tegra_Embd_Regstr_Expiry_Notifications__c.object-meta.xml
<CustomObject>
    <description>This object will have the Email Notifications those sent to the users by the batch class &apos;TegraEmb_Regstr_Expirations_Batch.cls&apos;</description>
    <label>Tegra Embd Regstr Expiry Notifications</label>
    <nameField>
        <displayFormat>EN-{00000000}</displayFormat>
        <label>Record Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tegra Embd Regstr Expiry Notifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Tegra_Embd_Regstr_Expiry_Notifications__c/fields/First_Notification_Sent__c.field-meta.xml
<CustomField>
    <fullName>First_Notification_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>First Notification Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tegra_Embd_Regstr_Expiry_Notifications__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Opportunity</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Opportunity.RecordType.DeveloperName</field>
            <operation>equals</operation>
            <value>Tegra_Embedded_Partner_Opportunity</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Tegra Embd Regstr Expiry Notifications</relationshipLabel>
    <relationshipName>Tegra_Embd_Regstr_Expiry_Notifications</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Tegra_Embd_Regstr_Expiry_Notifications__c/fields/Second_Notification_Sent__c.field-meta.xml
<CustomField>
    <fullName>Second_Notification_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Second Notification Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tegra_Embd_Regstr_Expiry_Notifications__c/fields/Third_Notification_Sent__c.field-meta.xml
<CustomField>
    <fullName>Third_Notification_Sent__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Third Notification Sent</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/Tegra_Embedded_Registration_Expirations__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This will have the Threshold limit in days for the Registration Expiration and the Threshold limit in days for the Email Notification Reminders for the first, second and third.</description>
    <label>Tegra Embedded Registration Expirations</label>
</CustomObject>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/fields/Default_Cc_Email_Ids__c.field-meta.xml
<CustomField>
    <fullName>Default_Cc_Email_Ids__c</fullName>
    <description>This Email Id&apos;s in this field will be added in the CC for the all the Email Notificaitons (1st, 2nd and 3rd)</description>
    <label>Default Cc Email Ids</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/fields/Default_Oppty_Owner_Email_Id__c.field-meta.xml
<CustomField>
    <fullName>Default_Oppty_Owner_Email_Id__c</fullName>
    <description>This field will have the Email address of the User who will be the Default replaced owner in case of any inActive PBM.</description>
    <label>Default Oppty Owner Email Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/fields/Default_Threshold_for_all_Partners__c.field-meta.xml
<CustomField>
    <fullName>Default_Threshold_for_all_Partners__c</fullName>
    <label>Default Threshold for all Partners</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/fields/First_Reminder__c.field-meta.xml
<CustomField>
    <fullName>First_Reminder__c</fullName>
    <label>First Reminder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/fields/Opportunity_Detail_Link_for_Partner_User__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Detail_Link_for_Partner_User__c</fullName>
    <description>This field will have the URL of Opportunity Detail Link for the Partner Users. This field is being used in the Email Templates for the &apos;Tegra Embedded Partner Opportunity&apos; Expirations project.</description>
    <label>Opportunity Detail Link for Partner User</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/fields/Opportunity_Stages_to_Exclude__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Stages_to_Exclude__c</fullName>
    <description>This field will have the StageNames of the Opportunities those should be excluded from Expiration process.</description>
    <label>Opportunity Stages to Exclude</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/fields/OWD_Sender_Email_Address__c.field-meta.xml
<CustomField>
    <fullName>OWD_Sender_Email_Address__c</fullName>
    <description>This field have the OWD Email Address, which will be used as a Sender</description>
    <label>OWD - Sender Email Address</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/fields/Second_Reminder__c.field-meta.xml
<CustomField>
    <fullName>Second_Reminder__c</fullName>
    <label>Second Reminder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Tegra_Embedded_Registration_Expirations__c/fields/Third_Reminder__c.field-meta.xml
<CustomField>
    <fullName>Third_Reminder__c</fullName>
    <label>Third Reminder</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Used in Enterprise KPIs and Other dashboards</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>NALA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CRM_Tegra_Embd_Reg_Expry_BAT_SCH_Test.cls
/*
 * Author: Manideep
 * Created Date: 2/12/2020
 * JIRA # SDS-1493
 * Description: This Test Class covers the code coverage of the classes below
                - CRM_Tegra_Embd_Reg_Expirations_BAT_SCH.cls
                - CRM_Tegra_Embd_Reg_Exp_BAT_Helper.cls
 */

@isTest
public class CRM_Tegra_Embd_Reg_Expry_BAT_SCH_Test {

    /*
     * Create Custom Setting/Custom object and its values/records needed for this test Class.
     */
    @testSetup static void dataSetup() {

        //Create Partner Users
        Id Pid = [Select Id from Profile where Name = 'Sales Profile - Tegra Embedded'].Id;
        Id RoleId = [Select Id From UserRole where Name = 'Sales Europe Manager - Tegra Auto/Emb'].Id;

        List<User> Users = new List<User>();
        User u;

        u = new User(FirstName = 'test', LastName = 'user 1', email = 'tusr1@example.com', Username = 'tusr1@example.com', Alias='bd', TimeZoneSidKey = 'America/Los_Angeles',
                     EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = Pid, UserRoleId = RoleId);
        Users.add(u);
        u = new User(FirstName = 'test', LastName = 'user 2', email = 'tusr2@example.com', Username = 'tusr2@example.com', Alias='bd', TimeZoneSidKey = 'America/Los_Angeles',
                     EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = Pid, UserRoleId = RoleId);
        Users.add(u);
        u = new User(FirstName = 'test', LastName = 'user 3', email = 'tusr3@example.com', Username = 'tusr3@example.com', Alias='bd', TimeZoneSidKey = 'America/Los_Angeles',
                     EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = Pid, UserRoleId = RoleId);
        Users.add(u);
        u = new User(FirstName = 'test', LastName = 'user 4', email = 'tusr4@example.com', Username = 'tusr4@example.com', Alias='bd', TimeZoneSidKey = 'America/Los_Angeles',
                     EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = Pid, UserRoleId = RoleId);
        Users.add(u);
        u = new User(FirstName = 'test', LastName = 'user 5', email = 'tusr5@example.com', Username = 'tusr5@example.com', Alias='bd', TimeZoneSidKey = 'America/Los_Angeles',
                     EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = Pid, UserRoleId = RoleId);
        Users.add(u);
        u = new User(FirstName = 'test', LastName = 'user 6', email = 'tusr6@example.com', Username = 'tusr6@example.com', Alias='bd', TimeZoneSidKey = 'America/Los_Angeles',
                     EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = Pid, UserRoleId = RoleId);
        Users.add(u);
        u = new User(FirstName = 'test', LastName = 'user 7', email = 'tusr7@example.com', Username = 'tusr7@example.com', Alias='bd', TimeZoneSidKey = 'America/Los_Angeles',
                     EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = Pid, UserRoleId = RoleId);
        Users.add(u);
        u = new User(FirstName = 'test', LastName = 'user 8', email = 'tusr8@example.com', Username = 'tusr8@example.com', Alias='bd', TimeZoneSidKey = 'America/Los_Angeles',
                     EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = Pid, UserRoleId = RoleId);
        Users.add(u);
        u = new User(FirstName = 'test', LastName = 'user 9', email = 'tusr9@example.com', Username = 'tusr9@example.com', Alias='bd', TimeZoneSidKey = 'America/Los_Angeles',
                     EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = Pid, UserRoleId = RoleId);
        Users.add(u);
        u = new User(FirstName = 'test', LastName = 'user 10', email = 'tusr10@example.com', Username = 'tusr10@example.com', Alias='bd', TimeZoneSidKey = 'America/Los_Angeles',
                     EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = Pid, UserRoleId = RoleId);
        Users.add(u);
        u = new User(FirstName = 'test', LastName = 'user 11', email = 'tusr11@example.com', Username = 'tusr11@example.com', Alias='bd', TimeZoneSidKey = 'America/Los_Angeles',
                     EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = Pid, UserRoleId = RoleId);
        Users.add(u);
        u = new User(FirstName = 'test', LastName = 'user 12', email = 'tusr12@example.com', Username = 'tusr12@example.com', Alias='bd', TimeZoneSidKey = 'America/Los_Angeles',
                     EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = Pid, UserRoleId = RoleId);
        Users.add(u);
        u = new User(FirstName = 'test', LastName = 'default Owner', email = 'testdefaultowner@nvidia.com', Username = 'testdefaultowner@nvidia.com', Alias='bd', TimeZoneSidKey = 'America/Los_Angeles',
                     EmailEncodingKey = 'UTF-8', LanguageLocaleKey = 'en_US', LocaleSidKey = 'en_US', ProfileId = Pid, UserRoleId = RoleId);
        Users.add(u);

        User usr = [Select Id from User where Id = :UserInfo.getUserId()];
        system.runAs(usr) {
            insert Users;
        }

        List<User> UserList = [Select Id, Name from User where CreatedDate = Today AND ProfileId = :Pid AND UserRoleId = :RoleId ORDER BY email ASC];

        // Create Custom Setting to define various reminder timelines, Default Owner, Send email as, cc users in Notifications etc.,
        list<Tegra_Embedded_Registration_Expirations__c> tegEmbRegExpList = new list<Tegra_Embedded_Registration_Expirations__c>();
        Tegra_Embedded_Registration_Expirations__c terExp = new Tegra_Embedded_Registration_Expirations__c(Default_Threshold_for_all_Partners__c = 60, First_Reminder__c = 14, Second_Reminder__c = 5, Third_Reminder__c = 0,
                                                                                                           Default_Oppty_Owner_Email_Id__c = 'testdefaultowner@nvidia.com',
                                                                                                           Default_Cc_Email_Ids__c = 'testdefaultowner@nvidia.com', OWD_Sender_Email_Address__c = 'no_reply@nvidia.com',
                                                                                                           Opportunity_Detail_Link_for_Partner_User__c = 'https://stid.nvidia.com/sfdcContent/index.html?retURL=/',
                                                                                                           Opportunity_Stages_to_Exclude__c = 'Closed Won;Closed Lost;Closed - Program Canceled;');
        tegEmbRegExpList.add(terExp);
        insert tegEmbRegExpList; // Create Custom Setting values

        // Create records for ChannelAdmin Approval Routing and pass the Channel Admins by each Region
        List<ChannelAdmin_Approval_Routing__c> chAdminAprRtngList = new List<ChannelAdmin_Approval_Routing__c>();

        chAdminAprRtngList.add( new ChannelAdmin_Approval_Routing__c ( Name = 'JP', Jetson_Approver__c = UserList[4].Id));
        chAdminAprRtngList.add( new ChannelAdmin_Approval_Routing__c ( Name = 'KR', Jetson_Approver__c = UserList[5].Id));
        chAdminAprRtngList.add( new ChannelAdmin_Approval_Routing__c ( Name = 'US', Jetson_Approver__c = UserList[1].Id));
        chAdminAprRtngList.add( new ChannelAdmin_Approval_Routing__c ( Name = 'CN', Jetson_Approver__c = UserList[3].Id));
        chAdminAprRtngList.add( new ChannelAdmin_Approval_Routing__c ( Name = 'RU', Jetson_Approver__c = UserList[7].Id));
        chAdminAprRtngList.add( new ChannelAdmin_Approval_Routing__c ( Name = 'FR', Jetson_Approver__c = UserList[10].Id));


        insert chAdminAprRtngList;
    }


    /*
     * This method covers code coverage for "TegraEmb_Regstr_Expirations_Batch"
       and for its helper class "TegraEmb_Regstr_Expirations_Batch_Helper".
     */
    private static testMethod void insertAndUpdateTegraOpportunitywithDatesForBatch() {

        list<Opportunity> tEmdOpplst = new list<Opportunity>(); // list for Opportunities
        User usr = [Select Id from User where Id = :UserInfo.getUserId()];

        // Fetch the Opportunity Record Type 'Tegra Embedded Partner Opportunity' by Name
        map<string, Id> map_tEmbd_Opportunity_RT = COMM_Utility.getRTsByName(COMM_Constants.SOBJECT_OPPORTUNITY, COMM_Constants.OPPTY_RT_TEGRA_EMBEDDED_PARTNER_OPPTY);

        /*
           // Create Accounts
           for(integer i=1; i<10; i++) {
            Account acc = new Account();
            acc.Name = 'TegraEmb_Regstr_Expirations_Batch_Test_' + 'Acc' + i;
            acc.RecordTypeId = map_CUSTOMER_ACCOUNT_RT.get(COMM_Constants.ACCOUNT_RT_NV_PPA);
            accList.add(acc);
           }
           insert accList;
           list<Account> accList2 = [SELECT Id, Name from Account WHERE Name LIKE '%TegraEmb_Regstr_Expirations_Batch_Test_Acc%' ORDER BY Name ASC];
         */

        /*
           list<Account> accList3 = [SELECT Id, Name from Account WHERE RecordType.Name = :COMM_Constants.ACCOUNT_RT_NV_PPA
                                  AND Name LIKE '%TegraEmb_Regstr_Expirations_Batch_Test_Acc%'
                                  ORDER BY Name ASC];
           system.debug('accList3------>'+accList3);
         */

        // Create Partner Account, Contact and User
        map<String, Id> mapPP_PartnerProgramAccount_RT = COMM_Utility.getRTsByName(COMM_Constants.SOBJECT_ACCOUNT, COMM_Constants.ACCOUNT_RT_NV_PPA);
        map<String, Id> mapPP_PartnerContact_RT = COMM_Utility.getRTsByName(COMM_Constants.SOBJECT_CONTACT, COMM_Constants.CONTACT_RT_PARTNER_CONTACT);
        map<string, Id> mapPP_TPP_Generic_Prof = COMM_Utility.getProfsByName(COMM_Constants.PROF_PP_TPP_GENERIC);

        
        // Create Partner Account (string Name, string RecordTypeId, Boolean isPartner, Boolean isCustomerPortal)
        Account partnerAccount = Test_COMM_Factory.createAccount('TegraEmb_Regstr_Expirations_Batch_Test_Acc_1', mapPP_PartnerProgramAccount_RT.get(COMM_Constants.ACCOUNT_RT_NV_PPA), true, false);

        //Create a Partner Contact
        Contact partnerContact = Test_COMM_Factory.createContact('TegraEmb_Regstr_Expirations_Batch_Test_PC_1', 'TestPC1@nv.com', partnerAccount.Id, mapPP_PartnerContact_RT.get(COMM_Constants.CONTACT_RT_PARTNER_CONTACT), COMM_Constants.CON_PPG_COMMUNITY);

        //Create a Partner User
        User partnerUser = Test_COMM_Factory.createUserWithEmail(partnerContact.Id, partnerContact.email, mapPP_TPP_Generic_Prof.get(COMM_Constants.PROF_PP_TPP_GENERIC));
        list<user> lstPU = [Select email, IsPortalEnabled, UserType From User Where id =:partnerUser.Id AND IsPortalEnabled = TRUE];

        // Create records for the Custom object 'Tegra Embedded Regstr Expiration by Partner'
        list<Tegra_Embd_Regstr_Expiration_by_Partners__c> tembRegExpbyPartnerList = new list<Tegra_Embd_Regstr_Expiration_by_Partners__c>();

        Account pacct = [Select Id, Name, RecordTypeId, RecordType.Name, BillingStreet, BillingCity, BillingState, BillingCountry, BillingPostalCode from Account where Id =:partnerAccount.Id];
        pacct.BillingStreet = '1234 Test Street';
        pacct.BillingCity = 'Santa Clara';
        pacct.BillingState = 'California';
        pacct.BillingCountry = 'United States';
        pacct.BillingPostalCode = '12345';
        update pacct;
        system.debug('pacct------->'+pacct);

        //for(integer i=1; i<10; i++) {
        Tegra_Embd_Regstr_Expiration_by_Partners__c terExpPartner = new Tegra_Embd_Regstr_Expiration_by_Partners__c();
        //terExpPartner.Partner_Sales_Rep_Company__c = accList2[i-1].Id;
        terExpPartner.Partner_Sales_Rep_Company__c = pacct.Id;
        terExpPartner.Default_Threshold_Limit_for_Partner__c = 60;
        terExpPartner.Expire_Registration__c = True;
        tembRegExpbyPartnerList.add(terExpPartner);
        //}
        system.debug('tembRegExpbyPartnerList before insert----->'+tembRegExpbyPartnerList);
        insert tembRegExpbyPartnerList; // Create records into Custom Object 'Tegra Embd Regstr Expiration by Partners'

        list<Account> partAccList = [SELECT Id, Name from Account WHERE RecordType.Name =:COMM_Constants.ACCOUNT_RT_NV_PPA
                                                                                          AND Name LIKE '%TegraEmb_Regstr_Expirations_Batch_Test_Acc%'
                                                                                          ORDER BY Name
                                                                                          ASC];
        system.debug('partAccList------>'+partAccList);

        // login as Partner User
        system.runAs(partnerUser) {

            // Create Opportunities for 1st Email Notification
            for(integer i=1; i<4; i++) {
                Opportunity opp = new Opportunity();
                opp.Name = 'TegraEmb_Regstr_Expirations_Batch_Test_' + 'opp' + i;
                opp.ownerId = usr.id;
                //opp.AccountId = accList2[i-1].Id;
                opp.AccountId = partnerAccount.Id;
                opp.StageName = 'Prospect';
                opp.RecordTypeId = map_tEmbd_Opportunity_RT.get(COMM_Constants.OPPTY_RT_TEGRA_EMBEDDED_PARTNER_OPPTY);
                //opp.DR_Partner_Sales_Rep_Company__c = accList3[i-1].Id;
                opp.DR_Partner_Sales_Rep_Company__c = partAccList[0].Id;
                opp.DR_SalesOps_Approver__c = partnerUser.Id;
                opp.Opportunity_Expired__c = false;
                opp.LastModifiedDate_by_Partner__c = (system.today() - 46);
                opp.CloseDate = system.today() + 10;
                opp.Region__c = 'EMEA';
                tEmdOpplst.add(opp);
            }

            // Create Opportunities for 2nd Email Notification
            for(integer i=4; i<7; i++) {
                Opportunity opp = new Opportunity();
                opp.Name = 'TegraEmb_Regstr_Expirations_Batch_Test_' + 'opp' + i;
                opp.ownerId = usr.id;
                //opp.AccountId = accList2[i-1].Id;
                opp.AccountId = partnerAccount.Id;
                opp.StageName = 'Prospect';
                opp.RecordTypeId = map_tEmbd_Opportunity_RT.get(COMM_Constants.OPPTY_RT_TEGRA_EMBEDDED_PARTNER_OPPTY);
                //opp.DR_Partner_Sales_Rep_Company__c = accList3[i-1].Id;
                opp.DR_Partner_Sales_Rep_Company__c = partAccList[0].Id;
                opp.DR_SalesOps_Approver__c = partnerUser.Id;
                opp.Opportunity_Expired__c = false;
                opp.LastModifiedDate_by_Partner__c = (system.today() - 55);
                opp.CloseDate = system.today() + 10;
                opp.Region__c = 'NALA';
                tEmdOpplst.add(opp);
            }

            // Create Opportunities for 3rd Email Notification
            for(integer i=7; i<10; i++) {
                Opportunity opp = new Opportunity();
                opp.Name = 'TegraEmb_Regstr_Expirations_Batch_Test_' + 'opp' + i;
                opp.ownerId = usr.id;
                //opp.AccountId = accList2[i-1].Id;
                opp.AccountId = partnerAccount.Id;
                opp.StageName = 'Prospect';
                opp.RecordTypeId = map_tEmbd_Opportunity_RT.get(COMM_Constants.OPPTY_RT_TEGRA_EMBEDDED_PARTNER_OPPTY);
                //opp.DR_Partner_Sales_Rep_Company__c = accList3[i-1].Id;
                opp.DR_Partner_Sales_Rep_Company__c = partAccList[0].Id;
                opp.DR_SalesOps_Approver__c = partnerUser.Id;
                opp.Opportunity_Expired__c = false;
                opp.LastModifiedDate_by_Partner__c = (system.today() - 60);
                opp.CloseDate = system.today() + 10;
                opp.Region__c = 'EMEA';
                tEmdOpplst.add(opp);
            }

            insert tEmdOpplst;

        } // end of login As Partner User

        list<Opportunity> tegraPartnerOppList = [SELECT Id, Name, RecordType.Name, DR_Partner_Sales_Rep_Company__c, DR_SalesOps_Approver__c, LastModifiedDate_by_Partner__c
                                                 FROM Opportunity
                                                 WHERE RecordType.Name = :COMM_Constants.OPPTY_RT_TEGRA_EMBEDDED_PARTNER_OPPTY
                                                                         AND Name LIKE '%TegraEmb_Regstr_Expirations_Batch_Test_opp%'
                                                                         AND CreatedDate = Today
                                                                                           ORDER BY Name
                                                                                           ASC];
        system.debug('tegraPartnerOppList------>'+tegraPartnerOppList);

        // Manually populate the 'LastModifiedDate_by_Partner__c' field again as the logic in Opportunity trigger will overwrite the above inserted dates because earlier logged in as Partner User for inserting Opportunities.
        integer counter = 0;
        for(Opportunity tegOpp: tegraPartnerOppList) {
            counter = counter + 1;
            if(counter>0 && counter<4) tegOpp.LastModifiedDate_by_Partner__c = (system.today() - 46);
            if(counter>3 && counter<7) tegOpp.LastModifiedDate_by_Partner__c = (system.today() - 55);
            if(counter>6 && counter<10) tegOpp.LastModifiedDate_by_Partner__c = (system.today() - 60);
        }
        system.debug('tegraPartnerOppList------>'+tegraPartnerOppList);
        update tegraPartnerOppList;

        // invoke the batch class
        Test.StartTest();
        CRM_Tegra_Embd_Reg_Expry_BAT_SCH schBatch = new CRM_Tegra_Embd_Reg_Expry_BAT_SCH();
        String schTime = '0 0 23 * * ?';
        system.schedule('Test check', schTime, schBatch);
        Test.stopTest();

        /*
           // Validate if the Email Notifications are created successfully in the custom object 'Tegra Embd Regstr Expiry Notifications'
           list<Tegra_Embd_Regstr_Expiry_Notifications__c> tegRegExpNotificationList = [SELECT Id, Opportunity__c, First_Notification_Sent__c, Second_Notification_Sent__c, Third_Notification_Sent__c
                                                                                     FROM Tegra_Embd_Regstr_Expiry_Notifications__c
                                                                                     WHERE Name LIKE '%TegraEmb_Regstr_Expirations_Batch_Test_opp%'
                                                                                     AND CreatedDate = Today
                                                                                     ORDER BY Name
                                                                                     ASC];
           system.assertEquals(tegRegExpNotificationList.size(), 9);  // Total no. of notifications sent

           system.assertEquals(tegRegExpNotificationList[0].Opportunity__c, tegraPartnerOppList[0].Id);
           system.assertEquals(tegRegExpNotificationList[0].First_Notification_Sent__c, True);

           system.assertEquals(tegRegExpNotificationList[1].Opportunity__c, tegraPartnerOppList[1].Id);
           system.assertEquals(tegRegExpNotificationList[1].First_Notification_Sent__c, True);

           system.assertEquals(tegRegExpNotificationList[2].Opportunity__c, tegraPartnerOppList[2].Id);
           system.assertEquals(tegRegExpNotificationList[2].First_Notification_Sent__c, True);

           system.assertEquals(tegRegExpNotificationList[3].Opportunity__c, tegraPartnerOppList[3].Id);
           system.assertEquals(tegRegExpNotificationList[3].Second_Notification_Sent__c, True);

           system.assertEquals(tegRegExpNotificationList[4].Opportunity__c, tegraPartnerOppList[4].Id);
           system.assertEquals(tegRegExpNotificationList[4].Second_Notification_Sent__c, True);

           system.assertEquals(tegRegExpNotificationList[5].Opportunity__c, tegraPartnerOppList[5].Id);
           system.assertEquals(tegRegExpNotificationList[5].Second_Notification_Sent__c, True);

           system.assertEquals(tegRegExpNotificationList[6].Opportunity__c, tegraPartnerOppList[6].Id);
           system.assertEquals(tegRegExpNotificationList[6].Third_Notification_Sent__c, True);

           system.assertEquals(tegRegExpNotificationList[7].Opportunity__c, tegraPartnerOppList[7].Id);
           system.assertEquals(tegRegExpNotificationList[7].Third_Notification_Sent__c, True);

           system.assertEquals(tegRegExpNotificationList[8].Opportunity__c, tegraPartnerOppList[8].Id);
           system.assertEquals(tegRegExpNotificationList[8].Third_Notification_Sent__c, True);
         */

    } // end of insertAndUpdateTegraOpportunitywithDatesForBatch()

}