force-app/main/default/objects/SuRF_Contacts__c/SuRF_Contacts__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF-Contact</label>
    <nameField>
        <displayFormat>SuRF-C-{00000}</displayFormat>
        <label>SuRF-Contacts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuRF-Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_Contacts__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Service and Support</fullName>
            </value>
            <value>
                <fullName>Service &amp; Support</fullName>
            </value>
            <value>
                <fullName>RMA</fullName>
            </value>
            <value>
                <fullName>MDF</fullName>
            </value>
            <value>
                <fullName>Marketing;MDF</fullName>
            </value>
            <value>
                <fullName>Marketing;POS</fullName>
            </value>
            <value>
                <fullName>Marketing;POS;MDF</fullName>
            </value>
            <value>
                <fullName>Marketing;POS;Partner Primary Contact</fullName>
            </value>
            <value>
                <fullName>Marketing;POS;Partner Primary Contact;MDF</fullName>
            </value>
            <value>
                <fullName>Marketing;Partner Primary Contact</fullName>
            </value>
            <value>
                <fullName>Marketing;Partner Primary Contact;MDF</fullName>
            </value>
            <value>
                <fullName>Marketing;RMA</fullName>
            </value>
            <value>
                <fullName>Marketing;RMA;POS</fullName>
            </value>
            <value>
                <fullName>Marketing;Service and Support;Partner Primary Contact;MDF</fullName>
            </value>
            <value>
                <fullName>Marketing;Technical</fullName>
            </value>
            <value>
                <fullName>Marketing;Technical;POS;Partner Primary Contact;MDF</fullName>
            </value>
            <value>
                <fullName>Marketing;Technical;Service and Support</fullName>
            </value>
            <value>
                <fullName>Marketing;Technical;Service and Support;POS</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>POS;MDF</fullName>
            </value>
            <value>
                <fullName>POS;Partner Primary Contact</fullName>
            </value>
            <value>
                <fullName>POS;Partner Primary Contact;MDF</fullName>
            </value>
            <value>
                <fullName>Partner Primary Contact</fullName>
            </value>
            <value>
                <fullName>Partner Primary Contact;MDF</fullName>
            </value>
            <value>
                <fullName>RMA;POS;Partner Primary Contact</fullName>
            </value>
            <value>
                <fullName>RMA;POS;Partner Primary Contact;MDF</fullName>
            </value>
            <value>
                <fullName>RMA;Partner Primary Contact;MDF</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SuRF_Contacts_Trans__c/SuRF_Contacts_Trans__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF-Contacts Trans</label>
    <nameField>
        <displayFormat>SuRF-C-{00000}</displayFormat>
        <label>SuRF-Contacts Trans Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuRF-Contacts Trans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_Contacts_Trans__c/fields/Phone_Number__c.field-meta.xml
<CustomField>
    <fullName>Phone_Number__c</fullName>
    <label>Phone Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NPN_SuRF_Batch_C.cls
global class NPN_SuRF_Batch_C implements Database.batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator([SELECT Account_ID__c
                                         ,Contact_Name__c
                                         ,Email__c
                                         ,Phone_Number__c
                                         ,Role__c
                                         FROM SuRF_Contacts__c
                                         WHERE isDeleted = false]);
    }
    global void execute(Database.BatchableContext BC, List<SuRF_Contacts__c> scope) {
        List<SuRF_Contacts_Trans__c> lst = new List<SuRF_Contacts_Trans__c>();
        for(SuRF_Contacts__c obj : scope) {
            SuRF_Contacts_Trans__c transObj = new SuRF_Contacts_Trans__c();
            transObj.Account_ID__c = obj.Account_ID__c;
            transObj.Contact_Name__c = obj.Contact_Name__c;
            transObj.Email__c = obj.Email__c;
            transObj.Phone_Number__c = obj.Phone_Number__c;
            transObj.Role__c = obj.Role__c;
            lst.add(transObj);
        }
        insert lst;
    }
    global void finish(Database.BatchableContext BC) {
    }
}