force-app/main/default/objects/SuRF_Contacts__c/SuRF_Contacts__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF-Contact</label>
    <nameField>
        <displayFormat>SuRF-C-{00000}</displayFormat>
        <label>SuRF-Contacts Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuRF-Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_Contacts_and_Training__c/SuRF_Contacts_and_Training__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF-Contacts and Training</label>
    <nameField>
        <displayFormat>SuRF-CT-{00000}</displayFormat>
        <label>SuRF-Contacts and Training Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuRF-Contacts and Trainings</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_DGX_HOT_Compliance__c/SuRF_DGX_HOT_Compliance__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF_DGX_HOT_Compliance</label>
    <nameField>
        <label>SuRF_DGX_HOT_Compliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SuRF_DGX_HOT_Compliance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_DGX_HOT_CPL_Contacts__c/SuRF_DGX_HOT_CPL_Contacts__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF_DGX_HOT_CPL_Contacts</label>
    <nameField>
        <label>SuRF_DGX_HOT_CPL_Contacts Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SuRF_DGX_HOT_CPL_Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_Lead_Management__c/SuRF_Lead_Management__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF-Lead Management</label>
    <nameField>
        <displayFormat>SuRF-LM-{00000}</displayFormat>
        <label>SuRF-Lead Management Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuRF-Lead Management</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_Opportunity__c/SuRF_Opportunity__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF-Opportunity</label>
    <nameField>
        <displayFormat>SuRF-OPP-{00000}</displayFormat>
        <label>SuRF-Opportunity Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuRF-Opportunities</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_Partner_Performance_Scorecard__c/SuRF_Partner_Performance_Scorecard__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF-Partner Performance Scorecard</label>
    <nameField>
        <displayFormat>SuRF-PPS-{00000}</displayFormat>
        <label>SuRF-Partner Performance Scorecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuRF-Partner Performance Scorecards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_Portal_Login__c/SuRF_Portal_Login__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF-Portal Login</label>
    <nameField>
        <displayFormat>SuRF-PL-{00000}</displayFormat>
        <label>SuRF Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuRF-Portal Logins</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_POS__c/SuRF_POS__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF-POS</label>
    <nameField>
        <displayFormat>SuRF-POS-{00000}</displayFormat>
        <label>SuRF-POS Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuRF-POS</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_POS_Submission__c/SuRF_POS_Submission__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF-POS Submission</label>
    <nameField>
        <displayFormat>SuRF-POS_SUB-{00000}</displayFormat>
        <label>SuRF-POS Submission Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuRF-POS Submissions</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_Transit__c/SuRF_Transit__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SuRF Transit</label>
</CustomObject>

force-app/main/default/objects/SuRF_Transit__c/fields/isTransit__c.field-meta.xml
<CustomField>
    <fullName>isTransit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isTransit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/SuRF_UpdateStart__c/SuRF_UpdateStart__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF-UpdateStart</label>
    <nameField>
        <displayFormat>SuRF-US-{00000}</displayFormat>
        <label>SuRF-UpdateStart Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuRF-UpdateStart</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_UpdateTime__c/SuRF_UpdateTime__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF-UpdateTime</label>
    <nameField>
        <displayFormat>SuRF-UT-{00000}</displayFormat>
        <label>SuRF-UpdateTime Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuRF-UpdateTime</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/classes/NPN_Test_Surf_Batch.cls
@isTest
private class NPN_Test_Surf_Batch {
    
    static testMethod void testBatchC() {
        SuRF_Contacts__c objSC = new SuRF_Contacts__c();
        insert objSC;
        NPN_SuRF_Batch_C objC = new NPN_SuRF_Batch_C();
        Database.executeBatch(objC);
    }
    
    static testMethod void testBatchCT() {
        SuRF_Contacts_and_Training__c objSCT = new SuRF_Contacts_and_Training__c();
        insert objSCT;
        NPN_SuRF_Batch_CT objCT = new NPN_SuRF_Batch_CT();
        Database.executeBatch(objCT);
    }
    
    static testMethod void testBatchLM() {
        SuRF_Lead_Management__c objSLM = new SuRF_Lead_Management__c();
        insert objSLM;
        NPN_SuRF_Batch_LM objLM = new NPN_SuRF_Batch_LM();
        Database.executeBatch(objLM);
    }
    
    static testMethod void testBatchO() {
        SuRF_Opportunity__c objSO = new SuRF_Opportunity__c();
        insert objSO;
        NPN_SuRF_Batch_O objO = new NPN_SuRF_Batch_O();
        Database.executeBatch(objO);
    }
    
    static testMethod void testBatchPL() {
        SuRF_Portal_Login__c objSPL = new SuRF_Portal_Login__c();
        insert objSPL;
        NPN_SuRF_Batch_PL objPL = new NPN_SuRF_Batch_PL();
        Database.executeBatch(objPL);
    }
    
    static testMethod void testBatchPOS() {
        SuRF_POS__c objSPOS = new SuRF_POS__c();
        insert objSPOS;
        NPN_SuRF_Batch_POS objPOS = new NPN_SuRF_Batch_POS();
        Database.executeBatch(objPOS);
    }
    
    static testMethod void testBatchPPS() {
        SuRF_Partner_Performance_Scorecard__c objSPPS = new SuRF_Partner_Performance_Scorecard__c();
        insert objSPPS;
        NPN_SuRF_Batch_PPS objPPS = new NPN_SuRF_Batch_PPS();
        Database.executeBatch(objPPS);
    }
    
    static testMethod void testBatchPS() {
        SuRF_Transit__c trans = SuRF_Transit__c.getOrgDefaults();
        trans.isTransit__c = true;
        insert trans;
        SuRF_UpdateTime__c objSUT = new SuRF_UpdateTime__c();
        insert objSUT;
        SuRF_UpdateStart__c objSUS = new SuRF_UpdateStart__c();
        insert objSUS;
        SuRF_POS_Submission__c objSPS = new SuRF_POS_Submission__c();
        insert objSPS;
        NPN_SuRF_Batch_PS objPS = new NPN_SuRF_Batch_PS();
        Database.executeBatch(objPS);
    }

    @isTest 
    static void testBatchDHTC(){
        SuRF_DGX_HOT_Compliance__c  objDHTC = new SuRF_DGX_HOT_Compliance__c ();
        insert objDHTC;
        NPN_SuRF_Batch_DGX_HOT_Compliance objDHTC_Batch = new NPN_SuRF_Batch_DGX_HOT_Compliance();
        Database.executeBatch(objDHTC_Batch);
    }

    @isTest 
    static void testBatchDHTCC(){
        SuRF_DGX_HOT_CPL_Contacts__c  objDHTCC = new SuRF_DGX_HOT_CPL_Contacts__c ();
        insert objDHTCC;
        NPN_SuRF_Batch_DGX_HOT_CPL_Contacts objDHTCC_Batch = new NPN_SuRF_Batch_DGX_HOT_CPL_Contacts();
        Database.executeBatch(objDHTCC_Batch);
    }
}