force-app/main/default/objects/NV_Log__c/NV_Log__c.object-meta.xml
<CustomObject>
    <description>Global Logging Object</description>
    <label>NV Log</label>
    <nameField>
        <displayFormat>Log-{0000000}</displayFormat>
        <label>Nvidia Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NV Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NV_Log__c/fields/Error_Description__c.field-meta.xml
<CustomField>
    <fullName>Error_Description__c</fullName>
    <label>Error Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NV_Log__c/fields/Functionality_Name__c.field-meta.xml
<CustomField>
    <fullName>Functionality_Name__c</fullName>
    <label>Functionality Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service: SAP RMA Callout</fullName>
            </value>
            <value>
                <fullName>IDM: User Sync</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NV_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error: Batch</fullName>
            </value>
            <value>
                <fullName>Error: Trigger</fullName>
            </value>
            <value>
                <fullName>Error: Callout</fullName>
            </value>
            <value>
                <fullName>Error: Other</fullName>
            </value>
            <value>
                <fullName>Error: Future Method</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NV_Log__c/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <inlineHelpText>Record Id or list of record Ids or Batch Job Id etc which can help to locate the exact record.</inlineHelpText>
    <label>Record Id(s)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NV_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchApexErrorEvent_tgr_cls.cls
public with sharing class BatchApexErrorEvent_tgr_cls extends NV_TriggerHandler {
    private static list<BatchApexErrorEvent> newRecords;
    
    public override void init() { 
        OBJECT_NAME = 'BatchApexErrorEvent';
        newRecords 	= trigger.New;
        //System.debug('New Records' + newRecords + '1'); 
    }
    public override void afterInsert() {
    	system.debug('20191213 1');
    	BatchApexErrorEvent_tgr_cls.logErrors();
    }
    
    private static void logErrors() {
    	try {
	    	List<NV_Log__c> logs = new List<NV_Log__c>();
	    	system.debug('20191213 2');
	    	set<Id> jobIds = new set<Id>();
	    	for(BatchApexErrorEvent event : newRecords) {
	    		jobIds.add(event.AsyncApexJobId);
	    	}
	    	
	    	map<Id, AsyncApexJob> asyncJobMap = new map<Id, AsyncApexJob>([SELECT Id, ApexClass.Name,CreatedDate,ExtendedStatus,JobItemsProcessed,JobType,LastProcessed,LastProcessedOffset,MethodName,NumberOfErrors,ParentJobId,Status,TotalJobItems 
	    											FROM AsyncApexJob where id in: jobIds]);
	    	
		    for(BatchApexErrorEvent event : newRecords) {
		    	NV_Log__c nvlog 			= new NV_Log__c();
		        nvlog.Job_ID__c				= event.AsyncApexJobId;
		    	nvlog.Record_ID__c			= event.JobScope;
			    nvlog.Error_Description__c	= event.StackTrace;
		        nvlog.Error_Message__c		= event.Message;
		        
		        AsyncApexJob asyncJob		= asyncJobMap.get(event.AsyncApexJobId);
		        nvlog.Log_Type__c			= asyncJob.JobType;//'Error: Batch';
		    	nvlog.Component_Name__c		= asyncJob.ApexClass.Name;
	            nvlog.Functionality_Name__c	= asyncJob.ApexClass.Name;
	            nvlog.Method_Name__c		= asyncJob.methodname;
	            nvlog.Error_Message__c	   += ', [Extended Status]: ' + asyncJob.ExtendedStatus + ', [Exception Type]: '+ event.ExceptionType;
	            nvlog.Status__c				= 'Exception';
	            
	            logs.add(nvlog);
		    }
		    
		    if (!logs.isEmpty()) {
			    insert logs;
		    }
	    } catch (Exception ex) {
            system.debug('20191213 6');
            //for(BatchApexErrorEvent ent : (list<BatchApexErrorEvent>)scope) {
            map<Id, BatchApexErrorEvent> recordsMap = new map<Id, BatchApexErrorEvent>();
            recordsMap.putAll((list<BatchApexErrorEvent>)newRecords);
            NV_Log__c nvlog = new NV_Log__c(Component_Name__c 	= 'BatchApexErrorEvent_tgr_cls',Error_Description__c	= ''+ex.getStackTraceString(),
                                    		Error_Message__c	= ''+ex.getMessage(),			Functionality_Name__c   = 'BatchApexErrorEvent_tgr_cls',
                                    		Log_Type__c         = 'Error: Batch',				Method_Name__c          = 'afterInsert',
                                    		Record_ID__c        = ''+recordsMap.keySet(),		Status__c           	= 'Exception'
                                );
            insert nvlog;
            //}
        }
    }
}