force-app/main/default/objects/NV_Log__c/NV_Log__c.object-meta.xml
<CustomObject>
    <description>Global Logging Object</description>
    <label>NV Log</label>
    <nameField>
        <displayFormat>Log-{0000000}</displayFormat>
        <label>Nvidia Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NV Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NV_Log__c/fields/Error_Description__c.field-meta.xml
<CustomField>
    <fullName>Error_Description__c</fullName>
    <label>Error Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NV_Log__c/fields/Functionality_Name__c.field-meta.xml
<CustomField>
    <fullName>Functionality_Name__c</fullName>
    <label>Functionality Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service: SAP RMA Callout</fullName>
            </value>
            <value>
                <fullName>IDM: User Sync</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NV_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error: Batch</fullName>
            </value>
            <value>
                <fullName>Error: Trigger</fullName>
            </value>
            <value>
                <fullName>Error: Callout</fullName>
            </value>
            <value>
                <fullName>Error: Other</fullName>
            </value>
            <value>
                <fullName>Error: Future Method</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NV_Log__c/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <inlineHelpText>Record Id or list of record Ids or Batch Job Id etc which can help to locate the exact record.</inlineHelpText>
    <label>Record Id(s)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NV_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NPN_Solution_Provider_VAR__c.field-meta.xml
<CustomField>
    <fullName>NPN_Solution_Provider_VAR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NPN Solution Provider/VAR that applies to this specific opportunity.</description>
    <inlineHelpText>Select the NPN Solution Provider/VAR that applies to this specific opportunity.  This should represent the tier 2 partner involved with the deal.</inlineHelpText>
    <label>NPN Solution Provider/VAR</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>Account.NPN_Active_Program_Competency__c</field>
            <operation>contains</operation>
            <value>Solution Provider, Solutions Integration Partner</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>SW &amp; Service Renewals</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Deal Registration</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (NPN Solution Provider (VAR))</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NPN_Solution_Provider_VAR_Text__c.field-meta.xml
<CustomField>
    <fullName>NPN_Solution_Provider_VAR_Text__c</fullName>
    <description>SDS-2837-Share Opptys with VAR Account Owner and Team</description>
    <label>NPN Solution Provider/VAR(Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Preliminary_OEM_ODM_Disti__c.field-meta.xml
<CustomField>
    <fullName>Preliminary_OEM_ODM_Disti__c</fullName>
    <description>SOQ-120 (Defect) - Renamed the label from Preliminary to Additional</description>
    <inlineHelpText>If there are multiple OEM/ODM or Distis competing for this business please detail here</inlineHelpText>
    <label>Additional OEM/ODM/Disti List</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ADLINK</fullName>
            </value>
            <value>
                <fullName>ADVANTECH</fullName>
            </value>
            <value>
                <fullName>ARROW</fullName>
            </value>
            <value>
                <fullName>ASUS</fullName>
            </value>
            <value>
                <fullName>ATOS</fullName>
            </value>
            <value>
                <fullName>BULL</fullName>
            </value>
            <value>
                <fullName>CARAHSOFT</fullName>
            </value>
            <value>
                <fullName>CEAC International</fullName>
            </value>
            <value>
                <fullName>CIRRASCALE</fullName>
            </value>
            <value>
                <fullName>CISCO</fullName>
            </value>
            <value>
                <fullName>CRAY</fullName>
            </value>
            <value>
                <fullName>CUBIX</fullName>
            </value>
            <value>
                <fullName>DAWNING (SUGON)</fullName>
            </value>
            <value>
                <fullName>DELL</fullName>
            </value>
            <value>
                <fullName>EURO TECH</fullName>
            </value>
            <value>
                <fullName>FOXCONN</fullName>
            </value>
            <value>
                <fullName>FUJITSU</fullName>
            </value>
            <value>
                <fullName>GERMANE SYSTEMS</fullName>
            </value>
            <value>
                <fullName>GIGABYTE</fullName>
            </value>
            <value>
                <fullName>H3C</fullName>
            </value>
            <value>
                <fullName>HPE</fullName>
            </value>
            <value>
                <fullName>HPI</fullName>
            </value>
            <value>
                <fullName>HUAWEI</fullName>
            </value>
            <value>
                <fullName>IBM</fullName>
            </value>
            <value>
                <fullName>INGRAM MICRO</fullName>
            </value>
            <value>
                <fullName>INSPUR</fullName>
            </value>
            <value>
                <fullName>INVENTEC</fullName>
            </value>
            <value>
                <fullName>ISOLIN TRADE &amp; INVEST LIMITED</fullName>
            </value>
            <value>
                <fullName>LEADTEK</fullName>
            </value>
            <value>
                <fullName>LENOVO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Preliminary_OEM_ODM_Disti_List_Text__c.field-meta.xml
<CustomField>
    <fullName>Preliminary_OEM_ODM_Disti_List_Text__c</fullName>
    <description>SDS-2075-Sales: Enable partner sharing when Opptys are prelim with Partners. Auto set from Preliminary OEM/ODM/Disti List (multi-picklist) to be used in sharing rules</description>
    <inlineHelpText>Auto set from Preliminary OEM/ODM/Disti List (multi-picklist) to be used in sharing rules</inlineHelpText>
    <label>Additional OEM/ODM/Disti List(Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_NPN_OEM_ODM_Disti__c.field-meta.xml
<CustomField>
    <fullName>Primary_NPN_OEM_ODM_Disti__c</fullName>
    <businessOwnerUser>oweber@nvidia.com.trprod</businessOwnerUser>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SOQ-79

5/24/2021 Geo Update: Updated help text. Added admin field information like Data Owner.</description>
    <inlineHelpText>Please identify the partner who will issue the PO to NVIDIA</inlineHelpText>
    <label>Primary NPN OEM/ODM/Disti</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please make sure to only select those Accounts marked as business engagement layer partner Accounts</errorMessage>
        <filterItems>
            <field>Account.Business_Engagement_Relationship__c</field>
            <operation>equals</operation>
            <value>Distributor, ODM, OEM</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Primary NPN OEM/ODM/Disti)</relationshipLabel>
    <relationshipName>PartnerOpportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_NPN_OEM_ODM_Disti_Text__c.field-meta.xml
<CustomField>
    <fullName>Primary_NPN_OEM_ODM_Disti_Text__c</fullName>
    <description>SOQ-79: Copy NPN/OEM/ODM/DIST Name to be used in the sharing rules - lookup field is not supported in Criteria based sharing rules</description>
    <label>Primary NPN OEM/ODM/Disti(Text)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Tracker_Processor__c/Platform_Event_Tracker_Processor__c.object-meta.xml
<CustomObject>
    <description>Infra : Captures predefined change events</description>
    <label>Platform-Event-Tracker-Processor</label>
    <nameField>
        <displayFormat>Event-{00000}</displayFormat>
        <label>Platform-Event-Tracker-Processor Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Platform-Event-Tracker-Processor</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Platform_Event_Tracker_Processor__c/fields/EventName__c.field-meta.xml
<CustomField>
    <fullName>EventName__c</fullName>
    <label>EventName</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Platform_Event_Tracker_Processor__c/fields/ProcessedDate__c.field-meta.xml
<CustomField>
    <fullName>ProcessedDate__c</fullName>
    <label>ProcessedDate</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/Opp_NPNOEMODMDISTI_Event_Tracker_Bat.cls
public class Opp_NPNOEMODMDISTI_Event_Tracker_Bat implements Database.Batchable<SObject>, System.Schedulable, Database.Stateful{
        
    private static final string EVENTNAME = 'NPNOEMODMDISTI';
    private static final integer iBatchSize = 20;
    list<Id> lstProcessedRecordIds = new list<Id>(); //Use it to update the records in the finish method
    set<Id> setUniqueRecordIds = new set<Id> ();
    List<Platform_Event_Tracker_Processor__c> lstEvents = new list<Platform_Event_Tracker_Processor__c>();

    //Constructor
    public Opp_NPNOEMODMDISTI_Event_Tracker_Bat() {}

    //Schedulable interface method implementation.
    public void execute(SchedulableContext sc){
        system.debug('------------------Start: Schedule Batch Job Opp_NPNOEMODMDISTI_Event_Tracker_Bat ---------------------------');
        Opp_NPNOEMODMDISTI_Event_Tracker_Bat oJob = new Opp_NPNOEMODMDISTI_Event_Tracker_Bat();
        database.executeBatch(oJob, iBatchSize);

        /*
        DateTime nextScheduleTime = system.now().addMinutes(2);
	    string minute = string.valueof(nextScheduleTime.minute());
	    string second = string.valueof(nextScheduleTime.second ());
	    string cronValue = second + ' ' + minute + ' * * * ?' ;
	    string jobName = 'Opp_NPNOEMODMDISTI_Event_Tracker_Bat - ' + nextScheduleTime.format('hh:mm');
	    Opp_NPNOEMODMDISTI_Event_Tracker_Bat oSchCls = new Opp_NPNOEMODMDISTI_Event_Tracker_Bat();
	    system.schedule(jobName, cronValue , oSchCls);
        system.debug('------------------End: Schedule Batch Job Opp_NPNOEMODMDISTI_Event_Tracker_Bat ---------------------------');
        */

        system.debug('------------------End: Schedule Batch Job Opp_NPNOEMODMDISTI_Event_Tracker_Bat ---------------------------');
    }


    //*************************************************************************************************************************
    //  BATCH METHODs
    //*************************************************************************************************************************
    public Database.QueryLocator start(Database.BatchableContext BC){
        system.debug('*******Enters Batch Start Method');
        return Database.getQueryLocator([   SELECT Id, EventName__c, ObjectName__c, ProcessedDate__c, Processed__c, RecordId__c 
                                            FROM Platform_Event_Tracker_Processor__c
                                            WHERE Processed__c = false
                                                AND EventName__c = :EVENTNAME
                                            Order By LastModifiedDate
                                        ]);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope){
        system.debug('---------Entering Batch Job Opp_NPNOEMODMDISTI_Event_Tracker_Bat execute method-------------------');
        if (scope != null && !scope.isEmpty()){
            lstEvents = (List<Platform_Event_Tracker_Processor__c>) scope;
            for (Platform_Event_Tracker_Processor__c event : lstEvents){
                setUniqueRecordIds.add(event.RecordId__c);
            }

            //Update the Opportunities
            list<Opportunity> lstOpps = [Select Id, 
                                            NPN_Solution_Provider_VAR__r.name, NPN_Solution_Provider_VAR_Text__c, 
                                            Primary_NPN_OEM_ODM_Disti__r.name, Primary_NPN_OEM_ODM_Disti_Text__c, 
                                            Preliminary_OEM_ODM_Disti__c, Preliminary_OEM_ODM_Disti_List_Text__c 
                                        From Opportunity 
                                        Where Id = :setUniqueRecordIds];
            for (Opportunity opp : lstOpps ){
                opp.NPN_Solution_Provider_VAR_Text__c = string.isNotBlank(opp.NPN_Solution_Provider_VAR__c) ? opp.NPN_Solution_Provider_VAR__r.name.toLowercase() : '';
                opp.Primary_NPN_OEM_ODM_Disti_Text__c = string.isNotBlank(opp.Primary_NPN_OEM_ODM_Disti__c) ? opp.Primary_NPN_OEM_ODM_Disti__r.name.toLowercase() : '';
                opp.Preliminary_OEM_ODM_Disti_List_Text__c = string.isNotBlank(opp.Preliminary_OEM_ODM_Disti__c) ? opp.Preliminary_OEM_ODM_Disti__c.toLowercase() : '';
            }

            system.debug('***lstOpps > ' + lstOpps);
            system.debug('***Begin: Update the Opportunities');
            Database.SaveResult[] lstSR = Database.update(lstOpps, false);
            system.debug('***End: Update the Opportunities');

			for (Database.SaveResult sr : lstSR) {
				if (sr.isSuccess()) {
				    // Operation was successful, so get the ID of the record that was processed
				     system.debug('Successfully Updated Opportunity: ' + sr.getId());
                     lstProcessedRecordIds.add(sr.getId());
				}else {
                    system.debug('***Opportunuty Update failed> ' + sr.getErrors());  
                    /*
				    // Operation failed, so get all errors
                    system.debug('Begin: Logging Errors in NV_Log__c');            
				    for(Database.Error err : sr.getErrors()) {
                        NV_Log__c nvlog = new NV_Log__c(Component_Name__c   = 'NPNOEMODMDISTI',
                            Functionality_Name__c   = 'Opp_NPNOEMODMDISTI_Event_Tracker_Bat',
                            Method_Name__c          = 'execute',
                            Error_Message__c = '' + err.getMessage(),
                            Error_Description__c    = '' + err.getStatusCode() + '-' + err.getFields(),
                            Log_Type__c         = 'Error: Batch',
                            Record_ID__c        = '' + sr.getId(),     
                            Status__c               = 'Error'
                        );
                        insert nvlog;
				    }
                    system.debug('End: Logging Errors in NV_Log__c');
                    */
				}
			}
        }
        system.debug('---------Exiting Batch Job Opp_NPNOEMODMDISTI_Event_Tracker_Bat execute method-------------------');
    }
    
    public void finish(Database.BatchableContext BC){
        system.debug('---------Entering Batch Job finish method-------------------');
        system.debug('****lstProcessedRecordIds: ' + lstProcessedRecordIds);
        if (lstProcessedRecordIds.size() > 0){
            List<Platform_Event_Tracker_Processor__c> lstEventsUpd =  [SELECT Id
                                                                        FROM Platform_Event_Tracker_Processor__c
                                                                        WHERE Processed__c = false
                                                                            AND EventName__c = :EVENTNAME
                                                                            AND RecordId__c = :lstProcessedRecordIds
                                                                        ];
            for (Platform_Event_Tracker_Processor__c event :lstEventsUpd){
                event.Processed__c = true;
                event.ProcessedDate__c = datetime.now();
            }

            database.update(lstEventsUpd, false);
        }
        system.debug('---------Exiting Batch Job finish method-------------------');
    }
    
}