force-app/main/default/objects/GRID_VCA_Instant_Message__c/GRID_VCA_Instant_Message__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community :</description>
    <label>Portal Instant Message</label>
    <nameField>
        <label>Instant Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Instant Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GRID_VCA_Instant_Message__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_GridPortalSearchPage1.cls
@isTest
private class Test_GridPortalSearchPage1{

    static testMethod void myUnitTest() {
    
        User u = [select Id from User where isActive=true and Profile.Name='System Administrator' limit 1];
        GRID_VCA_Instant_Message__c objGridVCAMsg = new GRID_VCA_Instant_Message__c();
        objGridVCAMsg.Start_Date__c = System.today();  
        objGridVCAMsg.Expiration_Date__c = System.today() + 2;
        objGridVCAMsg.Message__c = 'Hello World';                     
        insert objGridVCAMsg;        
                   
        RecordType rt = [select Id from RecordType where Name='Partner Lead' and SobjectType='Lead'];
        Lead leadObj = new Lead ();
        leadObj.RecordTypeId = rt.Id;
        leadObj.FirstName = 'SearchText';
        leadObj.LastName = 'SearchText';
        leadObj.Company = 'CompanyName';
        leadObj.LeadSource  = 'Email';        
        insert leadObj;
        
        ApexPages.CurrentPage().getParameters().put('searchText','SearchText');
        GridPortalSearchPage obj = new GridPortalSearchPage ();
        obj.ShowSearchResult();


    }
}