force-app/main/default/objects/Country_List__c/Country_List__c.object-meta.xml
<CustomObject>
    <description>CRM : Country/State/Region/Sub-Region/Territory: Contains the Country ISO Code, Name for all countries. Used to drive Region/Sub-Region/Territory information.
Need Public Read Only OWD for internal and external access.</description>
    <label>Country List</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country Lists</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/NPN_Revenue_Commitment_Master__c/NPN_Revenue_Commitment_Master__c.object-meta.xml
<CustomObject>
    <description>NPN : Master data: holds NPN Partner Opportunity Pipeline Commitments for Competency, Level, Country and Threshold($). 

This data will be used to create yearly &quot;NPN Revenue Target&quot; records for each &quot;Partner Attribute&quot; record.</description>
    <label>NPN Revenue Commitment Master</label>
    <nameField>
        <displayFormat>NPNRCM-{0000}</displayFormat>
        <label>NPN Revenue Commitment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPN Revenue Commitment Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/NPN_Revenue_Commitment_Master__c/fields/Competency__c.field-meta.xml
<CustomField>
    <fullName>Competency__c</fullName>
    <label>Competency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Compute</fullName>
            </value>
            <value>
                <fullName>Virtualization</fullName>
            </value>
            <value>
                <fullName>Visualization</fullName>
            </value>
            <value>
                <fullName>Inception Partner</fullName>
            </value>
            <value>
                <fullName>Compute DGX</fullName>
            </value>
            <value>
                <fullName>Embedded Edge</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Commitment_Master__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to Country List custom object</description>
    <label>Country</label>
    <referenceTo>Country_List__c</referenceTo>
    <relationshipLabel>NPN Revenue Commitment Master</relationshipLabel>
    <relationshipName>NPN_Revenue_Commitment_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Commitment_Master__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Commitment_Master__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Solution Provider</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Cloud Service Provider</fullName>
            </value>
            <value>
                <fullName>Federal Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Global Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Solutions Integration Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Commitment_Master__c/fields/Sub_Program__c.field-meta.xml
<CustomField>
    <fullName>Sub_Program__c</fullName>
    <label>Sub Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Data Center Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Commitment_Master__c/fields/Threshold__c.field-meta.xml
<CustomField>
    <fullName>Threshold__c</fullName>
    <label>Threshold($)</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Target_Automation_Settings__c/NPN_Revenue_Target_Automation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used in NPN Revenue Target Automation related trigger and batch job.
If the field &quot;No Match - No Revenue Target&quot; is true, then do not add a revenue target if there is no matching master data lookup in NPN Revenue Commitment Master (for Program Type, Competency, Level, Account Billing Country)</description>
    <label>NPN Revenue Target Automation Settings</label>
</CustomObject>

force-app/main/default/objects/NPN_Revenue_Target_Automation_Settings__c/fields/No_Match_No_Revenue_Target__c.field-meta.xml
<CustomField>
    <fullName>No_Match_No_Revenue_Target__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the field &quot;No Match - No Revenue Target&quot; is true, then do not add a revenue target if there is no matching master data lookup in NPN Revenue Commitment Master (for Program Type, Competency, Level, Account Billing Country)</description>
    <inlineHelpText>If the field &quot;No Match - No Revenue Target&quot; is true, then do not add a revenue target if there is no matching master data lookup in NPN Revenue Commitment Master(for Program Type, Competency, Level, Account Billing Country)</inlineHelpText>
    <label>No Match - No Revenue Target</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Targets__c/NPN_Revenue_Targets__c.object-meta.xml
<CustomObject>
    <description>NPN : NPN Revenue Target: It holds revenue targets for each year for each NPN Partner based on their Program/Competency/Level and their Billing Country. It is child of Partner Attribute object (Partner Attributes are child to Account).</description>
    <label>NPN Revenue Target</label>
    <nameField>
        <displayFormat>RT-{000000}</displayFormat>
        <label>Targets ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPN Revenue Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NPN_Revenue_Targets__c/fields/Minimum_Annual_Sales_Commitment__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Annual_Sales_Commitment__c</fullName>
    <label>Minimum Annual Sales Commitment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Targets__c/fields/Partner_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Partner_Attribute__c</fullName>
    <inlineHelpText>This is the auto-generated Partner Attribute number. Please do not edit this field.</inlineHelpText>
    <label>Partner Attribute</label>
    <referenceTo>Partner_Attribute__c</referenceTo>
    <relationshipLabel>NPN Revenue Targets</relationshipLabel>
    <relationshipName>NPN_Revenue_Targets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Targets__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <inlineHelpText>Select the calendar year.</inlineHelpText>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/Partner_Attribute__c.object-meta.xml
<CustomObject>
    <description>NPN : Additional attributes to an account - program type, competency, level etc.</description>
    <label>Partner Attribute</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Attribute ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/CRM_NPN_Revenue_Target_Common.cls
/*
	Common class and methods for NPN Revenue Target automation. Routines called from Partner Attribute trigger class and CRM_NPN_Revenue_Target_Automation scheduled batch apex
	
	2021.01.31 	Rajat	SDS-2724 Added Sub Program in the logic.
*/
public class CRM_NPN_Revenue_Target_Common {

	//This function fetches the Threshold__c with matching Competency, Country, Level and sets the NPN Revenue Targets 	"Minimum Annual Sales Commitment" and finally inserts the records
	public static void createRevenueTargets(list<PartnerAttributeExt> lstPAExt, string currFY){
		system.debug('***Enters createRevenueTargets() with lstPAExt = ' + lstPAExt);
		
		//Collect the list of countries to search the NPN_Revenue_Commitment_Master__c data
		set<string> setBillCountryInPA = new set<string>();
		for (PartnerAttributeExt paExt :  lstPAExt){
			setBillCountryInPA.add(paExt.AccountBillingCountry);
		}
		
		//fetch the NPN Revenue Commitment Maste data for all the Countries
		list<NPN_Revenue_Commitment_Master__c> lstRevCommitMstr = [	Select Program__c, Sub_Program__c, Competency__c, Level__c, Country__r.Name, Threshold__c 
																	From NPN_Revenue_Commitment_Master__c 
																	Where Country__r.Name = :setBillCountryInPA Limit 50000	];

		//make a key value pair from the master data list. key being the combination of competency-level-country; value being the threshold value
		map<string, decimal> mapRevCommitMstr = new map<string, decimal>();
		for (NPN_Revenue_Commitment_Master__c mstrdata : lstRevCommitMstr){
			// Added Sub_Program__c for SDS-2724
			string key = mstrdata.Program__c + '-' + mstrdata.Sub_Program__c + '-' + mstrdata.Competency__c + '-' + mstrdata.Level__c + '-' + mstrdata.Country__r.Name;
			mapRevCommitMstr.put(key.toLowerCase(), mstrdata.Threshold__c);
		}
		system.debug('***mapRevCommitMstr: ' + mapRevCommitMstr);
		
		//get the "No Match - No Revenue Target" flag from NPN_Revenue_Target_Automation_Settings__c, if it is true then skip the revenue targets with no matching Prog Type, Competency, Level and Billing Country
		boolean bNoMatchNoRevTrgtCS = NPN_Revenue_Target_Automation_Settings__c.getOrgDefaults().No_Match_No_Revenue_Target__c;
		system.debug('***bNoMatchNoRevTrgtCS: ' + bNoMatchNoRevTrgtCS);
		
		//from the PA Extension list, make the key and use it to fetch the threshold from mapRevCommitMstr
		list<NPN_Revenue_Targets__c> lstNewRevenueTargets = new list<NPN_Revenue_Targets__c>();
		for (PartnerAttributeExt PAExt : lstPAExt){
			string key = PAExt.Program + '-' + PAExt.SubProgram + '-' + PAExt.Competency + '-' + PAExt.Level + '-' + PAExt.AccountBillingCountry;
			system.debug('***key searched: ' + key.toLowerCase());
			decimal dThreshold = mapRevCommitMstr.get(key.toLowerCase());
			system.debug('***dThreshold: ' + dThreshold);
			if ( dThreshold != null || (dThreshold == null && bNoMatchNoRevTrgtCS == false) ){
				lstNewRevenueTargets.add(new NPN_Revenue_Targets__c(Partner_Attribute__c = PAExt.Id, Year__c = currFY, Minimum_Annual_Sales_Commitment__c = dThreshold));
			}
		}
		
		system.debug('***New Revenue Target details to be inserted: ' + lstNewRevenueTargets);
		//insert the new revenue targets
		if (!lstNewRevenueTargets.isEmpty()){
			database.insert(lstNewRevenueTargets);
		}
			
	}
	
	//User defined class to hold Partner Attribute fields and its Account billing country
	public class PartnerAttributeExt{
		public Id Id;
		public string Program;
		public string SubProgram;		// Added for SDS-2724
		public string Competency;
		public string Level;
		public string AccountBillingCountry;
		
		public PartnerAttributeExt(Id Id, string Program, string SubProgram, string Competency, string Level, string AccountBillingCountry){
			this.Id = Id;
			this.Program = Program;
			this.SubProgram = SubProgram;
			this.Competency = Competency;
			this.Level = Level;
			this.AccountBillingCountry = AccountBillingCountry;
		}
		
	}
	
	//Get Fiscal Year name From FiscalYearSettings based on a Date literal without time part - Partner Attribute trigger
    public static string getFiscalYear(Date dt){
    	FiscalYearSettings currentFiscalYear = [Select  FY.Name from FiscalYearSettings FY where FY.StartDate <=:dt and FY.EndDate >= : dt];
        return currentFiscalYear.Name;
    }
}