force-app/main/default/objects/Account/fields/Account_Class__c.field-meta.xml
<CustomField>
    <fullName>Account_Class__c</fullName>
    <description>Select the class that applies to this Account.</description>
    <inlineHelpText>Select the class that applies. Select &quot;Named Account&quot; if on Named Account List or a key important revenue account.  Select Lighthouse if major installation/test account.  Select General for all other type accounts.</inlineHelpText>
    <label>Account Class</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>General Account</fullName>
            </value>
            <value>
                <fullName>Named Account</fullName>
            </value>
            <value>
                <fullName>Lighthouse Account</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/EMS_Update_Required__c.field-meta.xml
<CustomField>
    <fullName>EMS_Update_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Licensing 2.0 EMS Updates are monitored using this.</description>
    <label>EMS Update Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>SAP Customer Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Update_Required__c.field-meta.xml
<CustomField>
    <fullName>EMS_Update_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EMS Update Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tesla</fullName>
            </value>
            <value>
                <fullName>vGPU</fullName>
            </value>
            <value>
                <fullName>Quadro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/SAP_Contact_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_Contact_ID__c</fullName>
    <externalId>true</externalId>
    <label>SAP Contact ID</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contract/fields/Nvidia_Status__c.field-meta.xml
<CustomField>
    <fullName>Nvidia_Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Renewed</fullName>
            </value>
            <value>
                <fullName>Upgraded</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
            <value>
                <fullName>Returned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <description>4/25/2018 - @Manideep: This field is all set to delete. Look at this JIRA ticket for the details about deleting this field: https://jirasw.nvidia.com/browse/SDS-361</description>
    <label>Product Line (Legacy)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tesla</fullName>
            </value>
            <value>
                <fullName>QUADRO</fullName>
            </value>
            <value>
                <fullName>GRID</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/IsCPQ__c.field-meta.xml
<CustomField>
    <fullName>IsCPQ__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsCPQ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Type__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Automotive Datacenter</fullName>
            </value>
            <value>
                <fullName>CMP</fullName>
            </value>
            <value>
                <fullName>DC GPU</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
            <value>
                <fullName>Educational Services</fullName>
            </value>
            <value>
                <fullName>Fleet Command</fullName>
            </value>
            <value>
                <fullName>GeForce</fullName>
            </value>
            <value>
                <fullName>Grid</fullName>
            </value>
            <value>
                <fullName>Grid Hardware</fullName>
            </value>
            <value>
                <fullName>HPC SDK</fullName>
            </value>
            <value>
                <fullName>Jetson</fullName>
            </value>
            <value>
                <fullName>NGC-Ready Services</fullName>
            </value>
            <value>
                <fullName>Parabricks</fullName>
            </value>
            <value>
                <fullName>ProViz</fullName>
            </value>
            <value>
                <fullName>RTX</fullName>
            </value>
            <value>
                <fullName>RTX Blade Server</fullName>
            </value>
            <value>
                <fullName>Titan</fullName>
            </value>
            <value>
                <fullName>Value-Added Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Spares</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAP_Order__c/SAP_Order__c.object-meta.xml
<CustomObject>
    <description>CPQ : Captures SAP Orders from SAP/EMS through integration</description>
    <label>SAP Order</label>
    <nameField>
        <label>SAP Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP_Order__c/fields/Error_Log__c.field-meta.xml
<CustomField>
    <fullName>Error_Log__c</fullName>
    <label>Error Log</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <description>ZOR - Standard, ZSO - Sample, ZMRS - MRS Internal, ZRMA - Return</description>
    <inlineHelpText>ZOR - Standard, ZSO - Sample, ZMRS - MRS Internal, ZRMA - Return</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZOR</fullName>
            </value>
            <value>
                <fullName>ZSO</fullName>
            </value>
            <value>
                <fullName>ZMRS</fullName>
            </value>
            <value>
                <fullName>ZRMA</fullName>
            </value>
            <value>
                <fullName>ZDO</fullName>
            </value>
            <value>
                <fullName>ZKB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/SFDC_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SFDC Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>SAP Orders (SFDC Opportunity)</relationshipLabel>
    <relationshipName>SAP_Orders1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/SFDC_Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SFDC Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>SAP Orders</relationshipLabel>
    <relationshipName>SAP_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Processed is for Quote Line/Renewals to avoid record locks, Synced means record has been successfully completed, Error is error</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/CPQSAPOrdersTest.cls
@isTest
private class CPQSAPOrdersTest {
    

    @testSetup static void setup() {
       //Create Accounts w/ Correct Ids based on SAP Acount ID 0009017426, Sold to Account 0000102826, VAR 0000803500, SAP Sales order Number 0000716602, 
        //Create Contacts based on Product End Text 0000031036, Reseller Contact 0000031037
        //Create Opps based on SAP Delivery 0082116056

        
        List<Account> testAccts = new List<Account>();
        testAccts.add(new Account(Name = 'TestAcct1', Industry='Higher Ed/Research', Website='www.test.com', SAP_Customer_Number__c='0009017426',Account_Class__c='General Account', EMS_Update_Required__c =False));
        testAccts.add(new Account(Name = 'TestAcctVAR', Industry='Higher Ed/Research', Website='www.test.com', SAP_Customer_Number__c='0000803500',Account_Class__c='General Account',EMS_Update_Required__c =False));
        testAccts.add(new Account(Name = 'TestAcctSoldTo', Industry='Higher Ed/Research', Website='www.test.com', SAP_Customer_Number__c='0000102826',Account_Class__c='General Account',EMS_Update_Required__c =False));
        insert testAccts;

        List<Contact> testCons=new List<Contact>();
        testCons.add(new Contact(LastName='lname', FirstName='fname', Accountid=testAccts.get(0).id, SAP_Contact_ID__c='0000031036', Email='test@test.com',EMS_Update_Required__c =False));
        testCons.add(new Contact(LastName='lname2', FirstName='fname2', Accountid=testAccts.get(1).id, SAP_Contact_ID__c='0000031037', Email='test2@test.com',EMS_Update_Required__c =False));
        insert testCons;        

        Opportunity opp=new Opportunity(CloseDate=system.today().addDays(30), Name='TestOpp1', StageName='Draft');
        insert opp;

        SBQQ__Quote__c quote=new SBQQ__Quote__c(SBQQ__Opportunity2__c=opp.id, SBQQ__Account__c=testAccts.get(0).id, SBQQ__Type__c='Renewal', SBQQ__Primary__c=true);
        insert quote;

        Contract contract=new Contract(StartDate=system.today(), EndDate=system.today().addYears(1), Nvidia_Status__c='Active', AccountId=testAccts.get(0).id);
        insert contract;
       


    }


    @isTest static void test_invalid_products_errors() {
        // Implement test 
        List<sObject> ls = Test.loadData(SAP_Order__c.sObjectType, 'testOrders1');
        //insert ls;

        SAP_Order__c order=(SAP_Order__c) ls[0];
        system.debug(order);



    }

    
    @isTest static void test_valid() {
        // Implement test 

        //Insert Products
        
        List<Product2> prods = new List<Product2>();
        for(Integer i=1; i<=5; i++){
            Product2 objProduct1 = new Product2();
         objProduct1.Name = 'Product A'+i;
         objProduct1.ProductCode = 'Pro-A'+i;
         objProduct1.isActive = true;
         objProduct1.isCPQ__C = true;
         prods.add(objProduct1);
        }
        insert prods;
        /*List<Product2> prods=new List<Product2>();
        prods.add(new Product2(Name='711-DWS022', ProductCode='711-DWS022', isActive=true, Product_Type__c='Software', Product_Line__c='Grid'));
        prods.add(new Product2(Name='711-VWS021', ProductCode='711-VWS021', isActive=true, Product_Type__c='Software', Product_Line__c='Grid'));
        prods.add(new Product2(Name='712-VWS003', ProductCode='712-VWS003', isActive=true, Product_Type__c='Software', Product_Line__c='Grid'));

        insert prods;*/
        
        List<sObject> ls = Test.loadData(SAP_Order__c.sObjectType, 'testOrders1');
        //insert ls;

        //SAP_Order__c order=(SAP_Order__c) ls[0];
        //system.debug(order);

        //CPQRenewalForecastBatch myBatch=new CPQRenewalForecastBatch();
        //database.executebatch(myBatch,1);
        
    }

    @isTest static void test_valid_renewal() {
        // Implement test 

        //Insert Products

        List<Product2> prods = new List<Product2>();
        for(Integer i=1; i<=5; i++){
            Product2 objProduct1 = new Product2();
         objProduct1.Name = 'Product B'+i;
         objProduct1.ProductCode = 'Pro-B'+i;
         objProduct1.isActive = true;
         objProduct1.isCPQ__C = true;
         prods.add(objProduct1);
        }
        insert prods;
        /*List<Product2> prods=new List<Product2>();
        prods.add(new Product2(Name='711-DWS022', ProductCode='711-DWS022', isActive=true, Product_Type__c='Software', Product_Line__c='Grid'));
        prods.add(new Product2(Name='711-VWS021', ProductCode='711-VWS021', isActive=true, Product_Type__c='Software', Product_Line__c='Grid'));
        prods.add(new Product2(Name='712-VWS003', ProductCode='712-VWS003', isActive=true, Product_Type__c='Software', Product_Line__c='Grid'));

        insert prods;*/
        
        //List<sObject> ls = Test.loadData(SAP_Order__c.sObjectType, 'testOrders1');
        //insert ls;

        //SAP_Order__c order=(SAP_Order__c) ls[0];
        //system.debug(order);
        Account acc=[Select id from Account LIMIT 1];
        Contract con=new Contract();
        con.Accountid=acc.id;
        insert con;

        //CPQRenewalForecastBatch myBatch=new CPQRenewalForecastBatch();
        //database.executebatch(myBatch,1);
        
    }

    @isTest static void test_method_opps() {
        // Implement test code
        List<Product2> prods = new List<Product2>();
        for(Integer i=1; i<=5; i++){
            Product2 objProduct1 = new Product2();
         objProduct1.Name = 'Product C'+i;
         objProduct1.ProductCode = 'Pro-C'+i;
         objProduct1.isActive = true;
         objProduct1.isCPQ__C = true;
         prods.add(objProduct1);
        }
        insert prods;
        /*List<Product2> prods=new List<Product2>();
        prods.add(new Product2(Name='711-DWS022', ProductCode='711-DWS022', isActive=true, Product_Type__c='Software', Product_Line__c='Grid'));
        prods.add(new Product2(Name='711-VWS021', ProductCode='711-VWS021', isActive=true, Product_Type__c='Software', Product_Line__c='Grid'));
        prods.add(new Product2(Name='712-VWS003', ProductCode='712-VWS003', isActive=true, Product_Type__c='Software', Product_Line__c='Grid'));

        insert prods;*/

        SBQQ__Quote__c quote=[select id from SBQQ__Quote__c LIMIT 1];
        Opportunity opp=[Select id from Opportunity LIMIT 1];

         SBQQ__QuoteLine__c ql=new SBQQ__QuoteLine__c(SBQQ__Quote__c=quote.id, SBQQ__Product__c=prods.get(0).id, SBQQ__Quantity__c=1);
         insert ql;

         SAP_Order__c order=new SAP_Order__c();
         order.SFDC_Opportunity__c=opp.id;
         order.SFDC_Quote_Line__c=ql.id;
         order.Order_type__c='ZOR';
         order.Error_Log__c=null;
         order.Status__c='Processed';
         insert order;

         system.debug(order);

         List<Opportunity> oppList=new List<Opportunity>();
         oppList.add(opp);

         CPQ_SAP_Process_Quote_Lines myBatch=new CPQ_SAP_Process_Quote_Lines();
         database.executebatch(myBatch);

         //CPQSAPClosedWonBAtch myBatch=new CPQSAPClosedWonBAtch(oppList);
         //database.executebatch(myBatch);

    }

    
// Dummy CRON expression: midnight on Feb 28.
// Because this is a test, job executes
// immediately after Test.stopTest().


@isTest static void testScheduledJob() {
        Test.startTest();
            Datetime dt = Datetime.now().addMinutes(1);
            String CRON_EXP = '0 '+ dt.minute() + ' * ' + dt.day() + ' ' + dt.month() + ' ? ' + dt.year();
            String jobId = System.schedule('Dummy Test', CRON_EXP, new CPQ_SAP_Schedule_Quote_Line_Sync() );   
        Test.stopTest();
}

@isTest static void testScheduledJob2() {
        Test.startTest();
            Datetime dt = Datetime.now().addMinutes(1);
            String CRON_EXP = '0 '+ dt.minute() + ' * ' + dt.day() + ' ' + dt.month() + ' ? ' + dt.year();
            String jobId = System.schedule('Dummy Test2', CRON_EXP, new CPQRenewalForecastScheduler() );   
        Test.stopTest();
}

@isTest static void testScheduledJob3() {
        Test.startTest();
            Datetime dt = Datetime.now().addMinutes(1);
            String CRON_EXP = '0 '+ dt.minute() + ' * ' + dt.day() + ' ' + dt.month() + ' ? ' + dt.year();
            String jobId = System.schedule('Dummy Test2', CRON_EXP, new CPQ_SAP_Schedule_Legacy_Renewal_Quoted() );   
        Test.stopTest();
}
    
    /**************************************************************************************************
    * Input Parameters: No input parameters
    * DummyTestclass to imporove test ccoveragee 
    * Author : Venkat G
    * Purpose: Test method for NVService class pecLeadRequest method
    ***************************************************************************************************/ 
    static testMethod void dummyCoverageTest(){
     CPQ_SAP_Order_Processor.CoverageMethod();
     //repeat the same for the rest of classes.
  }  

    
}