force-app/main/default/objects/Account/fields/Approved__c.field-meta.xml
<CustomField>
    <fullName>Approved__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Account Approval Status</description>
    <label>Approved</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Inactive Account. Prevents editing the Account except Sys Admin, Data Admin, Sales Profile - Partner Admin</description>
    <inlineHelpText>Inactive/Terminated Account. Do not add/edit Contacts.</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/MDF_Program_Active__c.field-meta.xml
<CustomField>
    <fullName>MDF_Program_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <label>MDF Program Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/NPN_Program_Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>NPN_Program_Signed_Date__c</fullName>
    <inlineHelpText>NPN Program Signed Date</inlineHelpText>
    <label>NPN Agreement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/NPN_Account_Registry.recordType-meta.xml
<RecordType>
    <fullName>NPN_Account_Registry</fullName>
    <active>true</active>
    <label>NPN Account Registry</label>
</RecordType>

force-app/main/default/objects/Partner_Attribute__c/Partner_Attribute__c.object-meta.xml
<CustomObject>
    <description>NPN : Additional attributes to an account - program type, competency, level etc.</description>
    <label>Partner Attribute</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Attribute ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Attribute__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <inlineHelpText>Select account</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Attributes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/ATP_Partner__c.field-meta.xml
<CustomField>
    <fullName>ATP_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ATP Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/ATP_Partner_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ATP_Partner_Start_Date__c</fullName>
    <label>ATP Partner Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/ATP_Partner_Termination_Date__c.field-meta.xml
<CustomField>
    <fullName>ATP_Partner_Termination_Date__c</fullName>
    <label>ATP Partner Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Date_Competency_Terminated__c.field-meta.xml
<CustomField>
    <fullName>Date_Competency_Terminated__c</fullName>
    <label>Date Competency Terminated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Competency__c.field-meta.xml
<CustomField>
    <fullName>Partner_Competency__c</fullName>
    <label>Partner Competency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Partner_Program_Name__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Compute</fullName>
            </value>
            <value>
                <fullName>Compute DGX</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
            <value>
                <fullName>Embedded Edge</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Virtualization</fullName>
            </value>
            <value>
                <fullName>Visualization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Program_Name__c</fullName>
    <label>Partner Program Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Solution Provider</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Tegra Embedded</fullName>
            </value>
            <value>
                <fullName>Services Subcontractor</fullName>
            </value>
            <value>
                <fullName>Cloud Service Provider</fullName>
            </value>
            <value>
                <fullName>Service Delivery Partner</fullName>
            </value>
            <value>
                <fullName>Solution Advisor</fullName>
            </value>
            <value>
                <fullName>Solutions Integration Partner</fullName>
            </value>
            <value>
                <fullName>Industry Focus</fullName>
            </value>
            <value>
                <fullName>Federal Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Global Systems Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Sub_Program__c.field-meta.xml
<CustomField>
    <fullName>Partner_Sub_Program__c</fullName>
    <label>Partner Sub Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Partner_Program_Name__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Data Center Provider</fullName>
            </value>
            <value>
                <fullName>EDU Services</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Support Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Program_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Level__c</fullName>
    <description>Program Level</description>
    <inlineHelpText>Select the program level - Preferred or Elite</inlineHelpText>
    <label>Program Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NPN_PartnerLocatorBatchTest.cls
@isTest(SeeAllData=false)
private class NPN_PartnerLocatorBatchTest {
    @TestSetup
    static void makeData(){

        Id accRT= Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('NPN_Account_Registry').getRecordTypeId();       
         
        Account accSobj = new Account(
            Name = 'AddOnTesting',
            Phone = '922497367',
            NPN_Program_Signed_Date__c = Date.valueOf(system.today()),
            Inactive__c = false,
            Approved__c = false,
            //Account_Email__c = 'pardeshiakash143@gmail.com.invalid',
            MDF_Program_Active__c = false,
            RecordTypeId = accRT,
            BillingCountry ='China'         
            );
        insert accSobj; 
        
        Partner_Attribute__c pAttrb = new Partner_Attribute__c( 
            Account_Name__c  = accSobj.id,
            Partner_Competency__c = COMM_Constants.TEST_PORTAL_COMPETENCY_DL ,
            Partner_Program_Name__c = COMM_Constants.PA_PROGRAM_SP,
            Partner_Sub_Program__c ='',
            Program_Level__c = COMM_Constants.PA_LEVEL_ELITE , 
            ATP_Partner__c = true,            
            ATP_Partner_Termination_Date__c = null,
            Date_Competency_Terminated__c = null,
            ATP_Partner_Start_Date__c = Date.valueOf(system.today())
            );
        insert pAttrb;
        
        Partner_Attribute__c pAttrb2 = new Partner_Attribute__c( 
            Account_Name__c  = accSobj.id,
            Partner_Competency__c = COMM_Constants.TEST_PORTAL_COMPETENCY_DL ,
            Partner_Program_Name__c = COMM_Constants.PA_PROGRAM_SDP,
            Partner_Sub_Program__c ='EDU Services',
            Program_Level__c = COMM_Constants.PA_LEVEL_ELITE , 
            ATP_Partner__c = true,            
            ATP_Partner_Termination_Date__c = null,
            Date_Competency_Terminated__c = null,
            ATP_Partner_Start_Date__c = Date.valueOf(system.today())
            );
        insert pAttrb2;
        
        Partner_Attribute__c pAttrb3 = new Partner_Attribute__c( 
            Account_Name__c  = accSobj.id,
            Partner_Competency__c = COMM_Constants.TEST_PORTAL_COMPETENCY_DL ,
            Partner_Program_Name__c = COMM_Constants.PA_PROGRAM_SDP,
            Partner_Sub_Program__c ='Professional Services',
            Program_Level__c = COMM_Constants.PA_LEVEL_ELITE , 
            ATP_Partner__c = true,            
            ATP_Partner_Termination_Date__c = null,
            Date_Competency_Terminated__c = null,
            ATP_Partner_Start_Date__c = Date.valueOf(system.today())
            );
        insert pAttrb3;
    }

    @isTest
    static void testOne(){        
        Test.StartTest();
            NPN_PartnerLocatorBatch b = new NPN_PartnerLocatorBatch();
            
            Id batchId = Database.executeBatch(b, 100);
            
            system.assert(true, batchId != null);
            
        Test.stopTest();
    }
}