force-app/main/default/objects/Account/fields/Automotive_Startup__c.field-meta.xml
<CustomField>
    <fullName>Automotive_Startup__c</fullName>
    <label>Startup</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/City_of_iCafe__c.field-meta.xml
<CustomField>
    <fullName>City_of_iCafe__c</fullName>
    <label>City of iCafe</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/City_of_Supplier_SI__c.field-meta.xml
<CustomField>
    <fullName>City_of_Supplier_SI__c</fullName>
    <label>City of Supplier/SI</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GEO_Area__c.field-meta.xml
<CustomField>
    <fullName>GEO_Area__c</fullName>
    <description>GEO Areas</description>
    <inlineHelpText>Select a GEO Area that applies to this specific opportunity.</inlineHelpText>
    <label>GEO Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NALA</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>APAC-TASA</fullName>
            </value>
            <value>
                <fullName>APAC-Korea</fullName>
            </value>
            <value>
                <fullName>APAC-China</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>SDS-1469 - Label renamed from Industry to Opportunity Industry</description>
    <inlineHelpText>Select the &quot;Industry&quot; that best applies to this specific opportunity.</inlineHelpText>
    <label>Opportunity Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aerospace</fullName>
            </value>
            <value>
                <fullName>Architecture, Eng and Construction</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>CRISP (Consumer Internet Service Providers)</fullName>
            </value>
            <value>
                <fullName>Drones</fullName>
            </value>
            <value>
                <fullName>Financial Services Industry (FSI)</fullName>
            </value>
            <value>
                <fullName>Gaming</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Higher Ed/Research</fullName>
            </value>
            <value>
                <fullName>IT Services</fullName>
            </value>
            <value>
                <fullName>IVA (Security and Safety)</fullName>
            </value>
            <value>
                <fullName>Logistics &amp; Transportation</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Media/Entertainment</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas/Energy</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>Retail and CPG</fullName>
            </value>
            <value>
                <fullName>Robotics</fullName>
            </value>
            <value>
                <fullName>Strategic Hyperscale</fullName>
            </value>
            <value>
                <fullName>Supercomputing</fullName>
            </value>
            <value>
                <fullName>Telecommunications</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Class__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Class__c</fullName>
    <inlineHelpText>Select the type of Opportunity Class.   &quot;Strategic&quot; means an Opportunity where you spend much of your focus to drive this opportunity to Closed Won. OEM/VAR Enablement means an opportunity that you hand off to the OEM to drive to closure.</inlineHelpText>
    <label>Opportunity Class</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Deep Learning Opportunity</fullName>
            </value>
            <value>
                <fullName>Strategic Opportunity</fullName>
            </value>
            <value>
                <fullName>OEM/VAR Enablement Opportunity</fullName>
            </value>
            <value>
                <fullName>Proof of Concept Opportunity (PoC) / Trial</fullName>
            </value>
            <value>
                <fullName>North America GRID Incentive Program</fullName>
            </value>
            <value>
                <fullName>Other Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <description>4/25/2018 - @Manideep: This field is all set to delete. Look at this JIRA ticket for the details about deleting this field: https://jirasw.nvidia.com/browse/SDS-361</description>
    <label>Product Line (Legacy)</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tesla</fullName>
            </value>
            <value>
                <fullName>QUADRO</fullName>
            </value>
            <value>
                <fullName>GRID</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Province_of_iCafe__c.field-meta.xml
<CustomField>
    <fullName>Province_of_iCafe__c</fullName>
    <label>Province of iCafe</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Anhui</fullName>
            </value>
            <value>
                <fullName>Beijing</fullName>
            </value>
            <value>
                <fullName>Chongqing</fullName>
            </value>
            <value>
                <fullName>Fujian</fullName>
            </value>
            <value>
                <fullName>Gansu</fullName>
            </value>
            <value>
                <fullName>Guangdong</fullName>
            </value>
            <value>
                <fullName>Guangxi</fullName>
            </value>
            <value>
                <fullName>Guizhou</fullName>
            </value>
            <value>
                <fullName>Hainan</fullName>
            </value>
            <value>
                <fullName>Hebei</fullName>
            </value>
            <value>
                <fullName>Heilongjiang</fullName>
            </value>
            <value>
                <fullName>Henan</fullName>
            </value>
            <value>
                <fullName>Hubei</fullName>
            </value>
            <value>
                <fullName>Hunan</fullName>
            </value>
            <value>
                <fullName>Jiangsu</fullName>
            </value>
            <value>
                <fullName>Jiangxi</fullName>
            </value>
            <value>
                <fullName>Jilin</fullName>
            </value>
            <value>
                <fullName>Liaoning</fullName>
            </value>
            <value>
                <fullName>Nei Mongol(inner Mangolia)</fullName>
            </value>
            <value>
                <fullName>Ningxia</fullName>
            </value>
            <value>
                <fullName>Qinghai</fullName>
            </value>
            <value>
                <fullName>Shaanxi</fullName>
            </value>
            <value>
                <fullName>Shandong</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Shanxi</fullName>
            </value>
            <value>
                <fullName>Sichuan</fullName>
            </value>
            <value>
                <fullName>Tianjin</fullName>
            </value>
            <value>
                <fullName>Xinjiang</fullName>
            </value>
            <value>
                <fullName>Xizang(Tibet)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Province_of_Supplier_SI__c.field-meta.xml
<CustomField>
    <fullName>Province_of_Supplier_SI__c</fullName>
    <label>Province of Supplier/SI</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Anhui</fullName>
            </value>
            <value>
                <fullName>Beijing</fullName>
            </value>
            <value>
                <fullName>Chongqing</fullName>
            </value>
            <value>
                <fullName>Fujian</fullName>
            </value>
            <value>
                <fullName>Gansu</fullName>
            </value>
            <value>
                <fullName>Guangdong</fullName>
            </value>
            <value>
                <fullName>Guangxi</fullName>
            </value>
            <value>
                <fullName>Guizhou</fullName>
            </value>
            <value>
                <fullName>Hainan</fullName>
            </value>
            <value>
                <fullName>Hebei</fullName>
            </value>
            <value>
                <fullName>Heilongjiang</fullName>
            </value>
            <value>
                <fullName>Henan</fullName>
            </value>
            <value>
                <fullName>Hubei</fullName>
            </value>
            <value>
                <fullName>Hunan</fullName>
            </value>
            <value>
                <fullName>Jiangsu</fullName>
            </value>
            <value>
                <fullName>Jiangxi</fullName>
            </value>
            <value>
                <fullName>Jilin</fullName>
            </value>
            <value>
                <fullName>Liaoning</fullName>
            </value>
            <value>
                <fullName>Nei Mongol (Inner Mongolia)</fullName>
            </value>
            <value>
                <fullName>Ningxia</fullName>
            </value>
            <value>
                <fullName>Qinghai</fullName>
            </value>
            <value>
                <fullName>Shaanxi</fullName>
            </value>
            <value>
                <fullName>Shandong</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Shanxi</fullName>
            </value>
            <value>
                <fullName>Sichuan</fullName>
            </value>
            <value>
                <fullName>Tianjin</fullName>
            </value>
            <value>
                <fullName>Xinjiang</fullName>
            </value>
            <value>
                <fullName>Xizang(Tibet)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Type__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Automotive Datacenter</fullName>
            </value>
            <value>
                <fullName>CMP</fullName>
            </value>
            <value>
                <fullName>DC GPU</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
            <value>
                <fullName>Educational Services</fullName>
            </value>
            <value>
                <fullName>Fleet Command</fullName>
            </value>
            <value>
                <fullName>GeForce</fullName>
            </value>
            <value>
                <fullName>Grid</fullName>
            </value>
            <value>
                <fullName>Grid Hardware</fullName>
            </value>
            <value>
                <fullName>HPC SDK</fullName>
            </value>
            <value>
                <fullName>Jetson</fullName>
            </value>
            <value>
                <fullName>NGC-Ready Services</fullName>
            </value>
            <value>
                <fullName>Parabricks</fullName>
            </value>
            <value>
                <fullName>ProViz</fullName>
            </value>
            <value>
                <fullName>RTX</fullName>
            </value>
            <value>
                <fullName>RTX Blade Server</fullName>
            </value>
            <value>
                <fullName>Titan</fullName>
            </value>
            <value>
                <fullName>Value-Added Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Sort_Order__c.field-meta.xml
<CustomField>
    <fullName>Product_Sort_Order__c</fullName>
    <description>Used to sort Parts in order in the &quot;Select a Product&quot; pop-up window. Parts to be displayed in descending order (largest &quot;Product Sort&quot; to be at top of list).</description>
    <label>Product Sort Order</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Test_clsOpportunityV2.cls
/*
    Change List: 
    2016.12.07 - PJENA - Price Override
            - Tesla Family is not longer existing, so the existing hard coded Tesla Family is changed to "Tesla HW Family"
            - The test class need to be rewritten not to depend on the existing org data.
            
    * @Manideep: 1/12/2019 - Logic in this code is commented as its not being used and in the process of Opportunity RecordType Cleanup. 

    2021.02.10 - SDS-2928-Delete Opportunity Fields That Were Hidden
*/

@isTest
private class Test_clsOpportunityV2 {

    @isTest (SeeAllData=true)
    static void ValidateTegraEmbeddedPartner_New() {
        //
        string strAccName = 'Test_clsOpportunityV2';
        Account acct = new Account(Name=strAccName);
        acct.Automotive_Startup__c = 'No';
        insert acct;
        
        Opportunity objOpp = new Opportunity();
        objOpp.Name = 'Test Opp TEP';
        objOpp.CloseDate = system.today().addMonths(2);
        objOpp.StageName = 'Prospecting';
        objOpp.Probability = 10;
        objOpp.GEO_Area__c = 'NALA';
        objOpp.Product_Line__c = 'GeForce';
        objOpp.Province_of_Supplier_SI__c = 'Test SI';
        objOpp.City_of_Supplier_SI__c = 'Test City SI';
        objOpp.City_of_iCafe__c = 'Test iCafe';
        objOpp.Province_of_iCafe__c = 'Test Provinance icafe';
        objOpp.AccountId = acct.Id;
        
        Map<String, Id> myRTMap = Utils.GetAllRecordTypeIdsByName();
        test.startTest();
            PageReference pgRef = new PageReference('/apex/vfOpportunityV2');
            pgRef.getParameters().put('accid', null);
            //pgRef.getParameters().put('RecordTypeChange','true');
            pgRef.getParameters().put('param', 'New');
            pgRef.getParameters().put('RecordType', myRTMap.get('Opportunity / Tegra Embedded Partner Opportunity'));
            Test.setCurrentPage(pgRef);
            
            ApexPages.Standardcontroller SC = new ApexPages.Standardcontroller(objOpp);
            clsOpportunityV2 objOutputCont = new clsOpportunityV2(SC);
            objOutputCont.initOne();
            objOutputCont.changeStageName();
            objOutputCont.opp.CloseDate = objOpp.CloseDate;
            objOutputCont.opp.Name = objOpp.Name;
            objOutputCont.opp.StageName = objOpp.StageName;
            objOutputCont.opp.Probability = objOpp.Probability;
            objOutputCont.opp.GEO_Area__c  = objOpp.GEO_Area__c;
            objOutputCont.opp.Product_Line__c = objOpp.Product_Line__c ;
            objOutputCont.opp.Province_of_Supplier_SI__c = objOpp.Province_of_Supplier_SI__c;
            objOutputCont.opp.City_of_Supplier_SI__c = objOpp.City_of_Supplier_SI__c;
            objOutputCont.opp.City_of_iCafe__c = objOpp.City_of_iCafe__c;
            objOutputCont.opp.Province_of_iCafe__c= objOpp.Province_of_iCafe__c;
            objOutputCont.opp.AccountId  = objOpp.AccountId;
            
            objOutputCont.pickStartingQuarter();
            clsOpportunityV2.OLIHelper objOliHelper = new clsOpportunityV2.OLIHelper();
            objOutputCont.lstProductFamilies.add(null);
             
             objOliHelper.strRecordTypeName = objOutputCont.RECORDTYPE_NAME;
            List<PricebookEntry> lstPBE = [select id, Name, UnitPrice
                                                   from   PricebookEntry
                                                   where  IsActive = true
                                                   and    Pricebook2Id = :objOutputCont.opp.Pricebook2Id
                                                   and    Product2.Family = :'Tegra Embedded'
                                                   order by Product2.Product_Sort_Order__c DESC, Name];
            //objOutputCont.mapPBEsByFamily = new map<String, List<PricebookEntry>>();
            for(PricebookEntry eachPBE: lstPBE){
                objOliHelper.pbesForFamily.add(new selectoption(eachPBE.id,eachPBE.Name));
            }
             
            clsOpportunityV2.OLIHelper objOliHelper1 = new clsOpportunityV2.OLIHelper(objOutputCont,'Tegra Embedded',lstPBE[0].id,null);      
            objOliHelper1.family = 'Tegra Embedded';
            objOliHelper1.productName =lstPBE[0].Name;
            objOliHelper1.asp = lstPBE[0].UnitPrice;
            objOliHelper1.totalUnits = 1;
            integer gettotalUnits = objOliHelper1.totalUnits;
            objOliHelper1.totalPrice = objOliHelper1.totalUnits * lstPBE[0].UnitPrice;
            Decimal gettotalPrice = objOliHelper1.totalPrice;
    
            objOutputCont.addNextQuarter();
            objOutputCont.addPreviousQuarter();
            objOutputCont.opp.CloseDate = objOpp.CloseDate.addMonths(3);
            objOutputCont.updateStartingQuarter();
            objOutputCont.addProduct();
            objOutputCont.deleteProductIndex = '0';
            objOutputCont.deleteProduct();
            objOutputCont.getErrorVal();
            objOutputCont.save();
            objOutputCont.Cancel();
          
            //Edit Inserted Opportunity
            pgRef = new PageReference('/apex/vfOpportunityV2');
            PgRef.getParameters().put('id', objOutputCont.Opp.id);
            pgRef.getParameters().put('accid', acct.Id);
            //pgRef.getParameters().put('RecordTypeChange','true');
            pgRef.getParameters().put('param', 'Edit');
            pgRef.getParameters().put('RecordType', myRTMap.get('Opportunity / Tegra Embedded Partner Opportunity'));
            Test.setCurrentPage(pgRef);
            objOutputCont = new clsOpportunityV2(SC);  
              
            //Create Opportunity with account id
            pgRef = new PageReference('/apex/vfOpportunityV2');
            pgRef.getParameters().put('accid', acct.Id);
            pgRef.getParameters().put('param', 'New');
            pgRef.getParameters().put('RecordType', myRTMap.get('Opportunity / Tegra Embedded Partner Opportunity'));
            Test.setCurrentPageReference(pgRef);
            objOutputCont = new clsOpportunityV2(SC);
      test.stoptest();
   }
         
    @isTest (SeeAllData=true)
    static void ValidateTegraEmbedded_New(){
   //
        string strAccName = 'Test_clsOpportunityV2';
        Account acct = new Account(Name=strAccName);
        acct.Automotive_Startup__c = 'No';
        insert acct;
        
        Opportunity objOpp = new Opportunity();
        objOpp.Name = 'Test Opp GeForce';
        objOpp.CloseDate = system.today().addMonths(2);
        objOpp.StageName = 'Prospecting';
        objOpp.Probability = 10;
        //objOpp.GEO_Area__c = 'NALA';
        //objOpp.Product_Line__c = 'GeForce';
        //objOpp.Province_of_Supplier_SI__c = 'Test SI';
        //objOpp.City_of_Supplier_SI__c = 'Test City SI';
        //objOpp.City_of_iCafe__c = 'Test iCafe';
        //objOpp.Province_of_iCafe__c = 'Test Provinance icafe';
        objOpp.AccountId = acct.Id;
        objOpp.Opportunity_Class__c = 'Strategic Opportunity';
        objOpp.Industry__c = 'Aerospace';
        //objOpp.Prefered_Partner__c = 'APPRO';
        //objOpp.Application_Type__c = 'ISVs';
        //objOpp.Critical_Priority_1_Software_Apps__c = 'AMBER';
        //objOpp.At_Risk_Level__c = 'Low';
        objOpp.Blocking_Issues__c = 'Test Issues';
        objOpp.Status_Next_Step__c = 'Test Next step';
        
        Map<String, Id> myRTMap = Utils.GetAllRecordTypeIdsByName();
        PageReference pgRef = new PageReference('/apex/vfOpportunityV2');
        pgRef.getParameters().put('accid', null);
        pgRef.getParameters().put('param', 'New');
        pgRef.getParameters().put('RecordType', myRTMap.get('Opportunity / Tegra Embedded Opportunity'));
        Test.setCurrentPage(pgRef);     
        ApexPages.Standardcontroller SC = new ApexPages.Standardcontroller(objOpp);
        clsOpportunityV2 objOutputCont = new clsOpportunityV2(SC);
        objOutputCont.initOne();
        objOutputCont.changeStageName();
        objOutputCont.opp.CloseDate = objOpp.CloseDate;
        objOutputCont.opp.Name = objOpp.Name;
        objOutputCont.opp.StageName = objOpp.StageName;
        objOutputCont.opp.Probability = objOpp.Probability;
        //objOutputCont.opp.GEO_Area__c  = objOpp.GEO_Area__c;
        //objOutputCont.opp.Product_Line__c = objOpp.Product_Line__c ;
        //objOutputCont.opp.Province_of_Supplier_SI__c = objOpp.Province_of_Supplier_SI__c;
        //objOutputCont.opp.City_of_Supplier_SI__c = objOpp.City_of_Supplier_SI__c;
        //objOutputCont.opp.City_of_iCafe__c = objOpp.City_of_iCafe__c;
        //objOutputCont.opp.Province_of_iCafe__c= objOpp.Province_of_iCafe__c;
        objOutputCont.opp.AccountId  = objOpp.AccountId;
        //objOutputCont.opp.Opportunity_Class__c = 'Strategic Opportunity';
        objOutputCont.opp.Industry__c = 'Aerospace';
        //objOutputCont.opp.Prefered_Partner__c = 'APPRO';
        //objOutputCont.opp.Application_Type__c = 'ISVs';
        //objOutputCont.opp.Critical_Priority_1_Software_Apps__c = 'AMBER';
        objOutputCont.opp.At_Risk_Level__c = 'Low';
        objOutputCont.opp.Blocking_Issues__c = 'Test Issues';
        objOutputCont.opp.Status_Next_Step__c = 'Test Next step';
                
        List<PricebookEntry> lstPBE = [select id, Name, UnitPrice
                                       from   PricebookEntry
                                       where  IsActive = true
                                       and    Pricebook2Id = :objOutputCont.opp.Pricebook2Id
                                       and    Product2.Family = :'Tegra Embedded'
                                       order by Product2.Product_Sort_Order__c DESC, Name]; 
         
       objOutputCont.lstProductFamilies.add(null);
       clsOpportunityV2.OLIHelper objOliHelper1 = new clsOpportunityV2.OLIHelper(objOutputCont,'Tegra Embedded',lstPBE[0].id,null);  
       //objOutputCont.mapPBEsByFamily = new map<String, List<PricebookEntry>>();
       for(PricebookEntry eachPBE: lstPBE){
           objOliHelper1.pbesForFamily.add(new selectoption(eachPBE.id,eachPBE.Name));
       } 
       objOliHelper1.pbeId = lstPBE[0].id;
       ApexPages.currentPage().getParameters().get('selectedPbeId');
       //objOutputCont.addProduct();
       objOutputCont.lstPossibleQuarters.add(new selectoption(Utils.getFiscalQuarterForDate(Date.today()),Utils.swapFiscalDateSections(Utils.getFiscalQuarterForDate(Date.today()))));
       objOutputCont.startingQuarter = Utils.getFiscalQuarterForDate(Date.today());
       objOutputCont.pickStartingQuarter();
       objOliHelper1.family = 'Tegra Embedded';
       objOliHelper1.productName =lstPBE[0].Name;
       clsOpportunityV2.ScheduleEntryHelper objSEH = new clsOpportunityV2.ScheduleEntryHelper(objOutputCont,objOliHelper1,objOutputCont.startingQuarter);
       // objOliHelper1.totalUnits = 1;
       // integer gettotalUnits = objOliHelper1.totalUnits;
       // objOliHelper1.totalPrice = objOliHelper1.totalUnits * lstPBE[0].UnitPrice;
       // Decimal gettotalPrice = objOliHelper1.totalPrice;
       objOutputCont.lstOLIHelpers[0].lstSEHs[0].units = 1;
       objOutputCont.lstOLIHelpers[0].lstSEHs[0].asp = 10;
       objOutputCont.lstOLIHelpers[0].totalUnits = 1;
       objOutputCont.lstOLIHelpers[0].totalPrice = 10;
       objOutputCont.lstOLIHelpers[0].pbeId =lstPBE[0].id;
       objOutputCont.lstOLIHelpers[0].pbe = lstPBE[0];
       objOutputCont.save();
       objOutputCont.addNextQuarter();
       objOutputCont.addPreviousQuarter();
       objOutputCont.opp.CloseDate = objOpp.CloseDate.addMonths(3);
       objOutputCont.updateStartingQuarter();
       objOutputCont.addProduct();
       objOutputCont.deleteProductIndex = '0';
       objOutputCont.deleteProduct();
       //objOutputCont.selectProduct();
       //objOutputCont.closePopup();
       //objOutputCont.showPopup();
       objOutputCont.getErrorVal();
      //objOutputCont.Cancel();
      
      //Edit Inserted Opportunity
      pgRef = new PageReference('/apex/vfOpportunityV2');
      PgRef.getParameters().put('id', objOutputCont.Opp.id);
      pgRef.getParameters().put('accid', acct.Id);
      //pgRef.getParameters().put('RecordTypeChange','true');
      pgRef.getParameters().put('param', 'Edit');
      pgRef.getParameters().put('RecordType', myRTMap.get('Opportunity / Tegra Embedded Opportunity'));
      Test.setCurrentPage(pgRef);
      objOutputCont = new clsOpportunityV2(SC);
        
      //Create Opportunity with account id
      pgRef = new PageReference('/apex/vfOpportunityV2');
      pgRef.getParameters().put('accid', acct.Id);
      pgRef.getParameters().put('param', 'New');
      pgRef.getParameters().put('RecordType', myRTMap.get('Opportunity / Tegra Embedded Opportunity'));
      Test.setCurrentPage(pgRef);
      objOutputCont = new clsOpportunityV2(SC);
    }
        
    @isTest (SeeAllData=true)
    static void ValidateTegraEmbedded_New_NoProductSelected(){
       // 
        string strAccName = 'Test_clsOpportunityV2';
        Account acct = new Account(Name=strAccName);
        acct.Automotive_Startup__c = 'No';
        insert acct;
        
        Opportunity objOpp = new Opportunity();
        objOpp.Name = 'Test Opp GeForce';
        objOpp.CloseDate = system.today().addMonths(2);
        objOpp.StageName = 'Prospecting';
        objOpp.Probability = 10;
        //objOpp.GEO_Area__c = 'NALA';
        //objOpp.Product_Line__c = 'GeForce';
        //objOpp.Province_of_Supplier_SI__c = 'Test SI';
        //objOpp.City_of_Supplier_SI__c = 'Test City SI';
       // objOpp.City_of_iCafe__c = 'Test iCafe';
        //objOpp.Province_of_iCafe__c = 'Test Provinance icafe';
        objOpp.AccountId = acct.Id;
        objOpp.Opportunity_Class__c = 'Strategic Opportunity';
        objOpp.Industry__c = 'Aerospace';
        //objOpp.Prefered_Partner__c = 'APPRO';
        //objOpp.Application_Type__c = 'ISVs';
        //objOpp.Critical_Priority_1_Software_Apps__c = 'AMBER';
        //objOpp.At_Risk_Level__c = 'Low';
        objOpp.Blocking_Issues__c = 'Test Issues';
        objOpp.Status_Next_Step__c = 'Test Next step';
        
        Map<String, Id> myRTMap = Utils.GetAllRecordTypeIdsByName();
        PageReference pgRef = new PageReference('/apex/vfOpportunityV2');
        pgRef.getParameters().put('accid', null);
        pgRef.getParameters().put('param', 'New');
        pgRef.getParameters().put('RecordType', myRTMap.get('Opportunity / Tegra Embedded Opportunity'));
        Test.setCurrentPage(pgRef);     
        ApexPages.Standardcontroller SC = new ApexPages.Standardcontroller(objOpp);
        clsOpportunityV2 objOutputCont = new clsOpportunityV2(SC);
        objOutputCont.initOne();
        objOutputCont.changeStageName();
        objOutputCont.opp.CloseDate = objOpp.CloseDate;
        objOutputCont.opp.Name = objOpp.Name;
        objOutputCont.opp.StageName = objOpp.StageName;
        objOutputCont.opp.Probability = objOpp.Probability;
        //objOutputCont.opp.GEO_Area__c  = objOpp.GEO_Area__c;
        //objOutputCont.opp.Product_Line__c = objOpp.Product_Line__c ;
        //objOutputCont.opp.Province_of_Supplier_SI__c = objOpp.Province_of_Supplier_SI__c;
        //objOutputCont.opp.City_of_Supplier_SI__c = objOpp.City_of_Supplier_SI__c;
        //objOutputCont.opp.City_of_iCafe__c = objOpp.City_of_iCafe__c;
        //objOutputCont.opp.Province_of_iCafe__c= objOpp.Province_of_iCafe__c;
        objOutputCont.opp.AccountId  = objOpp.AccountId;
        //objOutputCont.opp.Opportunity_Class__c = 'Strategic Opportunity';
        objOutputCont.opp.Industry__c = 'Aerospace';
        //objOutputCont.opp.Prefered_Partner__c = 'APPRO';
        //objOutputCont.opp.Application_Type__c = 'ISVs';
        //objOutputCont.opp.Critical_Priority_1_Software_Apps__c = 'AMBER';
        //objOutputCont.opp.At_Risk_Level__c = 'Low';
        objOutputCont.opp.Blocking_Issues__c = 'Test Issues';
        objOutputCont.opp.Status_Next_Step__c = 'Test Next step';
        
        List<PricebookEntry> lstPBE = [select id, Name, UnitPrice
                                       from   PricebookEntry
                                       where  IsActive = true
                                       and    Pricebook2Id = :objOutputCont.opp.Pricebook2Id
                                       and    Product2.Family = :'Tegra Embedded'
                                       order by Product2.Product_Sort_Order__c DESC, Name]; 
         
       objOutputCont.lstProductFamilies.add(null);
       clsOpportunityV2.OLIHelper objOliHelper1 = new clsOpportunityV2.OLIHelper(objOutputCont,'Tegra Embedded',lstPBE[0].id,null);  
       for(PricebookEntry eachPBE: lstPBE){
           objOliHelper1.pbesForFamily.add(new selectoption(eachPBE.id,eachPBE.Name));
       } 
       objOliHelper1.pbeId = lstPBE[0].id;
       ApexPages.currentPage().getParameters().get('selectedPbeId');
       objOutputCont.lstPossibleQuarters.add(new selectoption(Utils.getFiscalQuarterForDate(Date.today()),Utils.swapFiscalDateSections(Utils.getFiscalQuarterForDate(Date.today()))));
       objOutputCont.startingQuarter = Utils.getFiscalQuarterForDate(Date.today());
       objOutputCont.pickStartingQuarter();
       objOliHelper1.family = 'Tegra Embedded';
       objOliHelper1.productName =lstPBE[0].Name;
       clsOpportunityV2.ScheduleEntryHelper objSEH = new clsOpportunityV2.ScheduleEntryHelper(objOutputCont,objOliHelper1,objOutputCont.startingQuarter);
       objOutputCont.lstOLIHelpers[0].pbeId =lstPBE[0].id;
       objOutputCont.lstOLIHelpers[0].pbe = lstPBE[0];
       objOutputCont.save();       
            
    }
    
    @isTest (SeeAllData=true)
    static void ValidateTegraEmbedded_New_changeInOppFields(){
        //
        string strAccName = 'Test_clsOpportunityV2';
        Account acct = new Account(Name=strAccName);
        acct.Automotive_Startup__c = 'No';
        insert acct;
        
        Opportunity objOpp = new Opportunity();
        objOpp.Name = 'Test Opp GeForce';
        objOpp.CloseDate = system.today().addMonths(2);
        objOpp.StageName = 'Prospecting';
        objOpp.Probability = 10;
        //objOpp.GEO_Area__c = 'NALA';
        //objOpp.Product_Line__c = 'GeForce';
        //objOpp.Province_of_Supplier_SI__c = 'Test SI';
        //objOpp.City_of_Supplier_SI__c = 'Test City SI';
        //objOpp.City_of_iCafe__c = 'Test iCafe';
        //objOpp.Province_of_iCafe__c = 'Test Provinance icafe';
        objOpp.AccountId = acct.Id;
        objOpp.Opportunity_Class__c = 'Strategic Opportunity';
        objOpp.Industry__c = 'Aerospace';
        //objOpp.Prefered_Partner__c = 'APPRO';
        //objOpp.Application_Type__c = 'ISVs';
        //objOpp.Critical_Priority_1_Software_Apps__c = 'AMBER';
        //objOpp.At_Risk_Level__c = 'Low';
        objOpp.Blocking_Issues__c = 'Test Issues';
        objOpp.Status_Next_Step__c = 'Test Next step';
        objOpp.Description = 'Test Description';
        objOpp.Competition__c = 'Test';
        objOpp.Reason_for_Close__c = 'Test';
        objOpp.Closed_Lost_Comments__c = 'Test Comments';
        objOpp.Amount = 100;
        //objOpp.Reason_for_Approval__c = 'Test Approved';
        
        Map<String, Id> myRTMap = Utils.GetAllRecordTypeIdsByName();
        PageReference pgRef = new PageReference('/apex/vfOpportunityV2');
        pgRef.getParameters().put('accid', null);
        pgRef.getParameters().put('param', 'New');
        pgRef.getParameters().put('RecordType', myRTMap.get('Opportunity / Tegra Embedded Opportunity'));
        Test.setCurrentPage(pgRef);     
        ApexPages.Standardcontroller SC = new ApexPages.Standardcontroller(objOpp);
        clsOpportunityV2 objOutputCont = new clsOpportunityV2(SC);
        objOutputCont.initOne();
        objOutputCont.changeStageName();
        objOutputCont.opp.CloseDate = objOpp.CloseDate;
        objOutputCont.opp.Name = objOpp.Name;
        objOutputCont.opp.StageName = objOpp.StageName;
        objOutputCont.opp.Probability = objOpp.Probability;
        //objOutputCont.opp.GEO_Area__c  = objOpp.GEO_Area__c;
        //objOutputCont.opp.Product_Line__c = objOpp.Product_Line__c ;
        //objOutputCont.opp.Province_of_Supplier_SI__c = objOpp.Province_of_Supplier_SI__c;
        //objOutputCont.opp.City_of_Supplier_SI__c = objOpp.City_of_Supplier_SI__c;
        //objOutputCont.opp.City_of_iCafe__c = objOpp.City_of_iCafe__c;
        //objOutputCont.opp.Province_of_iCafe__c= objOpp.Province_of_iCafe__c;
        objOutputCont.opp.AccountId  = objOpp.AccountId;
        //objOutputCont.opp.Opportunity_Class__c = 'Strategic Opportunity';
        objOutputCont.opp.Industry__c = 'Aerospace';
        //objOutputCont.opp.Prefered_Partner__c = 'APPRO';
        //objOutputCont.opp.Application_Type__c = 'ISVs';
        //objOutputCont.opp.Critical_Priority_1_Software_Apps__c = 'AMBER';
        //objOutputCont.opp.At_Risk_Level__c = 'Low';
        objOutputCont.opp.Blocking_Issues__c = 'Test Issues';
        objOutputCont.opp.Status_Next_Step__c = 'Test Next step';
        objOutputCont.opp.Description = 'Test Description';
        objOutputCont.opp.Competition__c = 'Test';
        objOutputCont.opp.Reason_for_Close__c = 'Test';
        objOutputCont.opp.Closed_Lost_Comments__c = 'Test Comments';
        objOutputCont.opp.Amount = 100;
        //objOutputCont.opp.Reason_for_Approval__c = 'Test Approved';        
        
        List<PricebookEntry> lstPBE = [select id, Name, UnitPrice
                                       from   PricebookEntry
                                       where  IsActive = true
                                       and    Pricebook2Id = :objOutputCont.opp.Pricebook2Id
                                       and    Product2.Family = :'Tegra Embedded'
                                       order by Product2.Product_Sort_Order__c DESC, Name]; 
         
       objOutputCont.lstProductFamilies.add(null);
       clsOpportunityV2.OLIHelper objOliHelper1 = new clsOpportunityV2.OLIHelper(objOutputCont,'Tegra Embedded',lstPBE[0].id,null);  
       //objOutputCont.mapPBEsByFamily = new map<String, List<PricebookEntry>>();
       for(PricebookEntry eachPBE: lstPBE){
           objOliHelper1.pbesForFamily.add(new selectoption(eachPBE.id,eachPBE.Name));
       } 
       objOliHelper1.pbeId = lstPBE[0].id;
       ApexPages.currentPage().getParameters().get('selectedPbeId');
       //objOutputCont.addProduct();
       objOutputCont.lstPossibleQuarters.add(new selectoption(Utils.getFiscalQuarterForDate(Date.today()),Utils.swapFiscalDateSections(Utils.getFiscalQuarterForDate(Date.today()))));
       objOutputCont.startingQuarter = Utils.getFiscalQuarterForDate(Date.today());
       objOutputCont.pickStartingQuarter();
       objOliHelper1.family = 'Tegra Embedded';
       objOliHelper1.productName =lstPBE[0].Name;
       clsOpportunityV2.ScheduleEntryHelper objSEH = new clsOpportunityV2.ScheduleEntryHelper(objOutputCont,objOliHelper1,objOutputCont.startingQuarter);
       objOutputCont.lstOLIHelpers[0].lstSEHs[0].units = 1;
       objOutputCont.lstOLIHelpers[0].lstSEHs[0].asp = 10;
       objOutputCont.lstOLIHelpers[0].totalUnits = 1;
       objOutputCont.lstOLIHelpers[0].totalPrice = 10;
       objOutputCont.lstOLIHelpers[0].pbeId =lstPBE[0].id;
       objOutputCont.lstOLIHelpers[0].pbe = lstPBE[0];
       objOutputCont.save();
       objOutputCont.addNextQuarter();
       objOutputCont.addPreviousQuarter();
       objOutputCont.opp.CloseDate = objOpp.CloseDate.addMonths(3);
       objOutputCont.updateStartingQuarter();
       objOutputCont.addProduct();
       objOutputCont.deleteProductIndex = '0';
       objOutputCont.deleteProduct();
       objOutputCont.getErrorVal();
            
    }
    
}