force-app/main/default/objects/Account/fields/Automotive_Startup__c.field-meta.xml
<CustomField>
    <fullName>Automotive_Startup__c</fullName>
    <label>Startup</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GEO_Area__c.field-meta.xml
<CustomField>
    <fullName>GEO_Area__c</fullName>
    <description>GEO Areas</description>
    <inlineHelpText>Select a GEO Area that applies to this specific opportunity.</inlineHelpText>
    <label>GEO Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NALA</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>APAC-TASA</fullName>
            </value>
            <value>
                <fullName>APAC-Korea</fullName>
            </value>
            <value>
                <fullName>APAC-China</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>SDS-1469 - Label renamed from Industry to Opportunity Industry</description>
    <inlineHelpText>Select the &quot;Industry&quot; that best applies to this specific opportunity.</inlineHelpText>
    <label>Opportunity Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aerospace</fullName>
            </value>
            <value>
                <fullName>Architecture, Eng and Construction</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>CRISP (Consumer Internet Service Providers)</fullName>
            </value>
            <value>
                <fullName>Drones</fullName>
            </value>
            <value>
                <fullName>Financial Services Industry (FSI)</fullName>
            </value>
            <value>
                <fullName>Gaming</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Higher Ed/Research</fullName>
            </value>
            <value>
                <fullName>IT Services</fullName>
            </value>
            <value>
                <fullName>IVA (Security and Safety)</fullName>
            </value>
            <value>
                <fullName>Logistics &amp; Transportation</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Media/Entertainment</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas/Energy</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>Retail and CPG</fullName>
            </value>
            <value>
                <fullName>Robotics</fullName>
            </value>
            <value>
                <fullName>Strategic Hyperscale</fullName>
            </value>
            <value>
                <fullName>Supercomputing</fullName>
            </value>
            <value>
                <fullName>Telecommunications</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advanced Driver Assistant</fullName>
            </value>
            <value>
                <fullName>Cluster</fullName>
            </value>
            <value>
                <fullName>Cluster and Infotainment</fullName>
            </value>
            <value>
                <fullName>Expand Business</fullName>
            </value>
            <value>
                <fullName>Machine Replacement/upgrade</fullName>
            </value>
            <value>
                <fullName>New iCafe</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Rear Seat Entertainment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Prefered_Partner__c.field-meta.xml
<CustomField>
    <fullName>Prefered_Partner__c</fullName>
    <inlineHelpText>Select the NPN OEM that applies to this specific opportunity.</inlineHelpText>
    <label>NPN OEM/Distributor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acer Incorporated</fullName>
            </value>
            <value>
                <fullName>Adlink</fullName>
            </value>
            <value>
                <fullName>Advantech</fullName>
            </value>
            <value>
                <fullName>Aptec Distribution FFZ LLC</fullName>
            </value>
            <value>
                <fullName>ARROW</fullName>
                <label>Arrow Electronics</label>
            </value>
            <value>
                <fullName>ASUS</fullName>
            </value>
            <value>
                <fullName>BayNex</fullName>
            </value>
            <value>
                <fullName>Bull</fullName>
            </value>
            <value>
                <fullName>Carahsoft Technology Corporation</fullName>
            </value>
            <value>
                <fullName>C-Data Computer Ltd.</fullName>
            </value>
            <value>
                <fullName>CEAC International</fullName>
            </value>
            <value>
                <fullName>Cirrascale</fullName>
            </value>
            <value>
                <fullName>Cisco</fullName>
            </value>
            <value>
                <fullName>Clavis Company (Macnica)</fullName>
            </value>
            <value>
                <fullName>Cray</fullName>
            </value>
            <value>
                <fullName>DBCS</fullName>
                <label>Daebo Communication &amp; Systems</label>
            </value>
            <value>
                <fullName>Daou Data</fullName>
            </value>
            <value>
                <fullName>Dawning (Sugon)</fullName>
            </value>
            <value>
                <fullName>Dell</fullName>
            </value>
            <value>
                <fullName>Foxconn</fullName>
            </value>
            <value>
                <fullName>Fujitsu</fullName>
            </value>
            <value>
                <fullName>Gigabyte</fullName>
            </value>
            <value>
                <fullName>H3C</fullName>
            </value>
            <value>
                <fullName>HPE</fullName>
            </value>
            <value>
                <fullName>HPI</fullName>
            </value>
            <value>
                <fullName>Huawei</fullName>
            </value>
            <value>
                <fullName>IBM</fullName>
            </value>
            <value>
                <fullName>Ingram Micro</fullName>
            </value>
            <value>
                <fullName>Inspur</fullName>
            </value>
            <value>
                <fullName>Inventec</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Quadro_Opportunity_Solution__c.field-meta.xml
<CustomField>
    <fullName>Quadro_Opportunity_Solution__c</fullName>
    <inlineHelpText>Choose the GRID or Quadro product solution that applies to this Opportunity.  If you choose GRID VGX product, there are additional required fields.</inlineHelpText>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>GRID (VGX) Opportunity</fullName>
            </value>
            <value>
                <fullName>Traditional workstation (Quadro)</fullName>
            </value>
            <value>
                <fullName>QUADRO VCA</fullName>
            </value>
            <value>
                <fullName>SVS (Scalable Visualization Solutions)</fullName>
            </value>
            <value>
                <fullName>DVP (Digital Video Pipeline)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Solution_VAR__c.field-meta.xml
<CustomField>
    <fullName>Solution_VAR__c</fullName>
    <inlineHelpText>Enter the Solution Provider/VAR for this Opportunity.  This could be a GRID VAR, TTP or QPP.  If &apos;none&quot;, this please state.</inlineHelpText>
    <label>Solution Provider/VAR</label>
    <length>55</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/What_generated_this_Opportunity__c.field-meta.xml
<CustomField>
    <fullName>What_generated_this_Opportunity__c</fullName>
    <inlineHelpText>Please select the pull-down area which started this opportunity (e.g. qualified lead, call, etc.).  This will help us track how Opportunities get started.</inlineHelpText>
    <label>What started this Opportunity?</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Inbound Call</fullName>
            </value>
            <value>
                <fullName>Qualified Lead</fullName>
            </value>
            <value>
                <fullName>Personal Contact</fullName>
            </value>
            <value>
                <fullName>RFP</fullName>
            </value>
            <value>
                <fullName>Partner called me for support</fullName>
            </value>
            <value>
                <fullName>Ongoing Business</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ASP__c.field-meta.xml
<CustomField>
    <fullName>ASP__c</fullName>
    <label>ASP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_Entry__c/Schedule_Entry__c.object-meta.xml
<CustomObject>
    <description>Opportunity Management (Custom) : A schedule entry represents a single month&apos;s delivery and revenue schedule for an Opportunity</description>
    <label>Schedule Entry</label>
    <nameField>
        <displayFormat>SE-{0}</displayFormat>
        <label>Schedule Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_Entry__c/fields/ASP__c.field-meta.xml
<CustomField>
    <fullName>ASP__c</fullName>
    <description>Used only by Schedule Entries for Tegra Auto and other types of Opportunities that allow the ASP to change from month to month or quarter to quarter</description>
    <label>ASP</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_Entry__c/fields/Display_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Display_Quarter__c</fullName>
    <description>Fiscal Quarter</description>
    <label>Quarter (unsorted)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_Entry__c/fields/OLI_Id__c.field-meta.xml
<CustomField>
    <fullName>OLI_Id__c</fullName>
    <description>Opportunity Line Item Id for the associated Opportunity Line Item/Product</description>
    <label>OLI Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_Entry__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity to which the Product Schedule is associated.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Product Revenue</relationshipLabel>
    <relationshipName>Schedule_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule_Entry__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantity / # of units associated to a particular Schedule Entry</description>
    <label>Units</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/UnitTests_OpportunityReport_Controller.cls
/*
** Class:  UnitTests_OpportunityReport_Controller
** Created by OpFocus on 04/22/2011
** Description: Unit tests for the OpportunityReport_Controller

2016.08.24: Retrofitting of Opportunity creation with Primary Contact and Contact Role to avoid being caught up with validation rule 
 			that blocks opportunity record creation/update when the Probability is 40% (or any percent that could be changed later) without a primary contact and role
			-- Changed the probability to 10% to circumvent the validation rule

* @Manideep: 5/8/2019 - This code is commented as its not being used and in the process of Opportunity RecordType Cleanup.
*/	
@isTest
private class UnitTests_OpportunityReport_Controller { 

/*
    static testMethod void myUnitTest() {
        	
    	string strAccName = 'UnitTests_OpportunityReport_Controller';
        Account acct = new Account(Name=strAccName);
        acct.Automotive_Startup__c = 'No';
        insert acct;
        
        Map<String, Id> allRTMap = Utils.GetAllRecordTypeIdsByName(); 
    	
    	Opportunity oppQuadro = new Opportunity(AccountId = acct.id);
    	//oppQuadro.RecordTypeId = allRTMap.get('Quadro Sales Opportunity');
   		oppQuadro.Name = 'Unit Test Opp';
		oppQuadro.Type = 'Existing Business';
		oppQuadro.CloseDate = Date.today().addDays(14);
		oppQuadro.StageName = 'Prospecting';
		//oppQuadro.Probability = 50;
		oppQuadro.Probability = 10;
		oppQuadro.What_generated_this_Opportunity__c = 'Inbound Call';
		oppQuadro.Fermi_Adoption_Status__c = 'Not yet adopted Fermi';
		//oppQuadro.Industry__c = 'Testing';
		oppQuadro.Industry__c = 'Other';
		oppQuadro.GEO_Area__c = 'NALA';
		oppQuadro.Quadro_Opportunity_Solution__c = 'Medical';
		oppQuadro.Solution_VAR__c = '1';
		oppQuadro.Prefered_Partner__c = 'DELL';
		oppQuadro.Additional_Partners__c = '1';
		insert oppQuadro;
		
		PricebookEntry pbe = 
		  [select id, Name, UnitPrice
		   from   PricebookEntry
		   where  Product2.Family like 'Quadro%'
		   and    IsActive = true
		   limit 1];
		
		OpportunityLineItem oli = new OpportunityLineItem();
		oli.OpportunityId = oppQuadro.id;
		oli.PricebookEntryId = pbe.id;
		oli.ASP__c = pbe.UnitPrice;
		oli.Quantity = 1;
		oli.TotalPrice = pbe.UnitPrice;
		insert oli;
		
		Schedule_Entry__c se = new Schedule_Entry__c();
		se.Opportunity__c = oppQuadro.id;
		se.Display_Quarter__c = 'Q4-2011';
		se.OLI_Id__c = oli.id;
		se.Opportunity_Type__c = 'Quadro Sales Opportunity';
		se.Quantity__c = 1;
		insert se;
		
		
		List<Opportunity> lstOpps = [select id from Opportunity where id = :oppQuadro.id];
    	
        ApexPages.StandardSetController stdController = new ApexPages.StandardSetController(lstOpps);
        OpportunityReport_Controller ctl = new OpportunityReport_Controller(stdController);
        
       	ctl.selectListView();

		// The controller includes code that says, "If we're running in a unit test, then
		// fetch up to 10 Quadro opps.
		ctl.format = 'browser';
		ctl.repeatData = false;
		ctl.runReport();

		System.assert(!ctl.pageError, 'pageError');
		System.assert(!ctl.renderAsCsv, 'renderAsCsv');
		
		ctl.format = 'csv';
		ctl.repeatData = true;
		ctl.runReport();

		System.assert(!ctl.pageError, 'pageError');
		System.assert(ctl.renderAsCsv, 'renderAsCsv');
    }
*/    
}