force-app/main/default/objects/Account/fields/Automotive_Startup__c.field-meta.xml
<CustomField>
    <fullName>Automotive_Startup__c</fullName>
    <label>Startup</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Billing_Region__c.field-meta.xml
<CustomField>
    <fullName>Billing_Region__c</fullName>
    <label>Billing Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>NALA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/New_Customer_Account.recordType-meta.xml
<RecordType>
    <fullName>New_Customer_Account</fullName>
    <active>true</active>
    <label>New Customer Account</label>
</RecordType>

force-app/main/default/objects/Asset/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>Text(Product2.Product_Line__c)</formula>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Serial_Number__c</fullName>
    <externalId>true</externalId>
    <label>Serial Number</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Contact/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tesla</fullName>
            </value>
            <value>
                <fullName>vGPU</fullName>
            </value>
            <value>
                <fullName>Quadro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partner Primary Contact</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Service and Support</fullName>
            </value>
            <value>
                <fullName>RMA</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>MDF</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Renewals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/SalesContact.recordType-meta.xml
<RecordType>
    <fullName>SalesContact</fullName>
    <active>true</active>
    <label>Sales Contact</label>
</RecordType>

force-app/main/default/objects/Device_Event__c/Device_Event__c.object-meta.xml
<CustomObject>
    <label>Device Event</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Device Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Device_Event__c/fields/Alert_Create_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Alert_Create_DateTime__c</fullName>
    <label>Alert Create DateTime</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device_Event__c/fields/Alert_Id__c.field-meta.xml
<CustomField>
    <fullName>Alert_Id__c</fullName>
    <label>Alert Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device_Event__c/fields/Asset__c.field-meta.xml
<CustomField>
    <fullName>Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Asset</label>
    <referenceTo>Asset</referenceTo>
    <relationshipName>Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device_Event__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Device Events</relationshipLabel>
    <relationshipName>Device_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Device_Event__c/fields/Component_Id__c.field-meta.xml
<CustomField>
    <fullName>Component_Id__c</fullName>
    <label>Component Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device_Event__c/fields/Device_Event_ID__c.field-meta.xml
<CustomField>
    <fullName>Device_Event_ID__c</fullName>
    <externalId>true</externalId>
    <label>Device Event ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device_Event__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>2000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Device_Event__c/fields/Message_Details__c.field-meta.xml
<CustomField>
    <fullName>Message_Details__c</fullName>
    <label>Message Details</label>
    <length>10000</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Device_Event__c/fields/System_Name__c.field-meta.xml
<CustomField>
    <fullName>System_Name__c</fullName>
    <label>System Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Device_Event__c/fields/System_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>System_Serial_Number__c</fullName>
    <label>System Serial Number</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Base_SKU__c.field-meta.xml
<CustomField>
    <fullName>Base_SKU__c</fullName>
    <description>Opp Reg &gt; SAP integration (it can be semi-colon separated; if a sfdc product is applicable to 2 SKUs eg., different product like 16gb|32gb but its support has same price; in opp reg scenario instead of 2 products we are having only one product as pricing remains same)</description>
    <label>Base SKU</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Type__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Automotive Datacenter</fullName>
            </value>
            <value>
                <fullName>CMP</fullName>
            </value>
            <value>
                <fullName>DC GPU</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
            <value>
                <fullName>Educational Services</fullName>
            </value>
            <value>
                <fullName>Fleet Command</fullName>
            </value>
            <value>
                <fullName>GeForce</fullName>
            </value>
            <value>
                <fullName>Grid</fullName>
            </value>
            <value>
                <fullName>Grid Hardware</fullName>
            </value>
            <value>
                <fullName>HPC SDK</fullName>
            </value>
            <value>
                <fullName>Jetson</fullName>
            </value>
            <value>
                <fullName>NGC-Ready Services</fullName>
            </value>
            <value>
                <fullName>Parabricks</fullName>
            </value>
            <value>
                <fullName>ProViz</fullName>
            </value>
            <value>
                <fullName>RTX</fullName>
            </value>
            <value>
                <fullName>RTX Blade Server</fullName>
            </value>
            <value>
                <fullName>Titan</fullName>
            </value>
            <value>
                <fullName>Value-Added Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Spares</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_Device_Event_Helper.cls
/*---------------------------------------------------------------------------------------------------------
Test Class Name : Test_Device_Event_Helper. Related to object Device_Event__c
Description : This is a Test class to test Device_Event_Helper class and Device_Event_Trigger trigger

Date        Version    Modified by        Change details
-------     -------    -------------      --------------------------------------------------------
06-19-2019    1.0      Gagan Brar        SDS-1096: NV System Call Home (Phase 1) 
  
-----------------------------------------------------------------------------------------------------------*/

@isTest
public class Test_Device_Event_Helper {
    
    final static String NAME = 'Test_Device_Event_Helper'; 
    final static String AGENT_PROFILE_NAME = 'Service Cloud Generic User';
    final static String NV_AGENT_ROLE = 'NV Agent';
    
    @isTest
    static void test_TriggerHandler() {
        NV_TriggerHandler th = new NV_TriggerHandler();
        th.init();
        th.beforeInsert();
        th.beforeUpdate();
        th.afterInsert();
        th.afterUpdate();
    }
    @isTest
    static void Test_Device_Event_Helper_Trigger() {
   
        //Create an User
        //Profile agentProfile = [select id from profile  where name =: AGENT_PROFILE_NAME];
        //UserRole nvAgentRole = [SELECT Id FROM UserRole where Name =: NV_AGENT_ROLE];
        //User u1 = createUser(agentProfile, NAME+'1', nvAgentRole.Id);
        //insert u1;
        
        Test.startTest();
        //Create an Account
        Account acct = createAccount(NAME);
        insert acct;
        
        //Create an Asset
        Asset ast = createAsset(NAME, acct.Id);
        insert ast;

        //Create a Contact       
        Contact cont = createContact(NAME+'1', acct.Id);
        insert cont;

        //Create Device Event    
        Device_Event__c evnt = createDeviceEvent(NAME, ast.Id);
        insert evnt;
        List<Device_Event__c> testevnt1 = [SELECT Id,Case__c FROM Device_Event__c WHERE id = :evnt.Id AND Case__c != NULL];
        //System.assertEquals(1,testevnt1.size());

        evnt.Severity__c ='Cleared';
        update evnt;
        List<Device_Event__c> testevnt2 = [SELECT Id,Case__c FROM Device_Event__c WHERE id = :evnt.Id AND Case__c != NULL];
        //System.assertEquals(1,testevnt2.size());
        
        //Test Device Event with Same Batch ID
        Device_Event__c evnt2 = createDeviceEvent(NAME, ast.Id);
        evnt2.Batch_Id__c = evnt.Batch_Id__c;
        insert evnt2;
        List<Device_Event__c> testevnt3 = [SELECT Id,Case__c FROM Device_Event__c WHERE id = :evnt2.Id AND Case__c != NULL];
        //System.assertEquals(1,testevnt3.size());

        //Create Device Event    
        Device_Event__c evnt3 = createDeviceEvent(NAME, ast.Id);
        evnt3.Batch_Id__c = NULL;
        evnt3.Contact_Email__c = NULL;
        insert evnt3;
        List<Device_Event__c> testevnt4 = [SELECT Id,Case__c FROM Device_Event__c WHERE id = :evnt.Id AND Case__c != NULL];
        //System.assertEquals(1,testevnt4.size());
        
        Test.stopTest();
    }
    
    static User createUser(Profile p, String NAME, String roleId) {
    
        User testuser = new User(
                                    Alias           = 'testUser', 
                                    Email           = NAME+'@test.com',
                                    Emailencodingkey= 'UTF-8', 
                                    Lastname        = NAME, 
                                    Languagelocalekey= 'en_US',
                                    Localesidkey    = 'en_US',
                                    Profileid       = p.Id, 
                                    Timezonesidkey  = 'America/Los_Angeles', 
                                    Username        = NAME+'@test.com',
                                    UserRoleId      = roleId,
                                    IsActive        = true
                                );
       return testuser;
    }
    
    static Account createAccount(String NAME){
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType='Account' AND DeveloperName='New_Customer_Account'];       
        Account acct = new Account();
        acct.Name               = NAME;
        acct.BillingState       = 'California';
        acct.BillingCountry     = 'United States';
        acct.BillingStreet      = 'Test';
        acct.BillingCity        = 'Santa Clara';
        acct.BillingPostalCode  = '95051';
        acct.Billing_Region__c  = 'NALA';
        acct.RecordTypeId       = rt.Id;
        acct.Automotive_Startup__c = 'No';
        return acct;
    }
    
    static Contact createContact(String NAME, Id acctId){
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType='Contact' AND DeveloperName='SalesContact'];       
        Contact cont        = new Contact();
        cont.FirstName      = 'firstname';
        cont.LastName       = NAME;
        cont.AccountId      = acctId;
        cont.Title          = 'TEST CONTACT';
        cont.Role__c        = 'Technical';
        cont.Email          = NAME+'@mailinator.com';
        cont.Phone          = '4081001001';
        cont.RecordTypeId   = rt.Id;
        return cont;
    }

    static Asset createAsset(String NAME, id acctId){    
        Asset ast = new Asset();
        ast.AccountId = acctId;
        ast.Name = NAME+'12345';
        ast.Name = NAME+'12345';
        ast.Quantity = 1;
        ast.SerialNumber = NAME+'12345';
        ast.Serial_Number__c = NAME+'12345';
        ast.Status = 'Installed';
        
        Product2 prd = new Product2();
        prd.Base_SKU__c = NAME+'-Base-SKU';
        prd.Description = NAME+'-Description';
        prd.Family = 'DGX-1 Volta Product Family';
        prd.IsActive = true;
        prd.Name = NAME+'-product';
        prd.ProductCode = NAME+'-ProductCode';
        prd.Product_Line__c = NAME+'-Product_Line';
        prd.Product_Type__c = 'Hardware';
        insert prd;
        
        ast.Product2Id = prd.id;
        return ast;
    }
    
    static Device_Event__c createDeviceEvent(String NAME, Id assetId) {
        Device_Event__c evnt = new Device_Event__c();
        evnt.System_Name__c             = NAME+'-SYSTEM-NAME';
        evnt.Asset__c                   = assetId;
        evnt.Alert_Id__c                = NAME+'-ALERT-ID';
        evnt.Component_Id__c            = NAME+'-COMPONENT-ID';
        evnt.Alert_Create_DateTime__c   = system.now().format();
        evnt.Contact_Email__c           = NAME+'@mailinator.com';
        evnt.Device_Event_ID__c         = NAME+'-EVENT-ID-'+system.now();
        evnt.System_Serial_Number__c    = NAME+'12345';
        evnt.Severity__c                = 'Critical';
        evnt.Batch_Id__c                = NAME+'-BATCH-ID-'+system.now();
        evnt.Message__c                 = NAME+'-MESSAGE';
        evnt.Message_Details__c         = NAME+'-MESSAGE-DETAILS';
        return evnt;
    }
}