force-app/main/default/objects/Account/fields/Automotive_Startup__c.field-meta.xml
<CustomField>
    <fullName>Automotive_Startup__c</fullName>
    <label>Startup</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Critical_Priority_1_Software_Apps__c.field-meta.xml
<CustomField>
    <fullName>Critical_Priority_1_Software_Apps__c</fullName>
    <inlineHelpText>Select all key software applications included in this opportunity.  If none, select &quot;Not Applicable.”</inlineHelpText>
    <label>ISV Software Apps:</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Acceleware RTM</fullName>
            </value>
            <value>
                <fullName>Adobe Creative Suite</fullName>
            </value>
            <value>
                <fullName>Agilent Technologies ADS</fullName>
            </value>
            <value>
                <fullName>Allegorithmic Substance Designer</fullName>
            </value>
            <value>
                <fullName>Allegorithmic Substance Painter</fullName>
            </value>
            <value>
                <fullName>Altair HyperWorks</fullName>
            </value>
            <value>
                <fullName>AMBER</fullName>
            </value>
            <value>
                <fullName>Amira5</fullName>
            </value>
            <value>
                <fullName>AMR</fullName>
            </value>
            <value>
                <fullName>ANSYS</fullName>
            </value>
            <value>
                <fullName>ANSYS AIM</fullName>
            </value>
            <value>
                <fullName>ANSYS FLUENT</fullName>
            </value>
            <value>
                <fullName>ANSYS HFSS</fullName>
            </value>
            <value>
                <fullName>ANSYS HFSS SBR+</fullName>
            </value>
            <value>
                <fullName>ANSYS Mechanical</fullName>
            </value>
            <value>
                <fullName>ANSYS Nexxim</fullName>
            </value>
            <value>
                <fullName>ANSYS Polyflow</fullName>
            </value>
            <value>
                <fullName>ANSYS Workbench</fullName>
            </value>
            <value>
                <fullName>ASUCA</fullName>
            </value>
            <value>
                <fullName>Autodesk 3DS Max</fullName>
            </value>
            <value>
                <fullName>Autodesk AutoCAD</fullName>
            </value>
            <value>
                <fullName>Autodesk Inventor 2012</fullName>
            </value>
            <value>
                <fullName>Autodesk Maya</fullName>
            </value>
            <value>
                <fullName>Autodesk Revit.</fullName>
            </value>
            <value>
                <fullName>Autodesk vRed</fullName>
            </value>
            <value>
                <fullName>AVBP</fullName>
            </value>
            <value>
                <fullName>BEST</fullName>
            </value>
            <value>
                <fullName>BetaCAE ANSA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/GEO_Area__c.field-meta.xml
<CustomField>
    <fullName>GEO_Area__c</fullName>
    <description>GEO Areas</description>
    <inlineHelpText>Select a GEO Area that applies to this specific opportunity.</inlineHelpText>
    <label>GEO Area</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>NALA</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>India</fullName>
            </value>
            <value>
                <fullName>APAC-TASA</fullName>
            </value>
            <value>
                <fullName>APAC-Korea</fullName>
            </value>
            <value>
                <fullName>APAC-China</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Industry__c.field-meta.xml
<CustomField>
    <fullName>Industry__c</fullName>
    <description>SDS-1469 - Label renamed from Industry to Opportunity Industry</description>
    <inlineHelpText>Select the &quot;Industry&quot; that best applies to this specific opportunity.</inlineHelpText>
    <label>Opportunity Industry</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Aerospace</fullName>
            </value>
            <value>
                <fullName>Architecture, Eng and Construction</fullName>
            </value>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>CRISP (Consumer Internet Service Providers)</fullName>
            </value>
            <value>
                <fullName>Drones</fullName>
            </value>
            <value>
                <fullName>Financial Services Industry (FSI)</fullName>
            </value>
            <value>
                <fullName>Gaming</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Higher Ed/Research</fullName>
            </value>
            <value>
                <fullName>IT Services</fullName>
            </value>
            <value>
                <fullName>IVA (Security and Safety)</fullName>
            </value>
            <value>
                <fullName>Logistics &amp; Transportation</fullName>
            </value>
            <value>
                <fullName>Manufacturing</fullName>
            </value>
            <value>
                <fullName>Media/Entertainment</fullName>
            </value>
            <value>
                <fullName>Oil &amp; Gas/Energy</fullName>
            </value>
            <value>
                <fullName>Public Sector</fullName>
            </value>
            <value>
                <fullName>Retail and CPG</fullName>
            </value>
            <value>
                <fullName>Robotics</fullName>
            </value>
            <value>
                <fullName>Strategic Hyperscale</fullName>
            </value>
            <value>
                <fullName>Supercomputing</fullName>
            </value>
            <value>
                <fullName>Telecommunications</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advanced Driver Assistant</fullName>
            </value>
            <value>
                <fullName>Cluster</fullName>
            </value>
            <value>
                <fullName>Cluster and Infotainment</fullName>
            </value>
            <value>
                <fullName>Expand Business</fullName>
            </value>
            <value>
                <fullName>Machine Replacement/upgrade</fullName>
            </value>
            <value>
                <fullName>New iCafe</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Rear Seat Entertainment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Prefered_Partner__c.field-meta.xml
<CustomField>
    <fullName>Prefered_Partner__c</fullName>
    <inlineHelpText>Select the NPN OEM that applies to this specific opportunity.</inlineHelpText>
    <label>NPN OEM/Distributor</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Acer Incorporated</fullName>
            </value>
            <value>
                <fullName>Adlink</fullName>
            </value>
            <value>
                <fullName>Advantech</fullName>
            </value>
            <value>
                <fullName>Aptec Distribution FFZ LLC</fullName>
            </value>
            <value>
                <fullName>ARROW</fullName>
                <label>Arrow Electronics</label>
            </value>
            <value>
                <fullName>ASUS</fullName>
            </value>
            <value>
                <fullName>BayNex</fullName>
            </value>
            <value>
                <fullName>Bull</fullName>
            </value>
            <value>
                <fullName>Carahsoft Technology Corporation</fullName>
            </value>
            <value>
                <fullName>C-Data Computer Ltd.</fullName>
            </value>
            <value>
                <fullName>CEAC International</fullName>
            </value>
            <value>
                <fullName>Cirrascale</fullName>
            </value>
            <value>
                <fullName>Cisco</fullName>
            </value>
            <value>
                <fullName>Clavis Company (Macnica)</fullName>
            </value>
            <value>
                <fullName>Cray</fullName>
            </value>
            <value>
                <fullName>DBCS</fullName>
                <label>Daebo Communication &amp; Systems</label>
            </value>
            <value>
                <fullName>Daou Data</fullName>
            </value>
            <value>
                <fullName>Dawning (Sugon)</fullName>
            </value>
            <value>
                <fullName>Dell</fullName>
            </value>
            <value>
                <fullName>Foxconn</fullName>
            </value>
            <value>
                <fullName>Fujitsu</fullName>
            </value>
            <value>
                <fullName>Gigabyte</fullName>
            </value>
            <value>
                <fullName>H3C</fullName>
            </value>
            <value>
                <fullName>HPE</fullName>
            </value>
            <value>
                <fullName>HPI</fullName>
            </value>
            <value>
                <fullName>Huawei</fullName>
            </value>
            <value>
                <fullName>IBM</fullName>
            </value>
            <value>
                <fullName>Ingram Micro</fullName>
            </value>
            <value>
                <fullName>Inspur</fullName>
            </value>
            <value>
                <fullName>Inventec</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/ASP__c.field-meta.xml
<CustomField>
    <fullName>ASP__c</fullName>
    <label>ASP</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Product2.Name, captured when the OpportunityLineItem is added for a Notebook Opportunity; this is passed on to any associated Schedule Entries for display in the related list and in reports</description>
    <label>Product Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_Entry__c/Schedule_Entry__c.object-meta.xml
<CustomObject>
    <description>Opportunity Management (Custom) : A schedule entry represents a single month&apos;s delivery and revenue schedule for an Opportunity</description>
    <label>Schedule Entry</label>
    <nameField>
        <displayFormat>SE-{0}</displayFormat>
        <label>Schedule Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_Entry__c/fields/ASP__c.field-meta.xml
<CustomField>
    <fullName>ASP__c</fullName>
    <description>Used only by Schedule Entries for Tegra Auto and other types of Opportunities that allow the ASP to change from month to month or quarter to quarter</description>
    <label>ASP</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_Entry__c/fields/Display_Quarter__c.field-meta.xml
<CustomField>
    <fullName>Display_Quarter__c</fullName>
    <description>Fiscal Quarter</description>
    <label>Quarter (unsorted)</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_Entry__c/fields/OLI_Id__c.field-meta.xml
<CustomField>
    <fullName>OLI_Id__c</fullName>
    <description>Opportunity Line Item Id for the associated Opportunity Line Item/Product</description>
    <label>OLI Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_Entry__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity to which the Product Schedule is associated.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Product Revenue</relationshipLabel>
    <relationshipName>Schedule_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule_Entry__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Product: Name, written to the Schedule Entry via APEX</description>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_Entry__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantity / # of units associated to a particular Schedule Entry</description>
    <label>Units</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Schedule_Entry__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <description>Revenue associated to a particular Schedule Entry</description>
    <label>Revenue</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/UnitTests_TegraAuto_OppAndProducts.cls
/*
** Class:  UnitTests_TegraAuto_OppAndProducts
** Created by OpFocus on 3/24/2011
** Description: Unit tests for the TegraAuto_OppAndProducts_Controller class
* @Manideep - 5/8/2019 - This Test Class used by the Record Types 'Tegra Auto and Emb Opportunity', 'Tegra Auto OEM Opportunity', 'Tegra Auto Tier 1 Opportunity' and 'Tegra Embedded Opportunity'. All these
                          RecordTypes are Retired. So commented out this class as part of Opportunity RecordType Cleanup.
*/  
@isTest
private class UnitTests_TegraAuto_OppAndProducts {

/*
 * @Manideep - Opportunity RecordType Cleanup 
 
    static testMethod void test_BadParams() {

        PageReference pgRef = new PageReference('/apex/TegraAuto_OppAndProducts');
        pgRef.getParameters().put('id', '006bad id');
        Test.setCurrentPage(pgRef);

        TegraAuto_OppAndProducts_Controller ctl = new TegraAuto_OppAndProducts_Controller();
        ctl.InitPage();
        
        System.assert(ctl.pageError, 'Invoked page with no arguments');
        
        ctl.cancel();
    }

    static testMethod void test_WithAccountID() {
        
        string strAccName = 'UnitTests_TegraAuto_OppAndProducts_test_WithAccountID';
        Account acct = new Account(Name = strAccName, Automotive_Startup__c = 'No');
        insert acct;
    
        PageReference pgRef = new PageReference('/apex/TegraAuto_OppAndProducts');
        pgRef.getParameters().put('id', acct.id);
        Test.setCurrentPage(pgRef);

        TegraAuto_OppAndProducts_Controller ctl = new TegraAuto_OppAndProducts_Controller();
        ctl.InitPage();
        
        ctl.cancel();
    }
    static testMethod void test_ThePage() {
        
        string strAccName = 'UnitTests_TegraAuto_OppAndProducts_test_ThePage';
        Account acct = new Account(Name = strAccName, Automotive_Startup__c = 'No');
        insert acct;
        
        Map<String, Id> myRTMap = Utils.GetAllRecordTypeIdsByName();

        PageReference pgRef = new PageReference('/apex/TegraAuto_OppAndProducts');
        pgRef.getParameters().put('AccountId', acct.Id);
        pgRef.getParameters().put('RecordType', myRTMap.get('Opportunity/ Tegra Embedded Opportunity'));
        Test.setCurrentPage(pgRef);

        TegraAuto_OppAndProducts_Controller ctl = new TegraAuto_OppAndProducts_Controller();
        ctl.InitPage();
        
        ctl.startingQuarter = ctl.lstPossibleQuarters[0].getValue();
        ctl.pickStartingQuarter();

        System.assertEquals(null, ctl.opp.id, 'New opp should have no Id');
        System.assertEquals(Utils.getRecordTypeId('Opportunity/ Tegra Embedded Opportunity'), ctl.opp.RecordTypeId, 'Record Type');
        System.assertEquals(1, ctl.lstOLIHelpers.size(), 'Should have 1 empty OLI Helper');
        System.assertEquals(Utils.getFiscalQuarterForDate(Date.today()), ctl.lstQuarters[0], 'Initial FQ');
        
        ctl.opp.Name = 'Unit Test Opp';
        ctl.opp.AccountId = [select id from Account where name = 'Test Account' limit 1].id;
        ctl.opp.Type = 'Existing Business';
        ctl.opp.CloseDate = Date.today().addDays(14);
        ctl.opp.StageName = 'Prospecting';
        ctl.opp.Probability = 50;
        ctl.opp.Industry__c = 'Testing';
        ctl.opp.GEO_Area__c = 'NALA';
        ctl.opp.Prefered_Partner__c = 'DELL';
        ctl.opp.Additional_Partners__c = '1';
        ctl.opp.Critical_Priority_1_Software_Apps__c = 'AMBER';
        ctl.opp.Critical_Priority_2_Software_Apps__c = 'AMR';

        ctl.changeStageName();
        
        // Get a Product Family
        List<SelectOption> lstProductFamiliesSelectOptions = ctl.lstProductFamilies;
        System.assert(0 < lstProductFamiliesSelectOptions.size(), 'Product Family Select Options');
        
        // Populate an OLIHelper
        TegraAuto_OppAndProducts_Controller.OLIHelper olih = ctl.lstOLIHelpers[0];
        olih.family = lstProductFamiliesSelectOptions[1].getValue(); 
        olih.pbeId = olih.pbesForFamily[0].getValue();

        System.assertEquals(olih.pbesForFamily[0].getLabel(), olih.productName, 'productName');
        //System.assert(0 < olih.asp, 'asp');
        //System.assertEquals(0, olih.totalUnits, 'total Units with no SEH units specified');
        //System.assertEquals(0, olih.totalPrice, 'total Price with no SEH units specified');
        //System.assertEquals(1, olih.lstSEHs.size(), 'lstSEHs.size()');
        
        TegraAuto_OppAndProducts_Controller.ScheduleEntryHelper seh = olih.lstSEHs[0];  
        seh.units = 10;
        seh.asp = 1;    

        System.assertEquals(10, olih.totalUnits, 'total Units with 10 SEH units specified');
        //System.assertEquals(10 * olih.asp, olih.totalPrice, 'total Price with 10 SEH units specified');
        //System.assertEquals(10 * olih.asp, seh.revenue, 'SEH revenue with 10 SEH units specified');
        System.assert(seh.isEditable, 'SEH isEditable');
    
        // Add an OLIHelper, and then delete it
        ctl.addProduct();
        System.assertEquals(2, ctl.lstOLIHelpers.size(), 'After adding an OLI Helper');
        ctl.deleteProductIndex = '1';
        ctl.deleteProduct();
        System.assertEquals(1, ctl.lstOLIHelpers.size(), 'After deleting an OLI Helper');

        // Add some quarters
        ctl.addNextQuarter();
        ctl.addPreviousQuarter();
        System.assertEquals(3, ctl.lstQuarters.size(), 'After adding 2 quarters');
        System.assertEquals(3, ctl.lstSEHsByQuarter.size(), 'List of Schedule Entry Helpers after adding 2 quarters');
        System.assertEquals(Utils.getFiscalQuarterForDate(Date.today()),ctl.lstSEHsByQuarter[1].quarter, 'Schedule Entry Helper list after adding 2 quarters');
        
        System.assert(ctl.userIsAdmin, 'User running tests should be an admin');
        
        // Save the Opp
        ctl.save();
                
        Opportunity opp = [SELECT id, Amount FROM Opportunity WHERE id = :ctl.opp.id];
        //System.assertEquals(10 * olih.asp, opp.Amount, 'Saved Opp Amount');
        
        OpportunityLineItem oli = [SELECT Id, Product_Name__c, pricebookEntryId, ASP__c, Quantity, TotalPrice
                                   FROM OpportunityLineItem
                                   WHERE OpportunityId =:opp.id];
                
        System.assertEquals(olih.productName, oli.Product_Name__c, 'oli.Product_Name__c');
        System.assertEquals(olih.pbeId, oli.PricebookEntryId, 'oli.PricebookEntryId');
        //System.assertEquals(olih.asp, oli.ASP__c, 'oli.ASP__c');
        System.assertEquals(olih.totalPrice, oli.TotalPrice);
        
        // When we added 2 more quarters, their Units & ASP were populated from the existing quarter,
        // so we should now have 3 identical quarters
        System.assertEquals(3, [SELECT count() FROM Schedule_Entry__c WHERE Opportunity__c = :opp.id] );
        
        Schedule_Entry__c se = [SELECT Id, Opportunity_Type__c, OLI_Id__c, Product_Name__c, Display_Quarter__c, Quantity__c, Revenue__c
					            FROM Schedule_Entry__c
					            WHERE Opportunity__c = :opp.id 
					            limit 1];
        
        System.assertEquals('Tegra Auto/Emb Sales Opportunity', se.Opportunity_Type__c, 'se.Opportunity_Type__c');
        System.assertEquals(oli.id, se.OLI_Id__c, 'se.OLI_Id__c');
        System.assertEquals(olih.productName, se.Product_Name__c, 'se.Product_Name__c');
        System.assertEquals(seh.quarter, se.Display_Quarter__c, 'se.Display_Quarter__c');
        System.assertEquals(10, se.Quantity__c, 'se.Quantity__c');
        System.assertEquals(oli.TotalPrice / 3, se.Revenue__c, 'se.Revenue__c');

        // Get the controller to load the opp
        PageReference pgRef2 = new PageReference('/apex/TegraAuto_OppAndProducts');
        pgRef2.getParameters().put('AccountId', acct.Id);
        pgRef2.getParameters().put('id', opp.Id);
        Test.setCurrentPage(pgRef2);

        TegraAuto_OppAndProducts_Controller ctl2 = new TegraAuto_OppAndProducts_Controller();
        ctl2.InitPage();
        ctl2.startingQuarter = ctl.lstPossibleQuarters[0].getValue();
        ctl2.pickStartingQuarter();
        
        System.assertEquals(opp.id, ctl2.opp.id, 'Initialized page with existing opp');
        
        ctl2.lstOLIHelpers.clear();
        System.assertEquals(0, ctl2.lstOLIHelpers.size(), 'Cleared lstOLIHelpers');
       
        ctl2.save();
       
        TegraAuto_OppAndProducts_Controller ctl3 = new TegraAuto_OppAndProducts_Controller();
        ctl3.InitPage();
        System.assertEquals(opp.id, ctl3.opp.id, 'Initialized page with existing opp');
                    
        // Test when StageName = 'Closed'
        ctl3.opp.StageName = 'Closed';
        Id newPricebookId =  [select id  from   Pricebook2 where  name = 'Tegra Auto/Emb Price Book' limit 1].id;       
      
        // Create comments on Status change
        String strStatusLastStep = 'Prospecting';
        ctl3.opp.Status_Next_Step__c = 'Qualification';
        
        // Create comments on Description change
        String strPreviousDescription = 'Test Description 1';
        ctl3.opp.Description = 'Test Description 2';
         
        // Create comments on Blocking Issues change
        String strPreviousBlockingIssues = 'Test Blocking Issues 1';
        ctl3.opp.Blocking_Issues__c = 'Test Blocking Issues 2';
                  
        // Create comments on Competetion change
        String strPreviousCompetition = 'Test Competition 1';
        ctl3.opp.competitionold__c = 'Test Competition 2';
         
        // Create comments on Reason for Closed Lost/Other change
        String strPreviousReason= 'Test Reason for Closed 1';
        ctl3.opp.Reason_for_Close__c = 'Test Reason for Closed 2';

        // Create comments on Reason for Closed Lost/Other change
        String strPreviousClosedLostOtherComments = 'Test Reason for Closed Comments 1';
        ctl3.opp.Closed_Lost_Comments__c = 'Test Reason for Closed Comments 2';

        // Create comments on Amount change
        Integer iPreviousAmount = 100;
        ctl3.opp.Amount = 200;
        
        // Create comments on Reason for Approval change
        String strPreviousReasonForApproval = 'Test Reason For Approval 1';
        ctl3.opp.Reason_for_Approval__c = 'Test Reason For Approval 2';

        // Create comments on Conditions of Approval / Feedback change
        String strPreviousConditionsOfApproval = 'Test Conditions of Approval / Feedback 1';
        ctl3.opp.Conditions_of_Approval__c = 'Test Conditions of Approval / Feedback 2';
            
    }
*/    
}