force-app/main/default/objects/Account/fields/Billing_Region__c.field-meta.xml
<CustomField>
    <fullName>Billing_Region__c</fullName>
    <label>Billing Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>NALA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/fields/Inactive__c.field-meta.xml
<CustomField>
    <fullName>Inactive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Inactive Account. Prevents editing the Account except Sys Admin, Data Admin, Sales Profile - Partner Admin</description>
    <inlineHelpText>Inactive/Terminated Account. Do not add/edit Contacts.</inlineHelpText>
    <label>Inactive</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/fields/NPN_Program_Termination_Date__c.field-meta.xml
<CustomField>
    <fullName>NPN_Program_Termination_Date__c</fullName>
    <description>Moved over from Partner Attributes object - 3/20/2016</description>
    <label>NPN Program Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/NPN_Account_Registry.recordType-meta.xml
<RecordType>
    <fullName>NPN_Account_Registry</fullName>
    <active>true</active>
    <label>NPN Account Registry</label>
</RecordType>

force-app/main/default/objects/NPN_Partner_Locator__c/NPN_Partner_Locator__c.object-meta.xml
<CustomObject>
    <description>NPN Partner Locator</description>
    <label>NPN Partner Locator</label>
    <nameField>
        <displayFormat>PL-{00000}</displayFormat>
        <label>NPN Partner Locator Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPN Partner Locators</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NPN_Partner_Locator__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NPN Partner Locators</relationshipLabel>
    <relationshipName>NPN_Partner_Locators</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPN_Partner_Locator__c/fields/Partner_Competency__c.field-meta.xml
<CustomField>
    <fullName>Partner_Competency__c</fullName>
    <label>Partner Competency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compute</fullName>
            </value>
            <value>
                <fullName>Virtualization</fullName>
            </value>
            <value>
                <fullName>Visualization</fullName>
            </value>
            <value>
                <fullName>Compute DGX</fullName>
            </value>
            <value>
                <fullName>Embedded Edge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NPN_Partner_Locator__c/fields/Partner_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Program_Name__c</fullName>
    <label>Partner Program Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solution Provider</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Cloud Service Provider</fullName>
            </value>
            <value>
                <fullName>Solutions Integration Partner</fullName>
            </value>
            <value>
                <fullName>Education Services</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Solution Advisor - Storage Partner</fullName>
            </value>
            <value>
                <fullName>Global Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Solution Advisor - Data Center Provider</fullName>
            </value>
            <value>
                <fullName>Federal Systems Integrator</fullName>
                <isActive>false</isActive>
                <label>Federal Systems Integrator</label>
            </value>
            <value>
                <fullName>Service Delivery Partner</fullName>
                <isActive>false</isActive>
                <label>Service Delivery Partner</label>
            </value>
            <value>
                <fullName>Services Subcontractor</fullName>
                <isActive>false</isActive>
                <label>Services Subcontractor</label>
            </value>
            <value>
                <fullName>Solution Advisor</fullName>
                <isActive>false</isActive>
                <label>Solution Advisor</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NPN_Partner_Locator__c/fields/Partner_Sub_Program__c.field-meta.xml
<CustomField>
    <fullName>Partner_Sub_Program__c</fullName>
    <label>Partner Sub Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>EDU Services</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Support Services</fullName>
            </value>
            <value>
                <fullName>Data Center Provider</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NPN_Partner_Locator__c/fields/Program_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Level__c</fullName>
    <label>Program Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Preferred</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/Partner_Attribute__c.object-meta.xml
<CustomObject>
    <description>NPN : Additional attributes to an account - program type, competency, level etc.</description>
    <label>Partner Attribute</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Attribute ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Attribute__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <inlineHelpText>Select account</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Attributes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/ATP_Partner__c.field-meta.xml
<CustomField>
    <fullName>ATP_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ATP Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/ATP_Partner_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ATP_Partner_Start_Date__c</fullName>
    <label>ATP Partner Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/ATP_Partner_Termination_Date__c.field-meta.xml
<CustomField>
    <fullName>ATP_Partner_Termination_Date__c</fullName>
    <label>ATP Partner Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Date_Competency_Signed__c.field-meta.xml
<CustomField>
    <fullName>Date_Competency_Signed__c</fullName>
    <label>Date Competency Signed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Date_Competency_Terminated__c.field-meta.xml
<CustomField>
    <fullName>Date_Competency_Terminated__c</fullName>
    <label>Date Competency Terminated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Competency__c.field-meta.xml
<CustomField>
    <fullName>Partner_Competency__c</fullName>
    <label>Partner Competency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Partner_Program_Name__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Compute</fullName>
            </value>
            <value>
                <fullName>Compute DGX</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
            <value>
                <fullName>Embedded Edge</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Virtualization</fullName>
            </value>
            <value>
                <fullName>Visualization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Program_Name__c</fullName>
    <label>Partner Program Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Solution Provider</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Tegra Embedded</fullName>
            </value>
            <value>
                <fullName>Services Subcontractor</fullName>
            </value>
            <value>
                <fullName>Cloud Service Provider</fullName>
            </value>
            <value>
                <fullName>Service Delivery Partner</fullName>
            </value>
            <value>
                <fullName>Solution Advisor</fullName>
            </value>
            <value>
                <fullName>Solutions Integration Partner</fullName>
            </value>
            <value>
                <fullName>Industry Focus</fullName>
            </value>
            <value>
                <fullName>Federal Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Global Systems Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Sub_Program__c.field-meta.xml
<CustomField>
    <fullName>Partner_Sub_Program__c</fullName>
    <label>Partner Sub Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Partner_Program_Name__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Data Center Provider</fullName>
            </value>
            <value>
                <fullName>EDU Services</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Support Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Program_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Level__c</fullName>
    <description>Program Level</description>
    <inlineHelpText>Select the program level - Preferred or Elite</inlineHelpText>
    <label>Program Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NPN_PartnerLocatorBatch.cls
global class NPN_PartnerLocatorBatch implements Database.Batchable<sObject> {


    Id accRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('NPN_Account_Registry').getRecordTypeId();
    String query ='';

    public NPN_PartnerLocatorBatch(){


        if(String.isNotBlank(System.Label.NPN_Partner_Locator_Query)) {

            query = System.Label.NPN_Partner_Locator_Query;
        }else{
            query = 'SELECT Id, Name, BillingStreet, BillingCity, BillingState,BillingPostalCode, BillingCountry,Billing_Region__c,Website, '+
                    '(SELECT Id, Account_Name__c,Partner_Competency__c,Partner_Program_Name__c,Partner_Sub_Program__c,Program_Level__c, ATP_Partner__c, ATP_Partner_Start_Date__c, ATP_Partner_Termination_Date__c FROM Account_Attributes__r WHERE Date_Competency_Terminated__c = null AND CALENDAR_YEAR(Date_Competency_Signed__c) != 2099 AND Partner_Competency__c IN (\'Tesla\',\'vGPU\',\'Quadro\',\'DGX\') AND Partner_Program_Name__c IN (\'Solution Provider\',\'OEM\',\'Distributor\',\'Cloud Service Provider\',\'Solutions Integration Partner\',\'Service Delivery Partner\'))'+ // All the active partner attributes
                    'FROM Account WHERE RecordTypeId = :accRecTypeId AND NPN_Program_Termination_Date__c = NULL AND Inactive__c = FALSE';
        }
    }

    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext bc, List<Account> scope){

        List<NPN_Partner_Locator__c> partnerLocatorsForInsert = new List<NPN_Partner_Locator__c>();
        Map<Id, Integer> accountCount = new Map<Id, Integer>();
        for(Account acnt : scope) {

            accountCount.put(acnt.Id, acnt.Account_Attributes__r.size());
            if(!acnt.Account_Attributes__r.isEmpty()) {
                for(Partner_Attribute__c pat : acnt.Account_Attributes__r) {

                    NPN_Partner_Locator__c plObj = new NPN_Partner_Locator__c();

                    plObj.Account_Name__c           = acnt.Id;
                    plObj.Partner_Name__c           = acnt.Name;
                    plObj.Country__c                = String.isNotBlank(acnt.BillingCountry) ? acnt.BillingCountry : '';
                    plObj.State__c                  = String.isNotBlank(acnt.BillingState) ? acnt.BillingState : '';
                    plObj.City__c                   = String.isNotBlank(acnt.BillingCity) ? acnt.BillingCity : '';
                    plObj.Street__c                 = String.isNotBlank(acnt.BillingStreet) ? acnt.BillingStreet : '';
                    plObj.Region__c                 = String.isNotBlank(acnt.Billing_Region__c) ? acnt.Billing_Region__c : '';
                    plObj.Zip_Postal_Code__c        = String.isNotBlank(acnt.BillingPostalCode) ? acnt.BillingPostalCode : '';
                    plObj.Website__c                = String.isNotBlank(acnt.Website) ? acnt.Website : '';
                    plObj.Partner_Competency__c     = String.isNotBlank(pat.Partner_Competency__c) ? pat.Partner_Competency__c : '';
                    plObj.Program_Level__c          = String.isNotBlank(pat.Program_Level__c) ? pat.Program_Level__c : '';
                    plObj.Partner_Sub_Program__c    = String.isNotBlank(pat.Partner_Sub_Program__c) ? pat.Partner_Sub_Program__c : '';

                    if(String.isNotBlank(pat.Partner_Program_Name__c) && COMM_Constants.PA_PROGRAM_SDP.equalsIgnoreCase(pat.Partner_Program_Name__c) && String.isNotBlank(pat.Partner_Sub_Program__c)) {
                        if('EDU Services'.equalsIgnoreCase(pat.Partner_Sub_Program__c)) {
                            plObj.Partner_Program_Name__c   = 'Education Services';
                        }else if ('Professional Services'.equalsIgnoreCase(pat.Partner_Sub_Program__c)) {
                            plObj.Partner_Program_Name__c   ='Professional Services';
                        }
                    }else {
                        plObj.Partner_Program_Name__c   = String.isNotBlank(pat.Partner_Program_Name__c) ? pat.Partner_Program_Name__c : '';
                    }


                    if(String.isNotBlank(pat.Partner_Competency__c) && pat.Partner_Competency__c.contains('DGX') && pat.ATP_Partner__c && pat.ATP_Partner_Start_Date__c != null && pat.ATP_Partner_Termination_Date__c == null ) {
                        plObj.ATP_Partner__c = true;
                    }
                    partnerLocatorsForInsert.add(plObj);
                }
            }
        }

        System.debug('--> accountCount '+ accountCount);
        System.debug('--> partnerLocatorsForInsert.size() '+ partnerLocatorsForInsert.size());
        if(!partnerLocatorsForInsert.isEmpty()) {
            Database.SaveResult[] sr = Database.Insert(partnerLocatorsForInsert, false);
            system.debug('--> save result :'+ sr);
        }



    }

    global void finish(Database.BatchableContext bc){

    }
}