force-app/main/default/objects/Account/fields/Billing_Region__c.field-meta.xml
<CustomField>
    <fullName>Billing_Region__c</fullName>
    <label>Billing Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>NALA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/NPN_Account_Registry.recordType-meta.xml
<RecordType>
    <fullName>NPN_Account_Registry</fullName>
    <active>true</active>
    <label>NPN Account Registry</label>
</RecordType>

force-app/main/default/objects/Account/recordTypes/PartnerAccount.recordType-meta.xml
<RecordType>
    <fullName>PartnerAccount</fullName>
    <active>true</active>
    <label>Partner Account</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner Contact</label>
</RecordType>

force-app/main/default/objects/NPN_Contract_Packet_Config__c/NPN_Contract_Packet_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NPN Contracts Packet Config</label>
</CustomObject>

force-app/main/default/objects/NPN_Contract_Packet_Config__c/fields/VP_Email__c.field-meta.xml
<CustomField>
    <fullName>VP_Email__c</fullName>
    <label>VP Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/NPN_Contract_Packet_Config__c/fields/VP_First_Name__c.field-meta.xml
<CustomField>
    <fullName>VP_First_Name__c</fullName>
    <label>VP First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Contract_Packet_Config__c/fields/VP_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>VP_Last_Name__c</fullName>
    <label>VP Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_PartnerAttributes_Modifiaction__c/NPN_PartnerAttributes_Modifiaction__c.object-meta.xml
<CustomObject>
    <description>Add On Competency, Promotion, Demotion Using DocuSign</description>
    <label>NPN_PartnerAttributes_Modification</label>
    <nameField>
        <label>NPN_PartnerAttributes_DocuSignSync Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPN_PartnerAttributes_Modifications</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NPN_PartnerAttributes_Modifiaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>NPN_PartnerAttributes_Modifiactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPN_PartnerAttributes_Modifiaction__c/fields/Competency__c.field-meta.xml
<CustomField>
    <fullName>Competency__c</fullName>
    <label>Competency</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Compute</fullName>
            </value>
            <value>
                <fullName>Virtualization</fullName>
            </value>
            <value>
                <fullName>Visualization</fullName>
            </value>
            <value>
                <fullName>Compute DGX</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Embedded Edge</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NPN_PartnerAttributes_Modifiaction__c/fields/Competency_Level__c.field-meta.xml
<CustomField>
    <fullName>Competency_Level__c</fullName>
    <label>Competency_Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NPN_PartnerAttributes_Modifiaction__c/fields/Competency_Termination_30_days_Complete__c.field-meta.xml
<CustomField>
    <fullName>Competency_Termination_30_days_Complete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Competency Termination 30 days Complete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NPN_PartnerAttributes_Modifiaction__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Contact</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Contact.AccountId</field>
            <operation>equals</operation>
            <valueField>$Source.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipName>NPN_PartnerAttributes_Modifiactions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPN_PartnerAttributes_Modifiaction__c/fields/CSP_Yes_No__c.field-meta.xml
<CustomField>
    <fullName>CSP_Yes_No__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Does the CSP sell to other CSPs</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NPN_PartnerAttributes_Modifiaction__c/fields/DocuSign_Envelope_ID__c.field-meta.xml
<CustomField>
    <fullName>DocuSign_Envelope_ID__c</fullName>
    <label>DocuSign Envelope ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_PartnerAttributes_Modifiaction__c/fields/PartnerAttributes_Modification__c.field-meta.xml
<CustomField>
    <fullName>PartnerAttributes_Modification__c</fullName>
    <label>PartnerAttributes_Modification</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Add On Contracts Packet</fullName>
            </value>
            <value>
                <fullName>Promotion</fullName>
            </value>
            <value>
                <fullName>Demotion</fullName>
            </value>
            <value>
                <fullName>Termination</fullName>
            </value>
            <value>
                <fullName>Competency Termination</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NPN_PartnerAttributes_Modifiaction__c/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <label>Program Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solution Provider</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Cloud Service Provider</fullName>
            </value>
            <value>
                <fullName>Solutions Integration Partner</fullName>
            </value>
            <value>
                <fullName>Solution Advisor</fullName>
            </value>
            <value>
                <fullName>Service Delivery Partner</fullName>
            </value>
            <value>
                <fullName>Industry Focus</fullName>
            </value>
            <value>
                <fullName>Federal Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Global Systems Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NPN_PartnerAttributes_Modifiaction__c/fields/Sync__c.field-meta.xml
<CustomField>
    <fullName>Sync__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sync</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NPN_PartnerAttributes_Modifiaction__c/fields/Termination_Initiated__c.field-meta.xml
<CustomField>
    <fullName>Termination_Initiated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Termination Initiated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/Partner_Attribute__c.object-meta.xml
<CustomObject>
    <description>NPN : Additional attributes to an account - program type, competency, level etc.</description>
    <label>Partner Attribute</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Attribute ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Attribute__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <inlineHelpText>Select account</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Attributes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/ATP_Partner__c.field-meta.xml
<CustomField>
    <fullName>ATP_Partner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>ATP Partner</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/ATP_Partner_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ATP_Partner_Start_Date__c</fullName>
    <label>ATP Partner Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/ATP_Partner_Termination_Date__c.field-meta.xml
<CustomField>
    <fullName>ATP_Partner_Termination_Date__c</fullName>
    <label>ATP Partner Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Date_Competency_Signed__c.field-meta.xml
<CustomField>
    <fullName>Date_Competency_Signed__c</fullName>
    <label>Date Competency Signed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Date_Competency_Terminated__c.field-meta.xml
<CustomField>
    <fullName>Date_Competency_Terminated__c</fullName>
    <label>Date Competency Terminated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Competency__c.field-meta.xml
<CustomField>
    <fullName>Partner_Competency__c</fullName>
    <label>Partner Competency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Partner_Program_Name__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Compute</fullName>
            </value>
            <value>
                <fullName>Compute DGX</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
            <value>
                <fullName>Embedded Edge</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Virtualization</fullName>
            </value>
            <value>
                <fullName>Visualization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Program_Name__c</fullName>
    <label>Partner Program Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Solution Provider</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Tegra Embedded</fullName>
            </value>
            <value>
                <fullName>Services Subcontractor</fullName>
            </value>
            <value>
                <fullName>Cloud Service Provider</fullName>
            </value>
            <value>
                <fullName>Service Delivery Partner</fullName>
            </value>
            <value>
                <fullName>Solution Advisor</fullName>
            </value>
            <value>
                <fullName>Solutions Integration Partner</fullName>
            </value>
            <value>
                <fullName>Industry Focus</fullName>
            </value>
            <value>
                <fullName>Federal Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Global Systems Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Sub_Program__c.field-meta.xml
<CustomField>
    <fullName>Partner_Sub_Program__c</fullName>
    <label>Partner Sub Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Partner_Program_Name__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Data Center Provider</fullName>
            </value>
            <value>
                <fullName>EDU Services</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Support Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Program_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Level__c</fullName>
    <description>Program Level</description>
    <inlineHelpText>Select the program level - Preferred or Elite</inlineHelpText>
    <label>Program Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NV_Test_AddOnPromoDemoTermController.cls
@isTest(seeAllData=false)
private class NV_Test_AddOnPromoDemoTermController {

    static void makeData(){
        map<String, Id> mapProfNameId;
        Account partnerAcc;
        Contact partnerContact1;

        Id accRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('NPN_Account_Registry').getRecordTypeId();
        Id contactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Partner').getRecordTypeId();

        list<string> lstProfNames = new list<string> {COMM_Constants.PROF_PP_VGX_GENERIC, COMM_Constants.PROF_INT_PARTNER_ADMIN };
        mapProfNameId = Test_COMM_Factory.getProfsByName(lstProfNames);

        //Create a NPN Account with Billing Country, Region
        partnerAcc = Test_COMM_Factory.createNPNAccountWithUSBillingAddressRegion('DRNPNAccountRegistry1', accRecTypeId);

        //we can not set IsParnter or IsCustomerPortal at the time of insert, so needs to do this on update
        partnerAcc.IsPartner = true;
        partnerAcc.Billing_Region__c = 'NALA';
        update partnerAcc;

        //Create a Partner Contact
        partnerContact1 = Test_COMM_Factory.createContactWithMailingAddress('LDRJena11', 'FContact11', partnerAcc.Id, 'drcontactjena11@nv.com', contactRecTypeId, COMM_Constants.ADDRESS_STREET, COMM_Constants.ADDRESS_CITY, COMM_Constants.ADDRESS_STATE, COMM_Constants.ADDRESS_COUNTRY, COMM_Constants.ADDRESS_ZIP );

        list<Partner_Attribute__c> partnerAttrbList = new List<Partner_Attribute__c>();
        Partner_Attribute__c pAttrb = new Partner_Attribute__c(
            Account_Name__c  = partnerAcc.id,
            Partner_Competency__c = COMM_Constants.TEST_PORTAL_COMPETENCY_DL,
            Partner_Program_Name__c = COMM_Constants.PA_PROGRAM_SP,
            Partner_Sub_Program__c ='',
            Program_Level__c = COMM_Constants.PA_LEVEL_PREF,
            ATP_Partner__c = true,
            ATP_Partner_Termination_Date__c = null,
            Date_Competency_Terminated__c = null,
            Date_Competency_Signed__c = Date.valueOf (system.today()),
            ATP_Partner_Start_Date__c = Date.valueOf(system.today())
            );
        partnerAttrbList.add(pAttrb);

        Partner_Attribute__c pAttrb2 = new Partner_Attribute__c(
            Account_Name__c  = partnerAcc.id,
            Partner_Competency__c = COMM_Constants.TEST_PORTAL_COMPETENCY_PV,
            Partner_Program_Name__c = COMM_Constants.PA_PROGRAM_SP,
            Program_Level__c = COMM_Constants.PA_LEVEL_PREF,
            ATP_Partner_Termination_Date__c = null,
            Date_Competency_Terminated__c = null,
            Date_Competency_Signed__c = Date.valueOf (system.today()),
            ATP_Partner_Start_Date__c = Date.valueOf(system.today())
            );
        partnerAttrbList.add(pAttrb2);

        Partner_Attribute__c pAttrb3 = new Partner_Attribute__c(
            Account_Name__c  = partnerAcc.id,
            Partner_Competency__c = COMM_Constants.TEST_PORTAL_COMPETENCY_GV,
            Partner_Program_Name__c = COMM_Constants.PA_PROGRAM_SP,
            Program_Level__c = COMM_Constants.PA_LEVEL_PREF,
            ATP_Partner_Termination_Date__c = null,
            Date_Competency_Terminated__c = null,
            Date_Competency_Signed__c = Date.valueOf (system.today()),
            ATP_Partner_Start_Date__c = Date.valueOf(system.today())
            );
        partnerAttrbList.add(pAttrb3);

        insert partnerAttrbList;

        list<NPN_Contract_Packet_Config__c> listNPN_Contract_Packet_Config= new list<NPN_Contract_Packet_Config__c> ();

        NPN_Contract_Packet_Config__c NP1= new NPN_Contract_Packet_Config__c ();
        NP1.name= 'test';
        NP1.setupownerid= UserInfo.getOrganizationId();
        NP1.email_body__c= 'Attached you will find the NVIDIA Partner Network (NPN) Contacts Packet for review, completion and signature.';
        NP1.email_subject__c= 'NVIDIA Partner Network Contracts Packet for Review and Signature';
        NP1.vp_email__c= 'apardeshi@nvidia.com.invalid';
        NP1.vp_first_name__c= 'Anthony';
        NP1.vp_last_name__c= 'Medeiros';

        listNPN_Contract_Packet_Config.add(NP1);
        insert listNPN_Contract_Packet_Config;
    }

    @isTest static void docuSignTest1(){

        genericMock fakeResp = new genericMock(200,'Complete', '<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/><soapenv:Body><ns:SyncServiceResponse xmlns:ns="http://nvidiasapemsconnector.nvidiaaxis2service.nvidia.smps.gmlto.com"><ns:return xmlns:ax21="http://dto.nvidiaaxis2service.nvidia.smps.gmlto.com/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ax21:SyncResponse"><ax21:errorMessage></ax21:errorMessage><ax21:statusCode>success</ax21:statusCode><ax21:syncType>PartnerUser</ax21:syncType></ns:return></ns:SyncServiceResponse></soapenv:Body></soapenv:Envelope>',null);
        


        test.startTest();
        System.Test.setMock(HttpCalloutMock.class, fakeResp);
        
        makeData();
        
        Account partnerAccount = [SELECT Id, Name FROM Account LIMIT 1];

        Contact partnerContact = [SELECT Id FROM Contact WHERE AccountId = :partnerAccount.Id LIMIT 1];

        PageReference pageRef = Page.NV_AddOnPromoDemoTermination;
        Test.setCurrentPageReference(pageRef);
        ApexPages.currentPage().getParameters().put('id',partnerAccount.Id);
        NV_AddOnPromoDemoTerminationController controllerExt = new NV_AddOnPromoDemoTerminationController( new ApexPages.StandardController(partnerAccount));

        controllerExt.strDocumentIds = '4064457BCA2EDA5E457BCA2E4064B1B5F9E6B8690A9C, F9E6B8690A9C4064457BCA2EDA5E457BCA2E4064';
        controllerExt.objPAM = new NPN_PartnerAttributes_Modifiaction__c(
            PartnerAttributes_Modification__c = 'Add On Contracts Packet',
            Competency__c = COMM_Constants.TEST_PORTAL_COMPETENCY_DL+';'+COMM_Constants.TEST_PORTAL_COMPETENCY_PV+';'+COMM_Constants.TEST_PORTAL_COMPETENCY_GV+';',
            Competency_Level__c = 'Preferred',
            Sync__c = false,
            CSP_Yes_No__c = false,
            Account__c = partnerAccount.Id,
            Program_Type__c = COMM_Constants.PA_PROGRAM_SP,
            Termination_Initiated__c = false,
            Competency_Termination_30_days_Complete__c = false,
            Contact__c = partnerContact.Id,
            DocuSign_Envelope_ID__c = '457BCA2E-DA5E-4064-B1B5-F9E6B8690A9C'

            );
        controllerExt.save();

        test.stopTest();

    }
    
    @isTest static void docuSignTest2(){

        genericMock fakeResp = new genericMock(200,'Complete', '<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/><soapenv:Body><ns:SyncServiceResponse xmlns:ns="http://nvidiasapemsconnector.nvidiaaxis2service.nvidia.smps.gmlto.com"><ns:return xmlns:ax21="http://dto.nvidiaaxis2service.nvidia.smps.gmlto.com/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ax21:SyncResponse"><ax21:errorMessage></ax21:errorMessage><ax21:statusCode>success</ax21:statusCode><ax21:syncType>PartnerUser</ax21:syncType></ns:return></ns:SyncServiceResponse></soapenv:Body></soapenv:Envelope>',null);
        


        test.startTest();
        System.Test.setMock(HttpCalloutMock.class, fakeResp);
        
        makeData();
        
        Account partnerAccount = [SELECT Id, Name FROM Account LIMIT 1];

        Contact partnerContact = [SELECT Id FROM Contact WHERE AccountId = :partnerAccount.Id LIMIT 1];

        PageReference pageRef = Page.NV_AddOnPromoDemoTermination;
        Test.setCurrentPageReference(pageRef);
        ApexPages.currentPage().getParameters().put('id',partnerAccount.Id);
        NV_AddOnPromoDemoTerminationController controllerExt = new NV_AddOnPromoDemoTerminationController( new ApexPages.StandardController(partnerAccount));

        controllerExt.strDocumentIds = '4064457BCA2EDA5E457BCA2E4064B1B5F9E6B8690A9C, F9E6B8690A9C4064457BCA2EDA5E457BCA2E4064';
        controllerExt.objPAM = new NPN_PartnerAttributes_Modifiaction__c(
            PartnerAttributes_Modification__c = 'Promotion',
            Competency__c = COMM_Constants.TEST_PORTAL_COMPETENCY_DL+';'+COMM_Constants.TEST_PORTAL_COMPETENCY_PV+';'+COMM_Constants.TEST_PORTAL_COMPETENCY_GV+';',
            Competency_Level__c = 'Preferred',
            Sync__c = false,
            CSP_Yes_No__c = false,
            Account__c = partnerAccount.Id,
            Program_Type__c = COMM_Constants.PA_PROGRAM_SP,
            Termination_Initiated__c = false,
            Competency_Termination_30_days_Complete__c = false,
            Contact__c = partnerContact.Id,
            DocuSign_Envelope_ID__c = '457BCA2E-DA5E-4064-B1B5-F9E6B8690A9C'

            );
        controllerExt.save();

        test.stopTest();

    }
    
    @isTest static void docuSignTest3(){

        genericMock fakeResp = new genericMock(200,'Complete', '<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/><soapenv:Body><ns:SyncServiceResponse xmlns:ns="http://nvidiasapemsconnector.nvidiaaxis2service.nvidia.smps.gmlto.com"><ns:return xmlns:ax21="http://dto.nvidiaaxis2service.nvidia.smps.gmlto.com/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ax21:SyncResponse"><ax21:errorMessage></ax21:errorMessage><ax21:statusCode>success</ax21:statusCode><ax21:syncType>PartnerUser</ax21:syncType></ns:return></ns:SyncServiceResponse></soapenv:Body></soapenv:Envelope>',null);
        


        test.startTest();
        System.Test.setMock(HttpCalloutMock.class, fakeResp);
        
        makeData();
        
        Account partnerAccount = [SELECT Id, Name FROM Account LIMIT 1];

        Contact partnerContact = [SELECT Id FROM Contact WHERE AccountId = :partnerAccount.Id LIMIT 1];

        PageReference pageRef = Page.NV_AddOnPromoDemoTermination;
        Test.setCurrentPageReference(pageRef);
        ApexPages.currentPage().getParameters().put('id',partnerAccount.Id);
        NV_AddOnPromoDemoTerminationController controllerExt = new NV_AddOnPromoDemoTerminationController( new ApexPages.StandardController(partnerAccount));

        controllerExt.strDocumentIds = '4064457BCA2EDA5E457BCA2E4064B1B5F9E6B8690A9C, F9E6B8690A9C4064457BCA2EDA5E457BCA2E4064';
        controllerExt.objPAM = new NPN_PartnerAttributes_Modifiaction__c(
            PartnerAttributes_Modification__c = 'Demotion',
            Competency__c = COMM_Constants.TEST_PORTAL_COMPETENCY_DL+';'+COMM_Constants.TEST_PORTAL_COMPETENCY_PV+';'+COMM_Constants.TEST_PORTAL_COMPETENCY_GV+';',
            Competency_Level__c = 'Preferred',
            Sync__c = false,
            CSP_Yes_No__c = false,
            Account__c = partnerAccount.Id,
            Program_Type__c = COMM_Constants.PA_PROGRAM_SP,
            Termination_Initiated__c = false,
            Competency_Termination_30_days_Complete__c = false,
            Contact__c = partnerContact.Id,
            DocuSign_Envelope_ID__c = '457BCA2E-DA5E-4064-B1B5-F9E6B8690A9C'

            );
        controllerExt.save();

        test.stopTest();

    }

}