force-app/main/default/objects/Account/fields/Billing_Region__c.field-meta.xml
<CustomField>
    <fullName>Billing_Region__c</fullName>
    <label>Billing Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>NALA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NFR_Software_Licence__c/NFR_Software_Licence__c.object-meta.xml
<CustomObject>
    <description>NPN : NFR : Software Licence for maintaining DocuSign Ids</description>
    <label>NFR DocuSign Id</label>
    <nameField>
        <label>NFR DocuSign Id Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NFR DocuSign Ids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NFR_Software_Licence__c/fields/DocuSIgn_Template_ID__c.field-meta.xml
<CustomField>
    <fullName>DocuSIgn_Template_ID__c</fullName>
    <label>DocuSIgn Template ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_NFR_Request_Data__mdt/NPN_NFR_Request_Data__mdt.object-meta.xml
<CustomObject>
    <label>NPN NFR Request Data</label>
    <pluralLabel>NPN NFR Request Data</pluralLabel>
</CustomObject>

force-app/main/default/objects/NPN_NFR_Request_Data__mdt/fields/Value__c.field-meta.xml
<CustomField>
    <fullName>Value__c</fullName>
    <label>Value</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/NPN_NFR_Software_Request__c/NPN_NFR_Software_Request__c.object-meta.xml
<CustomObject>
    <description>NPN: Created for SDS-891
Stores the NFR SW License Requests raised on the NPN portal by partners.</description>
    <label>NFR SW License Request</label>
    <nameField>
        <displayFormat>NSR-{00000}</displayFormat>
        <label>NFR SW License Request</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NFR SW License Requests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NPN_NFR_Software_Request__c/fields/Approver__c.field-meta.xml
<CustomField>
    <fullName>Approver__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approver</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NPN_NFR_Software_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPN_NFR_Software_Request__c/fields/Company_Name__c.field-meta.xml
<CustomField>
    <fullName>Company_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Company Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>NPN_Demo_Unit_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPN_NFR_Software_Request__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested By</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>NFR_Licenses_Requests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPN_NFR_Software_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NPN_NFR_Software_Request__c/fields/vCS__c.field-meta.xml
<CustomField>
    <fullName>vCS__c</fullName>
    <label>vCS</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NPN_NFR_Software_Request__c/fields/VDWS__c.field-meta.xml
<CustomField>
    <fullName>VDWS__c</fullName>
    <description>Field label changed to &apos;vWS&apos; from &apos;VDWS&apos; for SDS-3278</description>
    <label>vWS</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NPN_NFR_Software_Request__c/fields/VPC__c.field-meta.xml
<CustomField>
    <fullName>VPC__c</fullName>
    <description>Field label changed to &apos;vPC&apos; from &apos;VPC&apos; for SDS-3278</description>
    <label>vPC</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NPN_NFR_VP_Data__mdt/NPN_NFR_VP_Data__mdt.object-meta.xml
<CustomObject>
    <label>NPN NFR VP Data</label>
    <pluralLabel>NPN NFR VP Data</pluralLabel>
</CustomObject>

force-app/main/default/objects/NPN_NFR_VP_Data__mdt/fields/First_Name__c.field-meta.xml
<CustomField>
    <fullName>First_Name__c</fullName>
    <label>First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_NFR_VP_Data__mdt/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NPN_NFR_SendDocusignCtrl.cls
public class NPN_NFR_SendDocusignCtrl {

    private final NPN_NFR_Software_Request__c objNFRReq;
    public String strDocumentIds {get; set;}
    public String strVPFirstName {get; set;}
    public String strVPLastName {get; set;}
    public String strVPEmail {get; set;}
    public String strEmailSubject {get; set;}
    public String strEmailBody {get; set;}
    public String legalEmail {get; set;}
    public String pricingOpsEmail {get; set;}
    public String npnOnboardingEmail {get; set;}
    public String reqstrFName {get; set;}
    public String reqstrLName {get; set;}
    public String rqstrEmail {get; set;}
    public String pbmFName {get; set;}
    public String pbmLName {get; set;}
    public String pbmEmail {get; set;}
    Map<String, String> metaRecordsMap {get; set;}
    Map<String, NPN_NFR_VP_Data__mdt> vpDataMap {get; set;}

    public NPN_NFR_SendDocusignCtrl(ApexPages.StandardController stdController) {

        String region = '';
        String country = '';

        metaRecordsMap = new Map<String, String>();
        vpDataMap = new Map<String, NPN_NFR_VP_Data__mdt>();
        strDocumentIds = '';

        this.objNFRReq = [SELECT Id, vCS__c, VDWS__c, VPC__c, Company_Name__r.Billing_Region__c, Company_Name__r.BillingCountry, Email__c, Requested_By__r.FirstName, 
        Requested_By__r.LastName,Approver__r.FirstName, Approver__r.LastName, Approver__r.Email, Status__c FROM NPN_NFR_Software_Request__c 
        WHERE Id = :ApexPages.CurrentPage().getParameters().get('Id') ];


        region = String.isNotBlank(this.objNFRReq.Company_Name__r.Billing_Region__c) ? this.objNFRReq.Company_Name__r.Billing_Region__c : '';
        country = String.isNotBlank(this.objNFRReq.Company_Name__r.BillingCountry) ? this.objNFRReq.Company_Name__r.BillingCountry : '';

        list<NFR_Software_Licence__c> lstDocusignConfig = [SELECT Id,Docusign_Template_ID__c, Name FROM NFR_Software_Licence__c];
        for(NFR_Software_Licence__c objDocConf : lstDocusignConfig) {
            if(!strDocumentIds.contains(objDocConf.Docusign_Template_ID__c)) {
                strDocumentIds += objDocConf.Docusign_Template_ID__c+',';
            }
        }

        strDocumentIds = strDocumentIds.substring(0,strDocumentIds.length()-1);

        for(NPN_NFR_Request_Data__mdt mdRec : [SELECT Id, DeveloperName, MasterLabel, Value__c FROM NPN_NFR_Request_Data__mdt]) {
            metaRecordsMap.put(mdRec.DeveloperName, mdRec.Value__c);
        }

        for(NPN_NFR_VP_Data__mdt vpRec : [SELECT Id, DeveloperName, MasterLabel, Email__c, First_Name__c, Last_Name__c FROM NPN_NFR_VP_Data__mdt]) {
            vpDataMap.put(vpRec.MasterLabel, vpRec);
        }

        strEmailSubject = metaRecordsMap.get('ds_Subject');
        strEmailBody = metaRecordsMap.get('ds_MsgBody');
        legalEmail = metaRecordsMap.get('Legal');
        pricingOpsEmail = metaRecordsMap.get('WWFO_Pricing_Operations');
        npnOnboardingEmail = metaRecordsMap.get('NPN_Onboarding');

        rqstrEmail      = this.objNFRReq.Email__c;
        reqstrFName     = this.objNFRReq.Requested_By__r.FirstName;
        reqstrLName     = this.objNFRReq.Requested_By__r.LastName;
        pbmFName        = this.objNFRReq.Approver__r.FirstName;
        pbmLName        = this.objNFRReq.Approver__r.LastName;
        pbmEmail        = this.objNFRReq.Approver__r.Email;

        if(String.isNotBlank(country) && vpDataMap.containsKey(country)) {
            strVPFirstName = vpDataMap.get(country).First_Name__c;
            strVPLastName = vpDataMap.get(country).Last_Name__c;
            strVPEmail  = vpDataMap.get(country).Email__c;
        } else if(String.isNotBlank(region) && vpDataMap.containsKey(region)) {
            strVPFirstName = vpDataMap.get(region).First_Name__c;
            strVPLastName = vpDataMap.get(region).Last_Name__c;
            strVPEmail  = vpDataMap.get(region).Email__c;
        }
    }
}