force-app/main/default/objects/Account/fields/Billing_Sub_Region__c.field-meta.xml
<CustomField>
    <fullName>Billing_Sub_Region__c</fullName>
    <label>Billing Sub-Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>EE</fullName>
            </value>
            <value>
                <fullName>ME</fullName>
            </value>
            <value>
                <fullName>NE</fullName>
            </value>
            <value>
                <fullName>SASIA</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>ANZ</fullName>
            </value>
            <value>
                <fullName>SEA</fullName>
            </value>
            <value>
                <fullName>CHINA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>KOREA</fullName>
            </value>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>TW</fullName>
            </value>
            <value>
                <fullName>LA</fullName>
            </value>
            <value>
                <fullName>NA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Account/recordTypes/NPN_Account_Registry.recordType-meta.xml
<RecordType>
    <fullName>NPN_Account_Registry</fullName>
    <active>true</active>
    <label>NPN Account Registry</label>
</RecordType>

force-app/main/default/objects/Partner_Attribute__c/Partner_Attribute__c.object-meta.xml
<CustomObject>
    <description>NPN : Additional attributes to an account - program type, competency, level etc.</description>
    <label>Partner Attribute</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Attribute ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Attribute__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <inlineHelpText>Select account</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Attributes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/ATP_Partner_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>ATP_Partner_Start_Date__c</fullName>
    <label>ATP Partner Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/ATP_Partner_Termination_Date__c.field-meta.xml
<CustomField>
    <fullName>ATP_Partner_Termination_Date__c</fullName>
    <label>ATP Partner Termination Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Date_Competency_Terminated__c.field-meta.xml
<CustomField>
    <fullName>Date_Competency_Terminated__c</fullName>
    <label>Date Competency Terminated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Exempted_from_POS_Submission__c.field-meta.xml
<CustomField>
    <fullName>Exempted_from_POS_Submission__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Check if the POS submission is not required for this partner attribute</inlineHelpText>
    <label>Exempted from POS Submission</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Competency__c.field-meta.xml
<CustomField>
    <fullName>Partner_Competency__c</fullName>
    <label>Partner Competency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Partner_Program_Name__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Compute</fullName>
            </value>
            <value>
                <fullName>Compute DGX</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
            <value>
                <fullName>Embedded Edge</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Virtualization</fullName>
            </value>
            <value>
                <fullName>Visualization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Program_Name__c</fullName>
    <label>Partner Program Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Solution Provider</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Tegra Embedded</fullName>
            </value>
            <value>
                <fullName>Services Subcontractor</fullName>
            </value>
            <value>
                <fullName>Cloud Service Provider</fullName>
            </value>
            <value>
                <fullName>Service Delivery Partner</fullName>
            </value>
            <value>
                <fullName>Solution Advisor</fullName>
            </value>
            <value>
                <fullName>Solutions Integration Partner</fullName>
            </value>
            <value>
                <fullName>Industry Focus</fullName>
            </value>
            <value>
                <fullName>Federal Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Global Systems Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Sub_Program__c.field-meta.xml
<CustomField>
    <fullName>Partner_Sub_Program__c</fullName>
    <label>Partner Sub Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Partner_Program_Name__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Data Center Provider</fullName>
            </value>
            <value>
                <fullName>EDU Services</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Support Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Program_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Level__c</fullName>
    <description>Program Level</description>
    <inlineHelpText>Select the program level - Preferred or Elite</inlineHelpText>
    <label>Program Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SuRF_DGX_HOT_Compliance__c/SuRF_DGX_HOT_Compliance__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF_DGX_HOT_Compliance</label>
    <nameField>
        <label>SuRF_DGX_HOT_Compliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SuRF_DGX_HOT_Compliance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_DGX_HOT_Compliance__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <label>Account_Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SuRF_DGX_HOT_Compliance__c/fields/Partner_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Program_Name__c</fullName>
    <label>Partner_Program_Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SuRF_Partner_Program</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SuRF_DGX_HOT_Compliance__c/fields/Partner_Sub_Program__c.field-meta.xml
<CustomField>
    <fullName>Partner_Sub_Program__c</fullName>
    <label>Partner_Sub_Program</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/SuRF_Partner_Program.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Solution Provider</fullName>
    </customValue>
    <customValue>
        <fullName>OEM</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud Service Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Solution Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>Inception Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Tegra Embedded</fullName>
    </customValue>
    <customValue>
        <fullName>Services Subcontractor</fullName>
    </customValue>
    <customValue>
        <fullName>Service Delivery Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Solutions Integration Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Federal Systems Integrator</fullName>
    </customValue>
    <customValue>
        <fullName>Global Systems Integrator</fullName>
    </customValue>
    <masterLabel>SuRF Partner Program</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/SuRF_DGX_HOT_CPL_tgr_cls_Test.cls
@isTest(seeAllData=false)
private class SuRF_DGX_HOT_CPL_tgr_cls_Test{


    @TestSetup
    static void makeData(){  
        
        
        Account partnerAcc;
        Id accRecTypeId = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('NPN_Account_Registry').getRecordTypeId();

        
        genericMock fakeResp = new genericMock(200,'Complete',
        '<?xml version="1.0" encoding="UTF-8"?>'+
        '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/>'+
        '<soapenv:Body><ns:SyncServiceResponse xmlns:ns="http://nvidiasapemsconnector.nvidiaaxis2service.nvidia.smps.gmlto.com">'+
        '<ns:return xmlns:ax21="http://dto.nvidiaaxis2service.nvidia.smps.gmlto.com/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ax21:SyncResponse"><ax21:errorMessage>'+
        '</ax21:errorMessage><ax21:statusCode>success</ax21:statusCode>'+
        '<ax21:syncType>PartnerUser</ax21:syncType></ns:return>'+
        '</ns:SyncServiceResponse></soapenv:Body></soapenv:Envelope>',null);

        System.Test.setMock(HttpCalloutMock.class, fakeResp);  


        //Create a NPN Account with Billing Country, Region
        partnerAcc = Test_COMM_Factory.createNPNAccountWithUSBillingAddressRegion('DRNPNAccountRegistry1', accRecTypeId);
        system.debug('***partnerAcc: ' + partnerAcc);


        //we can not set IsParnter or IsCustomerPortal at the time of insert, so needs to do this on update
        partnerAcc.IsPartner = true;
        update partnerAcc;

        Partner_Attribute__c pAttrb2 = new Partner_Attribute__c(
            Account_Name__c  =  partnerAcc.Id,
            Partner_Competency__c = COMM_Constants.TEST_PORTAL_COMPETENCY_DL,
            Partner_Program_Name__c = COMM_Constants.PA_PROGRAM_SP,
            Program_Level__c = COMM_Constants.PA_LEVEL_PREF,
            ATP_Partner_Termination_Date__c = null,
            Date_Competency_Terminated__c = null,
            Exempted_from_POS_Submission__c = false,
            ATP_Partner_Start_Date__c = Date.valueOf(system.today()));
        insert pAttrb2;
    }

    @isTest static void testOne(){   

        Account partnerAcc = [SELECT Id,
                                    Name 
                                    FROM Account 
                                    WHERE Name ='DRNPNAccountRegistry1' LIMIT 1];

        SuRF_DGX_HOT_Compliance__c dObj = new SuRF_DGX_HOT_Compliance__c (
            Partner_Program_Name__c = COMM_Constants.PA_PROGRAM_SP,
            Competency__c = COMM_Constants.TEST_PORTAL_COMPETENCY_DL,
            Category__c = 'Training Compliance',
            Account_Id__c = partnerAcc.Id,
            Account_Name__c = partnerAcc.Name,
            Partner_Sub_Program__c ='',
            Flag__c =1,
            Billing_Sub_Region__c ='NA',
            BillingCountry__c = 'United States',
            Order__c = 1
        );
        insert dObj;
    }

    @isTest static void testTwo(){   

        Account partnerAcc = [SELECT Id,
                                    Name 
                                    FROM Account 
                                    WHERE Name ='DRNPNAccountRegistry1' LIMIT 1];

        SuRF_DGX_HOT_Compliance__c dObj = new SuRF_DGX_HOT_Compliance__c (
            Partner_Program_Name__c = COMM_Constants.PA_PROGRAM_SP,
            Competency__c = COMM_Constants.TEST_PORTAL_COMPETENCY_DL,
            Category__c = 'Training Compliance',
            Account_Id__c = partnerAcc.Id,
            Account_Name__c = partnerAcc.Name,
            Partner_Sub_Program__c ='',
            Flag__c = -1,
            Billing_Sub_Region__c ='NA',
            BillingCountry__c = 'United States',
            Order__c = 1
        );
        insert dObj;
    }
}