force-app/main/default/objects/Account/fields/Billing_Region__c.field-meta.xml
<CustomField>
    <fullName>Billing_Region__c</fullName>
    <label>Billing Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>NALA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Announcement__c/Announcement__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : Custom Object for NVIDIA to create Announcements.</description>
    <label>Announcement</label>
    <nameField>
        <label>Announcement Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Announcement__c/fields/Access_Level__c.field-meta.xml
<CustomField>
    <fullName>Access_Level__c</fullName>
    <label>Access Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generic</fullName>
            </value>
            <value>
                <fullName>Product Specific</fullName>
            </value>
            <value>
                <fullName>Entitlement Specific</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Customer Specific</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Community_User_Active__c.field-meta.xml
<CustomField>
    <fullName>Community_User_Active__c</fullName>
    <formula>Community_User__r.IsActive</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Community User : Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/is_DGX_Contact__c.field-meta.xml
<CustomField>
    <fullName>is_DGX_Contact__c</fullName>
    <defaultValue>false</defaultValue>
    <label>is DGX Contact</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Synced_IDM_DGX__c.field-meta.xml
<CustomField>
    <fullName>Synced_IDM_DGX__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Synced_IDM_DGX</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CustomerAnnouncement__c/CustomerAnnouncement__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : Junction Object to create Announcement records to Accounts based on Announcement creation criteria like Generic, Product and Entitlement</description>
    <label>Announcement</label>
    <nameField>
        <label>Announcement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerAnnouncement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Announcements</relationshipLabel>
    <relationshipName>Announcements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CustomerAnnouncement__c/fields/Announcement__c.field-meta.xml
<CustomField>
    <fullName>Announcement__c</fullName>
    <label>Announcement</label>
    <referenceTo>Announcement__c</referenceTo>
    <relationshipLabel>Announcements</relationshipLabel>
    <relationshipName>Announcements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Entitlement_Status__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Status__c</fullName>
    <formula>IF ( Text(Order_Type__c) = &apos;ZMRS&apos;  || Text(Order_Type__c) = &apos;ZKB&apos; , &quot;MRS&quot;,
	IF ( ISBLANK(SAP_Order__c) &amp;&amp; ISBLANK(Subscription__c), &quot;Removed&quot;,
		IF ( TODAY() &gt;= StartDate &amp;&amp; TODAY() &lt;= EndDate, &quot;Active&quot;,
			IF(StartDate &gt; TODAY(), &quot;Inactive&quot;, 
						&quot;Expired&quot;
			)
		)
	)
)</formula>
    <label>Entitlement Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <formula>TEXT( Service_Product__r.Family )</formula>
    <label>Product Family</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ESP_DGXStationCoolentNotify_BAT_SCH.cls
/*-----------------------------------------------------------------------------------------------------------------------------------------------
Batch class name : ESP_DGXStationCoolentNotify_BAT_SCH
Description : Notify DGX station customers to remind about DGX Station Cooling Liquid at the anniversary of the DGX stations.
              Customer should be able to see an announcement for DGX Station Cooling Liquid on the community

Date            Version    Description
-----------    ---------   ----------------------------------------------------------------------- 
10/25/2019        1.0        Created
          
----------------------------------------------------------------------------------------------------------------------------------------------------
*/

public class ESP_DGXStationCoolentNotify_BAT_SCH implements Database.Batchable<SObject>,Schedulable,Database.RaisesPlatformEvents {

public Database.QueryLocator start(Database.BatchableContext BC){
    system.debug('**batch start**');
    List<Entitlement> lstEntitlement = [select id, AccountId from Entitlement where Product_Family__C like '%DGX Station%' and (startDate=:Date.Today().addYears(-1) or startDate=:Date.Today().addYears(-2) or startDate=:Date.Today().addYears(-3)) and Entitlement_Status__c='Active'];
    Set<Id> setActIds = new Set<Id>();
    if(lstEntitlement.isEmpty())
        return null;
    else{
            for(Entitlement tmpEnt : lstEntitlement ){
                setActIds.add(tmpEnt.AccountId );
            }
    }    
// Create Customer specific announcement for each Account
    CustomerAnnouncement__c custAnnounce;
    List<CustomerAnnouncement__c> lstCustAnnounce = new List<CustomerAnnouncement__c>();
    Announcement__c announce = [select id, name from Announcement__c where name= :label.Service_Cloud_Coolent_Announcement_Id and Access_Level__c ='Customer Specific' limit 1];
    for(Id actId : setActIds){
        custAnnounce = new CustomerAnnouncement__c (Announcement__c=announce.id ,Account__c=actId);
        lstCustAnnounce.add(custAnnounce );
    } 
    insert lstCustAnnounce; 
    system.debug('**setActIds**'+setActIds);  
// Find DGX contacts for above accounts    
    string strSql = 'select id,name,email,Account.Billing_Region__c,AccountId from contact where accountId in :setActIds and Community_User_Active__c=true and Synced_IDM_DGX__c=true and is_DGX_Contact__c=true';
    return Database.getQueryLocator(strSql );
}

public void execute(Database.BatchableContext BC, List<Contact>scope){
    system.debug('**batch execution**');
    EmailTemplate JapanTemplateId = [Select DeveloperName,Id,subject from EmailTemplate where DeveloperName= 'Service_Cloud_DGX_Station_Coolent_Reminder_Japan' limit 1];
    EmailTemplate TemplateId = [Select DeveloperName,Id,subject from EmailTemplate where DeveloperName= 'Service_Cloud_DGX_Station_Coolent_Reminder' limit 1];
    OrgWideEmailAddress owa = [select id, DisplayName, Address from OrgWideEmailAddress where Address='no_reply@nvidia.com' limit 1];
    List<Messaging.SingleEmailMessage> lstMessages= new List<Messaging.SingleEmailMessage>();
    Messaging.SingleEmailMessage mail ;
    List<string> lstToAddresses = new List<string>();
    for(Contact tmpContact : scope)
    {
            mail = new Messaging.SingleEmailMessage();
            mail.setOrgWideEmailAddressId(owa.id);
            if(tmpContact.Account.Billing_Region__c=='JAPAN')
                mail.setTemplateID(JapanTemplateId.Id);
            else
                mail.setTemplateID(templateId.Id);     
            mail.setTargetObjectId(tmpContact.Id);
            mail.setSaveAsActivity(true);
            lstMessages.add(mail);
    }
    if(!lstMessages.isEmpty()){          
         Messaging.SendEmailResult[] results = Messaging.sendEmail(lstMessages,false);
        if (results[0].success) {
            System.debug('The email was sent successfully.');
        } else {
            System.debug('The email failed to send: '
                  + results[0].errors[0].message);
        }
    }
}    


public void finish(Database.BatchableContext BC){
}

public void execute(SchedulableContext sc){
     ESP_DGXStationCoolentNotify_BAT_SCH bch = new ESP_DGXStationCoolentNotify_BAT_SCH();
     Database.executeBatch(bch,20);

}

}