force-app/main/default/objects/Account/fields/EMS_Update_Required__c.field-meta.xml
<CustomField>
    <fullName>EMS_Update_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Licensing 2.0 EMS Updates are monitored using this.</description>
    <label>EMS Update Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/NPN_Account_Registry.recordType-meta.xml
<RecordType>
    <fullName>NPN_Account_Registry</fullName>
    <active>true</active>
    <label>NPN Account Registry</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Community_User__c.field-meta.xml
<CustomField>
    <fullName>Community_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Community User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/EMS_Update_Required__c.field-meta.xml
<CustomField>
    <fullName>EMS_Update_Required__c</fullName>
    <defaultValue>false</defaultValue>
    <label>EMS Update Required</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partner Primary Contact</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Service and Support</fullName>
            </value>
            <value>
                <fullName>RMA</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>MDF</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Renewals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner Contact</label>
</RecordType>

force-app/main/default/objects/QPB_Statement__c/QPB_Statement__c.object-meta.xml
<CustomObject>
    <description>NPN: Created for SDS-1406
Stores the QPB details for partners</description>
    <label>QPB Statement</label>
    <nameField>
        <displayFormat>QPBS-{000000}</displayFormat>
        <label>QPB Statement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QPB Statements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QPB_Statement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QPB Statements</relationshipLabel>
    <relationshipName>QPB_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Attachment_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attachment Uploaded?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FY20</fullName>
            </value>
            <value>
                <fullName>FY21</fullName>
            </value>
            <value>
                <fullName>FY22</fullName>
            </value>
            <value>
                <fullName>FY23</fullName>
            </value>
            <value>
                <fullName>FY24</fullName>
            </value>
            <value>
                <fullName>FY25</fullName>
            </value>
            <value>
                <fullName>FY26</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Notified__c.field-meta.xml
<CustomField>
    <fullName>Notified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notified?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Q1</fullName>
            </value>
            <value>
                <fullName>Q2</fullName>
            </value>
            <value>
                <fullName>Q3</fullName>
            </value>
            <value>
                <fullName>Q4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>Progress</fullName>
            </value>
            <value>
                <fullName>MOU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NPN_QPB_Stmt_Notification_Batch_Test.cls
/***
 *  @description: Test class for NPN_QPB_Stmt_Notification_Batch
 */
@isTest(seeAllData = false)
private class NPN_QPB_Stmt_Notification_Batch_Test {


    static void createData(){
        map<String, Id> mapProfNameId;

        User partnerUser1;
        Id accRecTypeId;
        Id contactRecTypeId;
        Account partnerAcc;
        String userName;
        List<Contact> listContacts = new List<Contact>();
        List<User> listUsers = new List<User>();

        accRecTypeId     = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('NPN_Account_Registry').getRecordTypeId();
        contactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Partner').getRecordTypeId();

        Profile partnerProf = [SELECT Id, Name FROM Profile WHERE Name = :COMM_Constants.PROF_PP_TPP_GENERIC LIMIT 1];

        accRecTypeId     = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('NPN_Account_Registry').getRecordTypeId();
        contactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Partner').getRecordTypeId();

        //Create a NPN Account with Billing Country, Region
        partnerAcc = Test_COMM_Factory.createNPNAccountWithUSBillingAddressRegion('DRNPNAccountRegistry1', accRecTypeId);
        system.debug('***partnerAcc: ' + partnerAcc);


        //we can not set IsParnter or IsCustomerPortal at the time of insert, so needs to do this on update
        partnerAcc.IsPartner = true;
        update partnerAcc;


        Contact cont = new Contact();
        cont.FirstName      =   'Runu';
        cont.LastName       =   'Mulay';
        cont.Email          =   'drcontactjena11@nv.com';
        cont.Phone          =   '789-978-5529';
        cont.AccountId      =   partnerAcc.Id;
        cont.MailingCountry =   COMM_Constants.ADDRESS_COUNTRY;
        cont.Role__c        =   'Partner Primary Contact;POS';
        cont.RecordTypeId   =   contactRecTypeId;
        insert cont;

        User comUser = new User(
            LastName = cont.LastName,
            Alias = cont.LastName,
            Email = cont.Email,
            Username = cont.LastName+'@slytherin.com.rpcf',
            CommunityNickname = cont.LastName+'nvvippartnerone',
            ProfileId = partnerProf.Id,
            ContactId=cont.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            IsActive = true
            );
        insert comUser;

        cont.Community_User__c = comUser.Id;
        update cont;
    }

    static void makeData(){

        map<String, Id> mapProfNameId;
        Account partnerAcc;
        //Contact partnerContact1;
        User partnerUser1;
        Id accRecTypeId;
        Id contactRecTypeId;
        String userName;

        accRecTypeId     = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('NPN_Account_Registry').getRecordTypeId();
        contactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Partner').getRecordTypeId();

        //get All Profiles (PROF_PP_VGX_GENERIC = NPN Partner Community(LOGIN), PROF_INT_PARTNER_ADMIN = Sales Profile - Partner Admin)
        list<string> lstProfNames = new list<string> {COMM_Constants.PROF_PP_VGX_GENERIC, COMM_Constants.PROF_INT_PARTNER_ADMIN };
        mapProfNameId = Test_COMM_Factory.getProfsByName(lstProfNames);

        //Create a NPN Account with Billing Country, Region
        partnerAcc = Test_COMM_Factory.createNPNAccountWithUSBillingAddressRegion('DRNPNAccountRegistry1', accRecTypeId);
        system.debug('***partnerAcc: ' + partnerAcc);


        //we can not set IsParnter or IsCustomerPortal at the time of insert, so needs to do this on update
        partnerAcc.IsPartner = true;
        partnerAcc.EMS_Update_Required__c= false;
        update partnerAcc;

        //Create a Partner Contact
        //partnerContact1 = Test_COMM_Factory.createContactWithMailingAddress('LDRJena11', 'FContact11', partnerAcc.Id, 'drcontactjena11@nv.com', contactRecTypeId, COMM_Constants.ADDRESS_STREET, COMM_Constants.ADDRESS_CITY, COMM_Constants.ADDRESS_STATE, COMM_Constants.ADDRESS_COUNTRY, COMM_Constants.ADDRESS_ZIP );

        Contact cont = new Contact();
        cont.FirstName      =   'Runu';
        cont.LastName       =   'Mulay';
        cont.Email          =   'drcontactjena11@nv.com';
        cont.Phone          =   '789-978-5529';
        cont.AccountId      =   partnerAcc.Id;
        cont.MailingCountry =   COMM_Constants.ADDRESS_COUNTRY;
        cont.Role__c        =   'Partner Primary Contact;POS';
        cont.RecordTypeId   =   contactRecTypeId;
        insert cont;

        //Create a Partner User with profile named 'NPN Partner Community(LOGIN)'
        User comUser = new User(
            LastName='one',
            Alias = 'tsale',
            Email = 'nvpartnerone@foo.com',
            Username = 'nvvippartnerone@foo.com.crqext',
            CommunityNickname = 'nvvippartnerone',
            ProfileId = mapProfNameId.get(COMM_Constants.PROF_PP_VGX_GENERIC),
            //ContactId=partnerContact1.Id,
            ContactId=cont.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
            );
        insert comUser;

        cont.Community_User__c = comUser.Id;
        update cont;
    }

    static void createQPBRecords(){

        Account partnerAcc = [SELECT Id FROM Account WHERE Name = 'DRNPNAccountRegistry1' LIMIT 1];
        List<QPB_Statement__c> recordsForInsert = new List<QPB_Statement__c>();
        List<QPB_Statement__c> recordsForUpdate = new List<QPB_Statement__c>();
        for(Integer i = 1; i<=4; i++) {
            recordsForInsert.add (new QPB_Statement__c (
                              Account__c = partnerAcc.Id,
                              Fiscal_Year__c = 'FY20',
                              Quarter__c = 'Q'+i,
                              Type__c = 'Final',
                              Status__c = 'Active',
                              Attachment_Uploaded__c =false,
                              Notified__c =false
                              ));
        }

        insert recordsForInsert;

        for(QPB_Statement__c qpbRec : recordsForInsert) {
            qpbRec.Attachment_Uploaded__c = true;
            recordsForUpdate.add(qpbRec);
        }

        update recordsForUpdate;
    }

    @isTest static void notifyPartnersForStmtTest(){
        genericMock fakeResp = new genericMock(200,'Complete',
           '<?xml version="1.0" encoding="UTF-8"?>'+
           '<soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/>'+
           '<soapenv:Body><ns:SyncServiceResponse xmlns:ns="http://nvidiasapemsconnector.nvidiaaxis2service.nvidia.smps.gmlto.com">'+
           '<ns:return xmlns:ax21="http://dto.nvidiaaxis2service.nvidia.smps.gmlto.com/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ax21:SyncResponse"><ax21:errorMessage>'+
           '</ax21:errorMessage><ax21:statusCode>success</ax21:statusCode>'+
           '<ax21:syncType>PartnerUser</ax21:syncType></ns:return>'+
           '</ns:SyncServiceResponse></soapenv:Body></soapenv:Envelope>',null);

        System.Test.setMock(HttpCalloutMock.class, fakeResp);
        Test.startTest();

        //createData();
        makeData();
        createQPBRecords();
        //List<AsyncApexJob> existingJob = [SELECT Id,JobType,Status FROM AsyncApexJob WHERE ApexClass.Name ='NPN_QPB_Stmt_Notification_Batch' AND JobType ='ScheduledApex' AND Status ='Queued'];

        /*if(existingJob.isEmpty()) {
            NPN_QPB_Stmt_Notification_Batch batchName = new NPN_QPB_Stmt_Notification_Batch();
            Database.executeBatch(batchName,20);
        }else{*/
            for(AsyncApexJob aJob : [SELECT Id,JobType,Status FROM AsyncApexJob WHERE ApexClass.Name ='NPN_QPB_Stmt_Notification_Batch' AND JobType ='ScheduledApex' AND Status ='Queued']){
                System.AbortJob(aJob.Id);
            }
            NPN_QPB_Stmt_Notification_Batch sch = new NPN_QPB_Stmt_Notification_Batch();
            String jobId = System.schedule('NPN_QPB_Stmt_Notification_Batch_TEST','0 0 * * * ?',sch);
        //}
        Test.stopTest();
    }
}