force-app/main/default/objects/Account/fields/NPN_Program_Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>NPN_Program_Signed_Date__c</fullName>
    <inlineHelpText>NPN Program Signed Date</inlineHelpText>
    <label>NPN Agreement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Country_List__c/Country_List__c.object-meta.xml
<CustomObject>
    <description>CRM : Country/State/Region/Sub-Region/Territory: Contains the Country ISO Code, Name for all countries. Used to drive Region/Sub-Region/Territory information.
Need Public Read Only OWD for internal and external access.</description>
    <label>Country List</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country Lists</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_List__c/fields/ISO_Code__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code__c</fullName>
    <label>ISO Code</label>
    <length>2</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country_List__c/fields/Sub_Region__c.field-meta.xml
<CustomField>
    <fullName>Sub_Region__c</fullName>
    <label>Sub-Region</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Commitment_Master__c/NPN_Revenue_Commitment_Master__c.object-meta.xml
<CustomObject>
    <description>NPN : Master data: holds NPN Partner Opportunity Pipeline Commitments for Competency, Level, Country and Threshold($). 

This data will be used to create yearly &quot;NPN Revenue Target&quot; records for each &quot;Partner Attribute&quot; record.</description>
    <label>NPN Revenue Commitment Master</label>
    <nameField>
        <displayFormat>NPNRCM-{0000}</displayFormat>
        <label>NPN Revenue Commitment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPN Revenue Commitment Master</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/NPN_Revenue_Commitment_Master__c/fields/Competency__c.field-meta.xml
<CustomField>
    <fullName>Competency__c</fullName>
    <label>Competency</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Compute</fullName>
            </value>
            <value>
                <fullName>Virtualization</fullName>
            </value>
            <value>
                <fullName>Visualization</fullName>
            </value>
            <value>
                <fullName>Inception Partner</fullName>
            </value>
            <value>
                <fullName>Compute DGX</fullName>
            </value>
            <value>
                <fullName>Embedded Edge</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Commitment_Master__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <description>Lookup to Country List custom object</description>
    <label>Country</label>
    <referenceTo>Country_List__c</referenceTo>
    <relationshipLabel>NPN Revenue Commitment Master</relationshipLabel>
    <relationshipName>NPN_Revenue_Commitment_Master</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Commitment_Master__c/fields/Level__c.field-meta.xml
<CustomField>
    <fullName>Level__c</fullName>
    <label>Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Commitment_Master__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <label>Program</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Solution Provider</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Cloud Service Provider</fullName>
            </value>
            <value>
                <fullName>Federal Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Global Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Solutions Integration Partner</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Commitment_Master__c/fields/Threshold__c.field-meta.xml
<CustomField>
    <fullName>Threshold__c</fullName>
    <label>Threshold($)</label>
    <precision>10</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Target_Automation_Settings__c/NPN_Revenue_Target_Automation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Used in NPN Revenue Target Automation related trigger and batch job.
If the field &quot;No Match - No Revenue Target&quot; is true, then do not add a revenue target if there is no matching master data lookup in NPN Revenue Commitment Master (for Program Type, Competency, Level, Account Billing Country)</description>
    <label>NPN Revenue Target Automation Settings</label>
</CustomObject>

force-app/main/default/objects/NPN_Revenue_Target_Automation_Settings__c/fields/No_Match_No_Revenue_Target__c.field-meta.xml
<CustomField>
    <fullName>No_Match_No_Revenue_Target__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If the field &quot;No Match - No Revenue Target&quot; is true, then do not add a revenue target if there is no matching master data lookup in NPN Revenue Commitment Master (for Program Type, Competency, Level, Account Billing Country)</description>
    <inlineHelpText>If the field &quot;No Match - No Revenue Target&quot; is true, then do not add a revenue target if there is no matching master data lookup in NPN Revenue Commitment Master(for Program Type, Competency, Level, Account Billing Country)</inlineHelpText>
    <label>No Match - No Revenue Target</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Targets__c/NPN_Revenue_Targets__c.object-meta.xml
<CustomObject>
    <description>NPN : NPN Revenue Target: It holds revenue targets for each year for each NPN Partner based on their Program/Competency/Level and their Billing Country. It is child of Partner Attribute object (Partner Attributes are child to Account).</description>
    <label>NPN Revenue Target</label>
    <nameField>
        <displayFormat>RT-{000000}</displayFormat>
        <label>Targets ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPN Revenue Targets</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/NPN_Revenue_Targets__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>HYPERLINK(  Partner_Attribute__r.Account_Name__c,   Partner_Attribute__r.Account_Name__r.Name , &quot;_self&quot;)</formula>
    <label>Account Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Targets__c/fields/Minimum_Annual_Sales_Commitment__c.field-meta.xml
<CustomField>
    <fullName>Minimum_Annual_Sales_Commitment__c</fullName>
    <label>Minimum Annual Sales Commitment</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Targets__c/fields/Partner_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Partner_Attribute__c</fullName>
    <inlineHelpText>This is the auto-generated Partner Attribute number. Please do not edit this field.</inlineHelpText>
    <label>Partner Attribute</label>
    <referenceTo>Partner_Attribute__c</referenceTo>
    <relationshipLabel>NPN Revenue Targets</relationshipLabel>
    <relationshipName>NPN_Revenue_Targets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/NPN_Revenue_Targets__c/fields/Year__c.field-meta.xml
<CustomField>
    <fullName>Year__c</fullName>
    <inlineHelpText>Select the calendar year.</inlineHelpText>
    <label>Year</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2015</fullName>
            </value>
            <value>
                <fullName>2016</fullName>
            </value>
            <value>
                <fullName>2017</fullName>
            </value>
            <value>
                <fullName>2018</fullName>
            </value>
            <value>
                <fullName>2019</fullName>
            </value>
            <value>
                <fullName>2020</fullName>
            </value>
            <value>
                <fullName>2021</fullName>
            </value>
            <value>
                <fullName>2022</fullName>
            </value>
            <value>
                <fullName>2023</fullName>
            </value>
            <value>
                <fullName>2024</fullName>
            </value>
            <value>
                <fullName>2025</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/Partner_Attribute__c.object-meta.xml
<CustomObject>
    <description>NPN : Additional attributes to an account - program type, competency, level etc.</description>
    <label>Partner Attribute</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Attribute ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Attribute__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <inlineHelpText>Select account</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Attributes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Competency__c.field-meta.xml
<CustomField>
    <fullName>Partner_Competency__c</fullName>
    <label>Partner Competency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Partner_Program_Name__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Compute</fullName>
            </value>
            <value>
                <fullName>Compute DGX</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
            <value>
                <fullName>Embedded Edge</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Virtualization</fullName>
            </value>
            <value>
                <fullName>Visualization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Program_Name__c</fullName>
    <label>Partner Program Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Solution Provider</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Tegra Embedded</fullName>
            </value>
            <value>
                <fullName>Services Subcontractor</fullName>
            </value>
            <value>
                <fullName>Cloud Service Provider</fullName>
            </value>
            <value>
                <fullName>Service Delivery Partner</fullName>
            </value>
            <value>
                <fullName>Solution Advisor</fullName>
            </value>
            <value>
                <fullName>Solutions Integration Partner</fullName>
            </value>
            <value>
                <fullName>Industry Focus</fullName>
            </value>
            <value>
                <fullName>Federal Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Global Systems Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Program_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Level__c</fullName>
    <description>Program Level</description>
    <inlineHelpText>Select the program level - Preferred or Elite</inlineHelpText>
    <label>Program Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_CRM_NPNRevTrgtAuto_Batch.cls
/*
    Test class for Schedulable and Batachable CRM_NPNRevTrgtAuto_Batch class
*/
 
@isTest(SeeAllData=false)
private class Test_CRM_NPNRevTrgtAuto_Batch {
    private static string BILLING_COUNTRY_US = 'United States'; 
    private static string BILLING_COUNTRY_CA = 'Canada'; 
    private static decimal THRESHOLD_COMMIT_EL = 100;
    private static decimal THRESHOLD_COMMIT_PREF = 100;
    private static string ACCOUNT_RT_NPN_ACCOUNT_REGISTRY = 'NPN Account Registry';
    private static string PORTAL_COMPETENCY_AC = 'Accelerated Computing';
    private static string PA_PROGRAM_SP = 'Solution Provider';
    private static string PA_LEVEL_ELITE = 'Elite';
    private static string PA_LEVEL_PREF = 'Preferred';

    
    //test for scheduling methods
    static testMethod void testSchedule_CRM_NPNRevTrgtAuto_Batch() {
        
        map<string, Id> mapRTNameId = new map<string, Id>();
        list<RecordType> lstRecTypes = [Select Name From RecordType Where SobjectType = 'Account' And Name = :ACCOUNT_RT_NPN_ACCOUNT_REGISTRY];
        for (RecordType rt : lstRecTypes){
            mapRTNameId.put(rt.Name, rt.Id);
        }

        //Create a NPN Account Registry type of Account
        list<Account> lstNPNAccounts = new list<Account>();
        Account accNPNRegUS = new Account(name = 'NPNAccountRegistryUS', RecordTypeId = mapRTNameId.get(ACCOUNT_RT_NPN_ACCOUNT_REGISTRY), BillingStreet = 'street1', BillingCity = 'Santa Clara', BillingState = 'California', BillingCountry = BILLING_COUNTRY_US, BillingPostalCode = '95050', NPN_Program_Signed_Date__c = system.today() );
        Account accNPNRegCA = new Account(name = 'NPNAccountRegistryCA', RecordTypeId = mapRTNameId.get(ACCOUNT_RT_NPN_ACCOUNT_REGISTRY), BillingStreet = 'street1', BillingCity = 'Santa Clara', BillingState = 'British Columbia', BillingCountry = BILLING_COUNTRY_CA, BillingPostalCode = '95050', NPN_Program_Signed_Date__c = system.today() );
        lstNPNAccounts.add(accNPNRegUS);
        lstNPNAccounts.add(accNPNRegCA);
        insert lstNPNAccounts;
        
        
        //Create Country_List__c
        list<Country_List__c> lstCountry = new list<Country_List__c>();
        Country_List__c countryUS = new Country_List__c(name = BILLING_COUNTRY_US, ISO_Code__c = 'US', Region__c = 'NALA', Sub_Region__c = 'LA', Territory__c = 'LA'); 
        Country_List__c countryCA = new Country_List__c(name = BILLING_COUNTRY_CA, ISO_Code__c = 'CA', Region__c = 'NALA', Sub_Region__c = 'LA', Territory__c = 'LA'); 
        lstCountry.add(countryUS);
        lstCountry.add(countryCA);
        insert lstCountry;
        
        //Create NPN_Revenue_Commitment_Master__c
        list<NPN_Revenue_Commitment_Master__c> lstRevCommitMstr = new list<NPN_Revenue_Commitment_Master__c>();
        NPN_Revenue_Commitment_Master__c RevCommitMstrUSACEL = new NPN_Revenue_Commitment_Master__c(Program__c = PA_PROGRAM_SP, Competency__c = PORTAL_COMPETENCY_AC, Level__c = PA_LEVEL_ELITE, Country__c = countryUS.Id, Threshold__c = THRESHOLD_COMMIT_EL);
        NPN_Revenue_Commitment_Master__c RevCommitMstrCAACPREF = new NPN_Revenue_Commitment_Master__c(Program__c = PA_PROGRAM_SP, Competency__c = PORTAL_COMPETENCY_AC, Level__c = PA_LEVEL_PREF, Country__c = countryCA.Id, Threshold__c = THRESHOLD_COMMIT_PREF);
        lstRevCommitMstr.add(RevCommitMstrUSACEL);
        lstRevCommitMstr.add(RevCommitMstrCAACPREF);
        insert lstRevCommitMstr;
        
        //Create custom settings data
        NPN_Revenue_Target_Automation_Settings__c csNPNSettings = new NPN_Revenue_Target_Automation_Settings__c();
        csNPNSettings.No_Match_No_Revenue_Target__c = true;
        insert csNPNSettings;
        
        //Create a Partner Attribute record
        list<Partner_Attribute__c> lstPA = new list<Partner_Attribute__c>();
        Partner_Attribute__c paAccNPNRegUS = new Partner_Attribute__c(Account_Name__c = accNPNRegUS.Id, Partner_Program_Name__c = PA_PROGRAM_SP, Partner_Competency__c = PORTAL_COMPETENCY_AC, Program_Level__c = PA_LEVEL_ELITE );
        Partner_Attribute__c paAccNPNRegCA = new Partner_Attribute__c(Account_Name__c = accNPNRegCA.Id, Partner_Program_Name__c = PA_PROGRAM_SP, Partner_Competency__c = PORTAL_COMPETENCY_AC, Program_Level__c = PA_LEVEL_PREF );
        lstPA.add(paAccNPNRegUS);
        insert lstPA;
        
        //delete the Revenue Targets that gets created by Partner Attribute trigger
        list<NPN_Revenue_Targets__c> lstRevTrgts = [Select Id From NPN_Revenue_Targets__c Where Partner_Attribute__c = :lstPA];
        delete lstRevTrgts;
        
        //Start the actual test for scheduling
        Test.startTest();
            
            //Create the Schedule to run after 5 seconds
            DateTime currDT = DateTime.now().addSeconds(5);
            integer sec = currDT.second();
            integer min = currDT.minute();
            string CRON_EXP = sec + ' ' + min + ' ' + '* ? * *'; 

            // Schedule the test job
            String jobId = System.schedule('Test CRM_NPNRevTrgtAuto_Batch',  CRON_EXP ,  new CRM_NPNRevTrgtAuto_Batch());

            // Get the information from the CronTrigger API object
            CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];

            // Verify the expressions are the same
            System.assertEquals(CRON_EXP, ct.CronExpression);

            // Verify the job has not run
            System.assertEquals(0, ct.TimesTriggered);
        Test.stopTest();
    }


    //test for actual batch methods
    static testMethod void testBatch_CRM_NPNRevTrgtAuto_Batch() {
    
        list<string> lstSObjects = new list<string>{'Account'};
        map<String, Id> mapRTNameId = Test_COMM_Factory.getAllRTsByName(lstSObjects);

        //Create a NPN Account Registry type of Account
        list<Account> lstNPNAccounts = new list<Account>();
        for (integer i = 0; i < 10; i++){
            Account accNPNRegUS = new Account(name = 'NPNAccountRegistryUS'+i, RecordTypeId = mapRTNameId.get(ACCOUNT_RT_NPN_ACCOUNT_REGISTRY), BillingStreet = 'street1', BillingCity = 'Santa Clara', BillingState = 'California', BillingCountry = BILLING_COUNTRY_US, BillingPostalCode = '95050', NPN_Program_Signed_Date__c = system.today() );
            lstNPNAccounts.add(accNPNRegUS);
        }
        insert lstNPNAccounts;
        
        
        //Create Country_List__c
        list<Country_List__c> lstCountry = new list<Country_List__c>();
        Country_List__c countryUS = new Country_List__c(name = BILLING_COUNTRY_US, ISO_Code__c = 'US', Region__c = 'NALA', Sub_Region__c = 'LA', Territory__c = 'LA'); 
        lstCountry.add(countryUS);
        insert lstCountry;
        
        //Create NPN_Revenue_Commitment_Master__c
        list<NPN_Revenue_Commitment_Master__c> lstRevCommitMstr = new list<NPN_Revenue_Commitment_Master__c>();
        NPN_Revenue_Commitment_Master__c RevCommitMstrUSACEL = new NPN_Revenue_Commitment_Master__c(Program__c = PA_PROGRAM_SP, Competency__c = PORTAL_COMPETENCY_AC, Level__c = PA_LEVEL_ELITE, Country__c = lstCountry[0].Id, Threshold__c = THRESHOLD_COMMIT_EL);
        lstRevCommitMstr.add(RevCommitMstrUSACEL);
        insert lstRevCommitMstr;
        
        //Create a Partner Attribute record
        list<Partner_Attribute__c> lstPA = new list<Partner_Attribute__c>();
        for (integer i = 0; i < 10; i++){
            Partner_Attribute__c paAccNPNRegUS = new Partner_Attribute__c(Account_Name__c = lstNPNAccounts[i].Id, Partner_Program_Name__c = PA_PROGRAM_SP, Partner_Competency__c = PORTAL_COMPETENCY_AC, Program_Level__c = PA_LEVEL_ELITE );
            lstPA.add(paAccNPNRegUS);
        }
        insert lstPA;
        
        //delete the Revenue Targets that gets created by Partner Attribute trigger
        list<NPN_Revenue_Targets__c> lstRevTrgts = [Select Id From NPN_Revenue_Targets__c Where Partner_Attribute__c = :lstPA];
        delete lstRevTrgts;
        
        
        //Start the actual test for batch class
        Test.startTest();
            CRM_NPNRevTrgtAuto_Batch batchCls = new CRM_NPNRevTrgtAuto_Batch();
            Database.executeBatch(batchCls);
        Test.stopTest();
        
        list<NPN_Revenue_Targets__c> lstRevTrgtsAfterStop = [Select Year__c, Minimum_Annual_Sales_Commitment__c From NPN_Revenue_Targets__c Where Partner_Attribute__c = :lstPA];
        system.debug('***lstRevTrgtsAfterStop: ' + lstRevTrgtsAfterStop);
        system.assert(lstRevTrgtsAfterStop.size() == 10);
        system.assert(lstRevTrgtsAfterStop[0].Minimum_Annual_Sales_Commitment__c == THRESHOLD_COMMIT_EL);
    }
}