force-app/main/default/objects/Account/fields/NPN_Program_Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>NPN_Program_Signed_Date__c</fullName>
    <inlineHelpText>NPN Program Signed Date</inlineHelpText>
    <label>NPN Agreement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Partner_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Partner_Number__c</fullName>
    <externalId>true</externalId>
    <label>SAP Partner Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/NPN_Account_Registry.recordType-meta.xml
<RecordType>
    <fullName>NPN_Account_Registry</fullName>
    <active>true</active>
    <label>NPN Account Registry</label>
</RecordType>

force-app/main/default/objects/Contact/fields/AddEditTempContactID__c.field-meta.xml
<CustomField>
    <fullName>AddEditTempContactID__c</fullName>
    <label>AddEditTempContactID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Community_User__c.field-meta.xml
<CustomField>
    <fullName>Community_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Community User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partner Primary Contact</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Service and Support</fullName>
            </value>
            <value>
                <fullName>RMA</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>MDF</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Renewals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner Contact</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account Id)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPN_Bulk_Contact_Request__c/NPN_Bulk_Contact_Request__c.object-meta.xml
<CustomObject>
    <description>The object stores the bulk contact requests raised by partner users through Manage Contacts tab on partner portal.</description>
    <label>NPN Bulk Contact Request</label>
    <nameField>
        <displayFormat>BCR-{00000}</displayFormat>
        <label>NPN Bulk Contact Request Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NPN Bulk Contact Request</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NPN_Bulk_Contact_Request__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>NPN Bulk Contact Requests</relationshipLabel>
    <relationshipName>NPN_Bulk_Contact_Request</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPN_Bulk_Contact_Request__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Requested By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>NPN_Bulk_Contact_Request</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPN_Bulk_Contact_Request__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/Partner_Attribute__c.object-meta.xml
<CustomObject>
    <description>NPN : Additional attributes to an account - program type, competency, level etc.</description>
    <label>Partner Attribute</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Attribute ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Attribute__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <inlineHelpText>Select account</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Attributes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Temporary_Contact__c/Temporary_Contact__c.object-meta.xml
<CustomObject>
    <description>NPN : Automate Onboarding DocuSign: This object stores the Key contacts template Data.</description>
    <label>Temporary Contact</label>
    <nameField>
        <label>Temporary_Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Temporary Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Temporary_Contact__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Temporary Contacts</relationshipLabel>
    <relationshipName>Temporary_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Temporary_Contact__c/fields/Action_Requested__c.field-meta.xml
<CustomField>
    <fullName>Action_Requested__c</fullName>
    <label>Action Requested</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temporary_Contact__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Temporary Contacts</relationshipLabel>
    <relationshipName>Temporary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Temporary_Contact__c/fields/Reason_for_Deactivation_Deletion__c.field-meta.xml
<CustomField>
    <fullName>Reason_for_Deactivation_Deletion__c</fullName>
    <label>Reason for Deactivation / Deletion</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Temporary_Contact__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Community user who requests for contact updates.</description>
    <label>Requested By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Temporary_Contacts_Requestors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Temporary_Contact__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Partner Primary Contact</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Service and Support</fullName>
            </value>
            <value>
                <fullName>RMA</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>MDF</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Renewals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Temporary_Contact__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Contact.Account.Name</formula>
    <label>Company Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NV_Test_ListContactExtension.cls
@isTest(seeAllData = false)
private class NV_Test_ListContactExtension {

    @TestSetup
    static void makeData(){
    
        Id accRecTypeId     = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('NPN_Account_Registry').getRecordTypeId();
        Id contactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Partner').getRecordTypeId();
        List<Account> testAccts = new List<Account>();
        List<Temporary_Contact__c> testTempContacts = new List<Temporary_Contact__c>();
        List<Partner_Attribute__c> testPartnerAttrb = new List<Partner_Attribute__c>();

        for(Integer i=0; i<2; i++) {
            testAccts.add(
                new Account(
                    Name                        = 'TestAcct'+i,
                    RecordTypeId                = accRecTypeId,
                    SAP_Partner_Number__c       = '45684'+i,
                    NPN_Program_Signed_Date__c  = Date.valueOf(System.today())
                    )
                );
        }
        insert testAccts;

        Contact contact1 = new Contact();
        contact1.FirstName      =   'partner';
        contact1.LastName       =   'one';
        contact1.Email          =   'nvpartnerone@foo.com';
        contact1.Phone          =   '789-978-5529';
        contact1.AccountId      =   testAccts[0].Id;
        contact1.Role__c        =   'Partner Primary Contact';
        contact1.RecordTypeId   =   contactRecTypeId;
        insert contact1;

        List<Profile> comntyProfileList = [SELECT Id FROM Profile WHERE Name = 'NPN Partner Community(LOGIN)'];
        User comUser = new User(
            LastName='one',
            Alias = 'tsale',
            Email = 'nvpartnerone@foo.com',
            Username = 'nvvippartnerone@foo.com.crqext',
            CommunityNickname = 'nvvippartnerone',
            ProfileId = comntyProfileList[0].Id,
            ContactId=contact1.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
            );
        insert comUser;

        // Create multiple temp contacts contacts

        List<Temporary_Contact__c> tempContactList = new List<Temporary_Contact__c>();
        for(Integer i=0; i<2; i++) {
            Temporary_Contact__c objTemporaryContact = new Temporary_Contact__c();
            objTemporaryContact.Account_ID__c = testAccts[0].Id;
            objTemporaryContact.Status__c = 'Pending';
            tempContactList.add(objTemporaryContact);
        }

        insert tempContactList;
        
        
        List<NPN_Bulk_Contact_Request__c> blkContactList = new List<NPN_Bulk_Contact_Request__c>();
        for(Integer i=0; i<2; i++) {
            String accId = testAccts[i].Id;
            for(Integer j=0; j<2; j++) {
                NPN_Bulk_Contact_Request__c objBlkContactReq = new NPN_Bulk_Contact_Request__c();
                objBlkContactReq.Account_Name__c = accId;
                objBlkContactReq.Status__c = 'Pending';
                objBlkContactReq.Requested_By__c = comUser.Id;
                blkContactList.add(objBlkContactReq);
            }
        }
        insert blkContactList;
    }

    @isTest
    static void methodOne(){
    
        Id contactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Partner').getRecordTypeId();
        List<Account> acctList = [SELECT Id FROM Account WHERE Name IN ('TestAcct1','TestAcct2')];

        Contact contact1 = new Contact();
        contact1.FirstName      =   'Jake';
        contact1.LastName       =   'Paul';
        contact1.Email          =   'jake.paul@abc.com';
        contact1.Phone          =   '789-978-5529';
        contact1.AccountId      =   acctList[0].Id;
        contact1.Role__c        =   'Sales';
        contact1.Title          =   'Sales Analyst';
        contact1.RecordTypeId   =   contactRecTypeId;
        insert contact1;

        User contextuser = [SELECT Id FROM User WHERE Username = 'nvvippartnerone@foo.com.crqext'];

        test.startTest();
        system.RunAs(contextuser){
            PageReference pageRef = Page.NV_ListPartnerContacts;
            Test.setCurrentPageReference(pageRef);
            NV_ListContactExtension controllerExt = new NV_ListContactExtension();
            pageRef.getParameters().put('contactId',contact1.Id);
            pageRef.getParameters().put('actionToPerform','Edit');
            controllerExt.getContacts();
            controllerExt.getTemporaryContacts();
            controllerExt.checkContactStatus();
            controllerExt.addContact();
            controllerExt.getBulkContactRequests();
        }
        test.stopTest();

    }

    @isTest
    static void methodTwo(){
    
        Id contactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Partner').getRecordTypeId();
        List<Account> acctList = [SELECT Id FROM Account WHERE Name IN ('TestAcct1','TestAcct2')];

        Contact contact1 = new Contact();
        contact1.FirstName      =   'Jake';
        contact1.LastName       =   'Paul';
        contact1.Email          =   'jake.paul@abcc.com';
        contact1.Phone          =   '789-978-5529';
        contact1.AccountId      =   acctList[0].Id;
        contact1.Role__c        =   'Technical';
        contact1.Title          =   'Lead';
        contact1.RecordTypeId   =   contactRecTypeId;
        insert contact1;

        Temporary_Contact__c objTemporaryContact = new Temporary_Contact__c();
        objTemporaryContact.First_Name__c = contact1.FirstName;
        objTemporaryContact.Last_Name__c = contact1.LastName;
        objTemporaryContact.Email__c = contact1.Email;
        objTemporaryContact.Phone__c = contact1.Phone;
        objTemporaryContact.Account_ID__c = acctList[0].Id;
        objTemporaryContact.Role__c = contact1.Role__c;
        objTemporaryContact.Title__c= contact1.Title;
        objTemporaryContact.Status__c = 'Completed';

        objTemporaryContact.Requested_By__c = UserInfo.getUserId();
        objTemporaryContact.OwnerId = UserInfo.getUserId();
        insert objTemporaryContact;

        contact1.AddEditTempContactID__c = objTemporaryContact.Id;
        update contact1;

        User contextuser = [SELECT Id FROM User WHERE Username = 'nvvippartnerone@foo.com.crqext'];

        test.startTest();
        system.RunAs(contextuser){
            PageReference pageRef = Page.NV_ListPartnerContacts;
            Test.setCurrentPageReference(pageRef);
            NV_ListContactExtension controllerExt = new NV_ListContactExtension();
            pageRef.getParameters().put('contactId',contact1.Id);
            pageRef.getParameters().put('actionToPerform','Delete');
            controllerExt.getContacts();
            controllerExt.getTemporaryContacts();
            controllerExt.getBulkContactRequests();
            controllerExt.checkContactStatus();
            controllerExt.closePopup();         
        }
        test.stopTest();

    }

    @isTest
    static void methodThree(){
    
        Id contactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Partner').getRecordTypeId();
        List<Account> acctList = [SELECT Id FROM Account WHERE Name IN ('TestAcct1','TestAcct2')];

        Contact contact1 = new Contact();
        contact1.FirstName      =   'Jake';
        contact1.LastName       =   'Paul';
        contact1.Email          =   'jake.paul@abcc.com';
        contact1.Phone          =   '789-978-5529';
        contact1.AccountId      =   acctList[0].Id;
        contact1.Role__c        =   'Technical';
        contact1.Title          =   'Lead';
        contact1.RecordTypeId   =   contactRecTypeId;
        insert contact1;

        List<Profile> comntyProfileList = [SELECT Id FROM Profile WHERE Name = 'NPN Partner Community(LOGIN)'];
        User contact1User = new User(
            LastName='one',
            Alias = 'tsale',
            Email = 'nvpartnerTwo@foo.com',
            Username = 'nvvippartnerTwo@foo.com.crqext',
            CommunityNickname = 'nvvippartnerTwo',
            ProfileId = comntyProfileList[0].Id,
            ContactId=contact1.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            IsActive = true
            );
        insert contact1User;

        Temporary_Contact__c objTemporaryContact = new Temporary_Contact__c();
        objTemporaryContact.First_Name__c = contact1.FirstName;
        objTemporaryContact.Last_Name__c = contact1.LastName;
        objTemporaryContact.Email__c = contact1.Email;
        objTemporaryContact.Phone__c = contact1.Phone;
        objTemporaryContact.Account_ID__c = acctList[0].Id;
        objTemporaryContact.Role__c = contact1.Role__c;
        objTemporaryContact.Title__c= contact1.Title;
        objTemporaryContact.Status__c = 'Completed';
        objTemporaryContact.Action_requested__c = 'Delete';
        objTemporaryContact.Reason_for_Deactivation_Deletion__c = 'Delete for testing';
        objTemporaryContact.ContactId__c = contact1.Id;
        objTemporaryContact.Requested_By__c = UserInfo.getUserId();
        objTemporaryContact.OwnerId = UserInfo.getUserId();
        insert objTemporaryContact;

        contact1.AddEditTempContactID__c = objTemporaryContact.Id;
        contact1.Community_User__c = contact1User.Id;
        update contact1;

        Contact con1 = [SELECT Id, Community_User__c, AddEditTempContactID__c FROM Contact WHERE Id = :contact1.Id];

        system.assertEquals(objTemporaryContact.Id, con1.AddEditTempContactID__c);
        system.assertEquals(contact1User.Id, con1.Community_User__c);

        User contextuser = [SELECT Id FROM User WHERE Username = 'nvvippartnerone@foo.com.crqext'];

        test.startTest();
        system.RunAs(contextuser){
            PageReference pageRef = Page.NV_ListPartnerContacts;
            Test.setCurrentPageReference(pageRef);
            NV_ListContactExtension controllerExt = new NV_ListContactExtension();
            pageRef.getParameters().put('contactId',contact1.Id);
            pageRef.getParameters().put('actionToPerform','Delete');
            controllerExt.getContacts();
            controllerExt.getTemporaryContacts();
            controllerExt.getBulkContactRequests();
            controllerExt.checkContactStatus();
            controllerExt.removeContact();          
        }
        test.stopTest();

    }

    @isTest
    static void methodFour(){
    
        Id contactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Partner').getRecordTypeId();
        List<Account> acctList = [SELECT Id FROM Account WHERE Name IN ('TestAcct1','TestAcct2')];

        Contact contact1 = new Contact();
        contact1.FirstName      =   'Jake';
        contact1.LastName       =   'Paul';
        contact1.Email          =   'jake.paul@abcc.com';
        contact1.Phone          =   '789-978-5529';
        contact1.AccountId      =   acctList[0].Id;
        contact1.Role__c        =   'Technical';
        contact1.Title          =   'Lead';
        contact1.RecordTypeId   =   contactRecTypeId;
        insert contact1;

        List<Profile> comntyProfileList = [SELECT Id FROM Profile WHERE Name = 'NPN Partner Community(LOGIN)'];
        User contact1User = new User(
            LastName='one',
            Alias = 'tsale',
            Email = 'nvpartnerTwo@foo.com',
            Username = 'nvvippartnerTwo@foo.com.crqext',
            CommunityNickname = 'nvvippartnerTwo',
            ProfileId = comntyProfileList[0].Id,
            ContactId=contact1.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US',
            IsActive = true
            );
        insert contact1User;

        Temporary_Contact__c objTemporaryContact = new Temporary_Contact__c();
        objTemporaryContact.First_Name__c = contact1.FirstName;
        objTemporaryContact.Last_Name__c = contact1.LastName;
        objTemporaryContact.Email__c = contact1.Email;
        objTemporaryContact.Phone__c = contact1.Phone;
        objTemporaryContact.Account_ID__c = acctList[0].Id;
        objTemporaryContact.Role__c = contact1.Role__c;
        objTemporaryContact.Title__c= contact1.Title;
        objTemporaryContact.Status__c = 'Pending';
        objTemporaryContact.Action_requested__c = 'Delete';
        objTemporaryContact.Reason_for_Deactivation_Deletion__c = 'Delete for testing';
        objTemporaryContact.ContactId__c = contact1.Id;
        objTemporaryContact.Requested_By__c = UserInfo.getUserId();
        objTemporaryContact.OwnerId = UserInfo.getUserId();
        insert objTemporaryContact;

        contact1.AddEditTempContactID__c = objTemporaryContact.Id;
        contact1.Community_User__c = contact1User.Id;
        update contact1;

        Contact con1 = [SELECT Id, Community_User__c, AddEditTempContactID__c FROM Contact WHERE Id = :contact1.Id];

        system.assertEquals(objTemporaryContact.Id, con1.AddEditTempContactID__c);
        system.assertEquals(contact1User.Id, con1.Community_User__c);

        User contextuser = [SELECT Id FROM User WHERE Username = 'nvvippartnerone@foo.com.crqext'];

        test.startTest();
        system.RunAs(contextuser){
            PageReference pageRef = Page.NV_ListPartnerContacts;
            Test.setCurrentPageReference(pageRef);
            NV_ListContactExtension controllerExt = new NV_ListContactExtension();
            controllerExt.resonForRemoval = 'Delete for testing';
            pageRef.getParameters().put('contactId',contact1.Id);
            pageRef.getParameters().put('actionToPerform','Delete');
            controllerExt.getContacts();
            controllerExt.getTemporaryContacts();
            controllerExt.getBulkContactRequests();
            controllerExt.checkContactStatus();
            controllerExt.removeContact();
        }
        test.stopTest();
    }

    @isTest
    static void methodFive(){

        List<Account> acctList = [SELECT Id FROM Account WHERE Name IN ('TestAcct1','TestAcct2')];

        User contextuser = [SELECT Id FROM User WHERE Username = 'nvvippartnerone@foo.com.crqext'];

        String parentId =acctList[0].Id;
        String attachmentId ='';
        String fileName ='acd.xlsx';
        String contentType ='';
        String base64BlobValue='w4lXJ8OqwrFBw6Vpw7Ukfg0pf0dWwoPCicOXw5bCqRsdc0pJa8Ouw7zD';

        String attachmentIdStr = NV_ListContactExtension.attachBlob(parentId,  attachmentId,  fileName,  contentType, base64BlobValue);
        system.assertNotEquals(null, attachmentIdStr);

        String sendEmailRet = NV_ListContactExtension.sendEmail(attachmentIdStr);

        system.assertEquals(null, sendEmailRet);

    }
}