force-app/main/default/objects/Account/fields/NPN_Program_Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>NPN_Program_Signed_Date__c</fullName>
    <inlineHelpText>NPN Program Signed Date</inlineHelpText>
    <label>NPN Agreement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/recordTypes/NPN_Account_Registry.recordType-meta.xml
<RecordType>
    <fullName>NPN_Account_Registry</fullName>
    <active>true</active>
    <label>NPN Account Registry</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Community_User__c.field-meta.xml
<CustomField>
    <fullName>Community_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Community User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partner Primary Contact</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Service and Support</fullName>
            </value>
            <value>
                <fullName>RMA</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>MDF</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Renewals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner Contact</label>
</RecordType>

force-app/main/default/objects/Lead/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account Id)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Program_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Level__c</fullName>
    <label>Approved Program Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/Partner_Attribute__c.object-meta.xml
<CustomObject>
    <description>NPN : Additional attributes to an account - program type, competency, level etc.</description>
    <label>Partner Attribute</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Attribute ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Attribute__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <inlineHelpText>Select account</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Attributes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Date_Competency_Signed__c.field-meta.xml
<CustomField>
    <fullName>Date_Competency_Signed__c</fullName>
    <label>Date Competency Signed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Competency__c.field-meta.xml
<CustomField>
    <fullName>Partner_Competency__c</fullName>
    <label>Partner Competency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Partner_Program_Name__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Compute</fullName>
            </value>
            <value>
                <fullName>Compute DGX</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
            <value>
                <fullName>Embedded Edge</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Virtualization</fullName>
            </value>
            <value>
                <fullName>Visualization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Program_Name__c</fullName>
    <label>Partner Program Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Solution Provider</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Tegra Embedded</fullName>
            </value>
            <value>
                <fullName>Services Subcontractor</fullName>
            </value>
            <value>
                <fullName>Cloud Service Provider</fullName>
            </value>
            <value>
                <fullName>Service Delivery Partner</fullName>
            </value>
            <value>
                <fullName>Solution Advisor</fullName>
            </value>
            <value>
                <fullName>Solutions Integration Partner</fullName>
            </value>
            <value>
                <fullName>Industry Focus</fullName>
            </value>
            <value>
                <fullName>Federal Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Global Systems Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Program_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Level__c</fullName>
    <description>Program Level</description>
    <inlineHelpText>Select the program level - Preferred or Elite</inlineHelpText>
    <label>Program Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Temporary_Contact__c/Temporary_Contact__c.object-meta.xml
<CustomObject>
    <description>NPN : Automate Onboarding DocuSign: This object stores the Key contacts template Data.</description>
    <label>Temporary Contact</label>
    <nameField>
        <label>Temporary_Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Temporary Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Temporary_Contact__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Temporary Contacts</relationshipLabel>
    <relationshipName>Temporary_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Temporary_Contact__c/fields/Action_Requested__c.field-meta.xml
<CustomField>
    <fullName>Action_Requested__c</fullName>
    <label>Action Requested</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Temporary_Contact__c/fields/ContactId__c.field-meta.xml
<CustomField>
    <fullName>ContactId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Temporary Contacts</relationshipLabel>
    <relationshipName>Temporary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Temporary_Contact__c/fields/Partner_User__c.field-meta.xml
<CustomField>
    <fullName>Partner_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Temporary_Contact</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Temporary_Contact__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Partner Primary Contact</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Service and Support</fullName>
            </value>
            <value>
                <fullName>RMA</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>MDF</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Renewals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Temporary_Contact__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/User/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <formula>Contact.Account.Name</formula>
    <label>Company Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NPN_Test_TempContactHelper.cls
@isTest(seeAllData=false)
private class NPN_Test_TempContactHelper {

    @testSetup static void setup() {

        NV_NPN_TestDataFactory.setupCustomSettings();
        
        Id accRecTypeId     = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('NPN_Account_Registry').getRecordTypeId();
        Id contactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Partner').getRecordTypeId();
        List<Account> testAccts = new List<Account>();
        List<Temporary_Contact__c> testTempContacts = new List<Temporary_Contact__c>();
        List<Partner_Attribute__c> testPartnerAttrb = new List<Partner_Attribute__c>();

        Id profileId = [SELECT Id FROM Profile WHERE Name = :COMM_Constants.PROF_PP_TPP_GENERIC LIMIT 1].Id;
        for(Integer i=0; i<2; i++) {
            testAccts.add(
                new Account(
                    Name                        = 'TestAcct'+i,
                    RecordTypeId                = accRecTypeId,
                    NPN_Program_Signed_Date__c  = Date.valueOf(System.today())
                    )
                );
        }
        insert testAccts;


        testPartnerAttrb.add(
            new Partner_Attribute__c(
                Account_Name__c             = testAccts[0].id,
                Partner_Competency__c       = COMM_Constants.TEST_PORTAL_COMPETENCY_GV,
                Partner_Program_Name__c     = COMM_Constants.PA_PROGRAM_SP,
                Program_Level__c            = COMM_Constants.PA_LEVEL_PREF,
                Date_Competency_Signed__c   = Date.valueOf(system.today())
                )
            );

        testPartnerAttrb.add(
            new Partner_Attribute__c(
                Account_Name__c             = testAccts[0].id,
                Partner_Competency__c       = COMM_Constants.TEST_PORTAL_COMPETENCY_DL,
                Partner_Program_Name__c     = COMM_Constants.PA_PROGRAM_SA,
                Program_Level__c            = COMM_Constants.PA_LEVEL_PREF,
                Date_Competency_Signed__c   = Date.valueOf(system.today())
                )
            );

        testPartnerAttrb.add(
            new Partner_Attribute__c(
                Account_Name__c             = testAccts[1].id,
                Partner_Competency__c       = COMM_Constants.TEST_PORTAL_COMPETENCY_GV,
                Partner_Program_Name__c     = COMM_Constants.PA_PROGRAM_SA,
                Program_Level__c            = COMM_Constants.PA_LEVEL_PREF,
                Date_Competency_Signed__c   = Date.valueOf(system.today())
                )
            );

        testPartnerAttrb.add(
            new Partner_Attribute__c(
                Account_Name__c             = testAccts[1].id,
                Partner_Competency__c       = COMM_Constants.TEST_PORTAL_COMPETENCY_AC,
                Partner_Program_Name__c     = COMM_Constants.PA_PROGRAM_SA,
                Program_Level__c            = COMM_Constants.PA_LEVEL_PREF,
                Date_Competency_Signed__c   = Date.valueOf(system.today())
                )
            );

        insert testPartnerAttrb;
        
        Contact contact1 = new Contact();
        contact1.FirstName      =   'Jake';
        contact1.LastName       =   'Paul';
        contact1.Email          =   'jake.paul@abc.com';
        contact1.Phone          =   '789-978-5529';
        contact1.AccountId      =   testAccts[1].Id;
        contact1.Role__c        =   'Sales';
        contact1.Title          =   'Sales Analyst';
        contact1.RecordTypeId   =   contactRecTypeId;
        insert contact1;

        User commUsr = new User();
        commUsr.FirstName           =   'Jake';
        commUsr.LastName            =   'Paul';
        commUsr.Email               =   'jake.paul@abc.com';
        commUsr.Phone               =   '789-978-5529';
        commUsr.Alias               =   'jliv';
        commUsr.Username            =   'jake.paul@abc.com.community';
        commUsr.ProfileId           =   profileId;
        commUsr.TimeZoneSidKey      =   'GMT';
        commUsr.LanguageLocaleKey   =   'en_US';
        commUsr.EmailEncodingKey    =   'UTF-8';
        commUsr.LocaleSidKey        =   'en_US';
        commUsr.ContactId           =   contact1.Id;
        commUsr.IsActive            =   true;
        insert commUsr;

        contact1.Community_User__c  =  commUsr.Id;
        update contact1;

        Temporary_Contact__c temp = new Temporary_Contact__c();
        temp.First_Name__c  =   'John';
        temp.Last_Name__c   =   'Doe';
        temp.Email__c       =   'john.doe@abc.com';
        temp.Phone__c       =   '789-978-5569';
        temp.Account_Id__c  =   testAccts[0].Id;
        temp.Role__c        =   'Technical';
        temp.Title__c       =   'Lead analyst';
        testTempContacts.add(temp);

        Temporary_Contact__c temp1 = new Temporary_Contact__c();
        temp1.First_Name__c     =   'Jake';
        temp1.Last_Name__c      =   'Paul';
        temp1.Email__c          =   'jake.paul@abc.com';
        temp1.Phone__c          =   '789-978-5522';
        temp1.Account_Id__c     =   testAccts[1].Id;
        temp1.Role__c           =   'Sales';
        temp1.Title__c          =   'Sales Analyst';
        temp1.ContactId__c      =   contact1.Id;
        temp.Partner_User__c    =   contact1.Community_User__c;
        testTempContacts.add(temp1);

        insert testTempContacts;
    }

    @isTest static void newContactReqTest() {

        Map<Id,Temporary_Contact__c> tempContacts = new Map<Id, Temporary_Contact__c> ([SELECT Id, Status__c FROM Temporary_Contact__c]);

        system.assertEquals(2,tempContacts.size());

        Test.startTest();
        for(Temporary_Contact__c tc : tempContacts.values()) {
            tc.Status__c = 'Completed';
            tc.Action_Requested__c  = 'New';
        }

        update tempContacts.values();
        Test.stopTest();
        system.assertEquals('Completed',tempContacts.values()[0].Status__c);
    }

    @isTest static void updateRequestTest() {

        Map<Id,Temporary_Contact__c> tempContacts = new Map<Id, Temporary_Contact__c> ([SELECT Id, Status__c FROM Temporary_Contact__c]);
        system.assertEquals(2, tempContacts.size());

        Test.startTest();
        for(Temporary_Contact__c tc : tempContacts.values()) {
            tc.Role__c = 'Partner Primary Contact; Technical';
            tc.Status__c = 'Completed';
            tc.Action_Requested__c  = 'Update - (Role)';
        }
        update tempContacts.values();
        Test.stopTest();
        system.assertEquals('Completed',tempContacts.values()[0].Status__c);
    }

    @isTest static void newContactReqRejectedtTest() {

        Map<Id,Temporary_Contact__c> tempContacts = new Map<Id, Temporary_Contact__c> ([SELECT Id, Status__c FROM Temporary_Contact__c]);
        system.assertEquals(2, tempContacts.size());

        Test.startTest();
        for(Temporary_Contact__c tc : tempContacts.values()) {
            tc.Status__c = 'Rejected';
            tc.Action_Requested__c  = 'Update - (Role)';
        }
        update tempContacts.values();
        Test.stopTest();
        system.assertEquals('Rejected',tempContacts.values()[0].Status__c);
    }

    @isTest static void ContactDisableReqTest() {

        Map<Id,Temporary_Contact__c> tempContacts = new Map<Id, Temporary_Contact__c> ([SELECT Id, Status__c FROM Temporary_Contact__c]);
        system.assertEquals(2, tempContacts.size());

        Test.startTest();
        for(Temporary_Contact__c tc : tempContacts.values()) {
            tc.Status__c = 'Completed';
            tc.Action_Requested__c = 'Deactivate';
        }
        update tempContacts.values();
        Test.stopTest();
        system.assertEquals('Completed',tempContacts.values()[0].Status__c);
        system.assertEquals('Deactivate',tempContacts.values()[0].Action_Requested__c);
    }
}