force-app/main/default/objects/Account/fields/NPN_Program_Signed_Date__c.field-meta.xml
<CustomField>
    <fullName>NPN_Program_Signed_Date__c</fullName>
    <inlineHelpText>NPN Program Signed Date</inlineHelpText>
    <label>NPN Agreement Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Partner_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Partner_Number__c</fullName>
    <externalId>true</externalId>
    <label>SAP Partner Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/NPN_Account_Registry.recordType-meta.xml
<RecordType>
    <fullName>NPN_Account_Registry</fullName>
    <active>true</active>
    <label>NPN Account Registry</label>
</RecordType>

force-app/main/default/objects/Contact/fields/AddEditTempContactID__c.field-meta.xml
<CustomField>
    <fullName>AddEditTempContactID__c</fullName>
    <label>AddEditTempContactID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Partner Primary Contact</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Service and Support</fullName>
            </value>
            <value>
                <fullName>RMA</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>MDF</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Renewals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner Contact</label>
</RecordType>

force-app/main/default/objects/Partner_Attribute__c/Partner_Attribute__c.object-meta.xml
<CustomObject>
    <description>NPN : Additional attributes to an account - program type, competency, level etc.</description>
    <label>Partner Attribute</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Attribute ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Temporary_Contact__c/Temporary_Contact__c.object-meta.xml
<CustomObject>
    <description>NPN : Automate Onboarding DocuSign: This object stores the Key contacts template Data.</description>
    <label>Temporary Contact</label>
    <nameField>
        <label>Temporary_Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Temporary Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Temporary_Contact__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Temporary Contacts</relationshipLabel>
    <relationshipName>Temporary_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Temporary_Contact__c/fields/Requested_By__c.field-meta.xml
<CustomField>
    <fullName>Requested_By__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Community user who requests for contact updates.</description>
    <label>Requested By</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Temporary_Contacts_Requestors</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Temporary_Contact__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Partner Primary Contact</fullName>
            </value>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Service and Support</fullName>
            </value>
            <value>
                <fullName>RMA</fullName>
            </value>
            <value>
                <fullName>POS</fullName>
            </value>
            <value>
                <fullName>MDF</fullName>
            </value>
            <value>
                <fullName>Compliance</fullName>
            </value>
            <value>
                <fullName>Renewals</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Temporary_Contact__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NV_Test_AddEditContactController.cls
@isTest(seeAllData = false)
private class NV_Test_AddEditContactController {

    @TestSetup
    static void makeData(){
        
        Id accRecTypeId     = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('NPN_Account_Registry').getRecordTypeId();
        Id contactRecTypeId = Schema.SObjectType.Contact.getRecordTypeInfosByDeveloperName().get('Partner').getRecordTypeId();
        List<Account> testAccts = new List<Account>();
        List<Temporary_Contact__c> testTempContacts = new List<Temporary_Contact__c>();
        List<Partner_Attribute__c> testPartnerAttrb = new List<Partner_Attribute__c>();

        for(Integer i=0; i<2; i++) {
            testAccts.add(
                new Account(
                    Name                        = 'TestAcct'+i,
                    RecordTypeId                = accRecTypeId,
                    SAP_Partner_Number__c       = '45684'+i,
                    NPN_Program_Signed_Date__c  = Date.valueOf(System.today())
                    )
                );
        }
        insert testAccts;

        Contact contact1 = new Contact();
        contact1.FirstName      =   'partner';
        contact1.LastName       =   'one';
        contact1.Email          =   'nvpartnerone@foo.com';
        contact1.Phone          =   '789-978-5529';
        contact1.AccountId      =   testAccts[0].Id;
        contact1.Role__c        =   'Partner Primary Contact';
        insert contact1;

        List<Profile> comntyProfileList = [SELECT Id FROM Profile WHERE Name = 'NPN Partner Community(LOGIN)'];
        User comUser = new User(
            LastName='one',
            Alias = 'tsale',
            Email = 'nvpartnerone@foo.com',
            Username = 'nvvippartnerone@foo.com.crqext',
            CommunityNickname = 'nvvippartnerone',
            ProfileId = comntyProfileList[0].Id,
            ContactId=contact1.Id,
            TimeZoneSidKey = 'America/Los_Angeles',
            LocaleSidKey = 'en_US',
            EmailEncodingKey = 'UTF-8',
            LanguageLocaleKey = 'en_US'
            );
        insert comUser;
    }

    @isTest static void methodOne(){

        List<Account> acctList = [SELECT Id FROM Account WHERE Name IN ('TestAcct1','TestAcct2')];

        Contact contact1 = new Contact();
        contact1.FirstName      =   'Jake';
        contact1.LastName       =   'Paul';
        contact1.Email          =   'jake.paul@abc.com';
        contact1.Phone          =   '789-978-5529';
        contact1.AccountId      =   acctList[0].Id;
        contact1.Role__c        =   'Sales';
        contact1.Title          =   'Sales Analyst';
        //insert contact1;

        User contextuser = [SELECT Id FROM User WHERE Username = 'nvvippartnerone@foo.com.crqext'];

        test.startTest();
        system.RunAs(contextuser){
            PageReference pageRef = Page.NV_AddEditContact;
            Test.setCurrentPageReference(pageRef);
            NV_AddEditContactController controllerExt = new NV_AddEditContactController( new ApexPages.StandardController(contact1));
            controllerExt.saveContact();
        }
        test.stopTest();
    }

    @isTest static void methodTwo(){

        List<Account> acctList = [SELECT Id FROM Account WHERE Name IN ('TestAcct1','TestAcct2')];

        Contact contact1 = new Contact();
        contact1.FirstName      =   'Andy';
        contact1.LastName       =   'P';
        contact1.Email          =   'andy.paul@abc.com';
        contact1.Phone          =   '789-978-5529';
        contact1.AccountId      =   acctList[0].Id;
        contact1.Role__c        =   'Parter Primary Contact';
        contact1.Title          =   'Sales Analyst';
        insert contact1;

        contact1.FirstName = 'Andrew';
        contact1.LastName = 'Paul';
        contact1.Role__c = 'Technical';
        contact1.Phone   = '485-978-5529';
        contact1.Title   = 'Sales Analyst';

        User contextuser = [SELECT Id FROM User WHERE Username = 'nvvippartnerone@foo.com.crqext'];

        test.startTest();
        system.RunAs(contextuser){
            PageReference pageRef = Page.NV_AddEditContact;
            Test.setCurrentPageReference(pageRef);
            NV_AddEditContactController controllerExt = new NV_AddEditContactController( new ApexPages.StandardController(contact1));
            controllerExt.saveContact();
            controllerExt.getSelect();
            controllerExt.getDeselect();
            controllerExt.getDeselectedValues();
            controllerExt.getDeselectedValues();
        }
        test.stopTest();
    }

    @isTest static void methodThree(){

        List<Account> acctList = [SELECT Id FROM Account WHERE Name IN ('TestAcct1','TestAcct2')];

        Contact contact1 = new Contact();
        contact1.FirstName      =   'Andy';
        contact1.LastName       =   'Paul';
        contact1.Email          =   'andy.paul@abc.com';
        contact1.Phone          =   '789-978-5529';
        contact1.AccountId      =   acctList[0].Id;
        contact1.Role__c        =   'RMA';
        contact1.Title          =   'Sales Analyst';
        insert contact1;

        Temporary_Contact__c objTemporaryContact = new Temporary_Contact__c();
        objTemporaryContact.First_Name__c = contact1.FirstName;
        objTemporaryContact.Last_Name__c = contact1.LastName;
        objTemporaryContact.Email__c = contact1.Email;
        objTemporaryContact.Phone__c = contact1.Phone;
        objTemporaryContact.Account_ID__c = acctList[0].Id;
        objTemporaryContact.Role__c = contact1.Role__c;
        objTemporaryContact.Title__c= contact1.Title;
        objTemporaryContact.Status__c = 'Completed';
        objTemporaryContact.Requested_By__c = UserInfo.getUserId();
        objTemporaryContact.OwnerId = UserInfo.getUserId();
        insert objTemporaryContact;

        contact1.AddEditTempContactID__c = objTemporaryContact.Id;
        update contact1;

        contact1.FirstName = 'Andrew';
        contact1.LastName = 'Paul';
        contact1.Role__c = 'Technical';
        contact1.Phone   = '485-978-5529';
        contact1.Title   = 'Analyst';

        User contextuser = [SELECT Id FROM User WHERE Username = 'nvvippartnerone@foo.com.crqext'];

        test.startTest();
        system.RunAs(contextuser){
            PageReference pageRef = Page.NV_AddEditContact;
            Test.setCurrentPageReference(pageRef);
            NV_AddEditContactController controllerExt = new NV_AddEditContactController( new ApexPages.StandardController(contact1));
            controllerExt.saveContact();
            controllerExt.getSelect();
            controllerExt.getDeselect();
            controllerExt.getDeselectedValues();
            controllerExt.getSelectedValues();
        }
        test.stopTest();
    }

    @isTest static void cancelTest(){
        List<Account> acctList = [SELECT Id FROM Account WHERE Name IN ('TestAcct1','TestAcct2')];

        Contact contact1 = new Contact();
        contact1.FirstName      =   'Jake';
        contact1.LastName       =   'Paul';
        contact1.Email          =   'nvpartnerone@foo.com';
        contact1.Phone          =   '789-978-5529';
        contact1.AccountId      =   acctList[0].Id;
        contact1.Role__c        =   'Sales';
        contact1.Title          =   'Analyst';


        User contextuser = [SELECT Id FROM User WHERE Username = 'nvvippartnerone@foo.com.crqext'];

        test.startTest();
        system.RunAs(contextuser){
            PageReference pageRef = Page.NV_AddEditContact;
            Test.setCurrentPageReference(pageRef);
            NV_AddEditContactController controllerExt = new NV_AddEditContactController( new ApexPages.StandardController(contact1));
            controllerExt.cancelContact();
        }
        test.stopTest();
    }

    @isTest static void exceptionTest(){
    
        List<Account> acctList = [SELECT Id FROM Account WHERE Name IN ('TestAcct1','TestAcct2')];

        Contact contact1 = new Contact();
        contact1.FirstName      =   'Jake';
        contact1.LastName       =   'Paul';
        contact1.Email          =   'nvpartnerone@foo.com';
        contact1.Phone          =   '789-978-5529';
        contact1.AccountId      =   acctList[0].Id;
        contact1.Role__c        =   'Sales';
        contact1.Title          =   'Analyst';


        User contextuser = [SELECT Id FROM User WHERE Username = 'nvvippartnerone@foo.com.crqext'];

        test.startTest();
        system.RunAs(contextuser){
            PageReference pageRef = Page.NV_AddEditContact;
            Test.setCurrentPageReference(pageRef);
            NV_AddEditContactController controllerExt = new NV_AddEditContactController( new ApexPages.StandardController(contact1));
            controllerExt.saveContact();
        }
        test.stopTest();
    }
}