force-app/main/default/objects/Account/fields/Product_Lines__c.field-meta.xml
<CustomField>
    <fullName>Product_Lines__c</fullName>
    <description>This field rolls up Product Lines from Entitlements.</description>
    <inlineHelpText>Product Lines based on Active Entitlements.</inlineHelpText>
    <label>Product Lines</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Service_Cloud_Error_Log__c/Service_Cloud_Error_Log__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : Error Logs - Stores all integration errors</description>
    <label>Service Cloud Error Log</label>
    <nameField>
        <displayFormat>Err-{000}</displayFormat>
        <label>Service Cloud Error Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Service Cloud Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Cloud_Error_Log__c/fields/Functionality_Name__c.field-meta.xml
<CustomField>
    <fullName>Functionality_Name__c</fullName>
    <label>Functionality Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Service_Cloud_Error_Log__c/fields/Record_URL__c.field-meta.xml
<CustomField>
    <fullName>Record_URL__c</fullName>
    <label>Record URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Product_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Automotive Datacenter</fullName>
    </customValue>
    <customValue>
        <fullName>DGX</fullName>
    </customValue>
    <customValue>
        <fullName>DRIVE Constellation</fullName>
    </customValue>
    <customValue>
        <fullName>Educational Services</fullName>
    </customValue>
    <customValue>
        <fullName>Embedded</fullName>
    </customValue>
    <customValue>
        <fullName>GeForce</fullName>
    </customValue>
    <customValue>
        <fullName>Grid</fullName>
    </customValue>
    <customValue>
        <fullName>HPC SDK</fullName>
    </customValue>
    <customValue>
        <fullName>NGC-Ready Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Parabricks</fullName>
    </customValue>
    <customValue>
        <fullName>Premium Support Services</fullName>
    </customValue>
    <customValue>
        <fullName>Quadro</fullName>
    </customValue>
    <customValue>
        <fullName>RTX Blade Server</fullName>
    </customValue>
    <customValue>
        <fullName>Tesla</fullName>
    </customValue>
    <customValue>
        <fullName>vGaming</fullName>
    </customValue>
    <description>This picklist is created to host various Product Lines which can be used at Account, Entitlement, Product and Case level.</description>
    <masterLabel>Product Line</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/ESP_RollupProductLinesOnAccount_BAT.cls
/*
Service Cloud : Update Product Lines on Account
The Batch is responsible to rollup "Product Lines" from Entitlement to Account.

* Akhilesh: 07/24/2019: Created.
Pending Action Items: Use Common Log function
*/
public class ESP_RollupProductLinesOnAccount_BAT implements Database.Batchable<sObject>{
    
    private DateTime LookBackFromDt;
    private DateTime LookBackToDt;
    private String query;
    
    public ESP_RollupProductLinesOnAccount_BAT() {
        LookBackFromDt = DateTime.Now().addDays(-1);
        LookBackToDt   = DateTime.Now();
    }
    public ESP_RollupProductLinesOnAccount_BAT(String strQuery) {
        query = strQuery;
    }
    public ESP_RollupProductLinesOnAccount_BAT(DateTime sDate, DateTime eDate) {
        LookBackToDt   = (eDate != null) ? eDate : DateTime.Now();
        LookBackFromDt = (sDate != null) ? sDate : LookBackToDt.addDays(-1);
    }
    
    //lastmodifieddate > yesterday
    public Database.QueryLocator start(Database.BatchableContext bc) {
        //String LookBackFromDate = LookBackFromDt.year()+'/'+LookBackFromDt.month()+'/'+LookBackFromDt.day();
        //Date LookBackToDate = date.newinstance(LookBackToDt.year(), LookBackToDt.month(), LookBackToDt.day());
        
        if(query == null || query == '')
            query = 'select Id from Account'
            +' where Id in (select AccountId from Entitlement'
            +' where (EndDate >= '+ LookBackFromDt.format('yyyy-MM-dd') + ' AND EndDate <= '+ LookBackToDt.format('yyyy-MM-dd') +') '
            +'OR (lastmodifieddate >= ' +LookBackFromDt.format('yyyy-MM-dd HH:mm:ss.SSSZ').replaceAll(' ', 'T') + ' AND lastmodifieddate <= '+LookBackToDt.format('yyyy-MM-dd HH:mm:ss.SSSZ').replaceAll(' ', 'T')+')'
            +' ) '
            ;
        system.debug('query: '+ query);
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        try{
            system.debug('execute BC: '+ BC);
            List<Account> accList = scope;
            system.debug('execute accList: '+ accList);
            if(!accList.isEmpty()) {
                for(Account acc : accList) {
                    set<String> prodLineSet = ESP_Utility.FindProductLinesForCustomer(acc.Id);
                    
                    Service_Cloud_Error_Log__c sl = new Service_Cloud_Error_Log__c();
                    sl.Record_URL__c = ''+accList;
                    sl.Functionality_Name__c = 'Batch_UpdateProductLinesOnAccount';
                    sl.Error_Type__c = 'Success';
                    sl.Error_Description__c = 'AccountID: '+ acc.Id + 'ProductLines: '+ prodLineSet;
                    insert sl;
                    
                    acc.Product_Lines__c = string.join(new list<string>(prodLineSet), ';');
                    system.debug('ProductLines: '+ acc.Product_Lines__c);
                }
            }
            update accList;
            
        }catch (Exception ex) {
            Service_Cloud_Error_Log__c sl = new Service_Cloud_Error_Log__c();
            sl.Record_URL__c = ''+scope;
            sl.Functionality_Name__c = 'ESP_RollupProductLinesOnAccount_BAT';
            sl.Error_Type__c = 'Failure';
            sl.Error_Code__c = 'ESP_RollupProductLinesOnAccount_BAT';
            sl.Error_Description__c = 'ESP_RollupProductLinesOnAccount_BAT : ' + ex.getMessage() + 'Stack Trace: ' + ex.getStackTraceString();
            insert sl;
            //system.debug('Exception: '+ ex.getMessage());
            //ESP_Utility.LogErrors('ESP_RollupProductLinesOnAccount_BAT : ' + ex.getMessage(), ex.getStackTraceString());
        }
    }
    
    public void finish(Database.BatchableContext BC) {
        system.debug('finish BC: '+ BC);
        AsyncApexJob job = [SELECT Id, Status, NumberOfErrors, ExtendedStatus, MethodName, JobItemsProcessed, TotalJobItems, CreatedBy.Email
                                FROM AsyncApexJob
                                WHERE Id = :bc.getJobId()];
                                
        ESP_Utility.LogErrors('ESP_RollupProductLinesOnAccount_BAT', job.Id + ' ' +job.Status + 'BatchJobMethodName: '+job.MethodName +' NumberOfErrors : ' + job.NumberOfErrors + ' Error Details: '+ job.ExtendedStatus);
    }
}