force-app/main/default/objects/Account/fields/Product_Lines__c.field-meta.xml
<CustomField>
    <fullName>Product_Lines__c</fullName>
    <description>This field rolls up Product Lines from Entitlements.</description>
    <inlineHelpText>Product Lines based on Active Entitlements.</inlineHelpText>
    <label>Product Lines</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Line</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/fields/Product_Lines__c.field-meta.xml
<CustomField>
    <fullName>Product_Lines__c</fullName>
    <formula>IF( INCLUDES( Account.Product_Lines__c,&quot;Automotive&quot;),&quot;Automotive;&quot; , &quot;&quot;) 
&amp;
IF( INCLUDES( Account.Product_Lines__c,&quot;Automotive Datacenter&quot;),&quot;Automotive Datacenter;&quot; , &quot;&quot;) 
&amp;
IF( INCLUDES( Account.Product_Lines__c,&quot;DGX&quot;),&quot;DGX;&quot; , &quot;&quot;) 
&amp;
IF( INCLUDES( Account.Product_Lines__c,&quot;DRIVE Constellation&quot;),&quot;DRIVE Constellation;&quot; , &quot;&quot;) 
&amp;
IF( INCLUDES( Account.Product_Lines__c,&quot;Embedded&quot;),&quot;Embedded;&quot; , &quot;&quot;) 
&amp;
IF( INCLUDES( Account.Product_Lines__c,&quot;GeForce&quot;),&quot;GeForce;&quot; , &quot;&quot;) 
&amp;
IF( INCLUDES( Account.Product_Lines__c,&quot;Grid&quot;),&quot;Grid;&quot; , &quot;&quot;) 
&amp;
IF( INCLUDES( Account.Product_Lines__c,&quot;NGC-Ready Systems&quot;),&quot;NGC-Ready Systems;&quot; , &quot;&quot;) 
&amp;
IF( INCLUDES( Account.Product_Lines__c,&quot;Quadro&quot;),&quot;Quadro;&quot; , &quot;&quot;) 
&amp;
IF( INCLUDES( Account.Product_Lines__c,&quot;RTX Blade Server&quot;),&quot;RTX Blade Server;&quot; , &quot;&quot;) 
&amp;
IF( INCLUDES( Account.Product_Lines__c,&quot;Tesla&quot;),&quot;Tesla;&quot; , &quot;&quot;)</formula>
    <label>Product Lines</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tesla</fullName>
            </value>
            <value>
                <fullName>vGPU</fullName>
            </value>
            <value>
                <fullName>Quadro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner Contact</label>
</RecordType>

force-app/main/default/objects/Contract/fields/SAP_PAK_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_PAK_ID__c</fullName>
    <label>SAP PAK ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Hardware_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Hardware_Serial_Number__c</fullName>
    <label>Hardware Serial Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZOR</fullName>
            </value>
            <value>
                <fullName>ZSO</fullName>
            </value>
            <value>
                <fullName>ZMRS</fullName>
            </value>
            <value>
                <fullName>ZRMA</fullName>
            </value>
            <value>
                <fullName>ZDO</fullName>
            </value>
            <value>
                <fullName>ZKB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Entitlement/fields/PAK_ID__c.field-meta.xml
<CustomField>
    <fullName>PAK_ID__c</fullName>
    <label>PAK ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Created for backend purposes only.</description>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Renewed_PAK_ID__c.field-meta.xml
<CustomField>
    <fullName>Renewed_PAK_ID__c</fullName>
    <description>Rename this to Renewed PAK ID if CPQ decides to use both PAK ID and Renewed PAK ID in future. Right now, CPQ is not populating any values in PAK ID.</description>
    <label>Renewed PAK ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/SAP_Order__c.field-meta.xml
<CustomField>
    <fullName>SAP_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SAP Order</label>
    <referenceTo>SAP_Order__c</referenceTo>
    <relationshipLabel>Entitlements</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Service_Product__c.field-meta.xml
<CustomField>
    <fullName>Service_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is created to store Product lookup copied from Subscription or manually entered for MRS Products.</description>
    <label>Service Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Entitlements (Service Product)</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Entitlements</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Type__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Automotive Datacenter</fullName>
            </value>
            <value>
                <fullName>CMP</fullName>
            </value>
            <value>
                <fullName>DC GPU</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
            <value>
                <fullName>Educational Services</fullName>
            </value>
            <value>
                <fullName>Fleet Command</fullName>
            </value>
            <value>
                <fullName>GeForce</fullName>
            </value>
            <value>
                <fullName>Grid</fullName>
            </value>
            <value>
                <fullName>Grid Hardware</fullName>
            </value>
            <value>
                <fullName>HPC SDK</fullName>
            </value>
            <value>
                <fullName>Jetson</fullName>
            </value>
            <value>
                <fullName>NGC-Ready Services</fullName>
            </value>
            <value>
                <fullName>Parabricks</fullName>
            </value>
            <value>
                <fullName>ProViz</fullName>
            </value>
            <value>
                <fullName>RTX</fullName>
            </value>
            <value>
                <fullName>RTX Blade Server</fullName>
            </value>
            <value>
                <fullName>Titan</fullName>
            </value>
            <value>
                <fullName>Value-Added Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Spares</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAP_Order__c/SAP_Order__c.object-meta.xml
<CustomObject>
    <description>CPQ : Captures SAP Orders from SAP/EMS through integration</description>
    <label>SAP Order</label>
    <nameField>
        <label>SAP Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP_Order__c/fields/Hardware_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Hardware_Serial_Number__c</fullName>
    <label>Hardware Serial Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <description>ZOR - Standard, ZSO - Sample, ZMRS - MRS Internal, ZRMA - Return</description>
    <inlineHelpText>ZOR - Standard, ZSO - Sample, ZMRS - MRS Internal, ZRMA - Return</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZOR</fullName>
            </value>
            <value>
                <fullName>ZSO</fullName>
            </value>
            <value>
                <fullName>ZMRS</fullName>
            </value>
            <value>
                <fullName>ZRMA</fullName>
            </value>
            <value>
                <fullName>ZDO</fullName>
            </value>
            <value>
                <fullName>ZKB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>SAP Orders</relationshipLabel>
    <relationshipName>SAP_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/Product_SKU__c.field-meta.xml
<CustomField>
    <fullName>Product_SKU__c</fullName>
    <label>Product SKU</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/Renewed_PAK_ID__c.field-meta.xml
<CustomField>
    <fullName>Renewed_PAK_ID__c</fullName>
    <label>Renewed PAK ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/SAP_Account__c.field-meta.xml
<CustomField>
    <fullName>SAP_Account__c</fullName>
    <label>SAP Account</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/SAP_PAK_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_PAK_ID__c</fullName>
    <label>SAP PAK ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/SAP_Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sales_Order_Number__c</fullName>
    <label>SAP Sales Order Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/SFDC_Account__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SFDC Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SAP Orders</relationshipLabel>
    <relationshipName>SAP_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/Sold_To_Partner__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Partner__c</fullName>
    <label>Sold To Partner</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/Sold_To_Partner_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Partner_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To Partner Lookup</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SAP Orders (Sold To Partner Lookup)</relationshipLabel>
    <relationshipName>SAP_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/globalValueSets/Product_Line.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Automotive</fullName>
    </customValue>
    <customValue>
        <fullName>Automotive Datacenter</fullName>
    </customValue>
    <customValue>
        <fullName>DGX</fullName>
    </customValue>
    <customValue>
        <fullName>DRIVE Constellation</fullName>
    </customValue>
    <customValue>
        <fullName>Educational Services</fullName>
    </customValue>
    <customValue>
        <fullName>Embedded</fullName>
    </customValue>
    <customValue>
        <fullName>GeForce</fullName>
    </customValue>
    <customValue>
        <fullName>Grid</fullName>
    </customValue>
    <customValue>
        <fullName>HPC SDK</fullName>
    </customValue>
    <customValue>
        <fullName>NGC-Ready Systems</fullName>
    </customValue>
    <customValue>
        <fullName>Parabricks</fullName>
    </customValue>
    <customValue>
        <fullName>Premium Support Services</fullName>
    </customValue>
    <customValue>
        <fullName>Quadro</fullName>
    </customValue>
    <customValue>
        <fullName>RTX Blade Server</fullName>
    </customValue>
    <customValue>
        <fullName>Tesla</fullName>
    </customValue>
    <customValue>
        <fullName>vGaming</fullName>
    </customValue>
    <description>This picklist is created to host various Product Lines which can be used at Account, Entitlement, Product and Case level.</description>
    <masterLabel>Product Line</masterLabel>
    <sorted>true</sorted>
</GlobalValueSet>

force-app/main/default/classes/ESP_LinkSAPOrderToEntitlements_BAT_test.cls
@isTest
public with sharing class ESP_LinkSAPOrderToEntitlements_BAT_test {
    
    public static final string Name = 'ESP_LinkSAPOrderToEntitlements_BAT_test';
    @testSetup 
    static void setup() {
        //Create product
        Product2 product 		= Test_COMM_Factory.getProduct('Test Product');
        product.Product_Type__c = 'Hardware';
        product.Product_Line__c = 'DGX';
        product.ProductCode 	= 'PRD001';
        product.IsActive 		= true;
        insert product;
        
        //Account creation
        Account acc = Test_COMM_Factory.getAccount(Name);
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = :COMM_Constants.SOBJECT_ACCOUNT AND  Name = :COMM_Constants.ACCOUNT_RT_NEW_CUSTOMER];
        acc.RecordTypeId = rt.Id;
        insert acc;
        
        //Contract creation
        Contract contract = Test_COMM_Factory.getContract(acc.Id);
        insert contract;
        
        //Activate contract
        contract.Status = 'Activated';
        update contract;
        
        //Create SAP Order, with Order Type, Account, Partner, Soldto
        SAP_Order__c ord 	= new SAP_Order__c();
        ord.Order_Type__c 	= 'ZOR';
        ord.Start_Date__c 	= date.today();
        ord.End_Date__c 	= date.today().addYears(3);
        ord.SAP_PAK_ID__c 	= '12345';
        ord.Quantity__c 	= 3;
        ord.Renewed_PAK_ID__c = 'PAK234';
        ord.Sold_To_Partner__c = 'SAPAcc001';
        //ord.Sold_To_Partner_Lookup__c = acc.Id;
        ord.SAP_Sales_Order_Number__c = '111';
        ord.Hardware_Serial_Number__c = 'Serial111';
        SAPOrder_tgr_cls.skipTriggerActions = true;
        //ord.SAP_Account__c	= 'SAPAcc001';
        ord.SFDC_Account__c = acc.Id;
        ord.Product_SKU__c 	= 'PRD001';
        ord.Product__c		= product.Id;
        insert ord;
        
        
        //Subscription creation
        SBQQ__Subscription__c subscription1 = Test_COMM_Factory.getSubscription(acc.Id, product.Id, contract.Id);
        subscription1.Hardware_Serial_Number__c = 'Serial111';
        subscription1.SAP_Order__c = ord.Id;
        insert subscription1;
        
        //create subscription and entitlement manually
        SBQQ__Subscription__c subscription2 = Test_COMM_Factory.getSubscription(acc.Id, product.Id, contract.Id);
        subscription2.Hardware_Serial_Number__c = 'Serial111';
        insert subscription2;
        
        
        //Create Entitlement - 
        Entitlement Ent 				= Test_COMM_Factory.getEntitlement('Test Ent', acc.Id);
        Ent.Hardware_Serial_Number__c 	= 'Serial111';
        Ent.PAK_ID__c 					= '12345';
        Ent.Service_product__c 			= product.Id;
        Ent.EndDate 					= Date.today();
        Ent.StartDate 					= Date.today().addDays(-1);
        Ent.Subscription__c				= subscription1.Id;
        
        insert Ent;
        
        Entitlement Ent2 				= Test_COMM_Factory.getEntitlement('Test Ent', acc.Id);
        Ent2.Hardware_Serial_Number__c 	= 'Serial111';
        Ent2.PAK_ID__c 					= '12345';
        Ent2.Service_product__c 		= product.Id;
        Ent2.EndDate 					= Date.today();
        Ent2.StartDate 					= Date.today().addDays(-1);
        Ent2.Subscription__c			= subscription2.Id;
        
        insert Ent2;
        //Create Contact
        //Contact cont = Test_COMM_Factory.getContact(acc.Id);
        //system.assertNotEquals(Null, cont.AccountId);
        //insert cont;
    }
    
    @isTest
    static void testESP_LinkSAPOrderToEntitlements_BAT_sch() { 
        Test.startTest();
            ESP_LinkSAPOrderToEntitlements_BAT_SCH sh = new ESP_LinkSAPOrderToEntitlements_BAT_SCH();
            String sch = '0 0 23 * * ?'; 
            sh.iBatchSize = 2;
            system.schedule('Test Territory Check', sch, sh); 
        Test.stopTest();
    }
    
    @isTest
    static void testESP_LinkSAPOrderToEntitlements_BAT() { 
        Test.startTest();
        DateTime LookBackFromDt = DateTime.Now().addDays(-5);
        DateTime LookBackToDt   = DateTime.Now().addDays(0);
        
        Id batchJobId = Database.executeBatch(new ESP_LinkSAPOrderToEntitlements_BAT(), 2);
        system.debug('batchJobId: '+ batchJobId);
        
        //batchJobId = Database.executeBatch(new ESP_LinkSAPOrderToEntitlements_BAT(LookBackFromDt, LookBackToDt), 1);
        //system.debug('batchJobId: '+ batchJobId);
        
       // batchJobId = Database.executeBatch(new ESP_LinkSAPOrderToEntitlements_BAT('select Id from Account'), 1);
        //system.debug('batchJobId: '+ batchJobId);
        
        //batchJobId = Database.executeBatch(new ESP_LinkSAPOrderToEntitlements_BAT('select Id from Contact'), 1);
        //system.debug('batchJobId: '+ batchJobId);
        
        Test.stopTest();
        
        //System assertion for DGX
        //Account acc1 = [select Product_Lines__c from account where name = 'Test Account'];
        //system.assertequals('DGX',acc1.product_lines__c);
    }
}