force-app/main/default/objects/Account/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <defaultValue>&apos;2100&apos;</defaultValue>
    <label>Sales Organization</label>
    <length>4</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Account/fields/SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>SAP Customer Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_NPN_OEM_ODM_Disti__c.field-meta.xml
<CustomField>
    <fullName>Primary_NPN_OEM_ODM_Disti__c</fullName>
    <businessOwnerUser>oweber@nvidia.com.trprod</businessOwnerUser>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SOQ-79

5/24/2021 Geo Update: Updated help text. Added admin field information like Data Owner.</description>
    <inlineHelpText>Please identify the partner who will issue the PO to NVIDIA</inlineHelpText>
    <label>Primary NPN OEM/ODM/Disti</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Please make sure to only select those Accounts marked as business engagement layer partner Accounts</errorMessage>
        <filterItems>
            <field>Account.Business_Engagement_Relationship__c</field>
            <operation>equals</operation>
            <value>Distributor, ODM, OEM</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (Primary NPN OEM/ODM/Disti)</relationshipLabel>
    <relationshipName>PartnerOpportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/Generate_Email__c.field-meta.xml
<CustomField>
    <fullName>Generate_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Submit Sales Order Creation Request Email to Order Management Team</description>
    <inlineHelpText>Submit Sales Order Creation Request Email to Order Management Team</inlineHelpText>
    <label>Submit SO Request</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Order/fields/New_EC_Contact_SAP_Number__c.field-meta.xml
<CustomField>
    <fullName>New_EC_Contact_SAP_Number__c</fullName>
    <formula>TEXT(VALUE(IF( Use_Quote_EC_Account_Info__c ,   SBQQ__Quote__r.End_Customer_Contact__r.SAP_Contact_ID__c ,  New_EC_Contact_Lookup__r.SAP_Contact_ID__c  )))</formula>
    <label>EC Contact SAP Number (Entitlement Org)</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/New_End_Customer_Account_Lookup__c.field-meta.xml
<CustomField>
    <fullName>New_End_Customer_Account_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>New End Customer Account for Order Fulfillment</description>
    <label>End Customer Account (Entitlement Org)</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Orders</relationshipLabel>
    <relationshipName>Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order/fields/PO_Amount__c.field-meta.xml
<CustomField>
    <fullName>PO_Amount__c</fullName>
    <label>PO Amount</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/PO_Customer_Requested_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_Customer_Requested_Date__c</fullName>
    <label>PO Customer Requested Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/PO_Date__c.field-meta.xml
<CustomField>
    <fullName>PO_Date__c</fullName>
    <description>PO Customer Requested Date</description>
    <inlineHelpText>PO Customer Requested Date</inlineHelpText>
    <label>PO Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Order/fields/Reseller_Contact_SAP_Number__c.field-meta.xml
<CustomField>
    <fullName>Reseller_Contact_SAP_Number__c</fullName>
    <formula>TEXT(VALUE(SBQQ__Quote__r.Reseller_Contact__r.SAP_Contact_ID__c))</formula>
    <label>Reseller Contact SAP Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Reseller_SAP_Number__c.field-meta.xml
<CustomField>
    <fullName>Reseller_SAP_Number__c</fullName>
    <formula>TEXT(VALUE(SBQQ__Quote__r.Reseller_Account__r.SAP_Customer_Number__c))</formula>
    <label>Reseller SAP Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Sales_Organization__c.field-meta.xml
<CustomField>
    <fullName>Sales_Organization__c</fullName>
    <description>Sales Organization used for order booking in SAP</description>
    <inlineHelpText>2100 - US Sales Org
3300 - SG Sales Org</inlineHelpText>
    <label>Sales Organization</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>2100</fullName>
            </value>
            <value>
                <fullName>3300</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Order/fields/SOQ_Order_CC_Emails__c.field-meta.xml
<CustomField>
    <fullName>SOQ_Order_CC_Emails__c</fullName>
    <formula>&apos;CPQITSupport@nvidia.com,jrando@nvidia.com&apos;</formula>
    <label>SOQ_Order_CC_Emails</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/SOQ_Order_To_Emails__c.field-meta.xml
<CustomField>
    <fullName>SOQ_Order_To_Emails__c</fullName>
    <formula>IF(  NOT(ISPICKVAL(Opportunity.Region__c,&apos;JAPAN&apos;)) , &apos;SOQ-POUS@exchange.nvidia.com&apos;, &apos;SOQ-POJP@exchange.nvidia.com&apos;)</formula>
    <label>SOQ_Order_To_Emails</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Order/fields/Total_Amount_of_CPQ_Products__c.field-meta.xml
<CustomField>
    <fullName>Total_Amount_of_CPQ_Products__c</fullName>
    <description>SOQ: Total Amount of NV Branded Products for PO validation</description>
    <inlineHelpText>Total Amount of NV Branded Products from Quote</inlineHelpText>
    <label>Total Amount of NV Branded Products</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order/fields/Use_Quote_EC_Account_Info__c.field-meta.xml
<CustomField>
    <fullName>Use_Quote_EC_Account_Info__c</fullName>
    <defaultValue>true</defaultValue>
    <inlineHelpText>Check flag if End Customer on Quote and PO are the same. If not, populate PO End Customer Information.</inlineHelpText>
    <label>Use Quote EC Account Info</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/SubmitToSapController.cls
public with sharing class SubmitToSapController {

    public Order objOrder {get; set;}
    public static Boolean disable {get;set;}
    public static String strResult {get; set;}

    public SubmitToSapController(ApexPages.StandardController stdController) {
        objOrder = (Order)stdController.getRecord();
    }

    public void SubmitOrderFromVF() {
        /*RenewalOrderToSAP objROToSAP = new RenewalOrderToSAP ();
        strResult = objROToSAP.SubmitOrder(objOrder.Id,false);*/
        strResult = RenewalOrderToSAP.submitOrder(objOrder.Id,false);
    }
    
    
    public void SubmitInitialSORequest() {
        list<Order> OrderList = [select id, LastModifiedById ,OrderNumber, SBQQ__Quote__c, Generate_Email__c, New_EC_Contact_SAP_Number__c, PO_Amount__c, PO_Customer_Requested_Date__c, PO_Date__c, Purchase_Order_Number__c, Sales_Organization__c, Total_Amount_of_CPQ_Products__c, SOQ_Order_To_Emails__c, SOQ_Order_CC_Emails__c, LastModifiedBy.Email, Opportunity.Owner.Email, Account.Owner.Email,SBQQ__Quote__r.Primary_NPN_OEM_ODM_Disti__c,SBQQ__Quote__r.Primary_NPN_OEM_ODM_Disti__r.Owner.Email,SBQQ__Quote__r.SBQQ__Account__c,New_End_Customer_Account_Lookup__r.SAP_Customer_Number__c ,Reseller_SAP_Number__c,Reseller_Contact_SAP_Number__c,Use_Quote_EC_Account_Info__c from order where id=: objOrder.id];
        
        //OrderTriggerClass.sendEmailfromVF(OrderList);
         List<Id> lstConDocIds = new List<Id>();
         List<Order> lstEmailOrders = new List<Order>();
         List<Id> lstConVerIds = new List<Id>();
         List<Id> lstOrderIds = new List<Id>();
         List<Id> lstQuoteIds = new List<Id>();
         List<Id> lstQuoteIds2 = new List<Id>();
         map<Id, ContentDocumentLink> OrderContentDocumentMap = new map<Id, ContentDocumentLink>();
         map<Id, ContentVersion> ContentDocumentVersionMap = new map<Id, ContentVersion>();
         map<Id, List<Id>> ContentDocumentVersionListMap = new map<Id, List<Id>>();
         map<Id, id> QuoteOrderMap = new map<Id, Id>();
        map<Id, Double> OrderAmountMap = new map<Id, Double>();
         Messaging.SingleEmailMessage mail = new Messaging.SingleEmailMessage();
    
        for(order ordx : OrderList){
            lstQuoteIds2.add(ordx.SBQQ__Quote__c);
            QuoteOrderMap.put(ordx.SBQQ__Quote__c,ordx.Id);
                ordx.EffectiveDate = system.today();
                lstOrderIds.add(ordx.Id);
                lstQuoteIds.add(ordx.SBQQ__Quote__c);
                lstEmailOrders.add(ordx);
                //QuoteAmountMap.put(ordx.SBQQ__Quote__c,0.00);
                ordx.Generate_Email__c = false;
        }
    
        if(lstQuoteIds2.size()>0){
                //Double CPQTotal=0;
                    for(SBQQ__Quote__c SBQuote : [select id,Total_Amount_of_CPQ_Products__c  from SBQQ__Quote__c  WHERE id =: lstQuoteIds2]){
                           
                        OrderAmountMap.put(QuoteOrderMap.get(SBQuote.id),SBQuote.Total_Amount_of_CPQ_Products__c);    
                        system.debug('--------OrderAmountMap-----'+OrderAmountMap);
                        }
            } 
    
        for(order ordz : OrderList){
            
            ordz.Total_Amount_of_CPQ_Products__c = OrderAmountMap.get(ordz.id);
            
        }
    
        Set<Id> OrderSet = new Set<Id>(lstOrderIds);
        if(OrderSet.size()>0){
            List<ContentDocumentLink> ContentDocumentLinks = [select ContentDocumentId,id, LinkedEntityId from ContentDocumentLink where LinkedEntityId IN : OrderSet AND ContentDocumentId != null];
            Set<Id> contentDocIds = new Set<Id>();
            EmailTemplate ETemp = [select id, DeveloperName  from EmailTemplate where DeveloperName='SOQ_New_Order_Email' limit 1];
            ID TemplateId = ETemp.Id;
            for(ContentDocumentLink conDoc : ContentDocumentLinks) {
                    lstConDocIds.add(conDoc.ContentDocumentId);
                OrderContentDocumentMap.put(conDoc.LinkedEntityId,conDoc);
            }
            
            system.debug('>>>>>>>>>lstConDocIds>>>>>'+ lstConDocIds);
            
            for(ContentVersion conVer : [SELECT Id, ContentDocumentId FROM ContentVersion WHERE ContentDocumentId =: lstConDocIds]){
               lstConVerIds.add(conVer.Id);
               ContentDocumentVersionMap.put(conVer.ContentDocumentId,conVer);
                ContentDocumentVersionListMap.put(conVer.ContentDocumentId,lstConVerIds);
            }
            system.debug('>>>>>>>>>lstConVerIds>>>>>'+ lstConVerIds);
            
            
    
        for(order ordy : OrderList){
            
            ordy.Total_Amount_of_CPQ_Products__c = OrderAmountMap.get(ordy.id);
            
            system.debug('--------ordy.SOQ_Order_To_Emails__c--------'+ordy.SOQ_Order_To_Emails__c);
            list<String> ToEmails = ordy.SOQ_Order_To_Emails__c.split(',');
            list<String> CCEmails = ordy.SOQ_Order_CC_Emails__c.split(',');
            CCEmails.add(ordy.LastModifiedBy.Email);
            CCEmails.add(ordy.Opportunity.Owner.Email);
            CCEmails.add(ordy.Account.Owner.Email);
            if(ordy.SBQQ__Quote__r.Primary_NPN_OEM_ODM_Disti__r.Owner.Email !=null)
            CCEmails.add(ordy.SBQQ__Quote__r.Primary_NPN_OEM_ODM_Disti__r.Owner.Email);
            //LastModifiedBy.Email, Opportunity.Owner.Email, Account.Owner.Email
            system.debug('-------UserInfo------'+ UserInfo.getUserId());
            
            mail.setTemplateId(TemplateId);    
            //mail.setTargetObjectId(UserInfo.getUserId()); 
            mail.setTargetObjectId(ordy.LastModifiedById); 
            mail.setToAddresses(ToEmails); 
            //mail.setToAddresses(new List<String>{'vgattamaneni@nvidia.com','messayas@nvidia.com','dheerajs@nvidia.com'}); 
            mail.setCcAddresses(CCEmails);
            mail.setBccAddresses(new List<String>{'vgattamaneni@nvidia.com'});    
            mail.setSaveAsActivity(false); 
             Boolean RelatedCustomer = True;
              system.debug('---RelatedCustomer11---'+RelatedCustomer);
              system.debug('---xxxx---'+ordy.Use_Quote_EC_Account_Info__c);
              
             if(ordy.Use_Quote_EC_Account_Info__c==False){
              system.debug('---RelatedCustomer22---'+RelatedCustomer);
                 id accid = OrderTriggerClass.GetTopLevelAccount(ordy.SBQQ__Quote__r.SBQQ__Account__c);
                 system.debug('----top----'+accid);
                 List<Account> ls= [Select id, name,SAP_Customer_Number__c, parentId from Account where id =:accid];
                 string allcustomer = OrderTriggerClass.getHierarchies(ls);
                 if(allcustomer.contains(ordy.New_End_Customer_Account_Lookup__r.SAP_Customer_Number__c)){ system.debug('---RelatedCustomer33---'+RelatedCustomer);
                 }else{RelatedCustomer = False; system.debug('---RelatedCustomer33-2---'+RelatedCustomer);}
             }
             system.debug('---RelatedCustomer44---'+RelatedCustomer);
             if(!RelatedCustomer){
             	 ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Order Fulfillment End Customer Account is not related to the Customer on Quote.'));
             }else if(ordy.Purchase_Order_Number__c== null || ordy.PO_Amount__c == null  || ordy.PO_Date__c== null ){
                 ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Purchase Order #, PO Date and PO Amount are required.'));
             }else if(ordy.Reseller_SAP_Number__c== null || ordy.Reseller_Contact_SAP_Number__c == null  || ordy.New_EC_Contact_SAP_Number__c== null ){
                 ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Reseller, Reseller Contact and End Customer Contact are required to submit the order. Please fill the details on Quote.'));
             }else if(ordy.Total_Amount_of_CPQ_Products__c != ordy.PO_Amount__c){
                 ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'Order Amount is not matching with the PO Amount.'));
             }else If(ContentDocumentVersionListMap.size()>0){
                    ordy.status='Submitted';
                    mail.setEntityAttachments(ContentDocumentVersionListMap.get(OrderContentDocumentMap.get(ordy.id).ContentDocumentId) );
                    mail.setWhatId(ordy.id);
                    Messaging.sendEmail(new Messaging.SingleEmailMessage[] { mail });
                    OrderTriggerClass.SyncQuotes(lstQuoteIds);
                    Update ordy;
                        
             }else{
                    ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, 'No PO attachment on the Order, Add Attachment before selecting Submit SO Request.'));
                }
           
        }
         
            
        }    
        
    
    }
}