force-app/main/default/objects/Account/fields/SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>SAP Customer Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/PartnerAccount.recordType-meta.xml
<RecordType>
    <fullName>PartnerAccount</fullName>
    <active>true</active>
    <label>Partner Account</label>
</RecordType>

force-app/main/default/objects/Contract/fields/NPN_Solution_Provider_VAR__c.field-meta.xml
<CustomField>
    <fullName>NPN_Solution_Provider_VAR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NPN Solution Provider/VAR</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contracts</relationshipLabel>
    <relationshipName>Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DR_Deal_Status__c.field-meta.xml
<CustomField>
    <fullName>DR_Deal_Status__c</fullName>
    <formula>IF( TEXT(Type) =   $Setup.DR_Settings__c.Lead_Type__c, 
IF(DR_Is_Deal_Auto_Terminated__c  = True, $Setup.DR_Settings__c.Deal_Status_AutoTerminated__c, 
	IF (DR_Is_Terminated__c = True, $Setup.DR_Settings__c.Deal_Status_Terminated__c,
		IF (DR_Is_180Days_Extn_Approved__c = True, $Setup.DR_Settings__c.Deal_Status_ExtensionApproved__c,
			IF (DR_Is_180Days_Extn_Rejected__c = True, $Setup.DR_Settings__c.Deal_Status_ExtensionApproved__c,
				IF (DR_Is_Submitted_For_180Days_Extn__c = True, $Setup.DR_Settings__c.Deal_Status_ExtensionApproved__c,
					IF(DR_Is_Extension_Approved__c = True, $Setup.DR_Settings__c.Deal_Status_ExtensionApproved__c,
						IF(DR_Is_Extension_Rejected__c = True, $Setup.DR_Settings__c.Deal_Status_ExtensionRejected__c,
							IF(DR_Is_Submitted_For_Extension__c = True, $Setup.DR_Settings__c.Deal_Status_ExtensionApprovalInProgress__c,
								IF (DR_Is_Approved__c = True, $Setup.DR_Settings__c.Deal_Status_Approved__c,
									IF (DR_Is_Rejected__c = True, $Setup.DR_Settings__c.Deal_Status_Rejected__c,
										IF (DR_Is_Submitted_For_Approval__c = True, $Setup.DR_Settings__c.Deal_Status_ApprovalInProgress__c, $Setup.DR_Settings__c.Deal_Status_NotSubmitted__c)
									)
								)
							)
						)
					)
				)	
			)	
		)	
	)
)
, IF(CONTAINS( $Setup.DR_Settings__c.Deal_Reg_Record_Types__c, RecordType.Name), &quot;Non-Deal Reg&quot;, &quot;Not Applicable&quot;)
)</formula>
    <label>Registration Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DR_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>DR_Expiration_Date__c</fullName>
    <description>Calculated field. If Admin Expiration Override, then DR_Expiration_Date_Admin_Override else Expiration Date is based on either Approved Date + Extn Duration (if Extn approved) or Approved Date + 90</description>
    <formula>If ( !ISNULL(DR_Expiration_Date_Admin_Override__c), DR_Expiration_Date_Admin_Override__c, 
If ( (!ISNULL(DR_Extension_Approved_Date__c) &amp;&amp; DR_Is_Extension_Approved__c &amp;&amp; !ISBLANK(TEXT(DR_Extn_Duration__c))), DATEVALUE(DR_Approved_Date__c) + 90 + VALUE(TEXT(DR_Extn_Duration__c)), 
If ( (!ISNULL(DR_Extension_Approved_Date__c) &amp;&amp; DR_Is_Extension_Approved__c &amp;&amp; ISBLANK(TEXT(DR_Extn_Duration__c))), DATEVALUE(DR_Approved_Date__c) + 180,
If ( (!ISNULL(DR_Approved_Date__c) &amp;&amp; DR_Is_Approved__c), DATEVALUE(DR_Approved_Date__c) + 90, null) 
) 
)
)</formula>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NPN_Solution_Provider_VAR__c.field-meta.xml
<CustomField>
    <fullName>NPN_Solution_Provider_VAR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NPN Solution Provider/VAR that applies to this specific opportunity.</description>
    <inlineHelpText>Select the NPN Solution Provider/VAR that applies to this specific opportunity.  This should represent the tier 2 partner involved with the deal.</inlineHelpText>
    <label>NPN Solution Provider/VAR</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>Account.NPN_Active_Program_Competency__c</field>
            <operation>contains</operation>
            <value>Solution Provider, Solutions Integration Partner</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>SW &amp; Service Renewals</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Deal Registration</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (NPN Solution Provider (VAR))</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>O-{000000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Base_SKU__c.field-meta.xml
<CustomField>
    <fullName>Base_SKU__c</fullName>
    <description>Opp Reg &gt; SAP integration; shows the Base SKU from the underlying Product</description>
    <formula>PricebookEntry.Product2.Base_SKU__c</formula>
    <inlineHelpText>Opp Reg &gt; SAP integration; shows the Base SKU from the underlying Product</inlineHelpText>
    <label>Base SKU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Opp_Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Opp_Line_Number__c</fullName>
    <displayFormat>OLI-{000000}</displayFormat>
    <label>Opp Line Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>Opp Reg &gt; SAP integration; shows the Term from the underlying Product</description>
    <formula>PricebookEntry.Product2.Term__c</formula>
    <inlineHelpText>Opp Reg &gt; SAP integration; shows the Term from the underlying Product</inlineHelpText>
    <label>Term</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_RenewalOpportunityCleanupBatchClass.cls
/*
    Test class for RenewalOpportunityCleanupBatchClass
    
 */
@isTest(SeeAllData=False)
Public class Test_RenewalOpportunityCleanupBatchClass{

    /*
    private static final string OPPTY_RT_SWRenewal = 'SW & Service Renewals';
    private static final string ProdName = 'DGX Station V100-32GB';
    private static final string ProdCode = 'DGXDLStation32GB';
    private static final string ProdFamily = 'DGX Station Product Family';
    private static final string PriceBookName = 'OppReg Price Book';
    private static final string BaseSKU = '920-22587-2511';
    private static final string Term = '12';
    private static final string NPNVAR_SAPCustomerNumber = '0000800111';
    private static final string PEC_SAPCustomerNumber = '000900111';
    
    @isTest static void RenewalOppTest1() {
    //static testmethod void RenewalOppTest1() {
        map<string, Object> mapOpptyInfa = Test_COMM_Factory.setEnterpriseOpptyInfra(ProdName, ProdCode, ProdFamily,true, PriceBookName, 1000, 1500, BaseSKU, Term);
        Account partnerAccount = mapOpptyInfa.get('partneraccount') != null ? (Account) mapOpptyInfa.get('partneraccount') : new Account();
        Contact partnerContact = mapOpptyInfa.get('partnercontact') != null ? (Contact) mapOpptyInfa.get('partnercontact') : new Contact();
        Account customerAccount = mapOpptyInfa.get('customeraccount') != null ? (Account) mapOpptyInfa.get('customeraccount') : new Account();
        User partnerUser = mapOpptyInfa.get('partneruser') != null ? (User) mapOpptyInfa.get('partneruser') : new User();
        User pbm = mapOpptyInfa.get('pbm') != null ? (User) mapOpptyInfa.get('pbm') : new User();
        User pbmmanager = mapOpptyInfa.get('pbmmanager') != null ? (User) mapOpptyInfa.get('pbmmanager') : new User();
        User salesopsadmin = mapOpptyInfa.get('salesopsadmin') != null ? (User) mapOpptyInfa.get('salesopsadmin') : new User();
        PricebookEntry pricebookentryRecord = mapOpptyInfa.get('pricebookentry') != null ? (pricebookentry) mapOpptyInfa.get('pricebookentry') : new PricebookEntry();
        map<string, Id> mapProfNameId = mapOpptyInfa.get('mapprofnameid') != null ? (map<string, id>) mapOpptyInfa.get('mapprofnameid') : new map<string, Id>();
        map<String, Id> mapRTNameId = mapOpptyInfa.get('maprectypenameid') != null ? (map<string, Id>) mapOpptyInfa.get('maprectypenameid') : new map<string, Id>();
        
        Opportunity SWRenewals;
        ApexPages.Standardcontroller stdCon;
        
        User currUser = [Select Id From User where Id = :userinfo.getUserId()];
        
        system.debug('***currUser: ' + currUser);
        
        list<Account> lstAccount = new list<Account>(); 
        system.runAs(currUser){
            customerAccount.SAP_Customer_Number__c = PEC_SAPCustomerNumber;
            partnerAccount.SAP_Customer_Number__c = NPNVAR_SAPCustomerNumber;
            lstAccount.add(customerAccount);
            lstAccount.add(partnerAccount);
            update lstAccount;
            
            //createRenewalOpportunity(string name, Id recordTypeId, string stageName, Date closeDate, Id pricebook2Id, Id customerAccountId, Id partnerAccountId){
            SWRenewals = Test_COMM_Factory.createDealRegOpportunity('Service RenewalsOpp1', mapRTNameId.get(OPPTY_RT_SWRenewal), COMM_Constants.OPPTY_STAGE_PROSPECTING, System.Today(), pricebookentryRecord.PriceBook2Id, customerAccount.Id, partnerAccount.Id);
      
            //Test_COMM_Factory.setDealRegFieldsInOpportunity(SWRenewals.Id, customerAccount.Id, partnerAccount.Id);
        
            //Add Opportunity Line Items
            //OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = SWRenewals.Id, PricebookEntryId = pricebookentryRecord.Id, Quantity = 4, UnitPrice = pricebookentryRecord.UnitPrice);
            //insert oli;
            
            //Samar : Added contract test record and associate it with oppty
            Contract contract       = new Contract();
            contract.AccountId      = lstAccount[0].Id;
            contract.Status         = 'Draft';
            contract.StartDate      = Date.today();
            contract.SBQQ__RenewalOpportunity__c = SWRenewals.Id;
            insert contract;
            
            SWRenewals.SBQQ__RenewedContract__c = contract.Id;
            Update SWRenewals;
        }
        
        SWRenewals = [Select Id, Opportunity_Number__c, NPN_Solution_Provider_VAR__r.SAP_Customer_Number__c, 
                                                DR_Expiration_Date__c, DR_Deal_Status__c, Account.SAP_Customer_Number__c,  SBQQ__RenewedContract__c , 
                                                (Select Opp_Line_Number__c, Base_SKU__c, Term__c, Quantity From OpportunityLineItems) 
                                From Opportunity
                                Where Id = :SWRenewals.Id                                         
                                ];
        
        system.debug('****enterpriseSalesOppty: ' + SWRenewals);
        
        list<Opportunity> lstOppReg = new list<Opportunity>();
        lstOppReg.add(SWRenewals);
            
        //run as to avoid MIXED DML
        system.runAs(currUser){
            Test.startTest();
            
            //Schedule Batch Class
            RenewalOpportunityCleanupBatchClass schBatch = new RenewalOpportunityCleanupBatchClass(); 
            String schTime = '0 0 8 * * ?';  // Daily at 8 AM
            //system.schedule('Test check', schTime, schBatch); 
            Database.ExecuteBatch(schBatch);
            Test.stopTest();
        }
        
     } 
        
        */
        
    @isTest static void RenewalOppTest2() {
    
    
        Test.startTest();
            
            //Schedule Batch Class
            RenewalOpportunityCleanupBatchClass schBatch = new RenewalOpportunityCleanupBatchClass(); 
            //String schTime = '0 0 8 * * ?';  // Daily at 8 AM
            //system.schedule('Test check', schTime, schBatch); 
            //Database.ExecuteBatch(schBatch);
            schBatch.CoverageMethod();
        Test.stopTest();

    
    }        
  
}