force-app/main/default/objects/Account/fields/SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>SAP Customer Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/PartnerAccount.recordType-meta.xml
<RecordType>
    <fullName>PartnerAccount</fullName>
    <active>true</active>
    <label>Partner Account</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/DR_Deal_Status__c.field-meta.xml
<CustomField>
    <fullName>DR_Deal_Status__c</fullName>
    <formula>IF( TEXT(Type) =   $Setup.DR_Settings__c.Lead_Type__c, 
IF(DR_Is_Deal_Auto_Terminated__c  = True, $Setup.DR_Settings__c.Deal_Status_AutoTerminated__c, 
	IF (DR_Is_Terminated__c = True, $Setup.DR_Settings__c.Deal_Status_Terminated__c,
		IF (DR_Is_180Days_Extn_Approved__c = True, $Setup.DR_Settings__c.Deal_Status_ExtensionApproved__c,
			IF (DR_Is_180Days_Extn_Rejected__c = True, $Setup.DR_Settings__c.Deal_Status_ExtensionApproved__c,
				IF (DR_Is_Submitted_For_180Days_Extn__c = True, $Setup.DR_Settings__c.Deal_Status_ExtensionApproved__c,
					IF(DR_Is_Extension_Approved__c = True, $Setup.DR_Settings__c.Deal_Status_ExtensionApproved__c,
						IF(DR_Is_Extension_Rejected__c = True, $Setup.DR_Settings__c.Deal_Status_ExtensionRejected__c,
							IF(DR_Is_Submitted_For_Extension__c = True, $Setup.DR_Settings__c.Deal_Status_ExtensionApprovalInProgress__c,
								IF (DR_Is_Approved__c = True, $Setup.DR_Settings__c.Deal_Status_Approved__c,
									IF (DR_Is_Rejected__c = True, $Setup.DR_Settings__c.Deal_Status_Rejected__c,
										IF (DR_Is_Submitted_For_Approval__c = True, $Setup.DR_Settings__c.Deal_Status_ApprovalInProgress__c, $Setup.DR_Settings__c.Deal_Status_NotSubmitted__c)
									)
								)
							)
						)
					)
				)	
			)	
		)	
	)
)
, IF(CONTAINS( $Setup.DR_Settings__c.Deal_Reg_Record_Types__c, RecordType.Name), &quot;Non-Deal Reg&quot;, &quot;Not Applicable&quot;)
)</formula>
    <label>Registration Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DR_Expiration_Date__c.field-meta.xml
<CustomField>
    <fullName>DR_Expiration_Date__c</fullName>
    <description>Calculated field. If Admin Expiration Override, then DR_Expiration_Date_Admin_Override else Expiration Date is based on either Approved Date + Extn Duration (if Extn approved) or Approved Date + 90</description>
    <formula>If ( !ISNULL(DR_Expiration_Date_Admin_Override__c), DR_Expiration_Date_Admin_Override__c, 
If ( (!ISNULL(DR_Extension_Approved_Date__c) &amp;&amp; DR_Is_Extension_Approved__c &amp;&amp; !ISBLANK(TEXT(DR_Extn_Duration__c))), DATEVALUE(DR_Approved_Date__c) + 90 + VALUE(TEXT(DR_Extn_Duration__c)), 
If ( (!ISNULL(DR_Extension_Approved_Date__c) &amp;&amp; DR_Is_Extension_Approved__c &amp;&amp; ISBLANK(TEXT(DR_Extn_Duration__c))), DATEVALUE(DR_Approved_Date__c) + 180,
If ( (!ISNULL(DR_Approved_Date__c) &amp;&amp; DR_Is_Approved__c), DATEVALUE(DR_Approved_Date__c) + 90, null) 
) 
)
)</formula>
    <label>Expiration Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/NPN_Solution_Provider_VAR__c.field-meta.xml
<CustomField>
    <fullName>NPN_Solution_Provider_VAR__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>NPN Solution Provider/VAR that applies to this specific opportunity.</description>
    <inlineHelpText>Select the NPN Solution Provider/VAR that applies to this specific opportunity.  This should represent the tier 2 partner involved with the deal.</inlineHelpText>
    <label>NPN Solution Provider/VAR</label>
    <lookupFilter>
        <active>true</active>
        <booleanFilter>(1 AND 2) OR 3</booleanFilter>
        <filterItems>
            <field>Account.NPN_Active_Program_Competency__c</field>
            <operation>contains</operation>
            <value>Solution Provider, Solutions Integration Partner</value>
        </filterItems>
        <filterItems>
            <field>$Source.RecordTypeId</field>
            <operation>notEqual</operation>
            <value>SW &amp; Service Renewals</value>
        </filterItems>
        <filterItems>
            <field>$Source.Type</field>
            <operation>equals</operation>
            <value>Deal Registration</value>
        </filterItems>
        <isOptional>true</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Opportunities (NPN Solution Provider (VAR))</relationshipLabel>
    <relationshipName>Opportunities2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <displayFormat>O-{000000}</displayFormat>
    <label>Opportunity Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Opportunity_SAP_Integration_Status__c/Opportunity_SAP_Integration_Status__c.object-meta.xml
<CustomObject>
    <description>Opp Reg =&gt; SAP integration Status. It captures the status of Opportunity sync to SAP</description>
    <label>Opportunity SAP Integration Status</label>
    <nameField>
        <displayFormat>OPP-SAP-Sync-{00000}</displayFormat>
        <label>Opportunity SAP Integration Status Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunity SAP Integration Status</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Opportunity_SAP_Integration_Status__c/fields/Opportunity_Number__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Number__c</fullName>
    <description>Opportunity O-Number</description>
    <formula>OpportunityId__r.Opportunity_Number__c</formula>
    <inlineHelpText>Opportunity O-Number</inlineHelpText>
    <label>Opportunity Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_SAP_Integration_Status__c/fields/OpportunityId__c.field-meta.xml
<CustomField>
    <fullName>OpportunityId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>OpportunityId</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity SAP Integration Status</relationshipLabel>
    <relationshipName>Opportunity_SAP_Integration_Status</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity_SAP_Integration_Status__c/fields/Return_Code__c.field-meta.xml
<CustomField>
    <fullName>Return_Code__c</fullName>
    <label>Return Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_SAP_Integration_Status__c/fields/Return_Message__c.field-meta.xml
<CustomField>
    <fullName>Return_Message__c</fullName>
    <label>Return Message</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity_SAP_Integration_Status__c/fields/Return_Type__c.field-meta.xml
<CustomField>
    <fullName>Return_Type__c</fullName>
    <label>Return Type</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Base_SKU__c.field-meta.xml
<CustomField>
    <fullName>Base_SKU__c</fullName>
    <description>Opp Reg &gt; SAP integration; shows the Base SKU from the underlying Product</description>
    <formula>PricebookEntry.Product2.Base_SKU__c</formula>
    <inlineHelpText>Opp Reg &gt; SAP integration; shows the Base SKU from the underlying Product</inlineHelpText>
    <label>Base SKU</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Opp_Line_Number__c.field-meta.xml
<CustomField>
    <fullName>Opp_Line_Number__c</fullName>
    <displayFormat>OLI-{000000}</displayFormat>
    <label>Opp Line Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <description>Opp Reg &gt; SAP integration; shows the Term from the underlying Product</description>
    <formula>PricebookEntry.Product2.Term__c</formula>
    <inlineHelpText>Opp Reg &gt; SAP integration; shows the Term from the underlying Product</inlineHelpText>
    <label>Term</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOQ_QuoteCreation_Settings__c/SOQ_QuoteCreation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>SOQ - Initial Quote Creation default values</description>
    <label>SOQ QuoteCreation Settings</label>
</CustomObject>

force-app/main/default/objects/SOQ_QuoteCreation_Settings__c/fields/Approved_Quote_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Approved_Quote_Template_Id__c</fullName>
    <defaultValue>&quot;a3r1W000001BVwoQAG&quot;</defaultValue>
    <description>Approved Quote - Initial Sale</description>
    <inlineHelpText>Approved Quote - Initial Sale</inlineHelpText>
    <label>Approved_Quote_Template_Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOQ_QuoteCreation_Settings__c/fields/BATCHJOB_OppCreationCutOffDateTime__c.field-meta.xml
<CustomField>
    <fullName>BATCHJOB_OppCreationCutOffDateTime__c</fullName>
    <description>Only auto create quote and quote line item for Opp Regs created since this cutoff date/time</description>
    <inlineHelpText>Only auto create quote and quote line item for Opp Regs created since this cutoff date/time</inlineHelpText>
    <label>BATCHJOB_OppCreationCutOffDateTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SOQ_QuoteCreation_Settings__c/fields/Default_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Default_Template_Id__c</fullName>
    <defaultValue>&quot;a3r1W000001BVwjQAG&quot;</defaultValue>
    <description>Id for quote template - Budgetary Quote - Initial Sale</description>
    <inlineHelpText>Id for quote template - Budgetary Quote - Initial Sale</inlineHelpText>
    <label>Default Template Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOQ_QuoteCreation_Settings__c/fields/Initial_Status__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status__c</fullName>
    <description>Quote Initial Status - Draft</description>
    <label>Initial Status</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOQ_QuoteCreation_Settings__c/fields/Quote_Type_c__c.field-meta.xml
<CustomField>
    <fullName>Quote_Type_c__c</fullName>
    <defaultValue>&quot;Quote&quot;</defaultValue>
    <description>Quote Type - Quote/Renewal/Amendment/Re-quote</description>
    <inlineHelpText>Quote Type - in case of initial one it is &quot;Quote&quot;</inlineHelpText>
    <label>Quote Type</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOQ_QuoteCreation_Settings__c/fields/RecordTypeId__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeId__c</fullName>
    <description>Quote Record Type Id</description>
    <inlineHelpText>Quote Record Type Id</inlineHelpText>
    <label>RecordTypeId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_DR_OPPREG_SAP_SYNC_Batch.cls
/*
    Test class for DR_OPPREG_SAP_SYNC_Batch
    2018.09.30 - pjena - Batch class to to Sync OPP REG data to SAP
    
    
 */
@isTest(SeeAllData=false)
private class Test_DR_OPPREG_SAP_SYNC_Batch {
    
    private static final string OPPTY_RT_ENTERPRISESALESOPPTY = 'Enterprise Sales Opportunity';
    private static final string ProdName = 'DGX Station V100-32GB';
    private static final string ProdCode = 'DGXDLStation32GB';
    private static final string ProdFamily = 'DGX Station Product Family';
    private static final string PriceBookName = 'OppReg Price Book';
    private static final string BaseSKU = '920-22587-2511';
    private static final string Term = '12';
    private static final string NPNVAR_SAPCustomerNumber = '0000800111';
    private static final string PEC_SAPCustomerNumber = '000900111';
    
    static testMethod void syncOppRegWithSAP_success() {
    
        //setEnterpriseOpptyInfra(string ProdName, string ProdFamily, string ProdCode, boolean isDealEnabled, string PriceBookName, decimal StandardPrice, decimal CustomPrice, string BaseSKU, string Term
        map<string, Object> mapOpptyInfa = Test_COMM_Factory.setEnterpriseOpptyInfra(ProdName, ProdCode, ProdFamily,true, PriceBookName, 1000, 1500, BaseSKU, Term);
        
        //get the infra objects back from the map
        Account partnerAccount = mapOpptyInfa.get('partneraccount') != null ? (Account) mapOpptyInfa.get('partneraccount') : new Account();
        Contact partnerContact = mapOpptyInfa.get('partnercontact') != null ? (Contact) mapOpptyInfa.get('partnercontact') : new Contact();
        Account customerAccount = mapOpptyInfa.get('customeraccount') != null ? (Account) mapOpptyInfa.get('customeraccount') : new Account();
        User partnerUser = mapOpptyInfa.get('partneruser') != null ? (User) mapOpptyInfa.get('partneruser') : new User();
        User pbm = mapOpptyInfa.get('pbm') != null ? (User) mapOpptyInfa.get('pbm') : new User();
        User pbmmanager = mapOpptyInfa.get('pbmmanager') != null ? (User) mapOpptyInfa.get('pbmmanager') : new User();
        User salesopsadmin = mapOpptyInfa.get('salesopsadmin') != null ? (User) mapOpptyInfa.get('salesopsadmin') : new User();
        PricebookEntry pricebookentryRecord = mapOpptyInfa.get('pricebookentry') != null ? (pricebookentry) mapOpptyInfa.get('pricebookentry') : new PricebookEntry();
        map<string, Id> mapProfNameId = mapOpptyInfa.get('mapprofnameid') != null ? (map<string, id>) mapOpptyInfa.get('mapprofnameid') : new map<string, Id>();
        map<String, Id> mapRTNameId = mapOpptyInfa.get('maprectypenameid') != null ? (map<string, Id>) mapOpptyInfa.get('maprectypenameid') : new map<string, Id>();
        
        Opportunity enterpriseSalesOppty;
        ApexPages.Standardcontroller stdCon;
        
        User currUser = [Select Id From User where Id = :userinfo.getUserId()];
        
        system.debug('***currUser: ' + currUser);
        
        list<Account> lstAccount = new list<Account>(); 
        system.runAs(currUser){
            customerAccount.SAP_Customer_Number__c = PEC_SAPCustomerNumber;
            partnerAccount.SAP_Customer_Number__c = NPNVAR_SAPCustomerNumber;
            lstAccount.add(customerAccount);
            lstAccount.add(partnerAccount);
            update lstAccount;
            
            DateTime dt = DateTime.now();
           list<SBQQ__QuoteTemplate__c> lstQT = new list<SBQQ__QuoteTemplate__c>();
           SBQQ__QuoteTemplate__c Quotetemplate = new SBQQ__QuoteTemplate__c (name ='Approved Quote - Initial Sale');
            lstQT.add(Quotetemplate);
            SBQQ__QuoteTemplate__c Quotetemplate1 = new SBQQ__QuoteTemplate__c (name ='Budgetary Quote - Initial Sale');
            lstQT.add(Quotetemplate1);
            insert lstQT;
           SOQ_QuoteCreation_Settings__c objSOQCS = new SOQ_QuoteCreation_Settings__c(Approved_Quote_Template_Id__c=Quotetemplate .id, Default_Template_Id__c=Quotetemplate1.id, Quote_Type_c__c = 'Quote', BATCHJOB_OppCreationCutOffDateTime__c=dt, Initial_Status__c = 'Draft', RecordTypeId__c=Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByName().get('Initial Enterprise Sales Quote').getRecordTypeId());
           insert objSOQCS;
            //Create the Enterprise Opportunity with Deal Registration
            //createDealRegOpportunity(string name, Id recordTypeId, string stageName, Date closeDate, Id pricebook2Id, Id customerAccountId, Id partnerAccountId){
            System.debug('Limits.getLimitSoslQueries - '+ Limits.getLimitSoslQueries());
            enterpriseSalesOppty = Test_COMM_Factory.createDealRegOpportunity('Enterprise Sales Oppty1', mapRTNameId.get(OPPTY_RT_ENTERPRISESALESOPPTY), COMM_Constants.OPPTY_STAGE_PROSPECTING, System.Today(), pricebookentryRecord.PriceBook2Id, customerAccount.Id, partnerAccount.Id);
            
        }
        
        enterpriseSalesOppty = [Select Id, Opportunity_Number__c, NPN_Solution_Provider_VAR__r.SAP_Customer_Number__c, 
                                                DR_Expiration_Date__c, DR_Deal_Status__c, Account.SAP_Customer_Number__c,  
                                                (Select Opp_Line_Number__c, Base_SKU__c, Term__c, Quantity From OpportunityLineItems) 
                                From Opportunity
                                Where Id = :enterpriseSalesOppty.Id                                         
                                ];
        
        system.debug('****enterpriseSalesOppty: ' + enterpriseSalesOppty);
        
        list<Opportunity> lstOppReg = new list<Opportunity>();
        lstOppReg.add(enterpriseSalesOppty);
            
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('DR_OppRegSAPSync_Success');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/xml');
        
        //run as to avoid MIXED DML
        system.runAs(currUser){
            Test.startTest();
                Test.setMock(HttpCalloutMock.class, mock);    
                //set Deal Reg fields in Enterprise Opportunity
                Test_COMM_Factory.setDealRegFieldsInOpportunity(enterpriseSalesOppty.Id, customerAccount.Id, partnerAccount.Id);
            
                //Add Opportunity Line Items
                OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = enterpriseSalesOppty.Id, PricebookEntryId = pricebookentryRecord.Id, Quantity = 4, UnitPrice = pricebookentryRecord.UnitPrice);
                insert oli;
            
                Database.BatchableContext     bc;
                DR_OPPREG_SAP_SYNC_Batch bClass = new DR_OPPREG_SAP_SYNC_Batch();
                Database.QueryLocator ql = bClass.start(bc);
                bClass.execute(bc, lstOppReg);
                bClass.finish(bc);
      
                list<Opportunity_SAP_Integration_Status__c> lstOppRegSAPSyncStatus = [Select Return_Type__c, Return_Code__c, Return_Message__c From Opportunity_SAP_Integration_Status__c Where OpportunityId__c = :lstOppReg];
                system.debug('***lstOppRegSAPSyncStatus: ' + lstOppRegSAPSyncStatus);
                for (Opportunity_SAP_Integration_Status__c syncStatus : lstOppRegSAPSyncStatus){
                    system.assert(syncStatus.Return_Type__c == 'S');
                }
            Test.stopTest();
        }
        
    }
    
    static testMethod void syncOppRegWithSAP_failure() {
    
        //setEnterpriseOpptyInfra(string ProdName, string ProdFamily, string ProdCode, boolean isDealEnabled, string PriceBookName, decimal StandardPrice, decimal CustomPrice, string BaseSKU, string Term
        map<string, Object> mapOpptyInfa = Test_COMM_Factory.setEnterpriseOpptyInfra(ProdName, ProdCode, ProdFamily,true, PriceBookName, 1000, 1500, BaseSKU, Term);
        
        //get the infra objects back from the map
        Account partnerAccount = mapOpptyInfa.get('partneraccount') != null ? (Account) mapOpptyInfa.get('partneraccount') : new Account();
        Contact partnerContact = mapOpptyInfa.get('partnercontact') != null ? (Contact) mapOpptyInfa.get('partnercontact') : new Contact();
        Account customerAccount = mapOpptyInfa.get('customeraccount') != null ? (Account) mapOpptyInfa.get('customeraccount') : new Account();
        User partnerUser = mapOpptyInfa.get('partneruser') != null ? (User) mapOpptyInfa.get('partneruser') : new User();
        User pbm = mapOpptyInfa.get('pbm') != null ? (User) mapOpptyInfa.get('pbm') : new User();
        User pbmmanager = mapOpptyInfa.get('pbmmanager') != null ? (User) mapOpptyInfa.get('pbmmanager') : new User();
        User salesopsadmin = mapOpptyInfa.get('salesopsadmin') != null ? (User) mapOpptyInfa.get('salesopsadmin') : new User();
        PricebookEntry pricebookentryRecord = mapOpptyInfa.get('pricebookentry') != null ? (pricebookentry) mapOpptyInfa.get('pricebookentry') : new PricebookEntry();
        map<string, Id> mapProfNameId = mapOpptyInfa.get('mapprofnameid') != null ? (map<string, id>) mapOpptyInfa.get('mapprofnameid') : new map<string, Id>();
        map<String, Id> mapRTNameId = mapOpptyInfa.get('maprectypenameid') != null ? (map<string, Id>) mapOpptyInfa.get('maprectypenameid') : new map<string, Id>();
        
        Opportunity enterpriseSalesOppty;
        ApexPages.Standardcontroller stdCon;
        
        User currUser = [Select Id From User where Id = :userinfo.getUserId()];
        
        system.debug('***currUser: ' + currUser);
        
        list<Account> lstAccount = new list<Account>(); 
        system.runAs(currUser){
            customerAccount.SAP_Customer_Number__c = PEC_SAPCustomerNumber;
            partnerAccount.SAP_Customer_Number__c = NPNVAR_SAPCustomerNumber;
            lstAccount.add(customerAccount);
            lstAccount.add(partnerAccount);
            update lstAccount;
            
            DateTime dt = DateTime.now();
           SBQQ__QuoteTemplate__c Quotetemplate = new SBQQ__QuoteTemplate__c (name ='Approved Quote - Initial Sale');
            insert Quotetemplate;
            SBQQ__QuoteTemplate__c Quotetemplate1 = new SBQQ__QuoteTemplate__c (name ='Budgetary Quote - Initial Sale');
            insert Quotetemplate1;
           SOQ_QuoteCreation_Settings__c objSOQCS = new SOQ_QuoteCreation_Settings__c(Approved_Quote_Template_Id__c=Quotetemplate .id, Default_Template_Id__c=Quotetemplate1.id, Quote_Type_c__c = 'Quote', BATCHJOB_OppCreationCutOffDateTime__c=dt, Initial_Status__c = 'Draft', RecordTypeId__c=Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByName().get('Initial Enterprise Sales Quote').getRecordTypeId());
           insert objSOQCS;
            //Create the Enterprise Opportunity with Deal Registration
            //createDealRegOpportunity(string name, Id recordTypeId, string stageName, Date closeDate, Id pricebook2Id, Id customerAccountId, Id partnerAccountId){
            enterpriseSalesOppty = Test_COMM_Factory.createDealRegOpportunity('Enterprise Sales Oppty2', mapRTNameId.get(OPPTY_RT_ENTERPRISESALESOPPTY), COMM_Constants.OPPTY_STAGE_PROSPECTING, System.Today(), pricebookentryRecord.PriceBook2Id, customerAccount.Id, partnerAccount.Id);
                    
            
        }
        
        enterpriseSalesOppty = [Select Id, Opportunity_Number__c, NPN_Solution_Provider_VAR__r.SAP_Customer_Number__c, 
                                                DR_Expiration_Date__c, DR_Deal_Status__c, Account.SAP_Customer_Number__c,  
                                                (Select Opp_Line_Number__c, Base_SKU__c, Term__c, Quantity From OpportunityLineItems) 
                                From Opportunity
                                Where Id = :enterpriseSalesOppty.Id                                         
                                ];
        
        system.debug('****enterpriseSalesOppty: ' + enterpriseSalesOppty);
        
        list<Opportunity> lstOppReg = new list<Opportunity>();
        lstOppReg.add(enterpriseSalesOppty);
            
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('DR_OppRegSAPSync_Failure');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/xml');
        
        //run as to avoid MIXED DML
        system.runAs(currUser){
            Test.startTest();
                Test.setMock(HttpCalloutMock.class, mock);
                //set Deal Reg fields in Enterprise Opportunity
                Test_COMM_Factory.setDealRegFieldsInOpportunity(enterpriseSalesOppty.Id, customerAccount.Id, partnerAccount.Id);
            
                //Add Opportunity Line Items
                OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = enterpriseSalesOppty.Id, PricebookEntryId = pricebookentryRecord.Id, Quantity = 4, UnitPrice = pricebookentryRecord.UnitPrice);
                insert oli;
                Database.BatchableContext     bc;
                DR_OPPREG_SAP_SYNC_Batch bClass = new DR_OPPREG_SAP_SYNC_Batch();
                Database.QueryLocator ql = bClass.start(bc);
                bClass.execute(bc, lstOppReg);
                bClass.finish(bc);
      
                list<Opportunity_SAP_Integration_Status__c> lstOppRegSAPSyncStatus = [Select Return_Type__c, Return_Code__c, Return_Message__c From Opportunity_SAP_Integration_Status__c Where OpportunityId__c = :lstOppReg];
                system.debug('***lstOppRegSAPSyncStatus: ' + lstOppRegSAPSyncStatus);
                for (Opportunity_SAP_Integration_Status__c syncStatus : lstOppRegSAPSyncStatus){
                    system.assert(syncStatus.Return_Type__c == 'E');
                }
            Test.stopTest();
        }
        
    }
    
    static testMethod void syncOppRegWithSAP_exceptionCoverage() {
    
        //setEnterpriseOpptyInfra(string ProdName, string ProdFamily, string ProdCode, boolean isDealEnabled, string PriceBookName, decimal StandardPrice, decimal CustomPrice, string BaseSKU, string Term
        map<string, Object> mapOpptyInfa = Test_COMM_Factory.setEnterpriseOpptyInfra(ProdName, ProdCode, ProdFamily,true, PriceBookName, 1000, 1500, BaseSKU, Term);
        
        //get the infra objects back from the map
        Account partnerAccount = mapOpptyInfa.get('partneraccount') != null ? (Account) mapOpptyInfa.get('partneraccount') : new Account();
        Contact partnerContact = mapOpptyInfa.get('partnercontact') != null ? (Contact) mapOpptyInfa.get('partnercontact') : new Contact();
        Account customerAccount = mapOpptyInfa.get('customeraccount') != null ? (Account) mapOpptyInfa.get('customeraccount') : new Account();
        User partnerUser = mapOpptyInfa.get('partneruser') != null ? (User) mapOpptyInfa.get('partneruser') : new User();
        User pbm = mapOpptyInfa.get('pbm') != null ? (User) mapOpptyInfa.get('pbm') : new User();
        User pbmmanager = mapOpptyInfa.get('pbmmanager') != null ? (User) mapOpptyInfa.get('pbmmanager') : new User();
        User salesopsadmin = mapOpptyInfa.get('salesopsadmin') != null ? (User) mapOpptyInfa.get('salesopsadmin') : new User();
        PricebookEntry pricebookentryRecord = mapOpptyInfa.get('pricebookentry') != null ? (pricebookentry) mapOpptyInfa.get('pricebookentry') : new PricebookEntry();
        map<string, Id> mapProfNameId = mapOpptyInfa.get('mapprofnameid') != null ? (map<string, id>) mapOpptyInfa.get('mapprofnameid') : new map<string, Id>();
        map<String, Id> mapRTNameId = mapOpptyInfa.get('maprectypenameid') != null ? (map<string, Id>) mapOpptyInfa.get('maprectypenameid') : new map<string, Id>();
        
        Opportunity enterpriseSalesOppty;
        ApexPages.Standardcontroller stdCon;
        
        User currUser = [Select Id From User where Id = :userinfo.getUserId()];
        
        system.debug('***currUser: ' + currUser);
        
        list<Account> lstAccount = new list<Account>(); 
        system.runAs(currUser){
            customerAccount.SAP_Customer_Number__c = PEC_SAPCustomerNumber;
            partnerAccount.SAP_Customer_Number__c = NPNVAR_SAPCustomerNumber;
            lstAccount.add(customerAccount);
            lstAccount.add(partnerAccount);
            update lstAccount;
            
           DateTime dt = DateTime.now();
           SBQQ__QuoteTemplate__c Quotetemplate = new SBQQ__QuoteTemplate__c (name ='Approved Quote - Initial Sale');
            insert Quotetemplate;
            SBQQ__QuoteTemplate__c Quotetemplate1 = new SBQQ__QuoteTemplate__c (name ='Budgetary Quote - Initial Sale');
            insert Quotetemplate1;
           SOQ_QuoteCreation_Settings__c objSOQCS = new SOQ_QuoteCreation_Settings__c(Approved_Quote_Template_Id__c=Quotetemplate .id, Default_Template_Id__c=Quotetemplate1.id, Quote_Type_c__c = 'Quote', BATCHJOB_OppCreationCutOffDateTime__c=dt, Initial_Status__c = 'Draft', RecordTypeId__c=Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByName().get('Initial Enterprise Sales Quote').getRecordTypeId());
           insert objSOQCS;
            //Create the Enterprise Opportunity with Deal Registration
            //createDealRegOpportunity(string name, Id recordTypeId, string stageName, Date closeDate, Id pricebook2Id, Id customerAccountId, Id partnerAccountId){
            enterpriseSalesOppty = Test_COMM_Factory.createDealRegOpportunity('Enterprise Sales Oppty3', mapRTNameId.get(OPPTY_RT_ENTERPRISESALESOPPTY), COMM_Constants.OPPTY_STAGE_PROSPECTING, System.Today(), pricebookentryRecord.PriceBook2Id, customerAccount.Id, partnerAccount.Id);
                    
            //set Deal Reg fields in Enterprise Opportunity; this will make sure the code in DR_OPPREG_SAP_SYNC_Batch batch execute throws exception
            //Test_COMM_Factory.setDealRegFieldsInOpportunity(enterpriseSalesOppty.Id, customerAccount.Id, partnerAccount.Id);
        
            //Add Opportunity Line Items
            
        }
        
        enterpriseSalesOppty = [Select Id, Opportunity_Number__c, NPN_Solution_Provider_VAR__r.SAP_Customer_Number__c, 
                                                DR_Expiration_Date__c, DR_Deal_Status__c, Account.SAP_Customer_Number__c,  
                                                (Select Opp_Line_Number__c, Base_SKU__c, Term__c, Quantity From OpportunityLineItems) 
                                From Opportunity
                                Where Id = :enterpriseSalesOppty.Id                                         
                                ];
        
        system.debug('****enterpriseSalesOppty: ' + enterpriseSalesOppty);
        
        list<Opportunity> lstOppReg = new list<Opportunity>();
        lstOppReg.add(enterpriseSalesOppty);
            
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('DR_OppRegSAPSync_Failure');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/xml');
        
        //run as to avoid MIXED DML
        system.runAs(currUser){
            Test.startTest();
                Test.setMock(HttpCalloutMock.class, mock);
                OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = enterpriseSalesOppty.Id, PricebookEntryId = pricebookentryRecord.Id, Quantity = 4, UnitPrice = pricebookentryRecord.UnitPrice);
                insert oli;
                Database.BatchableContext     bc;
                DR_OPPREG_SAP_SYNC_Batch bClass = new DR_OPPREG_SAP_SYNC_Batch();
                Database.QueryLocator ql = bClass.start(bc);
                
                //coverage for DR_OPPREG_SAP_SYNC_Wrapper > Opp_Approver structure
                list<DR_OPPREG_SAP_SYNC_Wrapper.OPP_APPROVER> lstApprovers = new list<DR_OPPREG_SAP_SYNC_Wrapper.OPP_APPROVER>();
                DR_OPPREG_SAP_SYNC_Wrapper.OPP_APPROVER drApprover = new DR_OPPREG_SAP_SYNC_Wrapper.OPP_APPROVER();
                drApprover.Opportunity_Counter = 'Channel Admin Approval';
                drApprover.Name = 'ApproverJohn Smith';
                drApprover.Email_ID = 'johnsmith@nvidia.com';
                drApprover.Approved_On = '20181019';
                drApprover.Approved_At = '045355';
                lstApprovers.add(drApprover);
                
                DR_SAPOppRegIntegration oDRSORI = new DR_SAPOppRegIntegration();
                DR_SAPOppRegIntegration.Header_element oHE = new DR_SAPOppRegIntegration.Header_element();
                DR_SAPOppRegIntegration.OppReg_Response_DT oORR = new DR_SAPOppRegIntegration.OppReg_Response_DT();
                DR_SAPOppRegIntegration.Item_element oIE = new DR_SAPOppRegIntegration.Item_element();
                DR_SAPOppRegIntegration.RETURN_ITEM_element oRIE = new DR_SAPOppRegIntegration.RETURN_ITEM_element();
                DR_SAPOppRegIntegration.Approver_element oAE = new DR_SAPOppRegIntegration.Approver_element();
                DR_SAPOppRegIntegration.OppReg_Request_DT oORRDT = new DR_SAPOppRegIntegration.OppReg_Request_DT();
                
                bClass.execute(bc, lstOppReg);
                bClass.finish(bc);
      
                list<Opportunity_SAP_Integration_Status__c> lstOppRegSAPSyncStatus = [Select Return_Type__c, Return_Code__c, Return_Message__c From Opportunity_SAP_Integration_Status__c Where OpportunityId__c = :lstOppReg];
                system.debug('***lstOppRegSAPSyncStatus: ' + lstOppRegSAPSyncStatus);
                for (Opportunity_SAP_Integration_Status__c syncStatus : lstOppRegSAPSyncStatus){
                    system.assert(syncStatus.Return_Type__c == 'E');
                }
            Test.stopTest();
        }
        
    }
    
    static testMethod void syncOppRegWithSAP_schedule() {
    
        //setEnterpriseOpptyInfra(string ProdName, string ProdFamily, string ProdCode, boolean isDealEnabled, string PriceBookName, decimal StandardPrice, decimal CustomPrice, string BaseSKU, string Term
        map<string, Object> mapOpptyInfa = Test_COMM_Factory.setEnterpriseOpptyInfra(ProdName, ProdCode, ProdFamily,true, PriceBookName, 1000, 1500, BaseSKU, Term);
        
        //get the infra objects back from the map
        Account partnerAccount = mapOpptyInfa.get('partneraccount') != null ? (Account) mapOpptyInfa.get('partneraccount') : new Account();
        Contact partnerContact = mapOpptyInfa.get('partnercontact') != null ? (Contact) mapOpptyInfa.get('partnercontact') : new Contact();
        Account customerAccount = mapOpptyInfa.get('customeraccount') != null ? (Account) mapOpptyInfa.get('customeraccount') : new Account();
        User partnerUser = mapOpptyInfa.get('partneruser') != null ? (User) mapOpptyInfa.get('partneruser') : new User();
        User pbm = mapOpptyInfa.get('pbm') != null ? (User) mapOpptyInfa.get('pbm') : new User();
        User pbmmanager = mapOpptyInfa.get('pbmmanager') != null ? (User) mapOpptyInfa.get('pbmmanager') : new User();
        User salesopsadmin = mapOpptyInfa.get('salesopsadmin') != null ? (User) mapOpptyInfa.get('salesopsadmin') : new User();
        PricebookEntry pricebookentryRecord = mapOpptyInfa.get('pricebookentry') != null ? (pricebookentry) mapOpptyInfa.get('pricebookentry') : new PricebookEntry();
        map<string, Id> mapProfNameId = mapOpptyInfa.get('mapprofnameid') != null ? (map<string, id>) mapOpptyInfa.get('mapprofnameid') : new map<string, Id>();
        map<String, Id> mapRTNameId = mapOpptyInfa.get('maprectypenameid') != null ? (map<string, Id>) mapOpptyInfa.get('maprectypenameid') : new map<string, Id>();
        
        Opportunity enterpriseSalesOppty;
        ApexPages.Standardcontroller stdCon;
        
        User currUser = [Select Id From User where Id = :userinfo.getUserId()];
        
        system.debug('***currUser: ' + currUser);
        
        list<Account> lstAccount = new list<Account>(); 
        system.runAs(currUser){
            customerAccount.SAP_Customer_Number__c = PEC_SAPCustomerNumber;
            partnerAccount.SAP_Customer_Number__c = NPNVAR_SAPCustomerNumber;
            lstAccount.add(customerAccount);
            lstAccount.add(partnerAccount);
            update lstAccount;
            
            DateTime dt = DateTime.now();
           SBQQ__QuoteTemplate__c Quotetemplate = new SBQQ__QuoteTemplate__c (name ='Approved Quote - Initial Sale');
            insert Quotetemplate;
            SBQQ__QuoteTemplate__c Quotetemplate1 = new SBQQ__QuoteTemplate__c (name ='Budgetary Quote - Initial Sale');
            insert Quotetemplate1;
           SOQ_QuoteCreation_Settings__c objSOQCS = new SOQ_QuoteCreation_Settings__c(Approved_Quote_Template_Id__c=Quotetemplate .id, Default_Template_Id__c=Quotetemplate1.id, Quote_Type_c__c = 'Quote', BATCHJOB_OppCreationCutOffDateTime__c=dt, Initial_Status__c = 'Draft', RecordTypeId__c=Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByName().get('Initial Enterprise Sales Quote').getRecordTypeId());
           insert objSOQCS;
            //Create the Enterprise Opportunity with Deal Registration
            //createDealRegOpportunity(string name, Id recordTypeId, string stageName, Date closeDate, Id pricebook2Id, Id customerAccountId, Id partnerAccountId){
            enterpriseSalesOppty = Test_COMM_Factory.createDealRegOpportunity('Enterprise Sales Oppty1', mapRTNameId.get(OPPTY_RT_ENTERPRISESALESOPPTY), COMM_Constants.OPPTY_STAGE_PROSPECTING, System.Today(), pricebookentryRecord.PriceBook2Id, customerAccount.Id, partnerAccount.Id);
                    
            
        }
        
        enterpriseSalesOppty = [Select Id, Opportunity_Number__c, NPN_Solution_Provider_VAR__r.SAP_Customer_Number__c, 
                                                DR_Expiration_Date__c, DR_Deal_Status__c, Account.SAP_Customer_Number__c,  
                                                (Select Opp_Line_Number__c, Base_SKU__c, Term__c, Quantity From OpportunityLineItems) 
                                From Opportunity
                                Where Id = :enterpriseSalesOppty.Id                                         
                                ];
        
        system.debug('****enterpriseSalesOppty: ' + enterpriseSalesOppty);
        
        DR_OPPREG_SAP_SYNC_Batch bClass = new DR_OPPREG_SAP_SYNC_Batch();
        
        
        list<Opportunity> lstOppReg = new list<Opportunity>();
        lstOppReg.add(enterpriseSalesOppty);
            
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('DR_OppRegSAPSync_Success');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/xml');
        
        //run as to avoid MIXED DML
        system.runAs(currUser){
            Test.startTest();
                Test.setMock(HttpCalloutMock.class, mock);
                //set Deal Reg fields in Enterprise Opportunity
                Test_COMM_Factory.setDealRegFieldsInOpportunity(enterpriseSalesOppty.Id, customerAccount.Id, partnerAccount.Id);
            
                //Add Opportunity Line Items
                OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = enterpriseSalesOppty.Id, PricebookEntryId = pricebookentryRecord.Id, Quantity = 4, UnitPrice = pricebookentryRecord.UnitPrice);
                insert oli;
                DR_OPPREG_SAP_SYNC_Batch p = new DR_OPPREG_SAP_SYNC_Batch();
                Database.BatchableContext     bc;
                Database.QueryLocator ql = p.start(bc);
                DateTime currDT = DateTime.now().addMinutes(2);
                integer sec = currDT.second();
                integer min = currDT.minute();
                string sch = sec + ' ' + min + ' ' + '* ? * *'; //0 5 * * * ?
                system.debug('sch: ' + sch);
                system.schedule('Exec of DR_OPPREG_SAP_SYNC_Batch', sch, p);                
            Test.stopTest();
            
            //check the status now as the schedule run is complete after the stopTest method
            list<Opportunity_SAP_Integration_Status__c> lstOppRegSAPSyncStatus = [Select Return_Type__c, Return_Code__c, Return_Message__c From Opportunity_SAP_Integration_Status__c Where OpportunityId__c = :lstOppReg];
            system.debug('***lstOppRegSAPSyncStatus: ' + lstOppRegSAPSyncStatus);
            for (Opportunity_SAP_Integration_Status__c syncStatus : lstOppRegSAPSyncStatus){
                system.assert(syncStatus.Return_Type__c == 'S');
            }
        }
        
    }
}