force-app/main/default/objects/Account/fields/SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>SAP Customer Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/PartnerAccount.recordType-meta.xml
<RecordType>
    <fullName>PartnerAccount</fullName>
    <active>true</active>
    <label>Partner Account</label>
</RecordType>

force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/DR_Deal_Status__c.field-meta.xml
<CustomField>
    <fullName>DR_Deal_Status__c</fullName>
    <formula>IF( TEXT(Type) =   $Setup.DR_Settings__c.Lead_Type__c, 
IF(DR_Is_Deal_Auto_Terminated__c  = True, $Setup.DR_Settings__c.Deal_Status_AutoTerminated__c, 
	IF (DR_Is_Terminated__c = True, $Setup.DR_Settings__c.Deal_Status_Terminated__c,
		IF (DR_Is_180Days_Extn_Approved__c = True, $Setup.DR_Settings__c.Deal_Status_ExtensionApproved__c,
			IF (DR_Is_180Days_Extn_Rejected__c = True, $Setup.DR_Settings__c.Deal_Status_ExtensionApproved__c,
				IF (DR_Is_Submitted_For_180Days_Extn__c = True, $Setup.DR_Settings__c.Deal_Status_ExtensionApproved__c,
					IF(DR_Is_Extension_Approved__c = True, $Setup.DR_Settings__c.Deal_Status_ExtensionApproved__c,
						IF(DR_Is_Extension_Rejected__c = True, $Setup.DR_Settings__c.Deal_Status_ExtensionRejected__c,
							IF(DR_Is_Submitted_For_Extension__c = True, $Setup.DR_Settings__c.Deal_Status_ExtensionApprovalInProgress__c,
								IF (DR_Is_Approved__c = True, $Setup.DR_Settings__c.Deal_Status_Approved__c,
									IF (DR_Is_Rejected__c = True, $Setup.DR_Settings__c.Deal_Status_Rejected__c,
										IF (DR_Is_Submitted_For_Approval__c = True, $Setup.DR_Settings__c.Deal_Status_ApprovalInProgress__c, $Setup.DR_Settings__c.Deal_Status_NotSubmitted__c)
									)
								)
							)
						)
					)
				)	
			)	
		)	
	)
)
, IF(CONTAINS( $Setup.DR_Settings__c.Deal_Reg_Record_Types__c, RecordType.Name), &quot;Non-Deal Reg&quot;, &quot;Not Applicable&quot;)
)</formula>
    <label>Registration Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DR_Is_Terminated__c.field-meta.xml
<CustomField>
    <fullName>DR_Is_Terminated__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Terminated</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DR_Reason_For_Termination__c.field-meta.xml
<CustomField>
    <fullName>DR_Reason_For_Termination__c</fullName>
    <label>Reason for Termination</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/SOQ_QuoteCreation_Settings__c/SOQ_QuoteCreation_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>SOQ - Initial Quote Creation default values</description>
    <label>SOQ QuoteCreation Settings</label>
</CustomObject>

force-app/main/default/objects/SOQ_QuoteCreation_Settings__c/fields/Approved_Quote_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Approved_Quote_Template_Id__c</fullName>
    <defaultValue>&quot;a3r1W000001BVwoQAG&quot;</defaultValue>
    <description>Approved Quote - Initial Sale</description>
    <inlineHelpText>Approved Quote - Initial Sale</inlineHelpText>
    <label>Approved_Quote_Template_Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOQ_QuoteCreation_Settings__c/fields/BATCHJOB_OppCreationCutOffDateTime__c.field-meta.xml
<CustomField>
    <fullName>BATCHJOB_OppCreationCutOffDateTime__c</fullName>
    <description>Only auto create quote and quote line item for Opp Regs created since this cutoff date/time</description>
    <inlineHelpText>Only auto create quote and quote line item for Opp Regs created since this cutoff date/time</inlineHelpText>
    <label>BATCHJOB_OppCreationCutOffDateTime</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/SOQ_QuoteCreation_Settings__c/fields/Default_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Default_Template_Id__c</fullName>
    <defaultValue>&quot;a3r1W000001BVwjQAG&quot;</defaultValue>
    <description>Id for quote template - Budgetary Quote - Initial Sale</description>
    <inlineHelpText>Id for quote template - Budgetary Quote - Initial Sale</inlineHelpText>
    <label>Default Template Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOQ_QuoteCreation_Settings__c/fields/Initial_Status__c.field-meta.xml
<CustomField>
    <fullName>Initial_Status__c</fullName>
    <description>Quote Initial Status - Draft</description>
    <label>Initial Status</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOQ_QuoteCreation_Settings__c/fields/Quote_Type_c__c.field-meta.xml
<CustomField>
    <fullName>Quote_Type_c__c</fullName>
    <defaultValue>&quot;Quote&quot;</defaultValue>
    <description>Quote Type - Quote/Renewal/Amendment/Re-quote</description>
    <inlineHelpText>Quote Type - in case of initial one it is &quot;Quote&quot;</inlineHelpText>
    <label>Quote Type</label>
    <length>25</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SOQ_QuoteCreation_Settings__c/fields/RecordTypeId__c.field-meta.xml
<CustomField>
    <fullName>RecordTypeId__c</fullName>
    <description>Quote Record Type Id</description>
    <inlineHelpText>Quote Record Type Id</inlineHelpText>
    <label>RecordTypeId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Test_CRM_DR_TerminateDeal_cls.cls
/*
    Test class for controller class CRM_DR_TerminateDeal_cls
    2017.03.13 - Opp Reg 2.0 (Phase I) - TAM Automation, Direct Opp Reg record creation, Regional Roll-out
    2017.06.21 - Test class retrofit during MDF v1/v2 code cleanup
    2017.08.23 - Restrict Partners Closing Out Opportunity Regs - Code clean up
    2017.10.19 - 2017.10.19 - Opp Reg 2.5 (Record Locked to Partner after Submit, Auto Extension)
        -Remove Termination capability from partners
    
    2017.11.29 - PJENA - Deal Registration - only allow Deal Registration types to be terminated
    
    2019.03.11 - PJENA - SDS-774 - Remove Partner Opportunity Record Types
 */
 
@isTest(SeeAllData=false)
private class Test_CRM_DR_TerminateDeal_cls {
    
    private static final string OPPTY_RT_ENTERPRISESALESOPPTY = 'Enterprise Sales Opportunity';
    private static final string ProdName = 'DGX Station V100-32GB';
    private static final string ProdCode = 'DGXDLStation32GB';
    private static final string ProdFamily = 'DGX Station Product Family';
    private static final string PriceBookName = 'OppReg Price Book';
    private static final string BaseSKU = '920-22587-2511';
    private static final string Term = '12';
    private static final string NPNVAR_SAPCustomerNumber = '0000800112';
    private static final string PEC_SAPCustomerNumber = '000900112';
    
    
    //SalesOps Admin terminates the deal after Opp Reg submission by partner
    static testMethod void testTerminateDeal_AuthorizedAndValid() {
        
        //setEnterpriseOpptyInfra(string ProdName, string ProdFamily, string ProdCode, boolean isDealEnabled, string PriceBookName, decimal StandardPrice, decimal CustomPrice, string BaseSKU, string Term
        map<string, Object> mapOpptyInfa = Test_COMM_Factory.setEnterpriseOpptyInfra(ProdName, ProdCode, ProdFamily,true, PriceBookName, 1000, 1500, BaseSKU, Term);
        genericMock fakeResp = new genericMock(200,'Complete', '<?xml version="1.0" encoding="UTF-8"?><soapenv:Envelope xmlns:soapenv="http://schemas.xmlsoap.org/soap/envelope/"><soapenv:Header/><soapenv:Body><ns:SyncServiceResponse xmlns:ns="http://nvidiasapemsconnector.nvidiaaxis2service.nvidia.smps.gmlto.com"><ns:return xmlns:ax21="http://dto.nvidiaaxis2service.nvidia.smps.gmlto.com/xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ax21:SyncResponse"><ax21:errorMessage></ax21:errorMessage><ax21:statusCode>success</ax21:statusCode><ax21:syncType>PartnerUser</ax21:syncType></ns:return></ns:SyncServiceResponse></soapenv:Body></soapenv:Envelope>',null);
        System.Test.setMock(HttpCalloutMock.class, fakeResp);
        //get the infra objects back from the map
        Account partnerAccount = mapOpptyInfa.get('partneraccount') != null ? (Account) mapOpptyInfa.get('partneraccount') : new Account();
        Contact partnerContact = mapOpptyInfa.get('partnercontact') != null ? (Contact) mapOpptyInfa.get('partnercontact') : new Contact();
        Account customerAccount = mapOpptyInfa.get('customeraccount') != null ? (Account) mapOpptyInfa.get('customeraccount') : new Account();
        User partnerUser = mapOpptyInfa.get('partneruser') != null ? (User) mapOpptyInfa.get('partneruser') : new User();
        User pbm = mapOpptyInfa.get('pbm') != null ? (User) mapOpptyInfa.get('pbm') : new User();
        User pbmmanager = mapOpptyInfa.get('pbmmanager') != null ? (User) mapOpptyInfa.get('pbmmanager') : new User();
        User salesopsadmin = mapOpptyInfa.get('salesopsadmin') != null ? (User) mapOpptyInfa.get('salesopsadmin') : new User();
        PricebookEntry pricebookentryRecord = mapOpptyInfa.get('pricebookentry') != null ? (pricebookentry) mapOpptyInfa.get('pricebookentry') : new PricebookEntry();
        map<string, Id> mapProfNameId = mapOpptyInfa.get('mapprofnameid') != null ? (map<string, id>) mapOpptyInfa.get('mapprofnameid') : new map<string, Id>();
        map<String, Id> mapRTNameId = mapOpptyInfa.get('maprectypenameid') != null ? (map<string, Id>) mapOpptyInfa.get('maprectypenameid') : new map<string, Id>();
        
        Opportunity enterpriseSalesOppty;
        ApexPages.Standardcontroller stdCon;
        
        User currUser = [Select Id From User where Id = :userinfo.getUserId()];
        
        system.debug('***currUser: ' + currUser);
        
        list<Account> lstAccount = new list<Account>(); 
        system.runAs(currUser){
            customerAccount.SAP_Customer_Number__c = PEC_SAPCustomerNumber;
            partnerAccount.SAP_Customer_Number__c = NPNVAR_SAPCustomerNumber;
            lstAccount.add(customerAccount);
            lstAccount.add(partnerAccount);
            update lstAccount;
            
            DateTime dt = DateTime.now();
            SBQQ__QuoteTemplate__c Quotetemplate = new SBQQ__QuoteTemplate__c (name ='Approved Quote - Initial Sale');
            insert Quotetemplate;
            SBQQ__QuoteTemplate__c Quotetemplate1 = new SBQQ__QuoteTemplate__c (name ='Budgetary Quote - Initial Sale');
            insert Quotetemplate1;
            
           SOQ_QuoteCreation_Settings__c objSOQCS = new SOQ_QuoteCreation_Settings__c(Approved_Quote_Template_Id__c=Quotetemplate.id, Default_Template_Id__c=Quotetemplate1.id, Quote_Type_c__c = 'Quote', BATCHJOB_OppCreationCutOffDateTime__c=dt, Initial_Status__c = 'Draft', RecordTypeId__c=Schema.SObjectType.SBQQ__Quote__c.getRecordTypeInfosByName().get('Initial Enterprise Sales Quote').getRecordTypeId());
           insert objSOQCS;
            //Create the Enterprise Opportunity with Deal Registration
            //createDealRegOpportunity(string name, Id recordTypeId, string stageName, Date closeDate, Id pricebook2Id, Id customerAccountId, Id partnerAccountId){
            System.debug('Limits.getLimitQueries()- '+ Limits.getLimitQueries());
            System.debug('Limits.getQueries()- '+ Limits.getQueries());
            enterpriseSalesOppty = Test_COMM_Factory.createDealRegOpportunity('Enterprise Sales Oppty1', mapRTNameId.get(OPPTY_RT_ENTERPRISESALESOPPTY), COMM_Constants.OPPTY_STAGE_PROSPECTING, System.Today(), pricebookentryRecord.PriceBook2Id, customerAccount.Id, partnerAccount.Id);
            System.debug('Limits.getQueries()- '+ Limits.getQueries());        
            
            Test.startTest();
                //set Deal Reg fields in Enterprise Opportunity
                Test_COMM_Factory.setDealRegFieldsInOpportunity(enterpriseSalesOppty.Id, customerAccount.Id, partnerAccount.Id);
                System.debug('Limits.getQueries()- '+ Limits.getQueries());
                //Add Opportunity Line Items
                OpportunityLineItem oli = new OpportunityLineItem(OpportunityId = enterpriseSalesOppty.Id, PricebookEntryId = pricebookentryRecord.Id, Quantity = 4, UnitPrice = pricebookentryRecord.UnitPrice);
                insert oli;
                System.debug('Limits.getQueries()- '+ Limits.getQueries());
            
                //Terminate the Deal
                //---------------------------------------------------------
                PageReference pageRefTerminateDeal = new PageReference('/apex/CRM_DR_TerminateDeal');
                Test.setCurrentPage(pageRefTerminateDeal);
                ApexPages.currentPage().getParameters().put('Id', enterpriseSalesOppty.Id);
                    
                //Set the reasonForTermination contoller member and call the terminateDeal controller method
                CRM_DR_TerminateDeal_cls terminateDealCtlr = new CRM_DR_TerminateDeal_cls(stdCon);
                terminateDealCtlr.reasonForTermination = 'Terminated From Test class';
                pageRefTerminateDeal = terminateDealCtlr.terminateDeal();
                //---------------------------------------------------------
                System.debug('Limits.getQueries()--> InSTT '+ Limits.getQueries());    
                    
                Opportunity enterpriseSalesOpptyQry = [Select DR_Reason_For_Termination__c, DR_Is_Terminated__c, DR_Deal_Status__c From Opportunity Where id = :enterpriseSalesOppty.Id];
                System.debug('Limits.getQueries()--> InSTT '+ Limits.getQueries());    
                system.debug('***enterpriseSalesOpptyQry: ' + enterpriseSalesOpptyQry);
                system.assert(enterpriseSalesOpptyQry.DR_Is_Terminated__c == true);
            Test.stopTest();
        }
    }
    
}