force-app/main/default/objects/Account/fields/SAP_Customer_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Customer_Number__c</fullName>
    <externalId>true</externalId>
    <label>SAP Customer Number</label>
    <length>10</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Account/recordTypes/PartnerAccount.recordType-meta.xml
<RecordType>
    <fullName>PartnerAccount</fullName>
    <active>true</active>
    <label>Partner Account</label>
</RecordType>

force-app/main/default/objects/Contact/fields/Portal_Groups__c.field-meta.xml
<CustomField>
    <fullName>Portal_Groups__c</fullName>
    <label>Permissions &amp; Group Assignments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>All Partner Content</fullName>
            </value>
            <value>
                <fullName>Arrow Embedded Edge</fullName>
            </value>
            <value>
                <fullName>ATP</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Compute DGX Portal Full</fullName>
            </value>
            <value>
                <fullName>Compute Portal Full</fullName>
            </value>
            <value>
                <fullName>CSP Compute DGX Elite</fullName>
            </value>
            <value>
                <fullName>CSP Compute DGX Preferred</fullName>
            </value>
            <value>
                <fullName>CSP Compute Elite</fullName>
            </value>
            <value>
                <fullName>CSP Compute Preferred</fullName>
            </value>
            <value>
                <fullName>CSP Virtualization Elite</fullName>
            </value>
            <value>
                <fullName>CSP Virtualization Preferred</fullName>
            </value>
            <value>
                <fullName>CSP Visualization Elite</fullName>
            </value>
            <value>
                <fullName>CSP Visualization Preferred</fullName>
            </value>
            <value>
                <fullName>DGX Partner Content</fullName>
            </value>
            <value>
                <fullName>DISTI Compute DGX Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Compute Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Embedded Edge Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Virtualization Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Visualization Preferred</fullName>
            </value>
            <value>
                <fullName>EDU Lead Registration</fullName>
            </value>
            <value>
                <fullName>Embedded Edge Elite</fullName>
            </value>
            <value>
                <fullName>Embedded Edge Portal Full</fullName>
            </value>
            <value>
                <fullName>Embedded Edge Preferred</fullName>
            </value>
            <value>
                <fullName>Entitlements</fullName>
            </value>
            <value>
                <fullName>Fed SI Compute DGX Elite</fullName>
            </value>
            <value>
                <fullName>Fed SI Compute DGX Preferred</fullName>
            </value>
            <value>
                <fullName>Fed SI Compute Elite</fullName>
            </value>
            <value>
                <fullName>Fed SI Compute Preferred</fullName>
            </value>
            <value>
                <fullName>Fed SI Embedded Edge Elite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner Contact</label>
</RecordType>

force-app/main/default/objects/Portal_Permission_Sets__c/Portal_Permission_Sets__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : This is a custom object used to maintain SFDC Permission Sets assigned to each portal groups</description>
    <label>Portal Permission Set</label>
    <nameField>
        <label>SFDC Permission Set</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Permission Sets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Portal_Permission_Sets__c/fields/Portal_Groups__c.field-meta.xml
<CustomField>
    <fullName>Portal_Groups__c</fullName>
    <label>Permissions &amp; Group Assignments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Compute DGX Portal Full</fullName>
            </value>
            <value>
                <fullName>Compute Portal Full</fullName>
            </value>
            <value>
                <fullName>DISTI Compute DGX Elite</fullName>
            </value>
            <value>
                <fullName>DISTI Compute DGX Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Compute Elite</fullName>
            </value>
            <value>
                <fullName>DISTI Compute Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Virtualization Elite</fullName>
            </value>
            <value>
                <fullName>DISTI Virtualization Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Visualization Elite</fullName>
            </value>
            <value>
                <fullName>DISTI Visualization Preferred</fullName>
            </value>
            <value>
                <fullName>EDU Lead Registration</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Embedded Edge Portal Full</fullName>
            </value>
            <value>
                <fullName>Entitlements</fullName>
            </value>
            <value>
                <fullName>GRID VCA Legacy</fullName>
            </value>
            <value>
                <fullName>GRID VGX Legacy</fullName>
            </value>
            <value>
                <fullName>IP Portal Lite</fullName>
            </value>
            <value>
                <fullName>Leads &amp; Opportunities</fullName>
            </value>
            <value>
                <fullName>Manage Contacts</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Marketing Hub</fullName>
            </value>
            <value>
                <fullName>MDF</fullName>
            </value>
            <value>
                <fullName>MDFV3</fullName>
            </value>
            <value>
                <fullName>NFR SW License Request</fullName>
            </value>
            <value>
                <fullName>NPN Compliance(SFDC)</fullName>
            </value>
            <value>
                <fullName>NPN Compliance(Tableau)</fullName>
            </value>
            <value>
                <fullName>NPN QPB Statement</fullName>
            </value>
            <value>
                <fullName>NPN Submit POS</fullName>
            </value>
            <value>
                <fullName>OEM Compute Elite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Portal_Public_Groups__c/Portal_Public_Groups__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : This is a custom object used to maintain public groups assigned to each portal groups.</description>
    <label>Portal Public Group</label>
    <nameField>
        <label>Permissions &amp; Group Assignments</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Public Groups</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Portal_Public_Groups__c/fields/Portal_Public_Group__c.field-meta.xml
<CustomField>
    <fullName>Portal_Public_Group__c</fullName>
    <label>SFDC Public Group</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Arrow Embedded Edge</fullName>
            </value>
            <value>
                <fullName>Community Content</fullName>
            </value>
            <value>
                <fullName>CSP Compute DGX Elite</fullName>
            </value>
            <value>
                <fullName>CSP Compute DGX Preferred</fullName>
            </value>
            <value>
                <fullName>CSP Compute Elite</fullName>
            </value>
            <value>
                <fullName>CSP Compute Preferred</fullName>
            </value>
            <value>
                <fullName>CSP Virtualization Elite</fullName>
            </value>
            <value>
                <fullName>CSP Virtualization Preferred</fullName>
            </value>
            <value>
                <fullName>CSP Visualization Elite</fullName>
            </value>
            <value>
                <fullName>CSP Visualization Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Compute DGX Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Compute Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Virtualization Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Visualization Preferred</fullName>
            </value>
            <value>
                <fullName>Embedded Edge Elite</fullName>
            </value>
            <value>
                <fullName>Embedded Edge Preferred</fullName>
            </value>
            <value>
                <fullName>EMEAI Training Users</fullName>
            </value>
            <value>
                <fullName>Fed SI Compute Elite</fullName>
            </value>
            <value>
                <fullName>Fed SI Compute Preferred</fullName>
            </value>
            <value>
                <fullName>Fed SI Embedded Edge Elite</fullName>
            </value>
            <value>
                <fullName>Fed SI Embedded Edge Preferred</fullName>
            </value>
            <value>
                <fullName>Fed SI Virtualization Elite</fullName>
            </value>
            <value>
                <fullName>Fed SI Virtualization Preferred</fullName>
            </value>
            <value>
                <fullName>Fed SI Visualization Elite</fullName>
            </value>
            <value>
                <fullName>Fed SI Visualization Preferred</fullName>
            </value>
            <value>
                <fullName>GRID VCA Partner Users</fullName>
            </value>
            <value>
                <fullName>GRID VGX Partner Users</fullName>
            </value>
            <value>
                <fullName>Industry Focus AEC</fullName>
            </value>
            <value>
                <fullName>Industry Focus Automotive</fullName>
            </value>
            <value>
                <fullName>Industry Focus Financial Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NVIDIASFDCOrgInstanceInitializ_bat_test.cls
/*
	2019.08.14 - test class for  from NVIDIASFDCOrgInstanceInitializer_batch
		- Upates all email addresses of external User and Contact records 
*/

@isTest(SeeAllData=false)
private class NVIDIASFDCOrgInstanceInitializ_bat_test {

    static testMethod void testCreateExternalUserAndUpdateTheirEmailAddress() {
        string PPG_COMMUNITY = 'Community';
		string PPS_COMM_CONTENT = 'Community Content';
		string PP_COMM_LITE = 'PP_COMM_LITE_HOME_TAB';
		
		//Set Community Settings custom settings
		Test_COMM_Factory.set_CommunitySettings();
		
		//create Partner Portal Account
        //---------------------------------------------
        map<String, Id> mapPP_PartnerProgramAccount_RT = COMM_Utility.getRTsByName(COMM_Constants.SOBJECT_ACCOUNT, COMM_Constants.ACCOUNT_RT_PARTNER_ACCOUNT);
        map<String, Id> mapPP_PartnerContact_RT = COMM_Utility.getRTsByName(COMM_Constants.SOBJECT_CONTACT, COMM_Constants.CONTACT_RT_PARTNER_CONTACT);
        map<string, Id> mapPP_TPP_Generic_Prof = COMM_Utility.getProfsByName(COMM_Constants.PROF_PP_TPP_GENERIC);
        
        Portal_Permission_Sets__c oPPS;
        Portal_Public_Groups__c oPPG;
        Account partnerAccount;
        list<Contact> lstPartnerContact;
        User currUser = [Select Id From User where Id = :UserInfo.getUserId()];
        
        system.runAs(currUser){
	        //Create Portal Permission Sets object record
			oPPS = new Portal_Permission_Sets__c (Name = PP_COMM_LITE, Portal_Groups__c = PPG_COMMUNITY);
			database.SaveResult lstDSRPPS = Database.insert(oPPS, false); 
			
			//Create Portal Public Groups object record
			 oPPG= new Portal_Public_Groups__c (Name = PPG_COMMUNITY, Portal_Public_Group__c = PPS_COMM_CONTENT);
			database.SaveResult lstDSRPPG = Database.insert(oPPG, false); 
			
	        
	        //(string name, string recordTypeId, boolean isPartner, boolean isCustomerPortal)
	        partnerAccount = Test_COMM_Factory.createAccount('Test PP Account1', mapPP_PartnerProgramAccount_RT.get(COMM_Constants.ACCOUNT_RT_PARTNER_ACCOUNT), true, false);
	        /*
	        long lRandom = Math.roundToLong(Math.random() * 9999);
			long  uniqueVal = System.currentTimeMillis();
			string uniqueNameExt = lRandom + '' + uniqueVal;
	        partnerAccount.SAP_customer_Number__c = uniqueNameExt.right(4)+uniqueNameExt.right(6);
	        update partnerAccount;
	       */
	        //Check if the Account is a partner account 
	        system.assertEquals(partnerAccount.IsPartner, true);
	        //---------------------------------------------
         
        
        
	        //Create a Partner Contact 
	        //---------------------------------------------
	        //Contact partnerContact = Test_COMM_Factory.createContact('Test', 'test1@nv.com', partnerAccount.Id, mapPP_PartnerContact_RT.get(COMM_Constants.CONTACT_RT_PARTNER_CONTACT), COMM_Constants.CON_DEFAULT_CONTENT_TYPE_NPN);
	        
	        //Create N number of Partner Contacts
	        //---------------------------------------------
	        //createContacts(Id accountId, string recordTypeId, string strPortalGroups, integer iNumOfUsers){
	        lstPartnerContact = Test_COMM_Factory.createContacts(partnerAccount.Id, mapPP_PartnerContact_RT.get(COMM_Constants.CONTACT_RT_PARTNER_CONTACT), PPG_COMMUNITY, 10);
	        
        }
        //Create the Portal User for those N Partner Contacts
        //---------------------------------------------
        list<User> lstPartnerUser = Test_COMM_Factory.createUsers(lstPartnerContact, mapPP_TPP_Generic_Prof.get(COMM_Constants.PROF_PP_TPP_GENERIC)); 
        
        //---------------------------------------------
        
		
		Test.startTest();

     		NVIDIASFDCOrgInstanceInitializer_batch oBC = new NVIDIASFDCOrgInstanceInitializer_batch();
     		Database.executeBatch(oBC, 100);

   		Test.stopTest();
        
    }
}