force-app/main/default/objects/Account/fields/Support_Level__c.field-meta.xml
<CustomField>
    <fullName>Support_Level__c</fullName>
    <description>Picklist to show the type of Support a customer is entitled. Case will be routed Based on &quot;Support Level&quot;.</description>
    <label>Support Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>24x7 Escalated Remote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Announcement__c/Announcement__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : Custom Object for NVIDIA to create Announcements.</description>
    <label>Announcement</label>
    <nameField>
        <label>Announcement Title</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Announcement__c/fields/Access_Level__c.field-meta.xml
<CustomField>
    <fullName>Access_Level__c</fullName>
    <label>Access Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Generic</fullName>
            </value>
            <value>
                <fullName>Product Specific</fullName>
            </value>
            <value>
                <fullName>Entitlement Specific</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
            <value>
                <fullName>Customer Specific</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Announcement__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Announcements</relationshipLabel>
    <relationshipName>Announcements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Asset/fields/PAKID__c.field-meta.xml
<CustomField>
    <fullName>PAKID__c</fullName>
    <label>PAKID</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>Text(Product2.Product_Line__c)</formula>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/SAP_Delivery_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Delivery_Number__c</fullName>
    <label>SAP Delivery Number</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Community_User_Active__c.field-meta.xml
<CustomField>
    <fullName>Community_User_Active__c</fullName>
    <formula>Community_User__r.IsActive</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Community User : Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Contact/fields/Community_User_Type__c.field-meta.xml
<CustomField>
    <fullName>Community_User_Type__c</fullName>
    <formula>IF( !ISBLANK(Community_User__c) &amp;&amp;  Community_User__r.IsActive  = true &amp;&amp; CONTAINS(Community_User__r.Profile.Name, &quot;NPN Partner Community&quot;) &amp;&amp; (is_GRID_Contact__c = true ||  is_DGX_Contact__c  = true), &quot;NPN with ESP&quot;, 

IF( !ISBLANK(Community_User__c) &amp;&amp;  Community_User__r.IsActive  = true &amp;&amp; CONTAINS(Community_User__r.Profile.Name, &quot;NPN Partner Community&quot;) &amp;&amp; NOT(is_GRID_Contact__c = true ||  is_DGX_Contact__c  = true), &quot;NPN&quot;,

IF( !ISBLANK(Community_User__c) &amp;&amp;  Community_User__r.IsActive  = true &amp;&amp; CONTAINS(Community_User__r.Profile.Name, &quot;NVES Community User Non-Admin&quot;), &quot;ESP Non-Admin&quot;,

IF( !ISBLANK(Community_User__c) &amp;&amp;  Community_User__r.IsActive  = true &amp;&amp; CONTAINS(Community_User__r.Profile.Name, &quot;ESP Community User&quot;), &quot;ESP&quot;,

IF( !ISBLANK(Community_User__c) &amp;&amp; Community_User__r.IsActive = true &amp;&amp; CONTAINS(Community_User__r.Profile.Name, &quot;Community Lite Profile&quot;) &amp;&amp; (is_GRID_Contact__c = true ||  is_DGX_Contact__c  = true), &quot;Community with ESP&quot;, 

IF( !ISBLANK(Community_User__c) &amp;&amp; Community_User__r.IsActive = true, &quot;Others&quot;, 

IF( !ISBLANK(Community_User__c) &amp;&amp;  Community_User__r.IsActive  = false &amp;&amp; CONTAINS(Community_User__r.Profile.Name, &quot;NPN Partner Community&quot;) &amp;&amp; (is_GRID_Contact__c = true ||  is_DGX_Contact__c  = true), &quot;Inactive NPN with ESP&quot;, 

IF( !ISBLANK(Community_User__c) &amp;&amp; Community_User__r.IsActive = false &amp;&amp; CONTAINS(Community_User__r.Profile.Name, &quot;NPN Partner Community&quot;) &amp;&amp; NOT(is_GRID_Contact__c = true || is_DGX_Contact__c = true), &quot;Inactive NPN&quot;, 

IF( !ISBLANK(Community_User__c) &amp;&amp;  Community_User__r.IsActive  = false &amp;&amp; CONTAINS(Community_User__r.Profile.Name, &quot;ESP Community User&quot;), &quot;Inactive ESP&quot;, 

IF( !ISBLANK(Community_User__c) &amp;&amp; Community_User__r.IsActive = false &amp;&amp; CONTAINS(Community_User__r.Profile.Name, &quot;Community Lite Profile&quot;) &amp;&amp; (is_GRID_Contact__c = true ||  is_DGX_Contact__c  = true), &quot;Inactive Community with ESP&quot;, 

IF( !ISBLANK(Community_User__c) &amp;&amp; Community_User__r.IsActive = false, &quot;Inactive Others&quot;,  

&quot;&quot; 

)  

)   

)  

)  

)   

)  

) 

)

)

)

)</formula>
    <label>Community User Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CustomerAnnouncement__c/CustomerAnnouncement__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : Junction Object to create Announcement records to Accounts based on Announcement creation criteria like Generic, Product and Entitlement</description>
    <label>Announcement</label>
    <nameField>
        <label>Announcement</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Announcements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/CustomerAnnouncement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Announcements</relationshipLabel>
    <relationshipName>Announcements</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/CustomerAnnouncement__c/fields/Announcement__c.field-meta.xml
<CustomField>
    <fullName>Announcement__c</fullName>
    <label>Announcement</label>
    <referenceTo>Announcement__c</referenceTo>
    <relationshipLabel>Announcements</relationshipLabel>
    <relationshipName>Announcements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Entitlement_Status__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Status__c</fullName>
    <formula>IF ( Text(Order_Type__c) = &apos;ZMRS&apos;  || Text(Order_Type__c) = &apos;ZKB&apos; , &quot;MRS&quot;,
	IF ( ISBLANK(SAP_Order__c) &amp;&amp; ISBLANK(Subscription__c), &quot;Removed&quot;,
		IF ( TODAY() &gt;= StartDate &amp;&amp; TODAY() &lt;= EndDate, &quot;Active&quot;,
			IF(StartDate &gt; TODAY(), &quot;Inactive&quot;, 
						&quot;Expired&quot;
			)
		)
	)
)</formula>
    <label>Entitlement Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Hardware_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Hardware_Serial_Number__c</fullName>
    <label>Hardware Serial Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Link_Asset__c.field-meta.xml
<CustomField>
    <fullName>Link_Asset__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Link Asset</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/PAK_ID__c.field-meta.xml
<CustomField>
    <fullName>PAK_ID__c</fullName>
    <label>PAK ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Created for backend purposes only.</description>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Product_Description__c.field-meta.xml
<CustomField>
    <fullName>Product_Description__c</fullName>
    <formula>Service_Product__r.Description</formula>
    <label>Product Description</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Renewed_Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Renewed_Entitlement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Renewed Entitlement</label>
    <referenceTo>Entitlement</referenceTo>
    <relationshipLabel>Original Entitlements</relationshipLabel>
    <relationshipName>Original_Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Renewed_PAK_ID__c.field-meta.xml
<CustomField>
    <fullName>Renewed_PAK_ID__c</fullName>
    <description>Rename this to Renewed PAK ID if CPQ decides to use both PAK ID and Renewed PAK ID in future. Right now, CPQ is not populating any values in PAK ID.</description>
    <label>Renewed PAK ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/SAP_Delivery_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Delivery_Number__c</fullName>
    <formula>SAP_Order__r.SAP_Delivery__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>SAP Delivery Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Service_Product__c.field-meta.xml
<CustomField>
    <fullName>Service_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is created to store Product lookup copied from Subscription or manually entered for MRS Products.</description>
    <label>Service Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Entitlements (Service Product)</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Support_Level__c.field-meta.xml
<CustomField>
    <fullName>Support_Level__c</fullName>
    <formula>Text(Service_Product__r.Support_level__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Support Level</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Type__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Automotive Datacenter</fullName>
            </value>
            <value>
                <fullName>CMP</fullName>
            </value>
            <value>
                <fullName>DC GPU</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
            <value>
                <fullName>Educational Services</fullName>
            </value>
            <value>
                <fullName>Fleet Command</fullName>
            </value>
            <value>
                <fullName>GeForce</fullName>
            </value>
            <value>
                <fullName>Grid</fullName>
            </value>
            <value>
                <fullName>Grid Hardware</fullName>
            </value>
            <value>
                <fullName>HPC SDK</fullName>
            </value>
            <value>
                <fullName>Jetson</fullName>
            </value>
            <value>
                <fullName>NGC-Ready Services</fullName>
            </value>
            <value>
                <fullName>Parabricks</fullName>
            </value>
            <value>
                <fullName>ProViz</fullName>
            </value>
            <value>
                <fullName>RTX</fullName>
            </value>
            <value>
                <fullName>RTX Blade Server</fullName>
            </value>
            <value>
                <fullName>Titan</fullName>
            </value>
            <value>
                <fullName>Value-Added Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SLA_Scope__c.field-meta.xml
<CustomField>
    <fullName>SLA_Scope__c</fullName>
    <label>SLA Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All with same Product Line</fullName>
            </value>
            <value>
                <fullName>All with same Serial Number</fullName>
            </value>
            <value>
                <fullName>Only self</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Support_level__c.field-meta.xml
<CustomField>
    <fullName>Support_level__c</fullName>
    <label>Support level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>24x7 Escalated Remote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SLA_Settings__mdt/SLA_Settings__mdt.object-meta.xml
<CustomObject>
    <description>This metadata type will have information about SLA Process variables based on Support Level.</description>
    <label>SLA Settings</label>
    <pluralLabel>SLA Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SLA_Settings__mdt/fields/Entitlement_Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Process_Name__c</fullName>
    <label>Entitlement Process Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SLA_Settings__mdt/fields/SLA_By_Product_Line_Label__c.field-meta.xml
<CustomField>
    <fullName>SLA_By_Product_Line_Label__c</fullName>
    <defaultValue>&apos;All with same Product Line&apos;</defaultValue>
    <label>SLA By Product Line Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SLA_Settings__mdt/fields/SLA_By_SN_Label__c.field-meta.xml
<CustomField>
    <fullName>SLA_By_SN_Label__c</fullName>
    <defaultValue>&apos;All with same Serial Number&apos;</defaultValue>
    <label>SLA By SN Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TriggerEntitlementHelper.cls
/**************************************************************************************************
* Name       : TriggerEntitlementHelper
* Purpose    : Helper class for TriggerEntitlement Trigger 
***************************************************************************************************
* Author            | Version    | Created Date    | Description
***************************************************************************************************
*Perficient         | 1.0        | 12/13/2017      | Initial Draft
*Perficient         | 1.0        | 12/25/2017      | Final Draft
*Perficient         | 1.1        | 07/03/2018      | Added two methods AddAnnouncement and getAnnoucementsToAddByAccount
*Akhilesh Gupta     | 2.0        | 12/12/2019      | Updated code to implement Trigger Handler
| Add Logic to update Entitlement Name  
| Remove code responsible to assign Knowledge Category Permissions
*Akhilesh Gupta     | 2.0        | 02/26/2020      | SDS-2064 - Updated "UpdateEntitlement" function to use support level from Product 
- User new Constants framework, use ESP_Utility functions instead of ServiceCloudUtils.
* Nilesh Adkar      2.1        12/01/2020        SDS-2020 ESPContactNVIDIARenewalsButton
* Nilesh Adkar      2.2        01/01/2021        SDS-2432 : Service: Registration Reminder for Support Portal. Method Added checkSupportPortalRegistration
* Akhilesh Gupta    | 3.0        | 02/15/2021      |SDS-2901: Updated logic for 24x7 Business Critical.
**************************************************************************************************/
public class TriggerEntitlementHelper extends NV_TriggerHandler {
    public list<Entitlement> oldRecords;
    private static list<Entitlement> newRecords;
    private static map<Id, Entitlement> oldRecordsMap;
    private static map<Id, Entitlement> newRecordsMap;
    public static boolean DISABLE_TRIGGER = FALSE;
    public override void init() {
        OBJECT_NAME = 'Entitlement';
        oldRecords = trigger.old;
        newRecords = trigger.New;
        if(oldRecords != null)
            oldRecordsMap = new map<Id, Entitlement>(oldRecords);
        if(newRecords != null && Trigger.isUpdate)
            newRecordsMap = new map<Id, Entitlement>(newRecords);
        System.debug('Old Records' + oldRecords + '1');
        System.debug('New Records' + trigger.New + '1'); 
    }
    public override void beforeInsert() {
        //SDS-2901 
        //TriggerEntitlementHelper.UpdateEntilementProcess();
        //TriggerEntitlementHelper.updateAccountSupportLevel();        
        TriggerEntitlementHelper.UpdateName();
        TriggerEntitlementHelper.updateAssetId();
        //TriggerEntitlementHelper.LinkwithOriginalEntitlement();
    }
    public override void beforeUpdate() {
        //SDS-2901 
        //TriggerEntitlementHelper.updateAccountSupportLevel();
        TriggerEntitlementHelper.UpdateName();
        TriggerEntitlementHelper.updateAssetId();
        //TriggerEntitlementHelper.LinkwithOriginalEntitlement();
    }
    public override void afterInsert() {
        //SDS-2901 
        //TriggerEntitlementHelper.UpdateEntilementProcess();
        ESP_EntitlementUtils.checkForProductUpgrade(newRecords); //SDS-2908
        TriggerEntitlementHelper.AddAnnouncement(oldRecordsMap,newRecords);
    }
    public override void afterUpdate() {
        //SDS-2901 
        //TriggerEntitlementHelper.UpdateEntilementProcess();
        ESP_EntitlementUtils.checkForProductUpgrade(newRecords); //SDS-2908
        //TriggerEntitlementHelper.RemoveUpdatePermissionSet(trigger.oldMap,trigger.New);
        TriggerEntitlementHelper.AddAnnouncement(oldRecordsMap,newRecords);
    }
    
   /* public static void LinkwithOriginalEntitlement(){
        //set<String> PAKIDset = new set<String>();
        map<String, Entitlement> entbyRenewedPAKIDMap = new map<String, Entitlement>();
        for(Entitlement ent : newRecords){
            if(!string.IsBlank(ent.Renewed_PAK_ID__c)) {
                entbyRenewedPAKIDMap.put(ent.Renewed_PAK_ID__c, ent);
            } //else {
                //ent.Renewed_Entitlement__c = NULL;
            //}
            
            //Get Old Renewed PAKID's to delink entitlements.
            if(trigger.isUpdate) {
                Entitlement oldRecord = oldRecordsMap.get(ent.Id);
                if(!string.IsBlank(oldRecord.Renewed_PAK_ID__c) && ent.Renewed_PAK_ID__c != oldRecord.Renewed_PAK_ID__c) {
                    entbyRenewedPAKIDMap.put(oldRecord.Renewed_PAK_ID__c, ent);
                }
            }
        }
        
        if(entbyRenewedPAKIDMap.isEmpty())
            return;
        
        //Find ExistingEntitlement where NewEntitlement.RenewedPAKID = ExistingEntitlement.PAKID
        list<Entitlement> originalEntitlements = [select Id, Renewed_PAK_ID__c, PAK_ID__c, AssetId from Entitlement where PAK_ID__c in: entbyRenewedPAKIDMap.keySet()];
        
        list<Entitlement> entitlementsToUpdate = new list<Entitlement>();
        //IF found, Populate ExistingEntitlement.RenewedEntitlement = NewEntitlement
        for(Entitlement originalEnt : originalEntitlements) {
            //if(originalEnt.PAK_ID__c != originalEnt.Renewed_PAK_ID__c) {
                if(entbyRenewedPAKIDMap.containsKey(originalEnt.PAK_ID__c)) {
                    Entitlement renewedEntitlement = entbyRenewedPAKIDMap.get(originalEnt.PAK_ID__c);
                    if(originalEnt.PAK_ID__c == renewedEntitlement.Renewed_PAK_ID__c) {
                        if(originalEnt.Id != renewedEntitlement.Id) {
                            renewedEntitlement.AssetId = originalEnt.AssetId;
                            originalEnt.Renewed_Entitlement__c = renewedEntitlement.Id;
                        }
                    } else {
                        renewedEntitlement.AssetId = NULL;
                        originalEnt.Renewed_Entitlement__c = NULL;
                    }
                    if(renewedEntitlement.Id != originalEnt.Id)
                        entitlementsToUpdate.add(originalEnt);
                }
            //}
        }
        
        //bkpif(!entitlementsToUpdate.isEmpty())
        //bkp    update entitlementsToUpdate;
        ////update originalEntitlements;
    }
    
    */
    public static void updateAccountSupportLevel() {
        /*//set<Id> accountIdsToProcess = new set<Id>();
        List<Account> accList = new list<Account>();
        for(Entitlement ent: newRecords) {
            if(
                //acc != null && 
                //acc.Support_Level__c == ESP_Utility.ESPConstants.SLA_24X7SUPPORT && 
                trigger.isInsert && ent.Support_level__c == ESP_Utility.ESPConstants.SLA_24X7SUPPORT 
                || (
                    trigger.isUpdate && 
                    (oldRecordsMap.get(ent.Id).SlaProcessId != ent.SlaProcessId || oldRecordsMap.get(ent.Id).Support_level__c != ent.Support_level__c)
                )
            ){
                    System.debug('ent.SlaProcessId = ' + ent.SlaProcessId);
                    //ent.SlaProcessId = slaProcessId; //SDS-2901
                    //accountIdsToProcess.add(ent.AccountId);
                    accList.add(new Account(Id=ent.AccountId, Support_Level__c=ESP_Utility.ESPConstants.SLA_24X7SUPPORT));
                }
        }
        
        //System.debug('accountIdsToProcess = ' + accountIdsToProcess);
        //SDS-2901
        //if(!accountIdsToProcess.isEmpty()) {
        //    updateAccountSupportLevel(accountIdsToProcess);
        //}
        
        system.debug('accList: '+ accList);
        if(!accList.isEmpty()) {
            Account_tgr_cls.UPDATE_ALL_ENTITLEMENTS = TRUE;
            update accList;
			Account_tgr_cls.UPDATE_ALL_ENTITLEMENTS = FALSE;
        } */
    }
    /*
This function auto populates Entitlement Process Name for Business Critical Accounts
*/
    /*public static boolean UPDATE_ENT_PROCESS = TRUE;
    public static void UpdateEntilementProcess(){
        
        if(UPDATE_ENT_PROCESS) {
            UPDATE_ENT_PROCESS = FALSE;*/
            //set<Id> SlaProcessIdSet = new set<Id>();
          /*Set<Id> acctIdSet = new Set<Id>();
            for(Entitlement ent : newRecords){
                acctIdSet.add(ent.AccountId);
            }
            if(acctIdSet.isEmpty())// || EntProcessList.isEmpty()) 
                return;
            Map<Id,Account> acctMap = new Map<Id, Account>([SELECT Id, Support_Level__c FROM account WHERE Id IN :acctIdSet]);
            */
            
            /*SLA_Settings__mdt slaSetting = ESP_Utility.getSLASetting(ESP_Utility.ESPConstants.SLA_24X7SUPPORT);
            List<SlaProcess> EntProcessList;
            if(slaSetting != NULL)
                EntProcessList = [SELECT Id, Name FROM SlaProcess WHERE name =: slaSetting.Entitlement_Process_Name__c];
            
            Id slaProcessId = (EntProcessList.isEmpty()) ? NULL : EntProcessList[0].Id;
			*/
           /* set<Id> accountIdsToProcess = new set<Id>();
            for(Entitlement ent: newRecords) {
                //Account acc = acctMap.get(ent.AccountId); //SDS-2901
                //system.debug('1242019: '+ acc + 'ent: '+ ent); //SDS-2901
                if(
                    //acc != null && 
                    //acc.Support_Level__c == ESP_Utility.ESPConstants.SLA_24X7SUPPORT && 
                    (ent.Support_level__c == ESP_Utility.ESPConstants.SLA_24X7SUPPORT && ent.SlaProcessId == null) 
                    || (oldRecordsMap != null && !oldRecordsMap.isEmpty() && oldRecordsMap.get(ent.Id).SlaProcessId != ent.SlaProcessId)){
                        System.debug('ent.SlaProcessId = ' + ent.SlaProcessId);
                       //ent.SlaProcessId = slaProcessId; //SDS-2901
                       accountIdsToProcess.add(ent.AccountId);
                   }
            }
            
            System.debug('accountIdsToProcess = ' + accountIdsToProcess);
            	
            //SDS-2901
            if(!accountIdsToProcess.isEmpty()) {
                updateAccountSupportLevel(accountIdsToProcess);
				//if(System.IsFuture() || system.isBatch())
                //	return;
                //System.debug('accountIdsToProcess = ' + accountIdsToProcess);
                //Account_tgr_cls.managePlaceholderEntitlements(accountIdsToProcess, slaProcessId);
                //reEvaluateEntitlementProcess(accountIdsToProcess);
            }
        }
    } */
    
    //@future
    /*public static void updateAccountSupportLevel(set<Id> accountIdsToProcess) {
        List<Account> accList = new list<Account>();
        for(Id accId : accountIdsToProcess) {
            accList.add(new Account(Id=accId, Support_Level__c=ESP_Utility.ESPConstants.SLA_24X7SUPPORT));
        }
        system.debug('accList: '+ accList);
        if(!accList.isEmpty()) {
            //Account_tgr_cls.UPDATE_ALL_ENTITLEMENTS = TRUE;
            update accList;
			//Account_tgr_cls.UPDATE_ALL_ENTITLEMENTS = FALSE;
        }
    }*/
        /*
    @future
    @InvocableMethod
    public static void reEvaluateEntitlementProcess(List<Id> accIdsToUpdate) {
    	UPDATE_ENT_PROCESS = FALSE;
        //TriggerEntitlementHelper.DISABLE_TRIGGER = TRUE;
        //Query All the Entitlements to process
        map<Id, Entitlement> entitlementsToProcess 
             		= new map<Id, Entitlement>(
                        [SELECT Id, Name, AccountId, Hardware_Serial_Number__c, Account.Support_Level__c, SlaProcessId, Service_Product__r.Product_Line__c, Service_Product__r.Support_level__c, Service_Product__r.SLA_Scope__c  
                         FROM Entitlement 
                         WHERE AccountId IN :accIdsToUpdate
                         and Entitlement_Status__c != 'Expired' and Entitlement_Status__c != 'Inactive']
                    );
        
        if(entitlementsToProcess.isEmpty()) 
            return;
        
        SLA_Settings__mdt slaSetting = ESP_Utility.getSLASetting(ESP_Utility.ESPConstants.SLA_24X7SUPPORT);
        List<SlaProcess> EntProcessList;
        if(slaSetting != NULL)
            EntProcessList = [SELECT Id, Name FROM SlaProcess WHERE name =: slaSetting.Entitlement_Process_Name__c];
        
        Id slaProcessId = (EntProcessList.isEmpty()) ? NULL : EntProcessList[0].Id;
        
        //Create Dataset to Process
        set<String> SNSet 		= new set<String>();
        set<String> ProdLineSet = new set<String>();
        
        for(Entitlement ent: entitlementsToProcess.values()) {
            if(
                //ent.Account.Support_Level__c == ESP_Utility.ESPConstants.SLA_24X7SUPPORT && 
               Ent.Service_Product__r != NULL && 
               Ent.Service_Product__r.Support_level__c == ESP_Utility.ESPConstants.SLA_24X7SUPPORT && 
               Ent.Name != ESP_Utility.ESPConstants.ServiceCloudSettings.Placeholder_Entitlement_Name__c
              )
            {
                system.debug('Ent.Service_Product__r.SLA_Scope__c: '+ Ent.Service_Product__r.SLA_Scope__c);
                system.debug('ESP_Utility.ESPConstants.SLA_Settings.SLA_By_SN_Label__c: '+ ESP_Utility.ESPConstants.SLA_Settings.SLA_By_SN_Label__c);
                system.debug('ent.Service_Product__r.Product_Line__c: '+ ent.Service_Product__r.Product_Line__c);
                
                //Get SN List to Update
                if(Ent.Service_Product__r.SLA_Scope__c == ESP_Utility.ESPConstants.SLA_Settings.SLA_By_SN_Label__c 
                   	&& !string.isBlank(ent.Hardware_Serial_Number__c)
                  ) 
                    SNSet.add(ent.Hardware_Serial_Number__c);
                
                //Get Product Line list to update
                if(Ent.Service_Product__r.SLA_Scope__c == ESP_Utility.ESPConstants.SLA_Settings.SLA_By_Product_Line_Label__c 
                   	&& !string.isBlank(ent.Service_Product__r.Product_Line__c)
                  )
                    ProdLineSet.add(ent.Service_Product__r.Product_Line__c);
            }
        }
        
        system.debug('entitlementsToProcess: '+ entitlementsToProcess);
        system.debug('slaProcessId: '+ slaProcessId);
        system.debug('SNSet: '+ SNSet);
        system.debug('ProdLineSet: '+ ProdLineSet);
        map<Id, Entitlement> entMapToUpdate = new map<Id, Entitlement>();
        
        for(Entitlement ent: entitlementsToProcess.values()) {
            system.debug('SN: '+ ent.Hardware_Serial_Number__c);
            system.debug('Product Line: '+ ent.Service_Product__r.Product_Line__c);
            if(SNSet.contains(ent.Hardware_Serial_Number__c)) { //Update Entitlement based on Serial Number
                if(ent.SlaProcessId != slaProcessId) {
                    Ent.SlaProcessId = slaProcessId;
                    entMapToUpdate.put(ent.Id, ent);
                    system.debug('Match by SN');
                }
            } else if(ProdLineSet.contains(ent.Service_Product__r.Product_Line__c)) { //Update Entitlement based on Product Line
                if(ent.SlaProcessId != slaProcessId) {
                    Ent.SlaProcessId = slaProcessId;
                    entMapToUpdate.put(ent.Id, ent);
                    system.debug('Match by Product Line');
                }
            } else if(ent.SlaProcessId != NULL) {
                Ent.SlaProcessId = NULL;
                entMapToUpdate.put(ent.Id, ent);
                system.debug('No Match');
            }
        }
        
        system.debug('entMapToUpdate: '+ entMapToUpdate);
        if(!entMapToUpdate.isEmpty()){
            TriggerEntitlementHelper.UPDATE_ENT_PROCESS  = False;
            update entMapToUpdate.values();
            TriggerEntitlementHelper.UPDATE_ENT_PROCESS  = True;            
        }
	}
    */
    
    
    
    Public static void updateAssetId(){
        set<String> serialNumberSet = new set<String>();
        set<String> deliveryNumberSet = new set<String>();
        set<String> PAKIdNumberSet = new set<String>();
        for(Entitlement ent : newRecords){
            Entitlement oldEnt = (trigger.isUpdate) ? oldRecordsMap.get(ent.Id) : NULL;
            System.debug('Old Ent->'+oldEnt);
            if ( ( ent.Hardware_Serial_Number__c != null && ent.Hardware_Serial_Number__c != '')  
                    && (ent.Link_Asset__c == true || (oldEnt != NULL && oldEnt.Hardware_Serial_Number__c != ent.Hardware_Serial_Number__c) )
               ) {
                serialNumberSet.add(ent.Hardware_Serial_Number__c);
                //ent.AssetId = NULL;
            }else if((ent.SAP_Delivery_Number__c != null && ent.SAP_Delivery_Number__c != '' )
                    && (ent.Link_Asset__c == true || (oldEnt != NULL && oldEnt.SAP_Delivery_Number__c != ent.SAP_Delivery_Number__c) )
                    ){
                deliveryNumberSet.add(ent.SAP_Delivery_Number__c);
                //ent.AssetId = NULL;
            }/* Change: 25Oct2020: This code is commented due as we do not want to link based on PAK ID
              * else if((ent.PAK_ID__c != null && ent.PAK_ID__c != '') 
                     && (ent.Link_Asset__c == true || (oldEnt != NULL && oldEnt.PAK_ID__c != ent.PAK_ID__c) )
                    ){
                PAKIdNumberSet.add(ent.PAK_ID__c);
                //ent.AssetId = NULL;
            } */
            ent.Link_Asset__c = false;
        }
        System.debug('Assets Check point 1');
        if(serialNumberSet.isEmpty() && deliveryNumberSet.isEmpty()) // && PAKIdNumberSet.isEmpty() ) Change: 25Oct2020: This code is commented due as we do not want to link based on PAK ID
            return;
        System.debug('Assets Check point 2');
        // Change: 25Oct2020: This code is commented due as we do not want to link based on PAK ID
        List<Asset> AssetLst = [Select Id, Name, SerialNumber, SAP_Delivery_Number__c, PAKID__c from Asset where SerialNumber in: serialNumberSet OR SAP_Delivery_Number__c in: deliveryNumberSet];// OR PAKID__c in: PAKIdNumberSet]; 
        
        if(AssetLst.isEmpty())
            return;
        System.debug('Assets>>>'+AssetLst);
        Map <String, Asset> SNtoAssetMap = New Map<String, Asset>();
        for(Asset ast: AssetLst){
            if(ast.SerialNumber != null && ast.SerialNumber != ''){
                SNtoAssetMap.put(ast.SerialNumber, ast);
            }
            /* Change: 25Oct2020: This code is commented due as we do not want to link based on PAK ID
            if(ast.PAKID__c != null && ast.PAKID__c != ''){
                SNtoAssetMap.put(ast.PAKID__c, ast);
            } */
            if(ast.SAP_Delivery_Number__c != null && ast.SAP_Delivery_Number__c != ''){
                SNtoAssetMap.put(ast.SAP_Delivery_Number__c, ast);
            }
        }
        System.debug('SNtoAssetMap>>>'+SNtoAssetMap);
        for(Entitlement ent: newRecords) {
            if(SNtoAssetMap.containsKey(ent.Hardware_Serial_Number__c)){
                ent.AssetID = SNtoAssetMap.get(ent.Hardware_Serial_Number__c).id;
                System.debug('<<<AssetsId Update>>>');
            } /* Change: 25Oct2020: This code is commented due as we do not want to link based on PAK ID
            else if(SNtoAssetMap.containsKey(ent.PAK_ID__c)){
                ent.AssetID = SNtoAssetMap.get(ent.PAK_ID__c).id; 
                System.debug('<<<AssetsId Update>>>');
            } */ else if(SNtoAssetMap.containsKey(ent.SAP_Delivery_Number__c)){
                ent.AssetID = SNtoAssetMap.get(ent.SAP_Delivery_Number__c).id; 
                System.debug('<<<AssetsId Update>>>');
            }
        }
    }
    
    /* Update EntitlementName everytime either PAKID, Hardware Serial Number or Product Description changes.*/
    public static void UpdateName() {
        for(Entitlement ent : newRecords) {
            String description = string.IsBlank(ent.Product_Description__c) ? '' : '-' + ent.Product_Description__c;
            String entName = string.IsBlank(ent.Hardware_Serial_Number__c) ? ent.PAK_ID__c  +  description : ent.Hardware_Serial_Number__c + description;
            if(entName.left(80) != ent.Name)
                ent.Name = entName.left(80);
        }
    }
    
    /*
*   This method is invoked by the Entitlement Trigger
*   It is invoked/fired based on the After insert/update trigger event on the Entitlement
*   Following criteria is used to determine what entitlements will be processed for permission set removal
*   -   Only work on active record types of account NPN Account Registry or New Customer Account?
*   -   If an update, only apply product family changed and is the right status.
*   If any of the above is true, then we will look for associated announcements and construct 
*   CustomerAnnouncements based on them 
*/    
    public static void AddAnnouncement(Map<Id,Entitlement> triggerOldMap, List<Entitlement> triggerNewList){
        List<Entitlement> listToAdd = new List<Entitlement>();
        Id npnAccountRegistryRTId = null;
        Id newCustomerAccountRTId = null;
        // we only add to npn and new accounts
        Schema.RecordTypeInfo npnAccount = Schema.SObjectType.Account.RecordTypeInfosByName.get('NPN Account Registry');
        Schema.RecordTypeInfo newCustomer = Schema.SObjectType.Account.RecordTypeInfosByName.get('New Customer Account');
        
        if (npnAccount != null) {
            npnAccountRegistryRTId = npnAccount.RecordTypeId;
        }
        if (newCustomer != null) {
            newCustomerAccountRTId = newCustomer.RecordTypeId;
        }        
        //Changes Part of Version 1.1
        //Get Account Recordtype for related accounts in trigger.New
        List<Id> accountIdList = new List<Id>();
        for(Entitlement entitlelist:triggerNewList){
            accountIdList.add(entitlelist.AccountId);
        }
        
        //system.debug('123450 accountIdList: '+ accountIdList);
        Map<Id,Account> acctRecordIdMap = new Map<Id,Account>([Select Id,RecordTypeId From Account where Id IN :accountIdList]);
        
        for(Entitlement entList : triggerNewList){
            if(((acctRecordIdMap.get(entList.AccountId)).RecordTypeId == npnAccountRegistryRTId ||
                (acctRecordIdMap.get(entList.AccountId)).RecordTypeId == newCustomerAccountRTId) && 
               entList.Status == 'Active') {
                   //system.debug('123451 Inside for loop: ');
                   // for insert we want any active entitlements with the right account record types
                   if (trigger.isAfter && trigger.isInsert){
                       listToAdd.add(entList);
                       //system.debug('123452 Insert: ');
                   } else if(trigger.isAfter && trigger.isUpdate)
                   {
                       //system.debug('123452 Update: ');
                       
                       String oldStatus = triggerOldMap.get(entList.Id).Status;
                       String oldProduct = triggerOldMap.get(entList.Id).Product__c;
                       
                       // for update, we only want different product or status change to active
                       if ((!String.isBlank(oldProduct) && oldProduct != entList.Product__c) ||
                           (oldStatus == 'Removed' || oldStatus == 'Inactive' || oldStatus == 'Expired')) { 
                               //system.debug('123452 Update2: ');
                               listToAdd.add(entList);
                           }
                   }
               }
        }
        
        //system.debug('123453 Entitlements to process: '+ listToAdd);
        if(!listToAdd.isEmpty()){
            List<CustomerAnnouncement__c> toAdd = getAnnoucementsToAddByAccount(listToAdd);
            System.debug('Customer Announcements to create:');
            String debugBeforeInsert = '';
            for (CustomerAnnouncement__c ca : toAdd) debugBeforeInsert += '\n' + ca;
            System.debug(debugBeforeInsert);        
            insert toAdd;
        }
    }    
    
    /*
*   This method is invoked by the Entitlement Trigger via AddAnnouncement()
*   It takes in a list of entitlements and searches for the corresponding announcements to each
*   product on the entitlement.  It then constructs a customer announcement object based on the
*   account and announcement.  It returns a list of these customer announcements.
*/ 
    /**
* Changes on 29-June-2018
* Added logic to check for duplicate customer announcement creation
* */    
    public static List<CustomerAnnouncement__c> getAnnoucementsToAddByAccount(List<Entitlement> toCheck) {
        List<CustomerAnnouncement__c> toReturn = new List<CustomerAnnouncement__c>();
        Set<Id> accountIds = new Set<Id>();
        Set<Id> productIds = new Set<Id>();
        Set<String> productToAccount =new Set<String>();
        Map<Id,List<Id>> productToAnnouncementMap = new Map<Id,List<Id>>();
        Set<Id> CustAnnouncementSet = new Set<Id>();
        String accProdId;
        
        for(Entitlement enti : toCheck)
        {
            if(enti.Product__c != null && enti.AccountId != null){
                accountIds.add(enti.AccountId);
                productIds.add(enti.Product__c);
                accProdId=enti.Product__c+'-'+enti.AccountId;
                //Set of ProductId-AccountId; used to get announcement and create customer announcements 
                productToAccount.add(accProdId);
            }
        }
        //system.debug('123454 Product-Account KeyList: '+ accProdId);
        for(CustomerAnnouncement__c custAnnounce:[Select Id, Account__c,Announcement__c,Announcement__r.Product__c 
                                                  From CustomerAnnouncement__c Where Account__c IN :accountIds 
                                                  AND Announcement__r.Product__c IN:productIds])
        {
            // set of Existing Customer Announcement for that account
            // Used to check if there are any customer annoucements already created
            CustAnnouncementSet.add(custAnnounce.Announcement__c);
        }
        
        //system.debug('123455 Customer Announcements: '+ CustAnnouncementSet);
        for(Announcement__c listAnnouncement : [SELECT Id, Access_Level__c, Product__c 
                                                FROM Announcement__c WHERE Access_Level__c != 'Archived' 
                                                AND Product__c IN : productIds])
        {
            //Map of Product Id as key and List of Accountment id as value built based on annoucement for the list of products
            //and access level is not Archived
            //Used to get Accountment Id for that Product
            
            if(productToAnnouncementMap.containsKey(listAnnouncement.Product__c)) {
                List<Id> announceId = productToAnnouncementMap.get(listAnnouncement.Product__c);
                announceId.add(listAnnouncement.Id);
                productToAnnouncementMap.put(listAnnouncement.Product__c, announceId);
            } else {
                productToAnnouncementMap.put(listAnnouncement.Product__c, new List<Id> { listAnnouncement.Id });
            }
        }
        
        for(String prodToAcckey : productToAccount)
        {
            //system.debug('123457 product-Account key: '+ prodToAcckey);
            // validate if customer annoucement is already created
            if(!productToAnnouncementMap.isEmpty() && productToAnnouncementMap.containsKey((Id)prodToAcckey.substringBefore('-'))){
                //system.debug('123458 found key in map: ');
                For(Id announcementId:productToAnnouncementMap.get(prodToAcckey.substringBefore('-'))){
                    //system.debug('123459 announcementId: '+ announcementId);
                    if(!CustAnnouncementSet.contains(announcementId)){
                        //system.debug('1234510 : '+ announcementId);
                        CustomerAnnouncement__c toAdd = new CustomerAnnouncement__c();
                        toAdd.Account__c = prodToAcckey.substringAfter('-');
                        toAdd.Announcement__c = announcementId;
                        toReturn.add(toAdd);
                    }
                }
            }
        }
        return toReturn;
    }
    
@auraenabled
    public static string ESPContactNVIDIARenewalsButton(string strSubject, string strDescription){
        List<User> lstUser = [select name,Account.name,AccountId,ContactId,contact.name,email from User where id= :UserInfo.getUserId()];
        Messaging.SingleEmailMessage message = new Messaging.SingleEmailMessage();
        List<string> lstEmailIds = new List<string>();
        //lstEmailIds.add('gbrar@nvidia.com');
        lstEmailIds.add(label.Service_Cloud_ESP_Entitlement_Renewal_Team_email);
        message.setToAddresses(lstEmailIds);
        message.subject = '[' + lstUser.get(0).name + '] [Account- ' + lstUser.get(0).Account.name + '][' + strSubject + ']';
        message.plainTextBody = 'Account Name : ' + lstUser.get(0).Account.name +'\n' + 'Account Link : ' + URL.getSalesforceBaseUrl().toExternalForm() + '\\' + lstUser.get(0).AccountId + '\n Contact Name : ' + lstUser.get(0).contact.name + '\n Contact Link : ' + URL.getSalesforceBaseUrl().toExternalForm() +'\\'+ lstUser.get(0).ContactId + '\n Description : ' + strDescription;
        Messaging.SingleEmailMessage[] messages = 
        new List<Messaging.SingleEmailMessage> {message};
        Messaging.SendEmailResult[] results = Messaging.sendEmail(messages);
        if (results[0].success) {
            System.debug('The email was sent successfully.');
            return 'Success';
        } else {
            System.debug('The email failed to send: '
                  + results[0].errors[0].message);
            return 'Failed';      
        }
        
    } 
       
// SDS-2432 Added method
@InvocableMethod
    public static void checkSupportPortalRegistration(List<Entitlement> lstCurrentEntitlement){
        List<Contact> lstContact = [select id from Contact where Community_User_Type__c = 'ESP' and Community_User_Active__c=true and AccountId=:lstCurrentEntitlement.get(0).AccountId];
        if(lstContact.isEmpty()){
             List<Entitlement> lstEnt = [select Customer_Contact__c from Entitlement where AccountId = :lstCurrentEntitlement.get(0).accountId];
             if(!lstEnt.isEmpty()){
                 List<Id> lstContactIds = new List<Id>();
                EmailTemplate templateId = [Select DeveloperName,Id,subject from EmailTemplate where DeveloperName= 'Service_Cloud_Community_Registration_Reminder_to_Customer' limit 1];
                OrgWideEmailAddress owa = [select id, DisplayName, Address from OrgWideEmailAddress where Address='no_reply@nvidia.com' limit 1];
                List<Messaging.SingleEmailMessage> lstMessages= new List<Messaging.SingleEmailMessage>();
                Messaging.SingleEmailMessage mail ;
                List<string> lstToAddresses = new List<string>();
                for(Entitlement tmp : lstEnt){
                     if(tmp.Customer_Contact__c !=null){                         
                         mail = new Messaging.SingleEmailMessage();
                         mail.setOrgWideEmailAddressId(owa.id);
                         mail.setTemplateID(templateId.Id); 
                         mail.setTargetObjectId(tmp.Customer_Contact__c);
                         mail.setSaveAsActivity(false);
                         mail.setTreatTargetObjectAsRecipient(true);
                         mail.setWhatId(tmp.Id);
                        //mail.setSubject(templateId.subject);
                         lstMessages.add(mail); 
                     }                   
                 }
                if(!lstMessages.isEmpty()){          
                     Messaging.SendEmailResult[] results = Messaging.sendEmail(lstMessages,false);
                    if (results[0].success) {
                        System.debug('The email was sent successfully.');
                    } else {
                        System.debug('The email failed to send: '
                              + results[0].errors[0].message);
                    }                    
                }
             }
        }
    }    
}