force-app/main/default/objects/Account/fields/Support_Level__c.field-meta.xml
<CustomField>
    <fullName>Support_Level__c</fullName>
    <description>Picklist to show the type of Support a customer is entitled. Case will be routed Based on &quot;Support Level&quot;.</description>
    <label>Support Level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>24x7 Escalated Remote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Asset/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>Text(Product2.Product_Line__c)</formula>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Asset/fields/SBQQ__Subscription__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscribed Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Assets</relationshipLabel>
    <relationshipName>Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Entitlement_Status__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Status__c</fullName>
    <formula>IF ( Text(Order_Type__c) = &apos;ZMRS&apos;  || Text(Order_Type__c) = &apos;ZKB&apos; , &quot;MRS&quot;,
	IF ( ISBLANK(SAP_Order__c) &amp;&amp; ISBLANK(Subscription__c), &quot;Removed&quot;,
		IF ( TODAY() &gt;= StartDate &amp;&amp; TODAY() &lt;= EndDate, &quot;Active&quot;,
			IF(StartDate &gt; TODAY(), &quot;Inactive&quot;, 
						&quot;Expired&quot;
			)
		)
	)
)</formula>
    <label>Entitlement Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Hardware_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Hardware_Serial_Number__c</fullName>
    <label>Hardware Serial Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Product_Upgrade_Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Product_Upgrade_Entitlement__c</fullName>
    <formula>if( Service_Product__r.ProductCode  = &apos;718-A180I1&apos;, True, False)</formula>
    <label>Product Upgrade Entitlement?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Service_Product__c.field-meta.xml
<CustomField>
    <fullName>Service_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is created to store Product lookup copied from Subscription or manually entered for MRS Products.</description>
    <label>Service Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Entitlements (Service Product)</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Entitlements</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Support_Level__c.field-meta.xml
<CustomField>
    <fullName>Support_Level__c</fullName>
    <formula>Text(Service_Product__r.Support_level__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Support Level</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Type__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Automotive Datacenter</fullName>
            </value>
            <value>
                <fullName>CMP</fullName>
            </value>
            <value>
                <fullName>DC GPU</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
            <value>
                <fullName>Educational Services</fullName>
            </value>
            <value>
                <fullName>Fleet Command</fullName>
            </value>
            <value>
                <fullName>GeForce</fullName>
            </value>
            <value>
                <fullName>Grid</fullName>
            </value>
            <value>
                <fullName>Grid Hardware</fullName>
            </value>
            <value>
                <fullName>HPC SDK</fullName>
            </value>
            <value>
                <fullName>Jetson</fullName>
            </value>
            <value>
                <fullName>NGC-Ready Services</fullName>
            </value>
            <value>
                <fullName>Parabricks</fullName>
            </value>
            <value>
                <fullName>ProViz</fullName>
            </value>
            <value>
                <fullName>RTX</fullName>
            </value>
            <value>
                <fullName>RTX Blade Server</fullName>
            </value>
            <value>
                <fullName>Titan</fullName>
            </value>
            <value>
                <fullName>Value-Added Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/SLA_Scope__c.field-meta.xml
<CustomField>
    <fullName>SLA_Scope__c</fullName>
    <label>SLA Scope</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All with same Product Line</fullName>
            </value>
            <value>
                <fullName>All with same Serial Number</fullName>
            </value>
            <value>
                <fullName>Only self</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Support_level__c.field-meta.xml
<CustomField>
    <fullName>Support_level__c</fullName>
    <label>Support level</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>24x7 Escalated Remote</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Upgrade_Product__c.field-meta.xml
<CustomField>
    <fullName>Upgrade_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Upgrade Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Products (Upgrade Product)</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SLA_Settings__mdt/SLA_Settings__mdt.object-meta.xml
<CustomObject>
    <description>This metadata type will have information about SLA Process variables based on Support Level.</description>
    <label>SLA Settings</label>
    <pluralLabel>SLA Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/SLA_Settings__mdt/fields/Entitlement_Process_Name__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Process_Name__c</fullName>
    <label>Entitlement Process Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SLA_Settings__mdt/fields/SLA_By_Product_Line_Label__c.field-meta.xml
<CustomField>
    <fullName>SLA_By_Product_Line_Label__c</fullName>
    <defaultValue>&apos;All with same Product Line&apos;</defaultValue>
    <label>SLA By Product Line Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SLA_Settings__mdt/fields/SLA_By_SN_Label__c.field-meta.xml
<CustomField>
    <fullName>SLA_By_SN_Label__c</fullName>
    <defaultValue>&apos;All with same Serial Number&apos;</defaultValue>
    <label>SLA By SN Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ESP_EntitlementUtils.cls
/**
 * This is utility class for all reusable functions related to Entitlements.
 * Created: 02/10/2021 - Akhilesh Gupta 
 * 2021.10.02 - Akhilesh Gupta 	- Added reEvaluateEntitlementProcess to update Entitlement process on all the Entitlements associated with Account Ids provided.
 */

public class ESP_EntitlementUtils {
	
    public static void checkForProductUpgrade(list<Entitlement> entList) {
        map<String, Entitlement> EntMapBySN = new map<String, Entitlement>();
        for(Entitlement ent : entList) {
            system.debug('Upgrade Ent: '+ ent);
            if(ent.Product_Upgrade_Entitlement__c && ent.Hardware_Serial_Number__c != NULL && ent.Hardware_Serial_Number__c != '')
                EntMapBySN.put(ent.Hardware_Serial_Number__c, ent);
        }
        
        system.debug('EntMapBySN: '+ EntMapBySN);
        //Find All Entitlements matiching with SNs, AccountID, Active and Upgraded For equals ent.Service Prod
        list<Entitlement> entToProcess = [select Id, Name, AccountId, Subscription__c, Hardware_Serial_Number__c,
                                          	Service_Product__c, Service_Product__r.ProductCode, Service_Product__r.Upgrade_Product__c
                                         	, AssetId, Asset.SerialNumber, Asset.Product2.Upgrade_Product__c, Asset.Product2.Upgrade_Product__r.Description
                                          From Entitlement
                                         	Where Hardware_Serial_Number__c in: EntMapBySN.keySet() 
                                          		and EndDate >=: Date.today()
                                          		and Service_Product__r.Upgrade_Product__c != NULL
                                         ]; 
        
        system.debug('entToProcess: '+ entToProcess);
        
        if(entToProcess.isEmpty())
           return;
        
        list<Entitlement> EntitlementsToUpdate = new list<Entitlement>();
        list<Asset> AssetsToUpdate = new list<Asset>();
        list<SBQQ__Subscription__c> SubscriptionsToUpdate = new list<SBQQ__Subscription__c>();
        
        for(Entitlement oldEnt: entToProcess) {
            Entitlement upgradeEnt = EntMapBySN.get(oldEnt.Hardware_Serial_Number__c);
            system.debug('oldEnt: '+ oldEnt);
            if(oldEnt.AccountId == upgradeEnt.AccountId
              	//&& oldEnt.Service_Product__r.Upgrade_Product__c == upgradeEnt.Service_Product__c 
              ) {
        		oldEnt.Service_Product__c = oldEnt.Service_Product__r.Upgrade_Product__c;
                EntitlementsToUpdate.add(oldEnt);
                
                if(oldEnt.Subscription__c != null)
                    SubscriptionsToUpdate.add(new SBQQ__Subscription__c(Id=oldEnt.Subscription__c, 
                                                   SBQQ__Product__c=oldEnt.Service_Product__r.Upgrade_Product__c
                                                  ));
               	if(oldEnt.AssetId != Null && oldEnt.Asset.Product2 != NULL && oldEnt.Asset.Product2.Upgrade_Product__c != NULL) {
                	Asset ast = new Asset();
                    ast.Id = oldEnt.AssetId;
                    ast.Product2Id = oldEnt.Asset.Product2.Upgrade_Product__c;
                    ast.Name = oldEnt.Asset.SerialNumber + '-' + oldEnt.Asset.Product2.Upgrade_Product__r.Description;
                    AssetsToUpdate.add(ast);
                }
            }
        }
        
        system.debug('EntitlementsToUpdate: '+ EntitlementsToUpdate);
        system.debug('AssetsToUpdateldEnt: '+ AssetsToUpdate);
        system.debug('SubscriptionsToUpdate: '+ SubscriptionsToUpdate);
        
        if(!EntitlementsToUpdate.isEmpty()) 
            update EntitlementsToUpdate;
        if(!AssetsToUpdate.isEmpty()) {
            update AssetsToUpdate;
            //update AssetsToUpdate;
        }
        if(!SubscriptionsToUpdate.isEmpty()) 
            update SubscriptionsToUpdate;
    }
    
    public static void reEvaluateEntitlementProcess(set<Id> accIdsToUpdate) {
        //Query All the Entitlements to process
        map<Id, Entitlement> entitlementsToProcess 
             		= new map<Id, Entitlement>(
                        [SELECT Id, Name, AccountId, EndDate, Hardware_Serial_Number__c, Account.Support_Level__c, SlaProcessId, Entitlement_Status__c
                         	, Service_Product__r.Product_Line__c, Service_Product__r.Support_level__c, Service_Product__r.SLA_Scope__c  
                         FROM Entitlement 
                         WHERE AccountId IN :accIdsToUpdate 
                         and Name !=: ESP_Utility.ESPConstants.ServiceCloudSettings.Placeholder_Entitlement_Name__c
                         //and Entitlement_Status__c != 'Expired' and Entitlement_Status__c != 'Inactive'
                        ]
                    );
        
        if(entitlementsToProcess.isEmpty()) 
            return;
        
        SLA_Settings__mdt slaSetting = ESP_Utility.getSLASetting(ESP_Utility.ESPConstants.SLA_24X7SUPPORT);
        List<SlaProcess> EntProcessList;
        if(slaSetting != NULL)
            EntProcessList = [SELECT Id, Name FROM SlaProcess WHERE name =: slaSetting.Entitlement_Process_Name__c];
        
        Id slaProcessId = (EntProcessList.isEmpty()) ? NULL : EntProcessList[0].Id;
        
        //Create Dataset to Process
        set<String> SNSet 		= new set<String>();
        set<String> ProdLineSet = new set<String>();
        //map<Id, Integer> accTo24x7Count = map<Id, Integer>();
        
        for(Entitlement ent: entitlementsToProcess.values()) {
            if(
                //ent.Account.Support_Level__c == ESP_Utility.ESPConstants.SLA_24X7SUPPORT && 
               ent.Service_Product__r != NULL && 
               ent.Service_Product__r.Support_level__c == ESP_Utility.ESPConstants.SLA_24X7SUPPORT && 
               ent.Name != ESP_Utility.ESPConstants.ServiceCloudSettings.Placeholder_Entitlement_Name__c
               && ent.Entitlement_Status__c != 'Expired' && ent.Entitlement_Status__c != 'Inactive'
              )
            {
                system.debug('ent.Service_Product__r.SLA_Scope__c: '+ ent.Service_Product__r.SLA_Scope__c);
                system.debug('ESP_Utility.ESPConstants.SLA_Settings.SLA_By_SN_Label__c: '+ ESP_Utility.ESPConstants.SLA_Settings.SLA_By_SN_Label__c);
                system.debug('ent.Service_Product__r.Product_Line__c: '+ ent.Service_Product__r.Product_Line__c);
                
                //Get SN List to Update // and 
                if(ent.EndDate >= Date.today()) {
                    if(Ent.Service_Product__r.SLA_Scope__c == ESP_Utility.ESPConstants.SLA_Settings.SLA_By_SN_Label__c 
                        && !string.isBlank(ent.Hardware_Serial_Number__c)
                      ) 
                        SNSet.add(ent.Hardware_Serial_Number__c);
                    
                    //Get Product Line list to update
                    if(Ent.Service_Product__r.SLA_Scope__c == ESP_Utility.ESPConstants.SLA_Settings.SLA_By_Product_Line_Label__c 
                        && !string.isBlank(ent.Service_Product__r.Product_Line__c)
                      )
                        ProdLineSet.add(ent.Service_Product__r.Product_Line__c);
                }
            }
        }
        
        system.debug('entitlementsToProcess: '+ entitlementsToProcess);
        system.debug('slaProcessId: '+ slaProcessId);
        system.debug('SNSet: '+ SNSet);
        system.debug('ProdLineSet: '+ ProdLineSet);
        map<Id, Entitlement> entMapToUpdate = new map<Id, Entitlement>();
        
        for(Entitlement ent: entitlementsToProcess.values()) {
            system.debug('SN: '+ ent.Hardware_Serial_Number__c);
            system.debug('Product Line: '+ ent.Service_Product__r.Product_Line__c);
            if(ent.Name != ESP_Utility.ESPConstants.ServiceCloudSettings.Placeholder_Entitlement_Name__c) {
                if(Ent.EndDate < Date.today()) { //When an Entitlement is Exprired, remove SLA Process
                    if(ent.SlaProcessId != NULL) {
                        Ent.SlaProcessId = NULL;
                        entMapToUpdate.put(ent.Id, ent);
                    }
                    system.debug('Entitlement Expired');
                } else if(SNSet.contains(ent.Hardware_Serial_Number__c)) { //Update Entitlement based on Serial Number
                    if(ent.SlaProcessId != slaProcessId) { //Only update if Entitlement process not populated. Reduce number of records to be updated
                        Ent.SlaProcessId = slaProcessId;
                        entMapToUpdate.put(ent.Id, ent);
                        system.debug('Match by SN');
                    }
                } else if(ProdLineSet.contains(ent.Service_Product__r.Product_Line__c)) { //Update Entitlement based on Product Line
                    if(ent.SlaProcessId != slaProcessId) {//Only update if Entitlement process not populated. Reduce number of records to be updated
                        Ent.SlaProcessId = slaProcessId;
                        entMapToUpdate.put(ent.Id, ent);
                        system.debug('Match by Product Line');
                    }
                } else if(ent.SlaProcessId != NULL) { //Remove SLA Process when it is not fitting based on SLA Scope (SN/Product Line)
                    Ent.SlaProcessId = NULL;
                    entMapToUpdate.put(ent.Id, ent);
                    system.debug('No Match');
                }
            }
        }
        
        system.debug('entMapToUpdate: '+ entMapToUpdate);
        if(!entMapToUpdate.isEmpty()){
            TriggerEntitlementHelper.DISABLE_TRIGGER = TRUE;
            //TriggerEntitlementHelper.UPDATE_ENT_PROCESS  = False;
            update entMapToUpdate.values();
            updateAccountSupportLevel(accIdsToUpdate, slaProcessId);
            TriggerEntitlementHelper.DISABLE_TRIGGER = FALSE;
            //TriggerEntitlementHelper.UPDATE_ENT_PROCESS  = True;            
        }
	}
    
    public static void updateAccountSupportLevel(set<Id> accIdsToUpdate, Id slaProcessId) {
        list<Account> accountsToProcess = [select Id, Support_Level__c,
                                            (select Id, Name, SlaProcessId from Entitlements 
                                                where slaProcessId != NULL 
                                                  and Name !=: ESP_Utility.ESPConstants.ServiceCloudSettings.Placeholder_Entitlement_Name__c
                                            ) 
                                           from Account where Id IN :accIdsToUpdate];
        
        system.debug('accountsToProcess: '+ accountsToProcess);
        
        List<Account> accList = new list<Account>();
        for(Account acc : accountsToProcess) {
            system.debug('acc.Entitlements: '+ acc.Entitlements);
            system.debug('acc.Support_Level__c: '+ acc.Support_Level__c);
            if(acc.Entitlements != NULL && acc.entitlements.size() > 0) {
                if(acc.Support_Level__c != ESP_Utility.ESPConstants.SLA_24X7SUPPORT) 
                	accList.add(new Account(Id=acc.Id, Support_Level__c = ESP_Utility.ESPConstants.SLA_24X7SUPPORT));
            } else if(acc.Support_Level__c != '') {
                accList.add(new Account(Id=acc.Id, Support_Level__c=''));
            }
        }
        
        system.debug('accList: '+ accList);
        if(!accList.isEmpty()) {
            Account_tgr_cls.UPDATE_ALL_ENTITLEMENTS = TRUE;
            update accList;
			Account_tgr_cls.UPDATE_ALL_ENTITLEMENTS = FALSE;
        }
    }
}