force-app/main/default/objects/GRID_Portal_Profiles__c/GRID_Portal_Profiles__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community :</description>
    <label>Portal Profile</label>
    <nameField>
        <label>GRID_Portal_Profiles Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Profiles</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/GRID_Portal_Profiles__c/fields/Profile_Categories__c.field-meta.xml
<CustomField>
    <fullName>Profile_Categories__c</fullName>
    <label>Profile Categories</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales</fullName>
            </value>
            <value>
                <fullName>Marketing</fullName>
            </value>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Technical</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Portal Category(Generic)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GRID_VCA_Instant_Message__c/GRID_VCA_Instant_Message__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community :</description>
    <label>Portal Instant Message</label>
    <nameField>
        <label>Instant Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Instant Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GRID_VCA_Instant_Message__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GRID_VCA_Instant_Message__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>This is a url value for each instant message on portal.</description>
    <label>URL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Partner_Portal__c/Partner_Portal__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community :</description>
    <label>Partner Portal</label>
    <nameField>
        <label>GRID_Portals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Portal_Label__c/Partner_Portal_Label__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community :</description>
    <label>Partner Portal Box</label>
    <nameField>
        <label>Partner_Portal_Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal Box</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Portal_Label__c/fields/GRID_Portal_Profile__c.field-meta.xml
<CustomField>
    <fullName>GRID_Portal_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>GRID_Portal_Profile</label>
    <referenceTo>GRID_Portal_Profiles__c</referenceTo>
    <relationshipLabel>Partner_Portal_Labels</relationshipLabel>
    <relationshipName>Partner_Portal_Labels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Label__c/fields/Label_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Label_Serial_Number__c</fullName>
    <label>Label Serial Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Label__c/fields/Partner_Portal_Tab__c.field-meta.xml
<CustomField>
    <fullName>Partner_Portal_Tab__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner_Portal_Tab</label>
    <referenceTo>Partner_Portal_Tab__c</referenceTo>
    <relationshipLabel>Partner_Portal_Labels</relationshipLabel>
    <relationshipName>Partner_Portal_Labels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Links__c/Partner_Portal_Links__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community :</description>
    <label>Partner Portal Box Content</label>
    <nameField>
        <label>Partner_Portal_Links Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal Box Content</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Portal_Links__c/fields/Display_Bullet__c.field-meta.xml
<CustomField>
    <fullName>Display_Bullet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Display Bullet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Links__c/fields/Display_Page__c.field-meta.xml
<CustomField>
    <fullName>Display_Page__c</fullName>
    <label>Display Page</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Open in a New Tab</fullName>
            </value>
            <value>
                <fullName>Open in a New Window</fullName>
            </value>
            <value>
                <fullName>Open in existing page</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Portal_Links__c/fields/Link_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Link_Serial_Number__c</fullName>
    <label>Link Serial Number</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Links__c/fields/Partner_Portal_Label__c.field-meta.xml
<CustomField>
    <fullName>Partner_Portal_Label__c</fullName>
    <label>Partner_Portal_Label</label>
    <referenceTo>Partner_Portal_Label__c</referenceTo>
    <relationshipLabel>Partner_Portal_Links</relationshipLabel>
    <relationshipName>Partner_Portal_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Links__c/fields/Portal_Link_Name__c.field-meta.xml
<CustomField>
    <fullName>Portal_Link_Name__c</fullName>
    <label>Portal_Link Name</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Tab__c/Partner_Portal_Tab__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community :</description>
    <label>Partner Portal Tab</label>
    <nameField>
        <label>Partner Portal_Tab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal Tabs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Portal_Tab__c/fields/Partner_PortalName__c.field-meta.xml
<CustomField>
    <fullName>Partner_PortalName__c</fullName>
    <label>Partner_PortalName</label>
    <referenceTo>Partner_Portal__c</referenceTo>
    <relationshipLabel>Partner_Portal_Tabs</relationshipLabel>
    <relationshipName>Partner_Portal_Tabs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/portalSales1.cls
public class portalSales1 {   
    
    public string instanceMessage {get;set;}
    public List<wrapper> lstWrapper {get;set;}
    public List<CustomWrap> lst_CustomWrap{get;set;}
    public string tabName {get;set;}
    public boolean isLogATicket {get;set;}
    
    public portalSales1(){
        tabName = ApexPages.CurrentPage().getParameters().get('tab');
        lstWrapper = new List<wrapper>();
        lst_CustomWrap = new List<CustomWrap>();
        //if(!test.isRunningTest())
        init();
        showInstanceMessage();
                
        string profileName = [select  Id,Profile.Name from user where Id =:UserInfo.getUserId()].Profile.Name;  
        GRID_Portal_Profiles__c objGridPortalProfile = [select Profile_Categories__c from GRID_Portal_Profiles__c where Name=:profileName];
        
        if(objGridPortalProfile.Profile_Categories__c == 'Support'){
            isLogATicket = true;
        }else{
            isLogATicket = false;
        }
        
        
    }     
        public class wrapper{
        public integer serialNo {get;set;}
        public string label {get;set;}
        public boolean isBullet {get;set;}
        public List<wrapperData> lstwrapperData {get;set;}
        public wrapper(){
              lstwrapperData = new List<wrapperData>();
              serialNo = 0;          
        }
    }
    public class wrapperData{
        public string Value {get;set;}
        public string url {get;set;} 
        public string displayPageWindow {get;set;}
        public integer srno {get;set;}      
    }
    
    // Creating this map for each label and list of record with respect to that label.
    
   /* Map<string,List<GRID_Portal_Values__c>> mapLebelListOfRecord = new Map<string,List<GRID_Portal_Values__c>>();    */
    Map<string,List<Partner_Portal_Links__c>> mapLebelListOfRecordUpdated = new Map<string,List<Partner_Portal_Links__c>>();    
    public void init(){ 

        // Creating map from new Sobjects.
        Map<Id,Partner_Portal_Tab__c> mapIdandTabs = new Map<Id,Partner_Portal_Tab__c>([select Id,Name,Partner_PortalName__c from Partner_Portal_Tab__c where Name=:tabName AND Partner_PortalName__c =:[select Id from Partner_Portal__c where Name='GRID_VCA_Partner Portal' limit 1].Id]);
        Map<Id,Partner_Portal_Label__c> mapIdandLabels = new Map<Id,Partner_Portal_Label__c>([select Id,Name,Partner_Portal_Tab__c from Partner_Portal_Label__c where Partner_Portal_Tab__c In:mapIdandTabs.keyset()]);
        
        
        
        List<Partner_Portal_Links__c> lstPartner_Portal_Links = new List<Partner_Portal_Links__c>([select id,Name,Portal_Link_Name__c,Display_Page__c,Link_Serial_Number__c,Partner_Portal_Label__c,URL__c,
                                                                                                Partner_Portal_Label__r.Name,Partner_Portal_Label__r.Display_Bullet__c,Partner_Portal_Label__r.Label_Serial_Number__c from Partner_Portal_Links__c
                                                                                                where Partner_Portal_Label__c In:mapIdandLabels.keySet() AND 
                                                                                                (Partner_Portal_Label__r.GRID_Portal_Profile__r.Name=:[select Name from Profile where Id=:userinfo.getProfileId()].Name)]);        
          
             
        
        system.debug('check list size'+lstPartner_Portal_Links.size());
                system.debug('check list size'+lstPartner_Portal_Links);
        for(Partner_Portal_Links__c objGrid :lstPartner_Portal_Links){
                if(mapLebelListOfRecordUpdated.get(objGRID.Partner_Portal_Label__r.Name)==null){
                    mapLebelListOfRecordUpdated.put(objGRID.Partner_Portal_Label__r.Name,new List<Partner_Portal_Links__c>());            
                }mapLebelListOfRecordUpdated.get(objGRID.Partner_Portal_Label__r.Name).add(objGRID);        
        }
        
        
        // Using two object to maintain the dynamic box         
        /*
        List<GRID_Portal_Values__c> lstGRID_Portal_Values = new List<GRID_Portal_Values__c>([select Id,Name,GRID_Portal_Tabs__c,Display_Page__c,GRID_Portal_Tabs__r.GRID_Label_Name__c,GRID_Portal_Tabs__r.GRID_label_Serial_Number__c,GRID_Portal_Tabs__r.GRID_Portal_Profile__r.Name,GRID_Value_Serial_Number__c,Value_URL__c from GRID_Portal_Values__c where GRID_Portal_Tabs__r.Name=:tabName and GRID_Portal_Tabs__r.GRID_Portal_Profile__r.Name=:[select Name from Profile where Id=:userinfo.getProfileId()].Name]);        
        system.debug('Check values'+lstGRID_Portal_Values);               
        for(GRID_Portal_Values__c objGRID :lstGRID_Portal_Values){            
            if(mapLebelListOfRecord.get(objGRID.GRID_Portal_Tabs__r.GRID_Label_Name__c)==null){
                mapLebelListOfRecord.put(objGRID.GRID_Portal_Tabs__r.GRID_Label_Name__c,new List<GRID_Portal_Values__c>());            
            }mapLebelListOfRecord.get(objGRID.GRID_Portal_Tabs__r.GRID_Label_Name__c).add(objGRID);
        }
        */
        
               
        for(string label :mapLebelListOfRecordUpdated.keyset()){
            List<wrapperData> lstwrapperDataToSort = new List<wrapperData>();                   
            wrapper w = new wrapper();
            w.label = label.toUpperCase();                      
            List<Partner_Portal_Links__c> lstRecord = mapLebelListOfRecordUpdated.get(label);
            w.serialNo = integer.valueOf(lstRecord[0].Partner_Portal_Label__r.Label_Serial_Number__c);
            w.isBullet = lstRecord[0].Partner_Portal_Label__r.Display_Bullet__c;            
            for(Partner_Portal_Links__c gd :lstRecord){
               wrapperData wd = new wrapperData();
               wd.Value = gd.Portal_Link_Name__c;
               wd.displayPageWindow = gd.Display_Page__c;
               wd.url = gd.URL__c;
               wd.srno = integer.valueof(gd.Link_Serial_Number__c);
               lstwrapperDataToSort.add(wd);
               //w.lstwrapperData.add(wd); 
            }
            w.lstwrapperData =  sorting(lstwrapperDataToSort);                // Adding list of data which comes inside a box using sorting. 
            lstWrapper.add(w);            
        } 
        Integer num=0;
         
        
        // Return the list of wrapper class by sorting based on serialno.
        
        List<Wrapper> newSortedListWrapper = sorting(lstWrapper);        
        
        system.debug('newSortedListWrapper----------'+newSortedListWrapper);
        
        
        for(Integer idx=0; idx<newSortedListWrapper.size();idx++){
                                                                         
            List<Wrapper> lst_wrap = new List<Wrapper>();
            if(num!=idx){
                idx = num;
            }                                                                                  
            for(Integer j=0;j<3;j++){
               system.debug('Check index size'+idx+'check num'+num);                                                                         
               if(num<=idx && idx<newSortedListWrapper.size()){                                                            
                    lst_wrap.add(newSortedListWrapper[idx]);                        // Adding 3 record for each single row.                    
                    idx++;                    
                    num++;                                                     
                }                                               
            }            
            lst_CustomWrap.add(new CustomWrap(lst_wrap));
            system.debug('Check last index'+idx);
            if(newSortedListWrapper.size()-idx==1){
                idx--; 
            }                                     
        }
        
    }
    
    
   
    // Method to show instance messages.    
    public void showInstanceMessage(){
        instanceMessage = '';
        List<GRID_VCA_Instant_Message__c>  lstInstanceMessage =  [SELECT Expiration_Date__c,Message__c,Start_Date__c FROM GRID_VCA_Instant_Message__c where Expiration_Date__c>today Order by Expiration_Date__c ASC limit 2];
        for(GRID_VCA_Instant_Message__c grMsg :lstInstanceMessage){        
            instanceMessage = instanceMessage+grMsg.Message__c;
        }
        
    }
    
    // Wrapper class to pass all the data on visualforce page throught a list.  
    public class CustomWrap{
        public List<wrapper> lst_wrapper{get;set;}
        public CustomWrap(List<wrapper> lst_wrap){
            lst_wrapper = new List<wrapper>();
            lst_wrapper = lst_wrap;
        }
    }
    
    
    // Using this method to sort the wrapper class list based on the sequence number enter in records.    
     public list<Wrapper> sorting(list<Wrapper> currlist){
            integer j = 0;          
            Wrapper tmp = new Wrapper();  
            if(currlist.size()>1){           
                for(integer i=0;i<currlist.size();i++){
                    j = i;
                    system.debug('---currlist-----'+currlist[i]);
                    for(integer k = i;k<currlist.size();k++){               
                        if(currlist[j].serialNo  > currlist[k].serialNo){   
                            j = k;
                        }
                    }                    
                    tmp = currlist[i];
                    currlist[i] = currlist[j];
                    currlist[j] = tmp;
                }                
            }
            return currlist;  
    }
    
    // Using this method to sort the wrapperData class list based on the sequence number entered in records.    
     public list<WrapperData> sorting(list<WrapperData> currlist){
            integer j = 0;          
            WrapperData tmp = new WrapperData();  
            if(currlist.size()>1){           
                for(integer i=0;i<currlist.size();i++){
                    j = i;
                    system.debug('---currlist-----'+currlist[i]);
                    for(integer k = i;k<currlist.size();k++){               
                        if(currlist[j].srno  > currlist[k].srno){   
                            j = k;
                        }
                    }                    
                    tmp = currlist[i];
                    currlist[i] = currlist[j];
                    currlist[j] = tmp;
                }                
            }
            return currlist;
    }
    

}