force-app/main/default/objects/CRM_DoNotCallEmail_Settings__c/CRM_DoNotCallEmail_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains the messages for 
-No Sales Call/No Sales Email
-Pre-MQL Leads banner</description>
    <label>CRM : DoNotCallEmail, Pre-MQL : Settings</label>
</CustomObject>

force-app/main/default/objects/CRM_DoNotCallEmail_Settings__c/fields/ECL_SQL_Conversion_Alert__c.field-meta.xml
<CustomField>
    <fullName>ECL_SQL_Conversion_Alert__c</fullName>
    <description>ECL Alert: Lead status must be Sales Qualified to click ‘Convert’ and complete conversion process</description>
    <inlineHelpText>ECL Alert: Lead status must be Sales Qualified to click ‘Convert’ and complete conversion process</inlineHelpText>
    <label>ECL : SQL : Conversion Alert</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_DoNotCallEmail_Settings__c/fields/Lead_MSG__c.field-meta.xml
<CustomField>
    <fullName>Lead_MSG__c</fullName>
    <description>Message shown on the Lead detail page when one of the field No Sales Call or No Sales Email is checked</description>
    <label>Lead MSG</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CRM_DoNotCallEmail_Settings__c/fields/Pre_MQL_Lead_View_Msg__c.field-meta.xml
<CustomField>
    <fullName>Pre_MQL_Lead_View_Msg__c</fullName>
    <description>Message banner shown in Pre-MQL Lead detail pages</description>
    <inlineHelpText>Message banner shown in Pre-MQL Lead detail pages</inlineHelpText>
    <label>Pre-MQL Lead View Msg</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/No_Sales_Call__c.field-meta.xml
<CustomField>
    <fullName>No_Sales_Call__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Do Not Contact implementation</description>
    <inlineHelpText>&quot;Do Not Call&quot; indicates that the user does not wish to receive calls from NVIDIA Sales personnel.</inlineHelpText>
    <label>Do Not Call</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/No_Sales_Email__c.field-meta.xml
<CustomField>
    <fullName>No_Sales_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Do Not Contact implementation</description>
    <inlineHelpText>&quot;Do Not Email&quot; indicates that the user does not wish to receive emails from NVIDIA Sales personnel. If a user would like to unsubscribe from marketing emails, please refer them to: http://info.nvidianews.com/unsubscribepage.html</inlineHelpText>
    <label>Do Not Email</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CRM_Lead_DoNotCallEmail_Banner_cls.cls
/*
	2016.07.22 - pjena
	Controller class for CRM_Lead_DoNotCallEmail_Banner vf to show banner in the Lead record
	It pulls the No_Sales_Call__c, No_Sales_Email__c information of the Lead record and shows the message if any of them is checked
	
	2016.09.01 - PJENA - Combine DoNot Call/Email message with Pre-MQL Lead message
	
	2018.07.26 - PJENA - JIRA#SDS-550 - Add Alert on Enterprise Customer Lead Layout
						- Lead status must be Sales Qualified to click ‘Convert’ and complete conversion process.
*/
public class CRM_Lead_DoNotCallEmail_Banner_cls {
    public boolean showMessage{get;set;}
    public list<string> lstMsgs {get;set;}
    
    public CRM_Lead_DoNotCallEmail_Banner_cls(ApexPages.StandardController sc){
    	Id recordId = sc.getId();
    	lstMsgs = new list<string>();
    	if (recordId != null){
    		 
    		 list<Lead> lstLeads = [Select No_Sales_Call__c, No_Sales_Email__c, RecordType.Name 
    		 						From Lead 
    		 						Where Id = :recordId ];
    		 
    		 if (!lstLeads.isEmpty()){
    		 	if (lstLeads[0].RecordType.Name == COMM_Constants.LEAD_RT_PREMQL_LEAD){
    		 		showMessage = true;
    		 		lstMsgs.add(CRM_DoNotCallEmail_Settings__c.getOrgDefaults().Pre_MQL_Lead_View_Msg__c);
    		 	}
    		 	
    		 	if (lstLeads[0].No_Sales_Call__c == true || lstLeads[0].No_Sales_Email__c == true ){
    		 		showMessage = true;
    		 		lstMsgs.add(CRM_DoNotCallEmail_Settings__c.getOrgDefaults().Lead_MSG__c);
    		 	}
    		 	
    		 	//2018.07.26 - PJENA - JIRA#SDS-550 - Add Alert on Enterprise Customer Lead Layout
    		 	if (lstLeads[0].RecordType.Name == COMM_Constants.LEAD_RT_ENTERPRISE_CUSTOMER_LEAD){
    		 		showMessage = true;
    		 		lstMsgs.add(CRM_DoNotCallEmail_Settings__c.getOrgDefaults().ECL_SQL_Conversion_Alert__c);
    		 	}
    		 	
    		 }
    	}
    }
}