force-app/main/default/objects/Comments__c/Comments__c.object-meta.xml
<CustomObject>
    <description>CRM : Opportunity Comments made by internal team</description>
    <label>Comments</label>
    <nameField>
        <label>Comment Type</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Comments</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/QPB_Statement__c/QPB_Statement__c.object-meta.xml
<CustomObject>
    <description>NPN: Created for SDS-1406
Stores the QPB details for partners</description>
    <label>QPB Statement</label>
    <nameField>
        <displayFormat>QPBS-{000000}</displayFormat>
        <label>QPB Statement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QPB Statements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QPB_Statement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QPB Statements</relationshipLabel>
    <relationshipName>QPB_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Attachment_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attachment Uploaded?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Fiscal_Year__c.field-meta.xml
<CustomField>
    <fullName>Fiscal_Year__c</fullName>
    <label>Fiscal Year</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>FY20</fullName>
            </value>
            <value>
                <fullName>FY21</fullName>
            </value>
            <value>
                <fullName>FY22</fullName>
            </value>
            <value>
                <fullName>FY23</fullName>
            </value>
            <value>
                <fullName>FY24</fullName>
            </value>
            <value>
                <fullName>FY25</fullName>
            </value>
            <value>
                <fullName>FY26</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/FY_QTR__c.field-meta.xml
<CustomField>
    <fullName>FY_QTR__c</fullName>
    <formula>RIGHT(TEXT(Fiscal_Year__c), 2) + RIGHT(TEXT(Quarter__c), 1) + IF(ISPICKVAL(Type__c, &apos;Progress&apos;),&apos;1&apos;,&apos;2&apos;)</formula>
    <label>FY_QTR</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Notified__c.field-meta.xml
<CustomField>
    <fullName>Notified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Notified?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Quarter__c.field-meta.xml
<CustomField>
    <fullName>Quarter__c</fullName>
    <label>Quarter</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Q1</fullName>
            </value>
            <value>
                <fullName>Q2</fullName>
            </value>
            <value>
                <fullName>Q3</fullName>
            </value>
            <value>
                <fullName>Q4</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <formula>Account__r.Billing_Region_Text__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Region</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>Progress</fullName>
            </value>
            <value>
                <fullName>MOU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NPN_QPB_Stmt_Notification_Batch.cls
/**
 *  @name           : NPN_QPB_Stmt_Notification_Batch
 *  @author         : rkamble
 *  @description    : 
    2021.04.26  Created for SDS-2978. This is a schedular class for NPN_QPB_Stmt_Notification_Batch, which runs hourly to notify the partner about the new/ updated QPB Statements.
 *  CRON EXPRESSION : {0 0 * * * ?}

    //script
        NPN_QPB_Stmt_Notification_Batch sch = new NPN_QPB_Stmt_Notification_Batch();
        string cronexp='0 0 * * * ?';
        System.schedule('NPN_QPB_Stmt_Notification_Batch',cronexp,sch);
 */


global class NPN_QPB_Stmt_Notification_Batch implements Database.Batchable<sObject>, System.Schedulable {

    String queryString ='';
    String cronExpression='0 0 * * * ?';
    String batchName ='NPN_QPB_Stmt_Notification_Batch';
    Integer batchSize = 5;
    
    // Constructor
    public NPN_QPB_Stmt_Notification_Batch(){
        
        queryString = 'SELECT Id,Account_Name__c,Account__c,Attachment_Uploaded__c,Comments__c,Fiscal_Year__c,FY_QTR__c,LastModifiedDate,Name,Notified__c,Quarter__c,Region__c,Status__c,Type__c FROM QPB_Statement__c  WHERE Attachment_Uploaded__c = TRUE AND Notified__c = FALSE AND Status__c = \'Active\'';
    }

     global void execute(SchedulableContext sc) {

        NPN_QPB_Stmt_Notification_Batch batchName = new NPN_QPB_Stmt_Notification_Batch();
        Database.executeBatch(batchName,batchSize);
    }

    global Database.QueryLocator start(Database.BatchableContext bc){
        return Database.getQueryLocator(queryString);
    }

    global void execute(Database.BatchableContext bc, List<QPB_Statement__c> scope){
        
        Set<Id> qpbStmtIdSet = new Set<Id>();
        List<QPB_Statement__c> qpbStmtListForUpdate = new List<QPB_Statement__c>();
        
        for(QPB_Statement__c qpbObj : scope) {
            
            qpbStmtIdSet.add(qpbObj.Id);
            qpbObj.Notified__c = TRUE;
            qpbStmtListForUpdate.add(qpbObj);
        }
        
        if(!qpbStmtIdSet.isEmpty()){
            NPN_QPB_Statement_Util_cls.notifyPartnersForStmt(qpbStmtIdSet);
            
            update qpbStmtListForUpdate;
        }
    }
    
    global void finish(Database.BatchableContext bc){

        List<AsyncApexJob> existingJob = [SELECT Id,JobType,Status FROM AsyncApexJob WHERE ApexClass.Name ='NPN_QPB_Stmt_Notification_Batch' AND JobType ='ScheduledApex' AND Status ='Queued'];

        if(existingJob.isEmpty()) {
            NPN_QPB_Stmt_Notification_Batch sch = new NPN_QPB_Stmt_Notification_Batch();
            String cronexp = String.isNotBlank(cronExpression) ? cronExpression : '0 0 * * * ?';
            System.schedule('NPN_QPB_Stmt_Notification_Batch',cronexp,sch);
        }
    }
}