force-app/main/default/objects/Lead/fields/Account_Executive_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Executive_Name__c</fullName>
    <description>SDS-2142-EDU Lead Form Updates</description>
    <label>Account Executive Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DR_Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>DR_Deal_Type__c</fullName>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DGX</fullName>
            </value>
            <value>
                <fullName>vGPU</fullName>
            </value>
            <value>
                <fullName>Titan</fullName>
            </value>
            <value>
                <fullName>Jetson</fullName>
            </value>
            <value>
                <fullName>Server</fullName>
            </value>
            <value>
                <fullName>Workstation</fullName>
            </value>
            <value>
                <fullName>DLI</fullName>
            </value>
            <value>
                <fullName>Quadro</fullName>
            </value>
            <value>
                <fullName>Parabricks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/DR_Partner_Sales_Rep_Company__c.field-meta.xml
<CustomField>
    <fullName>DR_Partner_Sales_Rep_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Sales Rep Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Partner Sales Rep Company)</relationshipLabel>
    <relationshipName>DealRegPSRCLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DR_Product__c.field-meta.xml
<CustomField>
    <fullName>DR_Product__c</fullName>
    <label>Primary Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DR_Deal_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetName>Primary_Product</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/DR_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>DR_Program_Name__c</fullName>
    <description>Deal Registration</description>
    <label>Program Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DR_Secondary_Product__c.field-meta.xml
<CustomField>
    <fullName>DR_Secondary_Product__c</fullName>
    <description>Deal Registration</description>
    <label>Secondary Product</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>DR_Deal_Type__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DGX Station A100-40G</fullName>
            </value>
            <value>
                <fullName>DGX Station A100-80G</fullName>
            </value>
            <value>
                <fullName>DGX A100 40GB HW</fullName>
            </value>
            <value>
                <fullName>DGX A100 80G Full</fullName>
            </value>
            <value>
                <fullName>vGPU vApps Perp - GRID</fullName>
            </value>
            <value>
                <fullName>vGPU vApps Subs 1yr - GRID</fullName>
            </value>
            <value>
                <fullName>vGPU vApps Subs 3yr - GRID</fullName>
            </value>
            <value>
                <fullName>vGPU vApps Subs 4yr - GRID</fullName>
            </value>
            <value>
                <fullName>vGPU vApps Subs 5yr - GRID</fullName>
            </value>
            <value>
                <fullName>vGPU vPC Perpetual - GRID</fullName>
            </value>
            <value>
                <fullName>vGPU vPC Subs 1yr - GRID</fullName>
            </value>
            <value>
                <fullName>vGPU vPC Subs 3yr - GRID</fullName>
            </value>
            <value>
                <fullName>vGPU vPC Subs 4yr - GRID</fullName>
            </value>
            <value>
                <fullName>vGPU vPC Subs 5yr - GRID</fullName>
            </value>
            <value>
                <fullName>vGPU vWS Perp - GRID</fullName>
            </value>
            <value>
                <fullName>vGPU vWS Subs 1yr - GRID</fullName>
            </value>
            <value>
                <fullName>vGPU vWS Subs 3yr - GRID</fullName>
            </value>
            <value>
                <fullName>vGPU vWS Subs 4yr - GRID</fullName>
            </value>
            <value>
                <fullName>vGPU vWS Subs 5yr - GRID</fullName>
            </value>
            <value>
                <fullName>vGPU Virtual Compute Server Subs 1yr - GRID</fullName>
            </value>
            <value>
                <fullName>Tesla P4</fullName>
            </value>
            <value>
                <fullName>Tesla P40</fullName>
            </value>
            <value>
                <fullName>Tesla V100 PCIE-16GB</fullName>
            </value>
            <value>
                <fullName>Tesla P6</fullName>
            </value>
            <value>
                <fullName>Tesla M10</fullName>
            </value>
            <value>
                <fullName>Tesla M60</fullName>
            </value>
            <value>
                <fullName>Tesla P100 PCIE-16GB</fullName>
            </value>
            <value>
                <fullName>Tesla T4</fullName>
            </value>
            <value>
                <fullName>AI Starter Kit</fullName>
            </value>
            <value>
                <fullName>Quadro RTX5000</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/DR_Secondary_SKU_Quantity__c.field-meta.xml
<CustomField>
    <fullName>DR_Secondary_SKU_Quantity__c</fullName>
    <description>Deal Registration</description>
    <label>Secondary Product Quantity</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DR_SKU_Quantity__c.field-meta.xml
<CustomField>
    <fullName>DR_SKU_Quantity__c</fullName>
    <label>Primary Product Quantity</label>
    <precision>6</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DR_Submitted_Date__c.field-meta.xml
<CustomField>
    <fullName>DR_Submitted_Date__c</fullName>
    <label>Submitted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Lead_Number__c.field-meta.xml
<CustomField>
    <fullName>Lead_Number__c</fullName>
    <displayFormat>L-{000000}</displayFormat>
    <label>Lead Number</label>
    <type>AutoNumber</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Partner_Details__c.field-meta.xml
<CustomField>
    <fullName>Partner_Details__c</fullName>
    <description>SDS-2142-EDU Lead Form Updates</description>
    <inlineHelpText>Please include Partner Details (Partner Name, Account Manager Name, Account Manager Email Address, and Phone Number)</inlineHelpText>
    <label>Partner Details</label>
    <length>500</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/globalValueSets/Primary_Product.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>DGX Station A100-80G</fullName>
    </customValue>
    <customValue>
        <fullName>DGX Station A100-40G</fullName>
    </customValue>
    <customValue>
        <fullName>DGX A100 40GB HW</fullName>
    </customValue>
    <customValue>
        <fullName>DGX A100 80G Full</fullName>
    </customValue>
    <customValue>
        <fullName>vGPU vApps Perp - GRID</fullName>
    </customValue>
    <customValue>
        <fullName>vGPU vApps Subs 1yr - GRID</fullName>
    </customValue>
    <customValue>
        <fullName>vGPU vApps Subs 3yr - GRID</fullName>
    </customValue>
    <customValue>
        <fullName>vGPU vApps Subs 4yr - GRID</fullName>
    </customValue>
    <customValue>
        <fullName>vGPU vApps Subs 5yr - GRID</fullName>
    </customValue>
    <customValue>
        <fullName>vGPU vPC Perpetual - GRID</fullName>
    </customValue>
    <customValue>
        <fullName>vGPU vPC Subs 1yr - GRID</fullName>
    </customValue>
    <customValue>
        <fullName>vGPU vPC Subs 3yr - GRID</fullName>
    </customValue>
    <customValue>
        <fullName>vGPU vApps SUMS 4yr - GRID</fullName>
    </customValue>
    <customValue>
        <fullName>vGPU vApps SUMS 5yr - GRID</fullName>
    </customValue>
    <customValue>
        <fullName>vGPU vWS Perp - GRID</fullName>
    </customValue>
    <customValue>
        <fullName>vGPU vWS Subs 1yr - GRID</fullName>
    </customValue>
    <customValue>
        <fullName>vGPU vWS Subs 3yr - GRID</fullName>
    </customValue>
    <customValue>
        <fullName>vGPU vWS Subs 4yr - GRID</fullName>
    </customValue>
    <customValue>
        <fullName>vGPU vWS Subs 5yr - GRID</fullName>
    </customValue>
    <customValue>
        <fullName>vGPU Virtual Compute Server Subs 1yr - GRID</fullName>
    </customValue>
    <customValue>
        <fullName>Titan V</fullName>
    </customValue>
    <customValue>
        <fullName>Titan XP</fullName>
    </customValue>
    <customValue>
        <fullName>Titan RTX</fullName>
    </customValue>
    <customValue>
        <fullName>Jetson TX2 (module)</fullName>
    </customValue>
    <customValue>
        <fullName>Jetson AGX Xavier (module)</fullName>
    </customValue>
    <customValue>
        <fullName>Jetson AGX Xavier Devkit</fullName>
    </customValue>
    <customValue>
        <fullName>Jetson TX2 4GB (module)</fullName>
    </customValue>
    <customValue>
        <fullName>Jetson TX2i (module)</fullName>
    </customValue>
    <customValue>
        <fullName>Jetson Nano (Module)</fullName>
    </customValue>
    <customValue>
        <fullName>Jetson Xavier NX (module)</fullName>
    </customValue>
    <masterLabel>Primary Product</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/EDU_DR_Report_ctlr.cls
/*
    2020.12.14-PJENA-SDS-2748-EDU Lead Form Enhancements
        Show Pending, Approved, Rejected Edu Lead Registrations
*/
global without sharing class EDU_DR_Report_ctlr {
    private static list<lead> lstEduLeads{get;set;}
    private static Id accId {get; set;}
    private static Id contactId {get; set;}
    private static User partnerUser {get; set;}
    public static list<EDU_Lead_Wrapper> lstPendingEduLeads{get;set;}
    public static list<EDU_Lead_Wrapper> lstApprovedEduLeads{get;set;}
    public static list<EDU_Lead_Wrapper> lstRejectedEduLeads{get;set;}

    static {
        partnerUser = [Select ContactId, AccountId from User where id =: Userinfo.getUserid()];
        //contactId = partnerUser.ContactId;
        accId = partnerUser.AccountId;
        string eduLeadQuery = 'Select Lead_Number__c, Status, Company, DR_Program_Name__c, DR_Deal_Type__c, DR_Product__c, DR_SKU_Quantity__c, ' +
                                ' DR_Secondary_Product__c, DR_Secondary_SKU_Quantity__c, DR_Submitted_Date__c, Account_Executive_Name__c, DR_Partner_Sales_Rep_Company__c,  Partner_Details__c ' +
                                ' From Lead ' +
                                ' Where RecordType.developerName = \'EDU_Lead_Registration\'  And DR_Partner_Sales_Rep_Company__c = \'' + accId + '\' ' +
                                ' Order By CreatedDate' ;
        lstEduLeads = Database.query(eduLeadQuery);

        if (!lstEduLeads.isEmpty()){
            lstPendingEduLeads = new list<EDU_Lead_Wrapper>();
            lstApprovedEduLeads = new list<EDU_Lead_Wrapper>();
            lstRejectedEduLeads = new list<EDU_Lead_Wrapper>();
            EDU_Lead_Wrapper oEduLeadWraper;
            for (Lead oLead : lstEduLeads){
                oEduLeadWraper = new EDU_Lead_Wrapper();
                oEduLeadWraper.RequestId = oLead.Lead_Number__c;
                oEduLeadWraper.CustomerName = oLead.Company;
                oEduLeadWraper.ProgramName = oLead.DR_Program_Name__c;
                oEduLeadWraper.DealType = oLead.DR_Deal_Type__c;
                oEduLeadWraper.PrimaryProduct = oLead.DR_Product__c;
                oEduLeadWraper.PrimaryProductQuantity = oLead.DR_SKU_Quantity__c;
                oEduLeadWraper.SecondaryProduct = oLead.DR_Secondary_Product__c;
                oEduLeadWraper.SecondaryProductQuantity = oLead.DR_Secondary_SKU_Quantity__c;
                oEduLeadWraper.SubmittedDate = oLead.DR_Submitted_Date__c;
                oEduLeadWraper.AccountExecutiveName = oLead.Account_Executive_Name__c;
                oEduLeadWraper.PartnerDetails = oLead.Partner_Details__c;

                if (oLead.Status == 'In Review'){
                    lstPendingEduLeads.add(oEduLeadWraper);
                }else if (oLead.Status == 'Approved'){
                    lstApprovedEduLeads.add(oEduLeadWraper);
                }else if (oLead.Status == 'Rejected'){
                    lstRejectedEduLeads.add(oEduLeadWraper);
                }
            }
        }
    }

    @RemoteAction
    global static list<EDU_Lead_Wrapper> loadPendingEduLeads() {
        return lstPendingEduLeads;
    }

    @RemoteAction
    global static list<EDU_Lead_Wrapper> loadApprovedEduLeads() {
        return lstApprovedEduLeads;
    }

    @RemoteAction
    global static list<EDU_Lead_Wrapper> loadRejectedEduLeads() {
        return lstRejectedEduLeads;
    }
    

    global class EDU_Lead_Wrapper{
        public string RequestId{get;set;} //Lead_Number__c
        public string CustomerName {get;set;} //Company
        public string ProgramName {get;set;} //DR_Program_Name__c
        public string DealType{get;set;} //DR_Deal_Type__c
        public string PrimaryProduct {get;set;} // DR_Product__c
        public decimal PrimaryProductQuantity {get;set;} //DR_SKU_Quantity__c
        public string SecondaryProduct {get;set;} // DR_Secondary_Product__c
        public decimal SecondaryProductQuantity {get;set;} //DR_Secondary_SKU_Quantity__c
        public datetime SubmittedDate {get;set;} //DR_Submitted_Date__c
        public string AccountExecutiveName {get;set;} //Account_Executive_Name__c
        public string PartnerDetails {get;set;} //PartnerDetails__c
        public string Status {get;set;} //LeadStatus
    }
}