force-app/main/default/objects/Lead/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Id</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Account Id)</relationshipLabel>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DR_Deal_Type__c.field-meta.xml
<CustomField>
    <fullName>DR_Deal_Type__c</fullName>
    <label>Deal Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DGX</fullName>
            </value>
            <value>
                <fullName>vGPU</fullName>
            </value>
            <value>
                <fullName>Titan</fullName>
            </value>
            <value>
                <fullName>Jetson</fullName>
            </value>
            <value>
                <fullName>Server</fullName>
            </value>
            <value>
                <fullName>Workstation</fullName>
            </value>
            <value>
                <fullName>DLI</fullName>
            </value>
            <value>
                <fullName>Quadro</fullName>
            </value>
            <value>
                <fullName>Parabricks</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/DR_Partner_Sales_Rep_Company__c.field-meta.xml
<CustomField>
    <fullName>DR_Partner_Sales_Rep_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Sales Rep Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Partner Sales Rep Company)</relationshipLabel>
    <relationshipName>DealRegPSRCLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/Partner_Attribute__c.object-meta.xml
<CustomObject>
    <description>NPN : Additional attributes to an account - program type, competency, level etc.</description>
    <label>Partner Attribute</label>
    <nameField>
        <displayFormat>PA-{0000}</displayFormat>
        <label>Attribute ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Attribute__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <inlineHelpText>Select account</inlineHelpText>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Account_Attributes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Date_Competency_Signed__c.field-meta.xml
<CustomField>
    <fullName>Date_Competency_Signed__c</fullName>
    <label>Date Competency Signed</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Date_Competency_Terminated__c.field-meta.xml
<CustomField>
    <fullName>Date_Competency_Terminated__c</fullName>
    <label>Date Competency Terminated</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Competency__c.field-meta.xml
<CustomField>
    <fullName>Partner_Competency__c</fullName>
    <label>Partner Competency</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Partner_Program_Name__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Compute</fullName>
            </value>
            <value>
                <fullName>Compute DGX</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
            <value>
                <fullName>Embedded Edge</fullName>
            </value>
            <value>
                <fullName>Healthcare</fullName>
            </value>
            <value>
                <fullName>Virtualization</fullName>
            </value>
            <value>
                <fullName>Visualization</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Program_Name__c</fullName>
    <label>Partner Program Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Solution Provider</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>Tegra Embedded</fullName>
            </value>
            <value>
                <fullName>Services Subcontractor</fullName>
            </value>
            <value>
                <fullName>Cloud Service Provider</fullName>
            </value>
            <value>
                <fullName>Service Delivery Partner</fullName>
            </value>
            <value>
                <fullName>Solution Advisor</fullName>
            </value>
            <value>
                <fullName>Solutions Integration Partner</fullName>
            </value>
            <value>
                <fullName>Industry Focus</fullName>
            </value>
            <value>
                <fullName>Federal Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Global Systems Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Attribute__c/fields/Partner_Sub_Program__c.field-meta.xml
<CustomField>
    <fullName>Partner_Sub_Program__c</fullName>
    <label>Partner Sub Program</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Partner_Program_Name__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Data Center Provider</fullName>
            </value>
            <value>
                <fullName>EDU Services</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Support Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SuRF_DGX_HOT_Compliance__c/SuRF_DGX_HOT_Compliance__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF_DGX_HOT_Compliance</label>
    <nameField>
        <label>SuRF_DGX_HOT_Compliance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SuRF_DGX_HOT_Compliance</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_DGX_HOT_Compliance__c/fields/Account_Id__c.field-meta.xml
<CustomField>
    <fullName>Account_Id__c</fullName>
    <label>Account_Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SuRF_DGX_HOT_Compliance__c/fields/Partner_Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Partner_Program_Name__c</fullName>
    <label>Partner_Program_Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SuRF_Partner_Program</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SuRF_DGX_HOT_Compliance__c/fields/Partner_Sub_Program__c.field-meta.xml
<CustomField>
    <fullName>Partner_Sub_Program__c</fullName>
    <label>Partner_Sub_Program</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SuRF_DGX_HOT_Compliance_Trans__c/SuRF_DGX_HOT_Compliance_Trans__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF_DGX_HOT_Compliance_Trans</label>
    <nameField>
        <label>SuRF_DGX_HOT_Compliance_Trans Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SuRF_DGX_HOT_Compliance_Trans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_DGX_HOT_Compliance_Trans__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <label>Account_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SuRF_DGX_HOT_Compliance_Trans__c/fields/Billing_Sub_Region__c.field-meta.xml
<CustomField>
    <fullName>Billing_Sub_Region__c</fullName>
    <label>Billing_Sub_Region</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SuRF_DGX_HOT_Compliance_Trans__c/fields/Competency__c.field-meta.xml
<CustomField>
    <fullName>Competency__c</fullName>
    <label>Competency</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Surf_Competency</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SuRF_Partner_Performance_Scorecard__c/SuRF_Partner_Performance_Scorecard__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF-Partner Performance Scorecard</label>
    <nameField>
        <displayFormat>SuRF-PPS-{00000}</displayFormat>
        <label>SuRF-Partner Performance Scorecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuRF-Partner Performance Scorecards</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_Partner_Performance_Scorecard__c/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <label>Flag</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/SuRF_Partner_Performance_Scorecard_Trans__c/SuRF_Partner_Performance_Scorecard_Trans__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : NPN Compliance :</description>
    <label>SuRF-Partner Performance Scorecard Trans</label>
    <nameField>
        <displayFormat>SuRF-PPS-{00000}</displayFormat>
        <label>SuRF-Partner Performance Scorecard Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>SuRF-Partner Performance Scorecard Trans</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SuRF_Partner_Performance_Scorecard_Trans__c/fields/Partner_Program__c.field-meta.xml
<CustomField>
    <fullName>Partner_Program__c</fullName>
    <label>Partner Program</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>SuRF_Partner_Program</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/SuRF_Transit__c/SuRF_Transit__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>SuRF Transit</label>
</CustomObject>

force-app/main/default/objects/SuRF_Transit__c/fields/isTransit__c.field-meta.xml
<CustomField>
    <fullName>isTransit__c</fullName>
    <defaultValue>false</defaultValue>
    <label>isTransit</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Surf_Competency.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Compute DGX</fullName>
    </customValue>
    <customValue>
        <fullName>Virtualization</fullName>
    </customValue>
    <customValue>
        <fullName>Compute</fullName>
    </customValue>
    <customValue>
        <fullName>Visualization</fullName>
    </customValue>
    <customValue>
        <fullName>Embedded Edge</fullName>
    </customValue>
    <customValue>
        <fullName>DGX</fullName>
    </customValue>
    <masterLabel>Surf Competency</masterLabel>
</GlobalValueSet>

force-app/main/default/globalValueSets/SuRF_Partner_Program.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Solution Provider</fullName>
    </customValue>
    <customValue>
        <fullName>OEM</fullName>
    </customValue>
    <customValue>
        <fullName>Distributor</fullName>
    </customValue>
    <customValue>
        <fullName>Cloud Service Provider</fullName>
    </customValue>
    <customValue>
        <fullName>Solution Advisor</fullName>
    </customValue>
    <customValue>
        <fullName>Inception Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Tegra Embedded</fullName>
    </customValue>
    <customValue>
        <fullName>Services Subcontractor</fullName>
    </customValue>
    <customValue>
        <fullName>Service Delivery Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Solutions Integration Partner</fullName>
    </customValue>
    <customValue>
        <fullName>Federal Systems Integrator</fullName>
    </customValue>
    <customValue>
        <fullName>Global Systems Integrator</fullName>
    </customValue>
    <masterLabel>SuRF Partner Program</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/NV_PartnerTrainingPOSComplianceCtrl.cls
public without sharing class NV_PartnerTrainingPOSComplianceCtrl {
    
    private static Boolean isTransit = SuRF_Transit__c.getOrgDefaults().isTransit__c;
    public Decimal dTrainingCmpl{get;set;}
    public Decimal dPOSCmpl{get;set;}
    public Decimal dDGXHOTCmpl{get;set;}    // Added for SDS-3054
    public Decimal dRegComplStatus{get;set;}    // Added for SDS-3181
    public String strCompetency{get;set;}
    public static final string LEAD_PRODUCT_TYPE_PARABRICKS = 'Parabricks';
    public static final string LEAD_PRODUCT_TYPE_DLI = 'DLI';
    private lead objLead;
    list<Surf_Partner_Performance_Scorecard__c> lstPPS = new list<Surf_Partner_Performance_Scorecard__c>();
    list<Surf_Partner_Performance_Scorecard_Trans__c> lstPPST = new list<Surf_Partner_Performance_Scorecard_Trans__c>();
    List<SuRF_DGX_HOT_Compliance__c> lstSDHT = new List<SuRF_DGX_HOT_Compliance__c>();  // Added for SDS-3054
    List<SuRF_DGX_HOT_Compliance_Trans__c> lstSDHTT = new List<SuRF_DGX_HOT_Compliance_Trans__c>();  // Added for SDS-3054
    Set<String> signedCompetencySet = new Set<String>();

    public NV_PartnerTrainingPOSComplianceCtrl(ApexPages.StandardController controller) {
        objLead = [SELECT id,DR_Deal_Type__c,DR_Partner_Sales_Rep_Company__c FROM Lead where id =:controller.getId()];
        
        if(!isTransit) {
            if(objLead.DR_Deal_Type__c == COMM_CONSTANTS.LEAD_PRODUCT_TYPE_DGX || objLead.DR_Deal_Type__c == LEAD_PRODUCT_TYPE_PARABRICKS || objLead.DR_Deal_Type__c == LEAD_PRODUCT_TYPE_DLI) {
                strCompetency = COMM_CONSTANTS.TEST_PORTAL_COMPETENCY_DL;
                lstPPS = [SELECT id, Category__c, flag__c FROM Surf_Partner_Performance_Scorecard__c where Account_Id__c =:objLead.DR_Partner_Sales_Rep_Company__c and Partner_Program__c =:COMM_CONSTANTS.PA_PROGRAM_SP  and (competency__c =:COMM_CONSTANTS.TEST_PORTAL_COMPETENCY_DL or competency__c =:COMM_CONSTANTS.LEAD_PRODUCT_TYPE_DGX) and (Category__c = 'Training Compliance' or Category__c = 'POS Revenue') ];

                /* Changes for SDS-3054 START */
                lstSDHT = [SELECT Account_Id__c, Account_Name__c,BillingCountry__c,Billing_Sub_Region__c,Category__c,Competency__c,Flag__c,Id,Name,Order__c,Partner_Program_Name__c, Partner_Sub_Program__c FROM SuRF_DGX_HOT_Compliance__c WHERE Account_Id__c =:objLead.DR_Partner_Sales_Rep_Company__c AND Partner_Program_Name__c =:COMM_CONSTANTS.PA_PROGRAM_SP AND (Competency__c =:COMM_CONSTANTS.TEST_PORTAL_COMPETENCY_DL OR Competency__c =:COMM_CONSTANTS.LEAD_PRODUCT_TYPE_DGX) AND Category__c = 'Training Compliance'];
                /* Changes for SDS-3054 END */
            } else if(objLead.DR_Deal_Type__c == COMM_CONSTANTS.LEAD_PRODUCT_TYPE_GRID ) {
                strCompetency = COMM_CONSTANTS.TEST_PORTAL_COMPETENCY_GV ;
                lstPPS = [SELECT id, Category__c, flag__c FROM Surf_Partner_Performance_Scorecard__c where Account_Id__c =:objLead.DR_Partner_Sales_Rep_Company__c  and Partner_Program__c =:COMM_CONSTANTS.PA_PROGRAM_SP and competency__c = :COMM_CONSTANTS.TEST_PORTAL_COMPETENCY_GV and (Category__c = 'Training Compliance' or Category__c = 'POS Revenue') ];
            }
            if(lstPPS.size() > 0) {
                for(Surf_Partner_Performance_Scorecard__c objPPS : lstPPS) {
                    if(objPPS.Category__c == 'Training Compliance') {
                        dTrainingCmpl = objPPS.flag__c;
                    } else if (objPPS.Category__c == 'POS Revenue') {
                        dPOSCmpl = objPPS.flag__c;
                    }                
                }
            } else {
                dTrainingCmpl = -1;
                dPOSCmpl = -1;
            }
            // The value 9 indicates that DGX HOT Compliance Section is hidden if the lead is not SP Compute DGX/ DGX.
            dDGXHOTCmpl = !lstSDHT.isEmpty() ? lstSDHT[0].Flag__c : 9;  // Added for SDS-3054   
        } else {
            if(objLead.DR_Deal_Type__c == COMM_CONSTANTS.LEAD_PRODUCT_TYPE_DGX || objLead.DR_Deal_Type__c == LEAD_PRODUCT_TYPE_PARABRICKS || objLead.DR_Deal_Type__c == LEAD_PRODUCT_TYPE_DLI) {
                strCompetency = COMM_CONSTANTS.TEST_PORTAL_COMPETENCY_DL;
                lstPPST = [SELECT id, Category__c, flag__c FROM Surf_Partner_Performance_Scorecard_Trans__c where Account_Id__c =:objLead.DR_Partner_Sales_Rep_Company__c and Partner_Program__c =:COMM_CONSTANTS.PA_PROGRAM_SP  and (competency__c =:COMM_CONSTANTS.TEST_PORTAL_COMPETENCY_DL or competency__c =:COMM_CONSTANTS.LEAD_PRODUCT_TYPE_DGX) and (Category__c = 'Training Compliance' or Category__c = 'POS Revenue') ];
                
                /* Changes for SDS-3054 START */
                lstSDHTT = [SELECT Account_Id__c, Account_Name__c,BillingCountry__c,Billing_Sub_Region__c,Category__c,Competency__c,Flag__c,Id,Name,Order__c,Partner_Program_Name__c, Partner_Sub_Program__c FROM SuRF_DGX_HOT_Compliance_Trans__c WHERE Account_Id__c =:objLead.DR_Partner_Sales_Rep_Company__c AND Partner_Program_Name__c =:COMM_CONSTANTS.PA_PROGRAM_SP AND (Competency__c =:COMM_CONSTANTS.TEST_PORTAL_COMPETENCY_DL OR Competency__c =:COMM_CONSTANTS.LEAD_PRODUCT_TYPE_DGX)];
                /* Changes for SDS-3054 END */
            } else if(objLead.DR_Deal_Type__c == COMM_CONSTANTS.LEAD_PRODUCT_TYPE_GRID ) {
                strCompetency = COMM_CONSTANTS.TEST_PORTAL_COMPETENCY_GV ;
                lstPPST = [SELECT id, Category__c, flag__c FROM Surf_Partner_Performance_Scorecard_Trans__c where Account_Id__c =:objLead.DR_Partner_Sales_Rep_Company__c  and Partner_Program__c =:COMM_CONSTANTS.PA_PROGRAM_SP and competency__c = :COMM_CONSTANTS.TEST_PORTAL_COMPETENCY_GV and (Category__c = 'Training Compliance' or Category__c = 'POS Revenue') ];
            }
            if(lstPPST.size() > 0) {
                for(Surf_Partner_Performance_Scorecard_Trans__c objPPST : lstPPST) {
                    if(objPPST.Category__c == 'Training Compliance') {
                        dTrainingCmpl = objPPST.flag__c;
                    } else if (objPPST.Category__c == 'POS Revenue') {
                        dPOSCmpl = objPPST.flag__c;
                    }                
                }
            } else {
                dTrainingCmpl = -1;
                dPOSCmpl = -1;
            }
            // The value 9 indicates that DGX HOT Compliance Section is hidden if the lead is not SP Compute DGX/ DGX.    
            dDGXHOTCmpl = !lstSDHT.isEmpty() ? lstSDHT[0].Flag__c : -9;  // Added for SDS-3054          
        }
        /* Changes for SDS-3181 START */
        dRegComplStatus = -1;
        if(String.isNotBlank(objLead.DR_Partner_Sales_Rep_Company__c)){            
            for(Partner_Attribute__c paObj : [SELECT Account_Name__c,Partner_Competency__c FROM Partner_Attribute__c WHERE Date_Competency_Signed__c != null AND Date_Competency_Terminated__c = null AND Account_Name__c = :objLead.DR_Partner_Sales_Rep_Company__c AND (Partner_Competency__c = :strCompetency OR Partner_Competency__c = 'DGX')]){
                signedCompetencySet.add(paObj.Partner_Competency__c);
            }
        }
        if(!signedCompetencySet.isEmpty()){
            if(signedCompetencySet.contains(strCompetency) || signedCompetencySet.contains('DGX')){
                dRegComplStatus = 1;
            }
        }
        /* Changes for SDS-3181 END */
    }
}