force-app/main/default/objects/Lead/fields/Approved_Competencies__c.field-meta.xml
<CustomField>
    <fullName>Approved_Competencies__c</fullName>
    <label>Approved Competencies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Compute</fullName>
            </value>
            <value>
                <fullName>Virtualization</fullName>
            </value>
            <value>
                <fullName>Visualization</fullName>
            </value>
            <value>
                <fullName>Compute DGX</fullName>
            </value>
            <value>
                <fullName>Embedded Edge</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Approved_Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Approved_Program_Type__c</fullName>
    <label>Approved Program Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Solution Provider</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Solution Advisor</fullName>
            </value>
            <value>
                <fullName>Cloud Service Provider</fullName>
            </value>
            <value>
                <fullName>Service Delivery Partner</fullName>
            </value>
            <value>
                <fullName>Solutions Integration Partner</fullName>
            </value>
            <value>
                <fullName>Federal Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Global Systems Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Job_Role__c.field-meta.xml
<CustomField>
    <fullName>Job_Role__c</fullName>
    <label>Job Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Channel/Partners</fullName>
            </value>
            <value>
                <fullName>Chief Executive Officer (CEO)</fullName>
            </value>
            <value>
                <fullName>Chief Information Officer (CIO)</fullName>
            </value>
            <value>
                <fullName>Chief Technology Officer (CTO)</fullName>
            </value>
            <value>
                <fullName>Consultant</fullName>
            </value>
            <value>
                <fullName>Data Scientist</fullName>
                <label>Data scientist</label>
            </value>
            <value>
                <fullName>Developer/Programmer</fullName>
            </value>
            <value>
                <fullName>Director</fullName>
            </value>
            <value>
                <fullName>Engineer</fullName>
            </value>
            <value>
                <fullName>Executive/Management</fullName>
            </value>
            <value>
                <fullName>Film/Video Editor</fullName>
            </value>
            <value>
                <fullName>Graphic Designer/Animator</fullName>
            </value>
            <value>
                <fullName>Industrial Designer/Product Designer</fullName>
            </value>
            <value>
                <fullName>IT Administrator/Systems Administrator</fullName>
            </value>
            <value>
                <fullName>IT Manager/Director of IT/VP of IT</fullName>
            </value>
            <value>
                <fullName>Marketing/Communications</fullName>
            </value>
            <value>
                <fullName>Marketing Manager</fullName>
            </value>
            <value>
                <fullName>Product Design/Engineering</fullName>
            </value>
            <value>
                <fullName>Product Management/Technical Marketing</fullName>
            </value>
            <value>
                <fullName>Professor/Department Advisor</fullName>
            </value>
            <value>
                <fullName>Purchasing Manager</fullName>
            </value>
            <value>
                <fullName>Research Scientist</fullName>
            </value>
            <value>
                <fullName>Sales/Business Development</fullName>
            </value>
            <value>
                <fullName>Sales Engineer</fullName>
            </value>
            <value>
                <fullName>Sales Rep/Sales Manager</fullName>
            </value>
            <value>
                <fullName>Senior Vice President (SVP)</fullName>
            </value>
            <value>
                <fullName>Student/Post Grad</fullName>
            </value>
            <value>
                <fullName>Support/Services</fullName>
            </value>
            <value>
                <fullName>Vice President (VP)</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Program_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Level__c</fullName>
    <label>Approved Program Level</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Preferred</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Registered</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NPN_Competency_Permissions_Group_Map__c/NPN_Competency_Permissions_Group_Map__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>NPN Competency Permissions and Group Map</label>
</CustomObject>

force-app/main/default/objects/NPN_Competency_Permissions_Group_Map__c/fields/Permissions_and_Group__c.field-meta.xml
<CustomField>
    <fullName>Permissions_and_Group__c</fullName>
    <label>Permissions and Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Competency_Permissions_Group_Map__c/fields/Program_Level__c.field-meta.xml
<CustomField>
    <fullName>Program_Level__c</fullName>
    <label>Program Level</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Docusign_Comptency__c/NPN_Docusign_Comptency__c.object-meta.xml
<CustomObject>
    <description>NPN : Automate Onboarding DocuSign: NPN DocuSign Competency Data for Onboarding Process</description>
    <label>NPN_Docusign_Comptency</label>
    <nameField>
        <label>NPN_Docusign_Comptency Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPN_Docusign_Comptencys</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NPN_DocuSign_Id__c/NPN_DocuSign_Id__c.object-meta.xml
<CustomObject>
    <description>NPN : Automate Onboarding DocuSign: This Object is used for getting the templates Ids from DocuSign in NPN On-boarding process</description>
    <label>NPN_DocuSign_Id</label>
    <nameField>
        <label>NPN_DocuSign_Id Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPN_DocuSign_Ids</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NPN_DocuSign_Id__c/fields/Contracts_Packet__c.field-meta.xml
<CustomField>
    <fullName>Contracts_Packet__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Contracts Packet</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NPN_DocuSign_Id__c/fields/Docusign_Template_ID__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Template_ID__c</fullName>
    <label>Docusign Template ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_DocuSign_Id__c/fields/NPN_Docusign_Comptency__c.field-meta.xml
<CustomField>
    <fullName>NPN_Docusign_Comptency__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NPN_Docusign_Comptency</label>
    <referenceTo>NPN_Docusign_Comptency__c</referenceTo>
    <relationshipLabel>NPN_DocuSign_Ids</relationshipLabel>
    <relationshipName>NPN_DocuSign_Ids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPN_DocuSign_Id__c/fields/NPN_Docusign_Region__c.field-meta.xml
<CustomField>
    <fullName>NPN_Docusign_Region__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NPN_Docusign_Region</label>
    <referenceTo>NPN_Docusign_Region__c</referenceTo>
    <relationshipLabel>NPN_DocuSign_Ids</relationshipLabel>
    <relationshipName>NPN_DocuSign_Ids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPN_DocuSign_Id__c/fields/NPN_DocusiNPN_Docusign_Progn_ProgramType__c.field-meta.xml
<CustomField>
    <fullName>NPN_DocusiNPN_Docusign_Progn_ProgramType__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>NPN_Docusign_ProgramType</label>
    <referenceTo>NPN_Docusign_ProgramType__c</referenceTo>
    <relationshipLabel>NPN_DocuSign_Ids</relationshipLabel>
    <relationshipName>NPN_DocuSign_Ids</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPN_Docusign_ProgramType__c/NPN_Docusign_ProgramType__c.object-meta.xml
<CustomObject>
    <description>NPN : Automate Onboarding DocuSign: NPN DocuSign Program Type for Onboarding Process</description>
    <label>NPN_Docusign_ProgramType</label>
    <nameField>
        <label>NPN_Docusign_ProgramType Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPN_Docusign_ProgramTypes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NPN_Docusign_Region__c/NPN_Docusign_Region__c.object-meta.xml
<CustomObject>
    <description>NPN : Automate Onboarding DocuSign: NPN DocuSign Region master Data for Onboarding Process</description>
    <label>NPN_Docusign_Region</label>
    <nameField>
        <label>NPN_Docusign_Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPN_Docusign_Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NPN_Key_Contact__c/NPN_Key_Contact__c.object-meta.xml
<CustomObject>
    <description>NPN : DocuSign : Automated onboarding - Key Contacts form</description>
    <label>NPN Key Contact</label>
    <nameField>
        <label>NPN Key Contact Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NPN Key Contacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NPN_Key_Contact__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>NPN Key Contacts</relationshipLabel>
    <relationshipName>NPN_Key_Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NPN_Key_Contact__c/fields/Sales_Training__c.field-meta.xml
<CustomField>
    <fullName>Sales_Training__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Sales Training</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NPN_Key_Contact__c/fields/Technical_Training__c.field-meta.xml
<CustomField>
    <fullName>Technical_Training__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Technical Training</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_Automation_2__c/NPN_Onboarding_Automation_2__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>NPN Onboarding Automation 2</label>
</CustomObject>

force-app/main/default/objects/NPN_Onboarding_Automation_2__c/fields/Cover_Letter__c.field-meta.xml
<CustomField>
    <fullName>Cover_Letter__c</fullName>
    <label>Cover Letter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_Automation_2__c/fields/NPN_Distribution_Form__c.field-meta.xml
<CustomField>
    <fullName>NPN_Distribution_Form__c</fullName>
    <label>NPN Distribution Form</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_Automation_2__c/fields/NPN_Key_Contacts_Form__c.field-meta.xml
<CustomField>
    <fullName>NPN_Key_Contacts_Form__c</fullName>
    <label>NPN_Key_Contacts_Form</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_Automation_2__c/fields/NPN_SP_ProgramGuide__c.field-meta.xml
<CustomField>
    <fullName>NPN_SP_ProgramGuide__c</fullName>
    <label>NPN_SP_ProgramGuide</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_Competency_Level_Mapping__c/NPN_Onboarding_Competency_Level_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>NPN Onboarding Competency Level Mapping</label>
</CustomObject>

force-app/main/default/objects/NPN_Onboarding_Competency_Level_Mapping__c/fields/Competency__c.field-meta.xml
<CustomField>
    <fullName>Competency__c</fullName>
    <label>Competency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_Competency_Level_Mapping__c/fields/CSP_sell_to_other_CSPs__c.field-meta.xml
<CustomField>
    <fullName>CSP_sell_to_other_CSPs__c</fullName>
    <label>CSP sell to other CSPs</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_Competency_Level_Mapping__c/fields/Docusign_Program_Guide_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Program_Guide_Template_Id__c</fullName>
    <label>Docusign_Program_Guide_Template_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_GPU_Genius_Map__c/NPN_Onboarding_GPU_Genius_Map__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>NPN Onboarding Competency GPU Genius Map</label>
</CustomObject>

force-app/main/default/objects/NPN_Onboarding_GPU_Genius_Map__c/fields/GPU_Genius_Group__c.field-meta.xml
<CustomField>
    <fullName>GPU_Genius_Group__c</fullName>
    <label>GPU Genius Group</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_GPU_Genius_Map__c/fields/Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Program_Type__c</fullName>
    <label>Program Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NV_Test_LeadExtension.cls
@isTest
private class NV_Test_LeadExtension {
    
    static Id leadId;
    static Lead objLead;
    static void createData() {
    
        RecordType leadRec = [select id from RecordType where sobjectType='Lead' and developerName='NPN_Web_Onboard_Form'];
        objLead = new Lead();
        objLead.Approved_Competencies__c = 'High Performance Computing; GPU Virtualization';
        objLead.Approved_Program_Type__c = 'OEM';
        objLead.Program_Level__c = 'Elite';
        objLead.lastname = 'Varun Test';
        objLead.email = 'varun@test.com';
        objLead.Company = 'NVD';
        objLead.Country = 'India';
        objLead.recordTypeId = leadRec.id;
        insert objLead;
        leadId = objLead.id;
        NPN_Docusign_Region__c objRg = new NPN_Docusign_Region__c(name='India');
        insert objRg;
        NPN_Docusign_Comptency__c objCptcy = new NPN_Docusign_Comptency__c(name='High Performance Computing');
        insert objCptcy;
        NPN_Docusign_ProgramType__c objPT = new NPN_Docusign_ProgramType__c(name='OEM');
        insert objPT;
        NPN_DocuSign_Id__c objDcsgId = new NPN_DocuSign_Id__c();
        objDcsgId.NPN_Docusign_Region__c = objRg.id;
        objDcsgId.NPN_DocusiNPN_Docusign_Progn_ProgramType__c = objPT.id;
        objDcsgId.NPN_Docusign_Comptency__c = objCptcy.id;
        objDcsgId.Contracts_Packet__c = True;
        objDcsgId.Docusign_Template_ID__c = 'abcdef';
        insert objDcsgId;
        Attachment att = new Attachment(parentId = objLead.id, name='test Att', body = Blob.valueOf('Str'));
        insert att;
        NPN_Key_Contact__c objNPN = new NPN_Key_Contact__c(lead__c = objLead.id, email__c = 'varun@test.com', Job_Role__c = 'Sales', sales_training__c = true, technical_Training__c = true);
        insert objNPN;
        NPN_Onboarding_GPU_Genius_Map__c objNPNGPU = new NPN_Onboarding_GPU_Genius_Map__c(Name = 'abcd', Competency__c = 'High Performance Computing', Role__c = 'Sales', GPU_Genius_Group__c = 'abcd');
        insert objNPNGPU;
        NPN_Onboarding_Competency_Level_Mapping__c objNPNLVLMAP = new NPN_Onboarding_Competency_Level_Mapping__c(Name = 'abcd', Competency__c = 'High Performance Computing', Program_Type__c = 'OEM', Docusign_Template_Id__c = 'Cover_Letter__c', Docusign_Program_Guide_Template_Id__c='NPN_SP_ProgramGuide__c', CSP_sell_to_other_CSPs__c='No');
        insert objNPNLVLMAP;
        NPN_Competency_Permissions_Group_Map__c objNPNPGMAP = new NPN_Competency_Permissions_Group_Map__c(Name = 'abcd', Competency__c = 'High Performance Computing', Program_Type__c = 'OEM', Program_Level__C = 'Elite', Permissions_and_Group__c = 'abcd');
        insert objNPNPGMAP;
        NPN_Onboarding_Automation_2__c objNPNOnb = new NPN_Onboarding_Automation_2__c(Name='India', NPN_Key_Contacts_Form__c='Test' , NPN_SP_ProgramGuide__c='test',NPN_Distribution_Form__c='TEst');
        insert objNPNOnb;
    }
    
    static testmethod void convertLeadTest() {
        createData();
        Test.startTest();
            PageReference pageRef = Page.NV_Lead_Docusign;
            pageRef.getParameters().put('id', String.valueOf(leadId));
            Test.setCurrentPage(pageRef);
            ApexPages.StandardController sc = new ApexPages.StandardController(objLead);
            NV_LeadExtension objNVLeadExtn = new NV_LeadExtension(sc); 
            NV_DocuSign_LeadExtension objDLE = new NV_DocuSign_LeadExtension(sc);
        Test.stopTest();
    }
    
}