force-app/main/default/objects/Lead/fields/Approved_Competencies__c.field-meta.xml
<CustomField>
    <fullName>Approved_Competencies__c</fullName>
    <label>Approved Competencies</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Compute</fullName>
            </value>
            <value>
                <fullName>Virtualization</fullName>
            </value>
            <value>
                <fullName>Visualization</fullName>
            </value>
            <value>
                <fullName>Compute DGX</fullName>
            </value>
            <value>
                <fullName>Embedded Edge</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Approved_Program_Type__c.field-meta.xml
<CustomField>
    <fullName>Approved_Program_Type__c</fullName>
    <label>Approved Program Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Solution Provider</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Solution Advisor</fullName>
            </value>
            <value>
                <fullName>Cloud Service Provider</fullName>
            </value>
            <value>
                <fullName>Service Delivery Partner</fullName>
            </value>
            <value>
                <fullName>Solutions Integration Partner</fullName>
            </value>
            <value>
                <fullName>Federal Systems Integrator</fullName>
            </value>
            <value>
                <fullName>Global Systems Integrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Competencies_Interested_In__c.field-meta.xml
<CustomField>
    <fullName>Competencies_Interested_In__c</fullName>
    <label>Competencies Interested In</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Compute</fullName>
            </value>
            <value>
                <fullName>Virtualization</fullName>
            </value>
            <value>
                <fullName>Gaming</fullName>
            </value>
            <value>
                <fullName>Visualization</fullName>
            </value>
            <value>
                <fullName>Compute DGX</fullName>
            </value>
            <value>
                <fullName>Embedded Edge</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Organization_Type_select_one__c.field-meta.xml
<CustomField>
    <fullName>Organization_Type_select_one__c</fullName>
    <label>Organization Partner Type</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Academia</fullName>
            </value>
            <value>
                <fullName>Authorized Board Partner</fullName>
            </value>
            <value>
                <fullName>Cloud Service Provider</fullName>
            </value>
            <value>
                <fullName>Commercial</fullName>
            </value>
            <value>
                <fullName>Consultant/System Integrator</fullName>
            </value>
            <value>
                <fullName>Corp Reseller/Direct Market Reseller</fullName>
            </value>
            <value>
                <fullName>Distributor</fullName>
            </value>
            <value>
                <fullName>End User</fullName>
            </value>
            <value>
                <fullName>Etailer</fullName>
            </value>
            <value>
                <fullName>Government</fullName>
            </value>
            <value>
                <fullName>iCafe</fullName>
            </value>
            <value>
                <fullName>Inception Partner (Startup)</fullName>
            </value>
            <value>
                <fullName>ISV</fullName>
            </value>
            <value>
                <fullName>IT-Manager</fullName>
            </value>
            <value>
                <fullName>ODM</fullName>
            </value>
            <value>
                <fullName>OEM</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Partner</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>Retailer</fullName>
            </value>
            <value>
                <fullName>Solution Advisor</fullName>
            </value>
            <value>
                <fullName>Solution Provider (VAR)</fullName>
            </value>
            <value>
                <fullName>Solutions Integration Partner</fullName>
            </value>
            <value>
                <fullName>Support &amp; Services Delivery Partner</fullName>
            </value>
            <value>
                <fullName>System Builder</fullName>
            </value>
            <value>
                <fullName>Training Center</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Lead/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>NALA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NPN_Contract_Packet_Config__c/NPN_Contract_Packet_Config__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>NPN Contracts Packet Config</label>
</CustomObject>

force-app/main/default/objects/NPN_Contract_Packet_Config__c/fields/VP_Email__c.field-meta.xml
<CustomField>
    <fullName>VP_Email__c</fullName>
    <label>VP Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/NPN_Contract_Packet_Config__c/fields/VP_First_Name__c.field-meta.xml
<CustomField>
    <fullName>VP_First_Name__c</fullName>
    <label>VP First Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Contract_Packet_Config__c/fields/VP_Last_Name__c.field-meta.xml
<CustomField>
    <fullName>VP_Last_Name__c</fullName>
    <label>VP Last Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Docusign_Program_Type_KeyContact__c/NPN_Docusign_Program_Type_KeyContact__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>NPN_Docusign_Program_Type_KeyContact</label>
</CustomObject>

force-app/main/default/objects/NPN_Onboarding_Automation_2__c/NPN_Onboarding_Automation_2__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>NPN Onboarding Automation 2</label>
</CustomObject>

force-app/main/default/objects/NPN_Onboarding_Automation_2__c/fields/Cover_Letter__c.field-meta.xml
<CustomField>
    <fullName>Cover_Letter__c</fullName>
    <label>Cover Letter</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_Automation_2__c/fields/Master_Agreement__c.field-meta.xml
<CustomField>
    <fullName>Master_Agreement__c</fullName>
    <label>Master Agreement</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_Automation_2__c/fields/NEW_MDF_REBATE_VENDOR_SETUP_FORM__c.field-meta.xml
<CustomField>
    <fullName>NEW_MDF_REBATE_VENDOR_SETUP_FORM__c</fullName>
    <label>NEW MDF REBATE VENDOR SETUP FORM</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_Automation_2__c/fields/NPN_Distribution_Form__c.field-meta.xml
<CustomField>
    <fullName>NPN_Distribution_Form__c</fullName>
    <label>NPN Distribution Form</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_Automation_2__c/fields/NPN_Key_Contacts_Form__c.field-meta.xml
<CustomField>
    <fullName>NPN_Key_Contacts_Form__c</fullName>
    <label>NPN_Key_Contacts_Form</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_Automation_2__c/fields/NPN_OEM_CompetencyExhibit_AC__c.field-meta.xml
<CustomField>
    <fullName>NPN_OEM_CompetencyExhibit_AC__c</fullName>
    <label>NPN_OEM_CompetencyExhibit_AC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_Automation_2__c/fields/NPN_OEM_CompetencyExhibit_PV__c.field-meta.xml
<CustomField>
    <fullName>NPN_OEM_CompetencyExhibit_PV__c</fullName>
    <label>NPN_OEM_CompetencyExhibit_PV</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_Automation_2__c/fields/NPN_SP_CompetencyExhibit_AC__c.field-meta.xml
<CustomField>
    <fullName>NPN_SP_CompetencyExhibit_AC__c</fullName>
    <label>NPN_SP_CompetencyExhibit_AC</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_Automation_2__c/fields/NPN_SP_CompetencyExhibit_CV__c.field-meta.xml
<CustomField>
    <fullName>NPN_SP_CompetencyExhibit_CV__c</fullName>
    <label>NPN_SP_CompetencyExhibit_CV</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_Automation_2__c/fields/NPN_SP_CompetencyExhibit_PV__c.field-meta.xml
<CustomField>
    <fullName>NPN_SP_CompetencyExhibit_PV__c</fullName>
    <label>NPN_SP_CompetencyExhibit_PV</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_Competency_Level_Mapping__c/NPN_Onboarding_Competency_Level_Mapping__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <label>NPN Onboarding Competency Level Mapping</label>
</CustomObject>

force-app/main/default/objects/NPN_Onboarding_Competency_Level_Mapping__c/fields/Competency__c.field-meta.xml
<CustomField>
    <fullName>Competency__c</fullName>
    <label>Competency</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NPN_Onboarding_Competency_Level_Mapping__c/fields/Docusign_Program_Guide_Template_Id__c.field-meta.xml
<CustomField>
    <fullName>Docusign_Program_Guide_Template_Id__c</fullName>
    <label>Docusign_Program_Guide_Template_Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NV_LeadExtension.cls
public class NV_LeadExtension {
    private final Lead objLead;
    public List<NPN_Onboarding_Automation_2__c> lstNPNCustomSetting {get;set;}
    public String strDocumentIds {get;set;}
    public String strVPFirstName {get;set;}
    public String strVPLastName {get;set;}
    public String strVPEmail {get;set;}
    public String strEmailSubject {get;set;}
    public String strEmailBody {get;set;}
    public set<String> setProgramTypes;
    
    public NV_LeadExtension(ApexPages.StandardController stdController) {
        setProgramTypes = new set<String>();
        this.objLead = [select id, Approved_Program_Type__c , Approved_Competencies__c , Region__c, country, Organization_Type_select_one__c, Competencies_Interested_In__c from Lead where id = :ApexPages.CurrentPage().getParameters().get('Id')];        
        NPN_Onboarding_Automation_2__c objNPNCustomSetting = NPN_Onboarding_Automation_2__c.getInstance(objLead.country);
        NPN_Contract_Packet_Config__c objNPNContractsPacketConfig = NPN_Contract_Packet_Config__c.getInstance();
        map<String, NPN_Onboarding_Competency_Level_Mapping__c> mapNPNCompetencyProgramTypeMapping = NPN_Onboarding_Competency_Level_Mapping__c.getAll();
        map<String, NPN_Docusign_Program_Type_KeyContact__c> mapNPNDocusignPrgmTypeKeyContact = NPN_Docusign_Program_Type_KeyContact__c.getAll();
        strVPFirstName = objNPNContractsPacketConfig.VP_First_Name__c;
        strVPLastName = objNPNContractsPacketConfig.VP_Last_Name__c;
        strVPEmail = objNPNContractsPacketConfig.VP_Email__c;  
        strEmailSubject = objNPNContractsPacketConfig.Email_Subject__c;
        strEmailBody = objNPNContractsPacketConfig.Email_Body__c;
        if(objNPNCustomSetting == null) {
            if(objLead.Region__c == null) {
                objNPNCustomSetting = NPN_Onboarding_Automation_2__c.getInstance('');
            } else {
                objNPNCustomSetting = NPN_Onboarding_Automation_2__c.getInstance(objLead.region__c);
            }
        }
        if(objNPNCustomSetting != null) {
            strDocumentIds = objNPNCustomSetting.Cover_Letter__c + ','
                            + objNPNCustomSetting.Master_Agreement__c + ',';                                
            /*if(objLead.Approved_Program_Type__c!= null && objLead.Approved_Program_Type__c.contains(COMM_Constants.PA_PROGRAM_SP)) {                
                bSolutionProvider = true;
                if(objLead.Approved_Competencies__c!= null && objLead.Approved_Competencies__c.contains(COMM_Constants.TEST_PORTAL_COMPETENCY_AC)) {
                    strDocumentIds += objNPNCustomSetting.NPN_SP_CompetencyExhibit_AC__c + ',';
                } 
                if(objLead.Approved_Competencies__c!= null && objLead.Approved_Competencies__c.contains(COMM_Constants.TEST_PORTAL_COMPETENCY_CV_SPC)) {
                    strDocumentIds += objNPNCustomSetting.NPN_SP_CompetencyExhibit_CV__c + ',';
                } 
                if(objLead.Approved_Competencies__c!= null && objLead.Approved_Competencies__c.contains(COMM_Constants.TEST_PORTAL_COMPETENCY_PV)) {
                    strDocumentIds += objNPNCustomSetting.NPN_SP_CompetencyExhibit_PV__c + ',';
                } 
            } if(objLead.Approved_Program_Type__c!= null && objLead.Approved_Program_Type__c.contains(COMM_Constants.PA_PROGRAM_OEM)) {                
                bOEM = true;
                if(objLead.Approved_Competencies__c!= null && objLead.Approved_Competencies__c.contains(COMM_Constants.TEST_PORTAL_COMPETENCY_AC)) {
                    strDocumentIds += objNPNCustomSetting.NPN_OEM_CompetencyExhibit_AC__c + ',';
                }
                if(objLead.Approved_Competencies__c!= null && objLead.Approved_Competencies__c.contains(COMM_Constants.TEST_PORTAL_COMPETENCY_PV)) {
                    strDocumentIds += objNPNCustomSetting.get('NPN_OEM_CompetencyExhibit_PV__c') + ',';
                } 
            }*/
            for(NPN_Onboarding_Competency_Level_Mapping__c objNPNCompetencyProgramTypeMapping : mapNPNCompetencyProgramTypeMapping.values()) {
                if((objLead.Approved_Competencies__c!= null && objLead.Approved_Competencies__c.contains(objNPNCompetencyProgramTypeMapping.Competency__c)) 
                && (objLead.Approved_Program_Type__c!= null && objLead.Approved_Program_Type__c.contains(objNPNCompetencyProgramTypeMapping.Program_Type__c))) {
                    strDocumentIds += objNPNCustomSetting.get(objNPNCompetencyProgramTypeMapping.Docusign_Template_Id__c) + ',';
                }
            }
            strDocumentIds += objNPNCustomSetting.NPN_Key_Contacts_Form__c + ',';
            if(objNPNCustomSetting.NPN_Distribution_Form__c != '' && objNPNCustomSetting.NPN_Distribution_Form__c != 'N/A') {
                strDocumentIds += objNPNCustomSetting.NPN_Distribution_Form__c  + ',';
            }                
            if(objNPNCustomSetting.NEW_MDF_REBATE_VENDOR_SETUP_FORM__c != '' && objNPNCustomSetting.NEW_MDF_REBATE_VENDOR_SETUP_FORM__c != 'N/A') {
                strDocumentIds += objNPNCustomSetting.NEW_MDF_REBATE_VENDOR_SETUP_FORM__c + ',';
            }
            for(NPN_Onboarding_Competency_Level_Mapping__c objNPNCompetencyProgramTypeMapping : mapNPNCompetencyProgramTypeMapping.values()) {
                if(!setProgramTypes.contains(objNPNCompetencyProgramTypeMapping.Program_Type__c) && objLead.Approved_Program_Type__c!= null && objLead.Approved_Program_Type__c.contains(objNPNCompetencyProgramTypeMapping.Program_Type__c)) {
                    strDocumentIds += objNPNCustomSetting.get(objNPNCompetencyProgramTypeMapping.Docusign_Program_Guide_Template_Id__c) + ',';
                    setProgramTypes.add(objNPNCompetencyProgramTypeMapping.Program_Type__c);
                }
            }
            if(strDocumentIds != '' && strDocumentIds != null) {
                strDocumentIds = strDocumentIds.replaceAll('null,','');
            }
            if(strDocumentIds != '' && strDocumentIds != null) {                
                strDocumentIds = strDocumentIds.substring(0,strDocumentIds.length()-1);
            }          
        }
    }
}