force-app/main/default/objects/Opportunity/fields/Design_EOL_Date__c.field-meta.xml
<CustomField>
    <fullName>Design_EOL_Date__c</fullName>
    <inlineHelpText>Enter estimated date production to end.  Date only to estimate total Opportunity value (calcs lifetime revenue).</inlineHelpText>
    <label>Production EOL Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Design_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Design_Start_Date__c</fullName>
    <inlineHelpText>Enter estimated date production to begin.  Date ONLY to estimate total Opportunity value (calcs lifetime revenue).  If retail cycle aligned use:
12/1 = 1C
4/1 = 1.5C
7/1 = 2C
10/1 = 3C</inlineHelpText>
    <label>Production Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Opportunity_Type__c.field-meta.xml
<CustomField>
    <fullName>Opportunity_Type__c</fullName>
    <label>Opportunity Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Advanced Driver Assistant</fullName>
            </value>
            <value>
                <fullName>Cluster</fullName>
            </value>
            <value>
                <fullName>Cluster and Infotainment</fullName>
            </value>
            <value>
                <fullName>Expand Business</fullName>
            </value>
            <value>
                <fullName>Machine Replacement/upgrade</fullName>
            </value>
            <value>
                <fullName>New iCafe</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
            <value>
                <fullName>Rear Seat Entertainment</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Monthly_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Monthly_Quantity__c</fullName>
    <description>Populated with the line item quantity, via Apex</description>
    <label>Monthly Quantity</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OpportunityLineItem/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Product2.Name, captured when the OpportunityLineItem is added for a Notebook Opportunity; this is passed on to any associated Schedule Entries for display in the related list and in reports</description>
    <label>Product Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_Entry__c/Schedule_Entry__c.object-meta.xml
<CustomObject>
    <description>Opportunity Management (Custom) : A schedule entry represents a single month&apos;s delivery and revenue schedule for an Opportunity</description>
    <label>Schedule Entry</label>
    <nameField>
        <displayFormat>SE-{0}</displayFormat>
        <label>Schedule Entry ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Schedule Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Schedule_Entry__c/fields/OLI_Id__c.field-meta.xml
<CustomField>
    <fullName>OLI_Id__c</fullName>
    <description>Opportunity Line Item Id for the associated Opportunity Line Item/Product</description>
    <label>OLI Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_Entry__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <description>Opportunity to which the Product Schedule is associated.</description>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Product Revenue</relationshipLabel>
    <relationshipName>Schedule_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Schedule_Entry__c/fields/Product_Name__c.field-meta.xml
<CustomField>
    <fullName>Product_Name__c</fullName>
    <description>Product: Name, written to the Schedule Entry via APEX</description>
    <label>Product Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Schedule_Entry__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantity / # of units associated to a particular Schedule Entry</description>
    <label>Units</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Schedule_Entry__c/fields/Revenue__c.field-meta.xml
<CustomField>
    <fullName>Revenue__c</fullName>
    <description>Revenue associated to a particular Schedule Entry</description>
    <label>Revenue</label>
    <precision>16</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Schedule_Entry__c/fields/Schedule_Date__c.field-meta.xml
<CustomField>
    <fullName>Schedule_Date__c</fullName>
    <description>Start of the month associated to the particular Schedule Entry</description>
    <label>Schedule Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/CreateScheduleEntries.cls
/*
 * 12/17/2018: @Manideep: Commented out this class as part of retiring Old Opportunity Record Types.
 * 6/12/2019: @Manideep: Added fakeMethod() for code coverage as this class is commented out.
*/

public class CreateScheduleEntries {

   // Dummy method for code coverage
  // This method is coverred by the class 'UnitTests_DummyCodeCoverage_DEL_Classes.cls'
  public static void fakeMethod(){
    Integer i = 0;
    i++;
  }

/*
    // This static variable is intended only to allow us to update Schedule Entry records
    // for Notebook and Tegra Tablet opportunities while rolling out support for Quadro, Tesla, and Tegra Auto
    // opportunities. It is set by anonymous Apex code that does a one-time update of 
    // existing Schedule Entry data in Production, and is checked by the Schedule_Entry trigger.
    //
    // The code below refers to Notebook opps, but also applies to Tegra Tablet opps. 
    public static Boolean blnRecalculateNoteookScheduleEntries = false;
    
    public static List<Schedule_Entry__c> createScheduleForNotebookOpps(Opportunity opp, List<OpportunityLineItem> lstOLIs) {
        // createSchedule() takes an Opportunity and a list of (its, presumably) OpportunityLineItems
        // and creates the appropriate Schedule Entries for them.
        //  
        // The assumption here is that the OpportunityLineItems have already been populated
        // with the associated PricebookEntries AND the Product Name 
        //
        // Each Schedule Entry.Monthly Revenue amount for a given Opportunity is added to the
        // Opportunity: Lifetime Revenue amount
        
        List<Schedule_Entry__c> lstSEs = new List<Schedule_Entry__c>();
        List<OpportunityLineItem> lstUpdateOLIs = new List<OpportunityLineItem>();
        Double totalRevenue = 0;
    
        for(OpportunityLineItem oli :lstOLIs) {

            Integer iMonth = opp.Design_Start_Date__c.month();
            Integer iYear = opp.Design_Start_Date__c.year();
            Integer iCount = 0;
        
            Date scheduleDate = Date.NewInstance(iYear, iMonth, 15);
            Integer scheduleMonths = scheduleDate.monthsBetween(opp.Design_EOL_Date__c);
            do {
                Schedule_Entry__c se = new Schedule_Entry__c();
                
                se.Quantity__c     = oli.Monthly_Quantity__c;
                se.Revenue__c      = oli.Monthly_Quantity__c * oli.UnitPrice;
                se.Product_Name__c = oli.Product_Name__c;
                se.Opportunity__c  = opp.Id;
                se.OLI_Id__c       = oli.Id;
                if (opp.RecordType.Name == 'Tegra Tablets, SB, SP Opportunity')
                    se.Opportunity_Type__c = 'Tegra Tablet';
                else
                    se.Opportunity_Type__c = 'Notebook';
                
                se.Schedule_Date__c = scheduleDate;
                
                // adjust scheduleDate to the next month
                scheduleDate = scheduleDate.addMonths(1);
                
                totalRevenue = totalRevenue + se.Revenue__c;
                
                lstSEs.add(se);
                iCount++;
                
            } while (iCount <= scheduleMonths);
        }
        
        try {           
            double revenue;
            revenue = totalRevenue;
            // if(opp.Lifetime_Revenue__c == null) {
            //    revenue = totalRevenue;
            //} else {
            //    revenue = opp.Lifetime_Revenue__c + totalRevenue;
            //}
            //Opportunity newOpp = new Opportunity(Id=opp.Id, Name=opp.Name, Lifetime_Revenue__c=revenue);
            Opportunity newOpp = new Opportunity(Id=opp.Id, Name=opp.Name);

            update lstUpdateOLIs;
            // Cannot use Opportunity.Amount - that is the sum of Opp.LineItem amounts          
            update newOpp;
            return lstSEs;
            
        } catch(Exception ex) {
            return null;
        }
    }
*/    
}