force-app/main/default/objects/Contact/fields/No_Sales_Call__c.field-meta.xml
<CustomField>
    <fullName>No_Sales_Call__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Do Not Contact implementation</description>
    <inlineHelpText>&quot;Do Not Call&quot; indicates that the user does not wish to receive calls from NVIDIA Sales personnel.</inlineHelpText>
    <label>Do Not Call</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/CRM_DoNotCallEmail_Settings__c/CRM_DoNotCallEmail_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains the messages for 
-No Sales Call/No Sales Email
-Pre-MQL Leads banner</description>
    <label>CRM : DoNotCallEmail, Pre-MQL : Settings</label>
</CustomObject>

force-app/main/default/objects/CRM_DoNotCallEmail_Settings__c/fields/Contact_MSG__c.field-meta.xml
<CustomField>
    <fullName>Contact_MSG__c</fullName>
    <description>Message on the Contact detail record when any of the field No Sales Email or No Sales Contact is checked.</description>
    <label>Contact MSG</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CRM_Contact_DoNotCallEmail_Banner_cls.cls
/*
	2016.07.22 - pjena
	Controller class for CRM_Contact_DoNotCallEmail_Banner vf to show banner in the Contact record
	It pulls the No_Sales_Call__c, No_Sales_Email__c information of the Contact record and shows the message if any of them is checked

*/
public class CRM_Contact_DoNotCallEmail_Banner_cls {
    public boolean showMessage{get;set;}
    public string message{get;set;}
    
    public CRM_Contact_DoNotCallEmail_Banner_cls(ApexPages.StandardController sc){
    	Id recordId = sc.getId();
    	
    	if (recordId != null){
    		 
    		 list<Contact> lstLeads = [Select No_Sales_Call__c, No_Sales_Email__c 
    		 						From Contact 
    		 						Where Id = :recordId 
    		 							And (No_Sales_Call__c = true Or No_Sales_Email__c = true)];
    		 
    		 if (!lstLeads.isEmpty()){
    		 	showMessage = true;
    		 	message = CRM_DoNotCallEmail_Settings__c.getOrgDefaults().Contact_MSG__c;
    		 }
    	}
    }
}