force-app/main/default/objects/Contact/fields/Portal_Groups__c.field-meta.xml
<CustomField>
    <fullName>Portal_Groups__c</fullName>
    <label>Permissions &amp; Group Assignments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>All Partner Content</fullName>
            </value>
            <value>
                <fullName>Arrow Embedded Edge</fullName>
            </value>
            <value>
                <fullName>ATP</fullName>
            </value>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Compute DGX Portal Full</fullName>
            </value>
            <value>
                <fullName>Compute Portal Full</fullName>
            </value>
            <value>
                <fullName>CSP Compute DGX Elite</fullName>
            </value>
            <value>
                <fullName>CSP Compute DGX Preferred</fullName>
            </value>
            <value>
                <fullName>CSP Compute Elite</fullName>
            </value>
            <value>
                <fullName>CSP Compute Preferred</fullName>
            </value>
            <value>
                <fullName>CSP Virtualization Elite</fullName>
            </value>
            <value>
                <fullName>CSP Virtualization Preferred</fullName>
            </value>
            <value>
                <fullName>CSP Visualization Elite</fullName>
            </value>
            <value>
                <fullName>CSP Visualization Preferred</fullName>
            </value>
            <value>
                <fullName>DGX Partner Content</fullName>
            </value>
            <value>
                <fullName>DISTI Compute DGX Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Compute Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Embedded Edge Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Virtualization Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Visualization Preferred</fullName>
            </value>
            <value>
                <fullName>EDU Lead Registration</fullName>
            </value>
            <value>
                <fullName>Embedded Edge Elite</fullName>
            </value>
            <value>
                <fullName>Embedded Edge Portal Full</fullName>
            </value>
            <value>
                <fullName>Embedded Edge Preferred</fullName>
            </value>
            <value>
                <fullName>Entitlements</fullName>
            </value>
            <value>
                <fullName>Fed SI Compute DGX Elite</fullName>
            </value>
            <value>
                <fullName>Fed SI Compute DGX Preferred</fullName>
            </value>
            <value>
                <fullName>Fed SI Compute Elite</fullName>
            </value>
            <value>
                <fullName>Fed SI Compute Preferred</fullName>
            </value>
            <value>
                <fullName>Fed SI Embedded Edge Elite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GRID_VCA_Instant_Message__c/GRID_VCA_Instant_Message__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community :</description>
    <label>Portal Instant Message</label>
    <nameField>
        <label>Instant Message Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Instant Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/GRID_VCA_Instant_Message__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Afghanistan</fullName>
            </value>
            <value>
                <fullName>Albania</fullName>
            </value>
            <value>
                <fullName>Algeria</fullName>
            </value>
            <value>
                <fullName>American Samoa</fullName>
            </value>
            <value>
                <fullName>Antarctica</fullName>
            </value>
            <value>
                <fullName>Antigua and Barbuda</fullName>
            </value>
            <value>
                <fullName>Argentina</fullName>
            </value>
            <value>
                <fullName>Armenia</fullName>
            </value>
            <value>
                <fullName>Australia</fullName>
            </value>
            <value>
                <fullName>Austria</fullName>
            </value>
            <value>
                <fullName>Azerbaijan</fullName>
            </value>
            <value>
                <fullName>Bahamas</fullName>
            </value>
            <value>
                <fullName>Bahrain</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
            </value>
            <value>
                <fullName>Barbados</fullName>
            </value>
            <value>
                <fullName>Belarus</fullName>
            </value>
            <value>
                <fullName>Belgium</fullName>
            </value>
            <value>
                <fullName>Bermuda</fullName>
            </value>
            <value>
                <fullName>Bhutan</fullName>
            </value>
            <value>
                <fullName>Bolivia</fullName>
            </value>
            <value>
                <fullName>Bosnia and Herzegovina</fullName>
            </value>
            <value>
                <fullName>Botswana</fullName>
            </value>
            <value>
                <fullName>Brazil</fullName>
            </value>
            <value>
                <fullName>Brunei</fullName>
            </value>
            <value>
                <fullName>Bulgaria</fullName>
            </value>
            <value>
                <fullName>Cambodia</fullName>
            </value>
            <value>
                <fullName>Cameroon</fullName>
            </value>
            <value>
                <fullName>Canada</fullName>
            </value>
            <value>
                <fullName>Chile</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GRID_VCA_Instant_Message__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <label>Message</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/GRID_VCA_Instant_Message__c/fields/Permission_Set_Groups__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set_Groups__c</fullName>
    <label>Permission Set Groups</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Compute DGX Portal Full</fullName>
            </value>
            <value>
                <fullName>Compute Portal Full</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>MDF</fullName>
            </value>
            <value>
                <fullName>NVEP</fullName>
            </value>
            <value>
                <fullName>Portal Lite</fullName>
            </value>
            <value>
                <fullName>SP Compute DGX Elite</fullName>
            </value>
            <value>
                <fullName>SP Compute DGX Preferred</fullName>
            </value>
            <value>
                <fullName>SP Compute Elite</fullName>
            </value>
            <value>
                <fullName>SP Compute Preferred</fullName>
            </value>
            <value>
                <fullName>SP Virtualization Elite</fullName>
            </value>
            <value>
                <fullName>SP Virtualization Preferred</fullName>
            </value>
            <value>
                <fullName>SP Visualization Elite</fullName>
            </value>
            <value>
                <fullName>SP Visualization Preferred</fullName>
            </value>
            <value>
                <fullName>Virtualization Portal Full</fullName>
            </value>
            <value>
                <fullName>Visualization Portal Full</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/GRID_VCA_Instant_Message__c/fields/Portal_Permission_Set__c.field-meta.xml
<CustomField>
    <fullName>Portal_Permission_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Portal Permission Set</label>
    <referenceTo>Portal_Permission_Sets__c</referenceTo>
    <relationshipLabel>Portal Instant Messages</relationshipLabel>
    <relationshipName>Portal_Instant_Messages</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/GRID_VCA_Instant_Message__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>This is a url value for each instant message on portal.</description>
    <label>URL</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Portal_Permission_Sets__c/Portal_Permission_Sets__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : This is a custom object used to maintain SFDC Permission Sets assigned to each portal groups</description>
    <label>Portal Permission Set</label>
    <nameField>
        <label>SFDC Permission Set</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Permission Sets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Portal_Permission_Sets__c/fields/Portal_Groups__c.field-meta.xml
<CustomField>
    <fullName>Portal_Groups__c</fullName>
    <label>Permissions &amp; Group Assignments</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>Compute DGX Portal Full</fullName>
            </value>
            <value>
                <fullName>Compute Portal Full</fullName>
            </value>
            <value>
                <fullName>DISTI Compute DGX Elite</fullName>
            </value>
            <value>
                <fullName>DISTI Compute DGX Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Compute Elite</fullName>
            </value>
            <value>
                <fullName>DISTI Compute Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Virtualization Elite</fullName>
            </value>
            <value>
                <fullName>DISTI Virtualization Preferred</fullName>
            </value>
            <value>
                <fullName>DISTI Visualization Elite</fullName>
            </value>
            <value>
                <fullName>DISTI Visualization Preferred</fullName>
            </value>
            <value>
                <fullName>EDU Lead Registration</fullName>
            </value>
            <value>
                <fullName>Elite</fullName>
            </value>
            <value>
                <fullName>Embedded Edge Portal Full</fullName>
            </value>
            <value>
                <fullName>Entitlements</fullName>
            </value>
            <value>
                <fullName>GRID VCA Legacy</fullName>
            </value>
            <value>
                <fullName>GRID VGX Legacy</fullName>
            </value>
            <value>
                <fullName>IP Portal Lite</fullName>
            </value>
            <value>
                <fullName>Leads &amp; Opportunities</fullName>
            </value>
            <value>
                <fullName>Manage Contacts</fullName>
            </value>
            <value>
                <fullName>Manager</fullName>
            </value>
            <value>
                <fullName>Marketing Hub</fullName>
            </value>
            <value>
                <fullName>MDF</fullName>
            </value>
            <value>
                <fullName>MDFV3</fullName>
            </value>
            <value>
                <fullName>NFR SW License Request</fullName>
            </value>
            <value>
                <fullName>NPN Compliance(SFDC)</fullName>
            </value>
            <value>
                <fullName>NPN Compliance(Tableau)</fullName>
            </value>
            <value>
                <fullName>NPN QPB Statement</fullName>
            </value>
            <value>
                <fullName>NPN Submit POS</fullName>
            </value>
            <value>
                <fullName>OEM Compute Elite</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/clsPartnerPortalComponentSearch.cls
public with sharing class clsPartnerPortalComponentSearch {
    
    public string instanceMessage {get;set;}
    //public List<string> lstStringInstanceMessage {get;set;}
    public List<GRID_VCA_Instant_Message__c>  lstInstantMessage {get;set;}
    public string searchText {get;set;}
    
    public List<WrapInstanceMessages> lstWrapInstanceMessages {get;set;} 
    // In constructor we are initilizing all list which need to set of visualforce page.   
    public clsPartnerPortalComponentSearch (){        
        lstWrapInstanceMessages = new List<WrapInstanceMessages>();
        showInstanceMessage();        
                        
    }        
        
    public class WrapInstanceMessages{
        public string message {get;set;}
        public string url {get;set;}
    }
    
    public string hiddenValue {get;set;}
            
    public pagereference ShowSearchResult(){
        system.debug('Check search text values'+hiddenValue);
        pagereference page = new pagereference('/apex/GRID_portalSearch?='+'abcd').setRedirect(true);
        return page;
    }
    
     public void showInstanceMessage(){
        //lstStringInstanceMessage = new List<string>();  
        /*set<string> messagePermissionSets = new set<string>();
        for(PermissionSetAssignment psa :[SELECT AssigneeId,Id,PermissionSetId,PermissionSet.Name FROM PermissionSetAssignment where AssigneeId=:UserInfo.getUserId()]){
           //  if(psa.PermissionSet.Name.contains('MSG'))
             messagePermissionSets.add(psa.PermissionSet.Name);                                  
        }
        system.debug('check-------------'+messagePermissionSets);   
        instanceMessage = '';
        List<GRID_VCA_Instant_Message__c>  lstInstanceMessage =  [SELECT Expiration_Date__c,URL__c,Portal_Permission_Set__c,Portal_Permission_Set__r.Name, Message__c,Start_Date__c FROM GRID_VCA_Instant_Message__c where Expiration_Date__c>today Order by Expiration_Date__c ASC];
        system.debug('lstInstanceMessage---------'+lstInstanceMessage.size());
        for(GRID_VCA_Instant_Message__c grMsg :lstInstanceMessage){
            if(messagePermissionSets.contains(grMsg.Portal_Permission_Set__r.Name)||grMsg.Portal_Permission_Set__c==null){
                WrapInstanceMessages w = new WrapInstanceMessages();
                w.message  = grMsg.Message__c ;
                w.url  = grMsg.URL__c ;
                lstWrapInstanceMessages.add(w);
                //lstStringInstanceMessage.add(grMsg.Message__c);        
            }
            //instanceMessage = instanceMessage+'  '+grMsg.Message__c;
        }
        //system.debug('lstStringInstanceMessage--------'+lstStringInstanceMessage);
        system.debug('lstWrapInstanceMessages--------'+lstWrapInstanceMessages);
        //lstInstantMessage =  [SELECT Expiration_Date__c,Message__c,Start_Date__c FROM GRID_VCA_Instant_Message__c where Expiration_Date__c>today Order by Expiration_Date__c ASC limit 3]; */
        //Get User detail with contact, permission set group & country info
        User objLoggedInUser = new user();
        set<string> setUserPG = new set<string>();
        objLoggedInUser = [SELECT Id, ContactId, Contact.Portal_Groups__c, Contact.MailingCountry FROM User WHERE Id =: UserInfo.getUserId() AND IsActive = true]; /*ContactId != null*/
        
        //Get logged in user portal group
        if(objLoggedInUser != null && objLoggedInUser.Contact.Portal_Groups__c != null){
            for(string eachPG: objLoggedInUser.Contact.Portal_Groups__c.split(';')){
                setUserPG.add(eachPG.tolowercase());
            }
        }
        
        list<string> lstPSNames;
        set<string> setCountryNames;
        for(GRID_VCA_Instant_Message__c eachInstantMessage: [SELECT Expiration_Date__c,URL__c,Country__c,Permission_Set_Groups__c,Portal_Permission_Set__c,Portal_Permission_Set__r.Name, Message__c,Start_Date__c FROM GRID_VCA_Instant_Message__c where Expiration_Date__c>today Order by Expiration_Date__c ASC]){
            //CASE 1: If country & permission set group blank then message will be available for all users
            if(eachInstantMessage.Country__c == null && eachInstantMessage.Permission_Set_Groups__c ==  null){
                WrapInstanceMessages wrpMessage = new WrapInstanceMessages();
                wrpMessage.message  = eachInstantMessage.Message__c ;
                wrpMessage.url  = eachInstantMessage.URL__c ;
                lstWrapInstanceMessages.add(wrpMessage);
            }//CASE 2: IF country & permission set group are not blank
            else if(eachInstantMessage.Country__c != null && eachInstantMessage.Permission_Set_Groups__c !=  null){
                //Get selected portal groups of instant message
                lstPSNames = new list<string>();
                if (eachInstantMessage.Permission_Set_Groups__c != null){
                    lstPSNames.addAll(eachInstantMessage.Permission_Set_Groups__c.split(';'));
                }
                
                //Get selected country of instant message
                setCountryNames = new set<string>();
                if (eachInstantMessage.Country__c != null){
                    for(string eachCountry: eachInstantMessage.Country__c.split(';')){
                        setCountryNames.add(eachCountry.tolowercase());
                    }
                }
                
                system.debug(lstPSNames + 'Msg*****User'+setUserPG);
                system.debug(eachInstantMessage.Country__c + 'cnt*****Usercnt'+objLoggedInUser.Contact.MailingCountry);
                //Match portal group & country with instant messages
                if(lstPSNames.size()>0){
                    for(string eachPG: lstPSNames){
                        if(setUserPG != null && setUserPG.contains(eachPG.tolowercase()) && setCountryNames != null && setCountryNames.contains(objLoggedInUser.Contact.MailingCountry.tolowercase())){
                            WrapInstanceMessages wrpMessage = new WrapInstanceMessages();
                            wrpMessage.message  = eachInstantMessage.Message__c ;
                            wrpMessage.url  = eachInstantMessage.URL__c ;
                            lstWrapInstanceMessages.add(wrpMessage);
                        }
                    }
                }
            }//CASE 3: IF permission set group is blank but country is not blank
            else if(eachInstantMessage.Country__c != null && eachInstantMessage.Permission_Set_Groups__c ==  null){
                //Get selected country of instant message
                setCountryNames = new set<string>();
                if (eachInstantMessage.Country__c != null){
                    for(string eachCountry: eachInstantMessage.Country__c.split(';')){
                        setCountryNames.add(eachCountry.tolowercase());
                    }
                }
                
                //Match logged in user country
                if(setCountryNames != null && objLoggedInUser.Contact.MailingCountry != null && setCountryNames.contains(objLoggedInUser.Contact.MailingCountry.tolowercase())){
                    WrapInstanceMessages wrpMessage = new WrapInstanceMessages();
                    wrpMessage.message  = eachInstantMessage.Message__c ;
                    wrpMessage.url  = eachInstantMessage.URL__c ;
                    lstWrapInstanceMessages.add(wrpMessage);
                }
            }//CASE 4: If permission set is not blank but country is balnk
            else if(eachInstantMessage.Country__c == null && eachInstantMessage.Permission_Set_Groups__c !=  null){
                //Get selected portal groups on contact
                lstPSNames = new list<string>();
                if (eachInstantMessage.Permission_Set_Groups__c != null){
                    lstPSNames.addAll(eachInstantMessage.Permission_Set_Groups__c.split(';'));
                }
                
                //Match logged in user portal group
                if(lstPSNames.size()>0){
                    for(string eachPG: lstPSNames){
                        if(setUserPG != null && setUserPG.contains(eachPG.tolowercase())){
                            WrapInstanceMessages wrpMessage = new WrapInstanceMessages();
                            wrpMessage.message  = eachInstantMessage.Message__c ;
                            wrpMessage.url  = eachInstantMessage.URL__c ;
                            lstWrapInstanceMessages.add(wrpMessage);
                        }
                    }
                }
            }
        }
    }
    
}