force-app/main/default/objects/Contact/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Tesla</fullName>
            </value>
            <value>
                <fullName>vGPU</fullName>
            </value>
            <value>
                <fullName>Quadro</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Product_Type__c</controllingField>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Automotive</fullName>
            </value>
            <value>
                <fullName>Automotive Datacenter</fullName>
            </value>
            <value>
                <fullName>CMP</fullName>
            </value>
            <value>
                <fullName>DC GPU</fullName>
            </value>
            <value>
                <fullName>DGX</fullName>
            </value>
            <value>
                <fullName>Educational Services</fullName>
            </value>
            <value>
                <fullName>Fleet Command</fullName>
            </value>
            <value>
                <fullName>GeForce</fullName>
            </value>
            <value>
                <fullName>Grid</fullName>
            </value>
            <value>
                <fullName>Grid Hardware</fullName>
            </value>
            <value>
                <fullName>HPC SDK</fullName>
            </value>
            <value>
                <fullName>Jetson</fullName>
            </value>
            <value>
                <fullName>NGC-Ready Services</fullName>
            </value>
            <value>
                <fullName>Parabricks</fullName>
            </value>
            <value>
                <fullName>ProViz</fullName>
            </value>
            <value>
                <fullName>RTX</fullName>
            </value>
            <value>
                <fullName>RTX Blade Server</fullName>
            </value>
            <value>
                <fullName>Titan</fullName>
            </value>
            <value>
                <fullName>Value-Added Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Service</fullName>
            </value>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Spares</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AddUserHelper_test.cls
/**
* Akhilesh:        : 11/18/2019 : Created A test class for AddUserHelper
*/
@isTest
public with sharing class AddUserHelper_test {
    final static String ESP_Community_User  = 'ESP Community User';
    final static String Name                = 'AddUserHelper_test';
    
    @testsetup
    public static void setup(){
        //Create product
        Product2 product = Test_COMM_Factory.getProduct(Name);
        product.Product_Type__c = 'Hardware';
        product.Product_Line__c = 'DGX';
        product.IsActive        = true;
        insert product;
        
        //Create Account -
        Account acc = Test_COMM_Factory.getAccount(Name);
        insert acc;
        
        //Create Entitlement - 
        Entitlement ent  = Test_COMM_Factory.getEntitlement(NAME,acc.id);
        insert ent;
        
        //Create Contact
        Contact cont = Test_COMM_Factory.getContact(acc.Id);
        system.assertNotEquals(Null, cont.AccountId);
        insert cont;
        
        //Create Community User
        Profile espProfile  = [select id from profile  where name =: ESP_Community_User];
        User usr            = Test_COMM_Factory.createUser(cont.Id, espProfile.Id);
        system.assertNotEquals(Null, usr.Email);  
        system.assertNotEquals(Null, usr.username);
    }
    
    @istest
    static void TestsendRegistrationEMail(){
        Test.startTest();
        User usr = [Select Id, Email from User where Account.Name =: Name][0];
        
        //Run as (Community User Id) 
        system.runAs(usr) {
            String Email = usr.email;
            String hostName = 'www';
            String prodFamilySelected = 'DGX';
            
            AddUserHelper.UserType();
            AddUserHelper.sendRegistrationMail(Email, hostName, prodFamilySelected);
            //AddUserHelper.sendonBoardingMail(null, null, null, null, null);
            //System.assert();
        }
        Test.stopTest();
    }
}