force-app/main/default/objects/Knowledge__kav/Knowledge__kav.object-meta.xml
<CustomObject>
    <articleTypeChannelDisplay>
        <articleTypeTemplates>
            <channel>App</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Prm</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Csp</channel>
            <template>Toc</template>
        </articleTypeTemplates>
        <articleTypeTemplates>
            <channel>Pkb</channel>
            <template>Toc</template>
        </articleTypeTemplates>
    </articleTypeChannelDisplay>
    <label>Knowledge</label>
    <pluralLabel>Knowledge</pluralLabel>
</CustomObject>

force-app/main/default/objects/Knowledge__kav/fields/Answer__c.field-meta.xml
<CustomField>
    <fullName>Answer__c</fullName>
    <label>Content</label>
    <length>131000</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Knowledge__kav/fields/Customer_URL__c.field-meta.xml
<CustomField>
    <fullName>Customer_URL__c</fullName>
    <formula>$Label.ESP_Community_BaseURL&amp;&quot;?type=article&amp;id=&quot;&amp;UrlName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Customer URL</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SFDC_TrendingKnowledgeArticle.cls
/*
Class name : SFDC_TrendingKnowledgeArticle
Type : WebService
Description : This class will send Trending articles to external systems
Date        Version        Modified By        Description of change
--------------------------------------------------------------------------------------------------------------------
17/09/19    1.0            Nilesh Adkar        SDS-1695:Service: Trending Knowledge Article API for Enterprise Support Webpage

*/
@RestResource(urlMapping='/KnowledgeArticles/TrendingKnowledgeArticle/*')
global with sharing class SFDC_TrendingKnowledgeArticle{

@HttpGet
global static List<Knowledge__kav> getTrendingArticles(){
    RestRequest req = RestContext.request;
    RestResponse res = new RestResponse();
    RestContext.response = res;
    List<Knowledge__ViewStat> lstKnowledgeViewStat = [SELECT ParentId FROM Knowledge__ViewStat ORDER BY NormalizedScore DESC NULLS LAST LIMIT 20];
    List<Knowledge__kav> lstKnowledgeKav = new List<Knowledge__kav>();
    List<Id> lstIds = new List<Id>();
    if(lstKnowledgeViewStat.isEmpty() && !Test.isRunningTest())
        return null;
    else{
        for(Knowledge__ViewStat tmpViewStat : lstKnowledgeViewStat ){
            lstIds.add(tmpViewStat.ParentId );
        }
        lstKnowledgeKav = [SELECT Title,Answer__c,ArticleNumber,ArticleTotalViewCount,Customer_URL__c,LastPublishedDate,Summary,UrlName FROM Knowledge__kav where KnowledgeArticleId in :lstIds and PublishStatus = 'Online'];
        res.responseBody = Blob.valueOf(JSON.serialize(lstKnowledgeKav ));
        return lstKnowledgeKav;
    }    
  }  
}