force-app/main/default/objects/NVBug__c/NVBug__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : NV Bugs details for the Cases (Case, NVBugs URL)</description>
    <label>NVBug</label>
    <nameField>
        <label>NVBug ID</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>NVBugs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/QPB_Statement__c/QPB_Statement__c.object-meta.xml
<CustomObject>
    <description>NPN: Created for SDS-1406
Stores the QPB details for partners</description>
    <label>QPB Statement</label>
    <nameField>
        <displayFormat>QPBS-{000000}</displayFormat>
        <label>QPB Statement Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>QPB Statements</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/QPB_Statement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>QPB Statements</relationshipLabel>
    <relationshipName>QPB_Statements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Attachment_Uploaded__c.field-meta.xml
<CustomField>
    <fullName>Attachment_Uploaded__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Attachment Uploaded?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/FY_QTR__c.field-meta.xml
<CustomField>
    <fullName>FY_QTR__c</fullName>
    <formula>RIGHT(TEXT(Fiscal_Year__c), 2) + RIGHT(TEXT(Quarter__c), 1) + IF(ISPICKVAL(Type__c, &apos;Progress&apos;),&apos;1&apos;,&apos;2&apos;)</formula>
    <label>FY_QTR</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <sorted>true</sorted>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Inactive</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/QPB_Statement__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Final</fullName>
            </value>
            <value>
                <fullName>Progress</fullName>
            </value>
            <value>
                <fullName>MOU</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ContentDocumentLinkTriggerHelper.cls
public class ContentDocumentLinkTriggerHelper extends NV_TriggerHandler {
    public list<ContentDocumentLink> oldRecords;
    private static list<ContentDocumentLink> triggerNewList;
    private static map<Id, ContentDocumentLink> mapTriggerOld;
       
    /**
     * Gets FileExtension of the inserted content.
     
    public static String getFileExtension(ContentDocumentLink cdl) {
        String fileExtension;
        String docId = cdl.ContentDocumentId;
        FileExtension = [select FileExtension from ContentVersion where ContentDocumentId = :docId].get(0).FileExtension;
        return FileExtension;
    }*/
 
    /**
     * Gets the parent Case Number if the file is linked to an case.
     */
   /** public static String getCaseNumber(ContentDocumentLink cdl) {
        Integer Num;
        String id = cdl.LinkedEntityId;
        if (id.substring(0,3) == '500') {
            Num = [select CaseNumber from Case where Id = :id];
        } 
        return Num;
    }**/
     public override void init() { 
        System.debug('12345 12');
        oldRecords = trigger.old;
        triggerNewList = trigger.New;
        if(oldRecords != null)
            mapTriggerOld = new map<Id, ContentDocumentLink>(oldRecords);
        System.debug('Old Records' + oldRecords + '1');
        System.debug('New Records' + trigger.New + '1');
    }
    public override void afterInsert() {
        CaseUpdate();
        updateQPBStatements();
        LinkFilesToNvBug();
    }
    
    public override void beforeInsert() {
        updateCDLShare();
    }
    
    public static void updateCDLShare() {
        for(ContentDocumentLink objContentDocumentLink : triggerNewList){
            if(objContentDocumentLink.LinkedEntityId !=null && objContentDocumentLink.LinkedEntityId.getSobjectType() == QPB_Statement__c.SobjectType){
                objContentDocumentLink.Visibility = 'AllUsers';
            }
        }
    }
    
    public static void updateQPBStatements() {
        List<QPB_Statement__c> lstQPBStatements = new List<QPB_Statement__c>();
        set<Id> setQPBStatementId = new set<Id>();
        for(ContentDocumentLink objContentDocumentLink : triggerNewList){
            if(objContentDocumentLink.LinkedEntityId !=null && objContentDocumentLink.LinkedEntityId.getSobjectType() == QPB_Statement__c.SobjectType){
                setQPBStatementId.add(objContentDocumentLink.LinkedEntityId);
            }
        }
        if(!setQPBStatementId.isEmpty()) {
           lstQPBStatements = [SELECT Id, Name, Account__r.Name, FY_QTR__c, Type__c, Status__c, Attachment_Uploaded__c from QPB_Statement__c where ID IN :setQPBStatementId];
           if(!lstQPBStatements.isEmpty()) {
               for(QPB_Statement__c objQPBStatements : lstQPBStatements) {
                   objQPBStatements.Attachment_Uploaded__c = True;
               }
               update lstQPBStatements;
           }
        }
    }

    public static void CaseUpdate(){
        //Map<String,Case> lstCase = new Map<String,Case>();
        
        set<Id> caseIds = new set<Id>();
        Id userId = userInfo.getUserId();
    //Updating Status in Case
        for(ContentDocumentLink cdl : triggerNewList){
            //userId = cdl.createdbyId;
            if(cdl.LinkedEntityId !=null && cdl.LinkedEntityId.getSobjectType() == Case.SobjectType){
                caseIds.add(cdl.LinkedEntityId);
            }
        }
        
        if(!caseIds.isEmpty())
            ServiceCloudUtils.UpdateRecentActivityOnCase(caseIds, userId, 'ContentDocumentLink');
    }
    
    public static void LinkFilesToNvBug(){
        List<ContentDocumentLink > lstCDl = new List<ContentDocumentLink >();
        for(ContentDocumentLink cdl : triggerNewList){
            if(cdl.LinkedEntityId !=null && cdl.LinkedEntityId.getSobjectType() == NvBug__c.SobjectType){
                lstCDl.add(cdl);
            }
        }
        if(!lstCDl.isEmpty()){
            string strCDL = JSON.serialize(triggerNewList);
                NVBugOperations.linkNvBugFilesToNVbugSystem(strCDL);
        }            
    }
}