force-app/main/default/objects/Community_User_Local_Settings__c/Community_User_Local_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>CP or PP user Local Language settings</description>
    <label>Community User Local Settings</label>
</CustomObject>

force-app/main/default/objects/Partner_Portal__c/Partner_Portal__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community :</description>
    <label>Partner Portal</label>
    <nameField>
        <label>GRID_Portals Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Portal_Label__c/Partner_Portal_Label__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community :</description>
    <label>Partner Portal Box</label>
    <nameField>
        <label>Partner_Portal_Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal Box</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Portal_Label__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
                <default>true</default>
                <label>English</label>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Turkish</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Taiwanese</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Portal_Label__c/fields/Partner_Portal_Tab__c.field-meta.xml
<CustomField>
    <fullName>Partner_Portal_Tab__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner_Portal_Tab</label>
    <referenceTo>Partner_Portal_Tab__c</referenceTo>
    <relationshipLabel>Partner_Portal_Labels</relationshipLabel>
    <relationshipName>Partner_Portal_Labels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Label__c/fields/Permission_Set__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permission Set</label>
    <referenceTo>Portal_Permission_Sets__c</referenceTo>
    <relationshipLabel>Partner Portal Boxes</relationshipLabel>
    <relationshipName>Partner_Portal_Boxes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Label__c/fields/Portal_Content_Type__c.field-meta.xml
<CustomField>
    <fullName>Portal_Content_Type__c</fullName>
    <label>Portal Content Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Community</fullName>
            </value>
            <value>
                <fullName>NVEP</fullName>
            </value>
            <value>
                <fullName>Visualization</fullName>
            </value>
            <value>
                <fullName>Virtualization</fullName>
            </value>
            <value>
                <fullName>Compute DGX</fullName>
            </value>
            <value>
                <fullName>Compute</fullName>
            </value>
            <value>
                <fullName>Embedded Edge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Portal_Tab__c/Partner_Portal_Tab__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community :</description>
    <label>Partner Portal Tab</label>
    <nameField>
        <label>Partner Portal_Tab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal Tabs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Portal_Tab__c/fields/Community_Tab_URL__c.field-meta.xml
<CustomField>
    <fullName>Community_Tab_URL__c</fullName>
    <label>Community Tab URL</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Tab__c/fields/Language__c.field-meta.xml
<CustomField>
    <fullName>Language__c</fullName>
    <label>Language</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>English</fullName>
            </value>
            <value>
                <fullName>French</fullName>
            </value>
            <value>
                <fullName>German</fullName>
            </value>
            <value>
                <fullName>Italian</fullName>
            </value>
            <value>
                <fullName>Polish</fullName>
            </value>
            <value>
                <fullName>Spanish</fullName>
            </value>
            <value>
                <fullName>Turkish</fullName>
            </value>
            <value>
                <fullName>Japanese</fullName>
            </value>
            <value>
                <fullName>Taiwanese</fullName>
            </value>
            <value>
                <fullName>Chinese</fullName>
            </value>
            <value>
                <fullName>Korean</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Partner_Portal_Tab__c/fields/Local_Name__c.field-meta.xml
<CustomField>
    <fullName>Local_Name__c</fullName>
    <label>Local Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Tab__c/fields/Partner_PortalName__c.field-meta.xml
<CustomField>
    <fullName>Partner_PortalName__c</fullName>
    <label>Partner_PortalName</label>
    <referenceTo>Partner_Portal__c</referenceTo>
    <relationshipLabel>Partner_Portal_Tabs</relationshipLabel>
    <relationshipName>Partner_Portal_Tabs</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Tab__c/fields/Permission_Set__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permission Set</label>
    <referenceTo>Portal_Permission_Sets__c</referenceTo>
    <relationshipLabel>Partner Portal Tabs</relationshipLabel>
    <relationshipName>Partner_Portal_Tabs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Portal_Content_Type__c/Portal_Content_Type__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <label>Portal Content Type</label>
</CustomObject>

force-app/main/default/objects/Portal_Permission_Sets__c/Portal_Permission_Sets__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : This is a custom object used to maintain SFDC Permission Sets assigned to each portal groups</description>
    <label>Portal Permission Set</label>
    <nameField>
        <label>SFDC Permission Set</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Permission Sets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/NV_PartnerCommunityHeader.cls
public class NV_PartnerCommunityHeader {

    public string CurrentTab {get; set;}
    public List<Partner_Portal_Tab__c> lstTabs {get;set;}
    
    public class PPTabWrapper{
        public string tabName{get;set;}
        public string tabLocalName{get;set;}
        public string tabURL{get;set;}
    }
    public list<PPTabWrapper> lstPPTabWrapper{get;set;}
    
    public NV_PartnerCommunityHeader(){
        string ReferrerURL = ApexPages.currentPage().getHeaders().get('Referer');
        CurrentTab = ReferrerURL.right(ReferrerURL.length() - (ReferrerURL.indexOf('=')+1));
        //CurrentTab = ApexPages.currentPage().getParameters().get('tab');
        //get the country filter of the logged on user,
        //-----------------------------------------------------------
        /*
        Logic: If the user records langauge is found in the Community_User_Local_Settings__c then user the use the matching record otherwise default it to English
        */
        string currUserLocaleLangKey = UserInfo.getLanguage();
        string currUserLangName = COMM_Utility.getUserLanguage(currUserLocaleLangKey);
        //-----------------------------------------------------------
        
               
        //Find all the Permission Sets of the logged on User ending with 'Tab'
        set<string> userPSAsWithTab = new set<string>();  
        for(PermissionSetAssignment psa :[Select PermissionSet.Name From PermissionSetAssignment Where AssigneeId=:UserInfo.getUserId() And PermissionSet.Name like '%Tab']){
              userPSAsWithTab.add(psa.PermissionSet.Name);
        }
        
             
        set<Id> userPortalPSsWithTab = new set<Id>();
        for(Portal_Permission_Sets__c PortalPermissionSet : [Select Id From Portal_Permission_Sets__c Where Name in :userPSAsWithTab]){
           //if(PortalPermissionSet.Partner_Portal_Boxes__r.size()>0){
               //put a condition here that user has that box visbility which is inside this Tab.
               userPortalPSsWithTab.add(PortalPermissionSet.Id); 
           //}           
        }
        
        //Get list of Tabs for the GRID VCA Partner Portal and having the Permission Set mapped
        lstTabs = new List<Partner_Portal_Tab__c>([ Select id, Name, Local_Name__c, Community_Tab_URL__c 
                                                    From Partner_Portal_tab__c 
                                                    Where Permission_Set__c in :userPortalPSsWithTab
                                                        And Partner_PortalName__r.name =:COMM_Constants.PP_GRID_VCA_NAME
                                                        And (Language__c = :currUserLangName Or Language__c = null)
                                                    Order By Sort_Order__c]);
        
        //build the lstPPTabWrapper list
        lstPPTabWrapper = new list<PPTabWrapper>();
        for (Partner_Portal_Tab__c ppTab : lstTabs){
            PPTabWrapper tabWrapper = new PPTabWrapper();
            tabWrapper.tabName = ppTab.Name;
            tabWrapper.tabLocalName = ppTab.Local_Name__c;
            tabWrapper.tabURL = ppTab.Community_Tab_URL__c;
            
            lstPPTabWrapper.add(tabWrapper);
        }
        system.debug('lstPPTabWrapper = '+lstPPTabWrapper);
        system.debug('CurrentTab = '+CurrentTab);
        system.debug(ApexPages.currentPage().getHeaders() + ' = ApexPages.currentPage().getHeaders()' );
    }
        
    public pagereference home(){
        pagereference page = new pagereference('/apex/NV_PartnerCommunityTabs').setRedirect(true);
        return page;
    }
    
    //Delete the Portal Content Type custom setting record for the logged in user and delete it
    public pagereference deleteCustomSettingBeforeLogOut(){
        Portal_Content_Type__c userPortalContentType = Portal_Content_Type__c.getValues(UserInfo.getUserId());
        if(userPortalContentType != null){
            delete userPortalContentType;
        }
        return null;
    }
    
}