force-app/main/default/objects/NV_Batch_Job_Setting__mdt/NV_Batch_Job_Setting__mdt.object-meta.xml
<CustomObject>
    <label>NV Batch Job Setting</label>
    <pluralLabel>NV Batch Job Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/NV_Batch_Job_Setting__mdt/fields/Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Batch_Size__c</fullName>
    <defaultValue>200</defaultValue>
    <label>Batch Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NV_Batch_Job_Setting__mdt/fields/Disable_Job__c.field-meta.xml
<CustomField>
    <fullName>Disable_Job__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this checkbox to disable the scheduled Job.</description>
    <inlineHelpText>Check this checkbox to disable the scheduled Job.</inlineHelpText>
    <label>Disable Job</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NV_Batch_Job_Setting__mdt/fields/Frequency__c.field-meta.xml
<CustomField>
    <fullName>Frequency__c</fullName>
    <inlineHelpText>Frequency of Job in minutes</inlineHelpText>
    <label>Frequency</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/NV_Batch_Job_Setting__mdt/fields/Lookback_Time__c.field-meta.xml
<CustomField>
    <fullName>Lookback_Time__c</fullName>
    <inlineHelpText>Lookback time in minutes</inlineHelpText>
    <label>Lookback Time</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/NV_Utility.cls
/**
 * A Utility Class to add all code common for all teams.
 * Created: 10/20/2019 - Akhilesh Gupta | 
 * Update:  10/20/2019 - Akhilesh Gupta | Added Functions for Public Group/Queues.
  
 */

public with sharing class NV_Utility {
	
	/*Start: Functions to get Public Group and Queue Details. */
	private static map<string, Id> allPublicGroupsByDevName = new map<string, Id>();
	private static map<string, Id> allPublicGroupsByName = new map<string, Id>();
	//Find Group/Queue by Developer Name
	public static Id getPublicGroupsOrQueueIdByDevName(String name){
		getPublicGroupAndQueuesByName();
		return allPublicGroupsByDevName.get(name);
	}
	//Find Group/Queue by Name
	public static Id getPublicGroupOrQueueIdByName(String name){
		getPublicGroupAndQueuesByName();
		return allPublicGroupsByName.get(name);
	}
	//Query all Public Groups and Queue
	private static void getPublicGroupAndQueuesByName(){
		if (allPublicGroupsByName == null || allPublicGroupsByName.isEmpty()){
			list<Group> lstPGs = [Select Name, DeveloperName From Group 
									where Type in ('Regular', 'Queue')];
	    	
			for (Group grp : lstPGs){
				allPublicGroupsByName.put(grp.Name, grp.Id);
				allPublicGroupsByDevName.put(grp.DeveloperName, grp.Id);
			}
		}
	}
	/*End: Functions for Public Group and Queue */
	
	/*Funtion to get Batch Job settings*/
    public static map<String, NV_Batch_Job_Setting__mdt> batchJobSettingMap = null;
    public static map<String, NV_Batch_Job_Setting__mdt> getbatchJobSettings(){
        if(batchJobSettingMap == null){
            batchJobSettingMap = new map<String, NV_Batch_Job_Setting__mdt>();
            for(NV_Batch_Job_Setting__mdt setting : [SELECT Id, MasterLabel, DeveloperName, Batch_Size__c
            											, Disable_Job__c, Frequency__c, Lookback_Time__c 
                                                	FROM NV_Batch_Job_Setting__mdt]){
                batchJobSettingMap.put(setting.MasterLabel, setting);
            }
        }
        return batchJobSettingMap;
    }
    
    public static NV_Batch_Job_Setting__mdt getbatchJobSetting(String Name){
        if(batchJobSettingMap == null)
            getbatchJobSettings();
        
        return batchJobSettingMap.get(Name);
    }
}