force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner Contact</label>
</RecordType>

force-app/main/default/objects/Country_List__c/Country_List__c.object-meta.xml
<CustomObject>
    <description>CRM : Country/State/Region/Sub-Region/Territory: Contains the Country ISO Code, Name for all countries. Used to drive Region/Sub-Region/Territory information.
Need Public Read Only OWD for internal and external access.</description>
    <label>Country List</label>
    <nameField>
        <label>Country Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Country Lists</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/Country_List__c/fields/ISO_Code_3__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code_3__c</fullName>
    <description>3 letter ISO Code</description>
    <inlineHelpText>3 letter ISO Code</inlineHelpText>
    <label>ISO Code (3-letter)</label>
    <length>3</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Country_List__c/fields/ISO_Code__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code__c</fullName>
    <label>ISO Code</label>
    <length>2</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/DR_SalesOps_Admins__c/DR_SalesOps_Admins__c.object-meta.xml
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>DR : Partner Account Billing Country specific Deal Reg SalesOps admins</description>
    <label>DR : SalesOps : Admins</label>
</CustomObject>

force-app/main/default/objects/DR_SalesOps_Admins__c/fields/DR_Admin_Username__c.field-meta.xml
<CustomField>
    <fullName>DR_Admin_Username__c</fullName>
    <description>SFDC Username of the SalesOps Deal Reg Admin. Put the comma separated Country Names in the Billing Country(s) field. Create a separate row with name = &apos;OTHERS&apos; and the default username that will be used in case the Country of the Partner Contact does not match with any</description>
    <inlineHelpText>SFDC Username of the SalesOps Deal Reg Admin. Put the comma separated Country Names in the Billing Country(s) field. Create a separate row with name = &apos;OTHERS&apos; and the default username that will be used in case there is no match</inlineHelpText>
    <label>DR Admin Username</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DR_SalesOps_Admins__c/fields/DR_Billing_Country_s__c.field-meta.xml
<CustomField>
    <fullName>DR_Billing_Country_s__c</fullName>
    <inlineHelpText>Name of the Partner Account Billing Country (semi-colon separated if more than one)</inlineHelpText>
    <label>DR : Billing Country(s)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DR_Settings__c/DR_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>DR : required fields tracking, Constant &quot;Others&quot; for SalesOps Admin, Deal Status related constants</description>
    <label>DR : Settings</label>
</CustomObject>

force-app/main/default/objects/DR_Settings__c/fields/DR_Constant_Others__c.field-meta.xml
<CustomField>
    <fullName>DR_Constant_Others__c</fullName>
    <description>Constant used for deriving SalesOps admin in case no matching billing country found. It can be defaulted to &quot;Others&quot; or match with the value in DR : SalesOps : Admins</description>
    <inlineHelpText>Constant used for deriving SalesOps admin in case no matching billing country found. It can be defaulted to &quot;Others&quot; or match with the value in DR : SalesOps : Admins or remain blank</inlineHelpText>
    <label>DR Constant Others</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DR_Settings__c/fields/DR_NALA_TAM_User_Id__c.field-meta.xml
<CustomField>
    <fullName>DR_NALA_TAM_User_Id__c</fullName>
    <description>Deal Registration :  User id to be used for the Deal Reg Lead ownerId field for NALA regions</description>
    <inlineHelpText>User id to be used for the Deal Reg Lead ownerId field for NALA regions</inlineHelpText>
    <label>DR : NALA : TAM User Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DR_Settings__c/fields/Lead_RecordTypeName_For_Deal_Reg__c.field-meta.xml
<CustomField>
    <fullName>Lead_RecordTypeName_For_Deal_Reg__c</fullName>
    <defaultValue>&quot;Deal Registration&quot;</defaultValue>
    <description>Deal Registration Lead Record Type Name</description>
    <inlineHelpText>Deal Registration Lead Record Type  Name</inlineHelpText>
    <label>Lead RecordTypeName For Deal Reg</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DR_Settings__c/fields/Lead_Source__c.field-meta.xml
<CustomField>
    <fullName>Lead_Source__c</fullName>
    <defaultValue>&quot;Deal Registration&quot;</defaultValue>
    <description>Opp Reg 3.0 field to set the Lead Source &quot;Deal Registration&quot; of the Lead</description>
    <inlineHelpText>Opp Reg 3.0 field to set the Lead Source &quot;Deal Registration&quot; of the Lead</inlineHelpText>
    <label>Lead Source</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DR_Settings__c/fields/Lead_Status_IR__c.field-meta.xml
<CustomField>
    <fullName>Lead_Status_IR__c</fullName>
    <defaultValue>&quot;In Review&quot;</defaultValue>
    <description>Opp Reg 3.0 field to set the Lead Status to  &quot;In Review&quot;</description>
    <inlineHelpText>Opp Reg 3.0 field to set the Lead Status to  &quot;In Review&quot;</inlineHelpText>
    <label>Lead Status : IR</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/DR_Settings__c/fields/Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>Lead_Type__c</fullName>
    <defaultValue>&quot;Deal Registration&quot;</defaultValue>
    <description>Opp Reg 3.0 field to set the DR_Lead_Type__c &quot;Deal Registration&quot; of the Lead</description>
    <inlineHelpText>Opp Reg 3.0 field to set the DR_Lead_Type__c &quot;Deal Registration&quot; of the Lead</inlineHelpText>
    <label>Lead Type</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DR_Additional_Team_Member__c.field-meta.xml
<CustomField>
    <fullName>DR_Additional_Team_Member__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Sales/Account Manager</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads (Additional Team Member)</relationshipLabel>
    <relationshipName>DealRegATMLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DR_Additional_Team_Member_Email__c.field-meta.xml
<CustomField>
    <fullName>DR_Additional_Team_Member_Email__c</fullName>
    <label>Partner Sales/Account Manager Email</label>
    <type>Email</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DR_ChannelAdmin__c.field-meta.xml
<CustomField>
    <fullName>DR_ChannelAdmin__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Channel Admin</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DR_Is_Submitted_via_Btn_Click__c.field-meta.xml
<CustomField>
    <fullName>DR_Is_Submitted_via_Btn_Click__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Submitted via Btn Click?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DR_Lead_Type__c.field-meta.xml
<CustomField>
    <fullName>DR_Lead_Type__c</fullName>
    <label>Lead Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DR_Partner_Sales_Rep_Company__c.field-meta.xml
<CustomField>
    <fullName>DR_Partner_Sales_Rep_Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Sales Rep Company</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Leads (Partner Sales Rep Company)</relationshipLabel>
    <relationshipName>DealRegPSRCLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DR_Partner_Sales_Rep_Name__c.field-meta.xml
<CustomField>
    <fullName>DR_Partner_Sales_Rep_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner Sales Rep Name</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Leads (Partner Sales Rep Name)</relationshipLabel>
    <relationshipName>DealRegPSRLeads</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/DR_PBM__c.field-meta.xml
<CustomField>
    <fullName>DR_PBM__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>DR: This field contains the Owner of the &quot;Partner Sales Rep Company&quot;.</description>
    <label>Registration PBM</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Leads1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Lead/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>NALA</fullName>
            </value>
            <value>
                <fullName>JAPAN</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/State_List__c/State_List__c.object-meta.xml
<CustomObject>
    <description>CRM : Country/State/Region/Sub-Region/Territory : Contains all the State (ISO Code, Name) and has reference to Country_List record.
Need Public Read Only OWD for internal and external access.</description>
    <label>State List</label>
    <nameField>
        <label>State Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>State Lists</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/State_List__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Country</label>
    <referenceTo>Country_List__c</referenceTo>
    <relationshipName>States</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/State_List__c/fields/ISO_Code__c.field-meta.xml
<CustomField>
    <fullName>ISO_Code__c</fullName>
    <label>ISO Code</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/User/fields/Region__c.field-meta.xml
<CustomField>
    <fullName>Region__c</fullName>
    <description>Used in Enterprise KPIs and Other dashboards</description>
    <label>Region</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>APAC</fullName>
            </value>
            <value>
                <fullName>EMEA</fullName>
            </value>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>NALA</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/DR_CreateDR_cls.cls
/*
	2017.11.29 - PJENA - Deal Registration - Controller class for vf DR_CreateDR
	2018.02.03 - PJENA - Bug fix - correct state was not getting passed to TAM logic
	2018.02.16 - PJENA - Set DR_PBM User (DR_Partner_Sales_Rep_Company__c Owner)
	2018.07.20 - PJENA - SDS-587 (All NALA deal registrations to route to Anish Dave instead of following the Territory Alignment logic)
	
*/

public without sharing class DR_CreateDR_cls {
	
	//properties
	public boolean isError{get;set;}
	public boolean showError{get;set;}
	string dealRegId;
    public Lead oDealReg{get;set;}
	
	//default constructor
	public DR_CreateDR_cls(){
		oDealReg = new Lead();
	}
	
	//save process
	public pageReference saveDR(){
		Database.SaveResult oDealRegToSave = null;
        PageReference pageRef = null;
        try{
        	
			//automation logic
        	//1. Get the config details from DR Settings
        	string drsLeadDRRecTypeName = DR_Settings__c.getOrgDefaults().Lead_RecordTypeName_For_Deal_Reg__c;
        	string drsLeadStaus_IR = DR_Settings__c.getOrgDefaults().Lead_Status_IR__c;
        	string drsLeadLeadSource = DR_Settings__c.getOrgDefaults().Lead_Source__c;
        	string drsLeadType = DR_Settings__c.getOrgDefaults().Lead_Type__c;
        	//2018.07.20 - PJENA - SDS-587 (All NALA deal registrations to route to Anish Dave instead of following the Territory Alignment logic)
        	string drsNALA_TAM = DR_Settings__c.getOrgDefaults().DR_NALA_TAM_User_Id__c;
        	
        	map<string, Id> mapLeadDRID = COMM_Utility.getRTsByName('Lead', drsLeadDRRecTypeName);
        	oDealReg.RecordTypeId = mapLeadDRID.get(drsLeadDRRecTypeName); //set the record type to Deal Reg
        	oDealReg.LeadSource = drsLeadLeadSource; //'Deal Registration';
        	oDealReg.DR_Lead_Type__c = drsLeadType; //'Deal Registration';
        	oDealReg.Status = drsLeadStaus_IR; //'In Review';
        	
        	//2: Set the Partner User Reference fields
        	User currPartnerUser = [Select Contact.AccountId, Contact.Account.OwnerId, Contact.Account.BillingCountry, Contact.Id, ContactId From User u where id = :userInfo.getUserId()];
        	oDealReg.DR_Partner_Sales_Rep_Name__c = currPartnerUser.Contact.Id;
        	oDealReg.DR_Partner_Sales_Rep_Company__c = currPartnerUser.Contact.AccountId;
        	//2018.02.16 - PJENA - Set DR_PBM User (DR_Partner_Sales_Rep_Company__c Owner)
        	oDealReg.DR_PBM__c = currPartnerUser.Contact.Account.OwnerId;
        	
        	//3. set the additional team member contact
        	if (string.isNotBlank(oDealReg.DR_Additional_Team_Member_Email__c)){
        		list<Contact> lstAdditionalContacts = [	Select Id, email 
        												From Contact 
        												Where email = :oDealReg.DR_Additional_Team_Member_Email__c 
        													And AccountId = :currPartnerUser.Contact.AccountId
        												];
        		if (!lstAdditionalContacts.isEmpty()){
        			oDealReg.DR_Additional_Team_Member__c = lstAdditionalContacts[0].Id;
        		}
        	}
        	
        	//Find the region__c from the lead country
        	string strCountryName, strRegion;
        	string strStateName = '';
        	list<Country_List__c> lstCountryList = [Select Region__c, Name, ISO_Code__c, ISO_Code_3__c, 
        												(Select Name, ISO_Code__c From States__r) 
        											From Country_List__c 
        											Where ISO_Code__c = :oDealReg.CountryCode];
        	if (!lstCountryList.isEmpty()){
				strCountryName = lstCountryList[0].Name;
				strRegion = lstCountryList[0].Region__c;
				//oDealReg.Region__c = strRegion;
				system.debug('***Country Name: ' + strCountryName);
				system.debug('***Region Name: ' + strRegion);
				//2018.07.20 - PJENA - SDS-587 (All NALA deal registrations to route to Anish Dave instead of following the Territory Alignment logic)
				/*
				if (!lstCountryList[0].States__r.isEmpty()){
					for (State_List__c st : lstCountryList[0].States__r){
						if (st.ISO_Code__c == oDealReg.StateCode){
							strStateName =  st.Name; //lstCountryList[0].States__r[0].Name;
							system.debug('***strStateName: ' +strStateName) ;
							break;
						}
					}
					
				}
				*/
				//End: //2018.07.20 - PJENA - SDS-587 (All NALA deal registrations to route to Anish Dave instead of following the Territory Alignment logic)
        	}
        	
        	//2018.07.20 - PJENA - SDS-587 (All NALA deal registrations to route to Anish Dave instead of following the Territory Alignment logic)
        	//As the TAM is only for NALA and all the NALA deal registrations are going to Anish, we no longer need the TAM logic
        	
        	/*
        	//4. change ownership based on the TAM/PBM logic
        	//Call the TAM service with Partner's Customer Region, Country, State/Province, City, Industry (Partner's Customer = Lead here).
			//-------------------------------------------------------------------------------------------------------------------------------
			boolean bTAMFound = false;
			if (!bTAMFound){
				system.debug('***1. Find TAM from TAM service with  Partner\'s Customer Region, Country, State/Province, City, Industry (Partner\'s Customer = Lead here).');
				List<TAMSObjectRecTemplate> lstTSRT = new List<TAMSObjectRecTemplate>();
				TAMSObjectRecTemplate TSRT = new TAMSObjectRecTemplate();
				//TSRT.Id = lstOpps[0].AccountId; 
				TSRT.Region = strRegion; //oDealReg.Region__c;
				TSRT.Country = strCountryName; //oDealReg.Country;
				TSRT.State = strStateName; //oDealReg.State;
				TSRT.City = oDealReg.City;
				TSRT.Industry = oDealReg.Industry;
				lstTSRT.add(TSRT);
				
				system.debug('***Input lstTSRT: ' + lstTSRT);
				system.debug('***Invoke method CRM_TAM_Utility > getTAMs()');
				lstTSRT = CRM_TAM_Utility.getTAMs(lstTSRT);
				system.debug('***End: Invoke method CRM_TAM_Utility > getTAMs()');
				system.debug('***Output lstTSRT: ' + lstTSRT);
				
				//check if the TAMId gets populated from CRM_TAM_Utility Service
				if (string.isNotBlank(lstTSRT[0].TAMId)){
					oDealReg.OwnerId = lstTSRT[0].TAMId;
					bTAMFound = true;
					system.debug('***Checked TAM Matrix > bTAMFound: ' + bTAMFound);
				}
			}
			//End: Call the TAM service with Partner's Customer Region, Country, State/Province, City, Industry (Partner's Customer = Lead here).
			//-------------------------------------------------------------------------------------------------------------------------------
			*/
			//4. change ownership of NALA Deal Registrations to Anish
			boolean bTAMFound = false;
			if (string.isNotBlank(strRegion) && strRegion == COMM_Constants.ADDRESS_REGION_NALA && string.isNotBlank(drsNALA_TAM)){
				system.debug('***1. Regions = NALA, TAM is set to ' + drsNALA_TAM);
				bTAMFound = true;
				oDealReg.OwnerId = drsNALA_TAM;
			}
			
			//If TAM logic does not give any value, the PBM (oppty.Account.OwnerId) is the Owner of this Lead.
			//-------------------------------------------------------------------------------------------------------------------------------
			if (!bTAMFound){
				system.debug('***2. If Step 1 does not give any value, the PBM (oppty.Account.OwnerId) is the TAM.');
				oDealReg.OwnerId = currPartnerUser.Contact.Account.OwnerId;
				bTAMFound = true;
				system.debug('***Checked PBM > bTAMFound: ' + bTAMFound); 
			}
			//-------------------------------------------------------------------------------------------------------------------------------
			
			
        	//5. Set the Channel Admin based on the Opp Reg process
        	oDealReg.DR_ChannelAdmin__c = getChannelAdmin(currPartnerUser.Contact.Account.BillingCountry);
        	
        	//6. prepare the Deal Registration record for submission through code
        	oDealReg.DR_Is_Submitted_via_Btn_Click__c = true;

            //7. Insert the lead
            oDealRegToSave = Database.insert(oDealReg);
			
        	//8. Submit for Approval.
			system.debug('***Deal Registration Submitted for Approval.');
			Approval.ProcessSubmitRequest psr = new Approval.ProcessSubmitRequest();
			//psr.setComments('Registered Deal Submitted for Approval');
			psr.setComments(system.label.CRM_DR_RGSTR_DEAL_SUBMITTED);
			psr.setObjectId(oDealRegToSave.id);
			Approval.ProcessResult result = Approval.process(psr);
        	
			//9. Unlock the Deal Reg lead record
			list<lead> lstLeads = [Select Id From Lead Where Id = :oDealRegToSave.Id];
			list<Approval.UnlockResult> urList = Approval.unlock(lstLeads, false);
			
			// Iterate through each returned result
			for(Approval.UnlockResult ur : urList) {
			    if (ur.isSuccess()) {
			        // Operation was successful, so get the ID of the record that was processed
			        System.debug('***Successfully locked Lead with ID: ' + ur.getId());
			    }
			    else {
			        // Operation failed, so get all errors                
			        for(Database.Error err : ur.getErrors()) {
			            System.debug('***The following error has occurred.');                    
			            System.debug('***' + err.getStatusCode() + ': ' + err.getMessage());
			            System.debug('***Lead fields that affected this error: ' + err.getFields());
			        }
			    }
			}
			
            
            //10. Confirmation Redirection
            pageRef = new PageReference('/apex/DR_CreateDRConfirm');
            //End: Confirmation Redirection
        }catch(exception ex){
        	//exception logic
        	system.debug('***Exception: ' + ex);
        	string errMsg = ex.getMessage();
        	showError = true;
        	ApexPages.addmessage(new ApexPages.message(ApexPages.severity.ERROR, errMsg));
        }   
        return pageRef;
    }
	
    //cancel process
    public pageReference cancelDR(){
    	PageReference pageRef = null;
        pageRef = new PageReference('/apex/DR_CreateDRCancel');
        return pageRef;
    }
	
	
    //Get SalesOpsApprover user Id from Custom Settings based on Partner Account Country
	//===========================================================================================
	/*
	The sample structure of data
	1. United States; Canada => pjena@nvidia.com
	2. India => ghardy@nvidia.com
	3. OTHERS => mnagatani@nvidia.com
	*/
	//===========================================================================================
	private static Id getChannelAdmin(string countryName){ //Partner User > Contact > Account > BillingCountry
		system.debug('***Enters getChannelAdmin with country name: ' + countryName);
		//build the countryname-channeladminUsername map
		Map<string, string> mapCountryNameAdminUserName = new Map<String, string>();
		Map<string, DR_SalesOps_Admins__c> allDRSalesOpsAdmins = DR_SalesOps_Admins__c.getAll();
		for (DR_SalesOps_Admins__c cs : allDRSalesOpsAdmins.Values() ){
			string strCountryList = cs.DR_Billing_Country_s__c;
			if (strCountryList != null){
				list<string> lstCountry = strCountryList.split(';');
				for (string strCountry : lstCountry){
					string strCountrySpaceTrimmed = strCountry.trim();
					if (strCountrySpaceTrimmed != '' && mapCountryNameAdminUserName.get(strCountrySpaceTrimmed) == null){
						//add it to the map mapCountryNameAdminUserName
						mapCountryNameAdminUserName.put(strCountrySpaceTrimmed.toLowerCase(), cs.DR_Admin_Username__c);
					}
				}
			}
		}
		//End: build the countryname-channeladminUsername map
		
		string ChannelAdminUserName;
		Id ChannelAdminUserSFDCId;
		list<User> lstSalesOpsAdminUser;
		
		//find the ChannelAdmin User Name
		if (string.isNotBlank(countryName)){
			ChannelAdminUserName = mapCountryNameAdminUserName.get(countryName.toLowerCase());
			system.debug('***ChannelAdminUserName: ' + ChannelAdminUserName);
			//if there is Admin for a country check for the existence of OTHERS admin user. If present use it, otherewise give up
			if (string.isBlank(ChannelAdminUserName)){
				string DRConstant_Others = DR_Settings__c.getOrgDefaults().DR_Constant_Others__c; // This is like a Constant but instead stored in Custom Settings
				system.debug('***DRConstant_Others: ' + DRConstant_Others);
				if (string.isNotBlank(DRConstant_Others)){
					ChannelAdminUserName = mapCountryNameAdminUserName.get(DRConstant_Others.toLowerCase());
					system.debug('***ChannelAdminUserName - Other: ' + ChannelAdminUserName);
				}
						
			}
		}
		//End: find the ChannelAdmin User Name
		
		//Get the ChannelAdminUser Id
		if (string.isNotBlank(ChannelAdminUserName)){
			lstSalesOpsAdminUser = [Select Id From User Where username = :ChannelAdminUserName and IsActive = true];
			if(lstSalesOpsAdminUser != null && !lstSalesOpsAdminUser.isEmpty()){
				ChannelAdminUserSFDCId = lstSalesOpsAdminUser[0].Id;
			}
		}
		//End: Get the ChannelAdminUser Id
		system.debug('***lstSalesOpsAdminUser: ' + lstSalesOpsAdminUser);
		system.debug('***Exits getChannelAdmin with country name: ' + countryName);
		return ChannelAdminUserSFDCId;
	}
	//============================================================================================
    
}