force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner Contact</label>
</RecordType>

force-app/main/default/objects/NVIDIASFDCOrgInstanceInfo__c/NVIDIASFDCOrgInstanceInfo__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>This contains SFDC Instance Information (IsSandbox, Sandbox name, Sandbox Id). This will be auto set during Sandbox Refresh or by running NVIDIASFDCOrgInstanceInitializer class method</description>
    <label>NVIDIASFDCOrgInstanceInfo</label>
</CustomObject>

force-app/main/default/objects/NVIDIASFDCOrgInstanceInfo__c/fields/IsSandbox__c.field-meta.xml
<CustomField>
    <fullName>IsSandbox__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Is this instance a Sandbox?</description>
    <label>IsSandbox</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/NVIDIASFDCOrgInstanceInfo__c/fields/OrgId__c.field-meta.xml
<CustomField>
    <fullName>OrgId__c</fullName>
    <description>Sandbox Org Id : 00D</description>
    <label>OrgId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NVIDIASFDCOrgInstanceInfo__c/fields/RefreshDateTime__c.field-meta.xml
<CustomField>
    <fullName>RefreshDateTime__c</fullName>
    <label>RefreshDateTime</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/NVIDIASFDCOrgInstanceInfo__c/fields/SandboxId__c.field-meta.xml
<CustomField>
    <fullName>SandboxId__c</fullName>
    <description>Sandbox Id : 07E</description>
    <label>SandboxId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/NVIDIASFDCOrgInstanceInfo__c/fields/SandboxName__c.field-meta.xml
<CustomField>
    <fullName>SandboxName__c</fullName>
    <description>Name of the sandbox</description>
    <label>SandboxName</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NVIDIASFDCOrgInstanceInitializer.cls
/*
	2019.08.14 - Sandbox Initializer - runs automatic after the completion of sandbox referesh
		- Sets the NVIDIASFDCOrgInstanceInfo custom settings with Sandbox Name
		- Upates all email addresses of User and Contact records

*/

global class NVIDIASFDCOrgInstanceInitializer implements SandboxPostCopy{
	global void runApexClass(SandboxContext context) {
		
		Organization org = [SELECT IsSandbox FROM Organization];
		
		NVIDIASFDCOrgInstanceInfo__c oSFDCOrgInfo = new NVIDIASFDCOrgInstanceInfo__c();
		oSFDCOrgInfo.Name = 'NVIDIASFDCOrgInstanceInfo';
		oSFDCOrgInfo.IsSandbox__c = org.IsSandbox;
		oSFDCOrgInfo.OrgId__c = context.organizationId();
		oSFDCOrgInfo.RefreshDateTime__c = Datetime.now();
		oSFDCOrgInfo.SandboxId__c = context.sandboxId();
		oSFDCOrgInfo.SandboxName__c = context.sandboxName();
		system.debug('***oSFDCOrgInfo: ' + oSFDCOrgInfo);
		insert oSFDCOrgInfo;
		
		//set all admin emails back to regular emails
		system.debug('***Begin Call: revertAdminEmails()');
		revertAdminEmails();
		system.debug('***End Call: revertAdminEmails()');
		
		//invoke batch job to update email address in contact and user record
		system.debug('***Begin Batch Call: NVIDIASFDCOrgInstanceInitializer_batch');
		NVIDIASFDCOrgInstanceInitializer_batch oNVUsrConBatch = new NVIDIASFDCOrgInstanceInitializer_batch();
		database.executeBatch(oNVUsrConBatch, 100);
		system.debug('***End Batch Call: NVIDIASFDCOrgInstanceInitializer_batch');
		
    }
    
    global static void revertAdminEmails(){
		list<User> adminUserEmailList = [select Email from User where profile.name in ('System Administrator', 'Data Administrator', 'Sales Profile - Partner Admin') and isactive = true];
		list<User> adminUserEmailList_upd = new list<User>();
		for(User uc : adminUserEmailList){
			//to remove appended domain 
			string addedPhrase = '.invalid';
			uc.Email = uc.Email.remove(addedPhrase);
			adminUserEmailList_upd.add(uc);
		}
		system.debug('***adminUserEmailList_upd : ' + adminUserEmailList_upd);
        if(adminUserEmailList_upd.size() > 0){
             database.update(adminUserEmailList_upd, false);
		}
    }
    
    
}