force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner Contact</label>
</RecordType>

force-app/main/default/objects/Opportunity/fields/DR_Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>DR_Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SDS-1740-Remove field filter from Primary Customer Contact field on the Opportunity such that someone can pick any contact from the db</description>
    <inlineHelpText>This field must contain the Primary Contact involved with this opportunity</inlineHelpText>
    <label>Primary Customer Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Customer Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Role__c</fullName>
    <inlineHelpText>Select the role that best describes the Primary Customer Contact above.  This field must be populated when a Primary Customer Contact is identified.</inlineHelpText>
    <label>Primary Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Contact</fullName>
                <default>true</default>
                <label>Sales Contact</label>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Influencer/Buyer</fullName>
            </value>
            <value>
                <fullName>Solution Architect/IT</fullName>
            </value>
            <value>
                <fullName>Renewal Contact</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_CRM_OPP_ContactRole_Banner_cls.cls
/*
    2016.08.24 Test Class for  Apex Controller CRM_OPP_ContactRole_Banner_cls.cls
*/
 
@isTest(SeeAllData=false)
private class Test_CRM_OPP_ContactRole_Banner_cls {
    
    //Create Opporunity with Contact Role, Delete the contact role
    static testMethod void testCRM_OPP_ContactRole_Banner_cls(){
        //setup Custom Settings CRM : OCR : Settings: It sets the Default Contact Role to "Sales Contact"
        //--------------------------------------------
        Test_COMM_Factory.set_CRM_OCR_Settings();
        //--------------------------------------------
        
        
        //get all Record Types
        list<string> lstSObjects = new list<string>{'Account', 'Opportunity'};
        map<String, Id> mapRTNameId = Test_COMM_Factory.getAllRTsByName(lstSObjects);
        
        //declare the Account
        Account partnerAcc;
        
        //Create a Partner Account with Billing Country
        partnerAcc = Test_COMM_Factory.createAccountWithBillingAddress('PartnerAccount1', mapRTNameId.get(COMM_Constants.ACCOUNT_RT_NV_PPA), COMM_Constants.ADDRESS_STREET, COMM_Constants.ADDRESS_CITY, COMM_Constants.ADDRESS_STATE, COMM_Constants.ADDRESS_COUNTRY, COMM_Constants.ADDRESS_ZIP );
        system.debug('***partnerAcc: ' + partnerAcc);
        
        //Create the GRID Partner Opporunity : This also sets Primary Contact and Role in the factory method; it also creates a Opporrunity Contact Role per the Process Builder
        Opportunity gridPartnerOppty = Test_COMM_Factory.createOpportunity('Grid Partner Oppty1', partnerAcc.Id, mapRTNameId.get(COMM_Constants.OPPTY_RT_TEGRA_EMBEDDED_PARTNER_OPPTY), COMM_Constants.OPPTY_STAGE_PROSPECTING, System.Today(), null, null);
        
        //Delete the contact roles
        list<OpportunityContactRole> lstOCR = [ Select ContactId, OpportunityId, Role, IsPrimary 
                                                        From OpportunityContactRole 
                                                        Where OpportunityId = :gridPartnerOppty.Id];
        
        delete lstOCR;
        
        Test.startTest();
            //set the Primary Contact and Role of the Opporrunity to null
            gridPartnerOppty.DR_Customer_Contact__c = null;
            gridPartnerOppty.Primary_Contact_Role__c = null;
            update gridPartnerOppty;
            
            
            PageReference pageRef = new PageReference('/apex/CRM_OPP_ContactRole_Banner');
            Test.setCurrentPageReference(pageRef);
            ApexPages.Standardcontroller stdCon = new Apexpages.Standardcontroller(gridPartnerOppty);
            
            CRM_OPP_ContactRole_Banner_cls extnCtlr = new CRM_OPP_ContactRole_Banner_cls(stdCon);
            system.debug('***showMessage : ' + extnCtlr.showMessage);
            system.assert(extnCtlr.showMessage == true);
            
        Test.stopTest();
    } 
}