force-app/main/default/objects/Contact/recordTypes/Partner.recordType-meta.xml
<RecordType>
    <fullName>Partner</fullName>
    <active>true</active>
    <label>Partner Contact</label>
</RecordType>

force-app/main/default/objects/OCR_Settings__c/OCR_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Opportunity Contact Role set up data</description>
    <label>CRM : OCR : Settings</label>
</CustomObject>

force-app/main/default/objects/OCR_Settings__c/fields/Job_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>Job_Batch_Size__c</fullName>
    <defaultValue>100</defaultValue>
    <description>Batch size (100 or 200) to avoid the governor limits</description>
    <inlineHelpText>Batch size (100 or 200) to avoid the governor limits</inlineHelpText>
    <label>Job Batch Size</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/DR_Customer_Contact__c.field-meta.xml
<CustomField>
    <fullName>DR_Customer_Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SDS-1740-Remove field filter from Primary Customer Contact field on the Opportunity such that someone can pick any contact from the db</description>
    <inlineHelpText>This field must contain the Primary Contact involved with this opportunity</inlineHelpText>
    <label>Primary Customer Contact</label>
    <lookupFilter>
        <active>false</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Contact.AccountId</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Opportunities (Customer Contact)</relationshipLabel>
    <relationshipName>Opportunities1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Primary_Contact_Role__c.field-meta.xml
<CustomField>
    <fullName>Primary_Contact_Role__c</fullName>
    <inlineHelpText>Select the role that best describes the Primary Customer Contact above.  This field must be populated when a Primary Customer Contact is identified.</inlineHelpText>
    <label>Primary Contact Role</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Sales Contact</fullName>
                <default>true</default>
                <label>Sales Contact</label>
            </value>
            <value>
                <fullName>Technical Contact</fullName>
            </value>
            <value>
                <fullName>Executive Sponsor</fullName>
            </value>
            <value>
                <fullName>Influencer/Buyer</fullName>
            </value>
            <value>
                <fullName>Solution Architect/IT</fullName>
            </value>
            <value>
                <fullName>Renewal Contact</fullName>
            </value>
            <value>
                <fullName>Other</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/Test_CRM_OCR_Sync_Batch.cls
/*
    2016.08.24 Test Class for batchable and schedulable class CRM_OCR_Sync_Batch
    Functionality to test: 
        The job needs to sync all Opportunity record's Primary Contact and Primary Customer Contact Role from Primary Opportunity Contact Role related list (only if there is a mismatch)
        It is configurable to only consider the records from a specific date (e.g., the Primary OCRs whose last modified date is 1/1/2010) and the batc size

 */
@isTest(SeeAllData=false)
private class Test_CRM_OCR_Sync_Batch {

    static testMethod void testChngOfOCRAndOpptyCustomPrimaryContactUpdateCRMOCRSyncBatch() {
        //setup Custom Settings CRM : OCR : Settings: It sets the Default Contact Role to "Sales Contact" along with msg, batc size etc
        //--------------------------------------------
        Test_COMM_Factory.set_CRM_OCR_Settings();
        //--------------------------------------------
        
        
        //get all Record Types
        list<string> lstSObjects = new list<string>{'Account', 'Contact', 'Opportunity'};
        map<String, Id> mapRTNameId = Test_COMM_Factory.getAllRTsByName(lstSObjects);
        
        //declare the Account, Contact
        Account partnerAcc;
        Contact partnerContact, newOpportunityPrimaryContact;
       
        
        //Create a Partner Account with Billing Country
        partnerAcc = Test_COMM_Factory.createAccountWithBillingAddress('PartnerAccount1', mapRTNameId.get(COMM_Constants.ACCOUNT_RT_NPN_ACCOUNT_REGISTRY), COMM_Constants.ADDRESS_STREET, COMM_Constants.ADDRESS_CITY, COMM_Constants.ADDRESS_STATE, COMM_Constants.ADDRESS_COUNTRY, COMM_Constants.ADDRESS_ZIP );
        system.debug('***partnerAcc: ' + partnerAcc);
        
        //Create a Partner Contact 
        partnerContact = Test_COMM_Factory.createContactWithMailingAddress('LPartner1', 'FParnter1', partnerAcc.Id, 'crmocrsyncschedlr1@nv.com', mapRTNameId.get(COMM_Constants.CONTACT_RT_PARTNER_CONTACT), COMM_Constants.ADDRESS_STREET, COMM_Constants.ADDRESS_CITY, COMM_Constants.ADDRESS_STATE, COMM_Constants.ADDRESS_COUNTRY, COMM_Constants.ADDRESS_ZIP );
        system.debug('***partnerAcc: ' + partnerContact);

        //Create the 100s GRID Partner Opporunity : This also sets Primary Contact and Role in the factory method; it also creates a Opporrunity Contact Role per the Process Builder
        integer iBatchSize = integer.valueOf(OCR_Settings__c.getOrgDefaults().Job_Batch_Size__c);
        list<Opportunity> lstOpps = Test_COMM_Factory.createMassOpportunityWithOCR(iBatchSize, partnerAcc.Id, mapRTNameId.get(COMM_Constants.OPPTY_RT_TEGRA_EMBEDDED_PARTNER_OPPTY), COMM_Constants.OPPTY_STAGE_PROSPECTING, System.Today(), null, null, partnerContact.Id, COMM_Constants.OCR_DEFAULT_SALES_CONTACT);
        
        
        //Check if it creates a Opportuninty Contact Role
        list<OpportunityContactRole> lstOCR = [ Select ContactId, OpportunityId, Role, IsPrimary 
                                                From OpportunityContactRole 
                                                Where OpportunityId = :lstOpps and IsPrimary = true];
        //system.debug('***lstOCR: ' + lstOCR);
        system.assert(lstOCR.size() == iBatchSize);
        system.assert(lstOCR[0].ContactId == partnerContact.Id);
        
        //set all Opportunity Contact Roles to non-primary
        for (OpportunityContactRole ocr : lstOCR){
            ocr.IsPrimary = false;
        }
        update lstOCR;
        
        //Create a new Partner Contact to be set from the Opportunity Contact Role related list record 
        newOpportunityPrimaryContact = Test_COMM_Factory.createContactWithMailingAddress('LNewPartner1', 'FNewParnter1', partnerAcc.Id, 'newprimarycontact@nv.com', mapRTNameId.get(COMM_Constants.CONTACT_RT_PARTNER_CONTACT),COMM_Constants.ADDRESS_STREET, COMM_Constants.ADDRESS_CITY, COMM_Constants.ADDRESS_STATE, COMM_Constants.ADDRESS_COUNTRY, COMM_Constants.ADDRESS_ZIP );
        
        //set the Contact Role with new contact as their Primary Contact
        //------------------------------------------------------------------------
        list<OpportunityContactRole> lstOCRNew = new list<OpportunityContactRole>();
        
        for(Opportunity opp : lstOpps){
            lstOCRNew.add(new OpportunityContactRole(OpportunityId = opp.Id, ContactId = newOpportunityPrimaryContact.Id, IsPrimary = true, Role = COMM_Constants.OCR_DEFAULT_SALES_CONTACT));
        }
        if(!lstOCRNew.isEmpty()){
            insert lstOCRNew;
        }
        //------------------------------------------------------------------------
        
        Test.startTest();
            //Execute the batch job
            CRM_OCR_Sync_Batch batchCls = new CRM_OCR_Sync_Batch();
            Database.executeBatch(batchCls);
            
            //Verify the job has not run yet
            lstOpps = [ Select DR_Customer_Contact__c, Primary_Contact_Role__c
                                            From Opportunity
                                            Where Id = :lstOpps];
            system.assert(lstOpps[0].DR_Customer_Contact__c != newOpportunityPrimaryContact.Id);
        Test.stopTest();
        
        //Now that the scheduled job has executed after Test.stopTest(),   fetch the Opportunity record and check if the Primary_Contact_Role__c has been updated
        lstOpps = [ Select DR_Customer_Contact__c, Primary_Contact_Role__c
                                            From Opportunity
                                            Where Id = :lstOpps];
        system.assert(lstOpps[0].DR_Customer_Contact__c == newOpportunityPrimaryContact.Id);
    }

}