force-app/main/default/objects/Contact/recordTypes/SalesContact.recordType-meta.xml
<RecordType>
    <fullName>SalesContact</fullName>
    <active>true</active>
    <label>Sales Contact</label>
</RecordType>

force-app/main/default/objects/DGX_Registry_Container__c/DGX_Registry_Container__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : Stores &quot;DGX Container Registry Administrator&quot; information from DGX Registration page submission</description>
    <label>NGC Registry</label>
    <nameField>
        <displayFormat>NGC-{000}</displayFormat>
        <label>NGC Registry Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NGC Registry</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/objects/DGX_Registry_Container__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>SDS-1415 : 
7.NGC Registry record should show a Related Account.
10.User should be able to see all related NGC Registry records under an Account</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>NGC_Registry</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DGX_Registry_Container__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipName>DGX_Registry_Containers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DGX_Registry_Container__c/fields/Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Entitlement__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Entitlement</label>
    <referenceTo>Entitlement</referenceTo>
    <relationshipLabel>NGC Registry</relationshipLabel>
    <relationshipName>NGC_Registry</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/DGX_Registry_Container__c/fields/Hardware_Serial_Number_PAK_Id__c.field-meta.xml
<CustomField>
    <fullName>Hardware_Serial_Number_PAK_Id__c</fullName>
    <description>SDS-1415 : User should be able to see all related NGC Registry records under an Account</description>
    <label>Hardware Serial Number / PAK Id</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Hardware_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Hardware_Serial_Number__c</fullName>
    <label>Hardware Serial Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/PAK_ID__c.field-meta.xml
<CustomField>
    <fullName>PAK_ID__c</fullName>
    <label>PAK ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement__c/Entitlement__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : Contains Entitlement Information relevant to the Customer. Used to display Entitlement Information in the Communities. Will be used in Community Search as well.</description>
    <label>Entitlement</label>
    <nameField>
        <label>Entitlement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entitlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Entitlement__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Entitlements</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement__c/fields/Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Entitlement__c</fullName>
    <label>Entitlement</label>
    <referenceTo>Entitlement</referenceTo>
    <relationshipLabel>Entitlements</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Entitlement__c/fields/Hardware_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Hardware_Serial_Number__c</fullName>
    <formula>Entitlement__r.Hardware_Serial_Number__c</formula>
    <label>Hardware Serial Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement__c/fields/PAK_ID__c.field-meta.xml
<CustomField>
    <fullName>PAK_ID__c</fullName>
    <formula>Entitlement__r.PAK_ID__c</formula>
    <label>PAK ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NGC_Registry_Helper.cls
/*----------------------------------------------------------------------------------------------------------------------------------------------------
Class Name : NGC_Registry_Helper. Related to object DGX_Registry_Container__c
Description : This class contains all the methods that will operate on DGX_Registry_Container__c () NGC_Registry

Date        Version    Modified by        Change details
-------     -------    -------------      --------------------------------------------------------
21-5-2019     1.0      Nilesh Adkar        SDS-1415 : Helper methods for trigger to associate Contact and Account to NGC Registry.
  
------------------------------------------------------------------------------------------------------------------------------------------------------
*/

public class NGC_Registry_Helper{

// SDS-1415
public static void associateContactAndAccountWithNGC_Registry(List<DGX_Registry_Container__c> lstNewReg){
    set<string> setEmails = new set<string>();
    set<string> setSerialNo = new set<string>();
    for(DGX_Registry_Container__c tmp : lstNewReg){
        if(tmp.Email_Address__c !=null)  
            setEmails.add(tmp.Email_Address__c);
        if(tmp.Hardware_Serial_Number_PAK_Id__c !=null)
            setSerialNo.add(tmp.Hardware_Serial_Number_PAK_Id__c);
    }
    
    List<Entitlement> lstEnt = [select AccountId, Hardware_Serial_Number__c,PAK_ID__c from Entitlement where Hardware_Serial_Number__c in :setSerialNo or PAK_ID__c in :setSerialNo ORDER BY CreatedDate desc];
    Map<string, String> mapSerialAccount = new Map<string, String>(); 
    Map<string, String> mapSerialEntitlement = new Map<string, String>(); 
    for(Entitlement tmpEnt : lstEnt){
        if(tmpEnt.Hardware_Serial_Number__c !=null){
            mapSerialAccount.put(tmpEnt.Hardware_Serial_Number__c,tmpEnt.AccountId);
            if(mapSerialEntitlement!=null && !mapSerialEntitlement.containsKey(tmpEnt.Hardware_Serial_Number__c))
                mapSerialEntitlement.put(tmpEnt.Hardware_Serial_Number__c,tmpEnt.id);
            system.debug('***' + mapSerialEntitlement);
        }
        if(tmpEnt.PAK_ID__c !=null){
            mapSerialAccount.put(tmpEnt.PAK_ID__c,tmpEnt.AccountId);
            if(mapSerialEntitlement!=null && !mapSerialEntitlement.containsKey(tmpEnt.PAK_ID__c))
                mapSerialEntitlement.put(tmpEnt.PAK_ID__c,tmpEnt.id);
            system.debug('***' + mapSerialEntitlement);
        }
    }

    List<Contact> lstContacts = [select id, email,AccountId from Contact where email in :setEmails order by lastmodifieddate desc];
    Id ContactRecordTypeId = [SELECT DeveloperName,Id,SobjectType FROM RecordType WHERE SobjectType = 'Contact' AND DeveloperName = 'SalesContact' limit 1].id;
    Map<string, Contact> mapEmailContact = new Map<string, Contact>();
    for(Contact tmpCon : lstContacts){
        if(mapEmailContact !=null && tmpCon.email !=null && !mapEmailContact.containsKey(tmpCon.email))
            mapEmailContact.put(tmpCon.email,tmpCon );
    }
    
    List<Contact> lstNewContacts = new List<Contact>();
    List<DGX_Registry_Container__c> lstNewRegNoContact = new List<DGX_Registry_Container__c>();
    
    Boolean isContactAssociated = false;
    system.debug('***' + mapSerialEntitlement);
    for(DGX_Registry_Container__c tmpReg : lstNewReg){
        if(tmpReg.Hardware_Serial_Number_PAK_Id__c !=null && mapSerialEntitlement!=null && mapSerialEntitlement.get(tmpReg.Hardware_Serial_Number_PAK_Id__c)!=null){
            tmpReg.Entitlement__c = mapSerialEntitlement.get(tmpReg.Hardware_Serial_Number_PAK_Id__c);
        }
        if(mapEmailContact!=null && tmpReg.Email_Address__c!=null && mapEmailContact.get(tmpReg.Email_Address__c)!=null){
            if(tmpReg.Contact__c == null){
                tmpReg.Contact__c = mapEmailContact.get(tmpReg.Email_Address__c).id;
                isContactAssociated = true;
            }    
            if(tmpReg.Account__c == null && mapEmailContact.get(tmpReg.Email_Address__c).AccountId !=null  && tmpReg.Hardware_Serial_Number_PAK_Id__c ==null )
                tmpReg.Account__c = mapEmailContact.get(tmpReg.Email_Address__c).AccountId;
            else if(tmpReg.Account__c == null && tmpReg.Hardware_Serial_Number_PAK_Id__c !=null && mapSerialAccount!=null && mapSerialAccount.get(tmpReg.Hardware_Serial_Number_PAK_Id__c)!=null)
                tmpReg.Account__c = mapSerialAccount.get(tmpReg.Hardware_Serial_Number_PAK_Id__c);                
        }
        else if(isContactAssociated == false && tmpReg.Contact__c == null && !Trigger.isUpdate){
            Contact con = new Contact();
            con.email = tmpReg.Email_Address__c;
            con.Phone= tmpReg.Phone_Number__c;
            con.firstName = tmpReg.FirstName__c;
            con.lastName = tmpReg.Last_Name__c;
            con.RecordTypeId = ContactRecordTypeId;
            if(tmpReg.Account__c == null && tmpReg.Hardware_Serial_Number_PAK_Id__c !=null && mapSerialAccount!=null && mapSerialAccount.get(tmpReg.Hardware_Serial_Number_PAK_Id__c)!=null)
                con.accountId = mapSerialAccount.get(tmpReg.Hardware_Serial_Number_PAK_Id__c);
            lstNewContacts.add(con);
            lstNewRegNoContact.add(tmpReg);
        }
    }
    insert lstNewContacts;
    for(Contact tmpCon : lstNewContacts){
        mapEmailContact.put(tmpCon.email,tmpCon );
    }
    for(DGX_Registry_Container__c tmpReg : lstNewRegNoContact){
        if(mapEmailContact!=null && tmpReg.Email_Address__c!=null && mapEmailContact.get(tmpReg.Email_Address__c)!=null){
            tmpReg.Contact__c = mapEmailContact.get(tmpReg.Email_Address__c).id;
            tmpReg.Account__c = mapEmailContact.get(tmpReg.Email_Address__c).AccountId;
        }
    }
    
}

}