force-app/main/default/objects/Entitlement/fields/Entitlement_Status__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Status__c</fullName>
    <formula>IF ( Text(Order_Type__c) = &apos;ZMRS&apos;  || Text(Order_Type__c) = &apos;ZKB&apos; , &quot;MRS&quot;,
	IF ( ISBLANK(SAP_Order__c) &amp;&amp; ISBLANK(Subscription__c), &quot;Removed&quot;,
		IF ( TODAY() &gt;= StartDate &amp;&amp; TODAY() &lt;= EndDate, &quot;Active&quot;,
			IF(StartDate &gt; TODAY(), &quot;Inactive&quot;, 
						&quot;Expired&quot;
			)
		)
	)
)</formula>
    <label>Entitlement Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Environment_Profile__c.field-meta.xml
<CustomField>
    <fullName>Environment_Profile__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Environment Profile</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.AccountId</field>
            <operation>equals</operation>
            <valueField>Environment_Profile__c.Account__c</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Environment_Profile__c</referenceTo>
    <relationshipLabel>Entitlements</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Environment_Profile_Name__c.field-meta.xml
<CustomField>
    <fullName>Environment_Profile_Name__c</fullName>
    <formula>Environment_Profile__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Environment Profile Name</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Environment_Profile__c/Environment_Profile__c.object-meta.xml
<CustomObject>
    <description>SDS-995:Service Cloud: Track Customer Environment Profiles
As a Service Cloud User, I should be able to track customer-specific details for vGPU or DGX products owned by the Customer</description>
    <label>Environment Profile</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Environment Profiles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Environment_Profile__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Environment Profiles</relationshipLabel>
    <relationshipName>Environment_Profiles</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/EnvironmentProfileHelper.cls
/*
Class name : EnvironmentProfileHelper 
Description : This class provides Helper Methods for Environment Profile Object. Some methods are called 
from Lightning component Link Entitlements to Environment Profile.
Vesrion    Modified Date    Modified By          Description
-----------------------------------------------------------------------------------------------------------------------------------
1.0        30-Jan-20        Nilesh Adkar        Created. SDS-1982 Service Cloud: Link Customer Entitlements to Environment Profile

*/
public class EnvironmentProfileHelper {

// Displays the list of entitlements on select entitlement lightning action (Link Entitlements)
    @AuraEnabled
    public static List < Entitlement > getEntitlementList(Id envProfileId) {
        Id accId = [select Account__c from Environment_Profile__c where id =: envProfileId].Account__c;
        List < Entitlement > lstEntitlements = [select id, name, Entitlement_status__c, environment_profile__c, Environment_Profile_Name__c from Entitlement where AccountId =: accId];
        return lstEntitlements;
    }
    
// Gets selected Entitlements and associates Env profile to each.
    @AuraEnabled
    public static void linkEnvironmentProfileToEntitlements(Id envProfileId, List < Entitlement > lstEntitlements) {
        System.debug('**' + envProfileId);
        System.debug('**--Entitlement--' + lstEntitlements);
        for (Entitlement tmpEntitlements: lstEntitlements) {
            tmpEntitlements.environment_profile__c = envProfileId;
        }

        update lstEntitlements;
    }
}