force-app/main/default/objects/Entitlement/fields/Hardware_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Hardware_Serial_Number__c</fullName>
    <label>Hardware Serial Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZOR</fullName>
            </value>
            <value>
                <fullName>ZSO</fullName>
            </value>
            <value>
                <fullName>ZMRS</fullName>
            </value>
            <value>
                <fullName>ZRMA</fullName>
            </value>
            <value>
                <fullName>ZDO</fullName>
            </value>
            <value>
                <fullName>ZKB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <description>Created for backend purposes only.</description>
    <label>Product</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Renewed_PAK_ID__c.field-meta.xml
<CustomField>
    <fullName>Renewed_PAK_ID__c</fullName>
    <description>Rename this to Renewed PAK ID if CPQ decides to use both PAK ID and Renewed PAK ID in future. Right now, CPQ is not populating any values in PAK ID.</description>
    <label>Renewed PAK ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/SAP_Order__c.field-meta.xml
<CustomField>
    <fullName>SAP_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SAP Order</label>
    <referenceTo>SAP_Order__c</referenceTo>
    <relationshipLabel>Entitlements</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Service_Product__c.field-meta.xml
<CustomField>
    <fullName>Service_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This field is created to store Product lookup copied from Subscription or manually entered for MRS Products.</description>
    <label>Service Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Entitlements (Service Product)</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement__c/Entitlement__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : Contains Entitlement Information relevant to the Customer. Used to display Entitlement Information in the Communities. Will be used in Community Search as well.</description>
    <label>Entitlement</label>
    <nameField>
        <label>Entitlement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entitlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Entitlement__c/fields/End_Date__c.field-meta.xml
<CustomField>
    <fullName>End_Date__c</fullName>
    <formula>Entitlement__r.EndDate</formula>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Entitlement__c/fields/Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Entitlement__c</fullName>
    <label>Entitlement</label>
    <referenceTo>Entitlement</referenceTo>
    <relationshipLabel>Entitlements</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Entitlement__c/fields/Hardware_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Hardware_Serial_Number__c</fullName>
    <formula>Entitlement__r.Hardware_Serial_Number__c</formula>
    <label>Hardware Serial Number</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <formula>TEXT(Entitlement__r.Order_Type__c)</formula>
    <label>Order Type</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>Entitlement__r.Renewal_Quantity__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Entitlement__c/fields/Renewed_PAK_ID__c.field-meta.xml
<CustomField>
    <fullName>Renewed_PAK_ID__c</fullName>
    <description>Rename this to Renewed PAK ID in future.</description>
    <formula>Entitlement__r.Renewed_PAK_ID__c</formula>
    <label>Renewed PAK ID</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement__c/fields/Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Start_Date__c</fullName>
    <formula>Entitlement__r.StartDate</formula>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/SAP_Order__c.object-meta.xml
<CustomObject>
    <description>CPQ : Captures SAP Orders from SAP/EMS through integration</description>
    <label>SAP Order</label>
    <nameField>
        <label>SAP Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP_Order__c/fields/Hardware_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Hardware_Serial_Number__c</fullName>
    <label>Hardware Serial Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <description>ZOR - Standard, ZSO - Sample, ZMRS - MRS Internal, ZRMA - Return</description>
    <inlineHelpText>ZOR - Standard, ZSO - Sample, ZMRS - MRS Internal, ZRMA - Return</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZOR</fullName>
            </value>
            <value>
                <fullName>ZSO</fullName>
            </value>
            <value>
                <fullName>ZMRS</fullName>
            </value>
            <value>
                <fullName>ZRMA</fullName>
            </value>
            <value>
                <fullName>ZDO</fullName>
            </value>
            <value>
                <fullName>ZKB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>SAP Orders</relationshipLabel>
    <relationshipName>SAP_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/Renewed_PAK_ID__c.field-meta.xml
<CustomField>
    <fullName>Renewed_PAK_ID__c</fullName>
    <label>Renewed PAK ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/SAP_PAK_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_PAK_ID__c</fullName>
    <label>SAP PAK ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/SAP_Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sales_Order_Number__c</fullName>
    <label>SAP Sales Order Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/SFDC_Account__c.field-meta.xml
<CustomField>
    <fullName>SFDC_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SFDC Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SAP Orders</relationshipLabel>
    <relationshipName>SAP_Orders</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/Sold_To_Partner_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Partner_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To Partner Lookup</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SAP Orders (Sold To Partner Lookup)</relationshipLabel>
    <relationshipName>SAP_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/ESP_SyncSAPOrderToEntitlement_BAT_SCH.cls
public with sharing class ESP_SyncSAPOrderToEntitlement_BAT_SCH implements Schedulable{
	
	public integer BATCH_SIZE;
	public DateTime LookBackFromDt;
	/*
	private DateTime LookBackFromDt;
    private DateTime LookBackToDt;
    public ESP_SyncSAPOrderToEntitlement_BAT_SCH() {
    	system.debug('20191213 1.1');
        LookBackFromDt = DateTime.Now().addDays(-1);
        LookBackToDt   = DateTime.Now();
    }
    public ESP_SyncSAPOrderToEntitlement_BAT_SCH(DateTime fromDate, DateTime toDate) {
    	system.debug('20191213 1.3');
        LookBackToDt   = (toDate != null) ? toDate : DateTime.Now();
        LookBackFromDt = (fromDate != null) ? fromDate : LookBackToDt.addDays(-1);
    }*/
    
	public void execute(SchedulableContext SC) {
		ESP_SyncSAPOrderToEntitlement_BAT bat = new ESP_SyncSAPOrderToEntitlement_BAT();
		bat.LookBackFromDt = LookBackFromDt;
		system.debug('LookBackFromDt: '+ LookBackFromDt);
		Id batchJobId = Database.executeBatch(bat,BATCH_SIZE);
		
		///system.debug('LookBackFromDt: '+ LookBackFromDt + ' LookBackToDt: '+LookBackToDt);
		///Id batchJobId = Database.executeBatch(new ESP_SyncSAPOrderToEntitlement_BAT(LookBackFromDt, LookBackToDt));
		/*String Query = 'SELECT Name,SFDC_Account__c, Start_Date__c,End_Date__c,Product__r.Description,Quantity__c,Hardware_Serial_Number__c,SAP_PAK_ID__c,Product__c,Renewed_PAK_ID__c,SAP_Sales_Order_Number__c,ID, Sold_To_Partner_Lookup__c, Order_Type__c, (Select Id From Entitlements__r)'
		        			+ ' FROM SAP_Order__c'
		        			+ ' where Order_Type__c in  (\'ZOR\', \'ZSO\', \'ZDO\', \'ZMRS\' )'
		        			;
		Id batchJobId = Database.executeBatch(new ESP_SyncSAPOrderToEntitlement_BAT(Query),10);
		*/
		
		system.debug('batchJobId: '+ batchJobId);
		system.debug('Aborting the Job, Job ID: '+ sc.getTriggerId());
		system.abortJob(sc.getTriggerId());
	}
}