force-app/main/default/objects/Entitlement/fields/Hardware_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Hardware_Serial_Number__c</fullName>
    <label>Hardware Serial Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Entitlements</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/ESP_CreateEntFromSubscr_Settings__c/ESP_CreateEntFromSubscr_Settings__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>Contains setting related to the batch job ESP_CreateEntFromSubscr_Sch</description>
    <label>ESP : CreateEntFromSubscr : Settings</label>
</CustomObject>

force-app/main/default/objects/ESP_CreateEntFromSubscr_Settings__c/fields/BATCH_SIZE__c.field-meta.xml
<CustomField>
    <fullName>BATCH_SIZE__c</fullName>
    <defaultValue>25</defaultValue>
    <description>Number of records per batch to be processed in batch job</description>
    <inlineHelpText>Number of records per batch to be processed in batch job</inlineHelpText>
    <label>BATCH_SIZE</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ESP_CreateEntFromSubscr_Settings__c/fields/ENABLE_SCHDULED_JOB__c.field-meta.xml
<CustomField>
    <fullName>ENABLE_SCHDULED_JOB__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If set to false, the batch job will be terminated, but you need to run it manually to start again.
ESP_CreateEntFromSubscr_Sch p = new ESP_CreateEntFromSubscr_Sch();
DateTime currDT = DateTime.now().addMinutes(2);
integer sec = currDT.second();
integer min = currDT.minute();
String sch = sec + &apos; &apos; + min + &apos; &apos; + &apos;* ? * *&apos;; //0 5 * * * ?
system.debug(&apos;sch: &apos; + sch);
system.schedule(&apos;Exec of ESP_CreateEntFromSubscr_Sch&apos;, sch, p);</description>
    <inlineHelpText>If set to false, the batch job will terminated, but you need to run it manually to start again. See the fields description field how to start the batch job.</inlineHelpText>
    <label>ENABLE_SCHDULED_JOB</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/ESP_CreateEntFromSubscr_Settings__c/fields/LKBK_TIME__c.field-meta.xml
<CustomField>
    <fullName>LKBK_TIME__c</fullName>
    <defaultValue>30</defaultValue>
    <description>Lookback time used in LastModifiedDate &gt; Now - LookbackTime</description>
    <inlineHelpText>Lookback time used in LastModifiedDate &gt; Now - LookbackTime</inlineHelpText>
    <label>LKBK_TIME</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/ESP_CreateEntFromSubscr_Settings__c/fields/RECUR__c.field-meta.xml
<CustomField>
    <fullName>RECUR__c</fullName>
    <defaultValue>5</defaultValue>
    <description>Recurring time - the next time the job will run (Now + Recurring Time) in minutes</description>
    <inlineHelpText>Recurring time - the next time the job will run (Now + Recurring Time) in minutes</inlineHelpText>
    <label>RECUR</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/Test_ESP_CreateEntFromSubscr_Sch.cls
/**
    2019.07.03 - PJENA - Test class for ESP_CreateEntFromSubscr_Sch that created/sync Entitlements from SBQQ_Subscription__c
    Note: Run it with svcDeploy user as it has access to CPQ objects
 */
 
 
@isTest(SeeAllData=false)
private class Test_ESP_CreateEntFromSubscr_Sch {
    
    public static final string accName = 'TESTCUSTOMER20190703001';
    
    static testMethod void createEntitlement() {
        Test.startTest();
            string CRON_EXP = '0 1 * ? * *';
                
             // Schedule the test job
            String jobId = System.schedule('Test_ESP_CreateEntFromSubscr_Sch',  CRON_EXP,  new ESP_CreateEntFromSubscr_Sch());
    
             // Get the information from the CronTrigger API object
            CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, NextFireTime FROM CronTrigger WHERE id = :jobId];
    
            // Verify the expressions are the same
            System.assertEquals(CRON_EXP, ct.CronExpression);
    
            // Verify the job has not run
            System.assertEquals(0, ct.TimesTriggered);
        Test.stopTest();
    }
    
    
    @testsetup
    public static void setup(){
        
        //set the custom settings values
        ESP_CreateEntFromSubscr_Settings__c oCSSettings = new ESP_CreateEntFromSubscr_Settings__c();
        oCSSettings.Name = 'ESP : CreateEntFromSubscr : Settings';
        oCSSettings.BATCH_SIZE__c = 10;
        oCSSettings.ENABLE_SCHDULED_JOB__c = true;
        oCSSettings.LKBK_TIME__c = 15;
        oCSSettings.RECUR__c = 10;
        insert oCSSettings;

        //Account creation
        Account acc = Test_COMM_Factory.getAccount(accName);
        RecordType rt = [SELECT Id FROM RecordType WHERE SObjectType = :COMM_Constants.SOBJECT_ACCOUNT AND  Name = :COMM_Constants.ACCOUNT_RT_NEW_CUSTOMER];
        acc.RecordTypeId = rt.Id;
        insert acc;
                
        //Contract creation
        Contract contract = Test_COMM_Factory.getContract(acc.Id);
        insert contract;
        
        //Activate contract
        contract.Status = 'Activated';
        update contract;
        
        //Product creation
        Product2 product = Test_COMM_Factory.getProduct('Test Product');
        insert product;
        
        //Subscription creation
        SBQQ__Subscription__c subscription1 = Test_COMM_Factory.getSubscription(acc.Id, product.Id, contract.Id);
        subscription1.Hardware_Serial_Number__c = 'Serial111';
        insert subscription1;
        
        //create subscription and entitlement manually
        SBQQ__Subscription__c subscription2 = Test_COMM_Factory.getSubscription(acc.Id, product.Id, contract.Id);
        subscription2.Hardware_Serial_Number__c = 'Serial111';
        insert subscription2;
        
        list<Entitlement> lstEnt2 = [Select Id From Entitlement where Subscription__c = :subscription2.Id];
        if (lstEnt2 == null || lstEnt2.isEmpty()){
            Entitlement ent2 = new Entitlement(name='TestEnt', AccountId = acc.Id, Subscription__c =  subscription2.Id, Hardware_Serial_Number__c=subscription2.Hardware_Serial_Number__c );
            insert ent2;
        }
        
    }
}