force-app/main/default/objects/Entitlement/fields/Hardware_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Hardware_Serial_Number__c</fullName>
    <label>Hardware Serial Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/MRS_No_Subscription__c.field-meta.xml
<CustomField>
    <fullName>MRS_No_Subscription__c</fullName>
    <defaultValue>false</defaultValue>
    <description>MRS (Saturn V) field</description>
    <label>MRS (No Subscription)</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/NVIDIA_Sales_Order__c.field-meta.xml
<CustomField>
    <fullName>NVIDIA_Sales_Order__c</fullName>
    <label>NVIDIA Sales Order</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ZOR</fullName>
            </value>
            <value>
                <fullName>ZSO</fullName>
            </value>
            <value>
                <fullName>ZMRS</fullName>
            </value>
            <value>
                <fullName>ZRMA</fullName>
            </value>
            <value>
                <fullName>ZDO</fullName>
            </value>
            <value>
                <fullName>ZKB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Entitlement/fields/PAK_ID__c.field-meta.xml
<CustomField>
    <fullName>PAK_ID__c</fullName>
    <label>PAK ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Partner__c.field-meta.xml
<CustomField>
    <fullName>Partner__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Entitlements</relationshipLabel>
    <relationshipName>Entitlements1</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/SAP_Order__c.field-meta.xml
<CustomField>
    <fullName>SAP_Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>SAP Order</label>
    <referenceTo>SAP_Order__c</referenceTo>
    <relationshipLabel>Entitlements</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Entitlement/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Entitlements</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NV_Log__c/NV_Log__c.object-meta.xml
<CustomObject>
    <description>Global Logging Object</description>
    <label>NV Log</label>
    <nameField>
        <displayFormat>Log-{0000000}</displayFormat>
        <label>Nvidia Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>NV Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/NV_Log__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>API_Transaction_Loggers</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/NV_Log__c/fields/Error_Description__c.field-meta.xml
<CustomField>
    <fullName>Error_Description__c</fullName>
    <label>Error Description</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NV_Log__c/fields/Functionality_Name__c.field-meta.xml
<CustomField>
    <fullName>Functionality_Name__c</fullName>
    <label>Functionality Name</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Service: SAP RMA Callout</fullName>
            </value>
            <value>
                <fullName>IDM: User Sync</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NV_Log__c/fields/Log_Type__c.field-meta.xml
<CustomField>
    <fullName>Log_Type__c</fullName>
    <label>Log Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error: Batch</fullName>
            </value>
            <value>
                <fullName>Error: Trigger</fullName>
            </value>
            <value>
                <fullName>Error: Callout</fullName>
            </value>
            <value>
                <fullName>Error: Other</fullName>
            </value>
            <value>
                <fullName>Error: Future Method</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/NV_Log__c/fields/Record_ID__c.field-meta.xml
<CustomField>
    <fullName>Record_ID__c</fullName>
    <inlineHelpText>Record Id or list of record Ids or Batch Job Id etc which can help to locate the exact record.</inlineHelpText>
    <label>Record Id(s)</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/NV_Log__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAP_Order__c/SAP_Order__c.object-meta.xml
<CustomObject>
    <description>CPQ : Captures SAP Orders from SAP/EMS through integration</description>
    <label>SAP Order</label>
    <nameField>
        <label>SAP Order Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SAP Orders</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/SAP_Order__c/fields/Entitlement_Type__c.field-meta.xml
<CustomField>
    <fullName>Entitlement_Type__c</fullName>
    <label>Entitlement Type</label>
    <length>2</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/Hardware_Serial_Number__c.field-meta.xml
<CustomField>
    <fullName>Hardware_Serial_Number__c</fullName>
    <label>Hardware Serial Number</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/Order_Type__c.field-meta.xml
<CustomField>
    <fullName>Order_Type__c</fullName>
    <description>ZOR - Standard, ZSO - Sample, ZMRS - MRS Internal, ZRMA - Return</description>
    <inlineHelpText>ZOR - Standard, ZSO - Sample, ZMRS - MRS Internal, ZRMA - Return</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ZOR</fullName>
            </value>
            <value>
                <fullName>ZSO</fullName>
            </value>
            <value>
                <fullName>ZMRS</fullName>
            </value>
            <value>
                <fullName>ZRMA</fullName>
            </value>
            <value>
                <fullName>ZDO</fullName>
            </value>
            <value>
                <fullName>ZKB</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/SAP_PAK_ID__c.field-meta.xml
<CustomField>
    <fullName>SAP_PAK_ID__c</fullName>
    <label>SAP PAK ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/SAP_Sales_Order_Number__c.field-meta.xml
<CustomField>
    <fullName>SAP_Sales_Order_Number__c</fullName>
    <label>SAP Sales Order Number</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/Sold_To_Partner_Lookup__c.field-meta.xml
<CustomField>
    <fullName>Sold_To_Partner_Lookup__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Sold To Partner Lookup</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>SAP Orders (Sold To Partner Lookup)</relationshipLabel>
    <relationshipName>SAP_Orders2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/SAP_Order__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Processed is for Quote Line/Renewals to avoid record locks, Synced means record has been successfully completed, Error is error</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Processed</fullName>
            </value>
            <value>
                <fullName>Synced</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ESP_LinkSAPOrderToEntitlements_BAT.cls
/* 12/12/2019: Akhilesh: 	Created. This class/batch job is responsible to link SAP Order
				to Entitlements.	
   01/10/2020: Akhilesh:	Added logic to filter Perpetual Entitlements.	
*/
public with sharing class ESP_LinkSAPOrderToEntitlements_BAT implements database.Batchable<sObject>, Database.RaisesPlatformEvents {
    
    private string query = 'select Id, MRS_No_Subscription__c, Subscription__c, Subscription__r.SAP_Order__c'
    						+ ', Hardware_Serial_Number__c, PAK_ID__c, Subscription__r.SAP_Order__r.SAP_Sales_Order_Number__c'
    						+ ', Subscription__r.SAP_Order__r.Sold_To_Partner_Lookup__c, Subscription__r.SAP_Order__r.Order_Type__c'
    						+ ' from Entitlement where SAP_Order__c = Null';
    
    public ESP_LinkSAPOrderToEntitlements_BAT() {}
    public ESP_LinkSAPOrderToEntitlements_BAT(String strQuery) {
        system.debug('20191213 1');
        query = strQuery;
    }
    
    public Database.QueryLocator start(Database.BatchableContext bc) {
        system.debug('20191213 2');
        return Database.getQueryLocator(query);
    }
    
    public void execute(Database.BatchableContext bc, list<sObject> scope) {
        system.debug(scope);
        system.debug('20191213 3');
        updateSAPOrderOnEntitlements(scope);
    }
    
    public void finish(Database.batchableContext bc) {
        system.debug('20191213 5');
    }
    
    public void updateSAPOrderOnEntitlements(list<sObject> scope) {
        //try {
            system.debug('20191213 4');
            list<Entitlement> entToUpdate = new list<Entitlement>();
            list<Entitlement> mrsEntsToUpdate = new list<Entitlement>();
            //set<string> sNosToSearch = new set<string>();
            set<string> PAKIDsToSearch = new set<string>();
            for(Entitlement ent : (list<Entitlement>)scope) {
                system.debug('20191213 4.1');
                if(ent.Subscription__c != null && ent.Subscription__r.SAP_Order__c != null) {
                    system.debug('20191213 4.1.1');
                    ent.SAP_Order__c 			= ent.Subscription__r.SAP_Order__c;
                    ent.NVIDIA_Sales_Order__c	= ent.Subscription__r.SAP_Order__r.SAP_Sales_Order_Number__c;
                    ent.Partner__c  			= ent.Subscription__r.SAP_Order__r.Sold_To_Partner_Lookup__c;
                    //if(ent.MRS_No_Subscription__c)
                    //	ent.Order_Type__c 		= 'ZMRS';
                    //else
                    	ent.Order_Type__c		= ent.Subscription__r.SAP_Order__r.Order_Type__c;
                    entToUpdate.add(ent);
                } else {
                    system.debug('20191213 4.1.2');
                    /*if(!string.isEmpty(ent.Hardware_Serial_Number__c)) {
                        system.debug('20191213 4.1.2.1');
                        sNosToSearch.add(ent.Hardware_Serial_Number__c);
                        mrsEntsToUpdate.add(ent);
                    }*/
                    if(!string.isEmpty(ent.PAK_ID__c)) {
                        system.debug('20191213 4.1.2.1');
                        PAKIDsToSearch.add(ent.PAK_ID__c);
                        mrsEntsToUpdate.add(ent);
                    }
                }
            }
            
            if(!mrsEntsToUpdate.isEmpty()) {
                system.debug('20191213 4.2');
                //Find SAP_Order by sNos.
                list<SAP_Order__c> sapOrdersList = [select Id, Hardware_Serial_Number__c, SAP_PAK_ID__c, SAP_Sales_Order_Number__c, Sold_To_Partner_Lookup__c, Order_Type__c 
                									from SAP_Order__c 
                									//where Hardware_Serial_Number__c in: sNosToSearch 
                									where SAP_PAK_ID__c in: PAKIDsToSearch
                										and Entitlement_Type__c != 'PL'
                									];
                
                //Update MRS Entitlements with SAP_Order_ID
                if(!sapOrdersList.isEmpty()) {
                    system.debug('20191213 4.2.1');
                    for(Entitlement ent : mrsEntsToUpdate) {
                        for(SAP_Order__c sapOrder : sapOrdersList) {
                            system.debug('20191213 4.2.2');
                            if(sapOrder.SAP_PAK_ID__c == ent.PAK_ID__c) {
                                ent.SAP_Order__c 			= sapOrder.Id;
                                ent.NVIDIA_Sales_Order__c	= sapOrder.SAP_Sales_Order_Number__c;
                                ent.Partner__c  			= sapOrder.Sold_To_Partner_Lookup__c;
                                if(ent.MRS_No_Subscription__c)
                                	ent.Order_Type__c = 'ZMRS';
                                else
                                	ent.Order_Type__c			= sapOrder.Order_Type__c;
                            }
                        }
                    }
                    
                    update mrsEntsToUpdate;
                }
            }
            
            system.debug('20191213 4.3');
            if(!entToUpdate.isEmpty()) 
                update entToUpdate;
                
            //Integer i = 1/0;
        /*} catch (Exception ex) {
            system.debug('20191213 6');
            //for(Entitlement ent : (list<Entitlement>)scope) {
            map<Id, Entitlement> entitlementsMap = new map<Id, Entitlement>();
            entitlementsMap.putAll((list<Entitlement>)scope);
            NV_Log__c nvlog = new NV_Log__c(
                                    //Account__c='',
                                    Component_Name__c       = 'ESP_LinkSAPOrderToEntitlements_BAT',
                                    Error_Description__c    = ''+ex.getStackTraceString(),
                                    Error_Message__c        = ''+ex.getMessage(),
                                    Functionality_Name__c   = 'Link SAP Order to Entitlement Job',
                                    Log_Type__c             = 'Error: Batch',
                                    Method_Name__c          = 'LinkSAPOrderOnEntitlements',
                                    Record_ID__c            = ''+entitlementsMap.keySet(),
                                    Status__c               = 'Exception'
                                );                                      
            insert nvlog;
            //}
        } */
    }
}