force-app/main/default/objects/Entitlement/fields/Renew_Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Renew_Entitlement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renew Entitlement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Entitlement__c/Entitlement__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : Contains Entitlement Information relevant to the Customer. Used to display Entitlement Information in the Communities. Will be used in Community Search as well.</description>
    <label>Entitlement</label>
    <nameField>
        <label>Entitlement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entitlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Entitlement__c/fields/Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Entitlement__c</fullName>
    <label>Entitlement</label>
    <referenceTo>Entitlement</referenceTo>
    <relationshipLabel>Entitlements</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RenewEntitlementHelper.cls
public with sharing class RenewEntitlementHelper {
    /*
     * Renew entitlement for given entitlement Id
     */
    @AuraEnabled
    public static String RenewEntitlement(String Id){
        system.debug('id-->'+id);
        //Fetch Parent entitlement
        Entitlement__c ent = [SELECT Id, Entitlement__c FROM Entitlement__c WHERE Id =:id];
        if(ent != null && ent.Entitlement__c !=null){
            //Update Parent entitlement renewal flag
            Entitlement parentEnt = new Entitlement(id =ent.Entitlement__c, Renew_Entitlement__c = true);
            update parentEnt;    
        }else{
            return 'ERROR';
        }
        return 'SUCCESS';
    }
}