force-app/main/default/objects/Entitlement/fields/Renew_Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Renew_Entitlement__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Renew Entitlement</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Entitlement__c/Entitlement__c.object-meta.xml
<CustomObject>
    <description>Service Cloud : Contains Entitlement Information relevant to the Customer. Used to display Entitlement Information in the Communities. Will be used in Community Search as well.</description>
    <label>Entitlement</label>
    <nameField>
        <label>Entitlement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Entitlements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Entitlement__c/fields/Entitlement__c.field-meta.xml
<CustomField>
    <fullName>Entitlement__c</fullName>
    <label>Entitlement</label>
    <referenceTo>Entitlement</referenceTo>
    <relationshipLabel>Entitlements</relationshipLabel>
    <relationshipName>Entitlements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RenewEntitlementHelper_test.cls
/*
* Akhilesh Gupta    | 1.0        | 11/18/2019       | Created test class for RenewEntitlementHelper
*/
@isTest
public class RenewEntitlementHelper_test {
    final static String NAME = 'TestRenewEntitlementHelper_test';
    
    @testsetup
    public static void setup(){}
    
    @isTest
    public static void TestRenewEntitlement(){
        
        Test.startTest();
            //Account creation
            Account acc = Test_COMM_Factory.getAccount(NAME);
            insert acc;            
            //Entitlement creation
            Entitlement ent  = Test_COMM_Factory.getEntitlement(NAME,acc.id);
            insert ent;
            
            Entitlement__c custEnt = [SELECT Id, Entitlement__c FROM Entitlement__c WHERE Entitlement__c =:ent.id];
            system.assertNotEquals(Null, custEnt.id);
        
            RenewEntitlementHelper.RenewEntitlement(custEnt.id);
            Entitlement ent1 = [select Id, Renew_Entitlement__c from Entitlement where id =: ent.Id];
            system.assertEquals(False, ent1.Renew_Entitlement__c);
        Test.stopTest();
    }
}