force-app/main/default/objects/Partner_Portal_Label__c/Partner_Portal_Label__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community :</description>
    <label>Partner Portal Box</label>
    <nameField>
        <label>Partner_Portal_Label Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal Box</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Portal_Label__c/fields/Partner_Portal_Tab__c.field-meta.xml
<CustomField>
    <fullName>Partner_Portal_Tab__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Partner_Portal_Tab</label>
    <referenceTo>Partner_Portal_Tab__c</referenceTo>
    <relationshipLabel>Partner_Portal_Labels</relationshipLabel>
    <relationshipName>Partner_Portal_Labels</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Label__c/fields/Permission_Set__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permission Set</label>
    <referenceTo>Portal_Permission_Sets__c</referenceTo>
    <relationshipLabel>Partner Portal Boxes</relationshipLabel>
    <relationshipName>Partner_Portal_Boxes</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Tab__c/Partner_Portal_Tab__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community :</description>
    <label>Partner Portal Tab</label>
    <nameField>
        <label>Partner Portal_Tab Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Partner Portal Tabs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Partner_Portal_Tab__c/fields/Permission_Set__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Permission Set</label>
    <referenceTo>Portal_Permission_Sets__c</referenceTo>
    <relationshipLabel>Partner Portal Tabs</relationshipLabel>
    <relationshipName>Partner_Portal_Tabs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Partner_Portal_Tab__c/fields/Tab_URL__c.field-meta.xml
<CustomField>
    <fullName>Tab_URL__c</fullName>
    <label>Tab URL</label>
    <required>true</required>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Portal_Permission_Sets__c/Portal_Permission_Sets__c.object-meta.xml
<CustomObject>
    <description>NPN : Partner Community : This is a custom object used to maintain SFDC Permission Sets assigned to each portal groups</description>
    <label>Portal Permission Set</label>
    <nameField>
        <label>SFDC Permission Set</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Portal Permission Sets</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

force-app/main/default/classes/portalHeaderControllerPhase2.cls
public class portalHeaderControllerPhase2 {

    public string UserName {get;set;}
    public string CurrentTab{get; set;}
    public boolean isNewsPage{get; set;}
    public string ReferrerURL{get; set;}    
    
    public String usrProfileName {get;set;}
    set<string> permissionSets = new set<string>();
    set<Id> customPermissionSets = new set<Id>(); 
    public List<Partner_Portal_Tab__c>lstTabs {get;set;}
    
    public portalHeaderControllerPhase2(){
        UserName = 'Welcome'+UserInfo.getUserName();
        ReferrerURL = ApexPages.currentPage().getHeaders().get('Referer');
        CurrentTab = ReferrerURL.right(ReferrerURL.length() - (ReferrerURL.indexOf('=')+1));
        if(ReferrerURL.right(14) == 'portalNewsPage') {
                isNewsPage = true;
        }
        usrProfileName = [select u.Profile.Name from User u where u.id = :Userinfo.getUserId()].Profile.Name;
               
        // put a check for Tab which will must cotain a keyword     'Tab'      
        for(PermissionSetAssignment psa :[SELECT AssigneeId,Id,PermissionSetId,PermissionSet.Name FROM PermissionSetAssignment where AssigneeId=:UserInfo.getUserId()]){
            if(psa.PermissionSet.Name.contains('Tab'))
              permissionSets.add(psa.PermissionSet.Name);
        }
        system.debug('check---------'+permissionSets); 
             
        
        for(Portal_Permission_Sets__c PortalPermissionSet : [select Id,Name,(select Id,Name from Partner_Portal_Boxes__r) from Portal_Permission_Sets__c where Name in :permissionSets]){
           //if(PortalPermissionSet.Partner_Portal_Boxes__r.size()>0){
               //put a condition here that user has that box visbility which is inside this Tab.
               customPermissionSets.add(PortalPermissionSet.Id); 
           //}           
        }
        lstTabs = new List<Partner_Portal_Tab__c>([select id, Name, Tab_URL__c, Sort_Order__c from Partner_Portal_tab__c where Permission_Set__c in:customPermissionSets order by Sort_Order__c]);   
    }
        
    public pagereference home(){
        pagereference page = new pagereference('/apex/portalSales').setRedirect(true);
        return page;
    }
    
}